### ISSUE TITLE
Script and Style liquid tag

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#1012]
I would like to suggest that we change `NamedHelperTag` to `NamedHelperBlock` for Script and Style.  So that we can have the ability to add some custom scripts and styles just for a page.

Specifically I am look for `at="Foot"` for script.

For e.g., I need to run some jquery lines with jquery loaded at the bottom of the layout. `<script>$("body")</script>` will not run in a body of a content item.

**Comment by jtkech** [comment]
Yes, by default `script` is an `HelperTag`, so this

    {% script at:"foot" %}

is the same as this

    {% helper "script", at:"foot" %}

But you can use it as an `HelperBlock` by doing this

    {% block "script", at:"foot" %} ... {% endblock %}

**Comment by awyl** [comment]
Ahh... thanks.  Scripts at foot works.

And I think there is a bug, which is probably the same one as #993 that `<resources>` before `RenderBody` are not accounting for these in body part:
```
{% block "style" %}
...
{% endlbock %}
```
and
```
{% block "script", at:"Head" %}
...
{% endblock %}
```

**Comment by jtkech** [comment]
- Yes, in #993 it is because of the special case of the nested layout. The controller view is executed when we do `RenderLayoutBody()` in `ThemeLayout.cshtml` so before the base theme layout.

- But `ControllerLayout.cshtml` is exucuted only when the theme layout call `RenderBodyAsync()`.

- Did you see in #993 my last suggestion to also have a `ControllerResources.cshtml` only for resources tags and which is executed before `RenderLayoutBody()`?

- Then here, not sure i understand because right now through the body part the liquid context is limited so we can't use resource tags.

- But i tried to add a `LiquidPart` to a content type (idem as a `Page`) and this was working.

      {% block "script", at:"Head" %}
          var test = 2;
      {% endblock %}

**Comment by Skrypt** [comment]
```Liquid
{% block "script", at:"Foot" %}
    var test = 2;
{% endblock %}
```

This doesn't work on a Liquid template different than the Layout.liquid one. In fact, I need to test more but the block works but not the at:"Foot".
