### ISSUE TITLE
OpenIdBackgroundTask is not multi instance safe

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#10140]
As part of its execution the OpenIdBackgroundTask will prune certificates which are out of date.  The problem is that as soon as you have multiple instances of OC which are started at the same time, this task will run in parallel and result in errors being reported as instances find and try to delete the same files.  

This appears to be general problem with all background tasks as it does not appear they were designed with multiple instances being ran in parallel.  This is fine for tasks that apply to the local instance only but can cause issues when they access shared resources.

**Comment by jtkech** [comment]
@ShaneCourtrille 

Yes, people should be more aware of this kind of things, thanks for pointing it out  ;)

Through the admin UI, enable the background tasks feature, in the elated page you will see the existing bg tasks and their current settings that you will be able to edit and update. There are 2 advanced settings, a locking timeout (to acquire a lock) and a locking expiration.

If you want an exclusive execution, set the expiration > execution time of your task, and the timeout to something quite low e.g. 100 ms so that when an instance is doing the task, another one will just wait a little and then do nothing.

If you want an atomic execution, also set the timeout > expiration so that the other instance will wait more but will acquire the lock and then also do the task but atomically, only after the previous instance has completed. Note: A little more complex to adjust, if many instances are waiting you may need to increase the timeout without using a too big value.

**Comment by ShaneCourtrille** [comment]
Thanks.. this is exactly what we needed!

**Comment by yusuf-kayikci** [comment]
Is your suggestion valid for custom background task? @jtkech   
I m using Orchard Core on multiple instance and I have my background task(upload some files to ftp) and I want that this task works just one instance so for this I enable redis lock feature then set some values for lock timeout and lock expiration as you said on above but it continue to work all instance.

**Comment by jtkech** [comment]
@yusuf-kayikci Yes, here we only provide atomicity, we only prevent that 2 intances run concurrently, about exclusivity in my above comment, I only meant that while a 1st instance is running the task, a 2nd instance will not wait and will do nothing, but if the task was just completed the 2nd instance will do the job again.

For a complete exclusivity you have to also implement e.g. a simple distributed OwnerShip as described in this [comment](https://github.com/OrchardCMS/OrchardCore/issues/11463#issuecomment-1083570721).
