### ISSUE TITLE
Adding External login requires to change module OrchardCore.Users and OrchardCore.Users.Core. 

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#1043]
Hi, 

I am working on to create module for multi-tenant - application wide external authentication with MicrosoftAccount - App V2 model app. However while working on it I feel like it is not possible to accomplish it with just developing module - without changing orchard source code. 

Finally I changed the code for OrchardCore.Users.Core and OrchardCore.Users Module.

1. UserStore doesn't implement IUserLoginStore<TUser> hence, I had to change UserStore.cs 
2. Added ExternalLoginIndex and described it on UserIndex.cs - OrchardCore.Users.Core
3. Modify module OrchardCore.Users to add ExternalLogin and ExternalLoginCallback actions on AccountController.- as per Asp.net core samples.

But, change in OrchardCode source means - I could not use all awesome NuGet packages of OrchardCore.

Is it possible to achieve external authentication like, Microsoft, Google, Facebook, Twitter by developing module and without modifying source code OrchardCore?

**Comment by YaoaY** [comment]
I think you don't need to change OrchardCore source code,
All these things can be done in your custom module just like what `OrchardCore.Users` module does.

- Implement IUserStore(and IUserLoginStore e.g..) instead of changing `UserStore.cs`.
- Add `ExternalLoginIndex` in your module,and use them in `YourUserStore`.
- Write your `AccountController` and views.

Then don't forget register these services in `Startup.ConfigureServices`

> services.AddScoped<UserManager<IUser>, MyUserManager>();
services.AddScoped<IUserStore<IUser>, MyUserStore>();
services.AddScoped<IUserService, MyUserService>();

Use AddScoped instead of TryAddScoped to ensure that the previously registered services are replaced.

#1023

**Comment by ns8482e** [comment]
I don't want to rewrite the UserStore and OrchardCore.Users module and maintain a separate copy. I really like to reuse UserStore and OrchardCore.Users module out-of-the box.

Is it possible to reuse and extend UserStore and AccountCotroller of OrchardCore.Users in my custom module by reusing all the functionality provided by Users module and configure External login per tenant in Startup.cs?

**Comment by sebastienros** [comment]
We can always improve the module. Please provide a PR if it's just implementing more common interfaces. It can also be part of specific features that users can enable if it's adding complexity that is not necessary and could hurt the system in terms of perf.
