### ISSUE TITLE
Distributed - Feature state not syncing

### ISSUE THREAD

**Issue by markgould** [OrchardCMS/OrchardCore#10433]
### Describe the bug
When running multiple instances in 1.0.0 (in my case, running in AKS with two containers), enabling/disabling features can cause issues and don't seem to sync between instances. I've looked and I didn't see anything specific that has changed since 1.0.0 that may address this.

When I enable a feature, it refreshes the page showing it was enabled, but shows it disabled. Refreshing several times and depending on what instance you are routed to, you'll either see the feature enabled/disabled.

I also happen to be running in multi-tenant mode

### To Reproduce
1. Run multiple instances of OrchardCore in multi-tenant mode with a distributed cache
2. Enable "Forms" feature (but probably any feature will do)
3. See that Feature shows disabled
4. Refresh page several times noting the status each time

### Expected behavior
Feature state should sync between instances

### Screenshots
![image](https://user-images.githubusercontent.com/2712328/136548665-934bb835-32a5-4105-95a0-d2710c772963.png)

Refreshed and it is enabled:
![image](https://user-images.githubusercontent.com/2712328/136548982-6a97cb60-4bfb-4684-ae39-cf353f306858.png)

Refresh a few more times and it's disabled again:
![image](https://user-images.githubusercontent.com/2712328/136548919-75a90251-16b5-4be5-b80d-dd73d594b30f.png)

**Comment by markgould** [comment]
I think I found a temporary workaround - going into the tenants screen on the default tenant and reloading the specific tenant the feature has been enabled/disabled on.

**Comment by deanmarcussen** [comment]
Are you using the redis feature with a redis server between them?

**Comment by jtkech** [comment]
@markgould 

Yes, when you have a concrete distributed cache different things are kept in sync, e.g. cached settings managed by our `IDocumentManager`, front end cached data managed by our `IDynamicCacheService`.

But not all automatically, for other things you have different features, e.g. by default our recipes enable the `OC.Contents.FileContentDefinition` feature to store Content Definitions in a local file, so to keep them in sync you need a recipe that don't enable this feature so that they are stored in the shared database.

When you enable / disable a feature the related tenant is released and then re-built, so to keep tenant states in sync you need to enable the `OC.Tenants.Distributed` feature.

But to make this working you first need a stateless config, by default tenant / shell settings are persisted in local files, so you need to get them from a shared store e.g. the database or a blob, this by using in your main app startup one of the following extension `AddDatabaseShellsConfiguration()` or `AddAzureShellsConfiguration()`, e.g.

            services.AddOrchardCms()
                .AddDatabaseShellsConfiguration()
                .AddSetupFeatures("OrchardCore.AutoSetup");

And configure the related setting e.g. in your main `appsettings.json`, look at the related comments in the appsettings of our repo, and the doc https://docs.orchardcore.net/en/latest/docs/reference/core/Shells/#enable-database-shells-configuration

**Comment by jtkech** [comment]
Yes, these keys are related to tenant states

**Comment by markgould** [comment]
Awesome, thank you for the guidance!
