### ISSUE TITLE
Maintain Content Item Id across BagPart ContentItems Not Working?

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#10723]
### Describe the bug
On issue #5653 it appears the intent was to have content item ids on Bag Parts be persistent (i.e. not change). However, as of today, I don't see that it is working / could work. The Bag Part Content Item Id isn't persisted. Before I go and make a static Id using the IdGenerator that doesn't change per "content" item, I wanted to check if it is understood that this doesn't seem to work. The area of the code that seems to try and address this is [here](https://github.com/OrchardCMS/OrchardCore/blob/9ba5a4015b122ec2c2bbae3c864cc86a61f75d1a/src/OrchardCore.Modules/OrchardCore.Flows/Drivers/BagPartDisplay.cs#L72) but again, I don't think it is working anymore.  Reference @deanmarcussen as back in the day you had implemented it but maybe it is no longer desired.

### To Reproduce
Just made a parent content type with a child content type like so:
![image](https://user-images.githubusercontent.com/1848585/142525472-d3ac8846-adf0-4400-ab18-d5a4bd4c37c5.png)

Then I added in a Parent with a couple of children and published it to get this result (it is outputting the child content item id):
![image](https://user-images.githubusercontent.com/1848585/142525855-5d93a7cc-3d01-4ed3-af95-b9d3873a0d24.png)

But every time I Publish the Parent Content Item the child content item ids change:
![image](https://user-images.githubusercontent.com/1848585/142526519-28bab551-7dbf-43e5-ad0f-390032ef5958.png)

### Expected behavior
Based on the issue #5653 I had assumed it would retain it's child content item ids.

Again, it is not to big of a deal to have a static field (like an alias) that autogenerates a unique id every time. Just didn't want to bypass this if the goal was to have child content item ids persist.

**Comment by deanmarcussen** [comment]
They should be maintained I believe. It would break contained item routing if they were not.

@jeffolmstead you can check this by enabling contained item routing on the items. On publish there would be an error about a duplicate route I expect if the ids were not being maintained

**Comment by jeffolmstead** [comment]
@deanmarcussen I have gone ahead and done the following:

1. Added AutoRoute part to the Child content type and checked the "Manage contained item routes"
2. Updated AutoRoute part on the Parent content type and checked the "Allow contained item routing"
3. Updated my "Parent" content item and checked the "Route contained items"
4. Verified that Routing works properly on the child items

Even though routing works, the Child content item ids change:
![image](https://user-images.githubusercontent.com/1848585/143680448-9d9f5421-ba9b-40cf-92ec-509970aa6ea2.png)

I think the AutoroutePartIndex just get's updated every time with the new 'ContainedContentItemId' value when it is published. I tested this and here it is before a publish:
![image](https://user-images.githubusercontent.com/1848585/143680624-cee29449-a91d-4ab6-87cf-96af119c3726.png)

And here it is after:
![image](https://user-images.githubusercontent.com/1848585/143680639-e9b82ea9-09c1-4f3b-9906-dd129784ce9f.png)

**What is strange is that if I do that with a "Taxonomy", the "ContainedContentItemId" stay the same.** This must be something more specific with how the Taxonomy renders parts (i.e. it aligns with what is expected to maintain the content item). When I just use a BagPart / Named Part the content item id's of the child records are lost. 

Look forward to your thoughts.

**Comment by deanmarcussen** [comment]
@jtkech broke it ;)

https://github.com/OrchardCMS/OrchardCore/pull/10166/files#diff-8cb1bb08a36924a45d49022088f8699b3960f7bab3ee596c2825dcfc8c7bea69L42-R44

JT where you change from using `PrefixValue: widget.ContentItemId,` to `PrefixValue: htmlFieldPrefix + '-' + (index++).ToString(),`

Means this code here
https://github.com/OrchardCMS/OrchardCore/blob/bbd6a8bac4f7c5d0ed163051fa9a373ca9450266/src/OrchardCore.Modules/OrchardCore.Flows/Drivers/BagPartDisplayDriver.cs#L71

no longer works.

This code maybe buggy:
https://github.com/OrchardCMS/OrchardCore/blob/bbd6a8bac4f7c5d0ed163051fa9a373ca9450266/src/OrchardCore.Modules/OrchardCore.Autoroute/Handlers/AutoroutePartHandler.cs#L343

when using contained routing, because it should be throwing an error when the content item id changes.
i.e. it should be reporting a validation error when the route is no longer unique. which it should be if it finds a different contentitem id

**Comment by jtkech** [comment]
@deanmarcussen 

Good catch, so we need a dedicated hidden field `ContentItemIds[i]` that will be also posted by the related scripts e.g. when inserting an item, can't right now but I will do a PR asap, unless if you have time to do it in the meantime ;)

**Comment by deanmarcussen** [comment]
@jtkech cool, I think if we go with a second hidden field, it probably only needs to post existing `ContentItemIds` - because a new insert won't need to keep track of them, as it is only to maintain a reference to existing items. Probably.

I didn't check totally why you had changed away from the guid, but sounds like you think it is better to have a second field, rather than tweaking prefixes around again?

**Comment by jtkech** [comment]
@jeffolmstead 

Fixed locally, will do a PR soon. Last things to do related to when we remove / move, in the same container or to a (grand) parent / (grand) child one. That said when dragging an item from one container to another, the item id can't be preserved as it involves more than one FlowPartDriver where the check is done.
