### ISSUE TITLE
When you delete the Taxonomies it is not possible to get it come back

### ISSUE THREAD

**Issue by sergeor** [OrchardCMS/OrchardCore#10786]
1. Create new Blanksite
2. Go to Features and enable the Taxonomies
3. In Content Definition / Content Types edit the Taxonomy
4. Click delete
5. Try to bring it back from enable/disable Taxonomies from Features

It does not return. lost forever.

**Comment by Skrypt** [comment]
The "Create" migration runs only once. And it is appropriate. If you remove intentionally a `Content Type` then it will be lost forever unless you recreate it by hand in this case. I don't think it is an issue. You need to be careful. One solution would be to have a recipe to recreate this Content Type.

**Comment by ns8482e** [comment]
It’s by design 

Content definitions are created by migrations. Once migration has run, it will only run for next update.

Once  content definitions are built you can customize content definitions in admin UI. 

Ideally content definitions should be read only for code based part

see related issue  #4172

Solution is to disable the module and remove entry from migration record for that  module and enable again

**Comment by Skrypt** [comment]
Making these Content Type definitions read-only would need some thought. Having a notification before removing these could also be a different approach that could work.

**Comment by sergeor** [comment]
Thanks for the explanation.

Finally the easiest solution (for me) is to export the recipe for Taxonomy from another project and insert it in the one that has deleted.

But I think for the system  Content Types (like Taxonomy) it would be good if at every enable -and after the migration- to check if the content type is in db and if not to recreate. 

Maybe this will be marked as a feature at some point in the future
