### ISSUE TITLE
Correlate Task should support Liquid AND javascript parsing with separate editors

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10849]
The correlate task now uses the Monaco editor but only supports Script parsing.
We should also add the option the be able to parse Liquid by toggling the parser with a parser selector.
Should default to Script parsing to be backward compatible.

@hyzx86

**Comment by hyzx86** [comment]
I think the ability to switch syntax should not be limited to this one activity, but should define a property type like Elsa, which allows the property to switch between multiple syntax

I have tried to integrate the ELSA source code in my project to enable OC to achieve the same effect, but it has been more problematic to try. Since my current project is not very workflow related, I need to deal with other things for the time being, like the RDBMS mentioned last time

After that I will try to integrate ELSA code again
