### ISSUE TITLE
Setting PreserveCompilationReferences as true gives exception in .Net 6 and Orchard 1.1.0

### ISSUE THREAD

**Issue by vengi83644** [OrchardCMS/OrchardCore#10854]
### To Reproduce
1. Create a decoupled CMS app with .net 6 and Orchard 1.1.0
2. Set PreserveCompilationReferences in the project <PreserveCompilationReferences>true</PreserveCompilationReferences>
3. Run the project

![image](https://user-images.githubusercontent.com/5276778/145553758-00c7d673-937c-46b5-81bd-093a8b68f07f.png)

**Comment by jtkech** [comment]
Fixed in the main branch whose packages are available from the cloudsmith feed

Or wait for the next incoming release to be published on Nuget

Or try to update your app .csproj file with what we now use in our Cms.Web.csproj where we now reference directly the `Mvc.Razor.RuntimeCompilation` package with the condition of a new `RazorRuntimeCompilation` property.

**Comment by vengi83644** [comment]
Thank you @jtkech. The 3rd option is somewhat is OK to us for now.

I will reference that package. But if in future, will I have any problems If we upgrade Orchard Target to next public version?

**Comment by jtkech** [comment]
No because this is what we now do in our sample web app, and what you have to do in your app if you want to be able to have or not razor compilation by conditionaly referencing the package.

If you never reference the razor package, the new default (even in dev mode) will be no razor runtime compilation.

With net6.0 there is also the new hot reload, I tried it a little when it was a preview feature but didn't retry it again ;)

**Comment by vengi83644** [comment]
Thanks so much. I am closing this issue if you don't have any concerns.
