### ISSUE TITLE
Caching of Main Menu Still Querying Database

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#10913]
### Describe the bug
I have used caching of the main menu

```
{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_expires_after: "00:05:00", cache_tag: "alias:main-menu" %}
```

As defined in the [Liquid Shape documentation](https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#shape_cache) but when I have my SQL profiler hooked up it still is querying with this query (every time):

```
SELECT TOP (1) [OrchardCoreENS_Document].* 
FROM [OrchardCoreENS_Document] 
     INNER JOIN [OrchardCoreENS_AliasPartIndex] AS [AliasPartIndex_a1] ON [AliasPartIndex_a1].[DocumentId] = [OrchardCoreENS_Document].[Id] 
WHERE ([AliasPartIndex_a1].[Alias] = 'main-menu')
```

I have also tried:
```
{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_tag: "alias:main-menu" %}
```
But it too makes the SQL calls every time.

So it seems either I am misunderstanding how the caching mechanism on the shape works or something is going wrong. Look forard to anyone's thoughts.

**Comment by deanmarcussen** [comment]
I am guessing you are testing this in development?

We have a site setting for cache modes, under general settings, which is defaulted to `FromConfiguration`, so disabled in development, enabled in production.

Pr was here https://github.com/OrchardCMS/OrchardCore/pull/6390

We need to add a note to the docs, re this. If you could take the time to add a short note @jeffolmstead that would be great.

I know we discussed it at the time, but I cannot remember why `FromConfiguration` was the default. I suspect it was because it was blocking people from using the debugger.

**Comment by jeffolmstead** [comment]
@deanmarcussen my apologies on this taking forever to get back to. I have been on non-Orchard projects for too long and don't have a benchmark for checking this. I am quite sure it was in development environment (hence the no caching) but I won't have time to confirm or modify documentation. Wish I could be on this project much more than I have been for the past 2 years.
