### ISSUE TITLE
In a SaaS setup, how can the SaaS admin/owner manage the tenant features?

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#10962]
### Is your feature request related to a problem? Please describe.
In a SaaS environment, the service owner may not want the tenants to be able to manage their feature. Instead, I want to manage the features for each tenant so that I control what they have access too.

### Describe the solution you'd like
It would be nice to be able to disable the `OrchardCore.Features` module "At least the UI part" so that the tenant is unable to enable/disable features.

I am aware of the `OrchardCore.Tenants.FeatureProfiles` feature which allows you to define rules for which feature to include/exclude for the tenant. The issue with that is that you can only have a single profile per tenant. What if one tenant should have access to the standard profile, plus access to module A, B and C? Another solution may be to allow the user to select multiple profiles for one tenants to allow more flexible for reusing profiles.

### Describe alternatives you've considered
Revoke access to the features using permissions from a recipe.

**Comment by deanmarcussen** [comment]
Permissions / feature profiles are the good approaches here.

disabling the features feature would make the site unusable / upgradable very easily.

as a saas administrator wanting to restrict the tenant you should just not give them admin rights. Otherwise they’ll still be able to enable features with recipes , upgrade their privileges with workflows etc
