### ISSUE TITLE
Fluid template if null comparison stopped working properly when updating on 1.2 (.NET 6) from 1.0

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#10991]
### Describe the bug
This is the `if` condition
![not-null](https://user-images.githubusercontent.com/1761249/148651581-9bddc1aa-c452-47b7-b08b-be42c2ba27d8.png)

The `EmbeddedAddress` property is clearly null

![not-null-3](https://user-images.githubusercontent.com/1761249/148651606-9e86cbc3-4730-4415-bba2-364cb006c85b.png)

But the result is

![not-null-2](https://user-images.githubusercontent.com/1761249/148651643-e4b0bb8f-eef6-4bcd-abd5-a4a5fdd65d2a.png)

I also tried using `nil` as comparison but the result is the same

![not-null-4](https://user-images.githubusercontent.com/1761249/148651787-d99ac4c6-fab3-4bbd-92e7-5edc5606a414.png)

**Comment by sebastienros** [comment]
Since 1.1 and OC is using Fluid 2.0 which is more strict about the Liquid specification. Main changes are that 
- math operators are not supported anymore, use filters like `|plus :1` instead of `+ 1`
- grouping is not supported anymore, so `(a or b) and c` is not valid
- `null` isn't a thing, in your case do `{% if address == blank %}`. There is also `empty` that has a different meaning
- whitespace management around tags is also following the spec, e.g. `{%- if ... -%}`
- much faster
- new features

**Comment by dodyg** [comment]
OK thanks. TIL about `blank` and `empty`.
