### ISSUE TITLE
Forward Headers for Reverse Proxy

### ISSUE THREAD

**Issue by Sironheart** [OrchardCMS/OrchardCore#1101]
Right now it is not possible to use a reverse proxy or load balancer like NGINX... or it is not documented yet. Do we need Forward Headers Dependency to add?

**Comment by sebastienros** [comment]
Could you explain what makes you think it is not supported? How can I repro the issue?
Is it specific to Orchard, Kestrel, or both?

**Comment by awyl** [comment]
I just looked at the code a bit, not sure that I read the right place.  But it seems that at the moment, orchard only looks at the Host header. https://github.com/OrchardCMS/OrchardCore/blob/cc61d1dd47d5142607f3817f81ef8584ee228361/src/OrchardCore/OrchardCore.Modules/Extensions/RunningShellTableExtensions.cs#L20-L22

I think it would be better if it first look at `X-FORWARDED-HOST`.  So for example, when you have NGINX in front of App Service on Azure, you can set the `Host` header to the app url, and `X-Forwarded-Host` to the tenant hostname.  Otherwise Azure cannot probably route to the current website even then tenant hostname resolve to the correct IP.

But I think there is some reason to use the Host header because the comment:
https://github.com/OrchardCMS/OrchardCore/blob/cc61d1dd47d5142607f3817f81ef8584ee228361/src/OrchardCore/OrchardCore.Modules/Extensions/RunningShellTableExtensions.cs#L11

**Comment by sebastienros** [comment]
I assumed it was an issue related to tenant matching, but I want to be sure that's what @Sironheart means. 
It could also impact how we generate fully qualified urls (when we generate emails for instance).

I think Kestrel has an option to reassign `X-Forwarded-Host` to `Host` automatically. It could also be part of an Orchard option so that anyone can change this as part of their application configuration.

**Comment by Sironheart** [comment]
what @awyl said, is just what I meant. I tried to make OrchardCore available from behind an nginx reverse proxy via "dotnet publish" and "dotnet run" and just got an "could not redirect" header or something. Using Kestrel is documented by Microsoft, but I just wasn't able to reproduce it with OrchardCore.

I assume @sebastienros is on the right track. I used [this](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction) documentation by Microsoft, so I guess it is pretty easy to reproduce my error :) Would try to solve this by myself, just haven't used C# in decades ;)

**Comment by awyl** [comment]
How are we going to tackle this?

I will need this soon.  I can help with the implementation if needed.

**Comment by Sironheart** [comment]
I do not have the time to implement this and reintroduce myself to C# and .NET Core... sorry, not the biggest help :/

**Comment by sebastienros** [comment]
Isn't setting `proxy_set_header Host $host;` in the nginx configuration the way to handle it?

**Comment by sebastienros** [comment]
Also we can just call `httpRequest.Host` which is doing exactly `Headers["Host"]`

**Comment by awyl** [comment]
In Azure, you need the Host header to identify your web app.  And the actual domain you will need to associate with nginx vm.  So e.g.,

`www.example.com` point to nginx vm.
`orchard.azurewebsites.net` point to the actual web app.

So when a request comes in with `Host: www.example.com`, Azure routes it to nginx.  Then if nginx set the proxy `Host` header to `www.example.com`, Azure wouldn't be able to lookup the web app because none of the web app is registered with this hostname.

So the only way I know is to set the `X-Forwarded-Host` header to `www.example.com` and the `Host` header to `orchard.azurewebsites.net`.  But then the web app has to be aware of the `X-Forwarded-Host` header.  Actually any header will do since Azure web app doesn't do anything if `X-Forwarded-Host` is set.

This is what I figured out a few years back.  Perhaps there are other solutions now I am not aware of.

**Comment by sebastienros** [comment]
I made a PR, which is reading `X-Forwarded-Host` first then `Host`. That should take care of the issue. Would be great if you could test that is solves your issue.
