### ISSUE TITLE
Role can't see the items from a non-creatable type

### ISSUE THREAD

**Issue by ruisdias** [OrchardCMS/OrchardCore#11031]
### Describe the bug

I have created a new role to manage just one type on the CMS, so the user will see the items just from that type.
But if the type isn't creatable, It doesn't show the menu for the content, even though, it's already content created before the type turned to be not creatable.

The point is:
When I want for um role just to manage the items already existent in the CMS, without being able to create new ones, it can really see the content.

### To Reproduce
1. Create a type being creatable;
2. As the admin, create an item from that type;
3. Set the creatable setting to off from that type;
4. Create a role, able just to manage this new type;
5. Associate it to a user, with just this role;
6. Login with the new user;
7. you won't see the content menu;

### Expected behavior
You should be able to see the content if the content type is listable;
Creatable or no, if there is content you must see it;

**Comment by Piedone** [comment]
The issue is [here](https://github.com/OrchardCMS/OrchardCore/blob/36a84469842afb434aeca283ffd2670d32b97c25/src/OrchardCore.Modules/OrchardCore.Contents/AdminMenu.cs#L70). Both the New menu and the Content Items menu use the same list of content types filtered for Creatable ones only. However, the latter should indeed use Listable ones.
