### ISSUE TITLE
Feature to re-index content items

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11086]
### Is your feature request related to a problem? Please describe.
When importing many content items using the import feature, the indexes are not populated. 

### Describe the solution you'd like
It would be nice to add a feature that would allow the admin to select which content type to re-index, and the process will simply loop through all the content item and saves each one to force the indexes to process each record.

If there is not objections or grouches with this approach I may be able to add a feature in content-management "or other modules" that would allow this

### Describe alternatives you've considered
Nothing yet.

**Comment by Piedone** [comment]
Hmm, this looks more like a bug since those items should be indexed without further intervention (there is a reindexing feature already that'll reindex all items).

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/8316

I'll leave this open as what @Piedone says is correct, all items are reindexed when importing, so not sure if you're reporting a bug, or just something that isn't happening how you think it should.

I assume you're talking about sql / YesSql indexes here, not lucene

**Comment by CrestApps** [comment]
Yes I am talking about sql tables that are called indexes. I am not sure if this is a bug. I may have imported the data before enabling the features that register the indexes. 

Being able to manually re-index will allow one to re-index when the index is not sync with the data like when the index is created after data was generated.

**Comment by Piedone** [comment]
Ah, I totally thought about Lucene. However, SQL indices should be updated as well.

**Comment by ns8482e** [comment]
Related YesSQL issue https://github.com/sebastienros/yessql/issues/406

**Comment by deanmarcussen** [comment]
Closing as duplicate. It’s not a yes sql issue, it’s to be resolved in orchard.

calling save rebuilds index @ns8482e

**Comment by ns8482e** [comment]
Calling save for each document from migration when new feature is enable is not good option when reindex is required for new feature

**Comment by ns8482e** [comment]
So it’s something yessql to provide apis

**Comment by Skrypt** [comment]
The IndexingProviders come from Orchard Core implementations. Each IndexingProviders have their own business logic so it is something that should be done in Orchard Core for that matter.

**Comment by Skrypt** [comment]
Here the issue happens when someone enables the SQL Indexing feature after creating some content items. These content items will not be automatically added in the Index tables it populates. This is because IndexingProviders only index content items that are eventually published. We did not provide a process to populate these Index tables yet because you can also do it using pure SQL. Depending on the size of the database this is a process that could result in a request timeout so this could be implemented as a background task as we do with Lucene. We also need to have this working with a controller action that could resume the process with an AJAX call if a request timeout happens as we had in Orchard 1.
