### ISSUE TITLE
Startup classes are loaded twice in OrchardCore.Tests

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#11089]
The OrchardCore.Contents.Startup are loaded twice when run test case ShouldCreateAndPublishExistingContentItem from the official OC repo. Actually all test cases which use SiteContext has the same issue. 
Seems this behavior is different with the regular project. Is the test project specialized? 

My case is that I register a kafka event handler in Startup. In the test case, the handler is registered twice so that an event will be handled twice too. But actually an event only is required to be handled once.

**Comment by HengzheLi** [comment]
I think I figure out the reason. 

The test project will create a tenant with a GUID as a name. Then there are two tenants in the tenants.json file. When OC initials the shell context, it not only init the Default tenant but also the created GUID named tenant. So the Startup classes are loaded twice for different two tenants.

**Comment by HengzheLi** [comment]
I was wrong after I re-debug the code.

I found that the tenant's shell is initialized twice. When call to the tenant setup REST api to setup a new tenant. The api would init the tenant's shell scope. And this is the first time of Startup classes are loaded. And another one is that the deferred task which is ran in BeforeDisposeAsync. It creates another new shell scope and the startup classes are loaded again in this scope.

I found this PR https://github.com/OrchardCMS/OrchardCore/pull/7158 seems like BeforeDisposeAsync is used to do some cleaning task. But just wander why BeforeDisposeAsync would be called during a tenant setup?

**Comment by sebastienros** [comment]
Is the issue just in tests?

**Comment by jtkech** [comment]
> The api would init the tenant's shell scope. And this is the first time of Startup classes are loaded

This is when building a shell container that the module / feature startups `ConfigureServices()` are called, not when building a shell scope,  the startups `Configure()` are called when building a shell pipeline on a first request. That said, before building a shell container we build a temporary one with a `MinimumShellDescriptor` just to be able to retrieve the shell descriptor (from the database by default) that is required to build the shell container. So some `ConfigureServices()` are called twice but only on a minimum set of features.

>  But just wander why BeforeDisposeAsync would be called during a tenant setup?

In the `Shellscope.BeforeDisposeAsync()` we first execute before dispose delegates, we always have at least a registered delegate (see below) to commit the store that does a `_session.SaveChangesAsync()`, here we don't create a new scope. Then if there are deferred tasks we execute each one in an isolated shell scope **which happens if we create contents in a setup recipe**, but here also creating a new shell scope doesn't call any `ConfigureServices()`.

https://github.com/OrchardCMS/OrchardCore/blob/5da32127932fbacbc476996acbef8830cab0599f/src/OrchardCore/OrchardCore.Data.YesSql/OrchardCoreBuilderExtensions.cs#L130-L141

**Comment by sebastienros** [comment]
@jtkech close or keep open?

**Comment by jtkech** [comment]
Yes, I think we can close it

@HengzheLi feel free to re-open if you have other questions
