### ISSUE TITLE
[Documentation] Recipes should be ignore for publication

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1124]
see https://github.com/OrchardCMS/OrchardCore/pull/1114

**Comment by sebastienros** [comment]
I assume I wanted the documentation to mention somewhere that when creating a recipe the dev should not mark it as published content. Probably when we have some doc on Theme development.

**Comment by jtkech** [comment]
@sebastienros i think you can close this one. 

- At some point, some theme recipes were just under the web app and we needed to add some `<CopyToPublishDirectory>` for these recipes in the web app`.csproj` file.

- Then, when copying the recipes files to their related themes, i think that VS updated their `.csproj` files as they were defined in their original project. Otherwise this not done automatically by VS.
