### ISSUE TITLE
Troubles accessing the Html property of a MarkdownPart in Liquid Syntax

### ISSUE THREAD

**Issue by piskernik** [OrchardCMS/OrchardCore#1127]
There is probably an easy solution, I just don't get it...
What I've tried sofar (within a for loop in Liquid Syntax) is shown below:
- These examples give at least the unconverted markdown: 
`<p>{{ feature.MarkdownPart.Markdown | markdownify }}</p>`
`<p>{{ feature.MarkdownPart.Markdown }}</p>`
`<p> {% display feature.MarkdownPart %} </p>`
- Whenever I access the Html Property (as I understood from the documentation) it returns nothing:
`<p>{{ feature.MarkdownPart.Html }}</p>`
`<p> {% display feature.MarkdownPart.Html %} </p>`
`<p>{{ feature.MarkdownPart.Markdown.Html }}</p>`
Any help or reference to a document would be nice...

**Comment by piskernik** [comment]
This is, what I get, when I evaluate {{ feature }}:
{ "Id": 0, "ContentItemId": "48cfayncybm1fxxtej6cg2vgdn", "ContentItemVersionId": "46r9ba2wj5tpe46ma079rkxnxb", "ContentType": "BlogPost", "Latest": false, "Number": 0, "Published": false, "ModifiedUtc": "2017-10-24T06:15:27.6197777Z", "PublishedUtc": null, "CreatedUtc": null, "Owner": null, "Author": "admin", "BlogPost": {}, "AutoroutePart": { "Path": "title/title", "SetHomepage": false }, "MarkdownPart": { "Markdown": "1. Test\r\n2. Test\r\n3. Test\r\n\r\nAbsatz \r\n\r\nAbsatz\r\n\r\n\r\n" }, "TitlePart": { "Title": "Title" } }

**Comment by sebastienros** [comment]
In this case you can't just use the content as is as it's in markdown, you should just let the driver render the part by itself, and to do that you need to access the shape directly. I will give you the solution later when I have more time available.

**Comment by jtkech** [comment]
@piskernik as i remember so not sure of all.

A shape is a dynamic object built by its related driver and rendered through a template view. Here some examples of model properties we could have in different contexts, but not always.

1. Model is a shape
2. Model.Content is a shape
3. Model.ContentItems is a collection of shapes (e.g when rendering a `ListPart`)
4. Model.ContentItem is a `ContentItem`
5. Model.ContentItem.Content is a `JObject`
6. Model.ContentItem.Content.MarkdownPart.Markdown is a string
7. Model.Content.MarkdownPart is a shape (tied to a `MarkdownPartViewModel`)

You can use `{% display %}` on shapes but not on other properties. If you use .6 you have an unconverted markdown string. With .7 you have a shape meaning that the related driver has been executed. So here you could use `Model.Content.MarkdownPart.Html` but you can't because of the following.

For some types we need to register them to access their properties. This is done automatically for some types and for the current `Model`. But here `Model.Content.MarkdownPart` is a sub model / shape whose object type `MarkdownPartViewModel` is not registered.

In this case, the solution is to use `{% display Model.Content.MarkdownPart %}` and then, but only if you need more customization, also override the sub template e.g with a `MarkdownPart.liquid` file in your theme and where you can access `Model.Html`.

But i think you don't want to override the `MarkdownPart` template, you just want to display it where you want. So first, in place of iterating on content items, you would need to iterate on item shapes and use `{% display %}` on them. This if you want a custom global rendering of your collection, otherwise you could let the regular template (if it exists) doing its job (as the `ListPart` template do).

Then you need to override the template view of your feature item content type. See in `TheBlogTheme` for blog post type as an example. Finally, in this content type view use where you want something like this `{% display Model.Content.MarkdownPart %}`. 

But first, we need more infos on how you build and you get your `feature` collection.

**Comment by piskernik** [comment]
Thanks for the information & help!
I am using "The Agency Theme" and made an additional named part called "Features" with "BlogPost" as allowed content. I'm iterating the collection in `Content__LandingPage` like this:
`{% for feature in Model.ContentItem.Content.Features.ContentItems %}` (This is a collection of shapes, correct?)

So, what I understood is, that I need a Liquid file in the View folder of my Theme with the name `Content-BlogPost.liquid` (like in "The Blog Theme").  Because I want not to override the MarkdownPart I need to define just
`{% display Model.Content.MarkdownPart.Html %}`.

How can I invoke the view now in the `Content__LandingPage`template?
The simple idea of `{% display feature %}` is not working.

I'm somehow lost:-(

**Comment by sebastienros** [comment]
@jtkech I think `Model.ContentItem.Content.Features.ContentItems` is a collection of JObjects, as @piskernik could ouput the full json, and also because this is what the default tempalte (Content__LandingPAge) uses for all the sub items, which is replicated here.

I think the easiest way for a user would be to be able to evaluate markdown in this case, but we don't have a filter that does that, so that's a TODO. In the meantime you should use the HtmlPart so there is no conversion to do. Next I will look into how to access and render the corresponding shapes. Stay tuned.

**Comment by sebastienros** [comment]
@jtkech 

`ShapeAccessor` (liquid) and `Shape.Named` (razor) are equivalent and let us access a sub shape. So here from the `Model.Content` shape we need to access the part "named" `Features`. But the type of the part is `BagPart` and the content has many parts of this type. When you do {% display Model.Content.BagPart %} it displays the first one of this type, which is the Menu Items.

{% display Model.Content.Features %} won't work because we look at the type and not the name. So I will change it to lookup for the name. For the ones we use today, the name is the same as the type so it won't break. I might have to add more metadata to a shape though, but that's fine.

**Comment by piskernik** [comment]
The HtmlPart works. Certainly a filter like `markdownify` would make the use of the MarkdownPart very easy.

**Comment by jtkech** [comment]
@sebastienros @piskernik 

- Just retried based on the additional infos. Yes `Model.ContentItems` could be shapes but here `Model.ContentItem.Content.Features.ContentItems` is a collection of JObjects.

- So, i started with `Model.Content` which is a shape, then i couldn't iterate on `Model.Content.Items` because there are sub shapes of the `BagPartViewModel` type which is not registered.

- Then, i tried to access the `Model.Content.Features` but as you said we check the metadata `Type` and here this is the metadata `Prefix` which is equal to `Features`. So maybe after checking the `Type` we would need to also check `Prefix`.

- Anyway, `Model.Content.Features.Content` would be a JObject and `Model.Content.Features.ContentItems` would be a collection of `ContentItem`. So, here there is no `BagPart` shape with a markdownified text, this is in `BagPart.cshtml` that `BuildDisplayAsync()` would be used to build shapes for all items.

**Some unordered thoughts**

- Because the `Agency` theme doesn't use shapes that we could override hierarchically, in the main template we can't access the properties of some sub shapes whose type is not registered.

- Maybe we would need a liquid tag to build some shape as done by `BuildDisplayAsync()`, maybe good to be able to do this from a given part.

- Finally, as said above we need to also check the metadata `Prefix` to access sub `Items` shapes.

**Comment by sebastienros** [comment]
Same conclusions, I already have something, almost done

**Comment by jtkech** [comment]
Cool 👍

**Comment by piskernik** [comment]
Awesome! Thanks for acting on this idea, I really appreciate it.
