### ISSUE TITLE
Publish fail on 3499

### ISSUE THREAD

**Issue by SperoSophia** [OrchardCMS/OrchardCore#1164]
Updated the nuget from 3383 to 3499 on a azure hosted project.
there are issue with the flow.edit.cshtml on publish but build does not raise any issues.

**Comment by sebastienros** [comment]
Currently trying to repro, I see some issues but related to OrchardCore.Demo, not Flow. Can you provide the exact error message you see?

**Comment by SperoSophia** [comment]
When i publish via VS2017 Pro, i get the Publish fail error.

If i down grade to 3383 it works, just upgraded to 3499 to reproduce it, and the errors are back.
I can run it (debug and release locally), not sure what actually happens in the publish step, might be a VS issue, but the nuget downgrade seems to fix it.

![image](https://user-images.githubusercontent.com/3510805/32348210-f5b48b70-c00a-11e7-8c0a-c36f71854322.png)

**Comment by sebastienros** [comment]
Did MvcRazorExcludeRefAssembliesFromPublish fix your error?

**Comment by SperoSophia** [comment]
no, that only fixed the whitescreen i had earlier not the publish error, ( different subject :P )

**Comment by sebastienros** [comment]
FYI the publish step will try to compile the views, so if there is any compilation issue in a view this will fail. Issue is that I can find any problem on my side.

It looks like the file is in your project. Maybe you copy pasted it at some point and we changed something that breaks it now. I see `IShape doesn't contain ...` messages. Try to use a `dynamic` modifier instead of `var` where it fails, this is a change we did recently. Or get the new version of this file, or just delete it if you don't customize it.

**Comment by SperoSophia** [comment]
The error seems to be with BagPart.Edit.cshtml, a file within one of the Orchard modules.

**Comment by sebastienros** [comment]
Why is it mentioning your project?

![image](https://user-images.githubusercontent.com/1165805/32351626-4544043e-bfdb-11e7-9c15-66ed538ff437.png)

**Comment by SperoSophia** [comment]
not sure.

![image](https://user-images.githubusercontent.com/3510805/32351684-2cd15e70-c016-11e7-823c-27cd07be70aa.png)

**Comment by sebastienros** [comment]
delete the packages folder, and rebuild

**Comment by SperoSophia** [comment]
Neat, that seems to resolve it.
