### ISSUE TITLE
How to do query and show it on using template

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1178]
I have this

```
select b.Content
from ContentItemIndex a
inner join Document b
on a.DocumentId = b.Id
where a.ContentType = 'Project' and a.Latest = 1
```

It works but I cannot display it

```
 {% assign allProjects = "AllProjects" | query %}
      {% for p in allProjects %}
         {% display p %}
      {% endfor %}
```

This is as far as I can go. I can see the objects properties being rendered but ```{{p.Content.Id}}``` won't work.

**Comment by sebastienros** [comment]
First, you have issues in the query. What you are returning right now is just a string containing a json document, you can't do much with it.
There are two kind of results to return from a query:
- values like strings, integers, including computed ones
- documents, which are Json documents that are deserialized from the `Content` field in the `Documents` table

If you have to compute the archives count for instance it would be the first case

In your case you want documents, and there is a simple way to do it, just select the document ids you want, and check the `Return documents` option in the query.

```
select DocumentId
from ContentItemIndex
where ContentType = 'Project' and Published
```

If you test this query, it will return a set of document ids

Then in your template, you are currently calling `display` on a content string. The `display` tag only accepts shapes. You can build a shape using `build_display` on a content item. The good thing is that the previous query is returning Content Item documents, so this is what you need.

Also because you get a Content Item you now are able to do `p.Id` or `p.TitlePart.Title` if you have a Title Part.

```
 {% assign allProjects = "AllProjects" | query %}
 {% for p in allProjects %}
    {% display p | build_display: "Summary" %}
 {% endfor %}
```

**Comment by jtkech** [comment]
@dodyg @sebastienros 

I could get it working

- First, in the agency themes, projects are embedded in the landing page, so i created 2 items of type `Article`, and then used this query.

      select DocumentId
      from ContentItemIndex
      where ContentType = 'Article' and Published = true

    **Don't forgot to check `Return Documents`, otherwise you will only get the document id**

- Then in the landing page template i used.

      {% assign articles = "Articles" | query %}
       {% for article in articles %}
          {% display article | build_display: "Summary" %}
       {% endfor %}

- **But at this point it was not working because articles are `JObject`**. So, i updated the `build_display` filter to also check if it is a `JObject`, and then try to convert it to a `ContentItem`.

**Then it works, i will do a PR** for the `build_display` to also allow a `JObject` input.

**Comment by dodyg** [comment]
Thanks. It works now.
