### ISSUE TITLE
Ability to enable/disable feature for Tenant from Host

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#11870]
### Is your feature request related to a problem? Please describe.
I want to create a tenant with the following features disabled `OrchardCore.Features` , `OrchardCore.Workflows` and `OrchardCore.Deployments`. I have a SaaS environment and I want to be able to manage the tenant's features from the host.

### Describe the solution you'd like
Create a new feature that would allow the host admin to enable/disable features for tenants.

**Comment by ns8482e** [comment]
@CrestApps IMO the tenant admin should be able to enable/disable feature for his tenancy and not the host admin

**Comment by ns8482e** [comment]
@CrestApps it just the feeling restricting but really nothing prevents tenant admin to enable/disable any feature

**Comment by CrestApps** [comment]
This request is just to provide a UI for the host to be able to enable/disable features for some tenants. It has nothing to do with restricting features from being used by a tenant. Restricting feature is done using FeatureProfile.

**Comment by sebastienros** [comment]
Suggestion: Create a feature that lets you run a recipe (with code editor) for any tenant.

**Comment by jptissot** [comment]
> Suggestion: Create a feature that lets you run a recipe (with code editor) for any tenant.

I did this as part of this pr: https://github.com/StatCan/StatCan.OrchardCore/pull/207

**Comment by CrestApps** [comment]
@sebastienros I think that is a great idea. It may be good to also allow the host to be able to execute recipes for a tenant. But I think we first need a way to allow other modules to inject code into the list of tenants so next to each tenant we could have button like `Manage Features` and `Recipes`. we can even make the `Recipes` button as a drop down button that would allow for `Importing Recipe` and `Executing Recipe`. The ability to inject code into the list of tenants is done in PR#11869. If #11869 is merged, I'll submit a continuous PR that would allow for executing and importing recipe.

**Comment by MikeAlhayek** [comment]
@sebastienros can this be part of 1.5 release?

**Comment by Skrypt** [comment]
Just a thought here. I think we should start considering if we want the default tenant to always be the "management" tenant for all these tenants. Right now, I understand that we have a Tenant module that allows doing that from the default tenant. Though, maybe we should start considering having a dedicated tenant for managing globally everything in OC. This way it could be secured independently. 

Here, I'm thinking about this because not everyone will need to use multiple tenants. And in that case, we are maybe adding features to the default tenant that are not needed for the people that are using OC with a single tenant. It means somehow that we need to make the default tenant aware that it can need to create scopes for management which is something that could be needed without having a single tenant to start with.

**Comment by Piedone** [comment]
How would this be different than the current Default tenant? Currently, if you don't use multiple tenants, then nothing should bother you. If you do use multiple tenants, then you enable the corresponding features on the Default tenant and thus it serves as the dedicated special management tenant.

**Comment by Piedone** [comment]
More to the point of the original issue here: I'm not sure we want to surface pieces of another tenant's dashboard on the Default tenant. I think a better approach is to use the dashboard of the given tenant, and gain access to that. We have created [a module for this](https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.Admin.Login/Readme.md) but I guess this can be implemented even better.

**Comment by Skrypt** [comment]
See, the module there you have built is for adding some specific authentication for managing tenants. But, I think that ultimately if we want to manage all tenant's features we should not rely on an existing tenant that can also be used for building an actual website. Of course, right now the tenants' module is helpful where it stands, but the day we are starting to add more features we will probably need to start thinking about a dedicated management UI for all things tenants.

**Comment by Piedone** [comment]
> Though, I'm concerned about what it will lead to eventually if we merge this one.

This is my point too.

**Comment by MikeAlhayek** [comment]
@Skrypt @Piedone if we want to create an independent instance to manage tenants "this tenant could even a tool with no UI for all we care," we would have to restructure things which may be a bigger lift including some breaking changes. This would mean to also move the Tenants module because "Adding/Editing" tenants would also have to be moved including Tenant feature profiles. @jtkech you may want to shed some light here.

But this would also mean we would have to change the "DefaultTenant" flag on the feature attribute "which is a core concept." In fact, we would have to drop the whole concept behind having a default tenant. Which begs the question, why go through all that trouble just to shift everything? 

Maybe you can think about it differently and keep the default tenant to manage other tenants and create another tenants to do anything that isn't tenant management related. In other words, if you are not using Saas, everything is default tenant and everyone is happy. Maybe we should add a new flag called "MultiTenancyOnly" flag to allow us to prevent features from showing up in the absence is MultiTenancy. 

I think we should keep everything into a default and add "MultiTenancyOnly" flag. Also maybe in the future take this one step further and allow running multiple default tenants. Meaning maybe we allow the user to create multiple umbrellas or teants so default1 would allow x amount of tenants and default2 would allow y amount of teants. 

IMO, either way, this PR would still allow you to manage features where it's enabled and should belong here.

**Comment by Piedone** [comment]
I'm not arguing for a new management UI or a new way to offer that instead of the Default tenant. Instead, I'm arguing not to put anything in the Default tenant's dashboard that's otherwise available in the sub-tenant's (because then eventually we'll want to do that for everything, not just the Features page), rather, provide a way to gain access to the sub-tenant's dashboard proper.

**Comment by MikeAlhayek** [comment]
@Piedone if we have a dashboard, we would need an admin account for every tenant and I don't think we should. with the presented approach in the PR, we don't really need that. We simply run the `OC.Features.Admin` in the scope of a tenant instead.

**Comment by jtkech** [comment]
> @jtkech you may want to shed some light here.

Sorry I did not have enough time to think about it again, in the meantime maybe refer at some of my comments in the old PR #11869 e.g. https://github.com/OrchardCMS/OrchardCore/pull/11869#issuecomment-1222912888. So for now just some thinkings on the fly.

Hmm I understand your need but what @Skrypt and @Piedone said make sense. Yes we already use the Default tenant to manage other tenants but more like an intermediary between tenants and host services as `ShellHost`. For example in unit tests we can create tenants even if the Default is still `Uninitialized`.

Note: We chose the `Default` tenant only because it is always there.

 So we can release, reload, create any tenant, and in the future remove it, **but until now we never used the Default tenant to modify the composition of another tenant**, as suggested by @Skrypt could it still be an isolated Site? Hmm like a collection on which you can add/remove items but can't mutate their private properties. So more like a rights access concern as mentioned by @Piedone. With OpenId we already do things across dependent tenants but only when some dedicated features are enabled on each one.

Note: For example each tenant has its own data protection keys ring.

But I don't want to block anything, only my feeling ATM.

**Comment by MikeAlhayek** [comment]
I understand the concern stated above. However, I don't think this is an issue that this PR presents. This PR build on the top of what we already have in OC. We already use the default tenant to manage tenants "via OC.Tenants" and we already have `DefaultTenantOnly` flag to restrict tenants only for default tenant. If we want to move everything into `TenantManagement` instance, then everything including what this PR is providing will be moved at that time. But either way, the ability to manage tenants from a SaaS provider is a must.

Also, I think moving everything related to managing tenant from `Default` tenant to  `TenantManagement` should be discussed in a separate issue. When agreed on, everything has to do with managing tenants include `OC.Tenants` will somehow be only allowed for `TenantManagement` instance.

I do not disagree what we should separate managing tenant UI from the default tenant. But I don't agree that it should block this PR since this PR only build on the top of what we already have. If we decided to create a separate instance to manage tenants, then that will include `OC.Tenants` which will also include the changes in this PR.

**Comment by jtkech** [comment]
If we want this functionality and this is the only reasonable way to go I'm not against ;) But still thinking that it is more like an intermediary between host services and other tenants.

I think we were just trying to find another way, thinking about security/isolation concerns.

I'm a newbie in security but maybe a feature that would give to an authenticated user of the Default tenant (having a given role and so on) the access to all tenants having the same feature enabled or a related one, this way we could browse from the Default Features page to the Features pages of these tenants.

**Comment by MikeAlhayek** [comment]
@jtkech today we already relay on the Default tenant to manage other tenants by disable, enable, and soon remove them :) So if a default tenant can perform such operations, then the same default tenant should be able to manage key functions like features.

I think when you guys decide to move the management function into a different place and away from the Default tenant, managing features will also be moved along with disabling, enabling, and removing tenant.

**Comment by jtkech** [comment]
@MikeAlhayek No problem I'm open to everything and don't want to block anything, only discussions.

It seems that you didn't read this part of my comment https://github.com/OrchardCMS/OrchardCore/issues/11870#issuecomment-1253295938

> So we can release, reload, create any tenant, and in the future remove it, but until now we never used the Default tenant to modify the composition of another tenant ... Hmm like a collection on which you can add/remove items but can't mutate their private properties.

**Comment by sebastienros** [comment]
Personally I think it's fine to have it in the Default tenant. If it had to be doable from another tenant then we'd have to change what "Default" tenant means. It would require to be able to change what tenants can manage features for others.

**Comment by jtkech** [comment]
Okay, just saw the meeting where you discussed on this, here and in other issues I try to describe what is a tenant, and how the Default tenant is already used as an intermediary between host services and other tenants, so why not for an additional functionality.

My only concern is as said above

> So we can release, reload, create any tenant, and in the future remove it, but until now we never used the Default tenant to modify the composition of another tenant ... Hmm like a collection on which you can add/remove items but can't mutate their private properties.

By composition I mean the features of which a tenant is composed. Yes I saw in the meeting that the security would be more about Contents we could access than Features we could enable/disable. Hmm, I'm not fully convinced but if so why not, I let others decide.

Also each time we change things around shell management I always think that I need to take a closer look, take care of any implication, maybe I was not so motivated to focus again on all the things around this ;)
