### ISSUE TITLE
Run gulp pipeline as part of the CI

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#11916]
Run the gulp pipeline and check the result is the same as the checked-in file to ensure the PR correctly ran it if there were changes in js/css.

c.f. https://github.com/OrchardCMS/OrchardCore/pull/11893/files

**Comment by 0liver** [comment]
This should be addressed soon, because with a fresh clone of OC, using Node.js 16 + NPM 8, I get 7 modified files compared to what's committed to `dev`:

![image](https://user-images.githubusercontent.com/164360/215115829-3e090180-cd2a-4c92-8417-c793f0e7e59c.png)

When using Node.js 14 with NPM 6, the Gulp build actually fails due to NPM dependencies not automatically being installed and `Orchard.Setup` choking on that because of the missing `@popperjs` dependency of `bootstrap`.

**Comment by Piedone** [comment]
This was fixed in https://github.com/OrchardCMS/OrchardCore/pull/15735.
