### ISSUE TITLE
Documentation pages 'Edit' button returns 404

### ISSUE THREAD

**Issue by Cinnam00n** [OrchardCMS/OrchardCore#11962]
Example:

https://docs.orchardcore.net/en/dev/docs/topics/docs-contributions/

Edit button on the left which is supposed to let you edit the docs page redirects to 404.

https://github.com/OrchardCMS/OrchardCore/edit/dev/src/docs/topics/docs-contributions/README.md

**Comment by Skrypt** [comment]
The URL should be: 

https://github.com/OrchardCMS/OrchardCore/edit/main/src/docs/topics/docs-contributions/README.md

instead of:

https://github.com/OrchardCMS/OrchardCore/edit/dev/src/docs/topics/docs-contributions/README.md

It is pointing to a branch that no longer exists: "dev".

@agriffard

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/6bb53d98b7ef5b7d66e9392820bac4f1a77711dd/mkdocs.yml#L40

As you can see here the configuration is correctly done.

The issue is that the documentation can still resolve a page from a request that is made on the dev branch.
Else it works perfectly from that URL: 

https://docs.orchardcore.net/en/main/docs/topics/docs-contributions/

**Comment by Skrypt** [comment]
Also, this is coming from a search made on Google: 

![image](https://user-images.githubusercontent.com/3228637/177587096-4469e7ef-b458-4581-9980-14514eaa7a45.png)

The URLs are all pointing to the dev branch. This means the indexation has been set on these URLs.

**Comment by agriffard** [comment]
dev branch is not built anymore.
