### ISSUE TITLE
Adding content type with a custom stereotype fails by default

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#12038]
### Describe the bug
When creating a "creatable" content type using with a specific stereotype, then try to add a content-item for that content type, we get an exception.

The following example show the error after created a content type called "PhoneCall" with "ContactMethod" stereotype. 

![image](https://user-images.githubusercontent.com/24724371/179835263-3408526a-5145-49cc-ab5c-d1a1abe55abc.png)

### To Reproduce
1. Create new Listable/Creatable content-type called "PhoneCall" with "ContactMethod" stereotype.
2. Go to Content items, add new "Phone Call"
3. You'll get an exception

### Expected behavior
The page should render using `Content_Edit` template as a fall back instead of forcing the user to create `ContactMethod_Edit` unless an override is needed

**Comment by ns8482e** [comment]
Each stereotype should have its own Edit ( however they may choose to fall back to Content_Edit via morph inside template ) 

it’s not good idea to convert them to content_edit implicit

**Comment by CrestApps** [comment]
@ns8482e 
Currently, we just throw an exception which in my option is not a good user experience. Is there a better way to do this without throwing an exception beside using the defaults?

What is the disadvantage of add `Content_Edit` as alternate first?

**Comment by ns8482e** [comment]
Adding Content_Edit will not render Stereotype_Edit (e.g Widget_Edit, MenuItem_Edit) that defeat the purpose of having stereotype 

stereotype (Menu, Widget) is not Content

**Comment by CrestApps** [comment]
IMO, `Widget_Edit` and `MenuItem_Edit` are overrides to `Content_Edit`. The UI supports creating ContentTypes with custom stereotype, we should be able to provides some defaults/fallback. but if the user want to define/override their own template nothing will stop them just like we are doing in   `Widget_Edit` and `MenuItem_Edit`.

**Comment by ns8482e** [comment]
It’s morph, and it’s for a purpose  - And remember that it’s explicit

**Comment by Skrypt** [comment]
The issue is that you should create a shape when using a custom stereotype. Adding a fallback to the Content_Edit shape will swallow the exception while it should be throwing an exception if you didn't create a shape template. Maybe what we need in that case is a fallback to a shape that displays instructions on how to create a proper shape based on the StereoType one would have created. That would make more sense to me.

**Comment by ns8482e** [comment]
Stereotype is different family of shapes and defining stereotypes means you need to create every shape that you plan to use

Implicit fallback is not good as excepting tells dev what needs to be done

IMO  documentation needed here, to list minimum shapes needed for new stereotype to function with TheAdmin theme

**Comment by Skrypt** [comment]
Let's say it would fallback at least to a "content_stereotypes" shape template and that this template would display a link to create the shape template in the Admin UI. Then, if someone wants to use a single "shape template" for all his different Content-Type with a stereotype it would be possible to override that "content_stereotypes" template. But falling back to "content_edit" would not be acceptable.

This is the compromise that I think would work. But overriding this "content_stereotypes" template would still be a "hack". But at least if you don't want to create a single template per stereotype then you will be able to. I think this is what we are trying to avoid somehow because it would be bad practice to create a single template for every stereotype.

**Comment by Skrypt** [comment]
One idea I'm having right now is to simply do a redirect to the pre-filled template in the admin UI with a notification that says that you are missing a stereotype template.

**Comment by CrestApps** [comment]
@Skrypt what if a user with less access clicks on it first? Can't we just change the exception to an alert message?

**Comment by ns8482e** [comment]
> @Skrypt what if a user with less access clicks on it first? Can't we just change the exception to an alert message?

May be enabling OrchardCore.Diagnostic should show UI friendly error

**Comment by sebastienros** [comment]
Discussed on triage, use a special alternate `"Stereotype_[DisplayType]"` as a fallback to `"[Stereotype]_[DisplayType]"` such that if the user forgot to create a shape template for it, it will use the special stereotype fallback (which itself will morph to Content shapes).

**Comment by CrestApps** [comment]
@sebastienros PR #12149 completes your directions above.

**Comment by CrestApps** [comment]
@sebastienros the `Stereotype*` have been added.
