### ISSUE TITLE
Forced effective Manage Media permission

### ISSUE THREAD

**Issue by Cinnam00n** [OrchardCMS/OrchardCore#12057]
### Issue

Checking **Manage own media** permission for a user implicitly grants that user to **Manage media** which results in his ability to delete other user's media which is unwanted

### Expected behaviour

Isolate the own media management permission from the management of all media.

**Comment by hishamco** [comment]
Does we implemented manage own and other media permissions completely?

/cc @matiasmolleja

**Comment by Skrypt** [comment]
Manage Own Media is what should work if not.

**Comment by sebastienros** [comment]
Seems like ManageMedia is implied by ManageOwnMedia:
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Media/Permissions.cs#L13

**Comment by hishamco** [comment]
`Manage own media` should manage the owner media not others media, seems the issue he/she can manage others media, right?

**Comment by hishamco** [comment]
One more thing what are the main difference between `ManageMedia` and `ManageMediaFolder`? I didn't much difference

**Comment by Skrypt** [comment]
I suggest that we reassign this issue for 1.6 or that we close it if there will be no action taken.

**Comment by hishamco** [comment]
Agree to move it into the next release

**Comment by ericrrichards** [comment]
Not to make this more complicated, but there's a wrinkle that I'm running into at the moment that feels related to this.

I have a content type with the CustomUserSettings stereotype.
This content type has an attached MediaField - editor = "attached"
For a user to edit their own settings and upload a picture to that MediaField, I have to give the role both the "Manage Own Custom User Settings - {content_type}" permission, and the "Manage Own Media" permission.

If I do this, the user can upload an image, but they can also get into other top-level Media Library files because of the implied Manage Media permission, which is not ideal.

But they can't get to the file that they uploaded to the MediaField, because that is underneath the /mediafields folder in the Media Library, and they don't have the "Manage Attached Media Fields Folder" permission.

So the CustomUserSettings MediaField image ends up living in /mediafields/{CustomUserSettings-ContentType}/{CustomUserSettings-ContentItemId}/

Would it be possible to change this for MediaFields on CustomUserSettings objects so that the file ended up under /_Users/{userid}/mediafields/{CustomUserSettings-ContentType}/{CustomUserSettings-ContentItemId}/?

**Comment by Piedone** [comment]
Please check out this PR for an intended Secure Media feature that fixes this too: https://github.com/OrchardCMS/OrchardCore/pull/15173.

**Comment by Piedone** [comment]
Please give your feedback about subfolder permissions here: https://github.com/OrchardCMS/OrchardCore/issues/9369#issuecomment-2039754807.

**Comment by Piedone** [comment]
If anybody has any feedback on the https://github.com/OrchardCMS/OrchardCore/pull/15173 PR, please let us know under it. Otherwise, I'll merge it in a week.
