### ISSUE TITLE
Implement ITicketStore feature for large cookies

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#12142]
### Is your feature request related to a problem? Please describe.

When admin creates custom role and with lots of content types and provides custom permissions to the user. 

The logged in user having custom permissions can not access the admin section  as authentication cookie size increases and some web server has limit on header sizes( e.g IIS 16kb, Kestrel 32kb)

### Describe the solution you'd like

Implement `ITicketStore` as optional feature, when enabled it will store all claims for the logged in user on server in memory cache or distributed cache instead of cookie

### Describe alternatives you've considered
Currently you can increase cookie size limit in kestrel using following 
```
builder.WebHost.ConfigureKestrel(o=> o.Limits.MaxRequestHeadersTotalSize = 327680 );
```

Related discussion #12117

**Comment by saleemhaq** [comment]
> ### Is your feature request related to a problem? Please describe.
> When admin creates custom role and with lots of content types and provides custom permissions to the user.
> 
> The logged in user having custom permissions can not access the admin section as authentication cookie size increases and some web server has limit on header sizes( e.g IIS 16kb, Kestrel 32kb)
> 
> ### Describe the solution you'd like
> A clear and concise description of what you want to happen.
> 
> Implement `ITicketStore` as optional feature, when enabled it will store all claims for the logged in user on server in memory cache or distributed cache instead of cookie
> 
> ### Describe alternatives you've considered
> Currently you can increase cookie size limit in kestrel using following
> 
> ```
> builder.WebHost.ConfigureKestrel(o=> o.Limits.MaxRequestHeadersTotalSize = 327680 );
> ```
> 
> Related discussion #12117

@sebastienros please help me in that my application feature is not completed or work without this, Isuffer much.

**Comment by infofromca** [comment]
#9834

**Comment by sebastienros** [comment]
The default implementation of ITicketStore should use IDistributedCache, this way it would be in local memory for single node sites, and automatically go on Redis when the feature is enabled.

**Comment by lbertonicsc** [comment]
Good morning,

I came across the problem described in #1131. Besides losing auth when I enable a feature, I lose auth also when I restart the app.

This happens due to the feature `OrchardCore.Users.Authentication.CacheTicketStore`.

I have enabled the above mentioned feature to solve the problem described in #15327, which is caused by huge cookies as a consequence of many permissions related to a user, using a local memory cache (not a distributed one).

In order to solve both problems I can think about the following solutions:

1. You may consider storing in the cache, through the CacheTicketStore feature, everything except for the session data.
2. I need to implement a custom CacheTicketStore to use a more persistent cache.

What do you think about solution n. 1?

Since I am not very knowledgeable about .NET/OC do you see any other solution?

I am using IIS but increasing the allowed cookies' size to the maximum does not solve the problem of "Request too long".

I am currently using OC v1.5.0, has this problem been solved by any following release?

Thank you,
Luca Bertoni
