### ISSUE TITLE
Analyze cost of static file providers

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1220]
Based on a stack trace it looks like the mvc middleware is called after all the static file providers for modules. I'd like to know if moving them after the MVC pipeline makes things faster (for both mvc endpoints and static files), or if the prefix matching already prevents any perf issue.

An optimization to measure is to use a single prefixed middleware, like `/content` and then use the module name to route to the correct folder. Either using as many other static file providers, or a compound one that could use a prefix.

**Comment by sebastienros** [comment]
Or a single middleware with a CompoundFileProvider for all modules.

**Comment by jtkech** [comment]
Maybe better with embedded file providers which don't need file watchers ... But, while in dev, we will still use physical file providers for modules referenced as projects.

**Comment by sebastienros** [comment]
Didn't think about the file watchers. But we still need to measure it, and if possible understand what the impact of FWs is.

**Comment by jtkech** [comment]
@sebastienros i did some tests.

I tried to do tests which are comparable because, e.g when my computer is less hot results are better ;) The results seem also to be related to the amount of memory used before running the test.

- First, through the debugger i could see that for a given requested file, only the right instances of file providers are called. I think it is because for each one we provide `RequestPath = "/" + extension.Id` .

- Then i ordered providers by module names and used a little static file in one of the 1st modules and the same file in one of the last ones. Then, in a published context, i didn't see any significant differences.

---

- Then comparing the embedded branch and the dev branch, i've used a little static file and a concurency of 10. Then, waiting between tests for my pc to cool down, most of the time the embedded results were around `20%` better than the dev branch. The best result i could have with the dev branch was around `3500 rps` and with the embedded branch around `4300 rps`.

- In term of memory, in the task manager for the dotnet process i could see almost the same. At the begenning around `150 Mo`, then after some tests up to around `500 Mo` (but not always), then after some various time it can go down for both to around `200 Mo`.

- After the very first tests it seemed that the embedded branch memory was growing up higher, around `700 Mo`. But testing again the dev branch, i could see the same memory increase, so i don't know.

Note: Particularly after the 1st test series, it was quite long to shut down the application. Here also, it seems to be related to the amount of memory which is used before shutting down.

**Comment by sebastienros** [comment]
Thanks.
