### ISSUE TITLE
Add MVC examples to docs

### ISSUE THREAD

**Issue by Eaglef90** [OrchardCMS/OrchardCore#12506]
All the documentation examples use with Razor pages or Liquid. Can traditional MVC examples please be added so decoupled installs can know what method and classes are to be used in controlls and viewmodels?

**Comment by Skrypt** [comment]
duplicate

**Comment by Eaglef90** [comment]
You said this is a duplicate but I can't find it anywhere to follow and get status of

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/discussions/12505

**Comment by Eaglef90** [comment]
Sorry how is asking for all the docs to have MVC examples a duplicate of asking how to build a menu via MVC? MVC is not documented at all, this request is asking for MVC examples to be documented. 12505 is asking for help getting a menu working via MVC. IMHO these are two completely different requests.

**Comment by Skrypt** [comment]
I'm sorry but these requests are redundant and if we need to add documentation about the INavigationManager itself and how to use it directly instead of using shapes then there are examples of that in the source code of Orchard Core. I don't think it is worth opening an issue and a discussion about it. If there is an issue that needs to be fixed, we will create one based on the discussion you started but I would be really surprised if there is any action required to be done as it is as simple as using the INavigationManager and building a menu with it inside a custom service. Which is something pretty common that requires only reading source code on your part. We can't document everything. The common usage is documented and it is by using the TagHelpers.

**Comment by Eaglef90** [comment]
I guess I missunderstood the MVC part of the decoupled option. I though there where simple class like say "var menu = new OrchardCore.Menu.GetMenu("alies:main-menu")" that could be made in MVC to pull the data from the DB in a pre-defined structure which I could then do stuff with in the controller. If using MVC is more "to the bones" then, no, it should not be documented. I am not a professional programer like you guys, just a hobbies to stupid to really understand what is going on so I end up asking dumb questions and missunderstanding things. Sorry for the problems this has caused you guys over the past few weeks. Hopfully I will be able to figure out Razore and the TagHelpers with out having to bother you guys much more.
