### ISSUE TITLE
Model.ContentItem.Owner empty in Content-BlogPost.liquid

### ISSUE THREAD

**Issue by etcetraw** [OrchardCMS/OrchardCore#1251]
Owner:{{ Model.ContentItem.Owner }} returns nothing.
Author:{{ Model.ContentItem.Author }} return author.
Behavior appears to be the same for both recipe and created items.

**Comment by jtkech** [comment]
@sebastienros @etcetraw 

- It works when you 1st create an item. But you loose the `Owner` if you re-publish the item.

- The workaround is to add the `Common` part to the type and check the `DisplayOwnerEditor` option.

Just saw that in the `Versioning` handler the `Owner` is not copied (as the `CreatedUtc` is). I think the issue is there, i will suggest a PR.
