### ISSUE TITLE
ContentRequestCultureProvider does not set cookie based on content Culture

### ISSUE THREAD

**Issue by Dredy** [OrchardCMS/OrchardCore#12610]
Setting the ContentRequestCultureProvider "Set Cookie" on the Localization section does not sets the cookie based on the Content culture.

### To Reproduce
1. Create a page with Culture en-US
2. Create the it-IT variant of the page
3. View the en-US page
4. Change the url to show the it-IT version
5. The culture Picker remains on English
6. The .AspnetCore.Culture cookie remains to en-EN

### Expected behavior
I'm expecting that the Culture Picker will reflect the ContentItem.Content.LocalizationPart.Culture
and also the .AspnetCore.Culture cookie will reflect the ContentItem.Content.LocalizationPart.Culture

**Comment by hishamco** [comment]
Did you enable the Content Localization required features?

**Comment by Dredy** [comment]
Yes, of course.
The Culture Picker is working as expected: it changes the page to the relative Culture versione, but navigating on a page with different Culture (without using the Culture Picker), the picker remains on the initial Cultire and the Cookie is not updated reflecting the new culture

**Comment by hishamco** [comment]
Could you please try it in a Private Window may be there's a caching issue, if the issue still we need to check then

**Comment by Dredy** [comment]
Hi, i tried an "Empty cache and Hard reload", but i can confirm that it seems not to be a cache issue.
I also tried to Rebuild the project (to flush the asp.net cache) mantaining the page opened, but at refresh the picker reflects the cookie, that was with the old value.

Another info: the main menu got the Localization Part and has 2 localizations, but it does not changes the items according with the Picker. it remains always with the default Culture items

When i change the URL to the other Culture, the Picker remains on the old culture, then, if i change the culture using the Picker the page does not change (because i was already on the correct page. (that seems to work as expected)

Manually hacking the cookie value, i found that the Picker (at refresh) reads the cookie and reflects what is on the cookie, but no menu nor content reflects the new cookie value.

**Comment by alafi** [comment]
@hishamco 
I believe this is a valid bug which was introduced by [commit](https://github.com/OrchardCMS/OrchardCore/commit/66b1b352bbe95840463d023ed1dc02df45501fcb) in [src/OrchardCore.Modules/OrchardCore.Localization/Startup.cs](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Localization/Startup.cs).

The change in code is creating a new instance of `RequestLocalizationOptions` (inherited by `OrchardCoreRequestLocalizationOptions`) instead of reusing the existing one. This will ignore the configuration of `RequestLocalizationOptions` in [Content Localization Statrup.cs](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.ContentLocalization/Startup.cs) which happens earlier in the initialization lifecycle.

**Comment by hishamco** [comment]
I will check this one ..

**Comment by hishamco** [comment]
@Dredy I enabled `OC.ContentLocalization` module, then added `ContentCulturePicker` feature. After attaching `LocalizationPart` to `Article` content type and adding two versions, I'm able to switch between the content with expected result

**Comment by hishamco** [comment]
Furthermore we SHOULD NOT ignore the current culture provider(s)

**Comment by hishamco** [comment]
For reference #13093

**Comment by Dredy** [comment]
@hishamco to reproduce You have to change the url to /about-1 and /about-2
In my tests, the content changes to the required culture content, but the CulturePicker remains as it was before

**Comment by hishamco** [comment]
@Dredy could you try my PR?
