### ISSUE TITLE
After upgrade  getting error : The certificate chain was issued by an authority that is not trusted

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#12653]
After recent upgrade with  YesSQL v 3.2.0 (with schema support) I am getting the following error when loading an existing project : 

![image](https://user-images.githubusercontent.com/1516981/196028920-8c8d83db-466c-4888-aded-be1ef4e96b4d.png)

The fix is to append to the connectionstring the setting : 
```
;TrustServerCertificate=True
```
but I am wondering if this could be related to yessql upgrade ?

**Comment by MikeAlhayek** [comment]
I think you need `Encrypt=false` in the connection string 

@sebastienros you may want to shed some light here

**Comment by jtkech** [comment]
You need `TrustServerCertificate=True;`

**Comment by MikeAlhayek** [comment]
Just to clarify, you can use add `Encrypt=false` or `TrustServerCertificate=True` to the connection string to solve this issue. 

The reason this is happening because YesSql is now using the new SQL client which encrypts the connection by default. So if you don't have a trusted certification on the server and want to continue to encrypt the communication using the untrusted server, add `TrustServerCertificate=True` to the connection string. If you want to not encrypt the communication at all, you can use `Encrypt=false`

**Comment by ns8482e** [comment]
This is interesting,  How do we make it self healing on upgrade?

**Comment by MikeAlhayek** [comment]
@ns8482e make sure your server has a valid ssl certificate. I think you would face this issue locally only.
