### ISSUE TITLE
User reset password

### ISSUE THREAD

**Issue by sipronunciaaigor** [OrchardCMS/OrchardCore#1299]
From a user perspective, I think it's quite important to allow website users to reset their password.
This would mean, of course, to have in place a reset password procedure and a mailing system.
Is there any specific direction/idea regarding this?

I would be very happy to help in writing both of the systems... #1138

**Comment by sebastienros** [comment]
It's more than important, would be great for you to help.

**Comment by sipronunciaaigor** [comment]
@sebastienros can this be merged with #1332?

**Comment by sebastienros** [comment]
> Does OrchardCore.Email have to be a dependency in OrchardCore.Users and added to the recipes?

No. We should have a custom feature in Users that depends on Email.

> Do we initialize the default email sender during the setup, by using the provided email?

 No. Leave it blank because smtp settings will always be a required step.

> Do we need a Recipe Step to Configure the SmtpSettings?

I don't think so, there is already a step to configure any settings.

> Do we make friendly urls for ChangePassword, ForgotPassword, ... as it is done for Login?

If you mean like `/login`, yes.

> Do we display a Warning message in admin while the Smtp Settings are not set when the module is enabled?

Yes. It's independent from the user management. If Email is enabled but not configured we need a banner.

> Do we use Liquid templates for Registration and ResetPassword emails? Default .liquid view + allow to override it in Templates?

The default views should be in the module, in Razor.

> How do we pass the parameters (User properties, ...) to the liquid view?

I am not sure we have access to the current user from liquid, maybe file an issue.

> Do we use BaseUrl Site Setting (not editable in General settings right now) or ~/ syntax to generate the urls?

`BaseUrl` for emails. This is the only reason to have a base url property.

> Will we have the same opt-in settings than in O1? ..

I think so. Also anything that is doable in the default MVC template should work in Orchard, and most of the controller/actions should be used to do the same thing in Orchard.
