### ISSUE TITLE
Dynamic permission can't save in role

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#13024]
bug in pull: https://github.com/OrchardCMS/OrchardCore/pull/12510

1. Edit a role 
2. Select some dynamic permissions , like 'ExecuteApi_RecentBlogPosts'
3. Click save .
4. Reopen the role , ExecuteApi_RecentBlogPosts is not checked

cuz the code only can load the static permissions , the program will break on line 235

https://github.com/OrchardCMS/OrchardCore/blob/083d5d7f9885b6ba034f642259cb94326af9e551/src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs#L219-L252

We should load all permissions this way:

https://github.com/OrchardCMS/OrchardCore/blob/083d5d7f9885b6ba034f642259cb94326af9e551/src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs#L184-L185

**Comment by hyzx86** [comment]
https://user-images.githubusercontent.com/15613121/210260619-e0620501-62a0-4229-892b-532e0fd1cee8.mp4

**Comment by hyzx86** [comment]
https://user-images.githubusercontent.com/15613121/210268379-270677fb-5471-476d-8de2-1c8c664938c8.mp4

**Comment by gvkries** [comment]
Hehe, I just wanted to open the same bug. Actually there is a second even bigger issue with this PR. The way the `RoleUpdater` is now implemented causes it to always overwrite any admin settings, whenever the site starts. E.g. the 'Anonymous' role is now always getting the 'ViewContent' permission on startup, which breaks the whole content type permission system. Every content type is then allowed implicitly for everyone.

**Comment by hyzx86** [comment]
It seems that I should turn off PR first  🤣,
I haven't looked at the code carefully, I just let it work
It was embarrassing to find out when the program was released yesterday.. The role permission cannot be changed

**Comment by jtkech** [comment]
@hyzx86 

I think you were in the right path, yes using `GetInstalledPermissionsAsync()` in the controller edit post seems to fix issue because it uses `GetPermissionsAsync()` that also gets dynamic permissions.

For info I could also make it working by just using

            var permissionNames = new List<string>();
            foreach (var permissionProvider in _permissionProviders)
            {
                var permissions = await permissionProvider.GetPermissionsAsync();
                permissionNames.AddRange(permissions.Select(permission => permission.Name));
            }

Maybe you could re-open your PR ;)

As a reminder, things to be checked.

- Check if okay to use `_rolesDocumentManager` directly in `RoleUpdater` and `AdminController` to update the permissions history, knowing that the `RoleStore` (called by the aspnet `RoleManager`) will update the same document.

- Check if necessary to call the `RoleUpdater` logic on each feature enabling, before was on feature installing (called once on the first enabling).

- Check if necessary to call the `RoleUpdater` logic on each tenant activation. Hmm when a feature state change the shell will be rebuilt and then activated, so maybe at least only on tenant activation but not on any feature change, will see.

**Comment by hyzx86** [comment]
@jtkech reopened,
But I haven't looked at the problem mentioned by  @gvkries  carefully

**Comment by jtkech** [comment]
Okay no problem will look at the PR tomorrow

In the meantime can you try my above suggestion, if you have time

**Comment by hyzx86** [comment]
I am planning to build a module to obtain the corresponding site settings by specifying a type name
`CustomSettings`

The first time I tested with 'ViewContent'. Then I changed it to: `DeleteCcontent` to test again.
I don't think the latter should be given to any user without a role

But it didn't turn out, as I expected, that it actually had access

I have a big screenshot here, which shows my problems

![image](https://user-images.githubusercontent.com/15613121/210423336-b3cd5e2a-019d-44d6-9188-969b1f7cb15d.png)

**Comment by MikeAlhayek** [comment]
@hyzx86 are you working on a PR for this?

**Comment by hyzx86** [comment]
Not really. I just fixed the problem of edit role
https://github.com/OrchardCMS/OrchardCore/pull/13025

The permission check is not work. I don't know what the problem is

**Comment by gvkries** [comment]
I've created a separate issue #13035 for the `RoleUpdater` bug. I think your PR fixes the bug described here, the other one is related but a little bit harder to solve correctly.
