### ISSUE TITLE
Content items filters inconsistencies

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#13162]
There are multiple cases where the text filters in the content items admin page don't work correctly.

Ex: `text:home And type:Page` works but not `text:home AND type:Page` (the first part is removed and it only keeps `AND type:Page` after the redirect).
Idem with `Or` and `OR`.

**Comment by hishamco** [comment]
Is it related to Lucene?

**Comment by hishamco** [comment]
Is it related to Lucene?

**Comment by jtkech** [comment]
@agriffard 

The operators `AND` and `OR` are in uppercase otherwise they are considered as other terms, when there is no operator it's like we use `OR` between terms.

Normally an operator is followed by a term e.g. `text:home AND foo type:Page`, this in the same filter part (here `text:`) before the next filter part (here `type:`), an operator is not intended to be used between 2 filter parts.

So the problem is when an operator is not followed by a term, maybe in that case would be better to ignore it (maybe by checking that there is a parsing error), maybe remove it, and at least keep the previous term(s).

**Comment by agriffard** [comment]
Ok but then, when I type `text:home type:Menu` (without the OR between), I expect to list in the results a page with the title Home and the main menu whose type is Menu but nothing is displayed.

**Comment by jtkech** [comment]
> I expect to list in the results a page with the title Home and the main menu whose type is Menu

As it is working, when we add a filter part we add more selectivity, it's like having an implicit AND between filter parts, the results being the items whose title contains home AND whose type is Menu.

But yes I understand, we may want a logical OR between filters, but there is no option to do that ;)

Without any option, I think the more commonly use case is to want an implicit AND.

Another way would be to have an implicit OR but order items by relevance, for example list all items having Home in their title OR whose type is Menu, but list first items having Home in their title AND whose type is Menu, but more complex to do this kind of searching than a simple filtering.
