### ISSUE TITLE
Only active themes should be enabled

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13191]
### Is your feature request related to a problem? Please describe.
I can't think of a good reason why do we need manually enable/disable a theme. I think a theme should be auto enable/disabled when it is active/current. @jtkech may be there is a good reason why we truly need this to be manual? So any theme and it's dependencies should be enabled when it's activated. 

I have a custom admin theme `TheCustomAdmin` which is based on `TheAdmin`. So it depends on `TheAdmin`, but if someone clicks `Disable` button on `TheAdmin`, the site breaks!

I think all themes should be auto enabled/disabled based on their current status.

### Describe the solution you'd like
Remove the `Enable/Disable` functions from theme and only register services from current admin and site theme. All themes should still be listed on the UI, but only register services for the current sites.

**Comment by rjpowers10** [comment]
Related: #9836

**Comment by jtkech** [comment]
Need to think about it, and try it, but some first thoughts

Yes, a base theme is part of the dependency graph but not taken into account by the UI, at least we should provide an alert box as when we disable another feature, see https://github.com/OrchardCMS/OrchardCore/issues/9836#issuecomment-876773399

> So any theme and it's dependencies should be enabled when it's activated.

Hmm, normally this is the case but we can disable a base theme of a selected theme without alert box.

Yes for example a base theme of a selected theme is enabled but not selected, hmm when selecting another theme we could think about disabling the previous one and its base theme, unless if the previous selected theme is the base theme of the new selected one, normally this is taken into account by the dependency graph if the new selected theme is still part of the features to enable.

So yes maybe something like `EnabledByDependencyOnly` but in a different way because normally any theme, even if it is a base theme, should be itself selectable. As said would be good at least to have an alert box when we try to disable a base theme, particularly if this is the base theme of a selected theme.

**Comment by MikeAlhayek** [comment]
@jtkech why do we need a UI feature to enable/disable a theme? Themes and their dependency themes should be only enabled when a theme is activated. I don’t think there should be a button to enable/disable a theme. From a UI perspective, themes should not be treated as features even though I know theme is just a feature front infrastructure prospective

**Comment by jtkech** [comment]
Yes, didn't said the opposite ;) Just describing how it behaves as I remember, and start thinking how we could automatically enable / disable them on selection.

> hmm when selecting another theme we could think about disabling the previous one and its base theme, unless if the previous selected theme is the base theme of the new selected one ...

**Comment by sebastienros** [comment]
Child themes depend on other themes so some themes need to be enabled while not "active" aka fallback theme when the default selector is used.

If someone creates a Theme selector that can return random themes, all these themes need to be enabled. 

Active/Current only means that the DefaultSelector return this theme.
