### ISSUE TITLE
Elasticsearch fails to return documents when Source is not included

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13403]
### Describe the bug
Currently, Elasticsearch module allow us to include or exclude `source` from being stored in the ES index by setting the "Store source data" options in the index. If we change the settings to not include source, the `ElasticSearchQueryService` throws exception since `ContentItemId` won't exists

[                contentItemIds.Add(item.GetValueOrDefault("ContentItemId").ToString());](https://github.com/OrchardCMS/OrchardCore/blob/87b427104a60f1c9a38d7f978c60a4f429408984/src/OrchardCore/OrchardCore.Search.Elasticsearch.Core/Services/ElasticSearchQueryService.cs#L24)

I am working on a PR for this.

**Comment by Skrypt** [comment]
That's normal. You need then to adjust your queries.

**Comment by Skrypt** [comment]
You can analyze the generated schema per index.

**Comment by Skrypt** [comment]
That's what the Query returns naturally and how it works with ES. You just need to know that the _id is the ContentItemId. Adding parsing on top of that to return a ContentItemId in the Query result is going to add unnecessary overhead on each Query.

Else, I don't remember indexing the ContentItemId anywhere else than on that Id in ES. I'm not sure what you are talking about either. 😄

**Comment by MikeAlhayek** [comment]
@Skrypt out of the box today, OC will throw an exception if you uncheck the `Store source data` option in the index settings.

The reason this exception is thrown is because the following line 

https://github.com/OrchardCMS/OrchardCore/blob/87b427104a60f1c9a38d7f978c60a4f429408984/src/OrchardCore/OrchardCore.Search.Elasticsearch.Core/Services/ElasticSearchQueryService.cs#L24

In that code `item` is null since document has no source which throws this exception. 

So we need to have a way for the use to specify fields to return at query time or we need to return at least `ContentItemId` so that the search returns data.

**Comment by Skrypt** [comment]
I have made that work in the Query UI in the admin. You can see the difference there and how to retrieve data from an index that has no source stored. 

I don't think the issue comes from the ContentItemId not being stored but because ES will return the _source data naturally when doing a Query. If you remove the _source folder then you need to return the value stored in each field else it will return nothing simply. There, you should simply validate that the Source data is included in the index in the ElasticSearchQueryService and make a distinction there. You will need to do something quite different when the ES index has no source.

Also, I don't understand yet why you are doing item.GetValueOrDefault("ContentItemId") there. It must work with Lucene but not with Elasticsearch at all because of the field name "_id" ...

**Comment by MikeAlhayek** [comment]
@Skrypt I did not add `item.GetValueOrDefault("ContentItemId")` this has been part of the code for a while. I feel that you are not understanding the issue I am presenting here.

I just submitted a PR #13406 that'll fix the issue and I verified that it works in both cases. We may need to loop over the fields collections on line 400 and all theme if any. But, I do not see anywhere in OC where a user can specify fields to return in the query so I don't want to add it for no reason.

**Comment by Skrypt** [comment]
I don't have more time to analyze the issue right now. But, one thing I know is that the ContentItemId is stored as the _id in Elasticsearch because it is necessary for documents to be unique and to assert that unicity. Now, when we are removing the source data it still should index the _id else it would fail to process the document(s).
