### ISSUE TITLE
Liquid templates do not resolve in the BodyPart

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#1356]
**Repro:** 

Using dev branch install the blog recipe.
Create a new Article content item.
In the body Part type : Hello from {{Site.SiteName}}
When viewing the article on the frontend it does  not show the resolved liquid expression  {{Site.SiteName}}

**Comment by jtkech** [comment]
Oh, because when building shapes in the context of the driver of a part or a field there is no `DisplayContext or ViewContext`, so we can't do a full contextualization, see my comment on gitter.

To do this through a part you would need to use a `LiquidPart` because for the related shapes, through an `IShapeTableProvider`, we do a full contextualization, see in `LiquidShapes.cs`.
