### ISSUE TITLE
Unable to change the "Content" tab from Placement file

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#13605]
I'm unable to change the first tab from within the `Placement.json`, seems the default name is `Content`, @ns8482e any idea how we can change the first tab title?

**Comment by MikeAlhayek** [comment]
@hishamco Did you try assigning all of your filed into other tabs? I think the Content tab is used as a fallback so that any shape you did not group will get placed there. So if you assign all of the shapes in the Content location into another tab that would just have nothing left on a content and it’ll be removed leaving your tabs with your own names.

**Comment by ns8482e** [comment]
Default tab is Content. You must move all shapes to place on new Tab to completely remove Content

**Comment by hishamco** [comment]
Seems there're a lot of placement secrets need to be documented :)

Thanks all
