### ISSUE TITLE
How to deal with 1 pairs of N relationships

### ISSUE THREAD

**Issue by zhhbo** [OrchardCMS/OrchardCore#1361]
How to deal with 1 pairs of N relationships in yessql

**Comment by sebastienros** [comment]
Can you provide an example? And also create the issue on the YesSql repos?

**Comment by alberthajdu** [comment]
@sebastienros Like when I have a Person who has multiple Dogs but the Dogs are stored as individual content items because lets say one person can have 500 dogs. And I would like to retrieve a person with his dogs in one query. How should I do that?

I couldn't find any example regarding this in the source.

**Comment by sebastienros** [comment]
First you need to reference the parent object from the children. Like we do for Blog[1] -> BlogPost[*]. Then you can create an index that stores this relationship, again like we do for Blog Posts. And you can even reuse what we do for blog posts (Containers).

**Comment by alberthajdu** [comment]
@sebastienros I think maybe this isn't an answer to the question.

With 1 to N relationships one would like to achieve to retrieve the parent and it's children with **one** query. In the ListPart example the ListPartDisplayDriver uses an additional query to retrieve it's children:
`model.ContentItems = (await QueryListItemsAsync(listPart, pager, true)).ToArray();`
So the 1. query is when you retrieve the content item with the ListPart and the 2. query is when you retrieve the children.
(And the Person+Dogs example is just the most basic one.)

My question (and I believe the original question too) would be that how to do this with YesSql?
Is it a feature that needs to be implemented or YesSql won't support this scenario?
If it won't support it then could you please explain why it isn't an essential feature?

**Comment by Skrypt** [comment]
https://github.com/sebastienros/yessql/issues/21

**Comment by alberthajdu** [comment]
@Skrypt could you please explain what does the linked issue mean? It was opened 1,5 years ago, what's the current status?

If someone knows the answer to my above 3 questions could that person give an answer?

**Comment by Skrypt** [comment]
In YesSQL everything is map/reduced in the Document table.

![image](https://user-images.githubusercontent.com/3228637/37671902-1d904d06-2c43-11e8-890f-ad4fa0af947c.png)

If you look into other tables you will see a reference made to the DocumentId. An example of 1 to N relationship is Container --> Containable Types which are used by Blogs for example. In Orchard 1 it would have been the **List** feature. Here is an example with the ContainedPartIndex table that references itself on the DocumentId.

![image](https://user-images.githubusercontent.com/3228637/37672023-6d53ee56-2c43-11e8-9f89-7ef40f9340c8.png)

Your issue is not about 1 to N relationship it's about eager loading vs lazy loading data with one single Query. One thing that is sure is that the data stored in the **content field** of this table is JSON so it can handle data hierarchies. You could easily store a Person with his dogs in that content field just to be able to retreive all the data by a single query. Then you would have also a Dog table to be able to list the dogs options that can be added to a Person. Remember that YesSQL is about map/reducing.

**Comment by alberthajdu** [comment]
@Skrypt you are right my question is about eager loading with one single query but I think it fits the topic of this issue. There are multiple ways to deal with these relationships and my question would be that this specific scenario is supported, planned to be supported or won't be supported?

**Comment by Skrypt** [comment]
As an alternative : 

>  you can do SQL statements directly using the connection exposed by a Session. You can also use Dapper if you prefer. SQL should be built using the dialect property in the session to handle different databases if necessary. There should be a sample in the Lucene module.

**Comment by alberthajdu** [comment]
@Skrypt thanks I'm aware of all these possibilities. All I need is a confirmation from Sébastien. I'll use happily as much queries to retrieve my content items as necessary but I need a confirmation about that it won't affect perf and this is and will be the best supported solution.

**Comment by sebastienros** [comment]
```csharp
public class Person
{
  public string Name { get; set; }
}

public class Dog
{
  public string Name { get; set; }
  public string OwnerName { get; set; }
}
```

1 `Person` document
10 `Dog` documents
All these 11 documents are stored in the `Documents` table as individual json items. I will assume you also create an Index to query a `Dog` by its owner name, and another query to get a `Person` by name.

In this case to retrieve all 11 documents we need a query that is independent from the document type, and retrieves bot a `Person` with a specific name and `Dog` documents based  on the same name.

Because you have two indices tables, you can use a query using Linq in YesSql to query for the name in either table, and get the associated documents, I will try it myself.

Another solution is to use a single Index that has a `Name` column and will be applied to both `Dog` and `Person` object.

__However__ in this case I would recommend to keep it simple and do two queries, it's one for the root object and one for the relationship (whatever number of items is referenced). And that should be fast.
I think I understand why you want a single query, probably coming from a relational experience in a POCO you would like to prevent lazy loading. But in this case the POCOs are not directly related, so it's hard to map the same concepts. The documents are disjoints and only have a logical reference (the owner's name in this case).

**Comment by Skrypt** [comment]
What happens if we have 2 different Person with the same name? I'm sorry, maybe I'm confused by the example.

**Comment by sebastienros** [comment]
Use a different key then, name is just an example for a logical identifier, use SSN for instance, or a guid.

**Comment by alberthajdu** [comment]
@sebastienros thank you for the explanation. I think a lot of people will come from relational background therefore an explanation on why OC uses these concepts and how to solve complex data model problems would be useful.

The introduction of these concepts without explanation could easily scare away newcomers especially people who want to use only the framework.

P.S.: personally I really like these concepts, just want to understand the whys and the best practices. I've read all stuff about YesSql, looked into it's source, found a bug and a cause. Developed only Orchard websites in the recent 4,5 years. Looked and embraced **all** the YesSql and data access related stuff in OC source. And still, I have questions and concerns about the data access.
