### ISSUE TITLE
Custom Health Checks fail due to YesSql init change

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#13632]
Due to the changes from #13147 our custom health checks are now failing.

I did some investigating and the problem seems to be caused by the ordering of middleware.  When a /health/* request comes in the ModularTenantContainerMiddleware is called but the ModularTenantRouterMiddleware is never called.  Instead the Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware handles the call which means no tenant pipeline.  When I trace through the call I don't see the ShellContextFactory getting used so there is no properly configured IStore.

Does anyone know of a way to get around this?

**Comment by sebastienros** [comment]
@jtkech in case you have an idea

**Comment by jtkech** [comment]
@ShaneCourtrille 

> When a /health/* request comes in the ModularTenantContainerMiddleware is called but the ModularTenantRouterMiddleware is never called.

It would mean that no tenant was matched from the runningShellTable, but normally we fallback to the Default tenant that always exists. Or because the Default tenant is still in the initializing state, but I don't see any relation with the changes from #13147.

> Instead the .HealthChecks.HealthCheckMiddleware handles the call which means no tenant pipeline.

So it means that you register the healthCheck to the main app level pipeline, not at the tenant level per tenant. Hmm, but how it was working before if you were executing code that uses YesSql at the app level on the healthCheck routing, knowing e.g. that the YesSql store is a tenant singleton.

Can you show us how you register the healthCheck (globally or per tenant), the exact url(s) and which code (app level or tenant level) you are executing on these routes, so that we could test it.

**Comment by ShaneCourtrille** [comment]
Still looking into this.  I suspect the problem could be caused by how we are getting things from DI for these health checks.

**Comment by sebastienros** [comment]
Is this still a problem?

**Comment by jtkech** [comment]
@ShaneCourtrille I'm closing it but feel free to re-open if this is still an issue ;)
