### ISSUE TITLE
Enabling "OrchardCore.OpenId.Validation" feature while using custom Authority value in the server throws an exception

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13673]
### Describe the bug
When using **OpenId Server** feature along with **OpenId Validation** and using custom Authority value, the following exception is thrown

```
InvalidOperationException: The issuer attached to the static configuration must be the same as the one configured in the validation options.
```
### To Reproduce
1. Enable the OpenId Server and the Validation
2. Set a new value in the `Authority` settings in server settings.
3. The site become useless and you'll get the above exception.

### Workaround
To work around this issue I did the following steps

If the sure is not usable and there is a white-page/exception follow the next 5 steps. If the site is still usable, skip the first 2 steps, and start at step 3.
1. Use any RDBMS (like SQL Server Management Studio) tool to update the database directly. Update the the site settings document record by setting `Authority` to `null` in the OpenId Server settings.
2. Restart your app to force the app to read the updates you made in the database.
3. Make sure the `Deployment` feature is enable.
4. Go to **Configuratons** >> **Import/Export** >> **Import Recipe** and execute the following recipe

```
{
 "steps": [
     {
      "name": "OpenIdValidationSettings",
      "Authority": "The custom authority domain name you want to use like https://www.custom-name.com"
    } 
 ]
}
```

5. I went back to the OpenID Server settings and set the Authority value to the same value I used in the Authority above.

**Comment by kevinchalet** [comment]
Can you please try to reproduce the issue after adding `options.Issuer = configuration.Authority;` line 142?

https://github.com/OrchardCMS/OrchardCore/blob/9b905cfc068d2a4fccd6ec88a0af0620ceacb9b0/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdValidationConfiguration.cs#L143-L146

**Comment by kevinchalet** [comment]
@MikeAlhayek did you have a chance to try the suggested snippet? 😃

**Comment by MikeAlhayek** [comment]
@kevinchalet oops, sorry! I missed you last comment.

Yes that indeed fixes the issue. Do you want me to submit a PR with the change?  But, why would it work like this

```
options.Configuration = new OpenIddictConfiguration();
options.Issuer = configuration.Authority;
```

but not 
```
options.Configuration = new OpenIddictConfiguration()
{
    Issuer = configuration.Authority;
};
```

**Comment by kevinchalet** [comment]
It's due to the fact the `issuer` comes from potentially multiple places:
  - The issuer configured in the validation options (`options.Issuer`).
  - The issuer attached to a static configuration (`options.Configuration.Issuer`).
  - The issuer attached to a dynamic configuration, retrieved using OIDC discovery (accessed via `options.ConfigurationManager`).

Recent versions of OpenIddict use `options.Issuer` as the source of truth and now require that the issuer attached to a static configuration - which is the case when you target a "local" server - match the global value, `options.Issuer`.

Note: it's allowed to not set the `Issuer` on the `OpenIddictConfiguration` object as you do in your first snippet: in this case OpenIddict will copy it from `options.Issuer`. I just find the more "complete" version a bit more explicit 😃
