### ISSUE TITLE
Upgrades from 1.5 to 1.6

### ISSUE THREAD

**Issue by tripurarisingh1** [OrchardCMS/OrchardCore#13691]
I wanted to upgrade my orchard CMS from 1.5 to 1.6 and trying multiple ways to update it but it's could not update, Kindly provide solutions for that.

**Comment by hishamco** [comment]
You just simply upgrade the OC packages, also you might have a look to https://docs.orchardcore.net/en/latest/docs/releases/1.6.0/

**Comment by tripurarisingh1** [comment]
I am updating NeGet packages for orchard core, it's updating 1.6. 
it's mean it's updated on 1.6 right ?

**Comment by hishamco** [comment]
So, what's the problem then?

**Comment by tripurarisingh1** [comment]
Nothing, 
Only wanted confirmation no need to change anywhere only update NuGet packages for updating Orchard CMS 1.5 to 1.6.

**Comment by hishamco** [comment]
You need to change the NuGet packages as well as read the docs in case there's a behavior changes

**Comment by hishamco** [comment]
You need to change the NuGet packages as well as read the docs in case there's a behavior changes

**Comment by dsghi** [comment]
Random side comment, it might be helpful if the admin section displayed the version number, as it did in the old orchard. That could alleviate confusion around upgrading and what version people have running. Perhaps it could even display an update available notice when not running the latest version.

**Comment by hishamco** [comment]
FYI @dsghi I already created a System Module as a part of OCC that might help you with this situation https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/tree/main/src/OrchardCoreContrib.System

**Comment by sebastienros** [comment]
> Perhaps it could even display an update available notice when not running the latest version.

We did that in O1 but that was an issue for privacy reasons because people might be afraid we'd track their usage by "calling home". If you see a CMS showing a world map of all their active instances, that's what they do.

I assume we could do that using nuget these days, by checking the latest package available. Or at least with a custom feature that would check on demand (checking on all requests in the dashboard might be expensive). Could also be a custom widget for the dashboard. I think it deserves it's own issue to track a solution.
