### ISSUE TITLE
Support IAsyncDisposable in DI

### ISSUE THREAD

**Issue by gvkries** [OrchardCMS/OrchardCore#13716]
### Is your feature request related to a problem? Please describe.
It is currently not possible to use types that only implement `IAsyncDisposable` in DI, because `ShellHost` and `ShellContext` are not async disposable.

### Describe the solution you'd like
`ShellHost` could implement `IAsyncDisposable` to allow more flexibility for modules.

### Describe alternatives you've considered
This feature is optional of cause, we can always dispose synchronously.

**Comment by sebastienros** [comment]
Would you be able to try and provide a PR?

**Comment by gvkries** [comment]
It might take some time cause I'm busy, but I can do it.

**Comment by jtkech** [comment]
Yes I thought about it recently but didn't start anything on the fly because it is a sensitive area, a Shell may release other dependent Shells, this is the last active child scope that releases its parent shell.

The whole would need to be async to be able to call a `DisposeAsync()` asynchronously.
