### ISSUE TITLE
TenantValidator unit tests are failing frequently

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#13723]
I just notice that `TenantValidator` unit tests are failing frequently when we submitting a PR, the following is a sample of logs:

```
[xUnit.net 00:00:04.58]     OrchardCore.Modules.Tenants.Services.Tests.TenantValidatorTests.TenantValidationFailsIfInvalidConfigurationsWasProvided(name: "dEfAuLt", urlPrefix: "", hostName: "", featureProfile: "Feature Profile", errorMessages: ["The tenant name is in conflict with the 'Default' "...]) [FAIL]
  Failed OrchardCore.Modules.Tenants.Services.Tests.TenantValidatorTests.TenantValidationFailsIfInvalidConfigurationsWasProvided(name: "dEfAuLt", urlPrefix: "", hostName: "", featureProfile: "Feature Profile", errorMessages: ["The tenant name is in conflict with the 'Default' "...]) [3 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 1
Actual:   2
```

**Comment by sebastienros** [comment]
This is called a flaky test, disable it, file an issue that it needs to be made more deterministic, fix it.

**Comment by jtkech** [comment]
The same `SiteContext` is re-used by multiple tests, and some tests are using `GetOrCreateShellContext()`, which may interfere with tests using same tenant names and checking for example if a tenant already exists, but it depends on the execution order of tests.

Also `GetOrCreateShellContext()` adds and registers a shell in `ShellHost` but without any persited `ShellSettings`, which may break other tests.

Some tests are isolated because they generate unique tenant names.

**Comment by hishamco** [comment]
> The same SiteContext is re-used by multiple tests, and some tests are using GetOrCreateShellContext(), which may interfere with tests using same tenant names and checking for example if a tenant already exists, but it depends on the execution order of tests.

Can I use a scoped `SiteContext`?
