### ISSUE TITLE
Update ASP.NET packages to 2.0.5

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1373]
Will src\OrchardCore.Build\Dependencies.AspNetCore.props be updated to use the version 2.0.5 for MicrosoftAspNetCorePackageVersion ?

If I use the OC.Application.Cms.Targets nuget package in a custom web app, can I upgrade the version or Do I have to stick to the version used by the nuget ?

**Comment by jtkech** [comment]
I think it may work because packages dependencies just specify a minimum version to use (e.g 2.0.1).

Just tried.

- So, i used our web app where i replaced all `ProjectReference` with last `PackageReference`.

- Then i replaced the reference `Microsoft.AspNetCore 2.0.1` with `Microsoft.AspNetCore.All 2.0.5`.

- Then i removed  `.Mvc.Razor.ViewCompilation` which is included in the `.All` package.

Then, i didn't try everything, only start the app and go to the admin, but seems to work well.

**Comment by sebastienros** [comment]
We should not use .All in our source code. USers are fine doing it if they want, it will work.
I keep this one open though as we need to update the `dependencies.props` file to use 2.0.5. (I think UniverseCoherence)
