### ISSUE TITLE
TheBlogTheme's footer should display the current year instead of 2021

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/OrchardCore#13740]
### Describe the bug

2021 is wired into [the footer snippet](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Themes/TheBlogTheme/Recipes/Snippets/footer.html#L31), but [TheAgencyTheme renders the current year with JS](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Themes/TheAgencyTheme/Recipes/Snippets/footer.html#L9), so it should just do the same.

### To Reproduce

1. Set up the site with the Agency recipe.
2. Scroll down to the bottom.
3. See the copyright notice showing the year 2021.

### Expected behavior
The copyright notice should show the current year. Time travelers might not be able to reproduce the problem under specific circumstances.

**Comment by hishamco** [comment]
It depends some add the current year beside the Copyright, and some use the year of publishing the theme, or website. Anyhow we will fix it

**Comment by Piedone** [comment]
If we really want to be nitpicky, the year should be when the tenant was first set up. This is because it's the year when your copyright starts (with the first content), it shouldn't just be the current year.

**Comment by BenedekFarkas** [comment]
> If we really want to be nitpicky

It's a question of when, not if. :D

Anyway, yeah, in O1 terms, I'd just grab the CreatedDate of the Site content item.

**Comment by sebastienros** [comment]
By design! You should come to the meetings more often ;)

Legally a copyright is valid after the date mentionned, so stating 2023 has no more value than 2021.
Also we don't make it dynamic because we don't have to and doing so is just slower or requires caching.
Updating to whatever the source template is sufficient.

**Comment by hishamco** [comment]
> Also we don't make it dynamic because we don't have to and doing so is just slower or requires caching.
Updating to whatever the source template is sufficient.

I think using `now` filter is fine not much data to cache :)

**Comment by Piedone** [comment]
That's why I'm saying the year should be when the tenant was first set up. Having 2021 for everyone doesn't make sense legally, and you're forced to override the template for every single new site. I don't see how this would be desired, or good enough. I'd consider this a trivial issue with a low priority, but certainly something that's valid.

**Comment by Piedone** [comment]
So, I don't think this should be closed @sebastienros.

**Comment by Piedone** [comment]
@sebastienros?
