### ISSUE TITLE
App hangs when executing recipe.

### ISSUE THREAD

**Issue by ludovic-th** [OrchardCMS/OrchardCore#13914]
### To Reproduce
 - Execute a recipe (from Migrations folder) with the IRecipeMigrator in a migration
 - This recipe calls another recipe (RecipesStep) from Recipes folder
 - The app hangs.

### Expected behavior
Both recipes should execute normally.

Details :
Looks like there's an interlock here on "SHELL_ACTIVATE_LOCK" key here : https://github.com/OrchardCMS/OrchardCore/blob/7cb1cd2dc69ff5c5305e9feee80ca59d43d793b4/src/OrchardCore/OrchardCore/Locking/LocalLock.cs#L45C31-L45C31

Can be reproduced using [code here](https://github.com/ludovic-th/OrchardCore/commit/16ed7401e1e176e0cdea111c20f8ec2ce8d5f4b0).
Activate Demo module after launching and setup OrchardCore.Cms.Web.

**Comment by jtkech** [comment]
Yes, each recipe step is executed in its own shell scope that will try to activate the shell if not yet done, but the migrations are executed in a shell scope while it is already activating the shell.

That's why the recipe migrator set `recipeDescriptor.RequireNewScope` to true, this meaning that we should use the current shell scope, not a new one that will try again to activate the shell.

But when using nested recipes it looks like we don't flow up this property.

I will provide a PR and let you try it.
