### ISSUE TITLE
Add an extra parameter to AddOrchardCms(...) to pass a custom list of Modules

### ISSUE THREAD

**Issue by bsamba** [OrchardCMS/OrchardCore#1396]
Passing a customized list of mudules will allow use of the default implementation. `AddOrchardCms(this IServiceCollection services, params string[] modules)`

**Comment by sebastienros** [comment]
Makes sense, same for tenants, if not already the case with the default `AddModules` extensions.
Also it might already work with the `tenants.json` configuration file.

**Comment by bsamba** [comment]
Exactly!

**Comment by rserj** [comment]
I think we should be able to configure how to get those modules, we should support multiple sources
1) As it works now, with project/nuget reference
2) Able to download modules via configured nuget feed
3) Load modules via specified physical location

**Comment by rserj** [comment]
Probably @jtkech have some ideas too

**Comment by jtkech** [comment]
@rserj 

Hmm, if you mean loading at runtime it could be very complex, at some point we were doing dynamic compilation and dynamic loading. But, even we don't do dyn compilation where compile time assemblies could be not the same as the runtime ones, we still need to parse the dependency graph to know what we need to load. So, loading could be as simple as loading a portable assembly which only references other ambient assemblies (referenced by the app). Otherwise it could be very complex, and also if the assembly is framework dependent, even more if some of its dependencies are framework dependent, and so on ...

so, it was working, but we didn't keep dynamic compilation and also any **dynamic loading**, i wrote a wiki page on this which has been removed. So, but I'm open to anything we might want, to make an app working, any module needs to be referenced as a project (from any location) or as a package (from any feed) but at build time.

That said, about this issue, i'm working in a branch where you will be able to do (see #1766).

      services.AddOrchardCms();
          .WithDefaultFeatures("OtherDefaultFeature")

          // And custom tenant configuration could be added here.
          .ConfigureTenantServices<Dep1, Dep2 ...>((collection, dep1, dep2 ...) =>
          {
              // some stuff.
          })
          .ConfigureTenant((app, routes, sp) =>
           {
              // some stuff.
           })

**Comment by rserj** [comment]
I meant just simple Loading, Assembly.Load as we have now for references, without compilation.
Probably we should implement it similar to Orchard 1 with 
`PrecompiledExtensionLoader->IAssemblyLoader`
In such case Developer must make sure about all dependencies and version compatibility by himself, from our side we may check MinOrchardVersion in Feature/Module Manifest with Current Installed Orchard.

It seems we had something before, please see `AddExtensionLocation `extension
https://orchardcore.readthedocs.io/en/latest/OrchardCore/OrchardCore.Modules/README/

**Comment by jtkech** [comment]
Yes we had, but without dyn loading we didn't need anymore search locations. Maybe you could read #451 which also talk about dyn loading. I don't remember all details, just a little afraid to make it consistent and about all issues it could introduce. But again, i'm open to re-integrate seach a feature if we need it.
