### ISSUE TITLE
Why the created user is enabled

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#14037]
I'm not sure why the new user should be enabled by default, the default behavior should be disabled, then the admin can allow it to log in, perhaps it might needs an email confirmation

**Comment by MikeAlhayek** [comment]
A user is enabled by default to allow them to login. If the user require email confirmation, then they won't be able to login without conforming their email first.

If you have a use case when user should be disabled by default, please elaborate more about your use case.

**Comment by hishamco** [comment]
> A user is enabled by default to allow them to login

I knew :) but the case in many websites that you need some sort of approval before the user is able to log in, let us check the default behavior in ASP.NET Core Identity

**Comment by MikeAlhayek** [comment]
Sounds like you are looking for a custom membership approval process in addition to the email verification. 

You can accomplish that by using the available user events. I would use a claim instead of enable/disable status. Like if the user has an "approved" claim, redirect them to a page that read "user waiting for approval" or something like that. 

Either way, in a default setup, enabling the user by default makes perfect sense to me.

**Comment by hishamco** [comment]
> Sounds like you are looking for a custom membership approval process in addition to the email verification.

Nope

> Either way, in a default setup, enabling the user by default makes perfect sense to me.

I never mind if this is the default behavior of ASP.NET Core Identity, or this something custom for OC
