### ISSUE TITLE
When DisableLocalLogin, LinkExternalLogin should not confirm the password again

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#14215]
The scenario is as follows:
In my system, local account login is disabled, and all users can only log in through external authorization. OC is conveniently configured accordingly.
However, we have recently encountered some issues where we are unable to refer to a user's account until the user has logged in with external authorization. So I created this account manually through the administrator role and set a random password. However, users are required to enter this password when they log in for the first time with external authorization.

In my opinion, after we set `DisableLocalLogin`, can we disable this function? Allow externally authorized users to automatically connect to accounts with the same name or email address?

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/eece7842-9728-43ed-a80d-e9713cbfd723)

**Comment by MikeAlhayek** [comment]
> In my opinion, after we set DisableLocalLogin, can we disable this function? Allow externally authorized users to automatically connect to accounts with the same name or email address?

Is **Allow externally authorized users to automatically connect to accounts with the same name or email address?** a settings in OC? I do not see it being an option. Is that something you are using or something you are suggesting to add?

Either way, if you do not want to link external users to existing account, how would you define the new username or email address for the new users since each user must have a unique email and username?

**Comment by MikeAlhayek** [comment]
Yes I understand. For security reasons it is not a good idea to blindly link external user to existing user without another layer of validation.

Why? Will, Imagine you setup your site with a super user called "abc". Also, assume you enabled external provider for the same site. Also assume that someone other than you have a username called "abc" at the external provider. Now that external user can take over your internal SuperUser account! Bad news! 

However, if you continue to force to provide the internal password for existing user "as we do today", then we can safely ensure that you are the actual SuperUser before allowing you to like it. This only happens if the the local database already has a username created with password and the same username logs in using the external service.

**Comment by hyzx86** [comment]
Whether it is `Local password login` or `external authorization`, they are a form of identity authentication.

And when we integrate an external authorization, it means that the authenticated user should be completely trusted, right?

Of course, if the user chooses to enable external login along with local login, then the password is set by the user and there is no problem here.

**Comment by MikeAlhayek** [comment]
> And when we integrate an external authorization, it means that the authenticated user should be completely trusted, right?

Yes. But if a user already exists with a password in the database. We don't just allow to blindly link it to external user without password confirmation. There is a security flaw in you suggestion which we can't bring to OC.

**Comment by hyzx86** [comment]
Okay, thank you. my usage scenario is only internal to the enterprise, so this solution may only apply to my scenario
