### ISSUE TITLE
Does OrchardCore not support {% layout 'xyz' %} ?

### ISSUE THREAD

**Issue by tanriverdim** [OrchardCMS/OrchardCore#1425]
Syntax error, expected: if, endif, elsif, else, unless, endunless, case, endcase, when, for, endfor, continue, break, comment, endcomment, raw, endraw, cycle, assign, capture, endcapture, increment, decrement, include, render_body, render_section, page_title, display, helper, shape, link, meta, resources, script, style, block, endblock, a, enda, zone, endzone.

**Comment by sebastienros** [comment]
It doesn't, but I am wondering if we could handle it by letting views switch they layout shape that is used.

@jtkech do you see what I mean, does it make sense, should also work in razor. We wouldn't need to define custom layout templates/alternates.

**Comment by jtkech** [comment]
Humm, because we have `public class LiquidPage : RazorPage<dynamic>`, when displaying a liquid view, at the 1st level we still go through the razor engine. Then, when we contextualize a liquid view we don't keep all razor view properties but we still hold `ViewContext` => `View` => `RazorPage` => `Layout`. So, if it works with razor, it would be easy to make it working with liquid with a new tag.

**Comment by tanriverdim** [comment]
Actually I want to make a multi-purpose theme. According to the types of content I want them to edit templates from the Admin Panel.

example 
Default Layout -> Layout.liquid
Blog post -> Admin Templates -> Content__BlogPost -> {% layout 'LayoutAbc' %} 
Article -> Admin Templates -> Content__Article ->  {% layout 'LayoutXyz' %}
etc...

**Comment by sebastienros** [comment]
Right, now sure yet it can work from razor, maybe, after all I think the theme module is just calling into dynamically replacing the Layout view by our own that is then calling into the Layout shape and looking for a template. So the easiest might be to just add an alternate to the current shape and it would fine another template.

**Comment by sebastienros** [comment]
Think about it, just add an alternate to the current layout shape ;) This can be anything, like `abc`. That would just work, and you could even define the template in the admin. A Razor helper and liquid tag should be trivial to make, resolving the Layout using the Layout service.

**Comment by jtkech** [comment]
Just tried for testing and i could get it working.

This is only for testing because i needed to do, in an intermediate view, what our precompiled `Layout` view view do (see below). But this could be replaced by dedicated razor / liquid helpers.

- So, i created a `Content-Article.cshtml` template in which i added.

      Layout = "LayoutTrigger";

- Then i created this `LayoutTrigger.cshtml` intermediate view which will be replaced by our helpers.

      @{
          this.ThemeLayout.Metadata.Alternates.Add("LayoutTest");
          var body = RenderLayoutBody();
          this.ThemeLayout.Content.Add(body);
          Write(await DisplayAsync(ThemeLayout));
      }

- Then i created a custom `LayoutTest` view.

![layout](https://user-images.githubusercontent.com/8586360/35709836-a4518250-07b4-11e8-99f6-119f41374646.png)

**Comment by sebastienros** [comment]
Then that should work. And we can intercept the Layout property maybe on our base razor page and convert it to adding an alternate on the shape instead.

**Comment by jtkech** [comment]
Yes, this is what i did above, but because for testing i use an intermediate view, our precompiled `ThemeLayout` is not executed, so i needed to do other things.

Oh, let me re-try it without intermediate view, so by just using this in a template view.

    ThemeLayout.Metadata.Alternates.Add("OtherLayout");

**Comment by jtkech** [comment]
Yes, it works.

So, already easy to do with razor, and with liquid as said above we can retrieve the `ThemeLayout` through an helper, and we already have a filter to add alternates ...

**Comment by jtkech** [comment]
Just for the fun

- Just added this in the context.

      context.LocalScope.SetValue("ThemeLayout", layout);

- Then in a liquid view.

      {% assign test = ThemeLayout | add_alternates: "Layout2" %}

And it works.

**Comment by jtkech** [comment]
So, i could do a PR for this.

- Do we need a razor helper? because we already can just do

      ThemeLayout.Metadata.Alternates.Add("OtherLayout");

- Then, for liquid, we could just add `ThemeLayout` to the context because it is a shape and we already have filters to act on.

- Hmm, can we execute a filter without using a tag? Maybe good to create a special tag which do nothing just to use filters on any given input, e.g a shape.

- Otherwise, would we want a liquid `Tag` or a `Filter`? If a filter, same question as above for the usage.

**Comment by sebastienros** [comment]
We need a tag for liquid. Like the standard layout tag in liquid.
And a property in the base class that when assigned will insert an alternate at the top of the list of alternate- > `ViewLayout = "MyLayout"`. By default the `get` will return `Layout`, use a private property to store it.

**Comment by sebastienros** [comment]
We also need to ensure that this alternate is not actually preserved across requests, I am not really sure of it.

**Comment by jtkech** [comment]
Just saw your comment, see my answer in #1433

**Comment by tanriverdim** [comment]
Thanks a lot
