### ISSUE TITLE
In need of the Datetime field

### ISSUE THREAD

**Issue by konstrui** [OrchardCMS/OrchardCore#1438]
I would like to see the Datetime field as option when creating fields.
Probably somewhere on the roadmap, but just to be sure...

I'm creating blogposts and I'm not able to sort on a (publish) date?

**Comment by sebastienros** [comment]
I agree with the lack of this field, we'll fix it soon. But you already have a Published date. It's the `CreatedUtc` field in the Content Item, which is also indexed in the database if you are using custom queries.

CreatedUtc: The first time the content item was published (this is what you need for Blog posts ordering)
PublishedUtc: The last time the content item version modification was published
ModifiedUtc: The last time the content item version was modified

**Comment by sebastienros** [comment]
To give more details on why we don't have a DT field already, we decided to postpone from beta1 as we need to take Orchard1 feedback into account due to TimeZone complexity, and also the fact that we need more than one field, but one that also represents only a Time or a Date without Time Zone, like absolute time and date.

**Comment by Skrypt** [comment]
I'll take a look at this issue this week.

**Comment by agriffard** [comment]
Ok, @Skrypt : I created a PR with a basic implementation of DateTimeField : #1828

**Comment by sebastienros** [comment]
Without looking at the PR, I would expect to see two fields. Can you point me to the discussion I had with Daniel on Orchard 1 with a design that was discussed to solve TimeZone and also Time-Only data?

**Comment by agriffard** [comment]
https://github.com/OrchardCMS/Orchard/issues/6731

Ok, I will a TimeField.

**Comment by Skrypt** [comment]
Seems like a pretty dense explanation. Need to re-read carefully. But the issue should be easy to resolve with NodaTime Duration or Offset types.

**Comment by sebastienros** [comment]
@Skrypt 

Scenario:
- You want to create a Calendar item that will contain a date only, but even if the timezone changes display this date, like an Anniversary, or a Birthday. The date shouldn't change based on the current user's timezone, or site's timezone. Same for Time Field.
- DateTime field is already solved and works great, it's a point in time so will vary based on the context's timezone.

I confirm my recommendations. No need for using Nodatime here, `IClock.UtcNow` is perfect for DateTime field.

**Comment by Skrypt** [comment]
I agree that the Date itself should not change but you still need to know the context in which this Date is relevant. I could register my credit card on some website with a specific expiration date ; though if I'm not storing the TimeZone context on that date I will never know when it really expire. So someone who's running a server on a TimeZone that is not using Gregorian calendar could store February 29 2019 but this date would need to be converted still for the expiration to apply.

Still for a Birthday, if I'm on a different Calendar than Gregorian this February 29 2019 could be a different day for someone not on a Gregorian calendar. The date itself though, since I'm born in a specific TimeZone should always be displayed February 29 2019 on my User Profile. Though if my Chinese friends want to know when to celebrate my birthday on their Calendar then they need to convert this date so it still needs a TimeZone associated with it.

**Comment by agriffard** [comment]
We could add a setting to specify if we allow to display/edit the seconds and then use a "step" attribute = 0 or 1 that will prevent or allow to pick the seconds.
