### ISSUE TITLE
Add a way to Remove User from a Role

### ISSUE THREAD

**Issue by elaurentin** [OrchardCMS/OrchardCore#14632]
### Is your feature request related to a problem? Please describe.
To supplement existing workflow **AssignUserToRole**, add the following Activities:
**RemoveUserRole**: Remove a User from a role. This is very similar to AssignUserToRole but the ExecuteAsync to remove the user from a role instead

**SelectUsersInRole**: This activity to output users list (or email) as property to create a mailing list to send email or notifications.

This is to supplement:
User Workflow: User created event and assign user to role #3489

### Describe the solution you'd like
**RemoveUserRole**: has same properties as AssignUserToRole but implementation calls
`await _userManager.RemoveFromRoleAsync(user, roleName)`
in the ExecuteAsync handler

**SelectUsersInRole**: this activity has 2 properties and will create a workflow output variable:
**PropertyName**: the workflow property output name to create, which can then be reused through expression
**RoleName**: the User Role to get all users name or email

### Describe alternatives you've considered
The activities **AssignUserToRole** and **RemoveUserRole** can be combined as **UpdateUserRole** but this would break the interface.
**SelectUsersInRole**, may need to readjust the activity name for OC. Also, may need a different parameter to select the field for "UserName" or "Email".

![OC-Submission-UserRole](https://github.com/OrchardCMS/OrchardCore/assets/5598813/6ef28abf-5fe1-4437-a979-b33bb26b83e6)

**Comment by MikeAlhayek** [comment]
@elaurentin can you submit a PR for `Remove User Role Task`? the implementation should be very simple here and should be almost clone of `AssignUserRoleTask`.

Maybe you can enhance the Display Driver UI but letting the user select (using a checkbox list) which roles to update instead of a text box.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/52577d65-713b-4073-af06-57272e9bac06)
