### ISSUE TITLE
Filtering content with a SQL query

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1485]
Is it possible to filter a SQL query by a field in the Content column of the Document table?

Example- I have a content item with a field on it, I'd like to return all document ids where the field matches a given value.

I'm guessing that Lucene is the way to go here, but just want to make sure that it's not possible with SQL queries before I switch over to Lucene.

**Comment by sebastienros** [comment]
It's not possible right now. Only with Lucene as it "indexes" the document.
We could do the same thing for SQL by creating a generic indexing schema, which is exactly what is being done in Orchard 1 for Queries/Projections.

What I had in mind also was to be able to use what YesSql is doing a create custom Map/Reduce indexes dynamically. Either by exposing some metadata configuration layer in YesSql, or generating dynamic classes from Orchard to provide custom indices, and run migrations automatically too. We could then provide custom logic in JS to create these new classes (somehow what RaveDB is doing with Jint).

Also related, this is how I want to change Lucene indices. Let users provide some JS code that return the document to index. This way we are free to filter and alter any data from a content item to be indexed, instead of having the logic defined by the field types themselves. A Lucene index becomes a Javascript map/reduce function. And we could apply the same mechanism to store these indices in tables (generic or specific schema). Each change on the index would imply re-indexing the content items.

**Comment by sebastienros** [comment]
Some ideas
- be able to create different types of indices, one could come from the UI and others from a javascript function.
- or have indexing steps that can provide data to an index (js, BodyPart Step, ...)
- index sources to provide data to be indexed. One would be content items (drafts, content types, ...) but we could also index users, ...

**Comment by robsrip** [comment]
How do you structure a lucene query to filter by a content field? When querying for content items in /OrchardCore.Lucene/Admin/Query, I can see ContentType.Field columns listed, but I haven't been able to construct a query to access those values.

**Comment by Skrypt** [comment]
You can use alternatively JSON function in SQL Server https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017 for filtering JSON with native SQL Queries. SQLite has also some functions too https://www.sqlite.org/json1.html

Though it's different from one DB to the other. @sebastienros would this be needed to be added to YesSQL SQL dialect for this to work or I'm completely wrong?

**Comment by robsrip** [comment]
That would be an awesome solution, but the SQL query template doesn't appear to support JSON_VALUE or the CAST needed to pass Content into it.

**Comment by sebastienros** [comment]
If you can see the name of the column that contains the field value in the index, just add a TermQuery in the Lucene query. 

Here is an example which is created with the Blog recipe:
```
{
  "query": {
    "term" : { "Content.ContentItem.ContentType" : "BlogPost" } 
  },
  "sort": { "Content.ContentItem.CreatedUtc": { "order": "desc" } },
  "size": 3
}
```

Replace `"term" : { "Content.ContentItem.ContentType" : "BlogPost" } ` with the field and value you want to filter. Look at ElasticSearch documentation to add logical operators.

**Comment by P-h-e-m-m-e-r** [comment]
Hello! Can anyone give an example how to include parameters to lucene query like above?

**Comment by sebastienros** [comment]
```
{
  "query": {
    "term" : { "Content.ContentItem.ContentType" : {{ contentType | json }} } 
  },
  "sort": { "Content.ContentItem.CreatedUtc": { "order": "desc" } },
  "size": 3
}
```

**Comment by P-h-e-m-m-e-r** [comment]
Sebastien, thank you for your reply, but for some reason that doesn't work

> ```
> {
>   "query": {
>     "term" : { "Content.ContentItem.ContentType" : {{ contentType | json }} } 
>   },
>   "sort": { "Content.ContentItem.CreatedUtc": { "order": "desc" } },
>   "size": 3
> }
> ```

with the parameters object
```
{ contentType : "BlogPost" }
```
Where is my error?

**Comment by sebastienros** [comment]
Since we change the default encoding for Lucene queries, the solution has changed. You can use either:
- `"{{ contentType }}"`
- `{{ contentType | json | raw}}`

**Comment by sebastienros** [comment]
The issue was that it was generating `"BlogPost"` which was then encoded to `\"BlogPost\"` and made an invalid json document.

**Comment by Skrypt** [comment]
We can close this one?

**Comment by aminmohammadi05** [comment]
> We can close this one?

Hi, would you please do a favor to me? I want to run this query on Orchard that return 3 random products:
`SELECT TOP (3) * FROM ContentItemIndex WHERE (ContentType = 'Product') AND (Published = 1) ORDER BY newid()`
The query works on SQL server very good but in Orchard gives this error:
`Syntax error, expected: OVER, AS, id_simple, ,, HAVING, ORDER, LIMIT, OFFSET, ), UNION, ;, SELECT, FROM, WHERE, GROUP at line:0, col:15`
![Lcmow](https://user-images.githubusercontent.com/20872120/198877891-3efc37a9-d215-49b5-aa72-bfc23d5e280b.png)
