### ISSUE TITLE
Where we can edit content of Template through VS 

### ISSUE THREAD

**Issue by adopilot** [OrchardCMS/OrchardCore#1492]
We are trying to build up one production site using Visual Studio and Code from Git Hub.
For main theme we are using The Agency Theme and we want to custimize it.
We are able to without problem edit CSSs in `/OrchardCore.Themes/TheAgencyTheme/wwwroot/css`
But I do not know How to change texts in for template theme.
When I do changes in  /OrchardCore.Themes/TheAgencyTheme/index.html there is no reflection on ruining site. I am able to change default layout through web gui. But for easier developing  I'll love to edit theme also in  VS so it is all in one place.

**Comment by jtkech** [comment]
- So here, in the admin UI, in the `Templates` pages you have the `Content__LandingPage` template where all is done. Notice that when editing it, at the bottom you have a preview button to see the changes live. E.g you can have your editor on the left and the preview window on the right. Note: you may have to navigate in the preview to see your changes.

- That said, what you can also do is to copy the content of this template and paste it in a new `TheAgencyTheme/Views/Content-LandingPage.liquid` file. Then, because the database template has a higher priority (regardless of the currrent selected theme), rename it through the admin UI e.g by appending a number. Then, because in debug mode assets files are served from their project location, you can update your new template file while the app runs and see the changes ...
