### ISSUE TITLE
elasticsearch index reset or rebuild triggers error 

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#15083]
When enabling elastic search and creating an index if you try to reset or rebuild the index I get the following error : 

I am using "ConnectionType": "CloudConnectionPool" in the appsettings to connect to elastic search using a cloud Id.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/2ce6db54-5f63-445d-8446-5b9c073ecd96)

@Skrypt @MikeAlhayek

**Comment by MikeAlhayek** [comment]
It seems to be data related.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/b10233b0-73c1-48aa-817d-1c799a3c3f4f)


But also, look at the yessql warning before 

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/7a410f76-7979-4e1f-bdb0-01e96ae7a507)

If you can somehow export your content-type and content-items that are expected to be indexed, I can try to reproduce it locally. Otherwise, you may want to take your content definition and items and import them on a new site using OC source and trace the problem. 

@Skrypt may have other ideas.

**Comment by giannik** [comment]
It happens even on an index with an indexed content type that has no content items yet.

**Comment by MikeAlhayek** [comment]
What version are you using? I just tried to reset an index and it worked for me. I think the code I tested is using 1.9 preview

**Comment by giannik** [comment]
in the indexingTasks table i had some contentitem ids for indexing from a year ago. I deleted all these records  and started from zero and it worked.
