### ISSUE TITLE
ContentTypeDefinitionRecord and other names are confusing

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1515]
I think these names are leftovers from O1. Consider renaming them since they are not records anymore.

ContentTypeDefinitionRecord
ContentPartDefinitionRecord
ContentPartFieldDefinitionRecord

**Comment by sebastienros** [comment]
Maybe time to define some convention for document class names, while we are breaking things.

**Comment by sfmskywalker** [comment]
So basically replacing the word "Record" with "Document"?
What if you have nested objects within a document? E.g. with Workflows, I have `WorkflowDefinitionRecord` and `ActivityRecord`, where the `WorkflowDefinitionRecord` has a `IList<ActivityRecord>` property.  So the WorkflowDefinitionRecord is in fact a document, but the ActivityRecord is more like a node within that document. So perhaps a good convention might be to suffix document-level objects with "Document", and nested object types with "Node", "Element" or even just "Record" (as in a record within the document). Even better might be to not suffix at all for nested objects, but in the case of the Workflows module, there's already a type called `Activity` (which contains executable code via `Execute` etc.). Technically not a problem since both `Activity` and `ActivityRecord` live in separate namespaces, but I deliberately used the "Record" suffix to avoid confusion between the two types. 

Regardless, I think the Document suffix is a good convention, and no suffix for nested types of that document.

**Comment by sebastienros** [comment]
wip on `sebros/records`

**Comment by sebastienros** [comment]
Won't implement
