### ISSUE TITLE
Manage Own Media permissions not working for given role

### ISSUE THREAD

**Issue by vmahant** [OrchardCMS/OrchardCore#15159]
### To Reproduce
1. Go to Security > Roles > Choose any role say "Editor"
2. Search for "Media"
3. Scroll down to "Manage Own Media" and click that option
5. When the Editor login to the Admin panel. Users with Editor roles can still View / Delete other's Media

### Expected behavior
As a user, if any role has permission "Manage Own Media" can view or delete its own Media files (Images, Videos, and Documents) and cannot view/ delete other Media files in the admin panel

### Screenshots

<img width="823" alt="image" src="https://github.com/OrchardCMS/OrchardCore/assets/31914591/d4eae9da-6855-4f5e-b9e7-40ccd0506dea">

**Comment by hishamco** [comment]
I think this is a known issue, @Skrypt current me if you remember

**Comment by gvkries** [comment]
This is by design, only media below the '_Users/{userid}' folders are considered as 'own' media.

**Comment by hishamco** [comment]
I think it's duplicate for #14433

**Comment by andystevenshbi** [comment]
> This is by design, only media below the '_Users/{userid}' folders are considered as 'own' media.

This does make sense that a user can only manage media within their own {userid} folder, but shouldn't the top level media path be restricted.  Currently a user with permission to manage own media only can also manage media in the root folder - including creating and deleting sub folders from the root path?

Is there another way to restrict the media path so that the user only sees and has access to their userid folder and below?

**Comment by gvkries** [comment]
At the moment this is a missing feature. I currently have a similar requirement, maybe I can come up with a feature proposal.

**Comment by gvkries** [comment]
> I think it's duplicate for #14433

True... 😊
