### ISSUE TITLE
Field Type Selection Missing In Content Definition Editors 

### ISSUE THREAD

**Issue by clmcgrath** [OrchardCMS/OrchardCore#1520]
![image](https://user-images.githubusercontent.com/452012/36611760-7add2c18-18a2-11e8-9b4b-9bcfa2833cb5.png)

When you try to add a field to a custom content part the Field Type input is missing

Likely happening in the View Partial for the editor template 

See These Paths for repro 
http://{ hostname }/OrchardCore.ContentTypes/Admin/EditPart/{ TypeName }
http://{ hostname }/OrchardCore.ContentTypes/Admin/AddFieldTo/{ TypeName }

**Comment by alberthajdu** [comment]
I think this is no longer an issue.
![1](https://user-images.githubusercontent.com/12067180/37350565-653b0598-26d9-11e8-8ec0-98b658a9ca99.png)

**Comment by clmcgrath** [comment]
I would say this is very much still an issue 
![image](https://user-images.githubusercontent.com/452012/37407815-01c03eb4-2771-11e8-85a1-38077e5e7c32.png)

v: 1.0.0-beta2-4892

**Comment by clmcgrath** [comment]
It appears the issue is with automatic activation of dependent modules when enabling the content module

**Comment by jtkech** [comment]
As i remember this is the content fields which depends on content types which depends on content. So maybe you have the content types and content modules enabled but not the content field module. If so, try to enable the content field module.

In fact, content doesn't depend on content types which doesn't depend on content fileds, this is content fields which depends on content types to be able to add functionalities to content types. I understand your feelling but if e.g content types also depends on fields we would have a circular dependency.

**Comment by clmcgrath** [comment]
noted

**Comment by clmcgrath** [comment]
it feels clunky tho how can you create a content type  with no field types ,  the ui reports a field type error if you try to create a content part  without  any field types present

**Comment by jtkech** [comment]
Yes, you're right, at the end types needs parts which needs fields. If there is no module which defines at least one part, you can still create one through the UI. So, here the singularity is that we can't create a field through the UI, so you need at least to enable a module which defines a field.

Yes, this is when you try to add a field to a part that you have an error message because you didn't provide any type. But existing parts can still be used, and i could create a new part without any field, but i agree here it would not make sense.

But if someone write a module where he defines the only fields he want to use, he may want to be able to disable our fields module without disabling the types module. Hmm, maybe to be clearer the types module would need to define at least one basic field, e.g the text field, so that people could see that there is only one field type available, and if they want more they need to enable other modules.

Or maybe just a clearer error message, so please open another issue if you have any other idea about what would be better to do.
