### ISSUE TITLE
Difference in CreateChildContainer  when cloning multiple of the same type vs one.

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#15361]
### Describe the bug

When cloning services using CreateChildContainer we have a difference in behaviour between cloing multiple of the same service (see: https://github.com/OrchardCMS/OrchardCore/blob/a27a75eaa9fbd9e193569a42d4cdab9fcd28903e/src/OrchardCore/OrchardCore/Shell/Builders/Extensions/ServiceProviderExtensions.cs#L89) to if we were cloning just the one (see: https://github.com/OrchardCMS/OrchardCore/blob/a27a75eaa9fbd9e193569a42d4cdab9fcd28903e/src/OrchardCore/OrchardCore/Shell/Builders/Extensions/ServiceProviderExtensions.cs#L60)

The big difference here is that one uses the implementation factory and the other doesnt.

Is there a reason we do this? and should it all be going through the same process regardless of if its one or not...

**Comment by hishamco** [comment]
Nice to see @Jetski5822 shine again :)

**Comment by Piedone** [comment]
Is this causing any issue, or does it surface some discrepancy?

After JT's passing, paging the only person who was there at the time: @sebastienros.

**Comment by gvkries** [comment]
Because I was working on the shell container factory recently, I took a quick look. If I understand this code correctly, it is an optimization if there is a single service only. In that case, if the result is not disposable, creating the singletons can be deferred until a tenant resolves them. Otherwise all services must be created immediately. 

So I think this should be kept, but the code is hard to understand. Maybe we can simplify it little bit.
