### ISSUE TITLE
Recipes do not support comments

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#15385]
The recipe reader doesn't support comments in Json (it's a mode that isn't turned on).

Which is annoying when you have a lot of recipes, and need to make notes in them, as to why you did something.

Not sure if the System.Text pr has gone in yet, might change with that, as it's a Newtonsoft config that needs to be set.

**Comment by MikeAlhayek** [comment]
Yes the STJ is already in main.

I think the reason why comments are not supported is because we parse using `JOptions.Document` which is not configured to allow comments. I think we need to change that to options that is derived from the `Base` options like 'Default' or create one a static instance for recipes.
