### ISSUE TITLE
how do we use OrchardSuppressDependency in o2

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#1562]
where is OrchardSuppressDependency which was in o1?

**Comment by jrestall** [comment]
Since dependencies are registered explicitly in Orchard Core within startup classes there is no SuppressDependency attribute anymore. You can suppress a dependency by replacing it with your own within your modules startup class.

See the following unit test as an example: https://github.com/OrchardCMS/OrchardCore/blob/06ba0292c1e3431c543c52105c84fa7e378dbb6e/test/OrchardCore.Tests/Shell/ShellContainerFactoryTests.cs#L104

**Comment by infofromca** [comment]
thanks
