### ISSUE TITLE
Custom Theme is not shown in Active Themes Page

### ISSUE THREAD

**Issue by iyhammad** [OrchardCMS/OrchardCore#1565]
I'm trying to create a custom theme. I've created a new class library with the below Theme.txt
```
Name: Startup Theme
AntiForgery: enabled
Author: Startup Theme
Website: http://Startup.com
Description: Startup Theme
```
When I run the application it shows my theme class library in the website as a module under Configuration--->Modules and I can enable it from there.
However, It doesn't show under Themes--->Active Themes as I used to see when I use Beta1. 
Also, any modification I do in Layout.cshtml it doesn't affect however Content-LandingPage.cshtml is picked up.
Am I missing something?
**Note: using V1.0.0-beta2-4715**

**Comment by jtkech** [comment]
Yes, there are no more `Module.txt` and `Theme.txt` manifest files, there are replaced by assembly attributes, see `Manifest.cs` in one of our themes as an example. Note: attributes can be defined in any cs files.

So, in your case, it is as you don't define anything and it becomes by default a module. But, because you reference `OC.Theme.Targets` it should become a theme, this will be fixed soon. Meanwhile, as said above, you just have to define a `Theme` attribute.

**Comment by iyhammad** [comment]
Thank you very mush it works.
