### ISSUE TITLE
Add option to use DefaultAzureCredential for Azure BlobFileStore

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#15663]
### Is your feature request related to a problem? Please describe.
Using a Managed Identity (DefaultAzureCredential) is safer than using connection strings. Also allows to use RBAC to control access.

### Describe the solution you'd like
A simple solution would be to add a boolean flag UseDefaultAzureCredential to BlobStorageOptions and instantiate the BlobFileStore according to it.
Or could have a more flexible solution similar to Azure KeyVault `.AddOrchardCoreAzureKeyVault(new DefaultAzureCredential())`

**Comment by Piedone** [comment]
Is this something you'd venture into contributing if I help with pointers?

**Comment by mariojsnunes** [comment]
Yes I'd be happy to

**Comment by Piedone** [comment]
Great! Some suggestions:

- I'd add a new `ManagedIdentityClientId` property to `MediaBlobStorageOptions` and possibly `BlobShellStorageOptions`. Not `BlobStorageOptions` because the Azure Image Cache of ImageSharp doesn't support it, and thus the corresponding OC feature to be merged under https://github.com/OrchardCMS/OrchardCore/pull/15028 doesn't either. There's nothing else to store for this feature, right? Or not even that, and we only really need a boolean flag?
- Be sure to update [the docs](https://docs.orchardcore.net/en/latest/docs/reference/modules/Media.Azure/), see https://docs.orchardcore.net/en/latest/docs/topics/docs-contributions/.

**Comment by mariojsnunes** [comment]
yep it is
