### ISSUE TITLE
Liquid cache tag

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1569]
Create a custom `{% cache %} ... {% endcache %}` tag that will reflect what the cache tag helper is doing.
Ideally replicating all the logic from the cache tag helper, which means russian doll cache invalidation.
This might be a complex piece of code if the logic is not reusable, in which case we can bridge to the cache tag helper class directly.

The goal is to be able to wrap database access tags to prevent sql queries.
Also investigate how to use our existing caching abstractions, like we use in shape caching.

**Comment by paynecrl97** [comment]
I've been meaning to create this exact ticket, and have been thinking about how it could be implemented for the past couple of weeks.

I can pick this up once the Content / Queries changes are done.

**Comment by sebastienros** [comment]
I'd like to see more sites not use the Layers module for performance and simplicity reasons, like creating a Flow that has all the widgets of a zone, with an alias, or just single widget, then render these by alias in the views directly. This would definitely require some sort of caching.

**Comment by paynecrl97** [comment]
Thinking out loud:

We'd need to allow the tag to specify two things: an identifier for the cache item, and an expiration.

The identifier in the most simplest case would be a cache key eg `{% cache "header" %}`. We could also look to allowing 'differentiators' (name not set in stone). Differentiators would vary cache keys by state. e.g., if our header content changes based on whether or not a user was logged in, then we could use auth state as a differentiator. We'd provide an extention point so that modules can contribute their own differentiators that cache tags can opt in to using.

Expiration could be a sliding window, after a fixed period of time, or on an event. Events would most likely be managed with tags, e.g. tag a cache item with a content alias, and when that content item is changed, the cache item is evicted. Tags could be extensible.

I think expiration policy should be set from within the cache tag itself. Example: a cache tag around a query that displays a list of content items- we won't know the content item tags until the query has executed etc....

```
{% cache "mylist" %}
  {% foreach item in Queries.BlogPosts | query %}
    {{ item | display_text }}
    {% cache_add_tag item %}
  {% endfor %}
{% endcache %}
```

We'd also need to be smart about evicting parent cache items when a child cache item it contains is evicted.

**Bonus**: Add the ability to define and edit cache policies from the admin UI.

e.g.

PolicyA: 
Differentiators: [x] Auth State [ ] Another differentiator
Expiration: [x] When content changes [ ] After a period of time

`{% cache "mylist", policy: "PolicyA"%}`

**Comment by sebastienros** [comment]
Maybe use a specific shape, because everything you mentioned is already handle there. Take a look at the menu liquid tag and how it caches the menu shape. The only thing that is not handled is the policy, but that's doable.

The notion of differentiator is called HashProvider (or something like this), it's a service that has to be fast and returns a hash that varies based on the state of what it tracks.
