### ISSUE TITLE
Culture Selector Display on front 

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#15774]
When the `Content culture selector` feature is enabled with French and English cultures, the currently selected culture is not displayed correctly: 

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/a09b16c5-1421-4220-99f3-9a027a354f80)

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/477ac0e6-f0dc-4251-8c09-8e7ccac63eee)

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/7c898057-30dc-4239-968a-fadc92376558)

**Comment by Piedone** [comment]
What would be the correct display?

**Comment by agriffard** [comment]
> What would be the correct display?

In admin, the currently selected culture shows the friendly name of the culture, not the culture code : 

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/73db82f2-3361-4c27-9185-6c03de8690dd)

That is waht I expect to see.

**Comment by Piedone** [comment]
I see. It seems we just need to use `@currentCulture.Name` instead of `@currentCulture` [here](https://github.com/OrchardCMS/OrchardCore/blob/2b84c667563ad329a6e13c1960f9497b99f3bf6e/src/OrchardCore.Modules/OrchardCore.ContentLocalization/Views/ContentCulturePicker.cshtml#L19). Looks like something a new contributor could take on.

This isn't a regression, right?

**Comment by hishamco** [comment]
I think it's a regression, I remember everything was working fine

**Comment by Piedone** [comment]
Indeed it is: https://github.com/OrchardCMS/OrchardCore/commit/980f322c62210d3390c8005c27bf9560fa7b996d#diff-646554b6305f761642dc52e09e1cf0660af19bc6f28727f41723b21f147f129c. So we should fix this for 1.9.

**Comment by hishamco** [comment]
I fix it, a PR will be there soon
