### ISSUE TITLE
NodaTime : Standardize timezones for x-plat

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#1577]
Right now the issue is that we are using Windows TimeZones when using OC under Windows but when moving the website to a Linux/Mac system they are not having the same timezones. Different problems comes from TimeZoneInfo.GetSystemTimeZones() which could be fixed by using NodaTime.

The drawbacks of migrating mainly comes from our usage of DateTime type within Orchard everywhere. We either will need to replace all of those with NodaTime LocalTime or provide some Helper functions to convert from one to the other. Same goes with TimeZones, we need to be able to also have a helper function that will return NodaTime TimeZones to Windows TimeZones ... etc ...

@joeaudette solution
https://www.cloudscribe.com/docs/easy-timezone-handling

@andrewhanson solution
https://hanson.io/taming-the-datetime-beast-with-noda-time/
https://github.com/andrewhanson/NodaTimeExplorer

**Comment by Skrypt** [comment]
Here is also one library that could be usefull for only converting TimeZones.

https://github.com/mj1856/TimeZoneConverter

**Comment by jon123** [comment]
There is no lib that can convert between time-zones and always be accurate.  It is not possible.  Note the author says "The author's best-informed knowledge and opinions".

**Comment by Skrypt** [comment]
I think that the library I linked is actually the implementation in .NET Core 2.0. So, yes you are right about that. 

I also think that we should really replace entirely System.Datetime entirely else we are losing the point about why we would be using NodaTime. NodaTime is also about approaching coding DateTimes differently.

**Comment by BennieCopeland** [comment]
I don't know if this is related to the topic, but I get the following while trying to change the timezone in Beta1 on Ubuntu. No specific order that I can tell, and tons of duplicate entries.
![image](https://user-images.githubusercontent.com/15783343/37123295-f9a574cc-2263-11e8-932e-a5790ac7e8bb.png)

**Comment by sebastienros** [comment]
I am fine using NodaTime to handle timezones, but in the UI and the database we still need to use `DateTime`. The difference is that in the database values will always be converted to Utc and for the UI they will be provided as Local.

**Comment by sebastienros** [comment]
Other options 
1- to use DateTime only for database
2- use a long for database and get rid totally of it.

**Comment by ArtKarp** [comment]
"The difference is that in the database values will always be converted to UTC and for the UI they will be provided as Local."

I hope that this is only one option.  

Orchard needs a NON UTC date/time field. (if it doesn't already have one) with the option of including a time zone.

There are many date/times that need to be saved to a database and never converted when displayed in the UI.  They also need a way to store a specific time zone.  When the date/time is used in reporting it won't require any conversion and will always be accurate.  Without this ability, the UI will incorrect.  If you try converting a date of birth for UI someone viewing the record in California sees March 2 and someone sees it in Sydney as March 3.  The both users need to see the true and accurate date/time not a converted one.

Examples:   
An insurance policy expires on March 2, 2019 12:01 AM Pacific Time (no conversion - everyone needs to be clear on the expire date/time/time zone)

A date of birth is March 2, 2019 6:15 PM (time zone optional, not required)

A music concert scheduled on March 2, 2019 7 PM  (local time based on the city where the concert is held - no time zone required)

I bring this up because Microsoft Dynamics CRM didn't start out including a non UTC date/time field.  It took years to get it added/fixed.   Users had to create workarounds and deal with inaccurate date/times. 

Please do this correctly now. 
Thanks

**Comment by sebastienros** [comment]
@ArtKarp We already have an issue in O1 (that we take into account in O2) to have such fields without timezone. Thanks for the reminder, we'll definitely have you review it when it's done.

**Comment by jpiquot** [comment]
Hi,
Instead of storing an UTC DateTime. Can't we use a DateTimeOffset that stores the local time zone?

Regards,

**Comment by Skrypt** [comment]
Date of birth can still be confusing since the person could be born in a different timezone than where she actually lives. I understand that this is optional relatively depending on how this information will be used afterward.

Let's not make a mistake on how the dates should be stored and how they should be output "differently" in the app depending on the context. Using UTC datetime within the app on runtime should not be a big issue if we already know which current timezone the user session has. Though when needing to retreive back this information from the database I'm pretty sure that we should save timezones as part of the datetime since a user can also change from a timezone to an other and also timezones themselves can change at any time.

**Comment by jon123** [comment]
I left a comment here last night that apparently didn't get posted.

Along the lines of what @Skrypt  is saying above, it would be a nice to have a 'timezone' property added to the built in Orchard user.  That would allow for module interop.  In Orchard 1.x such a property was added by extending the user (typically a profile module) and while that was workable, it also meant there was no common place to find the setting and risked modules creating incompatible or conflicting duplicate settings.   If any module wants to localize datetime per user, it would be very helpful to have a centralized (i.e. built in) place where one can lookup the user's preferred timezone.

A use case may be a module that sends a 'happy new years' email at the stroke of midnight (i.e. a workflow trigger that uses timezones per user ).  There could be a calendar that localizes to the user's specified timezone (ie office time instead the timezone where they are).  Without a centralized setting each module has to create its own.

**Comment by ArtKarp** [comment]
In Dynamics CRM I built a cross reference table that I have included in an attached file.
Reasons for doing this were to address...


Data Entry Users Need:
------------------------------
-To select a time zone they understand when populating a date/time field (e.g. "Pacific Time |Los Angeles")


Users and Reports Need:
------------------------------
-An abbreviation of the time zone (e.g. "PT")
-To show the full name of the time zone (e.g. "Pacific Time")
-Might also include the +/- GMT info   (e.g. "1-Jan-2017 11:00 AM (-8:00) GMT)

(Note: I use the text "Pacific Time" rather than "Pacific Standard Time" or "Pacific Daylight Time" because the "Standard" and "Daylight usually just adds unnecessary information.  If you have to be at an event at 4:00 PM Pacific time, it doesn't matter if it is Standard or Summer time on that date.)


Developers Need:
-----------------------------------
May need to know the Windows Time Zone Number for IIS and .NET (e.g. "004" for Pacific Standard Time")
May need to know the IANA Zone Name for cross platform OS and development languages (e.g. "America/Los_Angeles", "Europe/Paris")
The offset hours from GMT for Standard Time and Daylight (Summer) time
Ability to import/use datetime data from external systems that do not include a time zone 
To not recalc data that isn't being edited in order to display it


System Needs:
-----------------------------------------
- To enable only valid usable time zones for the organization/company.  If you are an Australian website and all your activity is scheduled in country or in one state, you do not need/want to see a timezone list that includes the rest of the world.   However, if you are a company that works across Europe, you might want to include all European time zones when users enter a date/time. 

- A system users default time zone.  This is helpful for data entry as a starting point. Also, helpful to know when the person is most likely awake.  :) 


Other Notes: 
-----------------------------
Data fields to cross reference the IDs from TimeAndDate.com and WorldTimeServer.com were included because they offer commercial APIs that can be used to find out information about a specific date/time/timezone.  (e.g. "Is March 15, 2018 4:00 PM in Los Angeles standard time?", "Is a specified date a bank holiday", "If it is July 4th 8:00 AM in Los Angeles, what date/time is it in New York, London and Sydney")

Keep in mind that the GMT Offset and daylight/summer time and its offset minutes is set by each country/region by law.   Because of this, there are currently 27 standard time zones. Even within a country like the USA, the state of Arizona has its own "Mountain" time zone which different from the Mountain time zone of Denver.  Arizona doesn't observer Daylight changes.  It is on Standard time all year. The same thing happens in the state of Queensland Australia - no DST. 

You can read all about it here:
https://www.timeanddate.com/time/current-number-time-zones.html

[All Time Zones.xlsx](https://github.com/OrchardCMS/OrchardCore/files/1813654/All.Time.Zones.xlsx)
![eventix-eventdate-screenshot](https://user-images.githubusercontent.com/25698082/37439006-118d5fc4-27b3-11e8-8f7f-c29621182364.png)
![eventix-timezone-screenshot](https://user-images.githubusercontent.com/25698082/37439009-15a5f7ec-27b3-11e8-977b-d9b3c578e7b2.png)

**Comment by Skrypt** [comment]
Here is also the "complete" list of IANA timezones.
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

I understand that Microsoft Dynamics installs only on Windows so the cross reference table has been built to keep in sync with other systems but starts from Windows TimeZones. 

If we can install Orchard on different OS then the timezones differs from one to the other unless we decide to opt in with something that will give us the same adequate list of TimeZones for every OS. NodaTime gives us the ability to have that same TimeZone list for every OS. Right now .NET Core doesn't retrieve the TimeZones adequately as we reported before. On Mac OS the list of TimeZones is displaying only "GMT -X" without any description. The list of timezones is also longer on Mac and Linux than on Windows because of how .NET Core has been implemented this so far. Our issue stands also with migration scenario's where someone could develop on Windows and deploy on a Linux server that would not have the same Timezones.

Seems to me, after reading last post, that if we would use IANA timezones by default then we would be needing a cross reference table from IANA to other timezone systems (Windows, commercial APIs). Though Orchard itself doesn't require to have this unless it would need to consume some other commercial API's that use other Timezone data.

Thinking globally ; what would be really helpfull is an open source database of cross references between those different TimeZone systems.

**Comment by Skrypt** [comment]
In addition to being a superior date time API, the Noda Time library contains an embedded copy of the CLDR mappings. 

https://stackoverflow.com/questions/17348807/how-to-translate-between-windows-and-iana-time-zones
https://github.com/mj1856/TimeZoneConverter

I've updated my earlier post and I think this is still relevant. Needs to be tested though.
