### ISSUE TITLE
Shortcodes are not resolved for content types in bag parts

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#15804]
When you create a content item within a bagpart and the bagpart content item has a shortcode to render  say an image ( [image]post-bg.jpg[/image] ) then it does'nt display the image in display mode.

### To Reproduce
1.Using the blog theme recipe create a new contenttype and add a bag part that contains content types of type Article .
2. Create a new instance and add an article to the bag part and in the article html body part add an image : [image]post-bg.jpg[/image]
3. When displaying in the front end the image does not display 

If you create a standard article content item  with  same shortcode then the image shortcode renders correctly.

**Comment by Piedone** [comment]
This is not exactly a bug but something that seems unclear when using Bag Part: the shortcode itself works, but is not displayed.

This is because when opening the standalone Article, it's displayed in Detail display type, with the body rendered as-is. When displayed in Bag Part, it uses the Summary Display Type, and thus `HtmlBodyPart.Summary`. That [strips tags](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Html/Views/HtmlBodyPart.Summary.cshtml#L3), so the formatting of content items in a list won't get messed up.

If you configure "Detail" for the Display Type under the Bag Part's settings, then you'll see the same as when opening a standalone Article:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/79398fb8-0221-425a-927d-85a04fd3ea0f)

**Comment by giannik** [comment]
Oh @Piedone  your are correct. I missed the display type setting. 
Thank you.
