### ISSUE TITLE
Remove `VersionOptions.AllVersions`

### ISSUE THREAD

**Issue by MarGraz** [OrchardCMS/OrchardCore#16027]
For an explanation, see comments below from https://github.com/OrchardCMS/OrchardCore/issues/16027#issuecomment-2115840661. We should remove `VersionOptions.AllVersions`.

The original issue below is kept for context.

### Describe the bug

The method `_contentManager.GetAsync(model.ContentItemId, VersionOptions.AllVersions)` **fails to return any content items, whether published or draft.** When debugging in Visual Studio with "Just my code" disabled, execution enters the condition `else if (options.IsDraft || options.IsDraftRequired)` in `DefaultContentManager` [here](https://github.com/OrchardCMS/OrchardCore/blob/be675b3e1805f3a7b30afff9ceab747719ca9091/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L189). 

I'm unsure why this condition is satisfied, given that my content item is published and the boolean `IsDraft` and `IsDraftRequired` are set to `false`. 

Screenshots are provided for reference.

### To Reproduce
1. Use Orchard Core 1.8.3
2. Activate the "Content Fields Indexing (SQL)" feature (I have it active)
3. Create a Content Item and publish it
4. In a controller, use `IContentManager` from dependency injection to retrieve the Content Item by its ID with `VersionOptions.AllVersions` set, like this: `_contentManager.GetAsync(model.ContentItemId, VersionOptions.AllVersions)`
5. Execute the code to verify whether a Content Item is returned

### Expected behavior
A published or drafted Content Item must be returned when I set `VersionOptions.AllVersions`

### Screenshots

My Content Item:

![image](https://github.com/OrchardCMS/OrchardCore/assets/19241483/f6c0ddb3-b880-4d60-84ec-f6c1be2ed8f5)

`IsDraft` and `IsDraftRequired` are false, why the condition is satisfied?

![image](https://github.com/OrchardCMS/OrchardCore/assets/19241483/1bc59f0a-0ca7-47eb-8f51-06577734fda2)

**Comment by Piedone** [comment]
Is this what https://github.com/OrchardCMS/OrchardCore/pull/11433 addresses?

**Comment by Piedone** [comment]
A note for this and https://github.com/OrchardCMS/OrchardCore/pull/11433 @hyzx86 about  `AllVersions` :

- It's most possibly meant to let you fetch all past and the single current version of a content item.
- It isn't actually doing anything now, it's not used. But we can make it work, or remove it.
- It doesn't actually make sense for `GetAsync(contentItemId, VersionOptions options)`: that method will always return at most a single content item, so it can't return all versions of a content item. That method should throw an exception with this input.
- It does make sense for `GetAsync(IEnumerable<string> contentItemIds, VersionOptions options)` though, since it returns multiple items anyway. However, this might get confusing there, when you get back N `ContentItem`s, but those are mixed as versions and content items.

**Comment by Piedone** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/16077 takes the make it work approach, with throwing in `GetAsync(contentItemId, VersionOptions options)` and returning all versions in `GetAsync(IEnumerable<string> contentItemIds, VersionOptions options)`.

Any comments?
