### ISSUE TITLE
Razor SDK tooling

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1614]
We can force `Web` sdk by setting the `OutputType` explicitly:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
```

Or use `Sdk="Microsoft.NET.Sdk.Razor"` directly.

**Comment by jtkech** [comment]
- So, for our applications we use `.NET.Sdk.Web`.

- At one point for our modules we did the same to have razor intellisense but with `<OutputType>Library`. But now we use the new `.NET.Sdk.Razor` so that's ok.

- The exceptions are the modules which don't have and will never have razor views. These ones use `NET.Sdk` as all other core libraries.

- **So, all is ok for me**. The only thing is that we were using `netcoreapp2.0` in the testing modules in place of `netstandard2.0`. I will commit an update for this.

**Comment by sebastienros** [comment]
Tests can be netcoreapp2.1 actually. Look at the MVC repos for instance.

**Comment by jtkech** [comment]
`OC.Tests` is already `netcoreapp2.1`, i was talking about the referenced testing modules under the `OrchardCore.Tests.Modules` folder which should use `netstandard*.*` in place of `netcoreapp*.*`.

**Comment by jtkech** [comment]
@sebastienros i think we can close this one.

Note: All our app are already using `netcoreapp2.1`. When i talked about `netstandard2.0`, this is what we are using for all our libraries, including some fake modules referenced by the test application.

I did some updates here #1973.
