### ISSUE TITLE
Modules injection Docker

### ISSUE THREAD

**Issue by cocoke** [OrchardCMS/OrchardCore#1619]
Hello, 
I would like to know if it's possible and how to live inject modules in a OrchardCore website with docker

The structure would be :
- A main OrchardCore website running on a docker container with multiple tenants and having basic custom themes and some modules.
- Multiple module each running on a docker container.

How can I proceed ?

**Comment by sebastienros** [comment]
Modules are not services, even less micro services, they run in the same process as the web app. Hence you can't add them in other docker instances. The only think you can do is have different apps with different modules to create those micro services, and you will also need a proxy to route the requests to the correct services.

/cc @glennc because you love docker, micro services and orchard
