### ISSUE TITLE
SQL queries in GraphQL do not return results anymore

### ISSUE THREAD

**Issue by gvkries** [OrchardCMS/OrchardCore#16201]
### Describe the bug
There is a regression in the latest version (main branch). A SQL query does not return any results when used in a GraphQL query.

### To Reproduce
1. Create a new site with the blog recipe.
2. Create a second blog post and edit both post a few times by saving drafts, publishing etc.
3. Change the RecentBlogPosts query to return documents.
4. Use the query in GraphiQL. It does return an empty array.

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/7062785/6495c3cf-22d6-4184-8219-bbad56f360cf)

It looks like `_session.GetAsync<ContentItem>()` does not return anything.

**Comment by gvkries** [comment]
This must be something else, not sure what the error is. It's not showing up with a new site.

**Comment by Piedone** [comment]
In the repro you said to try with a new site, but then you commented it's not applicable to a new site. Which one is the repro?

**Comment by gvkries** [comment]
Yeah, I'm super confused ATM 🙈

**Comment by gvkries** [comment]
### To Reproduce
1. Create a new site with the blog recipe.
2. Create a second blog post and edit both post a few time by saving drafts, publishing etc.
3. Change the RecentBlogPosts query to return documents.
4. Use the query in GraphiQL. It does return an empty array.

So, this error occurs after some editing has been done. Seems to be related to versioning the items or something like that.

(PS.: I updated the original repro steps as well.)

**Comment by gvkries** [comment]
And I did not find when this broke 🤷‍♂️

**Comment by Piedone** [comment]
The issue is that (in my above example) the `documentIds` contains `[15, 10]`. However, those are not the Documents' IDs, but the `Id` values of the `ContentItemIndex` rows. We should rather take the `DocumentId` column from there.

The issue is that `connection.QueryAsync<long>(rawQuery, parameters, transaction)` will take the first column that matches `long`, which for new installations will be `Id`.

Changing the query to this fixes the issue:

```sql
SELECT DocumentId FROM ContentItemIndex WHERE ContentType='BlogPost' ORDER BY CreatedUtc DESC LIMIT 3
```

However, I'm unsure about how to tackle this:

- We can change the query in the recipe, and instruct people to make their queries always return only a Document ID, which should've always been the case. I'd do this, since with the `long` cast matching the first column, a `*` query (which is inefficient anyway) is uncertain anyway.
- Try to fish out the `DocumentId` from the query results with some heuristics. However, we need to keep in mind that the query can be anything, for any table (including custom ones), and the only thing we can reasonably assume is that there will be a column that contains Document IDs. This might have any random name, and be `long` or `int`. There can be any number of columns with these types that aren't the Document IDs.

What do you think?

**Comment by gvkries** [comment]
Oh, I should have seen that. I only checked the "return documents" field and it started to work. So I never actually checked the query itself 🙈 I think this is not a bug then... 

Thanks a lot for your help!

**Comment by gvkries** [comment]
I don't think it's worth changing anything here. Note to myself: one must create a correct query :)

**Comment by Piedone** [comment]
I think this is indeed a bug, just not in SQL Query, but perhaps the recipe (though it only really surfaces an issue if you try to use it with GraphQL) and and an omission in the documentation.

**Comment by Piedone** [comment]
So, I think [this docs section](https://docs.orchardcore.net/en/latest/reference/modules/Queries/#graphql) should include that the query should select a column containing a document ID. And the Query in the recipe should select `DocumentId`, since that's needed in any case, regardless if you use it in GraphQL or not.

**Comment by gvkries** [comment]
The query in the recipe does not return documents, so it's correct on its own IMHO. But  maybe we can detect those errors and make it harder for people to fall into the same trap as I did.

**Comment by Piedone** [comment]
It's not incorrect but it's unnecessary, since for its default usage in a template you also only need the document ID.

We could also add a hint to the checkbox BTW.

Not sure but maybe we need something similar for Lucene and Elasticsearch Queries too.

**Comment by gvkries** [comment]
@Piedone The blog recipe actually used a wrong property name in the SQL query step. I also made the Sql query source a little bit more forgiving by trying to get the correct column. Only if no `DocumentId` column is in the query, it falls back to the first `long` column it finds.
