### ISSUE TITLE
[LinkField] Add option to select the Target - _blank, _self, _parent and _top

### ISSUE THREAD

**Issue by vengi83644** [OrchardCMS/OrchardCore#16244]
### Is your feature request related to a problem? Please describe.
LinkField now only has URL and Text properties. However, having a Target property will help set the "target" attribute in the anchor tag HTML element.

### Describe the solution you'd like
Add Target Property in LinkField Class and expose a select list in the LinkField.Edit.cshtml to choose the target attribute.

### Describe alternatives you've considered
I tried inheriting the LinkField in my module and adding the Target property - Added the LinkField from my module and got error in a dictionary that the key already exists.

**Comment by vengi83644** [comment]
> #15636 This PR is for Menus. 

This request is for LinkField

**Comment by hyzx86** [comment]
Oh, yeah. It's true, they're different. I'm sorry. 
But I feel like the UI interaction should be similar

**Comment by MikeAlhayek** [comment]
@vengi83644 do you like to submit a PR? this should be simple implementation. The options/menu can follow that @hyzx86 did in PR #15636

**Comment by vengi83644** [comment]
> @vengi83644 do you like to submit a PR? this should be simple implementation. The options/menu can follow that @hyzx86 did in PR #15636

Happy to., Let me.,.,

**Comment by vengi83644** [comment]
@MikeAlhayek 
Here is the PR
https://github.com/OrchardCMS/OrchardCore/pull/16326

**Comment by sebastienros** [comment]
I don't feel like it's a good idea to add these kind of uncommon properties to core fields which should remain as lean as possible. When we designed this field we clearly not include it. This can be solved by adding an extra enum field already if necessary. So much that this is the first time (AFAIR) that this has been requested (since it's not blocking).

Also now all the views have to handle this new property, so if you create a custom template for your site you might have to react, or to handle it (more complexity) even if you don't want the complexity it adds in the views.

**Comment by MikeAlhayek** [comment]
There was a recent ask to have this added to the Menu #15636. I think it's a fair ask since it's just a setting to the field. Additionally, I don't think it adds much complexity to the code.
