### ISSUE TITLE
After removing the AliasPart from a content type, the indexed content items are still queried by the alias handle

### ISSUE THREAD

**Issue by dmourtzoukos** [OrchardCMS/OrchardCore#16410]
### Describe the bug
After removing the AliasPart from a content type, the indexed content items are still queried by the alias handle
 
### Orchard Core version
1.8.3
 
### To Reproduce
1. Create a Content Type with an Alias Part.
2. Create a Content Item of this type and give it an alias.
3. Create a Controller method that gets an alias as a parameter and a view that calls the GetContentItemByAliasAsync (which queries the AliasPartIndex) for the passed alias.
4. Navigate to this page and pass the alias of the Content Item created on step 2. The Content Item will be displayed on the page.
5. Remove the Alias Part from the Content Type.
6. Navigate again to the page of step 4. The Content Items still gets displayed.
 
### Expected behavior
After removing the Alias Part from the Content Type, the page should not display the Content Item, since the Content Type doesn't contain an Alias Part anymore.

**Comment by Piedone** [comment]
While this bug is about Alias Part, the same would happen with any part. In general, if you remove a content part from a content type, its data for previously created items are not deleted. So, both data in the content items' documents and corresponding rows in index tables remain.

When publishing these items the next time, the data should be removed, however (or shouldn't be retained for the new version).

So, if you want to fix this issue right now, a workaround is to (programmatically) republish all affected content items. The longer-term solution is https://github.com/OrchardCMS/OrchardCore/issues/8316. I don't think anything is needed for Alias Part, specifically, and this issue can be closed. But thank you for taking the time to detail your inquiry!

**Comment by sebastienros** [comment]
Let's follow up with https://github.com/OrchardCMS/OrchardCore/issues/8316
