### ISSUE TITLE
The default capacity of the BatchCommand StringBuilder 10240 might not be sufficient

### ISSUE THREAD

**Issue by gwonen** [OrchardCMS/OrchardCore#16487]
### Describe the bug
After upgrading a website from Orchard Core 1.7.0 to 1.8.3 I started seeing this recurring warning in my log whenever a content item of a particular content type is loaded. I've traced it back to line 33 (`var document = await _session.Query<T>().FirstOrDefaultAsync()`) in the `DocumentStore` class. Nothing seems to break functionally, but it looks a bit ominous.

### Orchard Core version
1.8.3

### To Reproduce
I have not been able to reproduce the issue in a different environment. The content type in question happens to contain many fields (around 30) over multiple parts. It sounds like its string representation is exceeding the initial size of some internal string builder, which might result in some additional overhead, hence the warning.

### Expected behavior
No ominous warnings.

### Logs and screenshots
Example log:
`2024-07-26 11:44:45.4884|MyTenant|00-adb6d0986e9c637d9ebdc93227339930-c901334b7cbdefc9-00||YesSql|WARN|The default capacity of the BatchCommand StringBuilder 10240 might not be sufficient. It can be increased with BatchCommand.DefaultBuilderCapacity to at least 10679 
2024-07-26 11:47:31.9291|MyTenant|00-e1c8602e4153c4993a7548d5e670a0f1-88a79bd627414da4-00||YesSql|WARN|The default capacity of the BatchCommand StringBuilder 10240 might not be sufficient. It can be increased with BatchCommand.DefaultBuilderCapacity to at least 10679 
2024-07-26 11:48:51.8397|MyTenant|00-e1c8602e4153c4993a7548d5e670a0f1-88a79bd627414da4-00||YesSql|WARN|The default capacity of the BatchCommand StringBuilder 10240 might not be sufficient. It can be increased with BatchCommand.DefaultBuilderCapacity to at least 10679`

**Comment by Piedone** [comment]
This is a warning coming from YesSql. You'll need to do what the log message says, and set a larger value to [`BatchCommand.DefaultBuilderCapacity`](https://github.com/sebastienros/yessql/blob/1ff3fd3894a6b591de8c7f9ee3301eb51ccf8972/src/YesSql.Core/Commands/BatchCommand.cs#L12). You can do this from e.g. the beginning of your root web project's `Program`.

What happens if you increase that? Apart from the warning going away, is everything working properly?

However, this value doesn't actually seem to be used anywhere. There is already an issue about it: https://github.com/sebastienros/yessql/issues/572.

**Comment by gwonen** [comment]
Increasing the DefaultBuilderCapacity in OrchardCore.Cms.Web.Program removes the warnings and doesn't seem to have any adverse effects. If it's a known issue and slated for removal from YesSql, I assume this will resolve itself in future versions.

**Comment by Piedone** [comment]
Yep! Great, then.
