### ISSUE TITLE
Module loading and unloading

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#16529]
### Describe the bug
Technically it is not a bug but some unexpected behaviour. When I create empty module with empty implmentation of `IDisposable` interface and and `ConfigureServices(IServiceCollection services)` and include it at bootstrap level:

 `builder.Services.AddOrchardCms(p => p.AddTenantFeatures("MyModule"));`
 
 I can observe following at startup sequence when creating default website:
 1. Module constructor is called 4 times
 2. Module `ConfigureServices` is called 3 times
 3. Module `Dispose` is called 3 times
 
 ans when I start it with default website already created:
 1. Module constructor is called 2 times
 2. Module `ConfigureServices` is called 1 time
 3. Module `Dispose` is called 1 time

### Orchard Core version
1.8.3

### To Reproduce
1. Create empty module using `StartupBase` as base class and annotate it with `[Feature("MyModule")]` and implement `IDisposable`
2. Add module to startup code: `builder.Services.AddOrchardCms(p => p.AddTenantFeatures("MyModule"));`

### Expected behavior
- When module is loaded I would not expect `Dispose` to be called just after start `ConfigureServices`
- The amount of Module spawn when creating site for a first time also seems strange, I would expect 1 spawn not 3

Is current implmentation expected behaviour?

**Comment by Piedone** [comment]
What exactly do you mean by "module constructor"?

How do you register the `IDisposable` implementation? Please show the full `Startup` code.

**Comment by arkadiuszwojcik** [comment]
@Piedone relevent code below, I marked "module constructor" with comment

Startup:

```
public static void Main(string[] args)
{
    var builder = WebApplication.CreateBuilder(args);

    builder.Services.AddOrchardCms(p => p.AddTenantFeatures("MyModule"));

    var app = builder.Build();

    if (!app.Environment.IsDevelopment())
    {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }

    app.UseStaticFiles();
    app.UseOrchardCore();

    app.Run();
}
```

Module code:

```
[Feature("MyModule")]
public class MyModule : OrchardCore.Modules.StartupBase, IDisposable
{
    private readonly ILogger _logger;
    private readonly IShellConfiguration _configuration;

    public MyModule(ILogger<MyModule> logger, IShellConfiguration configuration)
    {
        // Module constructor
        _logger = logger;
        _configuration = configuration;
    }

    public override void ConfigureServices(IServiceCollection services)
    {
    }

    public void Dispose()
    {
        // Dispose implementation
    }
}
```

**Comment by gvkries** [comment]
This is expected behavior, at least for normal startup. The DI container is created twice because each module can add services. So it has to be recreated after all the `ConfigureServices` of the startups have been executed.
For the setup, I think it's normal too, but I'm not so familiar with the inner workings there.

**Comment by Piedone** [comment]
Yes, `IStartup`s being resolved twice during shell start is expected, since the shell is built twice, see [here](https://github.com/OrchardCMS/OrchardCore/blob/c347a81dc4700db663c3d86c923e8ebeee2836f8/src/OrchardCore/OrchardCore/Shell/Builders/ShellContainerFactory.cs#L130). The reason is what Georg tells: any of these startups can register new services.

Setup creates temporary shells, so while I don't have time to look into that more now, a couple more instantiations don't seem alarming.

The dispose behavior matches the container disposes before new instantiations, so that's expected too.

BTW it's unusual to have an `IDisposable` startup. If you're doing some heavy lifting in your startup class that accesses unmanaged resources, then that's most possibly not the best place to do it. Running it [in a startup event](https://docs.orchardcore.net/en/latest/guides/run-code-on-startup/), or perhaps later lazily on-demand might be better.
