### ISSUE TITLE
SmtpSettings : Error retrieving Password

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1654]
When I try to change the Smtp Settings in the admin, an error occurs:
`The key {guid} was not found in the key ring.`

I don't know if it is since this commit a7fba792 from @PinpointTownes

**Comment by PinpointTownes** [comment]
Yep, that's because we moved to a single host key ring to a per-tenant key ring model: every payload encrypted using an older OrchardCore version won't be readable using newer OC packages.

We should probably catch exceptions that occur when calling `Unprotect()`, to ensure users can edit settings, without being blocked by this error.

**Comment by PinpointTownes** [comment]
@sebastienros it's really time for a global announcement :smile:
