### ISSUE TITLE
move GetActionContextAsync and its related stuff to abstract place

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#16554]
### Is your feature request related to a problem? Please describe.
under public class SeoMetaSettingsHandler and its related 
 private readonly IActionContextAccessor _actionContextAccessor;
 private readonly IHttpContextAccessor _httpContextAccessor;
 private readonly IUrlHelperFactory _urlHelperFactory;

### Describe the solution you'd like
move 
 private readonly IActionContextAccessor _actionContextAccessor;
 private readonly IHttpContextAccessor _httpContextAccessor;
 private readonly IUrlHelperFactory _urlHelperFactory;
and
GetActionContextAsync
to a topService, because many modules  will use the same logic.

**Comment by Piedone** [comment]
Moving injected dependency to a parent class is only marginally useful since you still have to write the constructor in a child class.

Factoring out this method can be useful:

https://github.com/OrchardCMS/OrchardCore/blob/557d6cf4674691acf7b02f2a49adf61b40bdb6e8/src/OrchardCore.Modules/OrchardCore.Seo/Handlers/SeoMetaSettingsHandler.cs#L209-L223

Because it's duplicated [here](https://github.com/OrchardCMS/OrchardCore/blob/557d6cf4674691acf7b02f2a49adf61b40bdb6e8/src/OrchardCore.Modules/OrchardCore.Seo/Handlers/SeoMetaPartHandler.cs#L186) and [here](https://github.com/OrchardCMS/OrchardCore/blob/557d6cf4674691acf7b02f2a49adf61b40bdb6e8/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/LiquidViewTemplate.cs#L201). These examples also show that these should be centralized in some kind of static helper.
