### ISSUE TITLE
Sitemap - memory allocation

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#16616]
### Describe the bug
Sitemaps with over 20.000 items consume too much memory and do not release it. We have currently added few more content types into sitemap and it grew up to 20k items. When we generate sitemap (with cache), it takes about 5 minutes to build and it allocates and holds around 6 GB of memory. 

### Orchard Core version
1.8.2

### Expected behavior
As the generated sitemap itself has only 4 MB, I wouldn't expect that cache/memory usage is 1,500x bigger

### Logs and screenshots
After sitemap build:
![image](https://github.com/user-attachments/assets/ffbb5e9b-df5c-40ad-a6d0-e43651da8680)

After sitemap cache clean: 
![image](https://github.com/user-attachments/assets/50bd34a7-676f-4ce4-816c-1fd04b2ebdef)
(seems memory is still not released, not even through tenant restart and it needs hard reset.)

Standard allocation is around 500-800 MB

Even more interesting is, that the sitemap cache is stored at FS, so it should not be in memory. I guess there is a memory leak somewhere. I tried to disable our custom modules but result is the same.

<details>

1

![image](https://github.com/user-attachments/assets/c9d2b123-0892-4051-98fa-c725922d5d4a)

2

![image](https://github.com/user-attachments/assets/8c32f4a5-9d02-4034-abd6-b57499ae2fae)

</details>

**Comment by MikeAlhayek** [comment]
@MikeKry it may be helpful to provide the steps to reproduce this issue.

Are you going to submit a PR for fixing this?

**Comment by Piedone** [comment]
I guess the root of the issue is that when building the sitemap (second exception) there will be just too much stuff in memory for 20k items. There's no batching/paging, so in the end, all items are looped over and the resulting XML is built on the fly (see `ContentTypesSitemapSourceBuilder`). If changing the logic is not feasible, we may look into [sitemap index files](https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps?visit_id=638602955058270056-1770555494&rd=2) to build multiple, smaller sitemaps (that's necessary at one point anyway, since sitemaps [are limited to 50MB/50k entries](https://www.sitemaps.org/faq.html#faq_sitemap_size)).

If you can provide a way to repro this, like with a suitable export file with that many items, or some code that generates suitable items, then indeed we can look into this better.

**Comment by gvkries** [comment]
You can already create a sitemap index to split the sitemap into smaller pieces. You can also limit the number of items in each sitemap. See https://docs.orchardcore.net/en/latest/reference/modules/Sitemaps/#sitemap-content-types-source

**Comment by sebastienros** [comment]
The two improvements I can see:
- Page the content items when we load/process them in sitemaps
- Have a new option to set the max number of items per sitemap to create multiple files (optional/separate PR maybe), with a sensible default

**Comment by MikeAlhayek** [comment]
@MikeKry if you are able to, please test out PR #16636 as it should fix your problem. You'll need to be on 2.0 previews or main branch to test it out.

**Comment by Piedone** [comment]
And repro information would still be useful.

**Comment by MikeKry** [comment]
@MikeAlhayek I will try it today on our dataset. 

Sadly I am not allowed to share this specific dataset, but in case it is needed, it should not be a problem to generate a sample dataset. I can provide you with generated one, in case you don't have option to generate.

**Comment by MikeKry** [comment]
Just tried that out, it seems fixed. 

If there would be still a need for getting a dataset, let me know, but whole usecase is just having a lot of pages included in sitemap.
