### ISSUE TITLE
When you edit a template, the scrollbars are not easily accessible

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1670]
When editing status,
  Fixed "SAVE, Publish, preview" button and "Editor scrollbar"
Do not follow the browser's scrollbar position.
Will it be better?

```
编辑状态时，
 固定 “SAVE、Publish、preview”按钮 和”编辑器横竖滚动条“，
不要跟随浏览器的滚动条移动位置，会不会更好呢？
```

![1](https://user-images.githubusercontent.com/28694676/38621038-9805dbdc-3dd2-11e8-914d-b7b473143f60.gif)

↓
↓
↓

![_20180411204148](https://user-images.githubusercontent.com/28694676/38621058-a2eec720-3dd2-11e8-9f3c-127cfc6b2f21.png)

↓
↓
↓

![2](https://user-images.githubusercontent.com/28694676/38621290-264cd83c-3dd3-11e8-80df-1c85851a23bb.png)

**Comment by agriffard** [comment]
@matiasmolleja Could you please find a solution for a scollbar problem that happens when you edit a template in the admin?

It is may be because of the footer but when a template has many lines and long lines (as the TheAgency LandingPage), there are horizontal and vertical inside scrollbars that are not easily usable.

**Comment by matiasmolleja** [comment]
I will look at it.

**Comment by sebastienros** [comment]
The footer in O1 was a pain to deal with. If it causes a single issue in OC I'll view to remove it.
