### ISSUE TITLE
OrchardCMS beta2 workflow implementation.

### ISSUE THREAD

**Issue by devanathan2017** [OrchardCMS/OrchardCore#1673]
Hi , 
We are trying to wire up the workflows in our modules. Its very difficult to understand how to use the Task and Event. I refered few documents and videos which are very old not related to the current version we use (Orchardcore beta2).
Is there any documents available atleast to read and understand ?
1.Also is it possible to get the property values between the two task?  I tried but getting the error "variable not defined". attached the image below.
a.Created the property name 'value1' and its value is 'store1'. 
b.Trying to assign this value in the next task. not sure this approach is possible? and how to do it.
2. Is there a way we can call our external methods inside the Task?.

![wf](https://user-images.githubusercontent.com/34333687/38722219-d2e110d4-3f1a-11e8-8509-77f3c73dc504.png)
Let me know your thoughts, thanks.
Dev.

**Comment by sfmskywalker** [comment]
I'll write some more documentation to describe these basics, I realize it's hard to guess how to use what without proper guidance.

Some quick pointers:

1. An Event is a specialized Activity that you use to listen for an event. When using an Event as a starting activity, the Workflows module will kick off the workflow when that event is triggered. When an Event is used elsewhere (i.e. not as the starting activity), it will halt the workflow until that event is triggered. When that happens, the workflow resumes.
2. You can set property values onto the workflow and retrieve them from other workflows. This is supported via the Set Property activity as you've shown in the screenshot as well as with JavaScript and Liquid fields. When you use activities such as **Output**, make sure you use a JS expression if you want to use a value from the workflow. Otherwise the value is interpreted as a string literal. In your example, use: `property('value1')`.
3. There is no generic Task that can call external methods out of the box. You should either implement your own custom, specialized Task that calls your method, or implement a generic one that can call any external method.

**Comment by devanathan2017** [comment]
Hi Walker,
1. Yes it would be great if you write the documents.
2. Am able to get the values form one task to another from set property task.
3. Worked with events, Not Sure how to trigger the 'Signal' events. Others are fine and working for me. need some info on this.
Definitely your response will help me to get started. 

Thanks
Dev

**Comment by sfmskywalker** [comment]
This walkthrough shows you how to use Signal events: http://www.ideliverable.com/blog/orchard-core-workflows-walkthrough-content-approval

**Comment by GadgetGeekUK** [comment]
The documents still don't give a good walkthrough of creating an Event and Activity in code inside your own module, then to use them in the application.

Workflows 101 is still needed. I have also looked at the following link and am working through the source code:
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Workflows/README/

**Comment by sfmskywalker** [comment]
Thanks for the feedback! I see that it indeed could use a simple step-by-step walkthrough, similar to the "writing a widget" article that we have in the O1 documentation.
