### ISSUE TITLE
Remove SiteOwner permission

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16763]
I think `SiteOwner` permission should be removed and not used any more. At someone point it probably made sense to have that permission, but I don't think we need it any more.

**Comment by MikeAlhayek** [comment]
They should stop relying on it.

**Comment by Piedone** [comment]
Let's leave assigning the milestone to the triage meeting, please. This is not at all an obvious thing but rather something that should be discussed.

Also, more rationale would be good: why do you think it should be removed, why nothing should rely on it? What's the problem with it?

**Comment by MikeAlhayek** [comment]
this was discussed a while back on a triage and agreed that it should be removed. So I am logging these things in the next major release. 

@sebastienros

**Comment by Piedone** [comment]
What was discussed there? Because I'd be interested in the rationale.

I don't think it should be removed, at most made internal, i.e. something that you can't authorize against. Because the Site Owner permission has two uses:

- As a permission to authorize against, as with any permission. I agree this shouldn't be done, but there are a couple of instances.
- As a meta-permission that gives you God mode, instead of selecting each and every permission, also ones added in the future. This, I think is very useful and should not be removed.

**Comment by MikeAlhayek** [comment]
I don't remember the exact details since this was discussed a while back. I am okay with removing the milestone and discuss this again. 

But if you are trying to accomplish your scenario "God power" would be a role not a permission. For example, anonymous is a role not a permission.

If you look at how we use SiteAdmin, you'll notice that we check it in specific places in addition to global. For example recipes, what if we want a specific user to import recipes but they are not the owner.

**Comment by Piedone** [comment]
If you want a role to be able to do anything, then currently, you only need to give it the Site Owner permissions. Using a role is no substitute for this, since the alternative would be to click every single permission under a given role, as well as _do this for any future permission when new ones are added_. You can't depend on permission defaults to be always suitable for you (not all new features of OC may add new permissions to the Administrator role, nor can we expect third-party features to do this), especially if your role is not named "Administrator". This is a worse experience for maintaining a site.

To put it otherwise, IMO `DefaultPermissionGrantingService` should stay as-is. And again, for the places where Site Owner is directly authorized against (i.e. used as `_authorizationService.AuthorizeAsync(User, StandardPermissions.SiteOwner)`) it should be removed in favor or a functionality-specific permission.

**Comment by MikeAlhayek** [comment]
I think for now, we should not be checking for SiteOwner explicitly like we do in couple places. As for as not needing to select permission, I’ll have a PR around roles that would help with this.

**Comment by MikeAlhayek** [comment]
@Piedone the addition of `HasFullAccess` property in PR #16781 should solve your use case so we live without `SiteOwner`

**Comment by Piedone** [comment]
That's great, but I don't see why we'd want to do this now. What's the use case that this enables? What's the problem it solves? Did anybody complain about it and provide understandable arguemtns? I really don't want to change such a fundamental thing that has been part of OC and O1 for more than two decades without a very good reason.

To clarify, the only issue with the current code is that `SiteOwner` shouldn't be authorized against. That's a nice to have thing and I'd consider it backlog, up for grabs if anyone wants to work on adding new permissions. Now, removing or changing `SiteOwner`'s "authorized for everything" feature, or introducing a new feature with the same goal is not something that I see the point of spending time on.

**Comment by MikeAlhayek** [comment]
@Piedone having a permission that auto grant other permission does not make sense to me from design perspective. However, giving a role a setting to grant all permission does. A role can contains a collection of permissions, so it make sense to have a grant all at the role level. With that PR, on the UI the user can just this role has full access, now all permissions will be granted. Another benefit of this approach, we reduce the claim collection size that is evaluated on every request. Instead of having 100 permissions, we'll have very few. This reduces the request side "cookie size" and also the lookup time will be much shorter since the collection size is much smaller.

**Comment by MikeAlhayek** [comment]
@gvkries are you saying you agree with adding property at the role level to grant users FullAccess instead of using SiteOwner permission?

**Comment by MikeAlhayek** [comment]
@gvkries after reading your comment [here](https://github.com/OrchardCMS/OrchardCore/pull/16781#issuecomment-2371196471), I understood what you meant. and I think I agree with you about using `Owner` type instead of adding another property.

**Comment by Piedone** [comment]
I see the point. Sounds good, then!
