### ISSUE TITLE
Custom analyzers in Elasticsearch no longer work

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#17012]
### Describe the bug
When specifying a custom analyzer in Elasticsearch as explained here https://docs.orchardcore.net/en/latest/reference/modules/Elasticsearch/#elasticsearch-analyzers it does create that custom analyzer in the Elasticsearch service.

### Orchard Core version
2.x

### To Reproduce

Configure custom analyzer like this:
```
"OrchardCore_Elasticsearch": {
      // Other settings
      "Analyzers": {
        "standard": {
          "type": "standard"
        },
        "keyword": {
          "type": "keyword"
        },
        "whitespace": {
          "type": "whitespace"
        },
        "knowledgebase_analyzer": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "stop"
          ],
          "char_filter": [
            "html_strip"
          ]
        }
      }
    }
```
Create an index using the custom `knowledgebase_analyzer`. Now try to search for anything you'll get an error 

> [multi_match] analyzer [knowledgebase_analyzer] not found

This issue was caused by PR #16843

**Comment by denispetrische** [comment]
I applied this configuration

"OrchardCore_Elasticsearch": {
  "ConnectionType": "SingleNodeConnectionPool",
  "Url": "http://localhost",
  "Ports": [ 9200 ],
  "Analyzers": {
    "standard": {
      "type": "standard"
    },
    "keyword": {
      "type": "keyword"
    },
    "whitespace": {
      "type": "whitespace"
    },
    "knowledgebase_analyzer": {
      "type": "custom",
      "tokenizer": "standard",
      "filter": [
        "lowercase",
        "stop"
      ],
      "char_filter": [
        "html_strip"
      ]
    }
  }
}

Created index with knowledgebase_analyzer
![image](https://github.com/user-attachments/assets/627a8cc0-05b2-4ae9-bce6-1ff9e00c20e3)

We can see that analyzer were created under name "default", it is necessary because for now there is no mechanism to specify concrete field for analyzer to be applied.

![image](https://github.com/user-attachments/assets/a5a66f08-4275-4e0d-addd-601edd9b98f1)

You can see also, that char filters are still not supported. 

I created few Menu content Items, I can see them in the default_my index directly
![image](https://github.com/user-attachments/assets/43858751-c7d0-42d0-902d-193a43665382)

I created a query and it works 
![image](https://github.com/user-attachments/assets/b5598eb4-ce42-472a-bc3a-70d527294430)
![image](https://github.com/user-attachments/assets/560f4622-5a95-4d6b-9081-bec03600405e)

I created also multimatch query
![image](https://github.com/user-attachments/assets/77d83ae0-5400-4521-be34-77cbdd28c778)
![image](https://github.com/user-attachments/assets/8fe41e47-1509-4c40-b169-9a0864551b9c)

So... everything works fine
