### ISSUE TITLE
Media selectors are broken

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1734]
![image](https://user-images.githubusercontent.com/1165805/39321894-0b0e4540-493d-11e8-9992-f0319697dd0b.png)

**Comment by matiasmolleja** [comment]
I can't repro.
To be sure I started from scratch:
Cloned the repo, started on VS, setup agency theme, Edit the landing page, and it seems to work nicely.
Can you please give me the steps you follow?

**Comment by sebastienros** [comment]
I tried from the netcoreapp21 branch, maybe I should have merged dev ... trying again

**Comment by jtkech** [comment]
Just tried from the netcoreapp21 branch without merging dev, it works for me.

**Comment by sebastienros** [comment]
Have you used it from a published folder?

**Comment by jtkech** [comment]
I will try it

**Comment by jtkech** [comment]
You're right, i got the same

**Comment by jtkech** [comment]
Okay, it's a problem specific to the `netcoreapp21` branch where we compile views at the module library level. So, a module needs to reference the projects / packages which define the tag helpers which are used in its views, this to be correctly precompiled. And we only see the problem in a non `Development` mode where we use precompiled views.

To fix it in the `netcoreapp21` branch i added the `ResourceManagement` (which defines tag helpers) reference in the `OC.Media` and `OC.Flows` modules projects.

**Todo**: Check all modules to see if there are other missing references. The problem is that when a tag helper is not defined the html is just rendered as it is but the precompilation doesn't fail.

Hmm, if we want to use the new razor sdk which allows precompiled views in module libaries, maybe good if we could put all of our tag helpers in only one (or a very few) dedicated module(s).
