### ISSUE TITLE
Error on login: Unable to resolve service for type 'OrchardCore.Email.ISmtpService' 

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1736]
Using the latest version, since the ResetPassword branch has been merged, there is an error when you want to login to the admin:
InvalidOperationException: Unable to resolve service for type 'OrchardCore.Email.ISmtpService' while attempting to activate 'OrchardCore.Users.Controllers.AccountController'.

**Comment by sebastienros** [comment]
Create a difference controller for password reset, or inject the service in the method of the actions that need it.

**Comment by agriffard** [comment]
A dependency to "OrchardCore.Email" has been added in the Users Manifest module to prevent the error.

Is it the good solution?
Do we have to add "OrchardCore.Email" in the recipes?

If we disable the Email module, it won't wrn you that other modules will be disabled and will lead to an error.

**Comment by sebastienros** [comment]
no, we don't want to have email enabled just because we need use management. What about a feature in Users, with its own controller, that requires Email?

**Comment by jtkech** [comment]
> If we disable the Email module, it won't wrn you that other modules will be disabled

Yes, it works for other features but not this one, i'm working on this.

**Comment by jtkech** [comment]
@agriffard @sebastienros sorry, finally the confirmation message works for me.

It's my fault :(, i was using.

    Dependencies = new [] { "OrchardCore.Email, OrchardCore.Authentication" }

in place of this. Notice the additional quotation marks because it is an array of strings.

    Dependencies = new [] { "OrchardCore.Email", "OrchardCore.Authentication" }

For infos, when you add a dependency on "A", look at the dependencies of "A" and so on, because of the transitivity you may be able to remove some deps and have a lighter manifest file, but take care.
