### ISSUE TITLE
blog post

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#1741]
when i add blog post directly from new it doesn't add to blog and i can't set pramlink to set for blog 
and test editor for blog post template is not complete like article editor

**Comment by Skrypt** [comment]
When using the admin menu the New --> Article is not a blog post. Article is a content type that creates a page without using the FlowPart that is used instead of a BodyPart when using New --> Page. The confusion here is that Article is not a blog post. To create blog posts you need to go the the Content --> Content Items and open the Blog you created to see the list of posts that are in that blog and to be able to edit or create new blog posts from there. The current admin menu doesn't have a quick link to create blog posts.
