### ISSUE TITLE
SMTP Settings : Shape type 'SmtpSettings_Edit' not found

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#1745]
![image](https://user-images.githubusercontent.com/3228637/39417623-952b0e32-4c23-11e8-9b2c-a32d7c5b8216.png)

**Comment by agriffard** [comment]
The view SmtpSettings.Edit.cshtml is in OrchardCore.Email\Views. 
It works for me.

**Comment by Skrypt** [comment]
I'm getting this from dev branch. I did a build clean and still getting it.

**Comment by Skrypt** [comment]
git clean -xdf fixed the issue

**Comment by agriffard** [comment]
@Skrypt Using OC.Application.Cms.Targets nuget package, with the latest version, when I go to `/Admin/Settings/SmtpSettings`, I have the same problem you mentionned: 
`Exception: Shape type 'SmtpSettings_Edit' not found`

Even if I clean and retry, there is an error.

**Comment by jtkech** [comment]
Just tried a new app which references the Cms package (beta2-5572), it works on my side?
Tried with Agency and Blog setups, only in debug mode, not in a published context.

**Comment by agriffard** [comment]
It works if I try on a new project and use TheAgencyTheme.

but on 2 other solutions previously created, that uses custom themes, the error is still occuring.
Can this be related?

**Comment by jtkech** [comment]
So, i could repro the exact same issue by renaming the shape, then i reverted back the change but still had the same issue. This because when you just rename a razor file (or delete and sometimes add) you have to do a rebuild on the related module / theme project (or the app).

So, i think that at some point the view (or an override one) was registered in the email module (or a custom theme) but not embedded in the assembly.

**Comment by agriffard** [comment]
I tried to make the same operations on another application but I am still having an error:
`InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.ILookupNormalizer' while attempting to activate 'Microsoft.AspNetCore.Identity.RoleManager`1[OrchardCore.Security.IRole]'.`
I guess this is because of the dependency between the Email and the User module but I can't manage to make it work anymore, even if I modify the json of the Features in the database.
