### ISSUE TITLE
Left Menubar on Admin Login Form

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#1761]
I tried to install Orchard Core without any User facing theme only with TheAdmin theme. I could see left panel with hamburger button on Admin Login page and Logoff Link
![image](https://user-images.githubusercontent.com/13991195/39660063-3f5e74d6-4fec-11e8-95c6-657541e9a287.png)

**Comment by Skrypt** [comment]
Why would you not assign any frontend theme?

**Comment by matiasmolleja** [comment]
Maybe it could be a common use case. Using Orchard as a backend only? I mean a CRM or something like that.

**Comment by Skrypt** [comment]
Yes but you would still need to have a Theme applied for the Login/Registration forms on the frontend.

**Comment by matiasmolleja** [comment]
But, If there is no frontend that is not needed, right?
The only thing that it is needed in that scenario is not showing the admin layout before the user is actually logged in.

**Comment by Skrypt** [comment]
I understand what you mean. Could work.

**Comment by matiasmolleja** [comment]
You are right, I think that in this scenario the menu is "hidden" by OrchardCore.Admin.AdminMenuFilter.cs

When we provide the empty layout it can be shared by the 4 views on Account: ChangePassword, ChangePasswordConfirmation, Login and Register.
The empty layout will have a "RenderBody()" and each view will render itself there.
It's already working like that on the Setup module.

So we provide an empty layout when the only available theme is an admin theme.

And we could do it at two levels . 
1. An empty layout that will be used by OrchardCore.Users .  That won'be very nice but it will work on TheAdmin and on any other Admin Theme too.

2. After that,  If we want to provide a customized nice looking login layout for our "TheAdmin" theme, we can add there another layout that will override the previous one and will use our styles there. Any other custom Admin theme can do the same.

What do you think? Maybe we are thinking too much? Do you know any other simpler way of achieving the same end result?

**Comment by Skrypt** [comment]
I'm trying to repro the issue first. I disabled The Agency theme leaving only TheAdmin and SafeMode themes enabled and the frontend falls back to the SafeMode admin theme. When I disabled the SafeMode it returns me a Layout not found error.

**Comment by Skrypt** [comment]
Ok first, there's all kinds of wrong in this. TheAdmin theme has in it's Manifest.cs file a Tag = Admin for Orchard to understand that this theme, or any other one, is an admin theme. So, for having TheAdmin theme as a single theme applied we need to force it in the database because it can't be done directly from the admin UI. Normal usage would be to disable the current frontend theme and then it would make it fallback to the SafeMode theme. 

Issue here that I see is that we should prevent admin theme from getting applied on frontend because it is wrong. This should be prevented also from recipes and falling back to the SafeMode theme if someone tries to.

Then for someone who wants to use TheAdmin theme as a starting point for creating a CRM he would need to duplicate TheAdmin theme and remove the Tag = admin in it's manifest file and rename the theme. This is not optimal for someone who doesn't want to take care of both Themes.

So, going back to the main issue, which is that someone wants to only have a login when using Orchard as a SaSS solution. We handle that scenario when using the SaSS recipe included in TheTheme. So if someone wants to use Orchard as a SaSS platform then he should use TheTheme (which displays as The Default Theme) in the Orchard backend.

So, I think that what we need to do is to have a better TheTheme theme ! If we are landing on that Theme the default home page should be the login page that would have some Orchard styling.

**Comment by rserj** [comment]
Sorry for short description provided in a ticket. I think I need to shed the light a bit of usage scenario and how to reproduce the issue.

I use Orchard Core as "Software as a service" so I referenced only Nuget Modules I need for Setup and Admin Tool support, see below
![image](https://user-images.githubusercontent.com/13991195/39667364-1f8bb948-5069-11e8-857f-4f56782163df.png)
(On a screen above I do not need a Email but I have to add it because of dependency)

In a recipe I enabled only Features I need for SaaS with Admin Tool support
"OrchardCore.DataProtection",
        "OrchardCore.Mvc",
        "OrchardCore.Admin",
        "OrchardCore.Commons",
        "OrchardCore.Authentication",
        "OrchardCore.Features",
        "OrchardCore.Navigation",
        "OrchardCore.Recipes",
        "OrchardCore.Resources",
        "OrchardCore.Roles", 
        "OrchardCore.Settings",
        "OrchardCore.Tenants",
        "OrchardCore.Themes",
        "OrchardCore.Users",
        "TheAdmin"
When I'm navigating to root page "/" I'm getting only white screen this is correct but when I'm navigating to /Admin I'm getting Left Menu bar.

+I have another scenario.
Our customers often want host Admin Tool on a different domain, because of security concerns, we have massive Admin Tool which allows managing settings for multiple back-ends, so in order to support such case we have to separate modules only for AdminTool and User faced site.

I think we should support having TheAdmin only the Single Theme, it should be also simple from the usage perspective, just installing recipe with TheAdmin theme

**Comment by Skrypt** [comment]
Still the OrchardCore.Themes module makes a distinction between Admin themes and Frontend themes and the Admin UI tools won't let you assign an admin theme on frontend. So we should never assign an admin theme for frontend. If you look at a frontend theme it has dependencies for making Fluid views to work. That's the reasons why I think the logic should stay how it is for our normal use case.

Though, If you are developping your frontends by only consuming Orchard Web API then you probably don't need to use any frontend themes in your tenants. The issue happening is that if you assign no Theme to your frontend then it will fall back to the SafeMode theme. So you assigned TheAdmin theme manually in the database as a frontend theme. So the question I'm asking myself is : What's wrong in using TheTheme as a frontend theme in that scenario on your SaSS server deployment? Does it prevents you from consuming the Web API from a different server/website?

**Comment by Skrypt** [comment]
Maybe a flag in the frontend theme settings could fallback to the current Admin theme. Something like CurrentThemeName : "false"

**Comment by rserj** [comment]
I do not familiar with Themes in Orchard. Please see my answers below

>The issue happening is that if you assign no Theme to your frontend then it will fall back to the SafeMode theme.

I didn't enable SafeMode theme either, I enabled only TheAdmin theme

>What's wrong in using TheTheme as a frontend theme in that scenario on your SaSS server deployment?

Nothing wrong with it, It is just not obvious to me, I have to enable FrontEnd theme in order to get TheAdmin theme work properly.

>If you want to add customizations on the SaSS server what's better between separating Admin/Frontend themes per tenants or not?

I'm not planning to use FrontEnd theme on any tenants.

I do not want to use TheAdmin theme as Front-end theme, I can just add a default/home route which will redirect to /Admin url.
I just think we should not tight TheAdmin theme to FrontEnd one, we should have an ability to use them separately. Please see below, how it works for me right now
![image](https://user-images.githubusercontent.com/13991195/39669742-8490ae44-50a9-11e8-8b4a-fb935dbfe290.png)

**Comment by Skrypt** [comment]
Yes but you are changing the standard behavior of Orchard.Themes modules by not providing a SafeMode theme ...

**Comment by Skrypt** [comment]
Well I leave this one to @sebastienros I think I explained what are the issues about doing what you want to do. You would only need to have a frontend theme for the Login page like I explained earlier. Your solution is a custom one made from Nuget packages which is different than what we are developping. You are free to do wathever you want with it 😄 ! I just think that in the main Orchard Core repo we should not permit this to happen.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/39670029-60bb3e7e-50c9-11e8-9bba-6f578e9d69e7.png)

Here is what happens when you apply TheAdmin theme on TheAgency tenant recipe on it's frontpage. It's not pretty.

**Comment by Skrypt** [comment]
Of course the login still display because that route is registered by OrchardCore.Users module.
![image](https://user-images.githubusercontent.com/3228637/39670068-a19ed63e-50ca-11e8-877c-a88e737b075f.png)
But if you would want to add customization you then need to edit TheAdmin theme views and CSS which is not where you should have your overrides set. This is why we have frontend themes mainly. If you makes changes to TheAdmin theme views and CSS then you are using your own TheAdmin theme.
