### ISSUE TITLE
Load balanced data protection

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1824]
Data protection keys are currently stored on disk, which is an issue for a multi node environment behind a load balancer.

There's plenty of other storage options (SQL, Redis, Azure Storage), and I think we should support at least Azure blob storage out of the box (keeps Sébastien's bosses happy). Should be easy enough to do, we just need to make sure we maintain the current data protection tenant segregation.

**Comment by PinpointTownes** [comment]
> I think we should support at least Azure blob storage out of the box (keeps Sébastien's bosses happy).

It's worth noting that DP special-cases apps hosted in Azure and will automatically store your key ring in `%HOME%\ASP.NET\DataProtection-Keys`. which is synchronized across all the instances of your app (so that it just "works as it should OOTB").

Having an ABS-backed store is mainly useful if you want to easily share your DP keys between multiple apps or between deployment slots.

**Comment by paynecrl97** [comment]
The use case that I have is an application hosted on Azure VMs behind a load balancer
