### ISSUE TITLE
Create a Mini Profiler module

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1895]
And if possible make it display diagnostic sources.
Also YesSql should expose diagnostic sources (@Jetski5822 will agree on this one)

**Comment by jrestall** [comment]
What about a Glimpse module with a plugin for YesSql?

OrchardCore.Glimpse
OrchardCore.Glimpse.YesSql

Profiling can be written to the timeline tab. 
http://getglimpse.com/Docs/Timeline-Tab

**Comment by Skrypt** [comment]
Glimpse has now moved to Node.js
https://github.com/Glimpse/Home

And both their websites seems to be down : 

http://node.getglimpse.com/
https://getglimpse.com/

**Comment by jrestall** [comment]
Thanks @Skrypt, I didn't realize Glimpse had stopped actively supporting the ASP.NET version. I guess I just assumed they would after being acquired by Microsoft :laughing: 
I humbly take back my suggestion, keep up the great work guys!

**Comment by PinpointTownes** [comment]
Glimpse is dead, killed by Azure Application Insights (even the Node.js version is no longer developed).

I know @sebastienros strongly disagrees, but Glimpse died the day the 2 maintainers joined MSFT.

**Comment by sebastienros** [comment]
I just disagree with "Microsoft killed Glimpse". The maintainers decided to stop contributing once they started their job at MS. When I joined Microsoft I stopped contributing to some of my old projects too, and continued some others that still seemed interesting to me. By experience Microsoft doesn't tell you to stop working on what you want outside of work.

**Comment by sebastienros** [comment]
@JamesNK does it mean you will stop contributing to JSon.NET? Is Microsoft killing it too?

@PinpointTownes I still believe this was their choice. You know how it works, you spend the time you can and you want on open source projects. It's your own time and if you decide to stop then it's your decision. I wouldn't blame you if you stopped contributing to OpenIddict, I won't blame them for Glimpse. Maybe it's because they joined Microsoft and have other priorities, but I don't think it's because of Microsoft per se. Unless they were bribed into stopping their contributions, but I can't imagine this is the case. Is it what you are implying?

**Comment by PinpointTownes** [comment]
> You know how it works, you spend the time you can and you want on open source projects. It's your own time and if you decide to stop then it's your decision.

I don't question the decision, I criticize the motivations, clearly explained in Nik's comment:

> The team is no longer pursuing Glimpse. Look for similar experiences to be baked into Visual Studio and Azure over time.

Glimpse was not abandoned because the team didn't have enough time or motivation to work on it but because it was replaced by an Azure offer... Application Insights. This is a business decision, not a personal one.

> @JamesNK does it mean you will stop contributing to JSon.NET? Is Microsoft killing it too?

Did Microsoft publish 2 blog posts in which they explicitly said they'd support JSON.NET's development when James was hired like they did for Glimpse? I don't think so. And hem, JSON.NET has no equivalent service in the marvelous Azure world so they have no reason to kill it :smile: 

> I wouldn't blame you if you stopped contributing to OpenIddict.

If I did that, I'd do my best to find new maintainers or at least merge PRs aiming at making it compile with ASP.NET Core.

There's still a strong interest for Glimpse and yet, the 2 original maintainers deliberately ignore PRs or comments, instead of responsibly transferring the ownership to the folks interested in maintaining it. That's precisely what makes me think Glimpse was KILLED and not just abandoned because it became irrelevant.

**Comment by Skrypt** [comment]
@PinpointTownes Microsoft is a company ; so that implies it's driven "also" by profits. If I was indirectly contributing on a project that would create a competition against the company I work for. I'd probably rethink my position. 

I think we all agree that Glimpse was a nice tool and that it's "sad" that it's not available anymore as an open source licenced project. Though, there's surely other project initiatives out there that will come out of it. Let's be smarter than just trying to find who's fault it is... that's not the point of this topic. 😉

**Comment by PinpointTownes** [comment]
> @PinpointTownes Microsoft is a company ; so that implies it's driven "also" by profits. If I was indirectly contributing on a project that would create a competition against the company I work for. I'd probably rethink my position.

You probably missed this part is my previous message:

> Resources were instead allocated to App Insights (for business reasons I can understand).

I don't blame Microsoft for making money. I blame them for having explicitly said they'd support Glimpse. This was a total posture and a FUCKING LIE.

**Comment by Skrypt** [comment]
Yes but still there's 2 parts involved in this decision. Microsoft and the Glimpse owners ... so that's both their faults if you want to see it that way. Though, at the time that they got hired they'd probably had all good intentions and afterward they maybe found that they had way less time to work on Glimpse. They still worked on it for quite some time... So, stating that this is a lie is maybe hard on both of them. There are projects like these that changes all the time. Both in open source and proprietary software world... Nothing is all black and white when it comes to human decisions. Personally I understand the reasons ; and I don't really care that much about it because there are still alternatives.

**Comment by sebastienros** [comment]
Moving on, who wants to do this module?

**Comment by Skrypt** [comment]
I'm available after Localization 😉

**Comment by PinpointTownes** [comment]
@Skrypt you're right, this ticket is probably not the right place for that so I replied on Gitter :smile: 

@sebastienros maybe one should ask Nick if he'd be interested in helping?
