### ISSUE TITLE
Content Tree feature: Design

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1900]
Please @sebastienros, explain us what are the requirements to implement the Content Tree feature.

**Comment by bleroy** [comment]
My repo is here: https://bitbucket.org/bleroy/nwazet.tree/src/default/

Steal what you want. Happy to describe it and answer questions, but it should be pretty straightforward. Basically, you have providers that can feed items into the system, hierarchically. Works quite well.

**Comment by matiasmolleja** [comment]
I think one of the ways to navigate to content items that would be useful is a "menu based" one. 

For example:
1. The user select one menu content item from a listbox at the top of the left side bar. Normally the main menu.
2. The selected menu is shown in the form of a tree on the left.
3. The user can quickly go to any page-contentItem on the site, and start editing.
4. Ideally a button on each of the "branches" of the tree will show a popup with the available creatable types, so that the user can , with a single action, create the content item and positioning it where he or she wants it to be.

Some others CMS are doing it like that. And I think it's a quite common use case anyways.

**Comment by SchipperStash** [comment]
I was just reviewing OrchardCore as a potential candidate to replace Episerver. 

A basic content treeview with editing on click is critical and one of the factors people are using these commercial CMS's. I don't think it would be difficult to compete, but with sites that have hundreds or thousands of pages, the current one I just reviewed would never work. 

e.g. Solution Explorer on the left, content on the right. It's how all the content people I've met want to edit the site and it's a huge bonus if you can security trim the tree and only show the page types that are available from that node.

The current way seems like all the pages would get lost, there is no hierarchy by url (ala wordpress). There really is no clever re-engineering needed, what's worked for decades is still the preferred way. Url's are a hierarchy, not a random collection of pages. (imo)

Eagerly watching this issue to see how this will pan out as a remotely viable alternative.

**Comment by sebastienros** [comment]
@SchipperStash thanks for the feedback, we are indeed also working on a way to browse the content by reflecting the main menu in the content tree.

**Comment by agriffard** [comment]
PR made in #2479
