### ISSUE TITLE
the key ring of DataProtection is potentially shared between tenants

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#1966]
just as the note on NotifyFilter class
// Note: this filter is not located in a module that depends on the DataProtection module.
            // As such, we can't guarantee the key ring is not shared between tenants. To ensure cookies
            // encrypted by this tenant can't be read by another one, a sub-protector is always created.
dataProtectionProvider.CreateProtector on other places may make the key ring of DataProtection potentially shared between tenants

**Comment by sebastienros** [comment]
This should not be necessary because the data protector is registered another time at the tenant level with an isolation using the tenant name:

https://github.com/OrchardCMS/OrchardCore/blob/39f5f230f14f58b437fad1621c713417d91c124c/src/OrchardCore/OrchardCore.Modules/Extensions/OrchardCoreBuilderExtensions.cs#L140-L164

The key is also store in each site's folder under App_data.

**Comment by PinpointTownes** [comment]
Thing is nothing guarantees this extension will be ultimately called: folks that directly use `services.AddOrchardCore()` instead of `services.AddOrchardCms()` will have to manually call `AddDataProtection()` and chances are extremely high they won't call it.

In this case, services and modules that depend on DP will get a non-isolated DP stack, which completely sucks from a security perspective.

@jtkech was there any particular reason not to register the tenant-aware antiforgery, authentication and DP services directly in `services.AddOrchardCore()`?

**Comment by PinpointTownes** [comment]
Once we're 100% sure the tenant-aware DP services are always registered (independently of whether you're using the CMS helpers or the lower level framework components), we should remove the manual isolation step in `NotifyFilter`.

**Comment by sebastienros** [comment]
Right, we need to change it to be called in AddOrchardCore

**Comment by jtkech** [comment]
@PinpointTownes @sebastienros 

> was there any particular reason not to register the tenant-aware antiforgery, authentication and DP services directly in services.AddOrchardCore()?

No particular reason on my side, just because before you could run a setup recipe without the DP module, or an app without any recipe as the sample mvc and nancy apps.

So, no problem i will add it to `AddOrchardCore()`.

Then, what you think about these ones, do we keep them in `AddOrchardCms()`? And / or maybe another `AddOrchard()` which integrate the 3 tenant-aware security services. As you want.

    .AddAntiForgery()
    .AddAuthentication()

@PinpointTownes 

> we should remove the manual isolation step in NotifyFilter

Do you mean just use ?

    _dataProtectionProvider.CreateProtector(nameof(NotifyFilter));

**Comment by PinpointTownes** [comment]
Ideally, the antiforgery, authentication and DP tenant-aware services should all be registered by `AddOrchardCore()`, not just DP.

> Do you mean just use ?

Yup!

**Comment by jtkech** [comment]
Okay cool, i will do it.

**Comment by PinpointTownes** [comment]
> I'd love to understand why we need to register AuthenticationSchemeProvider a second time at the tenant level though.

Because it holds a reference to an underlying dictionary, responsible of storing the registered schemes. If we don't re-register it at the tenant level, the service - and thus the dictionary - is shared between all the tenants, which prevents enabling and disabling schemes per tenant. That's why we have to re-register it manually.

**Comment by sebastienros** [comment]
Thanks, I updated the source code with this information
