### ISSUE TITLE
Recipes should be idempotent

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1970]
Running the same recipe steps multiple times should result in the same outcome.
It is technically possible to create recipes that are not idempotent, for instance by generating a new guid for content item ids on every run, but this should be an unrecommended practice.

**Comment by sebastienros** [comment]
Related issue: https://github.com/OrchardCMS/OrchardCore/issues/1121

**Comment by sebastienros** [comment]
We should have different verbs on content item manipulation:
- Create (like POST)
  - not idempotent, always creates a new content item version
- Update (like PUT)
  - idempotent, replaces or updates a content item based on a mandatory content item version id
- Patch (like PATCH)
  - not idempotent, either creates or updates a property of the document

**Comment by nuno-tiago-reis** [comment]
Currently this applies to anything imported through package import right?

For example if I export content items of a given type they are duplicated (it seems to be the current behaviour, instead of being updated, the records are duplicated, sometimes in the database, sometimes in both the database and the front-end).

**Comment by nuno-tiago-reis** [comment]
@sebastienros 

Currently this applies to anything imported through package import right?

For example if I export content items of a given type they are duplicated (it seems to be the current behaviour, instead of being updated, the records are duplicated, sometimes in the database, sometimes in both the database and the front-end).

**Comment by deanmarcussen** [comment]
Yes, currently there are a number of issues (addressed in the linked pr) related to importing existing content items.

New content items have no problem

**Comment by agriffard** [comment]
Closed by #5487 I guess.
