### ISSUE TITLE
what happen when "Data Protection (Azure Storage) " enabled

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#1984]
because AddDataProtection(builder); is inside AddOrchardCore,
is it possible there is a conflict for Data Protection after Data Protection (Azure Storage) is enabled?

**Comment by jtkech** [comment]
So, now we can register custom startup classes at the host level **but which are executed in an isolated container of a given tenant**, as we do for other module startups. This is the case of the `OC.Mvc` module which doesn't exist anymore and has been replaced with the `OC.Mvc.Startup` class.

We can also use e.g the following which adds the provided lambda to a list of actions which will be executed by a custom startup class `OC.Modules.StartupActionsStartup`, and this as described above.

    builder.ConfigureServices((services, serviceProvider) =>

You can also pass an optional order whose default is 0. If different orders are used, more than one `StartupActionsStartup` will be created and registered. Note: `OC.Mvc.Startup` has an order of `-200`.

So `OC.Mvc.Startup` runs first (unless a module specify an order < -200), then, because they are registered first,  `StartupActionsStartup` is executed before all modules which have a default order of 0.

So for DP, as before, some host services are registered by aspnet helpers. Then `StartupActionsStartup` **registers isolated tenant level services** as done before by the DP module. And then the azure one can override the configuration. Before the azure startup had a positive value to run after the DP module.

![startups](https://user-images.githubusercontent.com/8586360/41494209-74ee0e78-7110-11e8-84c5-ebcd368ef001.png)

Finally, about the fact that the azure feature don't have to replace or re-register all DP services, but just has to configure what it needs, has been validated by @PinpointTownes.

**Comment by sebastienros** [comment]
@jtkech What are you trying to say? Are you just confirming that everything still works as expected, but with way more words? And some picture of the debugger? ;)

**Comment by jtkech** [comment]
Oh, maybe @infofromca was just thinking that before he would need to disable the DP module before enabling the DP azure feature, which is no more possible. But there is no problem because before the azure DP module had a dependency on the old DP module.

**Comment by infofromca** [comment]
but I think it is better to explicitly set order on Data Protection (Azure Storage), such as 5 or 10

**Comment by jtkech** [comment]
My bad i removed it because at some point the "startups" registered by the app had a big negative value. As said above it still works but you're right it's better to have a positive value for a module intended to override some configurations. I suggest 10 as `OC.Media.Azure` is now using for the same reason.

Could you do a PR which will close this issue when merged?

**Comment by infofromca** [comment]
will do it
