### ISSUE TITLE
Exception if previously visited Media folder doesn't exist

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2049]
from @jtkech 

Found the issue about OC.Media.

Let say that you create a Test folder under Media through the admin, then display its content.

Then close the browser, delete App_Data and redo a fresh setup.

Then, go back to the admin and display the assets. Because it has memorised the last displayed media path, i think on the client side, it tries again to display the Test folder which doesn't exist anymore. Then it fails with the exception mentioned above.

Let me know if it is the intended behavior or if we need to open an issue because some things need to be cleaned up, e.g when we close the browser, i don't know.

**Comment by matiasmolleja** [comment]
I think it's good to keep the last visited folder between browser sessions.
Instead of cleaning local storage when closing the browser I would prefer to improve the experience in the few cases that this error occurs.
For example right now the UI does not do anything. It shows an empty fonder that does not even exist. It should go to the root folder 
And the error in the console is a full html error page. It should be a short text message.

**Comment by jtkech** [comment]
Okay, as you want.

So, i don't know how it would behave with azure blob, but with file system storage i would suggest to just not fail when the physical path doesn't exist. See my suggestion here #2054.
