### ISSUE TITLE
Updatable page layouts at runtime

### ISSUE THREAD

**Issue by jakubsenk** [OrchardCMS/OrchardCore#2064]
Hello,
is there a way we can change the liquid or cshtml files so they won't be embedded in final dll package? We would like to change them anytime at runtime without recompiling and publishing entire solution.
I mean to separate the UI files from the code. This is the way it works in SharePoint, ASP.NET Forms/MVC for many years and this is quite helpful when it comes to deployment because we don't have to restart entire application pool and it's generally easier to work with.

**Comment by sebastienros** [comment]
When debugging you can already change the files dynamically. It's only on production that you should not be able to do it (however it might still work, have you tried?).

Otherwise we have the Templates feature that lets you change the templates from the admin. It's more efficient as it will also work when the sure uses multiple nodes, as opposed as it you would do it on the file system.

**Comment by sebastienros** [comment]
Please reopen if it doesn't work as I suggested.

**Comment by OndrejValenta** [comment]
Ok, thanks. We'll take a look at that feature. We have not noticed it.
