### ISSUE TITLE
Make an Orchard Core Documentation with Orchard Core

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2130]
Does anyone want to use Orchard Core to make an offline copy of "https://orchardcore.readthedocs.io/en/latest/" to place multiple languages, menus, paths, etc. into the template content library? It will also be an offline help file, and examples, thanks to everyone who is willing to work hard.

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2056

**Comment by sebastienros** [comment]
You can already download everything as it's on github, hence you can clone it. Or you can use @agriffard 's script to generate it locally with mkdocs. Or you can use a website extractor, that would download all the content online.

We can't use Orchard to handle the documentation, because that would be much harder.

**Comment by pgy866** [comment]
Thank you
