### ISSUE TITLE
Setup issue with dotnet core 2.1

### ISSUE THREAD

**Issue by sbiaudet** [OrchardCMS/OrchardCore#2221]
When I wan't setup a new version or new tenant, I've this issue. I try with différents versions since last days and it the same. It's a netcore 2.1 app.

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
Generated Code

'__Modules_OrchardCore_Setup_Views_Setup_Index.T' hides inherited member 'RazorPage<SetupViewModel>.T'. Use the new keyword if hiding was intended.
+
        public Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer T { get; private set; }

Do you have any idea ?

**Comment by jtkech** [comment]
Hmm, that would mean that, in the `_ViewImports.cshtml` of the setup module, you have.

    @inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>

That, unlike other modules, you would need to remove.

**Comment by sbiaudet** [comment]
I’ve no modules, only orchardcore.application.cms.target

**Comment by jtkech** [comment]
@sebastienros this is what we already do when precompiling the setup view in the context of the setup module. And then when using this precompiled view at runtime.

The problem occurs **only in debug mode** when the setup view is re-compiled at runtime (as we want) in the context of the application. So here, all view imports are used and also the one provided by `ThemingFileProvider` which forces the inheritance. Then, the result is that we have 2 `T` properties.

- So, one simple solution would be to just rename the injected property to avoid conflicts.

But but but, `ThemingFileProvider` was usefull when we didn't define a view imports so that we were still inheriting of our razor page. But now **this would only work in debug mode**, in other modes we now use the views which have been precompiled in the context of their modules, so without `ThemingFileProvider`.

- So, i think the best fix is to just remove `ThemingFileProvider` and when we want theming we have to do the inheritance (e.g through a view imports), as we now have to do even without this change.

 - **Just tried, it works**.

- Finally, also remove `DisplayManagement` and `ResourceManagement` tag helpers in the setup view imports which are not used, and then remove the related references in the setup project file.
