### ISSUE TITLE
AddDataProtection Beta1 -> Beta2

### ISSUE THREAD

**Issue by FreshRob** [OrchardCMS/OrchardCore#2293]
On migrating from Beta1 to Beta2 I see that data protection was added.

This has caused our application not to startup  
``` csharp
"Access to the path 'c:\\**\\**\\**\\App_Data\\**\\***\\DataProtection-Keys' is denied."
```

I tried adding redis

``` csharp
services.AddDataProtection().PersistKeysToRedis 
```

but no luck

If there was a way to set The type of DataProtection

As well as  have the ability to disable it since we use Orchard on readonly apis

**Comment by Jetski5822** [comment]
Seems weird... I can see in the code its trying to create the directory. Does the directory exist at least?

**Comment by FreshRob** [comment]
@Jetski5822 logging is reporting it is unable to access the path, I also had instances of locking when running integration tests.

I believe there should be a way of customising the DataProtection rather then always having Directory

**Comment by jtkech** [comment]
You can override DP through a module startup as done by `OrchardCore.DataProtection.Azure`.

    public override void ConfigureServices(IServiceCollection services)
    {
        var blobName = $"{_shellOptions.Value.ShellsContainerName}/{_shellSettings.Name}/DataProtectionKeys.xml";

        services.AddDataProtection().PersistKeysToAzureBlobStorage(GetBlobContainer(), blobName);
    }

    ...
    public override int Order => 10;

Or through the app startup.

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms(builder =>
            {
                builder.ConfigureServices((collection, serviceProvider) =>
                {
                    ...
                    ...
                }, 10);
            });
        }

But here it seems to fail on `CreateDirectory()`. There are other modules wich use `CreateDirectory()` as `OC.Tenants`, `OC.Lucene`, `OC.Media` ... But maybe they don't fail because the related directory already exists because your application has been first executed locally and then published.

So, maybe you would have to do the same, or any other way, so that in your published environment you will have the `App_Data/Sites/TenantName/DataProtection-Keys` subfolders.

**Comment by sebastienros** [comment]
Assuming you are running in IIS, grant write access to the App_data folder to the service account.

**Comment by FreshRob** [comment]
The only modules we use are
OrchardCore.Module.Targets
OrchardCore.Mvc.Core
OrchardCore.Application.Mvc.Targets

Which would be why we haven't had the issue before.

Unfortunately I am unable to set permissions for iis instances as we use the same image for all applications

**Comment by Jetski5822** [comment]
Yeah, they don't store state, they simply use the tenants.json file if I remember correctly.

We really need to remove any kind of state based stuff inside of `AddOrchardCore`, i.e. creating directories

**Comment by jtkech** [comment]
I first thought to move `AddDataProtection()` to `AddOrchardCms()` and let people which use `AddOrchardCore()` adding it if they they want. Or to make it again a module.

But we also call `AddAuthentication()` at the app and tenant levels which calls `AddDataProtection()`, [see here](https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication/AuthenticationServiceCollectionExtensions.cs#L24). So, at this point i think we need our `AddDataProtection()` to be tenant aware e.g by calling `.SetApplicationName(settings.Name)` and which do some cleanups (e.g remove duplicate startup filters).

 So i think that anyway we would need to make only one helper, maybe `AddSecurity()`, or only one module feature. Then what happens if on a read only system someone still want security. It will have to write its own module to do the specific stuff and cleanup we are doing but without creating a directory.

So, as suggested by @Jetski5822 we could just move out the directory creation and `.PersistKeysToFileSystem(directory)` to an individual helper or a module feature as done for `OrchardCore.DataProtection.Azure` which do `.PersistKeysToAzureBlobStorage()`.

But maybe good to always have this by default. So, i tried to comment out the directory creation and `.PersistKeysToFileSystem()`. It was still working, so for this specific case why not just using a try catch block on an `UnauthorizedAccessException`. Then if it fails to create the directory we don't use `PersistKeysToFileSystem()`.

**Comment by sebastienros** [comment]
I suggest you use a different implementation of DataProtection.  If you are using Redis then it should work just fine, maybe it was not correctly configured on your side?

**Comment by jtkech** [comment]
Yes but this line will be still executed and will fail on a read only system.

                var directory = Directory.CreateDirectory(Path.Combine(...

I will suggest a PR.

**Comment by Jetski5822** [comment]
Yup - the issue is not the data protection apis... it’s the way we store state. We are imposing something we shouldn’t be.

**Comment by PinpointTownes** [comment]
Copied from https://github.com/OrchardCMS/OrchardCore/pull/2308#issuecomment-417505933:
____________

> Maybe need to be confirmed by @PinpointTownes

Yup, if you don't set the directory path yourself (via calling `PersistKeysToFileSystem`), the default Data Protection storage resolution logic will automatically kick in. This is terrible in our case as it means we could end up registering a shared storage like `%LOCALAPPDATA%` or the registry for all tenants. It's only when both the `%LOCALAPPDATA%` folder and the registry are unavailable that DP falls back to the in-memory repository.

Having a shared key ring would make tenants terribly vulnerable, as things like cookies/tokens or encrypted settings created for tenant A could be read by tenant B (and vice versa).

That being said, I realize the current code is not ideal as it completely prevents a host from starting if the tenant-specific DP folder can't be created. To improve that, I suggest 2 options:

  - Creating our own `EphemeralXmlRepository` (the one in ASP.NET Core DP is internal and we have no way to register it, except by using reflection, which sucks) and falling back to it when we can't create the directory. This way, we completely bypass the default DP logic that may result in a shared repository being used.

  - Falling back to the host-provided DP services **and** registering a tenant-aware `IDataProtectionProvider` instance at the tenant level to provide the isolation between tenants. This way, we use DP's default logic resolution (so a shared place may be selected), but we still provide the necessary isolation at a different layer. This was our initial plan before we moved to a per-tenant-DP-keys model per @sebastienros' demand (not for security, just to make exporting keys easier): https://github.com/OrchardCMS/OrchardCore/issues/1391.

**Comment by sebastienros** [comment]
We are imposing lots of things ;) Opinionated framework ...
And we need to store some things somewhere. We happen to have App_data for that, right?

Here the issue is that App_data is readonly, which we don't expect. I don't even think it's a bug. But we should have other ways to store the DP keys, that is all IMO.

**Comment by Jetski5822** [comment]
I don’t care we have data protection apis being added... it makes sense. However the way we store the state should be abstracted off. 

Also I think we need options to not register components.

**Comment by Jetski5822** [comment]
(Hit close by mistake)

**Comment by kamikyo** [comment]
I have another question about DataProtection
My project looks like this：
![image](https://user-images.githubusercontent.com/7645337/45405614-30825e80-b696-11e8-86f5-03851be8874e.png)
My entry's Startup.cs like this (ps:this site i call it A):
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddDataProtection()
                .SetApplicationName("App Name")
                .PersistKeysToFileSystem(new DirectoryInfo(@"phisical path"))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(36500));

            services.AddOrchardCore()
                .AddMvc();
        }
```
I use IDataProtector to encrypt data on another website (ps:this site i call it B).
I will get an exception when using IDataProtector.Unprotect on site A,like this:
```
System.Security.Cryptography.CryptographicException
  HResult=0x80131430
  Message=The key {2ac4ef1f-05f7-444e-b1cd-7ad490bebacf} was not found in the key ring.
  Source=Microsoft.AspNetCore.DataProtection
  StackTrace:
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
```
But when I moved the following code to the module's Startup.cs
```
services.AddDataProtection()
                .SetApplicationName("App Name")
                .PersistKeysToFileSystem(new DirectoryInfo(@"phisical path"))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(36500));
```
The error didn't happen,it was worked fine.
Of course, I am using IDataProtector.Unprotect in the module of site A.
Why are there such problems?
