### ISSUE TITLE
Decoupled CMS feedback

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2332]
Here are some improvements to make the decoupled CMS story compelling

- [ ] Create an empty recipe which enables CMS modules and doesn't have any content definition
- [ ] Current extension methods require to inherit from a base `RazorPage` class, which is a View. The `Page` base class doesn't have the `OrchardCore` property. The best solution would be to make the `OrchardCore` helper injectable, which could then be set at the page level, or in the ViewImports. It could then have scoped state if necessary.
- [ ] Make new razor pages and changes detected dynamically in development mode. https://github.com/OrchardCMS/OrchardCore/pull/2316
- [ ] `ExecuteQueryAsync` should return `IEnumerable<T>`
- [ ] The login page uses a front end controller that requires a Layout shape. I am thinking we should serve these pages from the admin theme, and provide a different set of controllers for the front-end (in a separate feature). Or a set the TheTheme as the default front-end theme to serve as a fallback for front-end views that are accessed by mistake (TheAdmin can't be used in a front-end controller so far).

**Comment by psijkof** [comment]
https://github.com/psijkof/EmptyCMS
Can be added to main repo or shall I release it as a nuget package?

**Comment by sebastienros** [comment]
I didn't check your repo, but I made a recipe for this. I'll look at the differences, thanks.

**Comment by psijkof** [comment]
Yes I saw after (decoupled cms demo 1)...

**Comment by jtkech** [comment]
@sebastienros just for infos.

Yesterday, regarding this one, because most of extensions just use `HttpContext` to resolve services, i thought about just using `HttpContext` extensions and defined them in the related `.Abstractions` to not have to reference modules. E.g `Context.CultureName`, `Context.GetContentItemIdByAliasAsync()`... So that we can use them in our razor pages / views **but also in pure aspnet mvc razor pages / views**, e.g if we want to reference `OC.ContentManagement` but not `OC.DisplayManagement`.

Only one extension uses a `DisplayHelper` that we could resolve but with a `ViewContext`, so here maybe an extension on `ViewContext` (that have an HttpContext prop), e.g `ViewContext.DisplayAsync()`.

Another solution was to use extensions on the common `RazorPageBase` of all razor pages / views, and on which we can retrieve `Context` and `ViewContext` props, but we would have to use `this.SomeExtension()`. Hmm, but at least for our custom razor pages / views we could just have a property which just return `this` and then apply the extensions on this property.

**Comment by jtkech** [comment]
Oups, i thought i was on your PR.

Yes, i did it quickly and i saw that we need to inject a service if in an mvc page / view. That's ok for me but because i thought before of a possible solution which would not need this, i wanted to share it here.

**Comment by sebastienros** [comment]
Related to your comments, we'll probably use the metapackages, so all modules should be referenced from the app, and I am using an empty namespace, this way all extension methods are available.

I want a specific object, like `@Html`, so no `this.SomeExtension()`
