### ISSUE TITLE
CaaS (Content as a Service)

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#2370]
Any plans to implement CaaS (Content as a Service) in Orchard Core?   I was taking a look at Drupal and I noticed it has CaaS.  I would like to see a .NET Core CaaS implementation.  Everything I have seen so far is PHP.

**Comment by sebastienros** [comment]
We call it Headless CMS. I will make a demo at some point. We already are exposing "some" rest apis, and have a graphql PR almost ready that some devs are already using.
And because OC is multi-tenant we can host as many "CaaS" sites as we want on a single deployment.

**Comment by mdockal** [comment]
If you can do that surely OC supports a Hybrid CMS approach as well.  One where you can use OC as the CMS front end but also pull content to other devices through web APIs (Content Services).

**Comment by jrestall** [comment]
I've been working on using OC as a Headless CMS. There's a number of areas that need work.

- GraphQL - Check the [jsonapi](https://github.com/OrchardCMS/OrchardCore/tree/jsonapi) branch. Some recent thoughts on the API are at https://github.com/OrchardCMS/OrchardCore/issues/2360.
- Webhooks - I've implemented a module for this [here](https://github.com/jrestall/OrchardCore/tree/jrestall/webhooks/src/OrchardCore.Modules/OrchardCore.Webhooks).

I'd be interested in what features you are looking for.

Here's some items I think would be nice:
- GraphQL ordering, filtering, pagination.
- GraphQL authentication/security model.
- A JSON Object Field would be useful in an Headless CMS.
- A Headless CMS recipe (removes unnecessary modules such as Themes, Resources, Templates etc)
- An API Explorer module (Tidy up and style the [graphiql](https://github.com/graphql/graphiql) page in the json api branch)
- Templated webhooks for easy integration with popular services (Netlify, Discord, Mailgun etc)

**Comment by mdockal** [comment]
@jrestall I would like to see a Hybrid CMS,  one that would use Orchard Core as the CMS but have API to pull a piece of content to a mobile app for instance for a product or product(s).  I assume this is what they are trying to accomplish with the [jasonapi](https://github.com/OrchardCMS/OrchardCore/tree/jsonapi) branch.   Don't know much about GraphQL still trying to learn what it is about.   I also looked at your pull request webhooks module #2323 I like it.  I am contemplating a project where if something was posted to a blog post it would be posted to the user's social media account(s) that they have hooked into.  Based on what I read about your webhooks module this should work.   I tend to agree with the other guys that it needs to be part of a workflow.    Please keep us posted on your progress!

**Comment by alberthajdu** [comment]
+1 for the Headless CMS recipe (or Headless CMS NuGet package + dotnet template).

**Comment by ifle** [comment]
+1 for the Headless CMS

**Comment by sebastienros** [comment]
GraphQL has been merged in dev, early demos here: https://t.co/gzqJqa8lJZ

**Comment by MatthijsKrempel** [comment]
@jrestall 
Going to have a look into your webhooks module, while workflow is cool and solves the problem, webhooks is more lightweight and simpler.

**Comment by jrestall** [comment]
I agree @MatthijsKrempel, the average CMS user might struggle to configure a web hook if they had to go through Workflows. I also think Web Hooks should be a first class feature and not hidden in Workflows.

My module does duplicate a lot of the Workflow functionality though, so the best design would be to template out a workflow configuration and introduce that on the main navigation menu.  

There are some things my module does that Workflows currently doesn't, such as sending default metadata headers with the webhook request, signing of the request, form URL encoding support instead of JSON, retry and timeout policies via Polly, optional SSL validation and of course the simple to configure UI.

Demo:
https://www.youtube.com/watch?v=dTET-8-8HBQ&t=2159s

Module Code:
https://github.com/jrestall/OrchardCore/tree/jrestall/modules/webhooks/src/OrchardCore.Modules/OrchardCore.WebHooks
