### ISSUE TITLE
Layout not found from Razor Page with route

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2385]
Repro:
Create this
```razor
@page "{name}"

@functions {
public string Name {get;set;}
}
Hello
```

And in `_ViewStart.cshtml`

```
@ { Layout = "_Layout"; }
```

`_Layout.cshtml` is created in `Views\Shared`

Without the custom route, the layout is used.

**Comment by jtkech** [comment]
Okay, i will check it.

I'm working on other view locations related to #1921.

**Comment by jtkech** [comment]
@sebastienros 

---

**Just tried with the dev branch, it works on my side with or without the route.**

---

**What doesn't work** is if you put in the `_ViewStart` : `Layout = "../Views/Shared/_Layout.cshtml"`. When you put it in the page it works, the requested view path is still relative to the app's module virtual folder. But if you put it in the view start it fallbacks directly to `/Views/Shared` from the content root.

If i put this in the view start it works

    Layout = "../.Modules/OrchardCore.Cms.Web/Views/Shared/_Layout.cshtml";

I think it's quite easy to fix this use case by also serving views when requested from the content root, not only through the app's module, but do you think it's worth to implement this case?

**Comment by psijkof** [comment]
In Razor Pages, Layout should be in Pages\Shared.
That currently doesn't work when referencing Orcharch.

**Comment by jtkech** [comment]
@psijkof 

When talking about the application as a module, it is the final application which is not a module but behaving as a module when defining things at the app level, controller / views, shapes, views, pages.

An OC app don't call directly things as `.AddMvc()`, `AddRazorPages()` ... This is done through helpers in the isolated context of each tenant (at least one named `Default`). So, normally app level mvc things can't work, this is why we made the app behave as a "module" whose virtual location is `.Modules/ApplicationName`.

After a quick look to your `VanillaRazorPagesApp`, is it an application? You use `Sdk.Web`, `netcoreapp2.1`, `AspNetCore.App`, but you reference `Module.Targets`. Oh yes, so you did an app and then you want to use it as a module in another application. Great idea, maybe to test it independently,

So this is not the same sense as described. Never tried, not sure it works with our msbuild scripts. Anyway, for the following tests, i assume that your app is in fact a regular module / theme.

**Static files**

- At the module level, in `TheBlogTheme/Pages/Bar1.cshtml`, this works.

      <img src="~/TheBlogTheme/theme.png" alt="ASP.NET" class="img-responsive" />
      <img src="/TheBlogTheme/theme.png" alt="ASP.NET" class="img-responsive" />

- At the application level, in `/Pages/Bar.cshtml`, (i put the same image under the app `wwwroot`). Here we just replaced the module name by the application name (the application's module name).

      <img src="~/OrchardCore.Cms.Web/theme.png" alt="ASP.NET" class="img-responsive" />
      <img src="/OrchardCore.Cms.Web/theme.png" alt="ASP.NET" class="img-responsive" />

- We call `UseStaticFiles()` at the tenant level to serve all modules static files (including the app's module), that's why the above works. Then, assuming that your application also call `app.UseStaticFiles()` in its startup, its static files can also be served like this.

      <img src="~/theme.png" alt="ASP.NET" class="img-responsive" />
      <img src="/theme.png" alt="ASP.NET" class="img-responsive" />


**/Pages/Shared**

- It works both at the module and the application level when using #2386.

**asp-page anchor tag helper attribute**

- Here it's not a routing attribute, it is the name of the page related to its path. So, in a normal application where the page root directory is `/Pages`, `/Foo` point to `/Pages/Foo`. Then, in a page directly under `/Pages`, using the relative `Foo` without leading slash also point to `/Pages/Foo`.

- In our case at the module level, in `TheBlogTheme/Pages/Bar1.cshtml`, this works.

      <a asp-page="/.Modules/TheBlogTheme/Pages/Foo1" class="navbar-brand">FooPage</a>
      <a asp-page="Foo1" class="navbar-brand">FooPage</a> // or other relative paths.

    But the following doesn't work because there are wrong absolute paths.

      <a asp-page="/TheBlogTheme/Pages/Foo1" class="navbar-brand">FooPage</a>
      <a asp-page="/TheBlogTheme/Foo1" class="navbar-brand">FooPage</a>
      <a asp-page="/Foo1" class="navbar-brand">FooPage</a>

    But, because we define default route templates, you can just use `href` attributes.

      <a href="/.Modules/TheBlogTheme/Pages/Foo1" class="navbar-brand">FooPage</a>
      <a href="/TheBlogTheme/Pages/Foo1" class="navbar-brand">FooPage</a>
      <a href="/TheBlogTheme/Foo1" class="navbar-brand">FooPage</a>

    Then, by using `AddModularFolderRoute()` or `AddModularPageRoute()` as in the `OC.Demo` module, you will be able to use e.g.

      <a href="/AnyFolderName/Foo1" class="navbar-brand">FooPage</a>
      <a href="/Foo1" class="navbar-brand">FooPage</a>

- In our case at the application level, in `/Pages/Bar.cshtml`, for the same reasons this works.

      <a asp-page="/.Modules/OrchardCore.Cms.Web/Pages/Foo" class="navbar-brand">FooPage</a>
      <a asp-page="Foo" class="navbar-brand">FooPage</a> // or other relative paths.

    But not e.g.

      <a asp-page="/Foo" class="navbar-brand">FooPage</a> // relative path.

    But, because of our default route templates, you can just use `href` attributes.

      <a href="/.Modules/OrchardCore.Cms.Web/Pages/Foo" class="navbar-brand">FooPage</a>
      <a href="/OrchardCore.Cms.Web/Pages/Foo" class="navbar-brand">FooPage</a>

      // Because it is the application's module, we don't create this default template.
      //<a href="/OrchardCore.Cms.Web/Foo" class="navbar-brand">FooPage</a>

      // In place of the above, for the app's module we create this one.
      <a href="/Foo" class="navbar-brand">FooPage</a>

**Comment by jtkech** [comment]
@sebastienros just for infos

For testing i renamed `.Modules` to `Areas`, it opens many possibilities. For pages under `Areas` razor remove `Areas` and `Pages` segments from pages names / paths without custom conventions. We could re-use the default page root directory `/Pages` so that razor don't want to watch them from the root `/`. I think we could also get rid or simplify some view location expanders and so on.

I read a little the RCL doc, their stategy is that e.g if a library defines pages under their `Areas` or `Pages`,  they are respectively "imported" to the app `Areas` or `Pages`, where the app can override them. In my test this is what is defined in `{module}/Pages` which is "imported" in the app `/Areas/{module}/Pages`.

Maybe worth to discuss on this, but there would be many things to check.

**Comment by psijkof** [comment]
@jtkech Thanks for the explanation. 
I started with the App using Cms.Targets.
But having a Razor Pages module, seemed more like I would actually use it.
Starting with a default 'Web App' (dotnet default template) I showed what I had to change to make it work as a Module for OC.
Perhaps all I should have referenced was Module.targets to avoid any confusion and still be able to use IOrchardHelper?

Anyway, great work. I know it's perhaps not feasible, but the less I should have to change to make a 'web app' work as a module, the better it would be, or at least as long it's clear why and what I need to change.

Thanks for the great work, hope soon we see the changes you made merged.

**Comment by psijkof** [comment]
Seems to work great in a razor pages module scenario. We're building the modern business theme with razor pages in [repo](https://github.com/psijkof/ModernBusiness.OC.RazorPages)
If we however request for a non existent page, we get a 
![image](https://user-images.githubusercontent.com/25638593/46612512-b0221280-cb08-11e8-970e-84cb05218f04.png) ```Exception: Shape type 'Layout' not found```

Why is it trying to find the Layout in a ´404´ situation? What should we supply to create a decent (preferably styled according to the modern business template) error page?

Thanks for the insights!

**Comment by psijkof** [comment]
Follow up: We added a Layout.cshtml in the themes project, in location Pages\Shared. When a razor page from a module looks for 'Layout', that file is found and used.
However, if a request comes for a non existent page, OC looks for a Layout shape in Views in the themes folder.
Would it be a good idea to display the 404 content in that file?

**Comment by jtkech** [comment]
So, i you have the cms with the theming engine and then a selected teme, normally you just have to use a regular layout which render the body, and then a not found page in the shared folder, as done in `TheBlogTheme`. So try to create and use this view `YourTheme/Views/Shared/NotFound.cshtml`

**Comment by psijkof** [comment]
@jtkech If I place the `Layout.cshtml` back in `Views` of the Theme project, I get a not found by the localization of the layout page for the razor pages

```
/Areas/ModernBusiness.Theme/Pages/ModernBusiness.Pages/Layout.cshtml
/Areas/ModernBusiness.Theme/Pages/Shared/Layout.cshtml
/Areas/ModernBusiness.Theme/Views/ModernBusiness.Pages/Shared/Layout.cshtml
/Areas/ModernBusiness.Theme/Views/Shared/Layout.cshtml
```

That's why I put it in `Views\Shared`.

But then, when I request a non existing page, OC complains it can't find the Layout page... It is looking in the theme project, `Views `folder. 

Also, putting the Layout.cshtml as is, with RenderSection commands, it faults with the error:
```
An unhandled exception occurred while processing the request.
InvalidOperationException: RenderSection invocation in '/Areas/ModernBusiness.Theme/Views/Layout.cshtml' is invalid. RenderSection can only be called from a layout page.
Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureMethodCanBeInvoked(string methodName)
```

Any idea what I should do here?

**Comment by jtkech** [comment]
Yes, with a `RazorPages.Page` you specify the layout, but when not found it acts as a "normal" themed `Razor.RazorPage`, that's why the layout is searched in the theme `Views` folder.

Then, i think you need to call our `@await RenderBodyAsync()`, not `@RenderBody()`.
