### ISSUE TITLE
Cannot override base shapes in custom Theme.

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#2415]
I created a Message.cshtml file in my theme to style differently the message shape . But it  is  not picked up from my theme. It still uses the default shape coming from  :

OrchardCore.DisplayManagement.Shapes.CoreShapes.Message method.

This was working before I upgraded to the latest  version in dev branch.

**Comment by jtkech** [comment]
Hmm, for this one i found the following which seems to not be used anywhere in our solution.


    [Shape]
    public IHtmlContent Message(dynamic Shape)
    {
      TagBuilder tagBuilder = OrchardCore.DisplayManagement.Shapes.Shape.GetTagBuilder(Shape, "div");
      string type = Shape.Type.ToString().ToLowerInvariant();
      IHtmlContent message = Shape.Message;
      tagBuilder.AddCssClass("message");
      tagBuilder.AddCssClass("message-" + type);
      tagBuilder.Attributes["role"] = "alert";
      tagBuilder.InnerHtml.AppendHtml(message);
      return tagBuilder;
    }

It doesn't add any alternate and seems to apply to a given shape / model which has a `Message` and a `Type` (message type) properties. So, because i tried it in the `Content-Article.cshtml`, for testing i added to the `ZoneHolding` these 2 properties.

Here the result which works and where we can see that there is no alternates. So, an alternate of any name needs to be added explicitly by code before rendering this message shape.

![message](https://user-images.githubusercontent.com/8586360/46181442-0d76c200-c2c6-11e8-99b9-fb8633ed6e85.png)

**Comment by deanmarcussen** [comment]
Hi @jtketch

I had a look at this behaviour and yes, there are no alternates by default for any core shapes.

But by placing a `Message.cshtml` file in `TheAdmin` (or other theme) you would anticipate that it would be able to provide an override for a core shape.

The reason it doesn't anymore is because of this line in `ShapeTableManager` from https://github.com/OrchardCMS/OrchardCore/pull/2290
 
```
// let the application acting as a super theme for shapes rendering.
if (enabledAndOrderedFeatureIds.Remove(_hostingEnvironment.ApplicationName))
{
    enabledAndOrderedFeatureIds.Add(_hostingEnvironment.ApplicationName);
}
```

Because all the attribute shapes come through with a shape descriptor of 
`ShapeAttributeBindingStrategyOrchardCore.Cms.Webmessage`
whereas the template binding comes through as
`ShapeTemplateBindingStrategyTheAdminmessage`

So when the shape table manager orders the shape descriptors with
`.OrderBy(sd => enabledAndOrderedFeatureIds.IndexOf(sd.Value.Feature.Id))` 
the core shapes always win because the `OrchardCore.Cms.Web` feature is the winner / super theme.

Beyond that I'm a bit lost, but the `ShapeAttributeBindingStrategy` is picking `OrchardCore.Cms.Web` from the `ITypeFeatureProvider` as the feature name, whereas the `ShapeTemplateBindingStrategy` picks up the feature name from the `IShellFeaturesManager` (i.e. the modules name). 
So maybe changing that would be the way forward, but I'm not sure if this wouldn't have a knock on affect somewhere else?

**Comment by jtkech** [comment]
@deanmarcussen i think you see everything ;)

Yes the template one is based on the presence of a given template file under a given module, that's why it uses `IShellFeaturesManager` to retrieve all the enabled module paths.

The other retrieves registered shapes defined by code, that' why it uses `ITypeFeatureProvider`. And yes it retrieves `OC.Cms.Web` (the app's module) when a shape provider is registered by the app.

Just tried, if we register `CoreShapes` through the `OC.Contents` module startup, it works.

Maybe good to keep the ability to override a shape through the app, even it is by code. I will think about it, maybe we could tie shapes as `CoreShapes` to another subfeature of the app's module.
