### ISSUE TITLE
Bug - Adding second bag item fails with content picker

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#2422]
I made a content type with a content picker.  then I made another content type with a bag part that only accepts the type with the content picker.  When I add a new item to the bag the content picker works fine.  However when I go to add a second item to the bag the content picker does not show up.  That's the bug

**Comment by aodl** [comment]
Just to add to this issue I'm encountering similar problems - giving an content item more than one ContentPicker fields causes all but one of the ContentPicker dropdowns to break on the content item editing page. I think it might have something to do with the scripts being added to the page multiple times. I guess adding more than one ContentPicker field is supposed to be invalid? However a similar issue is also caused when adding just one ContentPicker field to a widget, and then adding that widget to a content item via a Flow part.

**Comment by aodl** [comment]
The problem ended up being quite simple. It was just that if more than one content picker field existed on the page, they both had the same Id (preventing vue multiselected from mounting the elements by Id). Used `Guid.NewGuid().ToString("n")` in the Id to fix.

Also, the reason that this broke with FLow, Bag, and WidgetList parts even when they only contained a single content picker item is that the ".Edit" template for all of these parts explicitly renders an additional *mock* content item for each type that the Flow/Bag/WidgetList can support (so that the editor scripts for those types are already added to the page before any ajax editor loading takes place).
