### ISSUE TITLE
publish project include too many files

### ISSUE THREAD

**Issue by Eternity8013** [OrchardCMS/OrchardCore#2448]
Publish without runtime still include all files.
And another question is how to publish cshtml files in some module,I don't want them to be precompiled for easy modification。

**Comment by sebastienros** [comment]
@Eternity8013 what do you mean by "all files", which ones should not be published yet still are?

@jtkech can you remind us here how to deploy including the csthml file?

**Comment by jtkech** [comment]
At the modules level it is no more possible. At some point we were doing it through custom msbuild scripts, then just when publishing the application in a temp folder to precompile modules views with the old tool. Now, modules views are never copied.

It is possible but it involves to re-use more complex msbuild scripts.

Then at the application level all is possible with the following options.

    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
    <MvcRazorExcludeViewFilesFromPublish>false</MvcRazorExcludeViewFilesFromPublish>

As i remember, just setting `RazorCompileOnPublish = false` automatically set the other options so that views are published and also compilation libraries under the `refs` folder.
