### ISSUE TITLE
How use favicon 

### ISSUE THREAD

**Issue by KANekT** [OrchardCMS/OrchardCore#2486]
[favicon_package_v0.16.zip](https://github.com/OrchardCMS/OrchardCore/files/2468205/favicon_package_v0.16.zip)

```
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

I load files in wwwroot, but in now view on my site 
https://innoline.pro/InnolineTheme/site.webmanifest or
https://innoline.pro/site.webmanifest

**Comment by sebastienros** [comment]
Two probable reasons:
- the `site.webmanifest` file might not be served because it's extension is not registered in the static file provider. This file is in the theme apparently, I am not sure how it would be configured if this is the case. @jtkech any idea?
- you are missing the `/InnoLineTheme` prefix in your links. If the static file is coming from a module or theme then you need it.

**Comment by agriffard** [comment]
Ading a new Mime type on IIS does not seem to be enough.
I added File name extension `.webmanifest` and Mime type = `application/manifest+json`

**Comment by sebastienros** [comment]
Definitely not enough, it's an aspnet core static middleware issue.

**Comment by jtkech** [comment]
`StaticFileOptions` has a `IContentTypeProvider` but this is not a collection and by default it is initialized to a new `FileExtensionContentTypeProvider`. So, a module would need to create a wrapper of this provider and which provides additional types. And then configure `StaticFileOptions.ContentTypeProvider`.

**Comment by sebastienros** [comment]
Ok, so we are injecting the options for the module static file provider: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs#L128

So you think the instance in the default option would be null? If not we could just have a custom configuration step in the main startup to update these options?

**Comment by jtkech** [comment]
Any module (application's module included) can do it in its `ConfigureServices()`.

    services.Configure<MvcOptions>((options) =>
    {
        options.ContentTypeProvider = new CustomContentTypeProvider();
    });

But, because it's not a collection, only the last one will win.

In our `AddStaticFiles()` another solution would be to also resolve all `IContentTypeProvider` so that people would just need to implement one to just add more types. And then wrap them in a composite type provider and pass it to `StaticFileOptions.ContentTypeProvider`.

**Comment by sebastienros** [comment]
But it's it really necessary to create a new one, isn't the an instance in the property already?

**Comment by jtkech** [comment]
If no module set it before it is null and then they set it to a new `FileExtensionContentTypeProvider`.
https://github.com/aspnet/StaticFiles/blob/master/src/Microsoft.AspNetCore.StaticFiles/StaticFileMiddleware.cs#L60

So, a module can configure this property e.g with an `IContentTypeProvider` which wraps a `FileExtensionContentTypeProvider` and provides more types.

Or we could do this and use the DI to resolve the types to add, and make a simpler helper to allow people to register additional types without having to implement a full `IContentTypeProvider`.

**Comment by sebastienros** [comment]
I suggest we add an appsettings section like we did for media.

**Comment by agriffard** [comment]
In which module (existing or new one) would we add this allowed static file extensions configuration?

**Comment by KANekT** [comment]
Bug is fixed?

**Comment by agriffard** [comment]
You can now upload .webmanifest files.
