### ISSUE TITLE
IShellHost.GetScopeAsync should accept a tenant name

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2518]
Right now it requires a full shell settings object. It would be easier to only require the tenant name.

**Comment by jtkech** [comment]
Replace or a new method?

So, e.g in place of calling `TryGetSettings()` and then `GetScopeAsync()`, we could do it in one call. But maybe here we would need a `TryGetScopeAsync()` because we were using `TryGetSettings()`? Or do you prefer to throw an exception if the tenant name is not valid?

And then what about `GetScopeAndContextAsync()`?
