### ISSUE TITLE
IShellSettingsManager should not expose GetSettings

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2519]
https://github.com/OrchardCMS/OrchardCore/blob/ffc405bd01831b734104bf5a1c479d853997ceab/src/OrchardCore/OrchardCore.Environment.Shell/ShellSettingsManager.cs#L101

It's loading all the settings every time. Instead `IShellHost` should provide access to the cross tenant site settings. Usually the site settings are used by being resolved in DI. This is an issue only when we need to resolve services from other tenants.

`IShellSettingsManager` would then only handle loading and storing site settings.

**Comment by jtkech** [comment]
Hmm, it may help also in distributed services when getting settings in a message handler.

I started something here so that `GetSettings()` and `TryGetSettings()` moved to `IShellHost` don't reload all settings. But not sure i well understood what you want.

See the `jtkech/shellSettings` branch and compare because i had problem with github to create a PR.
