### ISSUE TITLE
Menu shape builder (OnProcessing) ignores dynamically added parts

### ISSUE THREAD

**Issue by aodl** [OrchardCMS/OrchardCore#2540]
Extending the Menu content type definition via the admin UI doesn't work properly in all cases. Additional fields and parts can be added to the Menu content type, and then filled in for a specific Menu content item, but they are never added to the Menu shape when it is being populated (during the OnProcessing event for caching purposes) for display in the main site (not the admin site).

Parts other than the ones welded by the MenuContentHandler are currently overlooked when building the Menu shape, and they are therefore not available to be displayed in the Menu template. A workaround would be to inject IContentItemDisplayManager and some other helpers into the template, and call buildDisplay to get the ContentItemDisplayCoordinator to build the whole shape properly. However it seems it would be more helpful for this to be handled during the OnProcessing event with the other Menu shape building logic.

### Reproducing the Problem
- Go to the admin dashboard and add a new field to the Menu content type.
- Go to the Menu content item and fill in the new field with some value, and publish
- Load the any page for your actual site, and you will notice that the field is not displayed anywhere on the menu
- Go to the Menu.cs / liquid template and attempt to access the field on the Model...
- ... it isn't there

**Comment by sebastienros** [comment]
So what you say is that the custom fields data is not on the model, not just that the fields are not rendered. Because if it's not rendered I think that's fine, if it's the data this is an issue. I will test it, but your PR is also rendering some new shapes, which I think is wrong, there is no scenario where someone would get someone usable from the default display of a field in the current menu templates. They would always update the custom template.
