### ISSUE TITLE
Do not embed Assets folder in each module

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2575]
We need to look at every modules and set the Assets folder to not be embedded when the module is compiled or published. Those assets are transpiled/combined/minified and moved in the wwwroot folder of each modules through the gulp pipeline. There is no need to embed those files twice in the compiled/published modules. This will also make the assemblies to be smaller in size.

**Comment by jtkech** [comment]
For this we need to check that there is **no item groups** related to this folder because it is automatically excluded from embedded resources, [see here](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Module.Targets/OrchardCore.Module.Targets.props#L10).

Depending on how there are 1st created or copy pasted, VS may override this by adding an item group. Then, after marking them as not embedded through the UI of VS, the item group has changed but it is still there, but then it is useless and we can remove it.

**Comment by Skrypt** [comment]
So basically what you are saying is that it is fine to have an Asset folder in a module since it will be excluded automatically by the OrchardCore.Module.Targets.props. Which means that we also don't need to specify it like this either :  

```
  <ItemGroup>
    <Compile Remove="Assets\**" />
    <EmbeddedResource Remove="Assets\**" />
    <None Remove="Assets\**" />
  </ItemGroup>
```

**Comment by jtkech** [comment]
Yes, and after removing it the `Assets` folder will show up in the solution but will still not be embedded.

After a quick search i just found that there is an useless item group in `OC.Liquid` and `OC.Queries`. Not related to assets but useless, VS may have added them when creating a new folder without any file.

In the themes projects there are some item groups related to embedded resources but it is because gulp input assets are not in the `Assets` folder but under `wwwroot`.

**Comment by Skrypt** [comment]
We just got confused because I added an Assets folder to the new GraphQL.Api module and we forgot that this folder was automatically not embedded. If there is useless item groups we can clean them.

For the themes we kept the "assets" in the wwwroot folder an excluded those that we didn't needed to be embedded. Maybe we should use the same logic everywhere ; debatable.

**Comment by jtkech** [comment]
Yes, no problem, all is ok for me.

For themes i was just saying to not remove these kind of item groups because we still need them for another reason. Then in `OC.Liquid` and `OC.Queries` there are 2 item groups that we can clean up because anyway they refer to folders that don't exist.

Sorry for my bad english ;)

**Comment by pnda489** [comment]
Stop
________________________________

**Comment by Skrypt** [comment]
???
