### ISSUE TITLE
Rebuilding Lucene Indices after import

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2609]
When we reimport content through the deployment module ; content items are not added to the Indexing table unless you go back and re-publish them one by one. Either we need to add an option so that all published content items be added back to the index table when we rebuild the Lucene index or that we add those records when we reimport data.

I believe that the index table was introduced for performance reasons. @jtkech

**Comment by Skrypt** [comment]
Here is a SQL snippet that I used for this after reimporting data with import/export feature.

```SQL
INSERT INTO IndexingTask ( ContentItemId, CreatedUtc, Type )
SELECT ContentItemId, date('now'), 0 FROM ContentItemIndex WHERE ContentType = 'ContentTypeName' AND Published = 1 AND ContentItemId NOT IN (
SELECT ContentItemIndex.ContentItemId FROM ContentItemIndex INNER JOIN IndexingTask ON ContentItemIndex.ContentItemId = IndexingTask.ContentItemId WHERE ContentType = 'ContentTypeName' AND Published = 1
)
```

**Comment by agriffard** [comment]
This is an important fix to make.
When I Import a Blog and some associated Posts with a ListPart, the posts won't appear in the blog admin page or on front because the indexing hasn't been triggered.

**Comment by sebastienros** [comment]
Maybe we need a step to rebuild an index as part of the recipe.

Another option would be to have an event handler when a recipe is executed (we might already have it) and have the Lucene feature handle it to update the index, not rebuild (or reset).

**Comment by sebastienros** [comment]
I think this should work now, but maybe too well, in a way that each import would trigger a content item to be indexed instantaneously. This might slow down the import process.

A solution would be to make this automatic indexation an option in the lucene service state, have it on by default, and then create new recipe steps, one to deactivate it, one to activate it, and one to rebuild/reset an index.

We could also think about a way to detect that a recipe is running, such that features that don't want to run during the recipe can detect it. In the Recipe service, have a flag to detect that one is running. This way the background tasks would not be triggered, and we could also skip automatic indexing of content items, and detect when the recipe is successful to trigger an update of the index.

**Comment by agriffard** [comment]
Does the Lucene-index recipe step fix this issue?

**Comment by Skrypt** [comment]
No, it's just a setting. Though it's working like @sebastienros mentioned but a little too well as it will trigger indexing a new content item on every record added and it might be slow. We don't want that, we want to batch update the lucene index by parsing them by lots of 100 items at a time. Else it opens up the Lucene file, write in it, close the file, open it, write it ... that's a lot of I/0 in the drive.

**Comment by Skrypt** [comment]
See https://github.com/OrchardCMS/OrchardCore/pull/5487

**Comment by agriffard** [comment]
@deanmarcussen Will you be able to achieve this 'rebuild the Lucene indices after import' enhancement?

**Comment by deanmarcussen** [comment]
@agriffard yes, waiting for a design conversation on https://github.com/OrchardCMS/OrchardCore/pull/5487 

What @Skrypt added works, we just need to look at how to cover `Autoroute` as well, during imports

**Comment by Skrypt** [comment]
Also LocalizationPart doesn't work 😉

**Comment by deanmarcussen** [comment]
I have fixed the content events on https://github.com/OrchardCMS/OrchardCore/pull/5487
and written a test to prove that Lucene indexes are now built on import from a recipe.

They are added for rebuild as a `DeferredTask` by the `LuceneIndexingContentHandler ` and are gathered together and rebuilt at the end of the scope. There might be room for improvements on the sql calls generated, but the existing batching arrangement is working there, to prevent adding these items to the Lucene index until all items have been updated.

What I'm not quite sure on is the `CreateIndexingTaskContentHandler `. That also adds a `DeferredTask`, but doesn't do quite the same batching, so that could be improved, but because items aren't added until the end of the scope, no Lucene updates occur during an import, they wait until the import is completed, and the scope ends.

However unless the `Lucene Background Worker` is enabled, the indexing tasks don't actually do anything, unless I'm missing something?

So from what I find we don't actually need a recipe event to pause either of the handlers `LuceneIndexingContentHandler`, or`CreateIndexingTaskContentHandler`, because all of the work these handlers do occurs at the end of the scope. **Which is when an recipe completed event would fire** , so I think it's already been achieved

Am I missing something here?

(Localization to test still, but I suspect now that all the content events are firing it will just work)

**Comment by deanmarcussen** [comment]
OK tested this against sql server with 1001 content items

It works successfully, but there is opportunity for improvements.

Currently the `DeferredTask` will make 1001 sql queries, as it queries against every content item one at a time, with the content manager.
It could make a larger (batched) query at the start of the task to retrieve them all at once.

This isn't obvious when in normal operations, because there is only one or two content items in the `DeferredTask` set.

I thought the `DeferredTask` would have the advantage that most of the content items are already loaded into the `IContentManagerSession` but they are not!

This is because `DeferredTask` are done on a new shell scope, so the `IContentManagerSession` has been disposed, and a new empty one has been created.

Equally the `IndexingTaskManager` is creating a sql call for each entry, so there is also the opportunity to batch those with one sql call for all of the contexts.

Suggest we leave this issue open to consider further optimizations, but consider the main issue (rebuild after import) fixed

/cc @jtkech

**Comment by jtkech** [comment]
@deanmarcussen 

> This is because DeferredTask are done on a new shell scope, so the IContentManagerSession has been disposed, and a new empty one has been created.

Yes

> It could make a larger (batched) query at the start of the task to retrieve them all at once.

Yes i agree, we would have to retireve all the needed latest / published in one query.

> Equally the IndexingTaskManager is creating a sql call for each entry, so there is also the opportunity to batch those with one sql call for all of the contexts.

Hmm, after a quick look seems that there are already batched sql cmds

**Comment by Skrypt** [comment]
There are enhancements coming in but at least it works, so remaining can be done later on.
