### ISSUE TITLE
Template of "Menu" Not Overriding Theme

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#2631]
I have tried using "Menu", "MenuItem", and "MenuItemLink-LinkMenuItem" as "Configuration --> Templates" to override the theme's files of "Menu.liquid", "MenuItem.liquid", and "MenuItemLink-LinkMenuItem.liquid" but the templates do not render, the theme's files continue to be rendered. 

I also tried removing the theme's files completely but it still falls back to native Orchard Core files / shapes when rendering those items. 

I can use Templates for overriding widgets and other content successfully, just doesn't seem to work with the Menu area. I will update this more if I find other shapes that don't seem to allow template usage.

**Comment by sebastienros** [comment]
Might be related to #2632

**Comment by jtkech** [comment]
Just tried.

First, to see immediately my changes, i removed the cache parameter in the menu shape in `Layout.liquid`.

    {% shape "menu", alias: "alias:main-menu" %}

Then, `MenuItem` and `MenuItemLink__LinkMenuItem` was working. Notice the 2 undercores replacing `-`.

But `Menu` was not working. As i remember it was working. I will dig into it as i have time.

**Comment by jeffolmstead** [comment]
I can validate what you wrote, I tried on my system too and only Menu isn't working properly.  I think my earlier tests had menu wrapped in cache and that was why I thought the other 2 were not working either, good hint on that one.

**Comment by sebastienros** [comment]
1- We might just need to implement the related issue I commented about earlier
2- We need a site settings equivalent to the CDN mode setting, that lets us configure caching from Enabled;Disabled; and Disabled in dev, so that when we develop templates we are not prone to caching issues

**Comment by jtkech** [comment]
Yes, good idea.

Hmm, meanwhile maybe good to find (without caching) why it doesn't work only for the `Menu` template.

**Comment by sebastienros** [comment]
> Hmm, meanwhile maybe good to find (without caching) why it doesn't work only for the Menu template.

Fix the other issue, it will fix why it doesn't work ;)

**Comment by sebastienros** [comment]
Why try to solve something that will be undone again when the other issue is fixed

**Comment by jtkech** [comment]
Indeed ;)

**Comment by jtkech** [comment]
@sebastienros @jeffolmstead 

I found a more global issue.

- `TemplatesShapeBindingResolver.BuildShapeBinding()` create an incomplete `ShapeDescriptor`, so some of its events, e.g `DisplayingAsync()` or `ProcessingAsync()`, may not be called.

- If the template is really related to an alternate, **it's ok for `DisplayingAsync()`** because in `DefaultHtmlDisplay` it is called on the fundamental shape type, but `ProcessingAsync()` and `DisplayedAsync()` are not called.

- If the template is related to the base shape type as `MenuItem`, **no descriptor event at all is called**. So, for this one it's ok as long as we don't have any sub items, because there would not be populated in `DisplayingAsync()`. **Here, the workaround** is to really use an alternate as `MenuItem__MainMenu`.

- For `Menu` because we use the shape helper the 1st issue is to not use `{% shape "Menu"... %}` in place of `{% shape "menu"... %}`, i tried it, the template is found but nothing is rendered because of the above. Then i tried `Menu__MainMenu` but it was not working because here sub items and also alternates (so the alternate itself is not found) are populated in `ProcessingAsync()`. **Here the workaround** is to replace `.Describe("Menu").OnProcessing()`, in `MenuShapes.cs`, by `.Describe("Menu").OnDisplaying()`.

So, i could get it fully working by not using base shape types and replacing one shape descriptor event. But i'm thinking about a solution where our `IShapeBindingResolver` would just add a binding to an existing shape descriptor in place of creating an incomplete one.

**Comment by jtkech** [comment]
@sebastienros @jeffolmstead i found a fix to the underlying issue, i will suggest a PR tomorrow.

@jeffolmstead i saw your other issue #2650, your fix looks good, i will take a look tomorrow.

**Comment by stantoxt** [comment]
I also have the same problem.

**Comment by DaveEmmerson** [comment]
For the benefit of other people who come across this issue (hello future me if I forget):

e.g., menuAlias here is my-menu

{% shape "Menu", alias: menuAlias %}

Template needs to be Menu_MyMenu
