### ISSUE TITLE
Find a way to display contained content items

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2688]
Generic way to route bag part items, or taxonomy terms.
Might be resolved with custom routing templates, with a generic routes handling bag parts, and another one handling taxonomy terms.

Example:
Landing Page has an autoroute, let's say `/foo/bar`. The autoroute part would register this route. But the BagPart module could also register a route like `/foo/bar/projects/{project_slug}`

**Comment by sebastienros** [comment]
The Autoroute part could have some logic to navigate the Json document to the root, and each time the parent also has an autoroute it would append it to the final route and add a special routedictionary controller on how to find the correct node (main content item id + json path to inner one).

Ultimately any contained content item would be routable if it had an autoroute part. The editor would also be clever enough to show the base prefix leading to it.

**Comment by agriffard** [comment]
What was the progress on this one?

**Comment by sebastienros** [comment]
For taxonomies, a generic solution would be to create an action that takes a taxonomy id in one of the url segments, like /taxonomies/4abcdefgh123/colors/blue

**Comment by deanmarcussen** [comment]
I quite liked the concept in sebros/routable

but I think it could integrate it with autoroute (without breaking)
if autoroute always took a jsonPath, then if it was at the root great, if if was at a contained item, also great. (and if the jsonPath null, assume it was at the root - non breaking)

The challenge would be to call the autoroute handler when adding / creating bag items and taxonomy terms. 

Possibly a `ContainedContentManager` could be used instead of the ContentManager to get the difference in behaviour. 
Then handlers could still be invoked. 
With a flag on the context's for contained or standalone.

Advantages are you'd also get publishing dates, and other metadata which is missing (and slightly annoying sometimes when you want it) on contained content items.

**Comment by sebastienros** [comment]
How to route taxonomies:
From a discussion with @deanmarcussen @Skrypt @agriffard @daveblack101

Razor Page
For taxonomy /taxonomy/{id}/{*text}
/taxonomies/1234556787888/categories
/taxonomies/categories/1234556787888/

For term /taxonomy/{id}/{termid}/{*text}
/taxonomies/categories/science/biology/1234556787888/2342424234-2342424234
/taxonomies/categories/science-biology/1234556787888/2342424234-2342424234
/taxonomies/1234556787888/2342424234-2342424234/categories/science/biology

For taxonomy
/taxonomies/categories

`IHandlerAspect` to extract the alias (AliasPart provides one value) and store the value in a specific field of the Term Content Item and Taxonomy. Then used to lookup the term in memory (no query).
Create an index for taxonomies that would store their `IHandlerAspect` value to query. The default `IHandlerAspect` provider returns the Id and a slugified display text. If an AliasPart is not provided the urls will look like `/taxonomies/1234-categories/5678-science-technology/9012-biology

For terms (taxonomies/{taxAlias}/{*termAliases}
/taxonomies/categories/science-technology/biology

"Science & Technology"
