### ISSUE TITLE
Autoroute pattern : Liquid implementations

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2781]
Here is what I did locally ; I changed the pattern editor for the Liquid editor : 

![image](https://user-images.githubusercontent.com/3228637/49404960-100af300-f71f-11e8-8fbd-01a58f1b20d1.png)

I've tried to load a content item from a content picker using this technique : 
https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Contents/README/#loading-from-a-content-item-id

```liquid
{% assign content_picker_somefield = Content.ContentItemId[ContentItem.Content.ContentTypeName.SomeField.ContentItemIds[0]] %}
```

Though, so far, it didn't worked.

The idea for me would be to be able to create a different Alias if someone changes the Field value. That's why I also added back the "Automatically regenerate when editing content" option.

**Comment by sebastienros** [comment]
2 tasks with this issue

- syntax highlighting
- have access to the Content filter

**Comment by Skrypt** [comment]
> Many filters (e.g. ContentItemFilter) use an IServiceProvider obtained from the ctx.AmbientValues.TryGetValue("Services", out var services) to resolve services, but this value isn't initialized in the AutoroutePartHandler.

I see the same problem also in other handlers.

**Comment by lukaskabrt** [comment]
@Skrypt All filters that use `AmbientValues["Services"]` wouldn't work - I see at least these five: `HasPermissionFilter`, `TaxonomyTermsFilter`, `InheritedTermsFilter`, `ContentItemFilter` and `BuildDisplayFilter`, but I don't think the problem is in the filters.

The problem is that when we call `ILiquidTemplateManager.RenderAsync` from the handler, none of methods sets `AmbientValues["Services"]`. If I initialize `AmbientValues["Services"]`, filters start working.

Please have a look at https://github.com/lukaskabrt/OrchardCore/commit/fa1356819ebe0122b476153cfc3212de634d4770 If you think it is an acceptable fix I will make a PR.

**Comment by Skrypt** [comment]
Ok thanks a lot please @sebastienros and @jtkech review the changes if they are adequate I will provide a PR that adds the Liquid editor on the AutoroutePart settings.

**Comment by jtkech** [comment]
Yes, here there is no view and display contexts, there is a pending PR #2772 to create these contexts on the fly, and where we also have a `_viewContextAccessor`.

Meanwhile, because `ILiquidTemplateManager` is a scoped service, LGTM to pass its `_serviceProvider` to be registered in the `services` ambient values of the template context, if it is not already there.

---

Hmm, maybe a new `ContextualizeAsync(this TemplateContext, IServiceProvider)` that would be called in each individual driver before `RenderAsync()`. This new one would create a `DisplayContext` and only set its `ServiceProvider` prop, then it would call the default `ContextualizeAsync(this TemplateContext, DisplayContext)` in which we would have to add null checks on the other properties as `ViewContext`.

This way it would be ready when we will be able to set on the fly the other props of the display context. Also, this way `ILiquidTemplateEventHandler` would be called. But not sure in terms of perf if it is not so useful.
