### ISSUE TITLE
Wysywig Editor: Insert Image in Html instead of Liquid

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2822]
Currently, when you Insert an image from the Html editor, it adds Liquid code.

It can be a bit weird for some users that would expect to be able to see the image in the Wysiwyg editor.

The only advantage seems to be that it will resize the image to the expected size but, from my point of view, we are losing something important for 'standard' users.

**Comment by sebastienros** [comment]
A relatively low risk option would be to render the media url with the prefix only. The only case it would break the site is if the production instance uses a different prefix.

Best solution: Add a setting in the editor (trumbowyg/markdown) to either render media as `img` tags or liquid tags. This way the end user won't have to make the decision, and the admin knows how the site is published. The default would be `img` tag? (most common case) or liquid tag which works in all cases and allows for resizing.

**Comment by PiemP** [comment]
Hi @agriffard,

are you working on it or I can do it by myself? If I con do it by myself how can I proceed? Because in the https://github.com/OrchardCMS/OrchardCore/pull/4490 you tell me to don't use MediaShapes.cs but actually, with your last modify https://github.com/OrchardCMS/OrchardCore/pull/4651, seems to have the need to create a MediaShapes dedicated to trumbowyg option. 

Now in the Media-HtmlBodyPart.Modal.cshtml have some javascript code relative to trumbowyg editor. But this file seems a "vanilla" Media Shape and I believe we need a dedicated version of this shape file to trumbowyg. Can you confirm that? If I'm in fault and If you want, please give me some tips and I try to do this thing by myself (if you are agree about it).

Hope to have write something clear 😆

**Comment by agriffard** [comment]
@deanmarcussen was right and you too, I must have not tested this specific behaviour.
So, first, I need to fix the trumbowyg modal loading (see #4790) introduced by my PR. 

Then, we want to find a way to declare a Setting on the Editor to specify how we select a media (easy) and to retrieve this setting value from the Media Wrapper or Modal (not easy) and, based on it, initialize the trumbowyg.media plugin to insert either some liquid or some html for the selected image in the picker.
