### ISSUE TITLE
Slatejs: Wysiwyg editor

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2828]
Consider using this editor:
https://www.slatejs.org
https://github.com/ianstormtaylor/slate
https://www.npmjs.com/package/slate

Allow in the Content Type Definition to manage the configuration: toolbar, buttons, ...

**Comment by sebastienros** [comment]
The default HTML editor should not have any fancy settings. It's the "default", and it's implementation  might change overtime. If we want to add options that are specific to an implementation, like slate, then it should be in another editor with custom options. And it's fine to use the same plugin for two different editors.

**Comment by scleaver** [comment]
@agriffard @sebastienros Slate looks nice but it looks like slatejs is using React as a dependency. Thoughts on importing another dependency... are you ok with that?

**Comment by scleaver** [comment]
From what I can see it has it's advantages and disadvantages... it's very vanilla which personally I love because IMHO nobody should be assigning fonts and colours in a CMS. This is a content tool, not a presentation tool at this point. So for me, I like that OOTB it pretty much limits the user to bold, headings, lists etc and the approach seems to prevent DOM issues in the resulting markup. This might not be other people's cup of tea though which is why I guess people allow colour and font selection in a WYSIWYG editor.

It looks though that it serialises to JSON and in order to serialise to HTML we might need to write our own code. Take a read of this:https://medium.com/@yurkaninryan/lessons-from-a-year-of-wysiwyg-915135ec846e

If my assumption is correct, although it looks like a powerful editor from which to allow flexible customisations, is it too limited in what it can do straight out of the box?

**Comment by sebastienros** [comment]
If we need to construct the HTML, that would be part of the editor (to store some clean HTML when the editor gets the json document). But it makes sense actually that it works with a json representation, and HTML is just a view of that. I assume that's how it could also be used to generate markdown.

I don't think a simple editor would be hard to configure based on their examples.

**Comment by DannyT** [comment]
Adding another potential replacement wysiwyg editor: https://editorjs.io/ Not super familiar with it but looks decent on first glance.

**Comment by jptissot** [comment]
Another one : https://ory-editor.aeneas.io/

**Comment by leoniDEV** [comment]
there is also [roosterjs](https://github.com/microsoft/roosterjs) which is the control that Microsoft use in Azure DevOps (and I think in other palaces)
