### ISSUE TITLE
Enabling/Disabling Azure media storage module

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#3002]
Maybe this is related to #2038

The behavior I see on @agriffard Try Orchard site (in the tenant created for me), that 

Enabling the AMS module, results some pages of the Admin showing a duplicate warning message that the module is missing configuration (minor issue IMHO)

Disabling the AMS module results in a 400 error and it stays enabled.

**Comment by lukaskabrt** [comment]
I have created a pull request that prevents `Notifier` from showing duplicate messages. It happens because the `MediaBlobStorageOptionsCheckFilter` adds the error message for all requests (even for redirects), these messages are queued in the `Notifier` and displayed all at once.

I was unable to reproduce the problem with disabling the AMS module locally. Maybe @agriffard can give some tips, in case it is specific to the Try Orchard site.

**Comment by sebastienros** [comment]
I concur with @lukaskabrt , couldn't repro on tryorchard. I was able to disable the module.
