### ISSUE TITLE
Upload theme and module from admin menu

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#3011]
I couldnt find any option to upload costume module and theme to orchard core in admin menu.

**Comment by Skrypt** [comment]
This option has been deprecated in Orchard Core since it would require loading/unloading assemblies dynamically. It needs to be re-evaluated when .net core 3.0 will be out since it introduces a way to unload assemblies at runtime. I think we can close this issue since it's a duplicate.

**Comment by sebastienros** [comment]
We expect to be able to support that for themes only, that would only contain static files (js, css, images, liquid templates).

**Comment by khoshroomahdi** [comment]
What about module?
As i know in nopcommerce that based on netcore user allowed to upload theme and module

**Comment by Skrypt** [comment]
In NopCommerce they allow uploading themes and modules ; but you can't update a module on runtime without restarting the app pool because you can't unload an assembly on runtime. You can also uninstall a module which will cause the app pool to restart. Also, updating/uninstalling a module on runtime can cause service interruptions or delay since you are going to sometimes apply migrations to your data. 

The ideal approach, right now, for updating your websites is using docker containers and swapping them. I think this is the best option there is and that explains also why this feature has been deprecated and is not a priority. I think no one is against the idea to reintroduce this feature once we will be able to unload assemblies on runtime... though first iterations will be really experimental.

Also, if we reintroduce this feature it will lead into needing a Module Gallery ... The dev focus right now is on shipping OC beta 3 and after that RC. There's a lot of dev remaining just there.

If you need such feature for yourself you can look in PR's there's been some attempts already on doing such thing which I'm really against since all you need is to learn how to use Docker 😉
