### ISSUE TITLE
Change blog post field

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#3013]
Make blog recepie more simple. For example changing blog post filed to make blog post like wordress by adding continue button, image to show in briefly, add taxonomies.
I hope you could understand what i said.

**Comment by Skrypt** [comment]
The Taxonomies module is currently in development so that's mainly why there's is nothing in the recipe as of now. For blog post images right now there is no way to change the header image per post. Though in the Content-BlogPost.liquid template we could easily make the image dynamic by adding an image field to the BlogPost content type in the recipe and change this line in the template : 

```html
<header class="masthead" style="background-image: url('{{ "~/TheBlogTheme/img/post-bg.jpg" | href }}')">
```

**Comment by sebastienros** [comment]
I don't understand your issue. Can you try to rephrase it, or ask you question in your mother tongue and maybe someone from the community can translate it with the correct meaning?

**Comment by khoshroomahdi** [comment]
I mean that when i create blog recepie it would contain everything that a blog need. Line continue button, a sample taxonomies and so on.
I hope you got that.

**Comment by sebastienros** [comment]
we intend to add tags, right
