### ISSUE TITLE
OrchardCore.Taxonomies is missing reference to OrchardCore.ResourceManagement

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#3067]
The taxonomy edit page has `<script at="Foot">`.  I believe the project has to reference `OrchardCore.ResourceManagement` for it to work.

![screen shot 2019-01-21 at 6 37 02 pm](https://user-images.githubusercontent.com/1766955/51469183-b8e2df80-1dab-11e9-8607-2efc98f4cf5a.png)

**Comment by jtkech** [comment]
@sebastienros 

 I will check it more globally, i found a few  other missing references, i will do a PR.

One simple way is to check all `_ViewImports` and see if the related projects are referenced. But i saw one project which also have a missed reference in the `_ViewImports`.

There is also the opposite, no tag helper of a given project is used but it is referenced in the project file and / or in the `_ViewImports`. **Is it better to also do some cleanups in this case?**


Maybe better but it's not so easy to check all views to see if a given module use or not any tag helpers of a given project, and i don't want to break things.

**For themes** maybe different, we could always keep them. Note: when a theme only use liquid views and then liquid tags helpers, even they are based on the related razor tag helpers, normally they don't need to reference the related projects because there is no razor compilation. 

**We kept these references in themes** because at some point they were using razor views, **maybe good to also remove them after having tried it**. Or maybe the rule for these themes is to always keep them.

No problem, i can do it even it is longer, but i don't want to do useless things ;)
