### ISSUE TITLE
In the content items, buttons Edit and view doesnt work

### ISSUE THREAD

**Issue by Arashz22** [OrchardCMS/OrchardCore#3074]
In the admin panel I cannot change content items and when i press edit or view the page refresh and nothing happens.
I can send admin username and password to your email if someone wanna help me.

Windows server 2012
SQL Server
Both of Master and Dev Branch tested

![untitled3](https://user-images.githubusercontent.com/10775073/51517849-5df3cb80-1e31-11e9-8a37-52281b427757.gif)

**Comment by Arashz22** [comment]
the **local project works** but after publishing and uploading to **server it doesn't work**.

The **href** of edit button in the local project  is : 
`/Admin/Contents/ContentItems/4fbpay34fy7hnsbykdjfmydp47/Edit?returnUrl=%2FAdmin%2FContents%2FContentItems`

but in the published website is : 
`/Admin/Contents/ContentItems?returnUrl=%2FAdmin%2FContents%2FContentItems`

Is it the issue ?

**Comment by sebastienros** [comment]
How do you publish your site so we can try to repro?

**Comment by sebastienros** [comment]
And your contents don't have a display text, looks weird.

**Comment by Arashz22** [comment]
this way I've published.
![publish](https://user-images.githubusercontent.com/10775073/51708192-800b6a80-2038-11e9-8298-23c551865767.jpg)

**Comment by Arashz22** [comment]
This is the dev branch published by me, you can download it from [here](http://arashzandi.ir/myfiles/OrchardPublished.dev.zip)

I've aslo tried master branch.

**Comment by Arashz22** [comment]
pardon me.
I published through the console of visual studio with this command : 
`dotnet publish --configuration Release --output C:\Users\Arash\Desktop\a`

**Comment by jtkech** [comment]
I assigned it to myself but right now i can't repro, i will retry it.

**Comment by sebastienros** [comment]
also we have many users who publish websites online, and this works very well.

**Comment by jtkech** [comment]
Yes, just dowloaded your link, it's like you deployed all the solution because i can also see e.g testing projects. Maybe you have run the publish command under the root of the solution, you would need to clean your published folder and redo the command under the `OC.Cms.Web` folder.

Can be done under VS, as it seems you did to publish to your server, by selecting the right `OC.Cms.Web` project and do a publish on it. There is a folder profile option so that you can publish to a local folder.

Then looking at your screnshot i can see `<a class=... edit-for="test2" href="..."`. The `edit-for` attribute is used to target our tag helper which compute `href` and then `edit-for` is not rendered.

When the tag helper is not resolved and executed, `edit-for` is still present (can be explained by a missing reference), but in this case `href` is not rendered. So i don't understand, will see tomorrow ;)

**Comment by Arashz22** [comment]
I've tried this settings

**1-**
![publish](https://user-images.githubusercontent.com/10775073/51708192-800b6a80-2038-11e9-8298-23c551865767.jpg)

**2-**
and alteratively this commands (with many ways): 
**dotnet publish src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj --framework netcoreapp2.2 --configuration Release --self-contained -r win8-x86 --output C:\Users\Arash\Desktop\a**

none of them helped me and each of them had some new problems and errors.
(the **1**  after coping to host and running nothing shows and the **2** has some errors)
I'm sure that orchard core is OK and this is my mistake.

could anyone publish orchard core and place it in [release page](https://github.com/OrchardCMS/OrchardCore/releases) ?
