### ISSUE TITLE
_ViewStart layout is not working on decoupled CMS at host app after publishing

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3086]
OrchardCore version 1.0.0-beta3-70523

I publish using the following command

```
 dotnet publish -c Release -o "d:\Releases\Fellowship\Web" --self-contained -r win-x64
```
Layout defined at _ViewStart isn't used. The layout must be specified at the pages and view themselves. This behavior does not happen during development. Only after published.

![orchard-core-view-layout](https://user-images.githubusercontent.com/1761249/51696072-979a2180-203f-11e9-86fe-aa0aa8cfbdca.png)

![orchard-core-view-layout-2](https://user-images.githubusercontent.com/1761249/51696161-c1534880-203f-11e9-8b8d-58d6933e63e4.png)

The funny thing is that the _ViewStart defined at module works just fine. The problem is limited at Host App.

**Comment by jtkech** [comment]
Okay, i can repro, thanks for your feedback.

I tested many scenarios at module level and yes i missed this one at the application level.

It is related to how we adapt the relative paths of view descriptors when views are precompiled in the context of their module so that they can be found at runtime in the context of the application. And it is related to the special case of the application which also behaves as a module.

But no problem i fixed the issue, right now i don't work on the dev branch but i will do a PR soon.

Meanwhile i will assigned this issue to myself.
