### ISSUE TITLE
Allow to add localization files from App_Data to application using nuget packages

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3090]
In an application using OC.Cms.Targets package, if you want to include files in App_Data\Localization like .po files, there is an error because they are excluded by msbuild config defined in `OrchardCore.Application.Cms.Targets.targets`:

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <ItemGroup>
    <Compile Remove="App_Data\**" />
    <Content Remove="App_Data\**" />
    <EmbeddedResource Remove="App_Data\**" />
    <None Remove="App_Data\**" />
  </ItemGroup>

  <ItemGroup>
    <ResolvedFileToPublish Include="App_Data\**" Exclude="App_Data\**\*.log">
      <RelativePath>App_Data\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
    </ResolvedFileToPublish>
  </ItemGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/703248/51769263-f5337a00-20e2-11e9-8da3-0aed0865fca1.png)

We need to allow them so we can include the .po files in order to be able to translate the application.

/cc @jtkech

**Comment by Skrypt** [comment]
You don't need to add them to the VS project. You can still create the folder and files and it will get bundled as part of your publish builds.

**Comment by agriffard** [comment]
When I build the application, the files are not embedded in the dll.

In a module, it works, but not in a application.

**Comment by Skrypt** [comment]
Not sure why we remove that folder. @jtkech

**Comment by jtkech** [comment]
This is to not show up `App_Data` under the solution e.g if you have a lot of tenants.

But as @Skrypt said you can put any files under `App_Data` that will be published except `*.log`.

> When I build the application, the files are not embedded in the dll.

Right now only modules embeds files by default, at the app level they are outputed when publishing.

**Comment by agriffard** [comment]
Then, how are you supposed to test the localization when you develop and launch an application on IIS Express? 
The .po files are not taken into account.

The Culture setting is configured on fr-FR and the Localization module is enabled.

**Comment by Skrypt** [comment]
I will test it to see if I can repro locally from a clean source code solution. But I'm pretty sure I did before. Those files on dev runtime don't require to be bundled in the app dll if they are in your app App_Data folder.

**Comment by agriffard** [comment]
Again: it **works with the source code**, but **not with an application using nuget packages** in which you put .po files in App_Data\Localization, enable Localization, add/set a specific culture in settings and launch with IIS Express.

**Comment by Skrypt** [comment]
I tested and I confirm this work with source code solution. Let me test Nuget packages now.

**Comment by agriffard** [comment]
Damn, I tested with another application with nuget packages and it works as expected.

I need to figure why it does not work with the other one.

**Comment by Skrypt** [comment]
I can repro with a po file in the app folder. The issue is with the .po file harvesting when using Nuget packages on an app project.

**Comment by jtkech** [comment]
I will test it this night.

When it doesn't work, can you check if the related files have been published.

**Comment by jtkech** [comment]
Just coming and tried it on my machine.

- So i added a `fr-FR.po` file under `App_Data.Localization` and enabled the localization module.

- First it works in the same way in dev mode or in prod mode where i could check that the file is published.

- That said, in the settings the default culture is a fallback only used when no supported culture is found in the culture list returned by the providers.

- So, if you only use your system culture (no supported cultures) or only add one supported culture and use it, that's ok.

- But if you have more than one supported culture it may depend e.g on your browzer settings. There is the mvc `AcceptLanguageHeaderRequestCultureProvider` which retrieves from the headers some cultures and order them by quality (in my case the winner is fr-FR).

- So, in my case if i add 2 suported cultures fr-FR and en-US, and then select the en-US as the default culture and save it. In the admin features page, where i'm doing my tests, it is still in french. This because the page is requested with a language header where the culture with the higher quality is fr-FR. And because this is a supported culture it doesn't fallback to my default culture setting.

- To force the en-US culture i needed to remove the fr-FR from the supported cultures.

- In the same way if i have only the en-US supported culture and then select the system one as the default culture that in my case is fr-FR. The en-US is now the only one supported culture found in the headers (in my browzer settings, even with a lower priority, i also accept en-US). So, even i selected the system fr-FR as the default culture, it doesn't fallback to this culture, and my testing page is rendered in en-US.

Because of my english, not sure i'm clear ;)

Maybe we would need to allow to remove some providers and / or add custom ones by priority, e.g one which uses the default culture setting and with a given priority.

**Comment by Skrypt** [comment]
I think it works as expected. The issue is not with the ASP.NET Localization middleware. What you explained is a good summary of how it works but there is still an issue with loading .po files under the main application /App_Data/Localization/{{ somepattern }} when we are developping and/or publishing with an application that uses Nuget packages. When I get the time I will debug this and report what I've found. Let's not mix up different issues here, let's start by fixing the issue with the .po files and if someone can give repro steps for the AcceptLanguageHeaderRequestCultureProvider issue then let's fix it in an other issue. If there is an issue with the AcceptLanguageHeaderRequestCultureProvider it is more likely something that should be reported to the ASP.NET core dev team else we are creating weak patches.

**Comment by jtkech** [comment]
Okay.

Just to say that in my case the po file was published under App_Data and was correctly loaded in prod mode, and it was working if we are aware of the other providers. Hmm, but i didn't try to publish an app which only reference packages, i thought it was useless if at the end the file is publisehd at the same location under App_Data. But you gave me a doubt, you're right, need to be tested in this context, maybe the related file is just not published.

**Comment by jtkech** [comment]
Just tried by using the dotnet templates command occms to create an app which only references packages (last dev version). Then i added `App_Data/Localization/fr-PR.po` file as @agriffard did. Then i published the app, the po file is outputed and it was working, i could see my french translation under an admin page.

**Comment by Skrypt** [comment]
I can repro the bug while debugging a Nuget package solution. It's happening when doing dev with Nuget packages. I tried doing what you said with occms but had lots of things to fix with the references before making it work. We're you on latest release?

**Comment by Skrypt** [comment]
Good idea, tonight I'm off I'm taking a break 😉

**Comment by agriffard** [comment]
Another weird behavior: Once deployed in production on my server, the Localization feature is not enabled and I don't mange to enable it from the admin features.
I click on the 'Enable' button, 'Localization was enabled' is displayed but the feature is still disabled: The Enable button is still visible for the feature.

**Comment by jtkech** [comment]
Weird, at least it may explain the 1st issue.
Can you enable / disable another feature?

**Comment by agriffard** [comment]
Non, I can't. 
I might have a problem because any action leads to an error saying the db or the files (tenants.json) are readonly.
I configured the app to point App_Data to another folder bu specifying then env var 'Orchard_App_Data'.
The directory and files are not readonly but may be I need to change the user of the app pool and authorize it to access the folder.

**Comment by Skrypt** [comment]
Are you sure the culture of the system is Fr-FR ? Culture codes are always lowercase.

**Comment by sebastienros** [comment]
Conclusion, there is a bug, we should find the localization files from the App_Data folder when published.

**Comment by Skrypt** [comment]
Conclusion after testing. I made a mistake in my theme by using .cshtml file and .liquid files. When we are publishing the theme it will take precedence on the .cshtml files over .liquid files. This is why my Theme was showing assets from TheTheme because I had copied Razor views from that theme. For cultures I tested back and everything works as expected.
