### ISSUE TITLE
how can i set farsi or arabic calender ??

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3140]
i need to use another calendar like Persian or Arabic calendar. how can i do this?

**Comment by khoshroomahdi** [comment]
هنوز کامل نشده تو خود orchardcmsهست.
از قسمت culture بزاری فارسی تنظیم میشه

**Comment by aghili371** [comment]
thank you Mehdi, but it should able to save English (for query and search) and Persian (just for showing in ui ) date together.

**Comment by sebastienros** [comment]
We support calendars in O1 
- https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Localization/Services/DefaultCalendarManager.cs
- and `ICalendarSelector`

We should do the same here

/cc @DaRosenberg as you implemented it in O1 should be proud

**Comment by aghili371** [comment]
> هنوز کامل نشده تو خود orchardcmsهست.
> از قسمت culture بزاری فارسی تنظیم میشه

شما استفاده کردی؟ میشه برای کور ایتفاده کرد>؟

**Comment by aghili371** [comment]
@sebastienros  @DaRosenberg @khoshroomahdi 
it's easy to implement? i need Persian calendar and if it easy i will do that, unfortunately, I'm not familiar with the orchard core coding.

**Comment by sebastienros** [comment]
It might be trivial because we already have this in O1 and it should do the same thing. The only non-trivial thing that was done is the parsing of dates that was completely custom in O1, but you could start with the dotnet core implementation if you know that it works for you.
You would also add a calendar setting (like we added a TimeZone setting).

Technically just reproduce what this PR did:
https://github.com/OrchardCMS/Orchard/commit/a306759748b09e0ba07bb8b729073daddcd28687

You should look at these:
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Localization/Services/ICalendarSelector.cs
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Localization/Services/SiteCalendarSelector.cs
https://github.com/OrchardCMS/Orchard/blob/5b5eda6ae36dc2d7906599882165ef1e985cdc8c/src/Orchard/Localization/Services/DefaultCalendarManager.cs

Then change the DateTime shape to use this calendar.

All in all, could take a couple hours if you are familiar with Orchard.
