### ISSUE TITLE
Liquid Style Tag Not Resolving in Liquid Part inside Widget

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#3198]
Here is my liquid style code:

```
{% style src: "/folder/file.css" %}
```

This same snippet will resolve in Layout.liquid but will not resolve in a Liquid Part (in this case set up as a Widget but might have same issue even as a normal content - did not test that). The equivalent "script" snippet DOES work:

```
{% script src:"/folder/file.js", at:"Foot" %}
```

I do not think it is by design to not support style injection inside of a liquid part.

**Comment by jtkech** [comment]
Just tried the following which works. Also tried by using paths starting with `~/`, which is recommanded so that it also works if under a virtual folder. Where does your css file reside?

![resources](https://user-images.githubusercontent.com/8586360/52906788-2b809700-3254-11e9-8497-ce3cc889e2e1.png)

**Comment by jeffolmstead** [comment]
Well you have inspired me. I tested it on another one of my tenants on the same code base and it works there, in a liquid part in a widget. Same exact line of code. Something about this particular instance must be different and I will need to figure it out. It is odd that the script tag works but not the style tag. Thanks for checking on your end, I will close this out and only update if I can fined a pattern as to why it is happening.

**Comment by jeffolmstead** [comment]
@jtkech I have had time to attach a debugger and there still seems to be an issue here. Right now, all of the styles are rendered in OrchardCore.ResourceManagement.TagHelpers.StyleTagHelper BEFORE OrchardCore.ResourceManagement.TagHelpers.ResourceTagHelper Process method is called and thus they are all rendered EXCEPT this particular CSS hits the StyleTagHelper after the ResourceTagHelper has already Processed and rendered the Stylesheets, therefore this particular stylesheet goes unrendered. Do you know what calls the ResourceTagHelper Process method?

**Comment by jeffolmstead** [comment]
In my Layout.liquid file, if I move this

```
{% resources type: "Stylesheet" %}
``` 
down to the bottom of the file then all the stylesheets are included (down in the footer area). Of course, this is not idea as they should be up in the head area. I feel like there is some weird timing issue on this particular tenant.

**Comment by jeffolmstead** [comment]
@jtkech out of curiosity, I see you are using a "liquid page". Have you tried with a widget? I am wondering if it has something to do with that.

**Comment by jtkech** [comment]
Oh sorry, i thought you was talking about a liquid page.

With a liquid widget it's another story. Yes, this is the resources tag helper which renders (at the place you put it) the related entries that have been enlisted.

To understand what happens, take a look in `ThemeLayout.cs`

    public class ThemeLayout : Razor.RazorPage<dynamic>
    {
        public override async Task ExecuteAsync()
        {
            // The View's body is rendered 
            var body = RenderLayoutBody();

            // Then is added to the Content zone of the Layout shape
            ThemeLayout.Content.Add(body);

            // Finally we render the Shape's HTML to the page's output
            Write(await DisplayAsync(ThemeLayout));
        }
    }

So, only the **body is pre-executed** and added to the layout `Content` zone to be rendered later, but it may have registered some resources that will be rendered when the layout is rendered.

The **body** is related e.g to your content item with all its parts and fields. Any other thing is executed and rendered when the layout renders the zone it belongs, so after the resources tag helper for styles.

That's why it was not working with the style tag, and it was working with the script tag (at foot) because the related resources tag helper is executed at the end of the layout.

So, to be able to inject a style with a widget, the widget needs to belong to the **body**. E.g by adding the flow part to a content type so that you can add a liquid widget, but here it's per content item.

**Comment by jeffolmstead** [comment]
It makes perfect sense as to what is happening, though I don't know that it will not continue to trip people up who use layers to hold their widget. Obviously, layers are less critical since we can do so much more on a page now, but still, they are used. Getting users to remember they cannot inject CSS inside their widget might be a cause of a lot of future questions. I wish we could just delay the rendering of the Stylesheet resource but with Liquid I don't think that is feasible. 

How about a different approach, is it possible to pre-render the zones in my Layout.liquid? Can I just capture them as a variable right at the beginning and then later display them as "raw" html? This way I can have all content pre-rendered before it hits any of these resource tags. Might that be a good design pattern or do you see flaws in that?

**Comment by jtkech** [comment]
@jeffolmstead very good idea.

So, in razor it works by doing this in the layout.

    @{ 
        var htmlContent = await RenderBodyAsync();
    }
    ...
    ...
        @htmlContent

Then, thinking it is not yet possible in liquid, i looked for a more global solution which also works.

    public class ThemeLayout : Razor.RazorPage<dynamic>
    {
        public override async Task ExecuteAsync()
        {
            // The View's body is rendered 
            var body = RenderLayoutBody();

            // Then is added to the Content zone of the Layout shape
            ThemeLayout.Content.Add(body);

            var htmlContent = await DisplayAsync(ThemeLayout.Content);

            var content = ((Shape)ThemeLayout.Content);

            foreach (var item in content.Items.ToArray())
            {
                content.Remove(((IShape)item).Metadata.Name);
            }

            content.Add(htmlContent);

            // Finally we render the Shape's HTML to the page's output
            Write(await DisplayAsync(ThemeLayout));
        }
    }

But in fact it is already possible in liquid.

    {% assign htmlContent = Model.Content | shape_stringify %}
    ...
    ...
        {{ htmlContent }}

**Comment by jeffolmstead** [comment]
@jtkech that worked out great doing it in liquid:

```
{% assign featuredContent = Model.Featured | shape_stringify %}
...
{{ featuredContent }}
```

So we have a solid workaround for anyone who is needing it - bonus! Now I am just wondering if this is actually the best design pattern that I will do on all my layouts or whether there is a more global solution (as you were working on in your razor example). I actually like prerendering the "zones" as then I can check if they are empty and apply different conditions based on that so I am inclined to say simple is best and leave this as a workaround. What do you think, should I close this issue or keep it open?

**Comment by jtkech** [comment]
Note : Do you know that when using theming, somewhere the same `ThemeLayout` is executed for both razor and liquid. A liquid view is executed through a `LiquidPage` used as a precompiled razor view.

Note: We can't pre-execute `DocumentZone` which are rendered through `{% render_section %}`.

So, for a "global" solution (razor & liquid) we would need something like this.

    public class ThemeLayout : Razor.RazorPage<dynamic>
    {
        public override async Task ExecuteAsync()
        {
            // The View's body is rendered 
            var body = RenderLayoutBody();

            // Then is added to the Content zone of the Layout shape
            ThemeLayout.Content.Add(body);

            if (ThemeLayout is Shape layout)
            {
                foreach (var kv in layout.Properties.ToArray())
                {
                    if (kv.Value is IShape shape && shape.Metadata.Type != "DocumentZone")
                    {
                        ThemeLayout[kv.Key] = await DisplayAsync(kv.Value);
                    }
                }
            }

            // Finally we render the Shape's HTML to the page's output
            Write(await DisplayAsync(ThemeLayout));
        }
    }

But not sure it would work in all scenarios, with a new custom type of zone, and not sure it is good to pre-execute all zones e.g if at the end the layout will not render a given zone because of a condition we are not aware of. Hmm, my 1st feeling is that we can let it as it is and close the issue, but maybe we need more thinkings, so it is as you want ;)

**Comment by jeffolmstead** [comment]
Why do you say we can't pre-execute "DocumentZone"? The example I provided was the replacing of a "{% render_section..." - here is the what I fully replaced:

```
{% render_section "Featured", required: false %}
```

was replaced with this:

```
{% assign featuredContent = Model.Featured | shape_stringify %}
{{ featuredContent }}
```

And it worked fine. So I do believe all scenarios can be covered by the end user in their Layout.liquid. I am leaning towards NOT having it made universal at this time, the user can accomplish all of this without custom code and thus are in control. Thanks again for all your help on working through this!

**Comment by jtkech** [comment]
> Why do you say we can't pre-execute "DocumentZone"?

Yes, you are right. I was just saying that it would break existing views that still use `{% render_section ...`. I tried it, the `render_section` tag fails to render a pre-executed zone, but i think it would be easy to fix.

**Comment by jeffolmstead** [comment]
Oh, I see what you mean, if run through the Razor method it wouldn't work. I am inclined to let it stand as is unless it starts becoming problematic for future users. I actually like the linear progression (once it is understood that is what it is and not some black box of magic) that evaluation of content occurs vertically down the page. With this discussion here users can at least still resolve any Widget hindrances by pre-rendering their zones. Only thing that might be worthwhile is somehow getting this on ReadTheDocs.
