### ISSUE TITLE
Manipulating roles to elevate your permissions

### ISSUE THREAD

**Issue by JoshuaDouce** [OrchardCMS/OrchardCore#3216]
Not sure if this is intended and could not find any similar open issues. 

The scenario is as follows-
1. Create a role in Orchard for managing roles that can assign roles, create roles and manage users. 
2. Assign the role to a user
3. Log in as that user
4. Create a new role with all permissions then assign to yourself, effectively making yourself a superuser or just assign yourself the admin role

Should this be possible or should the ability to assign a role to a user be restricted by what permissions the user has access to?

**Comment by sebastienros** [comment]
This is a bug. Role management should only be accessible to site owners. Or assignable roles from the currently owned ones.

**Comment by sebastienros** [comment]
After looking at it, the ManageRoles permission is a `Security Sensitive` permission (https://github.com/OrchardCMS/OrchardCore/issues/2177), which means giving it to a user is equivalent to giving them Admin access (elevation). It's by design, so you should not give this permission to any user.

I would keep this issue though such that we can improve the system and create dynamic permissions to allow a user to set specific roles. For instance, one might be allowed to promote other users as 'Editor' only, like a community manager would do.

**Comment by SpencerWaz** [comment]
We could create an IPermissionProvider in the roles module, using the IRoleService, that returns dynamic  "Assign Role X" permission. In the same way were providing dynamic permissions for custom settings. We would have to determine the defaults for the built in roles

**Comment by sebastienros** [comment]
> we can improve the system and create dynamic permissions to allow a user to set specific roles

**Comment by Piedone** [comment]
Additionally, there could be a mechanism to only allow you to grant permissions that you yourself have. Something just for the future though.

**Comment by sebastienros** [comment]
@Piedone agreed, as I assume this is what we do in O1

**Comment by Piedone** [comment]
Not, unfortunately. I've created a feature like this for a client once, it's not as straightforward as it seems though.
