### ISSUE TITLE
Lucene enhancements

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3226]
* Drafts in indexes (already in O1)
* Specific content types in indexes (already in O1).
   - Add the ability to select in which index the content type will be stored in the content type settings.
   - Add an abstraction on which indexing provider will be used.
* Custom analyzer per index
   - Lucene has already a list of Analyzer "examples", we should be able to select which one we want to use per Index.
   - Analyzers should allow to sort results with "diacritics" properly depending on the culture.
* We should be able to have results filtered by culture. Either per " Lucene Analyzer" (different indexes) or by indexing the culture of the content item for filtering in the same index. Though, it would be more optimal to have a separate analyzer / index per culture since cultures requires different Analyzer options/settings.
* Improved elastic search DSL coverage
* Support "sorting" in Lucene with diacritics
* Implement Tokenized and Sanitized

**Comment by cwojke** [comment]
I would add that some of that like "specific content types in indexes" should be part of Indexing module, not Lucen itsefl.

**Comment by Skrypt** [comment]
Not sure what you mean all content type created from OC admin is indexed.

**Comment by cwojke** [comment]
Yesterday I noticed that you have to enable Lucene module in order to get "Include this element index" to appear in Field Definition... I think this should not be Lucene specific same as settings If you want to index drafts or what content types should be included/excluced from indexes. 

And why am I talking about it is because what If you don't want to use Lucene for indexing? Some time ago I wrote Elasticsearch index provider as a module because it played nice with some frontend library for filtering.

**Comment by hishamco** [comment]
@Skrypt why this is localization related?

**Comment by Skrypt** [comment]
Lucene requires different settings from a language to an other. For example french needs to support diacritics.

**Comment by hishamco** [comment]
I see ..  thanks

**Comment by hishamco** [comment]
@Skrypt please let me know if you need help in here, especially in localization :)
