### ISSUE TITLE
Need A Live Theme Builder

### ISSUE THREAD

**Issue by CodeHighlights** [OrchardCMS/OrchardCore#3279]
With wordpress, we have Elementor which allows people to edit their pages AND themes, live. Are there any plans to build something like this for Orchard Core CMS? If not, would it be possible to for someone to build this as a plugin/module or would there need to be changes in the CMS to allow such a module to do this?

**Comment by pgy866** [comment]
If there is such a module, you can directly create a template theme in the ORCHARD CORE framework, or update the template resources in the template DLL (such as CSS, JS), how wonderful, we can directly do not need any third-party software, directly in ORCHARD CORE Build and update template themes within the framework

**Comment by nigel-dewar** [comment]
@CodeHighlights , I know what you are thinking, and I thought the same thing. I'm thinking it would need to be built. Bit of work, but would certainly be awesome.

After watching my wife build her WIX website, I see drag and drop builders as the way of the future for general folk. It just makes it so easy. Its hard for developers to think this way especially if they been coding for a decade or 2. As for me, Im new to development, so I see things like Elementor and say "hey this is awesome"! and "I want this".

I rekon Orchard Core has potential far beyond Wordpress of course, hence the reason Im so interested in it. The trick will be making it awesome not just for developers, but for folk who know nothing about web dev and just want to put together a great looking site.

I think with the arrival of CSS GRID, and a few other things, it shouldn't be too hard to build out something like Elementor for Orchard now. Because YesSQL is so flexible, the entire GRID schema and all its config can be stored quite easily. I don't know enough about liquid and 'shapes and widgets' at this stage to comment, but I'm thinking about how these components can be drag and droppable in a page designer. 

Essentially you want a person with ZERO websmarts to be able to put together not only a great looking website, but also something that is truly functional as well. Being able to select from a catalog of pre-built web-components, webparts, widgets, apps "or whatever you want to call them", plonk em on a page where they want and configure them easily to do what they want them to do.

**Comment by Piedone** [comment]
This would perhaps work for you: https://github.com/Lombiq/Hosting-Media-Theme/

**Comment by hishamco** [comment]
Have a look to https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.Html/README.md

**Comment by Piedone** [comment]
Is there a use case that you envision and aren't covered by the above two projects?
