### ISSUE TITLE
Azure Premium Windows Container App Service persistent storage

### ISSUE THREAD

**Issue by VitoDeCarlo** [OrchardCMS/OrchardCore#3381]
I'm new at containers, so I'm not sure if I'm missing something, but I cannot seem to find a way to persist the App_Data in the container host.  Every time I change deployment slots or cause the image to be rewritten, my site reverts back to the setup window.  I'm pointing the image to, during setup of the App Service, to the orchardproject/orchardcore-cms-windows:dev repository.

I'm using the new Azure SKU "PC2", so I'm not sure if things have changed with this container service, compared to the older Windows Container architecture.  I've tried setting WEBSITES_ENABLE_APP_SERVICE_STORAGE = true, and ORCHARD_APP_DATA = /home, but that just causes the container to fail to load.

Is there a process I should follow to setup persisted storage within the host?  I have even tried attaching a file share, but I cannot seem to get that working either.

Here's a link to the info on the PC2 sku…
https://azure.microsoft.com/en-us/blog/announcing-the-public-preview-of-windows-container-support-in-azure-app-service/

**Comment by VitoDeCarlo** [comment]
I just wanted to add to this, that I did also try to setup one of the Linux App Services, based on the P1V2 service plan, which uses containers.  The result was the same.  Using the application variables WEBSITES_ENABLE_APP_SERVICE_STORAGE=true and ORCHARD_APP_DATA = /home, I was able to verify that all of the application data was being stored in the D:\Home directory.  However, once I setup another "slot" for staging, and mirrored it from the original slot, so that they had the same variables, the result was that once I swapped the slots, the D:\Home folder was swapped out as well.  Thankfully, if I swapped the two slots again to bring back the original slot, all of my data returned.

Knowing as little as I do about the use of containers within Azure, I cannot tell if this is a bug with Microsoft's App Services, or if this is a bug with the Orchard Core CMS (or its documentation).  I guess I'm looking for someone a little more experienced to inform me as to where in fact the issue lies.  It may be an issue with me and my understanding, for all I know.  :)

Thanks up front, for any help anyone can give me on this.

**Comment by sebastienros** [comment]
The `WEBSITES_ENABLE_APP_SERVICE_STORAGE` option is to direct App Service to share the `/home` storage across instances if you scale out. This way any change in the filesystem will be applied to other instances.

The `ORCHARD_APP_DATA` property is for Orchard to know where to put the files it creates dynamically, like the sqlite database, or media files that are uploaded. If you don't set this value then the local files would be lost every time the docker container is restarted. 

By setting both value you ensure that Orchard's state is shared across instances, and no volatile.

There are ways to have OC be stateless with regards to the local file system by:
- using a server database like SQL Server or PostgresQL instead of sqlite
- using Azure blob storage for storing media
- using the database to store content types

If all these features are used then you could omit `WEBSITES_ENABLE_APP_SERVICE_STORAGE` and also not set `ORCHARD_APP_DATA` as the state would be shared through a different way than the file system.

Now the fact that `home` is not shared across slots might be an issue for you, then the same solution applies, to extract the states you want to be shared across slots outside of the file system. Unless there is a path in App Service that is shared across slots, in which case you can use it for the `ORCHARD_APP_DATA` value.

**Comment by VitoDeCarlo** [comment]
I'm not sure if you've tried either of those App Service skus (one for Windows and the other for Linux).  I've tested (multiple times) setting both of those Application Settings.  I've also confirmed that Orchard is in fact placing its files into the /home path.  However, even though that folder *should* be stored on the underlying host system, it is in fact still attached to the slot.  If I swap slots, I lose my data, but then swapping brings it back.  Also, I have tried just changing configuration that would cause the image to reset in some way, and I lose the data in those instances as well.  I wish I could remember exactly what I did, but I honestly spent about a dozen hours trying everything I could think of, reading everything I could find.  I tried attaching Blob storage... I tried attaching File Storage (with mounted folders).  I just couldn't find a way to have the application data persist.  Maybe it's a bug on Microsoft's side, and I have opened a ticket with them.  But it's been a couple of days and they haven't shed any light on this issue.

So for now, I guess I'm just stuck at running a single container - which is fine for now.

Thank you,
Vito DeCarlo

**Comment by sebastienros** [comment]
Is it documented anywhere that slots are sharing the home folder?

**Comment by VitoDeCarlo** [comment]
I guess they have a bug in the new Windows containers (sku PC2).  Although I've told them that their Linux App Service containers (sku P1V2) were not working for me either.  I'm leaving it as a single container for now, until I can find out what my options are.  Until then, I'll just backup the /home folder myself.  I'm currently using SQL Server for data, so it's just a matter of backing up the config files, and the media files, I think.

**Comment by sebastienros** [comment]
Yes, and send me your site when it's online ;)

**Comment by VitoDeCarlo** [comment]
Absolutely.  I really want to contribute to this project, in one way or another.  Unfortunately, I'm temporarily at one of the toughest times in recent memory.  I think my house is going to sell within the next week or two, so that will certainly help ease some stress.  But as soon as I can break free from everything I have going on, I seriously want to help out.  I've been a fan of Orchard CMS since it's first prerelease.  So I'll certainly let you know as soon as they're up.

The domains are thepulse.com, thepulse.net, and my personal blog vitodecarlo.com.  I'm just starting to get the hang of it again, as it's been a long time since I've used it.  But I should have something within a week.

**Comment by VitoDeCarlo** [comment]
Years ago, I had one of my application development teams use Orchard to manage content on our large e-commerce site.  (It handled more than $50 million in sales per year.)  I think we used it for a couple of years before we replaced it.
