### ISSUE TITLE
What steps in migrating from Orchard 1 to Orchard 2 

### ISSUE THREAD

**Issue by weedkiller** [OrchardCMS/OrchardCore#342]
What steps in migrating from Orchard 1 to Orchard 2 and modules

**Comment by sebastienros** [comment]
Right now the idea is that there won't be any migration plan, because features will have different names, themes will use different html, layouts might use a different storage.

But it's not impossible that we can create some heavily customized code to convert most used data formats  to O2, like BodyPart, title, autoroute, tags, ... That might help. It's also possible that people will work on migration projects to port this data based on their specific usage.

**Comment by agriffard** [comment]
https://github.com/OrchardCMS/Orchard/issues/7450

**Comment by Piedone** [comment]
See this article: https://orcharddojo.net/blog/how-to-migrate-an-orchard-1-application-to-orchard-core. This is now a pretty well walked path. Do you think there's anything else necessary?
