### ISSUE TITLE
Admin menu collapses on some pages

### ISSUE THREAD

**Issue by Wej1971** [OrchardCMS/OrchardCore#3431]
Minor issue, but it appears that the Admin menu only stays open when accessing index pages - any edit pages cause the menu to reset.

**Comment by sebastienros** [comment]
Can you provide a gif of what you mean?

**Comment by Skrypt** [comment]
He means that if he uses the Admin Menu module sometimes it doesn't find on which page you are and it doesn't highlight/select the proper menu item. That's related to the method that evaluates the menu items url's against the currently displayed page. It's a quick fix, I think.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Navigation.Core/NavigationHelper.cs#L97

I replaced this line with this locally and forgot to push it.

url = menuItem.Href.Remove(0, viewContext.HttpContext.Request.PathBase.Value.Length);

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/64005122-49538080-cb42-11e9-9c96-69806737e360.png)
@Skrypt The above method does not solve the problem

**Comment by Skrypt** [comment]
Missing the tenant prefix

**Comment by jtkech** [comment]
Didn't try it yet, so not related to the issue yet, but after a quick look.

So because we are removing the pathBase from the item url (when it doesn't start with `~/`)

    url = menuItem.Href.Replace(viewContext.HttpContext.Request.PathBase, "");

At least, when the url starts with `~/`, this line is wrong

    url = url.Replace("~/", viewContext.HttpContext.Request.PathBase);

I would just use

    url = url.Substring(1);


Or use this without the slash

    url = url.Replace("~", viewContext.HttpContext.Request.PathBase);

And then without the `else` so that the pathBase is removed afterwards, but the 1st way is better ;)

**Comment by Skrypt** [comment]
I can remember doing something with the Substring once.

**Comment by jtkech** [comment]
In `NavigationManager` the `~/` is already checked, so the line i mentioned above is wrong but never executed. Then, in `NavigationManager`, if it starts with `~/` the url is prefixed with the tenant prefix which is wrong because in any case just after we do the same with pathBase that contains the tenant prefix.

I tried to use `~/Admin/Contents/ContentItems/` as a menu item node, it doesn't work in a prefixed tenant, we ends up with an url that contains the tenant prefix twice.

**I will do a PR for these 2 little tweaks**.

Then, for this "issue" it is just because there is no menuitem href that match the current path while editing an item. What we can do is to check if the path **starts** with a given menu item href so that when editing an item because `/Admin/Contents/ContentItems/contentItemId` starts with `/Admin/Contents/ContentItems/`, the admin menu item will be still selected.

But if the menuitem href would have been e.g `/Admin/Contents/ContentItems/List` this would not work. Idem when going to edit the same item but from another menu item in another place in the menu tree, e.g under `Content => Content Types => Article`.

**I will do this little update in the PR**, so that at least if we go to the regular content items index page and then editing an item, the menu item in the left menu will be still selected.

**Comment by chinasqzl** [comment]
Do you want to edit the route to override the list in order to expand properly?
/Admin/Contents/ContentItems/Article
  /Admin/Contents/ContentItems/{id}/Edit -> /Admin/Contents/ContentItems/Article/{id}/Edit

![image](https://user-images.githubusercontent.com/16968103/64090025-9d957500-cd7b-11e9-9234-8bf9effe9381.png)
