### ISSUE TITLE
Custom module breaks published site

### ISSUE THREAD

**Issue by idontbyte** [OrchardCMS/OrchardCore#3432]
Adding a custom razorsdk based module causes an error on my CMS once deployed to Azure:

```
2019-04-03 23:00:41.8326|Default|80000056-0000-e900-b63f-84710c7967bb||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.AspNet.WebApi.Client'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at OrchardCore.Mvc.ShellFeatureApplicationPart.<>c.<GetReferencePaths>b__10_0(CompilationLibrary library) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Mvc.Core\ShellFeatureApplicationPart.cs:line 92
```

This can be resolved by adding the following to the CMS Project:
`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`

This will need to be added to documentation or resolved.

**Comment by Skrypt** [comment]
Happened to me 3 weeks ago. My main app project had a Razor view that needed to be compiled on runtime which required the ref assemblies to be part of the published solution. The only trade off of including ref assemblies is that you won't get .NET Core patches applied since Azure updates it's runtime assemblies when needed.

In the OC repo every views are precompiled so there is no need normally to reference assemblies in your published solution and you should never require to do so. Please, look if there is a Razor view in your /Views folder of your main application project after it's published. If there is one then try set it to precompile instead.

**Comment by sebastienros** [comment]
Can you ensure that your project looks like this:

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Module/OrchardCore.Templates.Cms.Module.csproj

**Comment by idontbyte** [comment]
> In the OC repo every views are precompiled so there is no need normally to reference assemblies in your published solution and you should never require to do so. Please, look if there is a Razor view in your /Views folder of your main application project after it's published. If there is one then try set it to precompile instead.

Checked my published site folder, no Views, all pre-compiled.
My project:

`<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.2" />
    <PackageReference Include="OrchardCore.Admin" Version="1.0.0-beta3-71073" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-beta3-71073" />
  </ItemGroup>

</Project>
`
