### ISSUE TITLE
Decoupled CMS routing issue using Razor Pages 

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3449]
I am trying to create a custom module (ForumModule) with a Host with Decoupled CMS.

This is my Host system startup.cs

```
  public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services
            .AddOrchardCms()
            .AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseOrchardCore();
        }
    }
```

and this is the Startup at my ForumModule

```

    public class Startup : StartupBase
    {
        public override void ConfigureServices(IServiceCollection services)
        {
        }

        public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
        }
    }
```

This is the layout of the project

![module-1](https://user-images.githubusercontent.com/1761249/55730674-040aa700-5a19-11e9-9943-761a159a76a2.png)

The problem is that neither `/ForumModule/` nor `/ForumModule/About` nor `/ForumModule/Contact` works.

However `/About` and `/Contact` works! This is surprising and I wonder if it's supposed to be that way. Because if I just use `services.AddOrchardCore` instead of `add.AddOrchardCms()`, [the reverse situation happens](https://github.com/dodyg/practical-aspnetcore/tree/master/projects/orchard-core/routing-3).

`Contact.cshtml` is just consisted of this code so there is no overriding the path at the page level.
```
@page

<h1>Contact from Forum Module</h1>
```

![module-2](https://user-images.githubusercontent.com/1761249/55730682-0836c480-5a19-11e9-8a5a-b897f40d1c93.png)

The whole project is here https://github.com/dodyg/practical-aspnetcore/tree/master/projects/orchard-core/cms

**Comment by psijkof** [comment]
Hi, I did a Razor Pages sample a while ago. You might want to have a look:
[`Orchard Core with Razor Pages decoupled`](https://github.com/psijkof/ModernBusiness.OC.RazorPages)

**Comment by hishamco** [comment]
@jtkech is this related to #2549?

**Comment by jtkech** [comment]
@hishamco hmm, yes because around razor pages, but #2549 is more related to home pages and **razor page layouts** discovering. Normally  these issues have been fixed and there is a testing project `OC.Application.Pages` in our solution.

About this issue, `AddOrchardCms` call itself our `AddMvc` which is applied at the tenant level, then it returns the host level service collection. So, applying `AddMvc` on `AddOrchardCms`, as it is done here, re-add all mvc services at the host level.

So, @dodyg try to just remove the `AddMvc()` that you apply on `AddOrchardCms`.

**Comment by hishamco** [comment]
If they have been fixed .. we need to close them 😊

**Comment by dodyg** [comment]
It doesn't work.

With `AddMvc()`

![with-add-mvc](https://user-images.githubusercontent.com/1761249/56224538-0ea7ea80-6070-11e9-99cf-16e23a4a242c.png)

Without `AddMvc()`

![with-no-mvc](https://user-images.githubusercontent.com/1761249/56224552-136c9e80-6070-11e9-8dc6-7d16c10d7e42.png)

**Comment by jtkech** [comment]
@dodyg okay.

Just saw the link to your repo, i can't right now but i will try it this night directly from your repo.

**Comment by jtkech** [comment]
@dodyg

Just tried your project under the `C:\Sources\practical-aspnetcore\projects\orchard-core\routing-3\Host` folder of your repo, all was working fine.

When your app reference `OC.Application.Mvc.Targets`, as it is in your repo, it means that you don't use the full cms and it is not intended that you use `AddOrchardCms()`. In this case you have to rather use `AddOrchardCore()` and then `AddMvc()` on it, as it is done in your repo. So, i first tried your `Host` application as it is and all was working.

Then, in your app i referenced `OC.Application.Cms.Targets` and just used `AddOrchardCms()` without `AddMvc()` because it is called by `AddOrchardCms()`.

- I also created a wwroot folder with a placeholder file so that Image Sharp doesn't fail.

- Then, i add to run a setup where i selected the SaaS recipe.

- Then, i add to login and go to the admin.

- Then, **i had to enable** the `Forum` and the `Ticket` modules.

- Then, all links were working fine.

**Comment by dodyg** [comment]
Hi @jtkech,

Thank you for taking a look at this case. Unfortunately you checked on the wrong code. The code I was referring to is https://github.com/dodyg/practical-aspnetcore/tree/master/projects/orchard-core/cms

![actual](https://user-images.githubusercontent.com/1761249/56267393-ff1bb680-60ee-11e9-8f4a-51df441bd34e.png)


The [Host project](https://github.com/dodyg/practical-aspnetcore/blob/master/projects/orchard-core/cms/Host/Host.csproj) already uses the CMS target to
```
    <ItemGroup>
        <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-beta3-71077" />
        <PackageReference Include="OrchardCore.Application.Targets" Version="1.0.0-beta3-71077" />
        <PackageReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
```

And the [Forum project](https://github.com/dodyg/practical-aspnetcore/blob/master/projects/orchard-core/cms/ForumModule/ForumModule.csproj) uses 

```
 <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-beta3-71077" />
    <PackageReference Include="OrchardCore.Mvc.Core" Version="1.0.0-beta3-71077" />
  </ItemGroup>
```

**Comment by jtkech** [comment]
@dodyg okay no problem, just tried this project.

- I removed the `OC.Application.Targets` reference, you don't need it if you reference `OC.Application.Cms.Targets`.

- Then i removed `AddMvc()`, just kept `AddOrchardCms()`.

- The `ForumModule` manifest file was missing so i copy pasted a `Manifest.cs`.

- Then, i followed the same step as above, run the setup where i selected the blank site recipe, go to the admin and **enable the `ForumModule`** and so on.

- **Then all links with the module name work as expected**. To make working routes without the module name you would have to use razor pages route helpers, as we do in our demo module.

- In your `_ViewStart` you can just use `Layout = "_Layout";` then the layout is naturaly found in the views shared folder, the layout can also be put in the `Pages/Shared` folder, then the `_ViewImports.cshtml` and the `_ViewStart.cshtml` can be put under the `Pages` folder.

- Finally, i removed the `Watch Include` in your project file, and i was still able to update the views in live while in debug mode.

**Comment by dodyg** [comment]
Oh it seems that I missed a lot of steps. Awesome. It works now. Thank you!

**Comment by sallenkov** [comment]
Hi,
can you write the solution and the main steps to get it working

**Comment by dodyg** [comment]
@sallenkov  https://orchardcore.readthedocs.io/en/dev/docs/guides/decoupled-cms/
