### ISSUE TITLE
Site/Tenant startup fails when project has no wwwroot folder

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3459]
Relatively minor issue, but if you follow the guide to create a CMS Web Application with Nuget (Beta3), with an empty web project, and create a Saas site, then create a tenant, the tenant startup fails if you don't have a wwwroot in the mvc project.
![oc-tenant](https://user-images.githubusercontent.com/13782679/56020675-918f1500-5cff-11e9-8025-a8ec58298b9e.PNG)

The error is from ImageSharp, and if you follow the instructions and create a wwwroot folder everything works fine.

Actually just checked, it happens when you create a blog recipe on main tenant as well (rather than a Sass recpipe)

Should we be providing ImageSharp the App_Data folder for it's cache so that cache's are separated tenant by tenant?

Or update the guide to say create a wwwroot folder?

**Comment by Skrypt** [comment]
This folder should be automatically created simply.

**Comment by deanmarcussen** [comment]
@Skrypt Yes, ImageSharp takes the env.WebRootFileProvider for it's PhysicalFileSystemCache. We could swap that out for something that uses the OC File Providers. It could handle restricting the cache size that you were after as well

**Comment by Skrypt** [comment]
Makes sense to me to have a different cache folder for each tenant. Does ImageSharp has the extensibility point for that already though?

**Comment by deanmarcussen** [comment]
ImageSharp doesn't have a point specifically for cache location.
But it does have an extensibility point for swapping the cache implementation - which is trivial. 

I just had a look through my is-cache folder. Not exactly user friendly! 
So maybe not the best to expose it in the Media Folder - although it would provide an entry point for someone wanting to clear the cache.

`/App_Data/Site/sitename/is-cache` as a local folder independent from Blob Storage sounds good.

**Comment by Skrypt** [comment]
You mean this : 
https://docs.sixlabors.com/api/ImageSharp.Web/SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.html

**Comment by Skrypt** [comment]
If I'm looking at his issue there : 
https://github.com/SixLabors/ImageSharp/issues/216
Swapping the image cache implementation will be available only when this PR will be merged.
https://github.com/SixLabors/ImageSharp.Web/issues/5

**Comment by deanmarcussen** [comment]
@Skrypt I had a play with swapping `PhysicalFileSystemCache` out.

It swaps out with no problems.

Have you had a look at your is-cache folder size and contents? 

I didn't realise this, but discovered that even if the media is not resized, if it passes through the IS pipeline, IS moves it into is-cache folder. 

Will wait for #3200 to come in before going too much further.

**Comment by Skrypt** [comment]
I need to try this locally to see if all my images are appended to my is-cache folder. So far, what I've seen is that I had only my resized images. Can you look if there's not some image files that you are trying to resize into a non allowed size ; that would maybe explain why it appends the full sized image in your is-cache folder since it can't resize it to the size you would set it.

**Comment by deanmarcussen** [comment]
I just tried this locally with a modified Agency theme - took out all the image resizing from the main template and deleted the is-cache folder. In that case it didn't try and resize them.

Tried again with my other site which uses the razor tag helper (and no resizing) and the unresized media all passed through the image resizer and ended up in the is-cache folder.

So going to have to debug that later and see what the differences are between using the fluid helper, and the razor helper. Or if it's just some weirdness I've introduced on the razor site.

Yes the naming is difficult to follow - I only noticed it initially because windows was showing thumbnails, and I was pretty sure that the images on my homepage should probably be resized as one of them is way bigger than it needs to be, but I didn't think I'd ever got around to including that in the template.

From reading the IS code it looks like it uses a hash of the url path (presumably including query string) as it's cache key, and then splits them down into the a/b/d/e/x/etc.

I've seen the rebuild of the cache occur when I deploy - I wrote a sitewarmer that ships the contents of the website of to an azure function every time I deploy, and then the azure function parses each page for media tags and hits them, to force them into the cache. But with a cdn in front of it that probably becomes unnecessary, as once they're in the cdn, they're there forever, or until it's purged.

**Comment by Skrypt** [comment]
I stopped re-downloading my is-cache folder yesterday. Through FTP it took around 6 hours and it was not finished. I had around 6 gb of files already and the media folder is around 8 gb. So, it's a bad sing that it must be adding original files in there too. Also found that my is-cache folder is making Visual Studio 2019 making a stack overflow exception because it tries to analyse each folders in that cache when I open the solution.

**Comment by deanmarcussen** [comment]
Ok, I checked again now with a modified agency theme.
Definitely all media being served is being moved to the is-cache folder (didn't clear my browser cache this morning, clearly too early).

It must be running through the IS processor as well because the file sizes are different - an unresized jpg - the mountain picture from the agency theme `about/4.jpg` - is 4902 bytes in it's source media folder and when it becomes `a204cf0a6ba1.jpg` in the is-cache folder has risen to 5437 bytes.

Think it's happening because anything in the MediaFileStore gets picked up on by IS and 'handled' by the IS middleware. So regular StaticFile serving never gets an opportunity to handle it, even if it doesn't need resizing. 
There might be something we could do about that to handle it earlier. Not sure.

Regardless the is-cache folder clearly can grow too large!

**Comment by Skrypt** [comment]
I'm getting a lot of logs on Azure with the MediaFileProvider. It's probably related.

```C#
2019-03-11 00:00:47.0798|Default|8000035c-0000-da00-b63f-84710c7967bb||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.ArgumentOutOfRangeException: The specified URL is not inside the URL scope of the file store.
Parameter name: publicUrl
   at OrchardCore.Media.Services.MediaFileStore.MapPublicUrlToPath(String publicUrl) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaFileStore.cs:line 89
   at OrchardCore.Media.Processing.MediaFileProvider.GetAsync(HttpContext context) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Processing\MediaFileProvider.cs:line 49
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)    at OrchardCore.Media.Services.MediaFileStore.MapPublicUrlToPath(String publicUrl) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaFileStore.cs:line 89
   at OrchardCore.Media.Processing.MediaFileProvider.GetAsync(HttpContext context) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Processing\MediaFileProvider.cs:line 49
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

**Comment by deanmarcussen** [comment]
Interesting. Are you still serving media locally? Not through blob storage?

The `E:\Repositories` path just refers to where Azure built the dll I think from memory. Is it building with kudo on Azure directly? Not with VSTS?

**Comment by Skrypt** [comment]
I'm publishing the app on my PC and deploying it to Azure with FTP. Old school way.

**Comment by deanmarcussen** [comment]
Proper old school!

Front the media with a cdn and clear your is-cache folder regularly?

**Comment by Skrypt** [comment]
Actually resizing images takes a lot of processing on Azure and it slows down page loading time. What I need is to bypass this cache and to store resized images on a CDN permanently and use that CDN natural cache simply.

**Comment by deanmarcussen** [comment]
#3468 is working for me. 

Once the cdn is parked in front of it and the pages have been hit once the is-cache folder can be deleted and it's not even created again - until new media is added. 

Email me if you want to chat infrastructure some more - this has gotten a bit off topic

**Comment by Skrypt** [comment]
True, I'm going to try your PR first.

**Comment by sebastienros** [comment]
We have a placeholder file in the package to ensure the folder is created. It should have worked.

**Comment by deanmarcussen** [comment]
Can repro at will.
The placeholder doesn't get created.
Lesson for me -> always test before a demo!

I looked - the only reference I can find to a placeholder file is your commit https://github.com/OrchardCMS/OrchardCore/commit/e230fdbc7af021f9999a93c350dbc5707f5170ab
which forces .placeholder in the OrchardCore.Cms.Web project, which doesn't have an impact when referencing OrchardCore.Application.Cms.Targets from an empty web project (not sure if the template has changed with VS 2019 or not - perhaps the dot net core template used to have a `wwwroot` in it.)

If I do create a wwwroot folder all works fine, but there is still no .placeholder file created in it.

Not sure where the .nuspec is but could we not just include a .placeholder in the contentfiles in the package?

**Comment by jtkech** [comment]
@deanmarcussen @sebastienros 

> We have a placeholder file in the package

There is no placeholder in the package, right now you need to create yourself a `wwwroot` folder under your application, as done in our `OC.Cms.Web` application, and with a placeholder so that when publishing a `wwwroot` folder is created.

We would need to create a custom msbuild script executed on publishing and that auto generate this placeholder and add it to the publish outputs.

**Comment by sebastienros** [comment]
Our template should have it then. And also I thought there was a better exception message when it's not here.

**Comment by deanmarcussen** [comment]
How about just putting a placeholder in the nuget package contentFiles?

**Comment by jtkech** [comment]
@sebastienros @deanmarcussen 

Need to be retried but as i remember now package content files are considered immutable, so they can be referenced but not copied under a project. Hmm, maybe just create the `wwwroot` folder at runtime.

I tried to create the folder (if WebRootPath == null) at runtime in the media startup, with a lock because tenants can be built concurently, seems to work. But i think here it is a host concern and would be better, in a new **`UseOrchardCms()`** helper, to init the `WebRootPath` if null and then the `WebRootFileProvider` which in this case has been setup to a `NullFileProvider`, as we do for the `ContentRootFileProvider` in our `UseOrchardCore()` helper to add our embedded file provider.

That said, in our cms app startup just did the following, then the host automatically create the folder, then it works. I think this is the right way because the folder is created early by the host itself which then 1st setup correctly its `WebRootFileProvider`. Do we need an helper just for this?

            WebHost.CreateDefaultBuilder<Startup>(args)
                .UseWebRoot("wwwroot")
                .UseNLogWeb();

**Comment by deanmarcussen** [comment]
@sebastienros @jtkech Nice `UseWebRoot()` looks sensible.
That fixes the template, but doesn't fix the `Use empty project` Guide, which was what I was following when I stumbled across this. I still think it's just a minor bad user experience when following our docs/guides, so the tweak to the documentation for people that are using the beta3 NuGet's seems worthwhile.

Going forward - Package content files are immutable, but a .placeholder file will never change, so it is immutable. I could look at that if I knew where the .nuspec file was generated!

However I still think we have a bigger question.

Should the `host` be holding tenant related is-cache files?
I think they should be held by the tenant, in the tenants App_Data folder.
This would allow us to offer fine-grained tenant control of the size of that folder / or number of items in it.

Having discovered that IS processes all images that are served by it's pipeline, not just resized images, and moves them into it's is-cache folder, I think having control of that folder becomes a tenant concern, not a host concern - or maybe it's a bit of both. host needs to be able to set limits for tenants, but tenants should be able to reduce that limit perhaps?

Given that we start IS.Middleware on a tenant by tenant basis, it seems the cache should be tenant by tenant. In addition with the CacheHash strategy currently in IS being based on the file path & query string, it is totally possible for collisions between tenant images when tenants are served without a tenant prefix.
consider for example
```
tenant1 uses the agency recipe on https://tenant1.com
tenant2 uses the agency recipe on https://tenant2.com

Both request media/about/4.jpg
```
Whoever requests it first gets it, so if tenant1 requests first, and tenant2 changes media/about/4.jpg IS CacheHash doesn't know this and always serves tenant1's version. (the key is based on path/querystring not an SHA256 hash of the actual file contents)

Propose we swap the IS default `PhysicalFileSystemCache.cs` for a `TenantPhysicalFileSystemCache.cs` and implement a `OrchardCore.Tenants.MediaCacheProvider` based on the `OrchardCore.Tenants.FileProvider` which we give to the `TenantPhysicalFileSystemCache.cs` instead of `env.WebRootFileProvider`

This would also solve creating the directory re: tenant setup race conditions (I think)

And I think removes any dependency on the host file system 

I've got about half this written, but would rather have general thoughts, and be aware of any other issues it might cause before putting a PR in

**Comment by jtkech** [comment]
@deanmarcussen 

>That fixes the template, but doesn't fix the Use empty project Guide.

Yes, we would need to update the doc to add `UseWebRoot("wwwroot")`, but not sure if this is what you meant. Anyway, not sure myself that this is the better fix (see below), only a 1st suggestion.

> Package content files are immutable, but a .placeholder file will never change.

You're right, what i just meant is that this file will not be physically injected in your project.

> Having discovered that IS processes all images that are served by it's pipeline, not just resized images.

I think i fixed it in my PR through the `MediaFileProvider.IsValidRequest()` that checks if there is at least one of the mandatory resizing parameters (width or height).

> Control of that folder becomes a tenant concern, not a host concern - or maybe it's a bit of both.

A tenant is a kind of an isolated app but not yet an isolated host. What i mean is that beyond ISharp an host component needs to be correctly initialized at the app level and then we can compose with it knowing that if a shared host component is mutated in a tenant context we need a lock.

 E.g we let the host initialize the `ContentRootFileProvider` then in `UseOrchardCore()` we can setup a composite still using this provider but also our `ModuleEmbeddedFileProvider`. Here it is still at the host level and just because the application has choosed to call `UseOrchardCore()`.

So, among ISharp, we still need a `WebRootFileProvider` correctly setup by the host and then we can compose with it. There are pending PRs which do this, e.g for the verisioning tag helper using the `WebRootFileProvider` on which we add our custom provider.

When there is no `wwwroot`, `WebRootPath` is null and the `WebRootFileProvider` is a null file provider. That why i thought about `UseWebRoot("wwwroot")`, otherwise if we create the `wwwroot` later at the app level, or in a tenant context with a lock, we need to also setup this file provider.

But as said above, not sure that my 1st suggestion to use `UseWebRoot("wwwroot")` is the better fix. When we let the host creating the `wwwroot` it doesn't put a placeholder, so when publishing no `wwwroot` will be outputed. So, in a published context it may be recreated and it may depend on access rights.

So, to do it ourself at runtime, at the app level we would need a `UseOrchardCms()` helper, or at the tenant level by the 1st tenant being built and with a lock, but i don't like it.

**So i think i will create a little msbuild task embedded in the cms package** to do it.

> Propose we swap the IS default PhysicalFileSystemCache.cs for a TenantPhysicalFileSystemCache.cs.

Otherwise, i agree with all your suggestions about ISharp. This one looks like a very good idea!

**Comment by deanmarcussen** [comment]
@jtkech thanks for the extensive reply

> Yes, we would need to update the doc to add `UseWebRoot("wwwroot")`, but not sure if this is what you meant. Anyway, not sure myself that this is the better fix (see below), only a 1st suggestion.

Yes that's what I meant - see #3459 - not to add `UseWebRoot("wwwroot")`, but just to add the  folder in VS - also not sure is the best approach.

> > Package content files are immutable, but a .placeholder file will never change.
> 
> You're right, what i just meant is that this file will not be physically injected in your project.

Thought that was the point of contentFiles? That NuGet would add them to your project. I can think of a couple of times where I've use it physically add them to the csproj file.

> > Having discovered that IS processes all images that are served by it's pipeline, not just resized images.
> 
> I think i fixed it in my PR through the `MediaFileProvider.IsValidRequest()` that checks if there is at least one of the mandatory resizing parameters (width or height).

Brilliant! @Skrypt Will be pleased too I imagine.

> > Control of that folder becomes a tenant concern, not a host concern - or maybe it's a bit of both.
> 

Also thanks, that helped me understand the tenant / host process a lot better.

> **So i think i will create a little msbuild task embedded in the cms package** to do it.

My only question here is does this force the WebRoot to `wwwroot` if we're forcing creation during an MSBuild Task. If user has decided to go off the standard and make their own `myspecialroot` do we break things by creating another `wwwroot` alongside it?

> Otherwise, i agree with all your suggestions about ISharp. This one looks like a very good idea!
Cheers it's coming along, should get some time on it in the next few days.

**Comment by jtkech** [comment]
@deanmarcussen 

> I thought that was the point of contentFiles? That NuGet would add them to your project

This is no more the case with the new .csproj system and PackageReference, maybe unless for some project types. At some point, before embedding view contents in assembly, we needed an msbuild task to copy them from their package locations to be compiled by the precompilation tool before publishing.

> My only question here is does this force the WebRoot to wwwroot if we're forcing creation during an MSBuild Task. If user has decided to go off the standard and make their own myspecialroot do we break things by creating another wwwroot alongside it?

This is exactly what i said in one of my last comments in #3490. In fact each module has a wwwroot folder and at the tenant level we call `UseStatiFiles()` **by passing a custom file provider** with an hard coded `wwwroot`. Do you know that when using OC the application is a module itself so you can request an app level static file in a 2nd way by using in the requested path the application name (not often used).

That said, i don't think that using `UseWebRoot("myspecialroot")` is a problem, the tenant level file provider will still use the hard coded `wwwroot` to serve module static files, including the app's module by using the app name in the requested path.

Just tried the msbuild task embedded in the cms package, it works with 2 lines of code. Normally we would need to mark this file to be published, but fortunately the standard publishing script automatically publish the `wwwrot` folder.

**Comment by deanmarcussen** [comment]
@jtkech 
> This is no more the case with the new .csproj system and PackageReference, maybe unless for some project types. At some point, before embedding view contents in assembly, we needed an msbuild task to copy them from their package locations to be compiled by the precompilation tool before publishing.

I did not know that. Cheers. 

> the tenant level file provider will still use the hard coded `wwwroot` to serve module static files, including the app's module by using the app name in the requested path.

And I didn't know that either, which is something I was wondering how to do the other day, so again, cheers.

**Comment by JoshTango** [comment]
I just got this issue with a new install and using the Agency theme.
