### ISSUE TITLE
Has document for "File based Content Definition"

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#3476]
I saw in Beta 3 there is a new feature "File based Content Definition". But I can't find any document/issue discussion about this(Or maybe I use wrong searching keyword).
Can anybody help to give some links or description?

**Comment by psijkof** [comment]
You are right! That change didnt make it to the documents yet, and I think it is a great feature, with deployment in mind.

### File based Content Definition

Instead of storing the json describing your contenttypes for a certain tenant into the same database as the content, this module will instead create a file, `ContentDefinition.json`, at the tenant level in the `App_Data` folder. It will have the same contents as it was written to (and read from) the database by the default `ContentDefinitionStore`. Once enabled all reads and writes for contenttype definitions will come from that file. 
This makes it easy to deploy your app and content definitions consitently.

**Comment by HengzheLi** [comment]
Definitely it is a great feature, it helps to simplify the deployment and update content type definition without touching database.

Thanks for the reply.
