### ISSUE TITLE
Cache localization resources

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3485]
I revised `PortableObjectStringLocalizer`, `CultureDictionary` and `CultureDictionaryRecord` I didn't find any sort of caching mechanism for the localization resources, it would be nice if we cache the resources for better Perf

/cc @sebastienros

**Comment by Skrypt** [comment]
IDictionnary is permanent cache in memory of the App. We don't need to invalidate this kind of data, you just edit, add, delete elements to it's key/value store.

**Comment by sebastienros** [comment]
It's loaded once I think, as @Skrypt said. Did you find it to be wrong?

**Comment by hishamco** [comment]
Why are you using `IDictionary` instead of `ConccurentDictionary`?

**Comment by Skrypt** [comment]
Because it's not a resource that requires concurrency optimizations. You use a ConcurrentDictionnary if you need to make batch updates from different several threads and keep performance decent. Here, it's a Dictionnary that won't require batch updates since it's loaded once on the application start and if changes are required to it we do it manually into .po files.

**Comment by hishamco** [comment]
FYI ASP.NET Core Localization is already using `ConcurrentDictionary` for localization cache

**Comment by Skrypt** [comment]
For low level stuff makes sense.

**Comment by hishamco** [comment]
Hopefully ..

**Comment by Skrypt** [comment]
I'm not sure why they picked a ConcurrentDictionary to be honest. They only need to retreive the current OS cultures? When you say Localization cache you mean that list of Cultures taken from the OS?

**Comment by hishamco** [comment]
We removed the current OS cultures from beta 7 or 8.

> When you say Localization cache you mean that list of Cultures taken from the OS?

Nope, I mean cache the localisation resources

**Comment by Skrypt** [comment]
> We removed the current OS cultures from beta 7 or 8
???

**Comment by hishamco** [comment]
I was talking about ASP. NET Core 😊

**Comment by Skrypt** [comment]
https://github.com/dotnet/corefx/issues/1669
https://github.com/OrchardCMS/OrchardCore/issues/2197
https://github.com/dotnet/corefx/issues/1669

I don't have time to check everything in there so if there's a performance issue @hishamco you can check with @sebastienros.

Though, from what I've read, the culture list comes from the OS still but with variants for unix systems. I could be wrong because I've not read everything ; but the list we are displaying comes from CultureInfo.GetCultures which is already cached in the .NET Core framework. We could add an other cache on top of this API call so that it be always retrieved from that cache but it's not necessary if the page is hit really few times. Would make sense for example to cache it if it was a frontend home page so that this list would not be retreived on every page request from the API. But stil, they made it cached in .NET Core for making it already faster... I think that's what I meant previously. And I've not seen any performance issue yet either. Up to you guys to decide if we do something about it or not.
