### ISSUE TITLE
Time Zones on Setup don't show BST

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/OrchardCore#3510]
On the setup screen, under the "Default Time Zone" field, the options show that Europe/London is +00:00, i.e. GMT.  But in fact for half of the year the UK is +1 hour on GMT.  This is called BST or British Summer Time.

Therefore, it looks like this list doesn't take BST into account.

**Comment by sebastienros** [comment]
Isn't it London time and it will take that I to account? For instance for Seattle I pick Los Angeles and it switches by itself from summer time. It's the same time zone.

**Comment by stevetayloruk** [comment]
The list shows that London time is +00:00 of GMT. Which it's not.  I'm assuming this time offset is then used elsewhere in the system which will put it one hour out. Or is it just the list values that are incorrect?

**Comment by Skrypt** [comment]
https://nodatime.org/2.2.x/userguide/trivia

**Comment by stevetayloruk** [comment]
@Skrypt I'm not sure what those links are saying.

I did read the first link before I reported this issue.  I don't think what it states is correct (or just confusing).

Ultimately, half of the year the UK is GMT and the other half of the year is GMT+1 (known as British Summer Time). https://en.wikipedia.org/wiki/British_Summer_Time

We are currently in GMT+1 (BST) but the list of timezones is showing GMT+0 for London.

**Comment by Skrypt** [comment]
Maybe the list is showing +0 but the actual time is adjusted fine? I will test it. But if there's an issue it's more likely that it will need to be reported to NodaTime which would really surprise me.

**Comment by stevetayloruk** [comment]
Correct, I'm unsure if it does store the correct offset and it just needs the label/frontend changing or it stores the incorrect offset.  Either way, there is a fix required.

TBH, the list is sort of awkward anyway.  It doesn't look like a standard list I've used on many other sites etc. where the grouping of London is never on its own.

**Comment by Skrypt** [comment]
When you select a timezone you are not supposed to take care of the DST for making the proper choice. The DST is an offset applied to the timezone conditionnally of the timezone because not every timezone have a DST. 

Yes, the timezones are different from a OS to an other and it's by design. The TimeZone list on Mac OS / Linux is the IANA timezone list and on Windows it will display Windows TimeZones which will make a relation to the proper IANA timezone.

IANA Timezones : https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Windows Timezones : https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/56756305-7987ae80-675f-11e9-8421-095793048505.png)

There is something wrong with the ordering of these. It should be ordered by Offset + TimeZone name.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/3511

**Comment by stevetayloruk** [comment]
I don't think you can say the list is more accurate when its not correct. Presently, London is not GMT+0 which the list is showing.  I can see many users selecting a +1 option (like Dublin etc.) which would be wrong.

**Comment by Skrypt** [comment]
@stevetayloruk I understand your point though I added a hint under the timezone selector that says that DST is applied automatically. I'm not sure if we should change the TimeZone names to display the correct current offset. I mean the timezone name is GMT-0 Europe/London ... the only confusing thing is that the timezone name is showing {0:00} instead because some timezones have a 30 min offset.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/56831176-714e7280-6836-11e9-9876-22db33291189.png)

Here what I did to fix the issue.
