### ISSUE TITLE
Cannot delete themes from the admin

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/OrchardCore#3539]
There seems to be no way to remove themes from the admin dashboard.

Only way is to remove from code base (which requires full source)

**Comment by Skrypt** [comment]
That would require that we have dynamic loading of libraries ... which will not happen unless someones implements it without perf degradation in OC. Should also require .NET Core 3.0 to be able to unload assemblies.

**Comment by sebastienros** [comment]
Maybe not ... Without having the whole source code you can reference the modules and themes you want. The issue you are facing is that we have a meta package that references everything. We could split it between themes and modules actually, because that would make sense to not import the default themes we have.

Another option (and I think it's already files) is to be able to select which features are available for a tenant, like we have in O1, from the tenant screen or the app settings.

**Comment by jtkech** [comment]
If it is to just no show them in the admin, we already have helpers or config to add features for all or a given tenant, so we could make e.g a config to exclude some features.

**Comment by sebastienros** [comment]
Like msbuild, Include then Exclude steps.

**Comment by jtkech** [comment]
Good idea, e.g excluding some for all tenants but re-add some for a given tenant.

**Comment by Piedone** [comment]
Is this issues about hiding themes from just certain tenants? Removing the theme from the whole app is triv
