### ISSUE TITLE
Avoid deleting culture when localized contents are associated with

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3601]

**Comment by Skrypt** [comment]
Not sure about this one.

Deleting a culture will remove it as an accepted culture so that the LocalizationProviders won't interact with it. This should be removable at any time since this is the way that we enable/disable the ability to use a culture on the backend or frontend. If someone removes a culture he also, right now, will not be able to create any more content item in that culture. Though, if there is remaining content items associated with a culture that is not supported anymore we could keep the ability to save back this item into it's current culture or assign it to a new one (default culture or else .. invariant).

The only thing I don't like about avoiding deleting a supported culture when there is content items associated with it is the fact that this break the ability of removing a supported culture for the frontend and backend.

**Comment by Skrypt** [comment]
This issue is kind of the same as the fact that we should also permit to resave a content item as InvariantCulture. Right now we can't.

**Comment by hishamco** [comment]
> The only thing I don't like about avoiding deleting a supported culture when there is content items associated with it is the fact that this break the ability of removing a supported culture for the frontend and backend.

This is similar to 1-M relationship, avoid delete is required or cascade delete is another option

> Maybe a warning message would be more appropriate

May be  .. but the culture will still show up on the content items

**Comment by hishamco** [comment]
I'm thinking about couple options:

1. Avoid deleting a culture and showing info message

2. Ability to delete a culture after a warning message show up, here the associated contents could be:
a. Deleted
b. Archived (No action needed)
c. Migrated to another culture

**Comment by hishamco** [comment]
> This issue is kind of the same as the fact that we should also permit to resave a content item as InvariantCulture

Again I dislike invariant culture 😊, because I think every content should associated with a culture even system culture

**Comment by Skrypt** [comment]
InvariantCulture is still relevant because we have 2 scenarios that we need to handle.

1. Someone has created content items without enabling the Localization module and his default culture is InvariantCulture. He never assigned any LocalizationPart to his content items.

2. Someone has enabled both the Localization module and the Content Localization module from the beginning or not but he has content items that doesn't require any translation and that should not be considered as specific to a culture but as global to all cultures. Which means in that case that InvariantCulture takes his full sense since it says that it should not be different from a culture to an other. Example : a person name, a company name ...

A content item should never have CultureInfo = null because that's irrelevant. This is why InvariantCulture should be seen as a proper culture because that's the last option in the Fallback mechanism so that nothing be seen as null.

**Comment by Skrypt** [comment]
Another example of Invariant Culture item. I have a "Page" content type that I have added a LocalizationPart. I have multiple pages created in different cultures but I have one specific page that I don't want to translate in every language or culture. I just want it to be the same url for every culture but I will add a Liquid field for adding code to that page so that I can have translatable elements...

**Comment by hishamco** [comment]
Thanks for your information, seems I did some changes in my latest PR, the default content will stay as it's even the content localization enabled and it has ability to create a clone for other locale

**Comment by Skrypt** [comment]
You mean this one? : https://github.com/OrchardCMS/OrchardCore/pull/3597

**Comment by hishamco** [comment]
Yep .. if you test you will recognize that first content will be a default one and doesn't care about localization, this will be useful if we change the default culture .. no need for migration or sort type of things

In content items no culture will show up that indicates it's the default culture

**Comment by Skrypt** [comment]
This could work. I need to test it.

**Comment by hishamco** [comment]
I tested with many cases, with supported culture and without and works perfect

**Comment by hishamco** [comment]
Please check it in Mac OS if you can

**Comment by Skrypt** [comment]
I found a NRE this morning but not with your PR though.

**Comment by hishamco** [comment]
Aha coz I didn't see any NRE 😊

**Comment by sebastienros** [comment]
> Avoid deleting culture when localized contents are associated with

I don't think it's necessary. I am fine seeing old content items from old cultures even if they are not supported anymore. We can still find them in the content items list, no need to wait for all of them to be deleted.

**Comment by hishamco** [comment]
At least we should show a warning message that this culture has associated contents
