### ISSUE TITLE
Domain request culture provider

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3609]
We need sort of domain or url culture provider that reads the tenant url and set the current UK culture thread based on a slug or subdomain, examples:

http://www.ar.domain.com
http://www.fr.domain.com
http://www.domain.com/ar
http://www.domain.com/fr

**Comment by sebastienros** [comment]
1- Domain request culture provider

And also maybe an option to define the route of the home page for these domains. The reason is that all localized items have their own canonical url. For instance, `/` in English (the default) might me `home-fr` in French, but when we access `http://fr.domain.com` we want users to go to `http://fr.domain.com/home-fr` with a redirection.

2- Content item culture provider

For these examples:

http://www.domain.com/ar
http://www.domain.com/fr

I think we just need the "content item" request culture provider, not a domain one, because the domain is the same. But we would then have a `/ar` route for the home page in Arabic.

**Comment by hishamco** [comment]
> I think we just need the "content item" request culture provider, not a domain one, because the domain is the same.

The domain may different from tenant to another, Am I right? If it's yes we need a culture provider that detect the localisation part from URL so we can which culture is suited for each tenant. If it's no again a `/culture` need to be recognised too

**Comment by sebastienros** [comment]
A single tenant can use different domains. One domain is always to one tenant.

**Comment by hishamco** [comment]
> One domain is always to one tenant.

If we have multi-tenants we may need a culture provider to set the request culture for each

**Comment by sebastienros** [comment]
Each tenant has it's own modules, its own settings, its own middleware, its own database. Obviously when we talk about creating a module it applies to distinct tenants. In this case yes, each tenant will have its own set of mappings.

**Comment by hishamco** [comment]
> 2- Content item culture provider

@jptissot I think you implemented this one only, Am I right?

**Comment by sebastienros** [comment]
No action to take, we already have a content item picker that handles that, and the domain should be handled with standard redirections (url rewrite)
