### ISSUE TITLE
Content localization dependency

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3638]
I'm not sure why the content localization doesn't depend on localization module, I think this module is useless without the ability to activate the core localization module

/cc @jptissot @sebastienros @Skrypt

**Comment by Skrypt** [comment]
I explained that on a previous post. The responsibility of the Localization Middleware is to allow supported cultures and apply them with LocalizationProviders. We could easily still want to localize content items in the admin without wanting to support it yet on the frontend. So, for that matter those 2 features should not be tied together because the responsibility of the Localization Middleware has nothing to do with the responsibility of localizing content items.

**Comment by hishamco** [comment]
> I explained that on a previous post.

May be .. I didn't see that

> We could easily still want to localize content items in the admin without wanting to support it yet on the frontend.

But once you support it you must need the localization, so in either ways localization must be enabled or the localised content will be useless

**Comment by sebastienros** [comment]
Technically it's not necessary. We might change it once we add more features in either module to support localization. Like the domain mapping, or culture picker, or picker widget ...

So not closing it right now as we might have to change it.

**Comment by hishamco** [comment]
Seems what I asked for is happened https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ContentLocalization/Manifest.cs#L16 but I forgot to close this 😉
