### ISSUE TITLE
Force Setup before platform operational..

### ISSUE THREAD

**Issue by dazinator** [OrchardCMS/OrchardCore#3700]
Hello - I've been redirected from asp.net core as I asked a question which they said was implemented in orchard core platform: 
https://github.com/aspnet/AspNetCore/issues/10441#event-2363091201

I'd basically like to deploy my asp.net core application with a flag that says setup is not complete.  Whilst in this state, i'd like to force the user to complete a setup wizard, then at the end i'll set that flag to complete, at which point, the rest of the system (controllers etc) should become accessible / operational.

My question is, could someone point me to the relevent bits of the orchard.core framework that I could possibly re-use to enable this flow within my application? 

Many Thanks.

**Comment by jtkech** [comment]
@dazinator here some infos but not so obvious to describe OC in a few words.

- Most of things are done in a tenant (also named shell) context, we can have multiple tenants but at least one named `Default`. A tenant is composed of modules / features that can be enabled / disabled. For a given tenant, the enabled modules / features are persisted through a tenant / shell descriptor.

- We have a tenant middleware which do a kind of `.Map` to get or create a given tenant context (child container) from which a tenant service scope is created. Then a tenant router midleware which build (once per tenant when requested) a tenant pipeline, and / or execute this tenant pipeline.

- Modules are micro apps with their own startup `ConfigureServices()` and `Configure()`, controllers views, and other `OrchardCore` things. Modules / Features (enabled for a given tenant) participate to create the tenant context and to build the tenant pipeline.

- We have custom implementations of application parts, model providers and so on, so that, in a given tenant context, only enabled modules are taken into account, e.g their views and controllers.

- The application itself behaves as a module so that you can use existing modules (or not) and add other features through your app without having to create any module. We have some helpers to e.g register services and do configuration from the application but at the tenant level.

- On a 1st startup if we don't find any tenant / shell descriptor (can be pre-configured), we create the `Default` tenant with a minimum set of features (configurable) including a `Setup` module (can be your own feature) which defines an home route and a **controller view proposing a setup form**.

- By default the setup form asks for a database provider + connectionString for data persistency, e.g to store tenant / shell descriptors. Using a database is not mandatory, but in this case you would have to implement a custom `IShellDescriptorManager` (see in our source code for some examples).

 - By default, in the setup form you can choose a recipe (customizable file) that will setup the default tenant e.g by enabling a set of modules / features. Recipes are not mandatory, we have some helpers to define by code the features that will be always enabled, only during the setup, or only after the setup.

So yes, you may just use the `Default` tenant and use your application as the only one module that would have a custom setup feature that fits your needs. Hmm, but not sure that you need all this infrastructure.

**Comment by jtkech** [comment]
Also, currently we still use the `Router` system, but it is planned to use the new endpoint routing system when we will migrate to 3.0, see our `jtkech/core3.0` branch.

That said, maybe a simpler way to do what you want. Maybe a middleware which checks that your setup has been done. If not you could retrieve (and cache it) the endpoint related to your setup controller and then set it as the current endpoint, [see what we do here](https://github.com/OrchardCMS/OrchardCore/blob/f106cdbc0f537965f5aba549cbb25a16934d0e06/src/OrchardCore.Modules/OrchardCore.HomeRoute/Routing/HomeRouteMiddleware.cs#L49). Otherwise, if your setup has been done and the current route values match your setup controller, you would have to return a 404 response.

**Comment by dazinator** [comment]
@Jtkech thank you for the detailed response, that's a great help. I agree with you, I think sticking with a middleware is probably going to be the easiest approach as the app I am working on already has it's own multitenancy model including tenant containers and middleware pipeline and I don't want to have to overhaul that or bring in orchards recipe stuff for this one feature if I don't have to. I hadn't consisered using the new endpoint routing for this though so I'm going to take a closer look at that code you linked. 
Many thanks!

**Comment by dazinator** [comment]
@jktech I was wondering with respect to this:


> We have custom implementations of application parts, model providers and so on, so that, in a given tenant context, only enabled modules are taken into account, e.g their views and controllers.

I am designing something similar to orchard (in that it's an extensible platform) and I considered how to make MVC behave in a multi tenant way. The orchard approach derices custom MVC services to reach that goal. I ended up just registering MVC multiple times (once in each tenants context). This way you can configure mvc for the tenant based on what apps they have enabled etc, without having to code any custom mvc behaviours to make it multitenant. Given each tenant has it's own ServiceProvider which is swapped out at request time based on the current tenant, it's not like there is a single global SP with thousands of services registered in it, but now each tenants SP has MVC in it. I am curious to know whether you know if the orchard team considered this approach and actively decided against it?

**Comment by jtkech** [comment]
We are doing quite the same, each tenant has its own isolated child container, a shell context (shell = tenant) with its own service provider, from which we can create isolated shell scopes, also its own pipeline and so on. When using mvc (not mandatory with the OC framework) `AddMvc` is called for each tenant, we also register an isolated `ApplicationPartManager` for each one ...

In fact, most of the time we use regular mvc services and most of the time custom implementations are not related to multi tenancy but to modularity, meaning that for a given tenant we can dynamically enable / disable features (defined in modules) at run time. E.g by using our `ShellFeatureApplicationPart` only the controllers related to enabled fatures will be discovered.

Note: Beyond mvc there are some aspnetcore and orchardcore app level services. When we create a child container, it inherits from these services that we clone, and for an app level singleton the same instance is shared by all tenants. But some time these services still need to be isolated per tenant (e.g for authentication and data protection) so we do some cleaning before re-using regular extensions.

Some time we need to do the same with an app level singleton that uses some global config data that would not be thread safe if mutated concurrently by multiple tenants. We can do that because we wrap an app level singleton descriptor in a custom descriptor holding the original one, so that we can dectect that it has been registered at the app level and with which implementation type. So we can retrieve it, remove it and re-register it, then each tenant will use an isolated instance of this service.

E.g, we have a branch to migate to 3.0, and this is the case with the new endpoint routing services. Her my comments in the source code.

    // The routing system is not tenant aware and uses a global list of endpoint data sources which is
    // setup by the default configuration of 'RouteOptions' and mutated on each call of 'UseEndPoints()'.
    // So, we need isolated routing singletons (and a default configuration) per tenant.

**Comment by sebastienros** [comment]
> although my efforts predate orchard core

Do make risky statements like this ;) 

> I'm a one man band so development has progressed slowly

Why don't you join us then?

**Comment by dazinator** [comment]
> Do make risky statements like this ;)

Quite right, apologies. It seems orchard core repo was first created in 2014 and my efforts didnt start until 2015  - apologies!

> Why don't you join us then?

Good question. At the moment I prefer to learn through developing my own projects. I think it is the creative freedom that keeps things fun for me and keeps me learning. However who knows what will happen in the future, perhaps I'll look to help out / contribute to the orchard core project in future, once my personal projects in a similar area are concluded.

> 

Hmm not sure I fully understand the need for this custom stuff with descriptor wrappers and the like yet. For example, In my multitenancy library I have a razor pages example for 
Net core 3.0 - and I found adding `.UseEndpoints()` to the tenants middleware pipeline to be sufficient. Perhaps the difference is because I add the Mvc / razor pages services to the tenants services rather than applicatio services, so in essence each tenant gets it's own `RouteOptions` object without me having to coerce a shared service collection in anyway? Not sure. But you can see my sample here if curious: https://github.com/dazinator/Dotnettency/tree/develop/src/Sample.AspNetCore30.RazorPages

Btw: thank you for your detailed response, I find this stuff really interesting. It seems the only concept so far that you have touched upon that I have not personally found some need for is the ServiceDescriptor wrapper stuff. I dont want to take anymore of your time, perhaps as my platform matures I'll stumble accross the issue that you lead to that solution eventually, or perhaps its something I won't need due to the way I am handling  tenant services! Thank you regardless :-)
