### ISSUE TITLE
Gulp pipeline: enhancements

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3725]
1. Should allow to use different versions of Bootstrap/lib for different themes/modules.
2. Should create source maps files instead of bundling it in the minified assets.
3. Should work properly with dependency folders added to the main package.json file.

**Comment by sebastienros** [comment]
I want to see a some repro steps showing the issue, or statements about what the issue is and why the suggestion would fix it.

**Comment by deanmarcussen** [comment]
The Bootstrap 4.3.1 upgrade has a few version conflicts.

BS 4.3.1 still uses popper 1.14.7 but we have upgraded to popper 1.15.0

The `ResourceManifest` has the `bootstrap-bundle` depending on `popper` but `bootstrap-bundle` ships `popper 1.14.7` in it, so probably `bootstrap-bundle` only needs to depend on `jQuery` and `bootstrap` needs to take a dependency on `popper`

Lastly npm install with npm version 6.9.0 gives errors such as this because versions in package.json of the Setup / Admin / Resources are different. They resolve (mostly) by removing the 'package.lock.json' from the modules, or by doing an npm install in the modules folder directly, thereby updating the package-lock.json

![npm-error](https://user-images.githubusercontent.com/13782679/58786817-4fd46980-85e0-11e9-9c97-99820ae3eb4d.png)

Should we update these package-lock.json files in the modules and commit them?
And resolve the other version conflicts and rebuild TheAdmin.js etc

Caveat: Not an npm expert, just reporting what I'm seeing 😄

**Comment by deanmarcussen** [comment]
@Skrypt are you working on something related to this?

If not I might put a PR together to fix the bootstrap-bundle and popper issues I see?

**Comment by Skrypt** [comment]
Up for grab 😉

**Comment by deanmarcussen** [comment]
Also the bootstrap-bundle integrity values in `ResourceManifest.cs` are incorrect, and the script is blocked.

Will check the others as well
