### ISSUE TITLE
Install multiple languages

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#3731]
* .po files will be overwritten in the App_Data/Localization folder when we want to run multiple languages ​​by copying languages packs into the same directory.

**Comment by sebastienros** [comment]
You should use one folder per culture if you are using the files from crowdin. This is new since last month as we faced some conflict for some languages.

Is there a technical reason you can create these folders? If you download the po files from crowdin they will already be organized this way. see https://orchardcore.readthedocs.io/en/dev/docs/guides/install-localization-files/
