### ISSUE TITLE
Assets/Media are empty after Importing a Deployment Plan

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#3765]
I just exported the Media from our development server using a Deployment Plan (exporting Media) and then imported it into our cloud server.

**Cloud:**
![assets-cloud](https://user-images.githubusercontent.com/26597675/58970793-05a2e200-87b2-11e9-8f1a-cba1e5d98acf.png)

**Local:**
![assets-local](https://user-images.githubusercontent.com/26597675/58970794-063b7880-87b2-11e9-9518-071bc389130e.png)

The import worked correctly but then when I go to the Assets menu in the Admin page it only shows me empty folders. However if I try to upload the files manually it tells me that the files already exists (which they do, since I can access them via the /media/ path.

**Error:**
![assets-error](https://user-images.githubusercontent.com/26597675/58970932-4d296e00-87b2-11e9-9c09-bc489d2f6285.png)

**Edit:**
I'm using the following version:
OrchardCore.Application.Cms.Targets 1.0.0-beta3-71567

**Comment by deanmarcussen** [comment]
@nuno-tiago-reis I experienced a similar problem deploying to an Azure Windows WebApp a couple of weeks back, but I could not repeat the problem once I had 'fixed' it.

Can you check the chrome debug console network tab?

There are two ajax calls that are made `GetFolders` and then `GetMediaItems`.

For me the `GetFolders` called seemed to succeed, but a `GetMediaItems` call was never made. But if I uploaded a new media item the upload occurred, and I got the same error that you receive about the file already existing.

I tried webapp restarts, and looked at all the folder permissions through scm but everything looked good.

The 'fix' was to create another folder through the media library, and then everything started working perfectly. 

I wasn't able to repeat the issue by deleting the folder, or adding another tenant, and trying with a different theme.

So it would be good to see if your chrome tab shows both ajax calls, or just one, and if creating another folder might resolve it.

Here's the successful chrome network calls
![oc-media](https://user-images.githubusercontent.com/13782679/59108193-475a9680-8932-11e9-9912-28a7c42dd7f3.png)

**Comment by nuno-tiago-reis** [comment]
I have both ajax calls being registered and the responses look fine.
The issue is that nothing displays in the page.

**Comment by matiasmolleja** [comment]
I tried and I can't repro.

Maybe not related, but I noticed  that the import step does not create the marker file on the azure blob container. 
I mean, when you enable azure blob storage and create a folder through the UI, It creates marker files, so that azure "knows" that this is a folder.
But when the folder structure is created through the import step, marker files are not created.

Anyways this does not seem to be the cause of the issue, because I tried deleting those marker files by hand, and everything seems to be working nicely even without them.

More Info about those marker files here:  https://github.com/OrchardCMS/OrchardCore/blob/2365b822ea58a8e1a32d3a710f27e3b08aedd03e/src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs#L25
