### ISSUE TITLE
Lucene background worker : ViewLocalizer missing while invoking 't"

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3797]
This happens when I enable the Lucene background worker or when I'm rebuilding indices manually.
Seems to happen when we are using a Liquid template and we are using the { "something"  | t } filter on a string that has not been translated in a .po file.

![image](https://user-images.githubusercontent.com/3228637/59331444-f8aa5500-8cc1-11e9-9fbd-b46122893a82.png)

**Comment by Skrypt** [comment]
An other issue with the Lucene Background Worker I found.
When starting a website on Azure it will throw this exception : 

```C#
2019-06-19 20:23:23.7355||||OrchardCore.Modules.ModularBackgroundService|ERROR|'ModularBackgroundService' is stopping. 
```

**Comment by jtkech** [comment]
There are contexts where `LiquidTemplateManager.RenderAsync()` is used with no `DisplayContext` and then where the `TemplateContext` is not completely contextualized e.g without `IViewLocalizer`. That would mean that the `t` filter is used in one of these contexts.

A recent PR added in `RenderAsync()` a call to `ContextualizeWithDefault()` to register at least the service provider in the `TemplateContext.AmbientValues`.

Because now we can create e.g a fake `ViewContext` and so on, i think we could do a more complete contextualization when using the `LiquidTemplateManager` in these contexts.

**Comment by Skrypt** [comment]
Ok I did some tests and these issues happens only when indexing a LiquidPage content item. Because the template itself tries to render before getting indexed and thus trying to find also string translations.

_At some point those LiquidPages got added to my IndexingTask table but I don't require it anymore so I could simply remove those from the database to fix my issue._

I made a second test by adding indexing on the Title field of the LiquidPage content type and then created a new content item. It got added to the IndexingTask table. Though after removing the Indexing on the title field and publishing again the same content item it didn't remove the content item from the IndexingTask table.

For the issue itself it's surely related with the explanation made by @jtkech in the previous post.

**Comment by jtkech** [comment]
I don't remember the details but maybe normal for the `IndexingTask` because there are 2 types of task, `Update` and `Delete`.

Then i will do some tests by indexing the liquid part of a liquid page.

**Comment by jtkech** [comment]
I can't repro, when building an index of a liquid part, the content is used as it is, it is not liquid evaluated.

> The template itself tries to render before getting indexed.

How it is possible? Is it a simple liquid page without any other additional parts / fields?

**Comment by Skrypt** [comment]
I will try to provide a repro else just Skype me and watch the debug show. 😉

**Comment by jtkech** [comment]
I could repro your issue (regarding your 1st screenshot) by using a liquid widget (that has a liquid part).

I got the same breakpoint when publishing it and then after by the background task. Let me some time to debug it before investigating it together ;)

**Comment by sebastienros** [comment]
Please share the details to repro, I had the same question, how can indexing trigger a liquid template evaluation. Not that I would not love to be able to do this to index the full body of a content item.

**Comment by Skrypt** [comment]
Let me try with a clean tenant first.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/59889757-e56f4780-939b-11e9-9259-6b2285b4f69d.png)

And on the LiquidPage set the Title part to be indexed.
You will get this issue instantly : 

![image](https://user-images.githubusercontent.com/3228637/59889768-fcae3500-939b-11e9-90a5-c8c5ee31225e.png)

**Comment by sebastienros** [comment]
Share the stacktrace

**Comment by jtkech** [comment]
In fact i have the same breakpoint with a liquid page using the `t` localizer, when publishing it and then through the background task (even i uncheck the indexed in the liquid part).

It happens through the `AspectsContentIndexHandler.BuildIndexAsync()` that call the following that uses the `_liquidTemplateManager` and there is no log because it is catched. So, to repro you have to put a breakpoint as shown in the 1st screenshot, create a liquid page that use `t` and then publish it.

Notice that there is no contextualization, so only the default one (with "Services") will be used, maybe the default contextualization would eed to be more complete (with a fake display context).

        public override Task GetContentItemAspectAsync(ContentItemAspectContext context, LiquidPart part)
        {
            context.For<BodyAspect>(bodyAspect =>
            {
                try
                {
                    var result = _liquidTemplateManager.RenderAsync(part.Liquid, System.Text.Encodings.Web.HtmlEncoder.Default, new TemplateContext()).GetAwaiter().GetResult();
                    bodyAspect.Body = new HtmlString(result);
                }
                catch
                {
                    bodyAspect.Body = HtmlString.Empty;
                }
            });

            return Task.CompletedTask;
        }

**Comment by Skrypt** [comment]
Stacktrace : 

```
   at OrchardCore.DisplayManagement.Liquid.Filters.LiquidViewFilters.Localize(FluidValue input, FilterArguments arguments, TemplateContext context) in E:\Repositories\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\Filters\LiquidViewFilters.cs:line 33
   at Fluid.Ast.FilterExpression.<EvaluateAsync>d__12.MoveNext()
```

**Comment by jtkech** [comment]
Seems that all items of any types are always indexed and that you can just add / remove some parts / fields to be indexed, but seems to only work for new created items, even if i rebuild the index before.

Otherwise, the issue seems to be clear for me, it happens through `AspectsContentIndexHandler.BuildIndexAsync()` that calls `LiquidPartHandlerGetContentItemAspectAsync()` that uses `_liquidTemplateManager` without contextualization. I will try to fix it by providng a more complete contextualization.

Note: Indeed if the liquid part doesn't use the `t` localizer, there is no issue.

**Comment by Skrypt** [comment]
Would make sense that every content type contentItems would be added to the IndexingTask table. I could have made a mistake by looking at 2 differents databases while testing.

I will work on index settings to provide a way to decide which content types we want to index per index.

**Comment by jtkech** [comment]
I think that i fixed it but i still have a little concern that i will fix soon, then i will do a PR.

**Comment by jtkech** [comment]
@Skrypt did you try #3851 to see (if you have time, not urgent for me) if it fixes your issue?
