### ISSUE TITLE
issu in localization

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3798]
the localization settings don't work,
some version before it set the RTL and change the menu localization but now nothing happens.
![1](https://user-images.githubusercontent.com/24512878/59368758-3600f800-8d3f-11e9-9b46-4dd2e8a7ee0c.JPG)

**Comment by Skrypt** [comment]
Your browser probably has en-US as a supported culture that's why it will use it. That's the behavior of the AcceptLanguageHeaderRequestCultureProvider. We might want to add a setting to allow to disable it for removing confusion and only allow changing culture with cookie or querystring. Though it works properly there is no issue. Just put fa-IR on top of your allowed cultures in your browser and it will fix your issue.

**Comment by aghili371** [comment]
@Skrypt  thanks it works now
