### ISSUE TITLE
Encoding method POST

### ISSUE THREAD

**Issue by danis-arslanov** [OrchardCMS/OrchardCore#3811]
When I send a cyrillic text with Contact Form on email by method POST I recieve wrong encoding of the text.

I installed empty TheAgencyTheme, and I added Contact Form + HTTP Request Event + Email Task.
That's all. 

In Email Task the text from the request {{ Request.Form.Name }} has wrong encoding.
But if I type the text handly - it is in the normal encoding:

Имя: \u0418\u043C\u044F
Почта: \u0415\u043C\u0435\u0439\u043B
Телефон: \u0422\u0435\u043B\u0435\u0444\u043E\u043D

UPD:
I tested Beta 2 - this version does not have such problem, troubles starts in Beta 3.

**Comment by danis-arslanov** [comment]
It is a very stupid sutation, I killed four days for understanding, that the problem can be solved just with liquid filter "raw": 
{{ Request.Form.Name | raw }} 
it works.

**Comment by jtkech** [comment]
Not stupid, it will help others having the same issue. When i saw your issue i was not able to answer too ;)

**Comment by sebastienros** [comment]
Any time Liquid is used, we apply a default encoding now. Like in Razor where any injected property is HTML encoded by default. So in Lucene queries we Json encode it, in views we HTML encode it. In Workflow tasks, for an email it will be HTML encoded too, and the json ones will be Json encoded. That means you will be safe by default if you use any `{{ }}` expression, but if you know what you are doing you can use ` | raw`.

**Comment by danis-arslanov** [comment]
Thank you so much for you comment, But I don't understand why email works in Beta 2 without `| raw`, but in Beta 3 it needs it. Is it just a temp trouble?

**Comment by Skrypt** [comment]
No it's not a temp trouble. We are now encoding the Liquid templates in their different contexts as @sebastienros explained.

Example : http://yourdomain.com?param1=stringwithdiacritics(éàû)
would be html encoded as : http://yourdomain.com?param1=stringwithdiacritics&eacute;&agrave;&ucirc;

But then when it's parsed by a SQL Query Liquid template we need to search for "é" and not "&eacute;" so you need from your Query to specify that you want to have the string as a "raw" string instead of an HTML encoded string simply.

Like @sebastienros explained it is safer that way.

**Comment by sebastienros** [comment]
That's change we made between beta2 and beta3.

**Comment by danis-arslanov** [comment]
I understand what is HTML-entities, my question in other one: 
so, if I need to send email with cyrillic text, I always need to use `| raw`
And this method is correct and safety. Do I right understand you?
Sorry for my meticulousness, because I'm afraid this method.
