### ISSUE TITLE
Wysiwyg editor converts div to p tag 

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3817]
@sebastienros How to prevent the conversion of div to p tag automatically  in wysiwyg editor ?

**Comment by pbeachlerif** [comment]
Greetings,
I had to modify the Trumbowyg editor presets in their .js files to override this. I had the same issue when trying to build out custom image alignment and caption functions that resided within a div. 

This should be on/around line 494 in OrchardCore.Modules>OrchardCore.Resources>wwwroot>Scripts>trumbowyg.js

`    Trumbowyg.prototype = {
        DEFAULT_SEMANTIC_MAP: {
            'b': 'strong',
            'i': 'em',
            's': 'del',
            'strike': 'del',
            //'div': 'p' (comment this line out)
        },`

Let me know if that helps you.

**Comment by jtkech** [comment]
Yes, we would need some relevant settings for this editor, good candidate for a PR.

Thanks for the info, good catch.

**Comment by RajasekarPR** [comment]
@pbeachlerif @sebastienros 

Thanks mate. Can you raise a PR and merge this please.

**Comment by sleeplessninja** [comment]
Not looking to open this up again, but because this is where I first came to when I ran into this issue, I thought it would be useful for others.  The current version of Orchard Core converts div for p out of the box for the Wysiwyg editors, but the way to fix this issue is much more flexible.

Go to your HTML part/field.   Select Trumbowyg editor. There are editor options, add to those options:

```
 semantic:{
      'div': 'div'
    }
```

![image](https://user-images.githubusercontent.com/1628063/101569108-d3270600-39a1-11eb-85da-ceb8c317d055.png)

Refer to the documentations provided in the part/field editor for more details.
