### ISSUE TITLE
Some liquid filters should not be encoded

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#3833]
example:

```
{{ imagePath | asset_url | resize_url: width:475, height: 345, mode: 'crop }}
```

Currently the result is html encoded.

**Comment by sebastienros** [comment]
Example:

![image](https://user-images.githubusercontent.com/1165805/59796194-cc7a6f80-9291-11e9-8f2b-eae502b31769.png)

**Comment by jtkech** [comment]
Yes just tried, i can see it in the source code, but it works, the image is well rendered.

Above there is a missing `'` at the end of `'crop` and maybe you tested `strech` in place of `stretch`.

Otherwise, e.g in `resize_url` this can be fixed by using

            return new ValueTask<FluidValue>(new StringValue(url, false));

Not sure how to find all the filters that need this, maybe the ones that are intended to update a tag attribute.

Note: Using `| raw` also works

**Comment by Skrypt** [comment]
I don't understand the issue. Is it not safer to use ASCII chars only for url's? Does the image still gets resized by ImageSharp?
