### ISSUE TITLE
Bug in js asp-append-version implementation

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3885]
Build `1.0.0-beta3-71772`

![src](https://user-images.githubusercontent.com/1761249/60769871-4bb2d480-a0d5-11e9-9895-0dab05bfff5e.png)

`asp-append-version` in the current implementation only work if developer uses `asp-src` instead of a plain `src`.

This is in contrast on how the feature works in normal ASP.NET Core Tag helper which can create confusion. It is also in contrast to how it works in `img` tag (https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Media/#razor-append-version) or `link` tag.

**Comment by deanmarcussen** [comment]
Yes, good spot. I see what's going on there.

The Orchard Script TagHelper is taking over from the MVC one, when it shouldn't, which means it's getting queued in the `ResourceManager` to be placed later in the foot of the body, but because you do not call `<resources type="FootScript" />` it isn't getting rendered.

The use of `asp-src` is intentional, to differentiate between the two tag helpers, it lets you set locations (with `at="Foot"`) and `debug-src` and others. 

Regardless they shouldn't be colliding, and is an easy fix.

I think a similar issue might be happening with the `link` tag helper so will investigate a bit further
