### ISSUE TITLE
Admin scripts cache busting

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3912]
We should add asp-append-version on admin scripts that are subject of updates/enhancements.

**Comment by deanmarcussen** [comment]
@Skrypt Was just going to roll through all the admin scripts (I'm about halfway through so far) and add `asp-append-version` to them all so it's done. I see you have also already started to do the same 😄 I'll try and get the ones I've done so far into a PR so we don't cross efforts?

**Comment by Skrypt** [comment]
Don't worry I just created the issue because yesterday I was going through all the changes I made for myself and made separated PR's for each of them.

If we do media thumbnails make sure that it won't affect also the ImageSharp cache on every publish of the app.

**Comment by sebastienros** [comment]
During last meeting I mentioned have cache busting be the default, or at least have a setting to be able to make it the default, or disable it, or use whatever is defined in the tags. The same way we handle the CDN versions. Would it make sense?

**Comment by Skrypt** [comment]
Yes we made both PR's before having your opinion about it so I guess the PR needs to be refactored taking this in consideration.

**Comment by deanmarcussen** [comment]
That sounds like a good idea. 
Another site setting would work, on by default, but can be turned off, and the tag helpers and `ResourceManager` could override it.

We should also update the tags that only reference a cdn-src to be `asp-append-version="false"`, so that the `ShellFileVersionProvider` doesn't have to noop the absolute urls.
