### ISSUE TITLE
Vue content picker error even if not used

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3945]
I have a ContentItem with a FlowPart that is empty.
For this FlowPart there is only one widget with a ContentPicker available.
As i've said, even if the flow part is empty on a new content item, this error occurs:
![image](https://user-images.githubusercontent.com/1375119/61389215-cb505880-a8b8-11e9-90ba-58553c7cc76d.png)

**Comment by jptissot** [comment]
We should probably cleanup all the js initializers to target some classes or data attributes instead of injecting <script> tags in the body.

**Comment by jptissot** [comment]
I think this is related to https://github.com/OrchardCMS/OrchardCore/issues/4223

**Comment by Skrypt** [comment]
I got this issue too because we changed the content picker to events.
You need to register a listener on the events but the events themselves needs to be created first.
I fixed this by adding the script code right after the BODY on my Razor template.
Though, it should be handled more gracefully than that by fixing the script orders or something else.
