### ISSUE TITLE
Increase Z-Index of "Add Widget" dropdown when editing a content item

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#4015]
Hello,

Using `1.0.0-beta3-71936`

We have added quite a number of custom widgets to our Orchard system, and as such the drop down menu goes underneath the admin header bar at the top which means the top widget in the list can't be selected.

Also is there any chance of this list being sorted alphabetically opposed to in activation order please.

![image](https://user-images.githubusercontent.com/1166915/62721429-12d38b80-ba04-11e9-9d43-cf06f019edf4.png)

**Comment by sebastienros** [comment]
Do you want to create a PR, at least for the widgets ordering?
And if you have some ideas to make this selected better we are open for it too. Like a real popup, and bonus points if we can use custom thumbnail shapes for each of them.

**Comment by sebastienros** [comment]
@matiasmolleja I think you are looking for things to do, right ;)

**Comment by Skrypt** [comment]
https://getbootstrap.com/docs/4.3/layout/overview/#z-index
According to this using a z-index of 1000 on dropdown menu is the standard in BS4.
The issue is that the header is using a z-index of 1020 `$zindex-sticky:` which seems the appropriate var to use in this case. I guess we should then simply use 1000 for every `$zindex-sticky:` item then.
