### ISSUE TITLE
Expand and Collapse not working in WidgetListPart

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#4021]
@sebastienros Expand and collapse are not working When I try to add bagpart to widget.

Kindly do the needful.

**Comment by Skrypt** [comment]
Can you show us a screenshot because I'm not sure of what you mean.

**Comment by sebastienros** [comment]
Can you also try to do a CTRL+F5 to refresh the scripts?
Also if you can still repro the issue, what version?

**Comment by jtkech** [comment]
Okay i could repro.

I added to the `Paragraph` widget type a bag part of `BlogPost` type, then i added a `Paragraph` through the layers page and created in its bag part 2 posts. Then i could expand and collapse these `BlogPost`. So it works through the layers page.

Then i tried to do the same but through a `WidgetListPart` that i added to the `Article` type. Then, in an `Article` i could add a `Paragraph` and in its `BagPart` a `BlogPost` but at this point there are some 1st bad rendering i think due to the nested expanding / collapsing areas.

Then, at this point if i collapse the `BlogPost` i can't expand it anymore. If i publish the `Article` and re-edit it, i can expand the `Paragraph` but not the `BlogPost` included in its `BagPart`.

**Comment by RajasekarPR** [comment]
@sebastienros Will this be fixed in next release ? 

Since we are depend on this widgets on our application.

**Comment by RajasekarPR** [comment]
@jtkech @sebastienros Meanwhile, this issue is not happening in Layers Module.

**Comment by devlife** [comment]
I can confirm this is also happening for me with the `BagPart`. I cleared cache, did `CTRL + F5`, but still nothing.

**Comment by sebastienros** [comment]
@ns8482e can you please take a look?

**Comment by ns8482e** [comment]
@sebastienros  It's working in dev branch.
@devlife Can you provide more detail?

**Comment by agriffard** [comment]
Is it still occuring or can be closed?
