### ISSUE TITLE
 Using jQuery plug-in in module to report errors

### ISSUE THREAD

**Issue by xiaogewujiu** [OrchardCMS/OrchardCore#4026]
Hello! When I use the jQuery plug-in in my new module, when I put the plug-in method outside of the "ready" method, the plug-in method works well, but when I put the plug-in method inside the "ready" method, $(...) XXX is not a function. 
![XK OG$41NDF3O$PG@4BZ6J](https://user-images.githubusercontent.com/52649684/62848091-70215280-bd0c-11e9-8128-0236a82c9176.png)
![)Q( 3IX74({ RN$8491U{UE](https://user-images.githubusercontent.com/52649684/62848100-7c0d1480-bd0c-11e9-92a9-6ee090b21e2a.png)
Error content
![9 {SA4S0VN~VSI5TI$P_ HD](https://user-images.githubusercontent.com/52649684/62848193-f50c6c00-bd0c-11e9-83c4-2a3e561ac187.png)

**Comment by deanmarcussen** [comment]
Yes, because jQuery is being loaded at the foot of the theme layout, so after your inline script.

If you use 
```
<script at="Foot">
  $(document).ready(function () {
            console.log('script works');
        });
</script>
```

this should trigger the Orchard Core script tag helper which will load your script into the foot after jQuery.

Note - you need a reference to `OrchardCore.ResourceManagment` and this line `
@addTagHelper *, OrchardCore.ResourceManagement` in the `_ViewImports.cshtml` file of your module.
