### ISSUE TITLE
Taxonomies Deployment Plans

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4075]
Found when testing #3402 

Taxonomies are not properly exported when using Deployment Plans. Child Terms are not exported in the recipe.
Importing a taxonomy also does not work when using the "Import Package" feature of the Orchard Admin.

**Comment by LMSSonos** [comment]
@hishamco because I had another exception related to import/export taxonomies (still debugging) I found the following steps / behavior related to this issue

 think taxonomies are exported as soon you have other content referencing it. 

Try these steps
1. Start new orchard, blank site
2. Configuration > Features > Enable taxonomies
3. Content definition > Content Type > Create new type , Name: "Group", add title
4. Content definition > Content Type > Create new Taxonomy, Title: "grouptaxonomy", term content type "Group" => publish
5. New > Taxonomy > Title: "GroupTaxonomies", Term Content type: "Group" => Publish
6, Add 2-3 Groups + 2-3 Subgroups
7. Configuraiton > Deploymentplans > Add Steps All Content, All Features, Content Definitions => Run export
**=> Taxonomies are not in export, but I would have expected it**

8. Add new Content Type: TestPage (add title, autoroute), then add Taxonomy Field named "TestGroup"
9. New > TestPAge, select a group (or multiple) and enter a title, publish it
10. => Export it again
**=> taxonomies are now included in the export**
11. started blank site again, import worked as expected

**Comment by hishamco** [comment]
Thanks to know that, @jtkech is this a normal behavior?!!

**Comment by jtkech** [comment]
Just did a quick test, seems to work on my side.

That said in the step 4. i didn't do `Content definition > Content Type > Create new Taxonomy`.

Through the admin menu i just used `New > Taxonomy`.

**Comment by deanmarcussen** [comment]
Also tested and can't repro

All term items (and sub terms) are contained in deployment plan
