### ISSUE TITLE
Custom Widget with BagPart of Link Menu Item under Layers

### ISSUE THREAD

**Issue by sivakumar715** [OrchardCMS/OrchardCore#4079]
I have custom widget with BagPart of Link Menu Item. It's working fine by adding the custom widget in any content item and shows only Name & Url which is expected. But, In the Layers, additionally Title & layer of the widgets are displaying along with this. Is this expected?

**Custom widget in Content item with WidgetsListPart :**
![image](https://user-images.githubusercontent.com/54092242/63420106-a5702380-c423-11e9-85e6-e5240a2fb426.png)

**Custom widget in Layers:**
![image](https://user-images.githubusercontent.com/54092242/63420187-d0f30e00-c423-11e9-83a4-506bb9efeb2f.png)

**Comment by jtkech** [comment]
Yes, we only use the render title option through the `LayerMetadata` when wrapping a widget.

Then, when using layers, we need layer rules because rendering a widget is not tied to rendering a given content item, we need instead to define a rule as the predefined `Always` rule meaning that the widget will be shown in any front end themed page.

**Comment by sivakumar715** [comment]
Thanks @jtkech for the quick reply.
 I agree with your comment , displaying **Render title & layer rule** for the custom widget in layers sections. But, **Render title & layer rule** are displaying even for the Bag part of Link Menu Item (which is not a widget). Please confirm, is this expected?

![image](https://user-images.githubusercontent.com/54092242/63516065-de82c380-c509-11e9-9dc5-c4323c0099cb.png)

**Comment by sebastienros** [comment]
Makes sense, good catch.
