### ISSUE TITLE
metadata.AdminRouteValues，EditorRouteValues Same

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#4097]
![image](https://user-images.githubusercontent.com/16968103/63631621-ffa7f900-c65c-11e9-8c24-3032c4c1a7e2.png)

metadata.AdminRouteValues，EditorRouteValues Same
{"Action", "Edit"}   =>  {"Action", "Display"}
？？

**Comment by deanmarcussen** [comment]
Yes, the default Editor and Admin Controller are able to use the same Controller Action.

However you can override the default `ContentItemMetadata` Aspect on a content type / part to provide different route values for any of the actions
- CreateRouteValues
- EditorRouteValues
- AdminRouteValues
- DisplayRouteValues
- RemoveRouteValues

This would allow you to use a custom controller, rather than the default, to handle different actions.
