### ISSUE TITLE
The specificity of base admin theme rules is too strong

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#4138]
If you want to customise the look and feel of the admin a great thing to do is to simply base your custom admin theme on TheAdmin and then work from there. However, within TheAdmin theme the majority of rules use [dir] as the first selector making most rules difficult to tweak in a custom admin theme without resorting to more complex rules, which could easily be broken by updates to the admin UI, or by using !important (and you should rarely have to use important).

Using "dir" only makes sense when you need to override the css for right to left languages which in that case you should use [dir=rtl] but the base left to right version should not use [dir] and should resort to rules with low specificity so they can be easily tweaked (or even better BEM).

For example, let's look at caption. TheAdmin theme uses:

[dir] caption { padding-bottom: 0.75rem; }
[dir=ltr] caption { text-align: left; }
[dir=rtl] caption { text-align: right; }

The [dir] and [dir=ltr] shouldn't be necessary and a better approach would be:

caption { padding-bottom: 0.75rem; } (text-align: left is the default for ltr users)
[dir=rtl] caption { text-align: right; } (in fact this should be necessary at all I think because doesn't the users browser automatically set this as the default)

This still achieves the same thing but with less specificity and allows for a admin theme which is using TheAdmin as a base theme to easily override the classes without complexity.

**Comment by hishamco** [comment]
Hi @scleaver I think this is done automatically in gulp file, I will have a look if I can tweak this, and ignore the [dir=ltr], nothing but I will give a link that shared by @sebastienros which shows that this approach is suitable to support two direction

**Comment by deanmarcussen** [comment]
Seth @hishamco is right this is done by a gulp file task which adds the [dir] etc attributes automatically to anything that is direction related.

So the admin theme is based on bootstrap sass and all of the [dir] is actually being added to standard bootstrap sass.

The approach I use to customise the resulting css for the admin is to import the admin sass in the parent admin theme, add some custom sass in afterwards, and use the Orchard Core `gulpfile.js` with the 'assets.json' and you can either choose to generate rtl or not `"generateRTL":  true,`

That works well if you're working of git/dev.

If you're using nuget the other approach (rather than copying the admin sass files over) is probably to write your admin as sass and generate it with the Orchard Core `gulpfile.js` in RTL, and you should be able to write your sass without thinking about [dir] and just rely on the gulp task to auto generate.

For added ease just import the bootstrap variables as well and modify those, without having to touch the underlying sass. (caption the example you give above, is a bootstrap class, controlled by its variables)

**Comment by hishamco** [comment]
Thanks @deanmarcussen I really forgot that I created a flag `generateRTL` which allow us to enable/disable RTL classes
