### ISSUE TITLE
init exception

### ISSUE THREAD

**Issue by kiventwang** [OrchardCMS/OrchardCore#4153]
I create a module and the web application refence it, when I run the application project I got a excetption that -->An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'OrchardCore.Settings.ISiteService' while attempting to activate 'OrchardCore.HomeRoute.HomeRouteMiddleware'.
what can I do

**Comment by jtkech** [comment]
The Homeroute feature would need a feature that manage the Homeroute settings. The Autoroute feature does this but another feature could do this so here we don't define an explicit dependency.

Then, to manage the Homeroute settings, the Autoroute feature needs a feature that manage site settings as the `OC.Settings` do, and for the same reason here also without any explicit dependency.

**So, it seems that you are in a context where the Homeroute feature is enabled, and at least not the `OC.Settings` feature.**

Note: Here maybe better to have defined some dependencies so that some default implementations would be there, then other modules could override them. Maybe like this for historical reasons.

**Comment by kiventwang** [comment]
I According to Section (Adding a Menu Item to the Admin Navigation from a Module) of the document
(https://orchardcore.readthedocs.io/en/dev/docs/guides/add-admin-menu/) build the sample,but it is not run and shows the exception,I can't setting anything.
