### ISSUE TITLE
Consider moving the OpenIddict YesSql stores to a separate project

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#418]
https://github.com/OrchardCMS/Orchard2/issues/233#issuecomment-265261317

@jersiovic do you think it would be worth moving the YesSql to an "official" OpenIddict.YesSql package? If so, I'd like to include it in the upcoming beta2 release.

**Comment by jersiovic** [comment]
I think YesSQL still is evolving at least I'm not sure collections feature its on its final version (@sebastienros is who can give info related with that). So, if it evolves we will need you maintain it. Maybe it is better you wait till collections feature is on its final version. That's the only con I see. 
Related to pros, maybe someone is interested on using Openiddict with YesSQL instead of EF, and by the way this is good way of promoting the use of YesSQL by people not interested in Orchard.

**Comment by sebastienros** [comment]
Or it would make sense in order to be able to use something else than YesSql, in case you would only use the SaaS part of ORchard, meaning without CMS modules.

**Comment by jersiovic** [comment]
I see, but do we will need to replace current dependency on YesSql per sth more generic moving its interfaces like ISession to an abstractions package non related to YesSql? Or do you mean that those who want to be able to use something else should offer alternate implementations of YesSql interfaces?

**Comment by PinpointTownes** [comment]
> So, if it evolves we will need you maintain it.

I'm fine with that.

> Maybe it is better you wait till collections feature is on its final version.

@sebastienros do you have an approximate date for that? :smile:

**Comment by jersiovic** [comment]
@sebastienros I said that I believe collections in yessql are not on its final version and when it will be ready  it will impact on Orchard OpenId stores because of this issue: https://github.com/OrchardCMS/Orchard2/issues/233 there you say you wanted to change YesSql to use configuration to set which class uses which collection, but right now we need to use a using statement.

**Comment by PinpointTownes** [comment]
Closing as I think it's more flexible to keep the YesSql stores in the OC source.
