### ISSUE TITLE
Make The Admin UI mobile friendly

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4186]
I just open this as an issue tracker for all the issues related to the mobile views bugs

- [ ] Login
- [ ] Dashboard
- [x] Blog #2885
- [ ] Assets #4204
- [ ] Navigation Bar #3964
- [x] Content Items #4198
- [ ] Content Types #4216
- [ ] Content Parts #4217
- [ ] Menu #5449

I will keep update this list as long as I test the entire pages in The Admin theme

**Comment by jptissot** [comment]
I'm not sure if here is the right place to put this.. but in IE 11, the Admin menu does not open or close child menu's making it unusable.

**Comment by hishamco** [comment]
I suggest to file a new issue for that, and let this for UI mobile view if only

**Comment by Skrypt** [comment]
I don't think we should try to target IE 11 as Bootstrap 4 doesn't.

**Comment by MichaelPetrinolis** [comment]
Since bs4 supports ie10/11, OC should also support them.
Maybe we could limit support for IE11/Edge. There are many
Enterprises that have prerequisite support of Internet Explorer

**Comment by jptissot** [comment]
I found the issue and it's being fixed. It's because we were using template littlerals and arrow functions in out scripts which were not being transpiled.

**Comment by hishamco** [comment]
> It's because we were using template littlerals and arrow functions in out scripts which were not being transpiled.

Hope it supported ASAP :)

**Comment by Skrypt** [comment]
BS4 support of IE11 has been added lately because it was not supporting anything else than Edge a while ago. I still think that this is a small niche of users. Maybe a lot more than what it should be and instead we should encourage people to move away from Internet Explorer. There is absolutely no understandable reason why an Entreprise couldn't advise their employees to use Edge instead.

https://www.engadget.com/2019/02/08/microsoft-internet-explorer-technical-debt/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAJf2iWe8xucFxgfgoq2991balmFt62LR6wzpp-KM8uTHvmAp8ih3OYCKZOtaSTLPslPpkwgUCREYm9XKY71yhHbj996-tyLMLj-s74vvtfQSkKxfF5YwlxwtCeg-79G7tRfycoFDbKSMrfyzTm-vHyKH58Pth6kWTOFYI-c1qaLb

**Comment by matiasmolleja** [comment]
The assets was adapted for mobile in #2576. I did not close #2885 because that issue was about other pages too.
I think you could mark the "assets" checkbox.

**Comment by hishamco** [comment]
@matiasmolleja please have a look to #4204

**Comment by hishamco** [comment]
A lot of UI changes are happen since then, so time to close
