### ISSUE TITLE
 placement.json seems not working

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#4202]
`{
  "NumericField": [
    {

      "place": "Content:100000"
    },

    {
      "display-type": "Detail",
      "differentiator": "CarouselWithContentPicker-Height",
      "place": "Content:-"
    },
    {
      "display-type": "Detail",
      "differentiator": "customType-Height",
      "place": "-"
    },
    {
      "display-type": "Detail",
      "differentiator": "customType-Height",
      "place": ""
    }
  ],
  "BooleanField": [
    {

      "place": "Content:-"
    },
    {

      "place": "-"
    },
    {

      "place": ""
    }
   
  ]
}`
tried many ways(above), and Content:100000 did not move that to the end.

**Comment by hishamco** [comment]
Did you check our docs?

**Comment by hishamco** [comment]
Did you check our docs?

**Comment by infofromca** [comment]
doc is too simple.
for ex, there is no explation about hiding a shape

**Comment by hishamco** [comment]
Have a look to this PR #4154 we already hide a shape there

**Comment by deanmarcussen** [comment]
It is hard to see exactly what you are trying to do because you have so many examples that you try!

But this example works
```
{
  "NumericField": [
    {
      "place": "Content:20"
    }
  ]
}
``` 

to move a field after a markdown body

To remove a field the syntax is

```
{
  "NumericField": [
    {
      "place": "-"
    }
  ]
}
``` 

And to specify other parameters such as display type or differentiators or match on content types you would use like this (in the same block as your placement rule)
```
{
  "NumericField": [
    {
      "place": "-",
      "displayType": "Detail"
    }
  ]
}
``` 

Does that help?

**Comment by infofromca** [comment]
thanks
this time I used:
`{
  "NumericField": [
    {

      "place": "-"
    }

  
  ],
  "BooleanField": [
   
    {

      "place": "-"
    }
  
  ]
}`

but no useful, it is the same.
now the only thing I can think is that I created this placement.json after I created the page.
is it influenced?
I will delete the db , and try again in near future.
![placement_no_hide](https://user-images.githubusercontent.com/297675/64575656-e6809700-d342-11e9-8bdf-ef89edd05d48.png)

**Comment by infofromca** [comment]
created a brand new site. keep 
![placement_no_hide2](https://user-images.githubusercontent.com/297675/64576885-90aeed80-d348-11e9-97c6-253527a2d2a7.png)
the same

**Comment by infofromca** [comment]
i set breakpoints ,
![5_features](https://user-images.githubusercontent.com/297675/64580405-33b93480-d354-11e9-9b69-b801ea34cb39.png)
strangely, there ronly 5 features:
resources
feeds
homeRoute
indexing
scripting
and for all of them, the  exists are false, so did not go into placement code.
I used blog recipe this time.

**Comment by deanmarcussen** [comment]
In which location did you put your `placement.json` file?

It should be placed in the root of your theme for what you are trying to do.

**Comment by infofromca** [comment]
root of my module

**Comment by infofromca** [comment]
also tried the root of oc.resources, contentenFields

**Comment by infofromca** [comment]
just tried putting it under the root of TheBlogTheme, and OrchardCore.Cms.Web , not helpful.
and putting in this two locations is strange for me, and O1 is not like it.

**Comment by jtkech** [comment]
- What theme are you using? E.g with `TheBlogTheme` when displaying an article, the shape system find the `Content-Article.liquid` template, but then, see in this template file, e.g the `Subtitle` text field is explicitly rendered. So, at this point the shape system is "overridden" and the placement strategies are not used.

- So here i have setup a blog and then i switched to `TheTheme` theme, then i put the following `placement.json` under `TheTheme` project, and then when going to an `Article` page the `Subtitle` text field was not rendered.

      {
        "TextField": [
          {
            "place": "-"
          }
        ]
      }

- When adding / removing a `placement.json` under a project, don't forget to redo a full rebuild on it. Then check in your project file that no item groups have been added related to this file. If so, remove them, otherwise the json file might not be embedded in the related module / theme assembly, and then not recognized.

**Comment by infofromca** [comment]
> when displaying an article, the shape system find the Content-Article.liquid template, but then, see in this template file, e.g the Subtitle text field is explicitly rendered.

maybe this is the reason.
For my situation, the fields  were explicitly rendered in the **ContentPickerField**.
by the way, I used Agency, Blog themes.

**Comment by sebastienros** [comment]
I assume the reason has been found.
