### ISSUE TITLE
should be only one resource

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#4203]
I added  <style asp-name="bootstrap"></style>
    <script asp-name="bootstrap" at="Foot"></script>
to my module.
but there is already link of bootstrap in  the **some** themes, and it gave me two links.
it should be only one.

**Comment by hishamco** [comment]
Styles & scripts are added once

**Comment by hishamco** [comment]
Styles & scripts are added once

**Comment by infofromca** [comment]
if there is already there , should avoid adding again

**Comment by hishamco** [comment]
I'm still not how this happen /cc @deanmarcussen

**Comment by deanmarcussen** [comment]
Ok, so if you are using the default sample themes, then yes you will have this experience.

In `TheBlogTheme` (for example) we use generated bootstrap files from the theme/wwwroot/vender/styles folder
e.g. in `layout.liquid`
```
    <!-- Bootstrap core CSS -->
    {% style src:"~/TheBlogTheme/vendor/bootstrap/css/bootstrap.min.css", debug_src:"~/TheBlogTheme/vendor/bootstrap/css/bootstrap.css" %}
```

If you have used `<style asp-name="bootstrap"></style>` in a module, and then used a sample theme then yes, you will get two copies linked in. Because they are different.

Me, I don't see this as an issue particularly, the sample themes are samples, and if you are creating modules, I'd imagine you'll be creating a theme as well.

In which case you will use `<style asp-name="bootstrap"></style>` in the layout of the theme, and could use `<style depends-on="bootstrap"></style>` in your module, if you feel the need to put a dependancy in, or a `<style depends-on="your-theme-css"></style>`

Let me know if that all makes sense

**Comment by infofromca** [comment]
This time, I used TheBlogTheme:
![dup_css](https://user-images.githubusercontent.com/297675/64606859-3a1bd080-d395-11e9-9950-c6aaa9853d85.png)
As I remember, O1 can deal with this situation smoothly.

**Comment by infofromca** [comment]
> In which case you will use <style asp-name="bootstrap"></style> in the layout of the theme, and could use <style depends-on="bootstrap"></style> in your module, if you feel the need to put a dependancy in, or a <style depends-on="your-theme-css"></style>

sorry, I do not think so. because after I code my module, I should not change it again. and in future, I will use a theme in which there is no bootstrap, for ex, Foundation, material....

**Comment by infofromca** [comment]
> if you are creating modules, I'd imagine you'll be creating a theme as well.

I think module should be independent with any other modules, themes. in this way, we can show the power of decouple in OC. I remember O1 did that well.

**Comment by sebastienros** [comment]
> This time, I used TheBlogTheme:

Please don't use these themes is your components are trying to inject bootstrap as a resource. Create your own, and use the resources instead of embedding them in a single css/js like we do in these themes.

**Comment by sebastienros** [comment]
This is also why our front-end components usually don't call 'require' on the resources, or use any specific tagging.
