### ISSUE TITLE
Move Template under Theme Menu

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4288]
I suggest we move the Templates menu item under the themes menu in the admin.

**Comment by deanmarcussen** [comment]
What about actually at top level like Workflows with a nice icon (but still down the bottom of the list near / above the themes menu item?

**Comment by jptissot** [comment]
I would probably also remove the Themes page under the Configuration menu as it's used to configure which themes are enabled. 
Then, we could move the Templates menu item out of configuration and replace the Theme menu.

**Comment by jptissot** [comment]
I would also like to be able to easily modify the templates of a ContentType while on the edit ContentType page.

**Comment by sebastienros** [comment]
When we designed the menu, we wanted something like 5-6 root menu items, and everything was supposed to find its place in these ... be careful.

**Comment by sebastienros** [comment]
Also there is a link in the ContentType definition page to go directly to its template (same for parts).

**Comment by jptissot** [comment]
I think we should have a "UI" root menu and move the Active Theme, Templates, Layers under this menu. I find the different settings are a bit scattered especially since all those are related to the frontend .

**Comment by agriffard** [comment]
We should consider some changes to the Themes admin menu.

Here are my suggestions:

- Move some sub menus under it. Ex: Layers (Widgets), Templates, and may be admin menu, admin templates.
- Rename 'Active themes' to 'Themes'.
- Find a new name like 'UI', 'Appearance', 'Customize' or 'Design'.
- Replace the camera icon by another one.

**Comment by agriffard** [comment]
In fact, I would even go further.

My choice would be to stick as much as possible to the new doc structure I am suggesting so the main admin menus could be:

- New (May be move it to Content)
- Content
  - Content Items
  - Content Definition
- Media (main menu or sub menu of Content)
- Customize
  - Themes
  - Templates
  - Widgets
- Configuration
  - Import/Export
  - Recipes
  - Tenants
- Settings (moved from Configuration)
  - General
  - ... all settings
  - Facebook, Google, Twitter (which currently are main links)
- Security (moved from Configuration)
  - Users
  - Roles
  - Permissions
  - Open Id
- Search
  - Indexing (Instead of Site, moved from Configuration)
  - Queries
- Workflows

**Comment by hishamco** [comment]
`Design` or `Appearance` is better than `Display`

+1 for `Media`, I already filed an issue to replace `Asserts` to `Media`

IMHO `Settings` is very important but it's confusing little bit when it come with `Configuration`

**Comment by muzzi-w** [comment]
Also...

Instead of 'Security', maybe 'Accounts' or 'Authentication'

Separate 'Content' as this refers to content items, and 'Content Definitions' as this is creating a definition or type, not actually an item. 

Ultimately should be as intuitive as possible for new users.

**Comment by agriffard** [comment]
@muzzi-w 

Security will also contain settings like HTTPS, Recaptcha and features like Open Id so I think it is a more generic and appropriate term for this section.

I put Content Definition in Content on purpose because that is clearly associated to content management and to reduce the number of main sections. This is the kind of menu that a user with permissions (Administrator) uses a lot at the beginning of the site. A user will only a Content Edition role won't even see this menu.
