### ISSUE TITLE
Error constructing ShellDescriptor when adding WithTenants()

### ISSUE THREAD

**Issue by laguer71** [OrchardCMS/OrchardCore#4321]
I tried a sample multitenant demo from Sipke Schoostra with the latest bits for Beta 3, and got this  exception
System.AggregateException
HResult=0x80131500
Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: OrchardCore.Environment.Shell.Descriptor.IShellDescriptorManager Lifetime: Scoped ImplementationType: OrchardCore.Environment.Shell.Descriptor.Settings.ConfiguredFeaturesShellDescriptorManager': Unable to resolve service for type 'OrchardCore.Environment.Shell.Configuration.IShellConfiguration' while attempting to activate 'OrchardCore.Environment.Shell.Descriptor.Settings.ConfiguredFeaturesShellDescriptorManager'.)
Source=Microsoft.Extensions.DependencyInjection
StackTrace:
at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable1 serviceDescriptors, ServiceProviderOptions options) at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options) at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder) at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter1.CreateServiceProvider(Object containerBuilder)
at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
at Microsoft.Extensions.Hosting.HostBuilder.Build()
at MultiTenantApp.Program.Main(String[] args) in C:\Users\lague\source\repos\MultiTenantApp\Program.cs:line 17

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: OrchardCore.Environment.Shell.Descriptor.IShellDescriptorManager Lifetime: Scoped ImplementationType: OrchardCore.Environment.Shell.Descriptor.Settings.ConfiguredFeaturesShellDescriptorManager': Unable to resolve service for type 'OrchardCore.Environment.Shell.Configuration.IShellConfiguration' while attempting to activate 'OrchardCore.Environment.Shell.Descriptor.Settings.ConfiguredFeaturesShellDescriptorManager'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'OrchardCore.Environment.Shell.Configuration.IShellConfiguration' while attempting to activate 'OrchardCore.Environment.Shell.Descriptor.Settings.ConfiguredFeaturesShellDescriptorManager'.

The source cad be found at

https://github.com/laguer71/MultiTenantApp

**Comment by jtkech** [comment]
I fixed the `ConfiguredFeaturesShellDescriptorManager` registration, i will commit it.

When using `WithTenants()`, we don't use anymore a root `tenants.json` but e.g an `appsettings.json`, a root one or just under `App_Data`, or any other regular config source as env variables, cmd line args and so on.

Anyway, the preconfigured tenants need to be under an `OrchardCore` main section.

Hmm, didn't tried and i removed my testing application, but i think it also works if you use the new `tenants.json` that we use under `App_Data` but here without the `OrchadCore` main section. As you tried to do if i remember correctly, but it was not working because of the same bad registration.
