### ISSUE TITLE
Can't login without https since Core3

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4331]
Is it just me, or can you not login without https since core3 when using `dotnet run`

Is that something we have done, or maybe core 3 has done?

Do we just need to update the `.vsconfig` to reflect the https port and document somewhere?

**Comment by jptissot** [comment]
Same for me. I mentionned it in the Core 3.0 update thread.

**Comment by hishamco** [comment]
Related & unrelated, after updating `.vsconfig` I'm not able to run `dotnet run` in VS Code it takes long time without echo anything, any idea

**Comment by hishamco** [comment]
FYI I'm able to run both http & https using VS Code, is this related to VS 2019?

**Comment by jtkech** [comment]
I tried, it also works under VS2019 with `https://localhost:44300` and `http://localhost:2918`.

With `dotnet bin/debug/netcoreapp3.0/orchardcore.cms.web.dll` it works for `https://localhost:5001`, then it works with `http://localhost:5000`, login included, but you have to restart the application otherwise it doesn't work at all, the 1st front end page is not allowed.

That said, about login i had a similar issue where i couldn't login, i fixed the issue by using a new user name and password because, in my case, Chrome was checking that this user name / password were used too many times.

**Comment by jtkech** [comment]
Oh, i tried with `dotnet` but not with `dotnet run`, i will

**Comment by jtkech** [comment]
Don't use dotnet run, it's too long, i'm waiting, use in place `dotnet theDll.dll`.

**Comment by jtkech** [comment]
Okay, it also works on my side with `dotnet run`.

**Comment by hishamco** [comment]
So what's the action should be take about this one

**Comment by deanmarcussen** [comment]
@jtkech Ok, cool, I win best user id10t error for the month ;)

Totally related to Chrome user name being used too many times.

New user name and problem goes away

**Comment by deanmarcussen** [comment]
> So what's the action should be take about this one

No action, no bug. 

Clear your Chrome cache, or don't reuse the same username over and over again when setting up test tenants.

**Comment by jtkech** [comment]
Okay cool, @Skrypt also had the same issue and he helped me to fix it on skipe.
