### ISSUE TITLE
Workflows and Forms : Accessing Form Data for submitting POST HTTP request

### ISSUE THREAD

**Issue by ninad-k** [OrchardCMS/OrchardCore#4332]
Created a ContactUs form with the help of the [link](https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Forms)

I want to submit the form and store the values in the SQL Server Database so I created Web API with Post method and I tried to add HTTP Request Task in the workflow but I am not able to pass any form value through Body but if I pass simple static string then the record is getting inserted.

![image](https://user-images.githubusercontent.com/47207171/65239906-a2895100-dafd-11e9-9300-1875b72580fd.png)

I want to update the highlighted line with the liquid query so that I can pass the form data to my Web API.

My Workflow:
![image](https://user-images.githubusercontent.com/47207171/65238766-05c5b400-dafb-11e9-9ebb-886a2afd9da1.png)

Could someone tell me whether it is possible in beta version or I have to wait for the final version? Also is there any document or link which guide me step by step to submit form data to the database.

**Comment by hishamco** [comment]
@jptissot could you please have a look to this

**Comment by sfmskywalker** [comment]
Are you passing a JSON content body or URL encoded form values?

**Comment by ninad-k** [comment]
JSON content body. Below is my Web API structure.
 
![image](https://user-images.githubusercontent.com/47207171/65262810-c31ad080-db28-11e9-9b43-1d13097f75fc.png)

**Comment by sfmskywalker** [comment]
I suspect that is the issue. You are validating form values, which are expected to be sent using the `application/x-www-form-urlencoded` where the content body is expected to be like 

```
name=asdasdasdas&email=string1&phone=string1&message=string1
```

Which will be parsed into the `Request.Form` collection, which is used by the [ValidateFormFieldTask](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Forms/Workflows/Activities/ValidateFormFieldTask.cs) activity.

Since you're posting JSON content, it won't be parsed into `Request.Form`, which means any activity expecting FORM content will fail.

Since you're posting JSON, you could simply validate the payload using a [ScriptTask](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Workflows/Activities/ScriptTask.cs) using some JavaScript, and return the appropriate outcome.

Alternatively, you could write a custom activity that is similar to `ValidateFormFieldTask`, but for example takes an expression that evaluates to a value to be validated.
