### ISSUE TITLE
Assets pipeline issues

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4338]
As @deanmarcussen mentionned [here ](https://github.com/OrchardCMS/OrchardCore/pull/4336#pullrequestreview-290803707) I unknowingly included the wrong version of popper.js in TheAdmin.js script by using the assets pipeline. Which let me to investigate as to why this happenned as I had done a clean `npm install `and `gulp build`.

I found out why `popper.js@1.15` is in our [package-lock.json](https://github.com/OrchardCMS/OrchardCore/blob/dev/package-lock.json#L5282). The @types/bootstrap@4.3.1 package has a dependency of `popper.js "^1.14.1"` which automatically resolves `popper.js 1.15` because of the `^` 

Thankfully bootstrap seems to have upgraded their master branch with [popper 1.15](https://github.com/twbs/bootstrap/blob/master/package.json#L87). However, the fact that this issue occurred makes me thing we should rethink how assets are installed and used in the different Assets.json files.

Installing npm dependencies at the root is risky, especially when including package version from multiple sub package.json files like we do [here](https://github.com/OrchardCMS/OrchardCore/blob/dev/package.json#L37).
This has the potential to install "conflicting" version of packages and include the wrong version of the package in any built asset file.

**Example:**

1. deleted node_modules, ran `npm install`
2. ran `npm run rebuild` which calls `gulp rebuild`
3. Looked at modified assets, saw that popper.js and TheAdmin.js both were updated to version 1.15 of popper.js even if their package.json specified 1.14.7, all because the package `@types/bootstrap` includes `"popper.js": "^1.14.1"`  as part of its dependencies.

**Another test:**
1. Delete node_modules
2. Removed orchardcore.workflows as a dependency of the root package.json file since 
```
  "dependencies": {
    "orchardcore.apis.graphql": "file:src/OrchardCore.Modules/OrchardCore.Apis.GraphQL",
    "orchardcore.resources": "file:src/OrchardCore.Modules/OrchardCore.Resources",
    "orchardcore.setup": "file:src/OrchardCore.Modules/OrchardCore.Setup",
    "orchardcore.theadmin": "file:src/OrchardCore.Themes/TheAdmin"
  }
```
3. Run `npm install`
4. Run `npm run rebuild`
5. Error occurred because popper.js could not be found under node_modules. Although it clearly should have been since it's a dependency of orchardcore.resources.

**Another test with yarn:**

1. Undid all previous changes, deleted node_modules and package-lock.json
2. Ran `yarn install`
3. Run `npm run rebuild`
4. Popper.js shows the right version of 1.14.7 

I am not convinced that yarn solves the issue completely but it at least included the right version of popper.js in the built files. I still wonder if `@types/bootstrap` had the version ^1.15 in their dependencies if yarn would have included the wrong version. 

All this to say that we need to rethink how assets are built, especially when using npm as any dependency we include that has a dependency we rely on has the potential to break the version we want to include as part of our source. 

**A solution**

1. Switch to yarn. From personal experience, I can say that I have not seen as many package version resolution issues with yarn. I have seen issues like this with npm quite a few times.

**Another solution**

1. From the root package.json, do not reference the child package.json files like this:
```
  "dependencies": {
    "orchardcore.workflows": "file:src/OrchardCore.Modules/OrchardCore.Workflows",
    "orchardcore.apis.graphql": "file:src/OrchardCore.Modules/OrchardCore.Apis.GraphQL",
    "orchardcore.resources": "file:src/OrchardCore.Modules/OrchardCore.Resources",
    "orchardcore.setup": "file:src/OrchardCore.Modules/OrchardCore.Setup",
    "orchardcore.theadmin": "file:src/OrchardCore.Themes/TheAdmin"
  }
```
Instead, write a script that will cd into each folder an run npm install for each of the folders listed above.

Then, modify the `Assets.json` file of projects so that the js files are copied from the local node_modules under each project instead of targeting the node_modules folder located at the root of the solution. 

/CC @deanmarcussen @agriffard

**Comment by jptissot** [comment]
I just did another test, doing npm install from the root already installs node_modules in each referenced dependency so a quick fix would probably be to just modify the Assets.json files to reference these instead of targeting the root node_modules.

**Comment by jptissot** [comment]
We could also investigate newer assets build tools like Rollup.js or Webpack.

**Comment by deanmarcussen** [comment]
I completely agree @jptissot the problem exists, because of sub-packages, which we have no control over how they choose to reference dependencies.

Also, having it how it is, makes it difficult to allow different versions of dependencies, for different projects. 

For example, I have no trouble with popper being upgraded in TheAdmin, (it's a dot release, so shouldn't matter) but that will then likely cause it to get upgraded in `Resources` at some point as well, at which point it is out of sync with the bootstrap we provide via either local or cdn, and so on and so forth.

And more annoyingly, different installs on different machines **even with the same version of npm** seem to produce different package resolution (as I remember from the time I tried to understand this)

I don't have much experience with yarn, but if you can make it work better than npm at version resolution, I'd be all for it.

> Instead, write a script that will cd into each folder an run npm install for each of the folders listed above.

However I think this second solution, of making the child package.json files essentially independant of the root, and referencing them in the assets.json from the local node_modules folder instead of the root, might give more flexibility. 
@Skrypt you had the same issue / need when the bootstrap upgrade happened I think?
I did, and it forced me to update my bootstrap theme version, at a time when I needed the latest dev, but didn't really have time to go through that upgrade process.

Or consider webpack or other tools. Again if you wanted to experiment I'm open to the idea, but it's not my area of expertise.

Noting that we're already using webpack for GraphQl, so if that became more part of the pipeline so much the better (IMHO)

Lastly, and unrelated, but I noticed you removing the ES6 lambda's for IE support. 
Should we consider something like gulp-babel to do some transpilation so that we could support it in js (obviously not in razor)

Ultimately, it should not need to be this hard to produce some javascript files consistently, so anything we can do to make it easier is good I think.

**Comment by Skrypt** [comment]
The advantages of the gulp pipeline is that it is really highly customizable. The issues you are referring to are related to the fact that in the latest changes we added child packages references. Should we move to Webpack instead of npm ... yes. I made some tests with Webpack on my webpack_hmr branch https://github.com/OrchardCMS/OrchardCore/tree/skrypt/webpack-hmr

**Comment by Skrypt** [comment]
At the same time Webpack has the same kind of approach with submodules where it uses the same main shared node_modules folder. So, here, the issue is maybe not related with gulp/npm. If one submodule needs to have a different dependency then we should not make it a submodule of the main package. But I'm guessing that the intent to use submodules was to be able to also use the same dependency versions throughout the entire build pipeline to be able to point on places where it needs to be updated. Webpack offers at least a dependency graph, would be worth at least to have a prototype to see if it would fix this issue.

**Comment by jptissot** [comment]
Thing is.. Assets.json defines where the assets gets pulled from. We should not install those dependencies at the root but within each module. And the Assets.json should reference local node_modules. We could easily write a script that searches the solution for all package.json files and run npm install in those folders. Then, the build pipeline will just work because it will use local version of dependencies.

**Comment by deanmarcussen** [comment]
> Thing is.. Assets.json defines where the assets gets pulled from. We should not install those dependencies at the root but within each module. And the Assets.json should reference local node_modules

I agree, the conflict we currently have on dev is probably related to the upgrade to jquery (I think - not totally sure).
Which is a good thing to do, but the workflows modules uses jquery typings which has not been updated yet.

So it seems like when npm can't agree on which version it should install, it just drops the install to the root node_modules from that module. In this current case, it's the OrchardCore.Resources that misses out.

From googling other peoples solutions seem to be a script that does an install to a local node_modules for each package.

@jptissot Seems like you have more experience with this, would you be willing to take it on?

**Comment by jptissot** [comment]
Yeah, I can have a look after 1.0 ships.
