### ISSUE TITLE
Embedding Orchard Module into custom project

### ISSUE THREAD

**Issue by nexawo** [OrchardCMS/OrchardCore#4369]
I want to add a module from OrchardCms and modify that module according to my scenario but the problem is when I give reference of Module into my project then some functionality of Nuget Package
stops working. Below I am adding the link of source of my project https://github.com/sudurrani/OrchardCoreWithModules

**Comment by hishamco** [comment]
> but the problem is when I give reference of Module into my project then some functionality of Nuget Package stops working

What is the functionality that had been stopped?

**Comment by nexawo** [comment]
> > but the problem is when I give reference of Module into my project then some functionality of Nuget Package stops working
> 
> What is the functionality that had been stopped?

OrchardCore.Application.Targets functionality get removes when I add references for OrchardCore.Setup

**Comment by nexawo** [comment]
> > > but the problem is when I give reference of Module into my project then some functionality of Nuget Package stops working
> > 
> > 
> > What is the functionality that had been stopped?
> 
> OrchardCore.Application.Targets functionality get removes when I add references for OrchardCore.Setup

You can download the project from the given link and see it by yourself add the reference of OrchardCore.Setup and you will see the above mention issue

**Comment by jtkech** [comment]
i'll try to take a look tomorrow

**Comment by jtkech** [comment]
Okay i found the issue

- First reference `OC.Module.Targets` directly and only from your setup module.

- When referencing `OC.Application.Mvc.Targets`, you don't need to reference `OC.Application.Targets`.

- In your setup module project file specify a version for the additional aspnetcore packages, i used `2.2.0` because, as you can see in the dependencies of the projects, e.g `OC.Module.Targets` uses the same version.

- But the main issue was that you are using a project named `OrchardCore`, after renaming it by `OrchardCoreTest` (folder and project file), all was restoring and building.

**Comment by nexawo** [comment]
> Okay i found the issue
> 
> * First reference `OC.Module.Targets` directly and only from your setup module.
> * When referencing `OC.Application.Mvc.Targets`, you don't need to reference `OC.Application.Targets`.
> * In your setup module project file specify a version for the additional aspnetcore packages, i used `2.2.0` because, as you can see in the dependencies of the projects, e.g `OC.Module.Targets` uses the same version.
> * But the main issue was that you are using a project named `OrchardCore`, after renaming it by `OrchardCoreTest` (folder and project file), all was restoring and building.

 I tried to do as you said to change the name of orchardCore to orchardCore test and remove the OC.Application.Targets package but still it's not working can you commit these setting on the above-given link. Because I am a newbie to asp.net. Thanks in advance.

**Comment by jtkech** [comment]
I didn't forget you, i will help you as i have time, trust me we all are the newbie of something ;)

> but still it's not working

I assume here you just mean that you can't restore and / or build your app, because i just did a build but didn't run your app

> can you commit these setting on the above-given link

Hmm, not sure i can if i don't have the permissions, i will try it after having deleting all bin and obj folder and restoring your app_data folder. You would need to use a `.gitignore` file so that a commit will not take into account these files, as an example see this file in the root of our repo.

**Comment by jtkech** [comment]
I was not able to push my changes you would have to give me the permissions

**Comment by nexawo** [comment]
> was not able to push my changes you would have to give me the permissions

Thank you, Brother, for your help, I am done with this issue and it working as I follow your given points above. Thank You
