### ISSUE TITLE
Cannot authorize with "authorization code flow" in netcore 3 dev version

### ISSUE THREAD

**Issue by Tsjerno** [OrchardCMS/OrchardCore#4399]
In the latest dev version I cannot login (get access_token) with the authorization code flow.
In an earlier version(4months ago) on core 2 it works well.
Login screen pops up, Allow scopes screen pops up.
Then I get an AmbiguousMatchException

An unhandled exception occurred while processing the request.
AmbiguousMatchException: The request matched multiple endpoints. Matches: 

OrchardCore.OpenId.Controllers.AccessController.AuthorizeAccept (OrchardCore.OpenId)
OrchardCore.OpenId.Controllers.AccessController.Authorize (OrchardCore.OpenId)

I'm using postman. 
Reproduction:
 - Create a new site
 - Enable feature open id server
 - Configure rolling tokens and JWT
 - Add an confidential application/client 
Use postman to get a new access token
- grant type authorization code
- auth url: https://localhost:44300/connect/authorize
- token url: https://localhost:44300/connect/token
- client id and secret
- scope: offline_access

@PinpointTownes  Any idea?

**Comment by PinpointTownes** [comment]
@jtkech could that be caused by a regression in ASP.NET Core 3.0 or a bug in the new matcher behind `FormValueRequiredAttribute`?

**Comment by jtkech** [comment]
I will take a look this night but not confortable with openid things, i mean to be able to repro ;)

**Comment by jtkech** [comment]
As i remember for 2 actions having the same route endpoint pattern, one being decorate with `[HttpPost]`, the other one not decorated (meaning `HttpGet` by default), i needed to explicitly decorate the 2nd action with `[HttpGet]` to avoid the endpoint conflicts.

Here i saw that `AuthorizeAccept` is decorated with `HttpPost` and `Authorize` with both, here i assume we can't remove the `HttpPost` one for the 2nd action to make the distinction.

But the issue would mean that both actions have the same route pattern. Is it the case? Oh maybe yes because the second one has `[ActionName(nameof(Authorize))]`. Hmm, looking at the code i saw that we use `MapAreaControllerRoute` for one action and `settings.AuthorizationEndpointPath` for the pattern, but maybe both actions have the same pattern through the openId settings / config.

Okay, do both actions have the same route pattern? If so, is it required?

If so, maybe before the `FormValueRequiredAttribute` was making the distinction. As it is implemented currently with new endpoint policies, if a value is required for a given endpoint but not there the endpoint is invalidated, otherwise not. Hmm, but if the value is there how could we invalidate the other one that don't require this value and if it has the same route pattern?

Maybe a new `FormValueForbidden` attribute ;) Will see, i will 1st wait for your feedback.

**Comment by jtkech** [comment]
Okay, i could repro the same behavior in the `OC.Contents AdminController`


    [HttpPost,HttpGet] // I ADDED THIS LINE
    public async Task<IActionResult> Edit(string contentItemId)

    [HttpPost, ActionName("Edit")]
    [FormValueRequired("submit.Save")]
    public Task<IActionResult> EditPOST(string contentItemId, [Bind(Prefix = "submit.Save")] ...)

I think we can easily fix it with a simple `IEndpointComparerPolicy` as we did to make razor page having an higher precedence than controller view.

I'm doing a PR for this.

**Comment by ropstah** [comment]
A related issue occurs on `AccessController.Logout`. Actions `Logout` and `LogoutAccept` (via ActionName attribute) share a route. Both actions allow for POST and this can result in:

> AmbiguousMatchException: The request matched multiple endpoints. Matches: `OrchardCore.OpenId.Controllers.AccessController.Logout` (OrchardCore.OpenId) `OrchardCore.OpenId.Controllers.AccessController.LogoutAccept` (OrchardCore.OpenId)

To reproduce: 
 - enable openid
 - open SPA and login using implicit flow
 - logout via logout endpoint. 
 - confirm logout (shows error)

**Comment by sebastienros** [comment]
@ropstah would you be able to create a PR ? Or do you need some help to figure out the solution?

**Comment by kevinchalet** [comment]
It's weird, the `LogoutAccept` action is decorated with `[FormValueRequired("submit.Accept")]` 😭

**Comment by jtkech** [comment]
@ropstah

Which version do you use? Normally it has been fixed through #4415

**Comment by ropstah** [comment]
Ah ok I just looked at the code for the controller in `RC1` tag and `dev` branch and it seemed the same.

I'm using `RC1` so never mind :)

**Comment by rcedev** [comment]
When will this fix be merged to master?
