### ISSUE TITLE
Error with decoupled CMS with module

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4400]
![situation](https://user-images.githubusercontent.com/1761249/65628131-1f6e6c00-dfd1-11e9-8b0d-dc648723367b.png)

It is similar to this (https://github.com/OrchardCMS/OrchardCore/issues/4261#issuecomment-531217373) but I thought it's already fixed by https://github.com/OrchardCMS/OrchardCore/pull/4299.

**Comment by dodyg** [comment]
![module](https://user-images.githubusercontent.com/1761249/65628508-d9fe6e80-dfd1-11e9-97a8-0cbb056c71ec.png)


This is the offending module. If I disable it, it works.

**Comment by dodyg** [comment]
![config](https://user-images.githubusercontent.com/1761249/65628839-8c363600-dfd2-11e9-8234-412bdae2586e.png)

**Comment by jtkech** [comment]
Yes, to fix an mvc issue we overrided the `PageLoaderMatcherPolicy` razor page service.

But in your module you call `.AddMvc()` (the mvc one because you call it on a services collection) that calls again `.AddRazorPages()` that will register again the offending mvc `PageLoaderMatcherPolicy`.

**Comment by jtkech** [comment]
Try to remove `AddMvc()` from you module startup `ConfigureServices`

**Comment by sebastienros** [comment]
@jtkech then can you also explain how to 'configure' mvc in order to call `AddFluenvalidation` in this case ?

**Comment by jtkech** [comment]
Okay, because it acts on an `IMvcCoreBuilder`, i'll try to find a solution. Maybe we would need to overide the `PageLoaderMatcherPolicy` later in the pipeline.

Or provide an extension point to add things to our tenant `IMvcCoreBuilder`. I already thought about this by making an `OrchardCoreBuilder AddMvc(this OrchardCoreBuilder builder)` with an optional delegate acting on an `IMvcBuilder`, but right now we can't do that because our helper, in place of doing things itself by using our helpers and being able to use this delegate, it just registers our `OC.Mvc.Core` startup class that will do the things in its `ConfigureServices` that doesn't have a delegate parameter.

But i'll try to found the best compromise.

**Comment by jtkech** [comment]
But the best compromise would need to keep the ability to re-call `.AddMvc()` as done here.

Okay just found a so simple solution by using our app level `OrchardCoreBuilder.ConfigureServices` in our `OrchardCoreBuilder.AddMvc()`, just before registering our `OC.Mvc.Startup`, and with a high order so that it runs last to replace the offending policy , as i already did for another service.

I will do a PR.

**Comment by sebastienros** [comment]
Weird as the services in AddMvc should be called with `TryAddScoped` such that if something is already registered then it shouldn't replace it. Isn't this done in MVC for this service?

**Comment by jtkech** [comment]
`TryAddScoped` only check the service type and there are all registered a `MatcherPolicy`.

In fact for these services they use `TryAddEnumerable` that checks the implementation type (or instance type or factory return type). So registering our custom `PageLoaderMatcherPolicy` doesn't prevent another call to `AddMvc` to add the original `PageLoaderMatcherPolicy` that we want to override.
