### ISSUE TITLE
Images (Assets) Disappear with The Agency Theme

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#4419]
I've noticed this issue for a while when I use the agency theme on  a new website.   Initially all the images are there.   When I start editing the content they disappear.   Also if I go into the Admin and go to the folders the thumbnails are not there.   If I go look at the App_Data folder the image files are there.  I can type the url into the browser and it shows up fine.    It seems to happen after I add, edit, or delete items from the Landing Page.    The only images that appear to stay are the favicons and the header image.

https://www.dockaltech.com/media/portfolio/02-full.jpg

However when the home page is loaded nothing:

![image](https://user-images.githubusercontent.com/26497457/65793632-e4348000-e12b-11e9-8776-2200f6a3f02e.png)

![image](https://user-images.githubusercontent.com/26497457/65793821-57d68d00-e12c-11e9-8c04-d81950c5463b.png)

Check out https://www.dockaltech.com

**Comment by deanmarcussen** [comment]
You are having an error during resizing from the looks of it.

https://www.dockaltech.com/media/portfolio/02-full.jpg?&width=480&height=480&rmode=stretch

if you go to this you get a 500, which must mean there is an exception.

Do you have an `is-cache` folder of the `wwwroot` of your startup project?

But check your log files, ImageSharp will hopefully be saying something useful.

**Comment by mdockal** [comment]
> if you go to this you get a 500, which must mean there is an exception.

Yes I saw that if you removed the resizing parameters from the end of the URL it works.

> Do you have an is-cache folder of the wwwroot of your startup project?
Do you mean there has to be a folder called is-cache in wwwroot?   I just created one and it didn't seem to help.    

> But check your log files, ImageSharp will hopefully be saying something useful.
Ok I will check the log files.

**Comment by mdockal** [comment]
Running Ubuntu 18.04.3 LTS on AWS  with NGINX

Used the recommended settings for permissions for WordPress.   

sudo usermod -aG www-data ubuntu 

sudo chown -R www-data:www-data /var/aspnetcore

sudo chmod -R 774 /var/aspnetcore

Once I did this images started showing up.

 What are the recommended file permissions for Orchard Core for Linux?   Perhaps we need documentation for this?

**Comment by meodemsao** [comment]
i have log with image resize 

https://localhost:5001/v2/media/portfolio/04-full.jpg?&width=480&height=480&rmode=stretch

```
Microsoft.AspNetCore.Http.PathString..ctor(string value)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider.StartsWithBasePath(string subpath, out PathString rest)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider.GetFileInfo(string subpath)
Microsoft.Extensions.FileProviders.CompositeFileProvider.GetFileInfo(string subpath)
SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.GetAsync(string key)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, bool processRequest, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary<string, string> commands)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
OrchardCore.Diagnostics.DiagnosticsStartupFilter+<>c__DisplayClass3_0+<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by sebastienros** [comment]
What is the exception?

I tried on try.orchardproject.net, and it works. Also with agency:
https://try.orchardproject.net/0g1o2ql3/media/portfolio/04-full.jpg?&width=240&height=480&rmode=stretch

Please try different values that could make it fail

**Comment by meodemsao** [comment]
this execption when i use  orchard cms target rc 10004

**Comment by meodemsao** [comment]
But when i running in publish mode every image showing up

**Comment by sebastienros** [comment]
Can you paste the exception and its message? You only share the stack trace.

**Comment by jtkech** [comment]
There is an issue on ImageSharp (you can search it) related to the aspnetcore `StaticWebAssetsFileProvider` that is only used in dev mode.

As i remember, IS use the webroot file provider which may include (as a composite) this `StaticWebAssetsFileProvider`, and IS provide a path but that doesn't start with a `/`, so it fails because this path is converted to a `PathString` that needs a leading slash.

It doesn't fail with other providers as a physical file provider or our custom ones.

That said, the `StaticWebAssetsFileProvider` is used in dev mode and if you have some configuration providing some static asset paths. As i remember the config can provide a path to an xml file that can contains static assets paths, if no config, as i remember, this xml file is searched by defaiult in the executing directory.

So, search if you have such an xml file. Note: I saw that we have some under obj folders (as i remembe) but they are empty.

**Comment by jtkech** [comment]
[Here the issue](https://github.com/SixLabors/ImageSharp.Web/issues/78) on ImageSharp

**Comment by meodemsao** [comment]
@jtkech thanks

**Comment by meodemsao** [comment]
@sebastienros i am beginner with orchard, i use orchard cms target and only show stack trace in browser

**Comment by mdockal** [comment]
@meodemsao   I was not able to get the error logging to work.  However, I was able to fix the issue of images not showing up by changing the permissions of the website folders and files.   Did you see my post from above?

**Comment by meodemsao** [comment]
@mdockal in production mode every work well, i don't need add permission any folder
(i using docker)

My docker file

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Web/*.csproj ./Web/
COPY Theme/*.csproj ./Theme/
RUN dotnet restore

# copy everything else and build app
COPY Web/. ./Web/
COPY Theme/. ./Theme/
WORKDIR /app/Web
RUN dotnet publish -c Release -o out

# build release image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine AS runtime
WORKDIR /app
COPY --from=build /app/Web/out ./
ENTRYPOINT ["dotnet", "Web.dll"]
`

**Comment by meodemsao** [comment]
@mdockal maybe i don't run in stand aloneserver

**Comment by deanmarcussen** [comment]
@meodemsao @mdockal The issue here is as @jtkech posted regarding ImageSharp.

I am curious @meodemsao as to your configuration that has given you the `StaticWebAssetsFileProvider ` as when the ImageSharp issue was discovered I tried to see if I could get this `StaticWebAssetsFileProvider` loaded by default with Orchard Core to repro but was unable to.

The short term workaround is to replace the `env.WebRootFileProvider` with a standard `PhysicalFileProvider` from your startup project, when in development, until there is an ImageSharp fix.

Also noting @jtkech as we chatted about, I think this is unlikely to be an issue with any of the Orchard Core functionality, as I had a good look through when the ImageSharp issue came up and any place that we write to the `env.WebRoot` it is done with a new `PhysicalFileProvider`, rather than the default, which maybe the composite

**Comment by deanmarcussen** [comment]
PR in with ImageSharp for this https://github.com/SixLabors/ImageSharp.Web/pull/80

**Comment by deanmarcussen** [comment]
PR has been merged with ImageSharp.

When they release the next version we will update.

For anyone facing this issue, I believe Imagesharp run a myget feed

**Comment by agriffard** [comment]
Can this be closed @deanmarcussen ?

**Comment by deanmarcussen** [comment]
Fixed in ImageSharp.Web RC1
