### ISSUE TITLE
New Filters Bar UX

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4430]
This is a continuation for what @agriffard was did in #4358, this is can done in two ways:

**1- Drop Down Buttons**

Like what's I did now

![OrchardCore Filter](https://user-images.githubusercontent.com/3237266/65816151-f2a09b80-e200-11e9-93fe-31f0a6b1b55d.png)

- The user choose the filter from the dropdown and it will be the active filter for upcoming search
- Then the user can start typing in the search box and the result will show up immediately, using data binding with the content items list (client-side only)

Complexity:
- Requires an integration with other filters
- Pager & content items checkboxes should respect the current filter

**2- Drop Down Links**

Like what's shown in GitHub

![GitHub Filters](https://user-images.githubusercontent.com/3237266/65816158-051ad500-e201-11e9-944d-20f94dcdc6d8.png)

- The user choose the filter from the dropdown and the page will reload to apply this filter or
- Type filter syntax into the search box, something like: `author: admin`, `title: Orchard`
- Pager and other filter should works fine, while all the stuff are happening on the server

/cc @agriffard @sebastienros @Skrypt

**Comment by agriffard** [comment]
That is not exactly what I meant when I mentionned title and fulltext so let's clarify.

By default, search in title without specifying 'title:' and may be later, it will be interesting to add other qualifiers depending on what feature is enabled.
Ex: 
- Enable Indexing and configure some content types with full text search and then allow to filter with 'fulltext:'
- Enable Localization and then allow to filter on 'culture:'
- Enable Taxonomies or Tags when the feature is achieved and allow to filter on 'tags:' (equivalent of Labels on GitHub)

The 'is:' and the 'in:' qualifiers are useful on GitHub because they are easily understandable and used for different purposes. There could be:
- is:published, is:draft
- in:title, in:body to restrict the search

In Filters:
- Use the light background, not the secondary.
- In the dropdown, these are examples of filters that have to appear, not qualifiers.
Ex: Your items => 'author:agriffard', Published items => 'state:published', Draft items => 'state:draft', Current culture items => 'lang:fr' (depending on current Admin culture), ...

What I'd also like to see is a New dropdown button on the right, as in O1 (equivalent to 'New issue' on GitHub).

**Comment by hishamco** [comment]
What I mentioned above is the two ways that we can go with, plus mentioning the cons and pros for both

**Comment by hishamco** [comment]
> What I'd also like to see is a New dropdown button on the right, as in O1 (equivalent to 'New issue' on GitHub).

This is useful for the pages that requires new button

One point I want to mention that we need to use qualifier for what it should be like authors, title .. etc
because cultures, publishing status all are already there in the drop down list filters

**Comment by sebastienros** [comment]
Please comment on the exiting issue

**Comment by hishamco** [comment]
The intend of this is to help @agriffard on his PR, but while he already started on the filter bar it's fine to close this
