### ISSUE TITLE
Localization not working on publish

### ISSUE THREAD

**Issue by abdoneem** [OrchardCMS/OrchardCore#4438]
Localization not working on deploy and cant find po files when publish can any one help me
asp.net core

**Comment by hishamco** [comment]
@jtkech I think you working on this few days ago

**Comment by jtkech** [comment]
Would need more infos because localization files can be under a module and / or under a specific tenant folder and / or under the application.

What we did recently is that now app level files need to be under the app root `Localization` folder (as i remember it was `App_Data/Localization`). And there files are automatically copied when referencing the related translations packages. Note: The cms targets package reference all translations packages.

Just tried the app level localization files in a published context, it was working after enabling the localization feature.

**Comment by sebastienros** [comment]
Please provide some repro steps if the explanation that @jtkech gave you is not sufficient.
