### ISSUE TITLE
Error with decoupled CMS at Host

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4451]
This problem is similar to the fixed error at the module level (https://github.com/OrchardCMS/OrchardCore/issues/4400) 

![razor-time-2](https://user-images.githubusercontent.com/1761249/65947495-b9eb0700-e438-11e9-932a-64e8c8a81959.png)

Add `services.AddMvc()` at the host level breaks the system. 

```
  services.AddMvc().AddRazorRuntimeCompilation();
```

Above code works when it is registered at the Module.Startup but it will break when it is called at the host level.

![razor-time](https://user-images.githubusercontent.com/1761249/65947529-c66f5f80-e438-11e9-9618-87c54182f21b.png)

**Comment by dodyg** [comment]
This will impact people creating decoupled CMS but without custom module.

**Comment by jtkech** [comment]
First the `PageLoaderMatcherPolicy` issue will be fixed in a future aspnetcore version, but anyway using `AddMvc()` this way introduces other issues.

Unless you bypass things at the app level all request are processed in a tenant context, so, when using orchard, `AddMvc()` is not intended to be used like this, it is added for you when you use `AddOrchardCms()`, idem for `AddRazorRuntimeCompilation` where we also check that the `refs` folder exists in your executing directory (which is required for runtime compilation).

Note: each tenant has isolated services but they all inherit app level services (and we need some). As i remember for the new endpoint system i needed to remove app levelrouting services and re-register them at the tenant level to be isolated from the app. But we don't do that yet e.g for mvc services.

That said, if you need to add more mvc things without creating a module the right way is

            services.AddOrchardCms(builder =>
            {
                builder.ConfigureServices(s =>
                {
                    s.AddMvc().AddMoreMvcThings();
                },
                order: 100); // optional order as you can define in a module startup.
            });

Again, when using `AddOrchardCms` you don't need `AddRazorRuntimeCompilation`, you just need to have a `refs` folder by using in your application `Microsoft.NET.Sdk.Web` project file.

    <PreserveCompilationReferences>true</PreserveCompilationReferences>

**Comment by sebastienros** [comment]
I don't understand all these issues with ref folders. Don't we add this `<PreserveCompilationReferences>true</PreserveCompilationReferences>` in our dotnet templates already? Or is it when someone creates a project manually and might not have it. Should/Could it be part of the Targets file?

**Comment by jtkech** [comment]
Yes, things have changed around this.

Now, in a regular web app, runtime compilation is not supported by default, you have to reference the `RuntimeCompilation` package which embeds a custom `.targets` file that set `PreserveCompilationReferences` to true.

We already reference this package from `OC.Mvc.Core`, not from the web app in which we only have to set `PreserveCompilationReferences` leaving the ability to not set it e.g if someone doesn't want to output the `refs` folder because he doesn't want to use runtime compilation (e.g on publishing). Note: runtime compilation is required for any app level **shape** razor view.

That said, in place of using `PreserveCompilationReferences`, in the main web app, **people can just reference or not the `RuntimeCompilation` package** (that we already reference through `OC.Mvc.Core`) **as in a regular web app**.

> Don't we add this `<PreserveCompilationReferences>true</PreserveCompilationReferences>` in our dotnet templates

Yes we add it
