### ISSUE TITLE
PathString usages

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#4471]
As pointed out by @deanmarcussen in #4424 `PathString.Value` is not the same as `PathString.ToString()`, the last one is an encoded uri component.

- As an example this autoroute `testδ` doesn't work.

    In the `AutoRouteTransformer`, replacing this

      if (_entries.TryGetContentItemId(httpContext.Request.Path.ToString().TrimEnd('/'), ...))

    By this

      if (_entries.TryGetContentItemId(httpContext.Request.Path.Value.TrimEnd('/'), ...))

    Then it works.

So, we need to update all the places where a `PathString.ToString()` is explicitly or implicitly used e.g  to set a string property / variable, passed as it is to a string parameter and so on.

I can start to work on it, but only if you think it's worth to do, it's not just adding another pending PR ;)

**Comment by sebastienros** [comment]
I love pending PRs, that what is keeping OC alive

**Comment by jtkech** [comment]
So i assume that it's worth to start working on it ;)

**Comment by sebastienros** [comment]
Yeeessss

**Comment by jtkech** [comment]
Okay i'll start tomorrow, i'm going to see the last meeting video that has just been published

**Comment by jtkech** [comment]
Just to say that it will be faster because it will not call `ToUriComponent()` every time

**Comment by jtkech** [comment]
Before checking it everywhere tomorrow

Just tried a tenant prefix set to `tenantδ`, it was not working. Doing the same kind of update in `RunningShellTableExtensions` fixed it.

As a reminder: In this extension, see if passing `httpRequest.Host.ToString()` may be also an issue, and anyway, see if better to pass it as an `HostString` that already has properties as `Host` and `Port`.

**Comment by sebastienros** [comment]
Yes I saw that too last week when testing domains. We should pass HostString all along as we are even parsing the string later on to get the port.

**Comment by jtkech** [comment]
Okay, also see that `HostString` supports IPv6 addresses where the host contains multiple colons before the one delemiting the port. Hmm, but then, if we want to support IPv6, i think we would need to update the way tenant url are built in the admin tenants page, will see.

**Comment by deanmarcussen** [comment]
@jtkech you read my mind :)

Just some thoughts, from a file store perspective.

PathString seems like async / Task, once you start with it, it starts to want to go everywhere.

I think you suggested using it for blob, in a constructor, but I didn't because it felt like it should either be either no PathString, or PathString everywhere. 
Bearing in mind the file store semantics call for a leading slash always, so basically are PathStrings, but currently managed as strings always.

So the change I did on https://github.com/OrchardCMS/OrchardCore/pull/4424 I made small, with as few changes as possible, i.e. not to the interfaces on `IMediaFileStoreCache`.

But if I was refactoring like you are going to do, instead of just fixing one issue as I was, I would have wondered about changing it a deeper level (maybe), and making more of the interfaces take `PathString` so that there was less string manipulation / checking for leading slash etc going on at a lower level.

(or equally in this case `HostString`) 

cool IPv6 :)

**Comment by jtkech** [comment]
@deanmarcussen you read into my mind too, i think we just need to read the `PathString` and `HostString` sources closely to find where it is useful or when string manipulations are simpler.

E.g `StartsWithSegments` is useful but the passed parameter needs to not have a trailling `/`. E.g adding multiple `PathString` just creates a new one from their `Value` strings concatenation, but by taking care of not having consecutive `/`, and so on.

**I think the main concern is the call to `ToUriComponent` where we thought it was not done**. E.g when adding path strings but to init a string variable that is not intended to be encoded. Otherwise, to init a string variable that is intended to be encoded it is useful to add them to other encoded strings.

**I will think about this and re-work on it soon, for infos i just did an additional test**.

Just tried a tenant domain `tenantδ.localtest.me` which ends up after idn mapping to `xn--tenant-gye.localtest.me:2918`. It was not working. **Replacing `Host.ToString()` by `Host.Value` fixed it**.

![HostString](https://user-images.githubusercontent.com/8586360/66245508-94971b00-e70e-11e9-9e0d-d36d6799dc60.png)

I didn't remember but i already did a change in the tenants index page where i used the `HostString` but just to retrieve the `Port` property, to be continued.
