### ISSUE TITLE
How Attached MediaField keeps the original file name？

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#4563]
Attached MediaField uploaded as a GUID + real file name, saved and changed to MD5.xxx, is there such a necessary, or has other options to retain the original file name?

**Comment by matiasmolleja** [comment]
No other options as it is now.
When we designed how it should work we tried to preserve disk space as much as possible.
We use the hash to check if a newly added file is already there. If it is there we don't upload the new file.

We do that here:
https://github.com/OrchardCMS/OrchardCore/blob/f21b24cf4f2a7ab441bae03eba09f9322ab235f8/src/OrchardCore.Modules/OrchardCore.Media/Services/AttachedMediaFieldFileService.cs#L105

**Comment by Skrypt** [comment]
Hash is usefull for avoiding the issue of people naming their files with similar names. You don't want to override files when uploading new ones and you can't really remember all the file names you used before. I think here, what @chinasqzl wants is to add a name portion after the hash so that the file names themselves could be indexed by a search engine for SEO or could be also for adding to a Lucene index. For that matter, I prefer that we make use of a Title field for images. Most of the time people don't look at their image names and they just upload it even if they have strange chars and else. Ex: ( "my-file_06-copy2.jpg")

**Comment by deanmarcussen** [comment]
Yes I like the idea of appending the source file as an extension to the hash. We have had a requirement to know the original file name with this field, but had to capture it manually in a text field. 
I can imagine it’s not totally uncommon to need to maintain the original file name

**Comment by sebastienros** [comment]
That could be part of the data stored on the field instead.

**Comment by deanmarcussen** [comment]
What about a dictionary on the field for metadata such as this, and perhaps an alt tag value from an alt-editor @sebastienros ?

**Comment by sebastienros** [comment]
We have talked about tags already for standard media fields. I would be ok with that only as another property on the field. But that means changing the ui significantly. But no dictionary, it's not open ended. Well-known properties only.

**Comment by chinasqzl** [comment]
File name is especially important when the user uploads an attachment, not a picture

**Comment by DrewBrasher** [comment]
@deanmarcussen I've had to go ahead and start using that pull request in a production site. Is this still something the Orchard team is interested in supporting or should I work on a way to achieve this through a separate module?

**Comment by Skrypt** [comment]
We need to review back the PR. It is summer time, people are busy, sorry for that.

**Comment by DrewBrasher** [comment]
I understand

**Comment by hishamco** [comment]
May be I come too late but


> is there such a necessary, or has other options to retain the original file name?

I don't think it's a good idea to keep the original name, assume I upload a client picture "Jon.png", after awhile I create a blog that I need to upload a picture of the blogger. So, if Jon is there, either we need to notifiy the user that the image already there or overwrite it (which is a problematic).

Generating a GUID or random name avoid such naming issues

**Comment by DrewBrasher** [comment]
@hishamco My changes do not change the way filenames are generated or stored. It only adds a property to the field that contains the original file name so someone can use it if they want similar to mediaText or anchor. The reason I need this is because my admin users need to attach non image files like pdfs and audio files and since those do not have a thumbnail image like a picture file, once a file is attached they cannot tell what files have already been attached. Here is a screenshot of what it looks like for reference:

![image](https://user-images.githubusercontent.com/9272802/183249111-2175de55-2a69-48b2-94bc-5ab58ddb8063.png)

With the changes I made, I can now override the admin display in my own module so that it displays the original file name instead of a string of characters and no thumbnail.

**Comment by hishamco** [comment]
> @hishamco My changes do not change the way filenames are generated or stored. It only adds a property to the field that contains the original file name so someone can use it if they want similar to mediaText or anchor.

No problem. BTW I didn't look into your PR but I comment based on the issue I saw ;)

**Comment by PiemP** [comment]
Sorry guys but, for my opinion, save file with an hash name is something that reduce the site accessibility. This feature is more important than what is seems. For a blind user is not beautiful to download a file that have a strange name. And the MediaField, in the Attached mode, is the only field that allow to upload file in a position that is easy manageable by a security role's: reducing risks of wrong deletion. 

Add another fields in the MediaField to save the original file name could cause a lot of misunderstanding when update from one version of OrchardCore to another one. If would proceed in this way it could be necessary to document this changes well. To keep this modify more "transparent", for the old OrchardCore version, could be useful to edit `MediaField` templates to have the possibility to download the file with the original name (and not the hash one) without doing something strange in the code (the HTML5 `download` attribute is enough for this?). 

> Hash is usefull for avoiding the issue of people naming their files with similar names

OK, but is simple to return an exception, add an error to the model and say to user about the necessity to change the file name. If Orchard change the file name, it do an abuse, if the user have named a file in a logical way. Probably is not the focus of the `MediaField` to be used with pdf or other documents...but for me, at this time, could be impossible to move my uploaded documents to another specific field for this purpose. 

Another question: what happen if I delete a content item that have some files related and uploaded with a `MediaField` in `Attached` mode? If we reuse a file with the same hash in another content item ... what happen if I delete a content item that is related to this file?

Sorry guys, hope to be not inappropriate. I hope to been useful in some way and not polemic. Is not my intent to be polemic and sorry for my bad written english.
