### ISSUE TITLE
OrchardCore.Application.Cms.Core.Targets: Include Blank recipe and SafeMode theme

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4595]
Could it be possible to include at least the Blank recipe and the SafeMode theme in  OrchardCore.Application.Cms.Core.Targets package ?

**Comment by hishamco** [comment]
Sound good

**Comment by sebastienros** [comment]
Question for anyone, is SafeMode used in any way in OC ?

**Comment by sebastienros** [comment]
Maybe there is a bug right now with the Core target, as if it doesn't have a Recipe you can't execute the Setup. I think I had to setup using the CMS target, then switch to Core to be able to use it.

Also, not that "Cms.Core" is not "Core" as I mentioned. We might also want to have recipe name that is more explicit about the fact it contains only the CMS modules. "Blank" contains CMS modules, it's not Blank.

**Comment by sebastienros** [comment]
Same question with Localization, we need to be clear about which target contains it.
And document these targets.

**Comment by deanmarcussen** [comment]
> We were also thinking about renaming the package Cms.Blank instead of Cms.Core.

I prefer Blank. (or Empty, or Bare), or just anything but Core

Core is confusing as Sebastien says

**Comment by deanmarcussen** [comment]
While we are discussed this, it would also be helpful to have a package like Core, that you could use from a custom module, or custom theme, to automatically reference all the OrchardCore modules, and abstractions, so you don't have to install them via NuGet individually just to inject something.

The Core package currently doesn't work for this I think, because it also has all the MSBuild commands, and those don't want to be run from a module.
