### ISSUE TITLE
Content definition, field technical name small letter, graphql will be empty, bug!

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#4604]
![image](https://user-images.githubusercontent.com/16968103/67259165-0f11ba00-f4c7-11e9-9caa-9fff3905476f.png)

**Comment by jrestall** [comment]
Sounds like if the technical name of the field begins with a lowercase letter, the query will fail. 

I can definitely see how that could happen since we are Pascal Casing the field name in the code above before querying for it, so it wouldn't match. We do that since GraphQL.net always camel cases the field name.

However a better approach could be to use a closure to access field.Name which should always match.

```
var contentField = contentPart?.Get(typeToResolve, field.Name);
```

**Comment by sebastienros** [comment]
Repro steps to see what the issue is?
