### ISSUE TITLE
Bug - V2

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4650]
There is a problem with Azure Pipelines with this error:
dotnet/sdk#3606

I found out the bug is in: 
/test/OrchardCore.Tests.Pages/OrchardCore.Application.Pages/web.config

Apparently when you switched to .net core 3.0 you were suppose to update AspNetCoreModule to  AspNetCoreModuleV2.

I made this change and the pipeline ran and succeeded.

**Comment by hishamco** [comment]
Could you make a PR for it?

**Comment by jtkech** [comment]
When started from Visual Studio it replaces it to V2 automatically, i think we just need to remove this web.config file, as done in the other apps of our solution.

**Comment by deanmarcussen** [comment]
@jtkech is right, the `web.config` file shouldn't be there.

But for info @JoshTango when you are building from dev with azure pipelines, you should change the azure pipeline defaults to not search the entire solution for `*.csproj` (which it does by default)

The only `.csproj` file you should be building is `src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj` 

Otherwise you will find it starts trying to build the templates, and other projects which exist in the dev branch, but are not intended for direct use.

Or you could just use the NuGet packages, which is the recommended way :)

**Comment by JoshTango** [comment]
@deanmarcussen thank you for this info
maybe there should be azure pipeline or msbuild documentation?
