### ISSUE TITLE
AzureMediaStorage - The specified container does not exist

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#4662]
When you enable AzureMediaStorage feature on an empty Azure storage account, you get an exception : 'StorageException: The specified container does not exist.'

### Reproduction steps :
- Create a fresh new AzureStorageAccount
- Configure the storage account in `appsettings.json`
- Enable 'Azure Media Storage' feature

**Comment by deanmarcussen** [comment]
Hi @TFleury 

When I did blob resizing we decided to remove container creation as a feature from Azure Media Storage.

So you have to create the container yourself before using.

**Comment by TFleury** [comment]
Hi @deanmarcussen,
Thank you for your answer.
I just found the [discussion](https://github.com/OrchardCMS/OrchardCore/pull/4025#discussion_r319295284) with @sebastienros about that.

Data Protection Azure Storage creates the container itself and it's kind.

If we don't create the container, we should at least tell the user to do it.
Actually, if you enable the feature with no container created, your tenant is broken (500 error) and you don't have any - simple - way to go back.

**Comment by deanmarcussen** [comment]
Yes, Data Protection does, and the discrepancy is noted 

Couple of suggestions have been made for managing this with multiple tenants, on gitter, and I have yet to action anything. So detailing them here for more comments 

When using blob storage for multiple tenants, the simple thing regarding container creation is to create one for your host (as you would for the database etc), and then we could provide a flag, via configuration, to say append tenant name to the basepath inside the container. 
So you would only ever need one container, and each tenants would have a folder inside that container.

And we would apply the same principles to Data Protection, and remove container creation.

Regarding the 500 error, we did update the docs to say it was required, but there was no easy way (without going back to the filter than had to run on every request, and only did a partial job of checking that the container / connection was good)

I'll think about that error a little more. There maybe a better way of catching that error to a log, as it is annoying to get the 500 and bring the tenant down (noting I accidently tried to use `DevelopmentStorage=true` on Azure recently and that really blew up badly)

**Comment by infofromca** [comment]
> When using blob storage for multiple tenants, the simple thing regarding container creation is to create one for your host (as you would for the database etc), and then we could provide a flag, via configuration, to say append tenant name to the basepath inside the container.
> So you would only ever need one container, and each tenants would have a folder inside that container.
> And we would apply the same principles to Data Protection, and remove container creation.

that is very good. 
can we also abstract those  and manage the account in one place?

**Comment by scleaver** [comment]
From our discussion on Gitter @deanmarcussen my personal preference was to be able to use a container per tenant as I believe this allows you to have a little more control over the permissions for the container if the tenant has some security concerns. Additionally, if other tenant related files are eventually stored on Azure storage then all the tenant's stuff could be in their container alongside the media folder. This might be superfluous, I don't know.

**Comment by deanmarcussen** [comment]
@scleaver that's right we did, and never figured the option to go for.

- container per tenant (created via `ISetupEventHandler` on tenant setup)
- base folder inside single container per tenant, enabled via a flag

Both of these options are very simple to achieve

Which one does everyone prefer?

I have no particular opinion either way, so whatever works better for people.

@TFleury You are using this as well so interested to hear your thoughts?

@infofromca I think combining the two accounts into one has already been discussed, and I'd vote for keeping them seperate. Otherwise you have to potentitally check 3 values, and I can just see it getting even more confusing for people.

**Comment by TFleury** [comment]
I use a storage account per tenant (each customer has his own database and storage account).

One container for all tenants is not a solution I would consider. One container per tenant seems (to me) to be the minimum isolation level.

One thing that could be nice would be inheritance between features that uses Blob Storage :
```
"OrchardCore.AzureBlob":
{
  "ConnectionString": "MyStorageConnectionString" // optional
  "ContainerName": "MyTenant" // optional
},
"OrchardCore.DataProtection.Azure":
{
  "ConnectionString": // optional, default to OrchardCore.AzureBlob.ConnectionString
  "ContainerName": // optional, default to OrchardCore.AzureBlob.ContainerName
  "BasePath": "some/base/path", // optional, default to ""
},
"OrchardCore.Media.Azure":
{
  "ConnectionString": // optional, default to OrchardCore.AzureBlob.ConnectionString
  "ContainerName": // optional, default to OrchardCore.AzureBlob.ContainerName
  "BasePath": "some/base/path", // optional, default to ""
}
```

I'm also working on a blob storage based `ITenantFileProvider`.

**Comment by deanmarcussen** [comment]
@TFleury if you are using a storage account per tenant, how do you configure the blob connection string for each tenant? Is that something you've been able to automate during tenant setup or is it manual afterwards?

We should definitely move `DataProtection` to using `IOptions` instead of `IShellConfiguration` directly, as that would make it possible to to do the inheritance you have above, by overriding the `IOptions` .

I'm yet to be convinced to make it do inheritance oob, as you describe, as it feels like it makes configuration even more confusing, but open to becoming convinced :)

> I'm also working on a blob storage based ITenantFileProvider.

Great, if you need any help with that please reach out.

**Comment by TFleury** [comment]
> If you are using a storage account per tenant, how do you configure the blob connection string for each tenant? Is that something you've been able to automate during tenant setup or is it manual afterwards?

I do it manually
> I'm yet to be convinced to make it do inheritance oob, as you describe, as it feels like it makes configuration even more confusing, but open to becoming convinced :)

It's just a suggestion, it could just avoid duplicating ConnectionString in config. It could also inherit from a global config for those who use a single account for all tenants. (I wonder if there is not already an inheritance from the global config)

A first step could be to merge 'DataProtection.Azure' and 'Media.Azure' (and also 'Tenants.Azure' in a near future) into a single module. It would make configuration inheritance less confusing.

**Comment by deanmarcussen** [comment]
> from a global config for those who use a single account for all tenants. (I wonder if there is not already an inheritance from the global config)

Yes, there is already inheritance from the main projects 
`appsettings.json` -> `App_Data\appsettings.json` -> `App_Data\Sites\tenant_name\appsettings.json`

**Comment by sebastienros** [comment]
What's the solution to this issue? Preventing the site from failing when the container doesn't exist?

**Comment by TFleury** [comment]
> What's the solution to this issue? Preventing the site from failing when the container doesn't exist?

Failure is caused by `TempDirCleanerService`. It maybe only requires a try/catch.
Maybe other FileStores could fail and it must not prevent shell to be activated.

We should also add an alert in admin to tell the user that he has to create the container if it's missing.

**Comment by deanmarcussen** [comment]
By popular demand we'll bring back container creation :)

Had a chat with Sebastien, and got a rough design.

- Create container / check exists in either `Startup.Configure` or `IModularTenantEvents.ActivatingAsync`
- Template w/liquid such that `ContainerName` or `Folder` can optionally include the tenant name e.g. `ContainerName: "{tenant}-container"`, or `BasePath :"{tenant}/media"`
- Resolve the possibility of bringing site down because container won't create `TempDirCleanerService` looks like it cheers @TFleury 
- Apply same template options to DataProtection
