### ISSUE TITLE
Admin - Create user -> "The user name is already used." error

### ISSUE THREAD

**Issue by AkosLukacs** [OrchardCMS/OrchardCore#4663]
If I go to [Admin -> Create user](OrchardCore.Users/Admin/Create), after clicking save, an error message "The user name is already used." is shown.
The user is created, but roles not saved. Backing out to the user list, the new user is listed, can add roles set password, and can log in.

Debugging from the latest source looks like the user is created at [AdminController.cs # 169](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AdminController.cs#L169) `var shape = await _userDisplayManager.UpdateEditorAsync(user, updater: this, isNew: true);`
At that point the `ModelState` contains one error:
![image](https://user-images.githubusercontent.com/844331/67675695-14b44780-f980-11e9-97f7-16a948b5f4b9.png)

Edit: before the `UpdateEditorAsync` call the `ModelState` is empty.
Tested with SqLite and Ms Sql Server storage.

**Comment by AkosLukacs** [comment]
More info:
Looks like [UserDisplayDriver.cs:86](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserDisplayDriver.cs#L86) calls `_userManager.SetUserNameAsync` that eventually calls into [UserStore.cs#L177](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs#L177) that calls `_session.Save(user);`. After that call the `user` object does have an Id.

The chain of calls isn't clear for me: there debugger goes through the following calls in `UserStore.cs`: `SetUserNameAsync`, `SetSecurityStampAsync`, `GetSecurityStampAsync`, `GetUserNameAsync`, `FindByNameAsync`, `GetUserNameAsync`, `SetNormalizedUserNameAsync`, `GetEmailAsync`, `SetNormalizedEmailAsync`. The caller in the call stack is  "external code". Before the actual call to `_session.Save` only a couple of properties are set on the user object:
![image](https://user-images.githubusercontent.com/844331/67677829-598ead00-f985-11e9-9438-3094ee24c813.png)
After the `_session.Save` call the user object does haven an Id:
![image](https://user-images.githubusercontent.com/844331/67677881-7a570280-f985-11e9-9430-3e5cea8c43ff.png)

The error message is set at [UserDisplayDriver.cs#L95](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserDisplayDriver.cs#L95)

**Comment by deanmarcussen** [comment]
Yes, I can repro this. It looks like it might be a regression from this PR https://github.com/OrchardCMS/OrchardCore/pull/4521

**Comment by hishamco** [comment]
Might be, but I did what is expected to be done, let me check this one ..

**Comment by jtkech** [comment]
Yes, calling `_userManager.SetUserNameAsync` will call our `UserStore.UpdateAsync()` which does a `_session.Save(user)` then after `_userManager.GetUserIdAsync(userWithSameName)` find an "existing" user.

That's why i think `UserStore.SetUserNameAsync()` was used directly to just update the user name without session save.

Just an idea on the fly, maybe just update the fields of the user (that is a scoped object) in the driver directly without using the user store / manager. But maybe a better pattern to use the user store service to do this.

Then at the end just use `_userManager.UpdateAsync()` but in fact this is not in the driver that the user need to be saved, this is done by the `AdminController.EditPost()` line 221.

            var result = await _userManager.UpdateAsync(user);

**Comment by AkosLukacs** [comment]
Thanks!
