### ISSUE TITLE
Tag attribute on a shape tag not passed down to Model.Tag

### ISSUE THREAD

**Issue by bleroy** [OrchardCMS/OrchardCore#4666]
Repro: Create a shape from a Razor view, such as `<shape tag="p" Type="SomeShape" .../>`. From the template of `SomeShape`, `Model.Tag` will not be 'p' as expected. This is due to the `BaseShapeTagHelper` not passing the attribute down to the shape it creates. As a result, a `Tag(Model, "span")` in that view will result in a span being used instead of the p the outer view requested.

**Comment by deanmarcussen** [comment]
@bleroy I had a look at this, and ended up not sure.

The `BaseShapeTagHelper` `Tag` property seems to be for setting the `cache-tag`, rather than setting a `TagBuilder` `Tag`

A TagBuilder attribute could be passed in the `prop-` prefix to the properties dictionary, but that would mean the shape would need to be aware, and look in the properties dictionary, for the tag.
Which sounds like it's defeating what you're trying to do?

**Comment by bleroy** [comment]
The code certainly seems to indicate that, but then the problem is its naming. This behavior is extremely unexpected: unless you debug into this and look into the code, there's no way you're going to guess that tag attribute only works for some obscure caching feature. Especially when there's an established pattern in Orchard to enable the outer shape to specify what tag the inner shape should render as its external tag if it renders anything at all. That enables the inner shape to decide whether to render on its own terms, but still enable the outer shape to decide what wraps the markup. Yes, the shape needs to be aware of that, but that's exactly the pattern. It doesn't defeat what I'm trying to do, it's exactly what I'm trying to do.

**Comment by jtkech** [comment]
As i remember so not sure ;)

As said on gitter, i think the "problem" is how the underlying `TagHelper` works on aspnetcore side. If an attribute name matches an existing property, here tag => `Tag`, this property is initialized with the attribute value and then the attribute is removed from the output attributes list.
