### ISSUE TITLE
Liquid does not encode fa-IR Culture properly!

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#4711]
When we import and bind Farsi content in a template using liquid templates, it will not decode characters properly.
![image](https://user-images.githubusercontent.com/32009041/68068604-c29e6800-fd6b-11e9-8938-285b40b33de1.png)
I think it is better to modify Liquid module and make it decode contents. Because it is awful for search engines!

**Comment by hishamco** [comment]
I think I saw this issue before, @sebastienros is this related to Fluid or Liquid module itself

**Comment by sebastienros** [comment]
As you are showing, it is encoded properly. Your concern is actually that you don't want it encoded. This is due to the default HtmlEncoder in aspnet. There are settings to define other gross of chars that you don't want to be encoded. Search for an issue about Greek where we share the solution. Otherwise I will find it.

**Comment by hishamco** [comment]
@sebastienros do you mean this one #4041?

**Comment by ampadashi** [comment]
@sebastienros I've checked issued #4041 . But, I couldn't find the solution:)). Please help me;)

**Comment by hishamco** [comment]
> But, I couldn't find the solution:)). Please help me;)

I just asked him to verify if that's the issue :smile:

**Comment by sebastienros** [comment]
You can fix it for ASP.NET like this:

```
services.Configure(options =>
{
options.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All);
});
```

But Liquid won't use these options by itself. We need to either pick the HTML encoder from ASP.NET when rendering liquid templates, or expose a new configuration. 

I think we should at least pick the same encoder as for ASP.NET. Or use the same TextEncoderSettings wherever we can, even for other encoders.

For instance, here: https://github.com/OrchardCMS/OrchardCore/blob/0809e5ac8cc9b9f5f2ff566d1f20eeef7a7e3738/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/LiquidViewTemplate.cs#L115 instead of using the `HtmlEncoder.Default` instance, we should use the one from ASP.NET, or create a new one with the same options as ASP.NET.

**Comment by hishamco** [comment]
@ampadashi  seems this is fixed in https://github.com/OrchardCMS/OrchardCore/commit/3e221778f8b670fb16d6ffb5565526913ccc0411 

Feel free to contact us if the issue still happen
