### ISSUE TITLE
how is orchard cache data ?

### ISSUE THREAD

**Issue by meodemsao** [OrchardCMS/OrchardCore#4772]
i want known how orchard cache data because when i run 2 instance (using nginx loadblancing)
i update data and data in two instance difference in period
p/s: i also fixed session issues with using redis session

**Comment by meodemsao** [comment]
@sebastienros i try use redis for orchard caching by change 

```C#
services.AddSingleton<IDistributedCache, MemoryDistributedCache>();
`

with 

```C#
services.AddSingleton<IDistributedCache, Redis>();
`

in OrchardCore.Infrastructure/ Cache/OrchardCoreBuilderExtension.js

But not working 

I see we using memorycache but i can't find any solution for this in aspnetcore document

**Comment by jtkech** [comment]
We use in many place the local tenant memory cache where entries are tied to a change token so that when a state change or through an handler event, by using a **local signal service** we cancel the token and then invalidate the related local cache entrie.

Then, as i remember, we also cache shapes by using a distributed cache whose default implementation is a memory cache, here it is 1st because of its serialization / deserialization capabilities. Then, cache entries depend on different dynamic contexts, e.g the current user / roles / route / query, and can be tied to **local cache tags**, e.g an alias tag, that can be removed, e.g on publishing a content item, through a **local tag cache service**, this to invalidate the related local cache entrie.


Then the strategy in a distributed environment is to keep things as they are and provide distributed features / services, e.g a **distributed signal service**, a **distributed tag cache service** and so on. So that e.g a local token change or a tag removing is propagated to other instances (here by using a message bus) so that they are kept in sync by also invalidating their local cahe.

I will re-work on it soon, see #2247

**Comment by meodemsao** [comment]
@jtkech thank, your branch very cool :)
