### ISSUE TITLE
Exception: Shape type 'Taxonomy_SummaryAdmin' not found

### ISSUE THREAD

**Issue by sallenkov** [OrchardCMS/OrchardCore#4838]
I got this exception when i navigate to  Content Items, i am not sure on how to produce this error, but i can no longer get my content items even after disabling Taxonomy
![image](https://user-images.githubusercontent.com/17978153/69143456-4fb22280-0ac9-11ea-877b-f770580c6459.png)

**Comment by jtkech** [comment]
The content items List page uses by default for each item the `Content_SummaryAdmin` template if the related content type has no stereotype (and if no more specialized alternate exists), otherwise it uses by default `Stereotype_SummaryAdmin`.

So the only way i found to repro the exact same issue was to update one of my content types by setting the `Stereotype` to `Taxonomy`. So, check if one of your content types has been defined with such a `Stereotype`.
