### ISSUE TITLE
PublishingContext.PreviousItem is null when existing Context Item is updated

### ISSUE THREAD

**Issue by artemsv** [OrchardCMS/OrchardCore#4853]
Steps to reproduce:

1) Create simple Content Handler in the root of OrchardCore.Cms.Web project

   ```
    internal class MyContentHandler : ContentHandlerBase
    {
        public override Task PublishingAsync(PublishContentContext context)
        {
            var empty = context.PreviousItem == null;
            return base.PublishingAsync(context);
        }
    }


2) Register it in Startup.ConfigureServices method:

```
    services.AddScoped<IContentHandler, MyContentHandler>();
```

3) Create the new ContentType Student with one text filed and name it FirstName. Student is only Listable and Creatable, its field also only Creatable and Listable. 

4) Add Title Part.

5) Create one student with any title and FirstName = "John"
6) Publish it
7) Put breakpoint in MyContentHandler.PublishingAsync
8) Edit the Student by changing FirstName
9) When you press Publish button and debugger appears inspect context.PreviousItem property - it will be null.

Here you may see that FirstName is John2 (already new value), and context.PreviousItem is NULL.

![image](https://user-images.githubusercontent.com/1922262/69377646-c6177600-0cbd-11ea-8a05-c0357d8d6066.png)

In the database we may see the existing inundated value:

![image](https://user-images.githubusercontent.com/1922262/69377828-15f63d00-0cbe-11ea-9243-5b28d82e95f4.png)

It was in Journal. The same picture is in the table itself: 

![image](https://user-images.githubusercontent.com/1922262/69377921-4342eb00-0cbe-11ea-986b-2c3e2f6ab0bc.png)

UI when debugger is frozen:

![image](https://user-images.githubusercontent.com/1922262/69378024-81d8a580-0cbe-11ea-9053-4ec52aba5c5d.png)


Content Type itself

![image](https://user-images.githubusercontent.com/1922262/69378114-bd736f80-0cbe-11ea-8e97-9a55f3543c81.png)

**Comment by jtkech** [comment]
When publishing an already published item the following happens.

1. We make a new draft version with Latest = true and Published = false. And we set Latest = false for the currently published item.

2. We retrieve the current published version (that will be the previous one) and set its Published to false. Then we publish the new draft version by setting its Published to true.

But, as in your case, if the type is not `Versionable` we always use the same content item version. So in step 1. we unpublish the only one version we are working on, and then in step 2. we don't retrieve any currently published version, that's why here previous is null. Then we re-publish the only one version that has been unpublished in step 1.

So, if the content type is not `Versionable` the previous version is always null. If you want to check data before updating you would have to use the `UpdatingAsync()` event.

Note: In your handler you don't need to call `base.PublishingAsync(context)`.

**Comment by artemsv** [comment]
Thank you, will check. If the scenario I would like to implement works well when ContentType is Versionable checking this flag may be the best solution. Will close the issue after checking...

**Comment by artemsv** [comment]
Checked. Have set ```Versionable ``` flag and everything works as expected. Merci beaucoup!
