### ISSUE TITLE
Cache purge screen

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#489]
We should have some admin screen to purge the cache. For instance one listing all the `ITagCache` entries so that it's easy to purge tagged entries on demand. With a search filter and probably a purge all tags too.

**Comment by DanielStolt** [comment]
I approve of course. :)

**Comment by agriffard** [comment]
To be triaged.

**Comment by Piedone** [comment]
When would you use this? The tag cache seems like a very technical, internal thing for me that users shouldn't touch (even less so than the Media Cache). We shouldn't expect issues with it that may be solved with a purge either.

**Comment by hishamco** [comment]
While I worked recently on `OCC.Garnet` https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/tree/main/src/OrchardCoreContrib.Garnet I noticed that `ITagCache` is a technical thing as @Piedone mentioned, Also I'm confused with the tagging implementation I'm not sure if it's by design or the current Redis APIs
