### ISSUE TITLE
Request 404 When Oc is published to iis 7.5 in virtual folder 

### ISSUE THREAD

**Issue by stantoxt** [OrchardCMS/OrchardCore#4890]
When I published oc to iis 7.5 in virtual folder, many requst return 404,like publish post,content preview.But everything is ok in iis 8.5

**Comment by hishamco** [comment]
I think we need to investigate on this, @jtkech @Skrypt @agriffard did anyone saw this behavior before?

**Comment by jtkech** [comment]
What you can do is to try these urls locally by adding a virtual folder like this


        public void Configure(IApplicationBuilder app, IHostEnvironment env)
        {
            app.Map("/virtual", app2 =>
            {
                if (env.IsDevelopment())
                {
                    app2.UseDeveloperExceptionPage();
                }

                app2.UseStaticFiles();

                app2.UseOrchardCore();
            });
        }
    }

Just tried, i published an article and then used the preview, it works.

Can you give us an exact url that doesn't work? So that we could have more infos to search on what would be different when running under iis 7.5 or 8.5.

**Comment by stantoxt** [comment]
Thanks @hishamco @jtkech ,I will test it again.

**Comment by stantoxt** [comment]
If it is the problem about supported os,I published it to windows server 2008 r2 which is not supported by .net core 3.
