### ISSUE TITLE
Localized text values

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#500]
Some stored elements should be localized. In O1 the recommendation is to create a custom module to localize these strings, and use a helper when rendering them.

In O2 I would suggest a different approach:

When such string are used, for instance the `Description` of a content type or a content part, because the content is stored in the metadata we can't use `T`. We should instead store all the potential culture specific values, and use the correct one when we use it.

It means we need:
- A reusable text input component that works as a textbox, but has some UI to add more entries. It would default to the current culture.
- A reusable .NET type that would be backed by a `Dictionary<string, string>` and store the text as a JSon object indexed by the culture. We should probably have a neutral culture entry in case the text in the specified culture can't be found.
- Some helper methods to easily select the correct culture string on such an object.

Something like `public string DisplayName { get; private set; }` in a Content Type would become

```
public CultureString DisplayName { get; }
```

@bleroy @Piedone

**Comment by Piedone** [comment]
I think the question should rather be: how can we make `T()` (or otherwise the technique used in any other UI string) working?

`DisplayName` or `Description`, while being content type metadata, still (at least initially) come from code, like UI labels: the developer specifies it when implementing the type. Now we know that this metadata will then be saved into the DB (or at least this happens in O1), but that shouldn't make a difference from a dev's perspective.

Now things get more complicated with content types defined in recipes or by hand... Still I think foremost we need to examine whether it's feasible to make these string localizable with `T()` before introducing a third way of localization (in addition to `T()` and content localization).

**Comment by sebastienros** [comment]
> DisplayName or Description, while being content type metadata, still (at least initially) come from code

What have you smoked 🚬 They come from code as much as content localization, like zero!

**Comment by Piedone** [comment]
:-D What about migrations?

**Comment by sebastienros** [comment]
Ah ah! I see what you mean. I focused mainly on UI driven definitions, and took this one as an example. Look at Queries for instance. But I get what you mean.

Now try to understand what I meant and think of a solution that would solve it from the UI too. As my suggestion is also valid for migrations, if you not also much more practical than what you suggest.

**Comment by hishamco** [comment]
This could be done easily with `IDataLocalizer` that PR #3659 is covered

**Comment by hishamco** [comment]
@sebastienros is this a duplicate of #3607

**Comment by sebastienros** [comment]
Duplicate of #3607
