### ISSUE TITLE
Importing Data.

### ISSUE THREAD

**Issue by K-Bains** [OrchardCMS/OrchardCore#5030]
Hi im currently trying to import data using IDataMigration however i get the following error:

> 2019-12-13 12:53:39.2757|Default|80000012-0007-ff00-b63f-84710c7967bb||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'Project'. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: ContentItemIndex'.

if i try the same file as a recipe (in the recipe folder) via the admin page it seems to run ok and it does import all the data. Does anyone have any ideas on what could be wrong? Or is there a better way to import content items? 

below is an example of my recipe file i have removed the data.

```
{
    "name": "....",
        "displayName": "....",
        "description": "....",
        "author": "....",
        "website": "....",
        "version": "1.0",
        "issetuprecipe": false,
        "categories": [ "default" ],
        "tags": [  ],

    "steps": [
        {
            "name": "Content",
            "data": [

            ]
        }
    ]
}
```

**Comment by deanmarcussen** [comment]
where are you registering the `Migration` ?

It would seem you're registering it to run before the rest of the site has been setup and the content feature enabled. 

Are you trying to do this as part of setting up the site? 

Maybe you've run it from the Startup project, which is registering it early, before all the other migrations have run.

It would be better suited to either being a setup recipe, which has the features to enable step first (i.e. Content), or to use it as a migration registered in a module Startup, which would then run when the module is enabled.

**Comment by K-Bains** [comment]
so i have a setup recipe which creates all the content types, i wanted a 2nd recipe to run which would create all the content items, im doing this in a different module and im registering my IRecipeMigrator in the startup of that module. 

i followed this [tutorial](https://www.davidhayden.me/blog/recipe-migrations-in-orchard-core-cms)

**Comment by deanmarcussen** [comment]
are you registering the module in the features step of the setup recipe? Perhaps it's being registered before the Content module.

Basically the Content module is going to run a migration to create the `ContentItemIndex`, so that's going to need to run first.

Hard to say for sure what's happening without seeing all the code.

One option might be to change the `Order` property of your module that has this second recipe to say `1000` which should make it try and run last.

Also you might want to check your setup recipe, and make sure it runs the features step first - order matters here. 
Or combine the two into one recipe? not sure why you need to have them seperate, but maybe there is a reason.

**Comment by K-Bains** [comment]
how would i go about changing the order property for my module?

**Comment by deanmarcussen** [comment]
In the startup file for the module you can override the order property `public override int Order => 100;`

Really need to see some code though to understand what's going wrong for you. The Order is just an of the top of my head thought

**Comment by K-Bains** [comment]
Thanks the order did work for me. i will look into this some more.
