### ISSUE TITLE
[Question]Getting a valid token for all tenants

### ISSUE THREAD

**Issue by jardg** [OrchardCMS/OrchardCore#5070]
Hi, I'm trying to implement an scenario where I get a token using the password flow  on the default tenant and its valid for all the tenants(multitenancy scenario). The token should have claims to identify the same user(ClaimsPrincipal) in all the tenants. For me the same user means same email,id and username in all the tenants.Other properties change like roles and permissions. The user is created like that using my code.

For this I created a scope in the default tenant and make every child tenant belong to it. Then use Default tenant as Authorization server tenant in every child tenant. Finally for getting the token I made a call to /connect/token with the scope= openid offline_access profile roles and my newly created scope.
This was working okayish because the token I got using the default tenant wasn't identifying the correct user when using it on a child tenant controller. That's because the id differed. While the userId with email@email on default Tenant was 1 in child tenant was 3. So claimsPrincipal was identifying the incorect user. Since the claims had the email on it I could retrieve the correct user for the child tenant and make it work. But I think this is extra work because I had to call to userManager FindByEmailAsync and somehow hacks the purpose of the whole system. Am I missing some configuration to identify the correct user on all the tenants?

Is there a way to achieve this functionality of identifying the same user on all the tenants and make the token usable on all of them?Also is it possible to create a user on the default tenant and be the same on all the tenants with OC code without having to create it on all the tenants?

Thanks in advance for the help.

**Comment by sebastienros** [comment]
I think it's doable by using delegation. You can enable OpenId on a separate tenant, and configure each tenant to use this common one for auth.

/cc @PinpointTownes

**Comment by jersiovic** [comment]
In our scenario user management UI at child tenants is disabled so we only allow to manage users at parent tenant.
When any change is performed on users at parent tenant it is replicated at parent tenants.
You can think on it like if we were talking of three microservices, one responsible of user management and authentication (with current configuration which it is actually  the parent tenant) and the other microservices that need info related to those users (with current configuration those are actually the child tenants).
The point is we are using orchard within all these three microservices, and we need same userid for same user in the storage of all three microservices.
We want to store users added in parent tenant with same userid in the child tenants. This will fix problem reported by my fellow @jardg 

There are few problems that prevent us of doing that:

- YesSQL doesn't allow to set the userId of a new user

- User Id seems to be the Document Id so any extra content added to an Orchard tenant can take an Id that is used for an user in parent tenant.

So, the questions are:

-  Is it possible to have Users isolated in a different document collection table at db, with its own Id only for Users?

- Is there a way of setting the UserId when you store a new User?

**Comment by Skrypt** [comment]
Right now you can't. And yes, I reported this issue in a different issue. DocumentId is not an immutable Id for users because of multi-tenancy and import/export. So, the username is supposed to be the identifier of the user. Though this username is not immutable either. So, we will require someone to add a guid identifier eventually.

**Comment by jersiovic** [comment]
Thank you @Skrypt , so if that would be the solution then we also need to store that guid at the token for using it as identity of the user. And use it in all methods that currently request an user by I'd, isn't it?

**Comment by jersiovic** [comment]
Related to following the way I mentioned before, do you think that are doable the following things without friction with other parts of the code?:

-  To use a separate collection within this class  https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs based on this feature of YesSQL https://github.com/sebastienros/yessql/pull/30/files#diff-50c8dfc88150c980068843b43d83c701R209

- To change YesSQL current behavior when  an entity with an Id is stored and there is not an entity with that I'd in the db. Currently it throws an exception because it doesn't find an entity to update. Do you thing it could be a problem that in this case instead of reporting an exception it stores a new entity with that I'd?

We are interested on providing a PR that overcome the limitations we face. Can you address us in the right direction.

**Comment by Skrypt** [comment]
Related https://github.com/OrchardCMS/OrchardCore/issues/3492

**Comment by jersiovic** [comment]
After reading #3492 I agree we could use username as identity of the user if it were inmutable and provide to those who needed a Display name.
But we would need the token issued by open id module should contain username instead of user id as identity of the princial.

![image](https://user-images.githubusercontent.com/4950766/71467773-34bb8800-27c4-11ea-96dd-9c3cd9ae625a.png)

Is it doable?

**Comment by jersiovic** [comment]
Just in case anyone is interested on this scenario or someone wants to add any advice: We are taking the path mentione by @jardg .  Moreover, we are going to work on moving all the users management to parent tenant. So, from parent tenant UI we will be able to set the roles of an user for each one of the child tenants. Roles at child tenants will be disabled. So, parent tenant will have to issue tokens with claims for all the tenants. How an user can have different permissions on each tenants, we have to add a prefix with the tenant to all the claims of a tenant. To distinguish same permission for one tenant from another tenant.

**Comment by PinpointTownes** [comment]
> Is there a way to achieve this functionality of identifying the same user on all the tenants and make the token usable on all of them?

This is currently not a supported scenario: you can create scopes and assign them specific tenants (so that an access token can be accepted by the tenants listed by the requested scopes), but you can't have a token issued by a tenant and accepted by all the other ones.

> Also is it possible to create a user on the default tenant and be the same on all the tenants with OC code without having to create it on all the tenants?

Here's the approach I'd _personally_ recommend: to retrieve the user registered in tenant A from tenant B, use the cross-tenant shell APIs. It's a pattern we use in multiple places in the OpenID module. Here's an example: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Services/OpenIdValidationService.cs#L145-L169

Now, we'd probably want to have a better cross-tenant and support things like cross-tenant-authorizations/permissions natively... but it's something that would require some time to implement, and for 1.0, I guess it's too late.

**Comment by Skrypt** [comment]
This would work but only with OpenID use case. I think we need to find a proper fix for when using it and when not.

**Comment by jersiovic** [comment]
> > Is there a way to achieve this functionality of identifying the same user on all the tenants and make the token usable on all of them?
> 
> This is currently not a supported scenario: you can create scopes and assign them specific tenants (so that an access token can be accepted by the tenants listed by the requested scopes), but you can't have a token issued by a tenant and accepted by all the other ones.
> 

Problem of using scopes is you loose fine grain control isn't? I mean you cannot limmit claims issued to a subset of the permissions of a tenant.
Well, we finally managed to have a token for all the tenants providing username in the token as identity instead of userid. I will ask @jardg to share the code to accomplish it.
> > Also is it possible to create a user on the default tenant and be the same on all the tenants with OC code without having to create it on all the tenants?
> 
> Here's the approach I'd _personally_ recommend: to retrieve the user registered in tenant A from tenant B, use the cross-tenant shell APIs. It's a pattern we use in multiple places in the OpenID module. Here's an example: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Services/OpenIdValidationService.cs#L145-L169
> 
On the one hand despite we use that pattern problem is the userid stored in the token is not the same for same username in a different tenant. 
On the other hand we start this app as a regular multitenant app but we want to be ready to move to a microservices scenario where now what it is a tenant in a multitenant environment will be  moved to a different server with each tenant running standalone on separate instances for scalability reasons. That's why we should not rely on that shell pattern.
> Now, we'd probably want to have a better cross-tenant story and support things like cross-tenant-authorizations/permissions natively... but it's something that would require some time to implement, and for 1.0, I guess it's too late.
Maybe you are interested on how we have solved it. We will share as soon we are in the office.

**Comment by jersiovic** [comment]
@PinpointTownes Now I get that you mean to use cross-tenant shell APIs  for translating parent tenant User Id within the token to get username and then retrieve User in child tenant. It is an option. But it doesn't fit for us when we move to a microservices approach

**Comment by jardg** [comment]
So finally I replaced some services to have all the tenants have the same user by using the username.
I removed IUserStore<IUser> from serviceCollection and created a custom implementation with changes in FindByIdAsync and  GetUserIdAsync.


```
 public new async Task<IUser> FindByIdAsync(string userId, CancellationToken cancellationToken = default(CancellationToken))
        {
            int id;
            if (!int.TryParse(userId, out id)) //Keep compatibility with OrchardCore which uses id
            {
                return await FindByNameAsync(userId, default(CancellationToken));
            }
            else
            { 
                return await _session.GetAsync<User>(id);
            }
        }

        public new Task<string> GetUserIdAsync(IUser user, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (user == null)
            {
                throw new ArgumentNullException(nameof(user));
            }
//Read normalized username. If doesn't exists it means is called by Orchard code. So use id to keep compatibility with OrchardCore which uses id
            return Task.FromResult(string.IsNullOrWhiteSpace(((User)user).NormalizedUserName) ? ((User)user).Id.ToString(System.Globalization.CultureInfo.InvariantCulture) :
            ((User)user).NormalizedUserName.ToString(System.Globalization.CultureInfo.InvariantCulture));
        } 
```

Then to have the roles in different tenants work with different permissions I created a customClaimsFactory and removed default one from Orchard. This one just read what permissions has the user roles in the different tenants using the cross-tenant shell API. So the claim created by the role permission consists in the tenant prefix and the permission.

```
protected override async Task<ClaimsIdentity> GenerateClaimsAsync(IUser user)
        {
            ClaimsIdentity claims =  await base.GenerateClaimsAsync(user);
            var claimsToRemove = claims.FindAll(x => x.Type == "Permission").ToList();
            foreach (var claim in claimsToRemove)
            {
                claims.RemoveClaim(claim);
            }

            foreach (var roleName in (user as User).RoleNames)
            {
                foreach (var settings in _shellHost.GetAllSettings().Where(x => x.State == OrchardCore.Environment.Shell.Models.TenantState.Running && x.Name != "Default"))
                {
                    using (var shellContext = await _shellHost.CreateShellContextAsync(settings))
                    {
                        using (var scope = shellContext.CreateScope())
                        {
                            var roleStore = scope.ServiceProvider.GetRequiredService<IRoleStore<IRole>>();
                            var roleInTenant = await roleStore.FindByIdAsync(roleName, default(CancellationToken));
                            if (roleInTenant == null)
                            {
                                continue;
                            }

                            foreach (var claim in ((Role)roleInTenant).RoleClaims.Select(x => x.ToClaim()))
                            {
                                if (claims.FindFirst(x=>x.Value == string.Format("{0}_{1}", settings.Name, claim.Value)) ==null)
                                {
                                    claims.AddClaim(new Claim("Permission",string.Format("{0}_{1}",settings.Name,claim.Value)));
                                }
                            }
                        }
                    }
                }
            }

            var email = await _userManager.GetEmailAsync(user);

            if (email != null)
            {
                claims.AddClaim(new Claim("email", email));
            }

            if (await _userManager.IsEmailConfirmedAsync(user))
            {
                claims.AddClaim(new Claim("email_verified", "true"));
            }

            return claims;
        }
```
Finally removed Orchard permission handler and created custom permission handler. This is the same as the default but appends the tenant name to the permission when checking the claim to make it work.
```

 protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, PermissionRequirement requirement)
        {
            if (!(bool)context?.User?.Identity?.IsAuthenticated)
            {
                return Task.CompletedTask;
            }
            else if (context.User.HasClaim(Permission.ClaimType, string.Format("{0}_{1}",_settings.Name, requirement.Permission.Name)))
            {
                context.Succeed(requirement);
            }

            return Task.CompletedTask;
        }
```

**Comment by jersiovic** [comment]
As you see at the code we still use cross-tenant shell API for reading what permissions has the user roles in the different tenants. However that is sth we can go without in the case we move to a microservices scenario.

**Comment by jtkech** [comment]
Just for infos

- I would have used `GetOrCreateShellContextAsync()` so that you don't have to compose those that are already created.

- Okay to just use `CreateScope()` for what you are doing.

- After having grabbed all `RoleNames`, maybe better to use the `foreach (var roleName ...` inside a given shell scope, so that you don't have to create all shell scopes for each roleName.
