### ISSUE TITLE
AutoroutePart in Localized content

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5083]
I am still confused about route generation in localized part.

Say I have a Content Item with three parts:

- TitlePart
- AutoroutePart
- LocalizationPart

I add a new content in "en"
Title: "Hello world"
It generates route: "hello-world"

Then I create an another language version of it, say "ar"

Title: "شكرا"
It generates route: "hello-world-0"

So now you have two pieces of Content Item with two different route.

My question is this, can I go to "/hello-world" in "Arabic" culture and get the Arabic content instead of having to resort to "/hello-world-0"? 

Or is it by design that each language version of a ContentItem will get their own route?

**Comment by dodyg** [comment]
@hishamco

**Comment by hishamco** [comment]
I will vote for @sebastienros suggestion by introducing a language slug in the route for better SEO

@dodyg what you asking is doable but I don't think it will work with the current implementation, so I will ping @jptissot to answer this one

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/5071#issuecomment-567217465

**Comment by hishamco** [comment]
I am suggesting to use `RouteCultureProvider` so a language slug will be a part of the url, this will be unique from language to another

**Comment by dodyg** [comment]
> I will vote for @sebastienros suggestion by introducing a language slug in the route for better SEO

It's doable like this `{{ContentItem.Content.LocalizationPart.Culture}}/{{ ContentItem.DisplayText | slugify }}` (https://github.com/OrchardCMS/OrchardCore/issues/4589)

So let me confirm again, at the current implementation, each language version of a content item gets their route, correct?

**Comment by jptissot** [comment]
> So let me confirm again, at the current implementation, each language version of a content item gets their own route, correct?
@dodyg yes it does

We may need to improve the cloning handler when localizing and actually re-generate the autoroute based on the language.

**Comment by sebastienros** [comment]
I'd suggest to just regenerate the autoroute when it's cloned. If the pattern has a correct language tag, then the localized item will have it too automatically. And if not, then there will be a conflict, and the backup logic to add a version number will be used. There is a localization handler to do that.

However what I have seen multiple times is devs trying to automatically redirect from the home page (with a specific culture) to the one the browser is requesting. Maybe we could use a cookie to save the fact that it was the first time on the homepage, and then redirect to the request culture automatically. Not after, as subsequent navigation would be from explicit clicks. The cookie would be short-lived (session) so that the next visit it happens again.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/5089
