### ISSUE TITLE
Feature Request: By default treat Template and AdminTemplate as liquid file instead of Shape

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5093]
It would be nice to have Templates and AdminTemplates are identified and organized by file names by default instead of Shape.  So that liquid templates can be reused using file upload/download. 

e.g Currently It displays as `Content__Article`, How about showing it as file `Content-Article.liquid`,  and upload/download functionality can be added.

**Comment by jtkech** [comment]
Good idea and at some point we also thought about making a custom file provider serving content from the database as they were coming e.g from a liquid file, and maybe being able to group them in different documents so that we could create light themes by only using the admin UI.

**Comment by sebastienros** [comment]
What about displaying "also" the corresponding filename. And I like the idea of being able to download the shape, probably using the generated filename. To upload, copy pasting usually is sufficient, might be more work than necessary to add this.

I'd rather see you spend some time on the improvements that JT is mentioning, to be able to manage a theme dynamically with static files too, that would be stored in the db. There is an issue already open for this. This would replace these two modules actually.

**Comment by ns8482e** [comment]
> liquid file, and maybe being able to group them in different documents so that we could create light themes

@jtkech To support light themes - that includes only liquid and static assets - that do not require any compilation - the module discovery needs to be based on theme.json file and not based on assembly - needs changes in Module.cs

**Comment by jtkech** [comment]
@ns8482e 

This would not be a regular theme that would need to be discovered, but a feature that allows the following

About liquid, as i remember, it would just add templates with an higher priority (maybe lower than the existing templates feature), but grouped by light themes that could be enabled / disabled, and maybe with file naming conventions

Then yes we could also think about static assets, dynamic placements and so on, but would need to focus on it.

Would need more time to do this kind of interesting features but since a while i am mainly busy by distributed things, or just waiting for info to continue to work on it ;)

**Comment by ns8482e** [comment]
@jtkech I was assuming to have IModuleNamesProvider implementation that returns module object from different way of discovering  like module.json or folder instead of just assembly. But found that IModuleNamesProvider only returns names and module code is tied to Module.cs in constructor.

**Comment by Piedone** [comment]
https://github.com/Lombiq/Hosting-Media-Theme does this now. Do we need a built-in feature?
