### ISSUE TITLE
Index Entry Length for 'IDX_TextFieldIndex_Text' exceeds the maximum length of 900 bytes

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#5196]
Apparently Microsoft SQL server only allows for an index key field length of 900 bytes, while the OrchardCore.ContentFIelds "Text" datatype allows for a length of 4000 bytes to be stored (the rest is truncated, but it is stored in "BigText" column). 

This article discusses it: https://blogs.msdn.microsoft.com/bartd/2011/01/06/living-with-sqls-900-byte-index-key-length-limit/

I am guessing if we want to continue using the "Text" column as the "Index key column" for "IDX_TextFieldIndex_Text" that we would have to constrain it down to 900 in "OrchardCore.ContentFields.Indexing.SQL.TextFieldIndexProvider". It currently is:

```
Text = field.Text?.Substring(0, Math.Min(field.Text.Length, 4000)),
```

And would likely need changed to:
```
Text = field.Text?.Substring(0, Math.Min(field.Text.Length, 900)),
```

Or we could just remove the index completely but that would likely make the SQL searching on the Text field be slower. I am guessing the constraint to only storing the first 900 bytes would be best...

**Comment by Skrypt** [comment]
This limit changes if you are using SQL Server on premise or Azure SQL Server. So generally the 4000 bytes stands but it is specific to Azure SQL Server to allow for only 900 I think.

**Comment by jeffolmstead** [comment]
I am on local SQL Server Express, but live will be on Azure SQL (haven't tried it there). Apparently SQL Server 2016 and Azure SQL database have a maximum key size of 1700 bytes for nonclustered indexes and 900 bytes for clustered indexes.

It seems MySQL key length is 3072 bytes... Not sure on other databases.

To be safe, I am wondering if the lowest possible text length should be used. Otherwise users will be confused by these errors.

**Comment by Skrypt** [comment]
Ok for the change. Lowest value available.

**Comment by sebastienros** [comment]
This should be done in yessql, where we can ensure the data don't go over the limits as we know which dialect is used. But it would need some more metadata to ensure we are truncating it when an index is defined, not every time.

**Comment by sebastienros** [comment]
But if the index is defined in the migration, then I agree this would need to be handled in OC. And we would have to define a max size for any column like this ... not easy

**Comment by deanmarcussen** [comment]
No not easy. But yes should be yes sql. Worth noting that MySQL is currently completely broken due to the alias part length.

Been thinking of a YesSql fix but not found the right solution yet

**Comment by deanmarcussen** [comment]
I had a further look at this today.

I think we can do something in YesSql, essentially a builder option for creating indexes, which would allow you to specify options, like index column length (which is the appropriate fix for MySQL), but not the fix for MSSql. 

The fix for MSSql (and there are a few good options in the doc you linked @jeffolmstead ), could also be from this stackoverflow post https://stackoverflow.com/questions/2973520/how-to-resolve-900-key-length-limit-index-on-the-column-which-have-datatype-varc where you can add long columns using the `Include(col_name)` statement in the index.

the idea would be a `SchemaBuilder.AlterTable` overload that looked something like
```
            SchemaBuilder.AlterTable(nameof(TextFieldIndex), table => table
                .CreateIndex("IDX_TextFieldIndex_Text", i => i
                       .SetIndexColumnSize(250) <= only used by the mysql dialect
                       .SetIncludeColumn() <= only used by the sql dialect
                )
            );
```

I think this would be better than restricting the actual column sizes in the index table, as it would still allow you to execute a query `x => x.Text == "a really large value"` rather than stripping down the length of the `.Text` column itself. 

What would be really helpful is to know if there are similar issues with PostgreSQL before deciding on a solution. 

/cc @jptissot @MatthijsKrempel you are both PostgreSQL users, are you aware of index key length issues that we should be aware of?

**Comment by jeffolmstead** [comment]
@sebastienros do you know of any work around for this particular issue other than my switching over to using Source Code rather than MyGet and modifying the lines to make them work with Microsoft SQL? I need to release a project shortly and not sure of best approach.

**Comment by deanmarcussen** [comment]
@jeffolmstead still working on a long term solution for this.

but short term. the easy workaround is to delete the key indexes in ms sql. 
you will still have the table, and still be able to use Where clauses, they will just not be key indexed.

**Comment by deanmarcussen** [comment]
In terms of the actual long term solution.

I think the best way to do this might be to have two fields in the index
one called `Text` the other called `TextKey`

`TextKey` would be shortened via a substring to the largest value MySql and MS SQL can handle in the key index, but `Text` would still be the complete value for the text value.

So useful for using in a `Where` clause.

But the full value would still be available as well.

Your input be helpful here @sebastienros if that's an acceptable solution?
