### ISSUE TITLE
Get List of Articles by Category

### ISSUE THREAD

**Issue by OlziiNaran** [OrchardCMS/OrchardCore#5213]
Hello everyone, I created a set of categories (with nesting), and then added a few articles based on this category. Now I want to get a list of articles to which a category belongs. Currently, I will only filter by category Id. Ways to filter by category name? What should I do?

**Comment by dodyg** [comment]
I don't think this functionality exists yet. You can though implement a filter to do this. The code here will help https://github.com/OrchardCMS/OrchardCore/blob/688dbb32da17f8a3840f75485362104ea1a562b4/src/OrchardCore.Modules/OrchardCore.Taxonomies/Helper/TaxonomyOrchardHelperExtensions.cs. 

You will need to create a variation of https://github.com/OrchardCMS/OrchardCore/blob/688dbb32da17f8a3840f75485362104ea1a562b4/src/OrchardCore.Modules/OrchardCore.Taxonomies/Helper/TaxonomyOrchardHelperExtensions.cs#L93 that match the property you are looking for.

**Comment by sebastienros** [comment]
A technique that @dodyg has used by the past is create a route with both the if and the display name (as a slug) and then load the term using the id, while the url still contains the name for SEO purposes.

Another option would be for us to add the Displaytext in the TaxonomyIndex table, as there is no way otherwise to join it with the ContentItemIndex as terms are not stored there.

Or maybe we should index the terms in their own table, like we do for ContentItems, such that we could do joins with it, and we could also do queries on these terms and their parents/children.

**Comment by agriffard** [comment]
Related to #2818
