### ISSUE TITLE
Content List Regression

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5254]
Listable Widgets no longer display properly.

![image](https://user-images.githubusercontent.com/4681586/72184063-89aeef00-33bd-11ea-94d7-962fdbdfbbc3.png)

It seems the admin-for attribute does not work when the stereotype is a widget.

**Comment by jptissot** [comment]
Hmm I am trying this locally and it works fine 🤔 But the deployed version does not work.

**Comment by jptissot** [comment]
Ok, It happens locally in release mode only.

**Comment by Skrypt** [comment]
CDN issue probably then

**Comment by jptissot** [comment]
Hmm why isn't the admin-for helper working in release mode only. Not cdn imo

**Comment by Skrypt** [comment]
Missing a reference to the project defining this TagHelper.

**Comment by jptissot** [comment]
This is in the ContentItem list.

**Comment by jtkech** [comment]
Yes, i think @Skrypt is right, `OC.Widgets` needs to reference `OC.Contents` that defines the `ContentLinkTagHelper`, referencing it in the `_ViewImports` is not sufficient.

It works in dev mode because views are compiled at run time so in the context of the application, while published `.Views.dll` have been precompilled in the context of their related module / theme.

**Comment by jptissot** [comment]
Ah very interesting. Thanks for the explanation.
