### ISSUE TITLE
Cloning does not validate fields

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5267]
The error I encountered was related to the Autoroute. The pattern used was not properly slugifying and allowed some spaces in the text. Cloning the content type allowed for the ContentItem to be saved without validating the Autoroute.

**Comment by deanmarcussen** [comment]
Yes cloning happens in the handler, and the same applies for `Autoroute` Pattern generation as it is also in the handler.

We have validation in the drivers, but no good way to surface a validation error in a handler (as it may be called from many contexts).

So the actual issue is the original content items Autoroute pattern was not validated. 

As when it clones it just takes a copy of the original path, and does not apply the pattern, it uses the existing path, and tacks a `-1` on the end of it.

**Comment by sebastienros** [comment]
I think we should live with it. Maybe create a workflow when a content item is created to do some custom validation? I don't see anything that could be done and be of any help here.
