### ISSUE TITLE
Cannot create new taxonomies

### ISSUE THREAD

**Issue by Sibren** [OrchardCMS/OrchardCore#5272]
Hi,

I've installed version 1.0.0-rc1-10004 via NuGet and it's working fine.

Now I want to create tags for my blog, I've read I should use taxonomies for it.
So I enabled them in features, in all the explanations, such as https://www.davidhayden.me/blog/taxonomies-in-orchard-core-cms or in the [Youtube-video](https://www.youtube.com/watch?v=N8BQtmpBFuo&feature=youtu.be&t=40m20s), it now shows a Taxonomy Content Type. This does not appear.

It however appears under parts. Somehow I managed to get two items in there, but for the life of me I cannot remember how that happened, or where I can find them. I think I might have deleted those, but I am unsure.

Can somebody help me out?

You can find a video of what I am seeing [here](https://webm.red/HuGC).

**Comment by Sibren** [comment]
Oh, I am using .NET Core 3.1.

I've also tried installing the OrchardCore Taxonomies-nuget, but to no avail.
OrchardCore.Taxonomies.dll and OrchardCore.Taxonomies.Views.dll are in my bin-folder.

**Comment by sebastienros** [comment]
When the feature is enabled, the Taxonomy type should already be there. Otherwise you could also create a custom type with the TaxonomyPart, but don't do it.

Please try it on https://try.orchardcore.net to confirm it's an issue on your side. I'd also suggest to use the latest version on myget, or from the source code (github).
