### ISSUE TITLE
Orchard.ConsoleLog(shape) producing error.

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#5285]
Following the guide here to show shape in chrome browser :

https://orcharddojo.net/blog/consolelog-helper-issectiondefined-method-this-week-in-orchard-03-01-2020

I am getting the following error : 

![image](https://user-images.githubusercontent.com/1516981/72342648-9b520880-36d5-11ea-8d90-9d18cd2a903c.png)

@deanmarcussen

**Comment by deanmarcussen** [comment]
Probably means the collection was changed during execution.

There are going to be some unresolved collections, or collections that get altered. if you call it directly on `Model` possibly, because `Model` hasn't been executed.

Model itself is executed by the `Item.cshtml` in the `Orchardcore.Contents`

You maybe better using `Model.Content` or the name of the zone you have in there.

**Comment by giannik** [comment]
Hmm, think i get it.
Im using it with the content of a zone wrapper.
When changing to 
@Orchard.ConsoleLog((object)Model.Metadata.ChildContent)  
I was getting something in the log.
Thanks Dean.

**Comment by deanmarcussen** [comment]
ok, yes, it's not ideal. but the only other option is to call the log from outside the zone wrapper, by whatever is rendering the zone.
