### ISSUE TITLE
Partial views in modules not found when using RazorShapeTemplateViewEngine.RenderViewToStringAsync()

### ISSUE THREAD

**Issue by PaulEpitomy** [OrchardCMS/OrchardCore#5296]
When RenderViewToStringAsync sets up the ViewContext the route data does not include the "Area", I believe this is preventing the modules locations being matched.

If I change GetActionContextAsync from:

```
routeData = new RouteData();
routeData.Routers.Add(new RouteCollection());

httpContext = _httpContextAccessor.HttpContext;
```

to: 
```
var httpContext = _httpContextAccessor.HttpContext;

routeData = new RouteData(httpContext.GetRouteData());
routeData.Routers.Add(new RouteCollection());
```

The partials in modules are now matched, however I'm not aware of the possible consequences of this change.
As a work around I've simply copied the partial to the theme.

**Comment by Skrypt** [comment]
So basically you would take the RouteData from the current HttpContext and pass it back which makes sense. I'm not sure why it was not done that way.

**Comment by PaulEpitomy** [comment]
Yes exactly, what I'm actually trying to do is to render a shape to a string
```
using (var sw = new StringWriter())
{
      var htmlContent = await _displayManager.ExecuteAsync(displayContext);
      htmlContent.WriteTo(sw, HtmlEncoder.Default);
      var result = sw.ToString();
      return result;
}
```

**Comment by jtkech** [comment]
No time right now but i will take a look asap.

As i remember `RenderViewToStringAsync()` is intended to be used when there is no view context e.g through graphQL, then `GetActionContextAsync()` will check if there is an ambient action context otherwise it creates a new one without having to retrieve route data.

Where and in wich context do you use this code? How do you get a `displayContext`?

Meanwhile see the `ControllerExtensions.SendEmailAsync()` if it can help and that does

            var smtpService = controller.ControllerContext.HttpContext.RequestServices.GetRequiredService<ISmtpService>();
            var displayHelper = controller.ControllerContext.HttpContext.RequestServices.GetRequiredService<IDisplayHelper>();
            var htmlEncoder = controller.ControllerContext.HttpContext.RequestServices.GetRequiredService<HtmlEncoder>();
            var body = string.Empty;

            using (var sw = new StringWriter())
            {
                var htmlContent = await displayHelper.ShapeExecuteAsync(model);
                htmlContent.WriteTo(sw, htmlEncoder);
                body = sw.ToString();
            }

            ...

**Comment by PaulEpitomy** [comment]
I think that may have been where I originally got the code from.

The full code is: -
```
    public class ShapeRenderer : IShapeRenderer
    {
        private readonly IHtmlDisplay _displayManager;
        private readonly IDisplayHelper _displayHelper;

        public ShapeRenderer(IHtmlDisplay displayManager, IDisplayHelper displayHelper)
        {
            _displayManager = displayManager;
            _displayHelper = displayHelper;
        }

        public async Task<string> RenderAsync(Controller controller, IShape shape)
        {
            var displayContext = CreateDisplayContext(controller, shape);

            using (var sw = new StringWriter())
            {
                var htmlContent = await _displayManager.ExecuteAsync(displayContext);
                htmlContent.WriteTo(sw, HtmlEncoder.Default);
                var result = sw.ToString();
                return result;
            }
        }

        private DisplayContext CreateDisplayContext(Controller controller, IShape shape)
        {
            return new DisplayContext
            {
                ServiceProvider = controller.ControllerContext.HttpContext.RequestServices,
                Value = shape,
                DisplayAsync = _displayHelper
            };
        }
    }
```

**Comment by jtkech** [comment]
Sorry i didn't have any time to test it, i will do.

Yes, discovering a shape is not the same as discovering a controller view / partial view, but at the end if a shape is discovered and there is a view context we do `htmlHelper.PartialAsync()`.

So try to use `ShapeExecuteAsync` as in my above example.

Also, which version do you use? Because in the dev branch, when there is no view context, to 1st get an action context we now check if there is an ambient one through `IActionContextAccessor`.

**Comment by PaulEpitomy** [comment]
I've tried this in both the nuget 1.0.0-rc1-10004 and dev branch, same issue. 

I've tested using ```ShapeExecuteAsync``` and it has the same issue, although much cleaner implement so I've stuck with that!

Re-reading the title I wrote it's not clear what I'm actually doing, so: -

1. Rendering a Shape from a Controller to a string.
2. The Shape includes the use of a partial
3. When the partial is in a module it is not found.

**Comment by jtkech** [comment]
What i can say to give more infos, as i remember

- To be discovered a shape needs to have a shapeType and then, if related to a template file, this template file needs to be under a module `/Views` folder or under the current theme `/Views` that has precedence.

- To be discovered an mvc view has to be in the module defining the controller action and under the right folder e.g `/Views/{controller}/{action}.cshtml` or under the current theme `/Views/{module}/{controller}/{action}.cshtml` that has precedence. Or under another module but under its `/Views/Shared/` folder. Then any partial view with a given relative path needs to be under one of the above folder.

**Comment by sebastienros** [comment]
Please comment when this issue can be closed

**Comment by jtkech** [comment]
I close it because i think there is a mixing on how shapes / mvc views / partial views are discovered.

In the above comment, `1. Rendering a Shape from a Controller to a string` seems to work. Then `The Shape includes the use of a partial. When the partial is in a module it is not found` doesn't work. But if rendered as an mvc partial view it has to be found in the module defining the controller and relative to the  `/View/{controller}` folder or as suggested in another module under the `/Views/Shared` folder.

Just tried in the `OC.ItemController` by doing a `displayHelper.ShapeExecuteAsync(new ShapeViewModel("Testing"))` so by rendering a shape from a controller, the `Testing` shape template being just under the `/Views` folder to be discovered as a shape. Then in this shape by doing `@await Html.PartialAsync("Partial")`, the partial view being under the `/Views/Item` folder to be discovered as an mvc view. Then the same test with the partial view in another module but under its `/Views/Shared` folder. Both tests work.

The proposed change in our `GetActionContextAsync()` suggests, when there is no action context and we create a new one, to update the action context route data with the ambient ones, in place of using a new empty route value dictionary as we do. This change would make sense but while doing my above tests with the last dev i never hit this part of code, when creating a view context on the fly, the ambient action context was always retrieved through the `IActionContextAccessor`, so no new action context was created.

@PaulEpitomy feel free to re-open it if i misunderstood something ;)
