### ISSUE TITLE
Custom ITranslationProvider

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5303]
Hi,

I'm trying to replace the PoFilesTranslationsProvider with my own implementation. How can I replace the registered provider?

I tried to replace the ServiceDescriptor, but without success.

`services.AddOrchardCms();
services.Replace(ServiceDescriptor.Singleton<ITranslationProvider, ServiceTranslationProvider>());`

Thnx,
Arjan

**Comment by jtkech** [comment]
It is registered at the tenant level so you can't replace it here  at the application level. You would have to use a module whose startup.ConfigureServices() runs after the one that registers the original service, can be done bu adjusting the startup `Order` property that is overridable, or better in your manifest file have a dependency on the module registering this service.

Or you can still do it from the application but by using one of our helper so that it is executed as it was in a module startup, something like this

    .AddOrchardCms()
    .AddOrchardCore()
    .ConfigureServices(s =>
        {
            s.Replace(...);
            ...
        }, order: 100); // e.g 100 or more to run after

In the last dev there a version of `.AddOrchardCms()` that returns an `OrchardCoreBuilder` so that you could just use

    .AddOrchardCms()
    .ConfigureServices(s =>
        {
            s.Replace(...);
            ...
        }, order: 100); // e.g 100 or more to run after

**Comment by hishamco** [comment]
You could use what JT is suggested above if you 're working with the NuGet packages, otherwise you can replace it directly from within the localization module itself if you working with source

**Comment by ArieGato** [comment]
I achieved it by adding a new module with a dependency to the Localization module. I don't want to alter any OrchardCore code.

I have an additional question though. Is there a way to invalidate the cached translations? Should I remove it from MemoryCache, or force a restart of the tenant like in the settings section?

**Comment by hishamco** [comment]
Please you file a new issue for your second question

I will close this while it's answer, feel free to reopen if the issue not resolved
