### ISSUE TITLE
How to delete existing Theme in CMS? 

### ISSUE THREAD

**Issue by kyahyan** [OrchardCMS/OrchardCore#5313]
everytime i dotnet build 
![Screen Shot 2020-01-17 at 2 53 20 PM](https://user-images.githubusercontent.com/23460968/72590629-25e67200-3939-11ea-992c-ee0a1b5b1dc1.png)
it takes time

**Comment by Skrypt** [comment]
That's the drawback of using a compiled language. Orchard Core is a quite big project so it is normal. To be more productive you should follow our guide on how to use Nuget packages instead so that these modules be already compiled for you. The only thing it would compile then is your own modules / themes.
