### ISSUE TITLE
There is no way to export custom site settings like Login settings

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#5325]
Couldn't find a way to create a deployment plan where I can export settings other than general settings. One example could be exporting Login/Registration settings. Site Settings deployment step UI only offers to check the general settings.

What I could do is to write the JSON manually so when I import the recipe the `SettingStep` catches them and imports them to the Site entity.

```
    {
      "name": "settings",
      "LayerSettings": {
        "Zones": [ "Header", "Messages", "Footer" ]
      },
      "LoginSettings": {
        "UseSiteTheme": true
      }
    }
```

So this is imported perfectly but there is no way to create an export file containing the LoginSettings JSON property using the UI.

**Comment by Skrypt** [comment]
Probably related to the fact that these are IEntity.Properties.

**Comment by sebastienros** [comment]
Suggestion is to be able to opt-in to a generic Step that will export and import a named setting from ISite. Can provide a localized display name. 

```
exportSettingsOptions.Register("LayerSettings", T["Layer settings"]);
```

It's provided by the Settings module.

**Comment by agriffard** [comment]
@Piedone: Do you plan to provide a PR with this export Settings feature with opt-ins ?

**Comment by Piedone** [comment]
I don't think I'll work on this in the short term.

**Comment by aderderian** [comment]
@Piedone anyway we can take your simple option now and just exclude secure settings until that issue is solved?

**Comment by Piedone** [comment]
Excluding secure properties would be tricky, we've talked about that during the meeting, hence the other explicit registration concept you can see above. However, if you want to use this you can quickly exclude whole settings classes in this expression: https://github.com/OrchardCMS/OrchardCore/pull/6412/files#diff-3526fa9f74877b737cc1de3f7c3b0431R12 Otherwise if you just want a quick and dirty solution you can just use this and change the exported JSON by hand as you see fit. (Note that you can put this cshtml file into an admin theme of yours and thus override the built-in deployment step, you don't need to wait for the ultimate solution here.)

**Comment by Piedone** [comment]
Fantastic @agriffard!

**Comment by aderderian** [comment]
You rock! Thanks for doing this guys!!
