### ISSUE TITLE
Your documentation and examples are a joke

### ISSUE THREAD

**Issue by superluminalK** [OrchardCMS/OrchardCore#5355]
I am following your getting started & how to's that are quite frankly a joke.
How do you expect adoption if you basic examples do not work?

I am using VS2017, or 2019, doesnt matter.

https://orchardcore.readthedocs.io/en/dev/docs/getting-started/
https://orchardcore.readthedocs.io/en/dev/docs/getting-started/templates/#adding-orchard-core-nuget-feed

I am installing from here 
https://www.myget.org/F/orchardcore-preview/api/v3/index.json

On install, the packages that are added are NOT the same as in the image video on this page, here at this section
https://orchardcore.readthedocs.io/en/dev/docs/getting-started/templates/#adding-orchard-core-nuget-feed

When I add these to my startup they both fail

services.AddOrchardCms();

Error	CS1061	'IServiceCollection' does not contain a definition for 'AddOrchardCms' and no accessible extension method 'AddOrchardCms' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	

app.UseOrchardCore();

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseOrchardCore' and no accessible extension method 'UseOrchardCore' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	

If your going to release software, please test your install instructions, anyone would think you are Microsoft

**Comment by Skrypt** [comment]
@superluminalK How do you expect people to respond to you with this kind of title? The software is still in development so you should expect that some things might not work perfectly. These documentations are accurate and works for most people maybe there is a detail that you forgot. I'm keeping this open but if you expect to get free help from us, show some respect.

**Comment by jptissot** [comment]
And, since this is free and open source software, if you think something is lacking you are welcome to contribute.

**Comment by sebastienros** [comment]
@superluminalK looks like the packages didn't get restored correctly. If you don't know how to do this please ask and I am sure someone will help you if not myself.

Maybe try to build from the command line (dotnet build) if VS doesn't seem to restore things correctly, or double check that the feed is valid in your Nuget settings.

**Comment by mikecasas** [comment]
@Skrypt @sebastienros sorry for the above, i will have a talk with mom when i get home.

**Comment by ns8482e** [comment]
@superluminalK It's joke if it causes amusement for you then forget it as  like every other jokes.  But if you opened this issue with frustration then definitely it's not a joke - see it as an opportunity to seek help or provide help by contributing to documentation.

**Comment by microwales** [comment]
Hey Guys,
Lets ignore trolls.
I have this issues even though installed the package from nuggets. Apparently a very old version was installed. Once I installed latest 1.0.0-rc2-13450, the error cleared off. Hope this help someone.

be respectful when using a software written by others for free.

**Comment by Skrypt** [comment]
Well we moved to cloudsmith Nuget packages repository. And the instructions about adding a Nuget feed has been removed from that documentation ... These .gif are now quite old. I've made them 2 ~ 3 years ago but they are still relevant for some I think. Maybe the documentation was crap at that time because it was not accurate but that's truely a shame that some people act like this. At the same time, without being condescendent, I'm pretty sure that someone who knows what he's doing could easily have found the issue and report them. Yes, we forgot to update the documentation after moving to Cloudsmith and I'm pretty sure if I'm watching all these videos I will find things that could be updated. But the idea is about to understand the principle, not to carry your hands through it.

And to be honest after this post I stopped making documentation because it pissed me off a little. I'm the one who did this documentation to help people that know nothing about .NET Core to have some starting point. Maybe I should not have done it and let them figure everything out ... don't shoot the messenger like they say 😉
