### ISSUE TITLE
ArgumentNullException when using blank recipe on an empty site

### ISSUE THREAD

**Issue by CarlHA** [OrchardCMS/OrchardCore#5400]
When using the blank recipe on an empty web site the following exception is thrown:-

`ArgumentNullException: Value cannot be null. (Parameter 'contentItemId')
OrchardCore.ContentManagement.DefaultContentManager.GetAsync(string contentItemId) in DefaultContentManager.cs, line 92`

All the other recipes seem to work as they have a HomeRoute setting which is missing from the empty recipe.

**Comment by deanmarcussen** [comment]
This is intentional that we don’t have a home route by default in the blank recipe, however we could check the value when null to return not found instead of an exception.

Probably a check in the item controller for a value on contentitemid before trying to retrieve would be useful as well, as there was a recent change to return a null ref from the content manager

**Comment by CarlHA** [comment]
Created Pull request #5402

**Comment by agriffard** [comment]
Thanks.
Tip: When you do a PR, add 'Fixes #{IssueNumber}' in the description and the issue will be linked automatically and closed when the PR is merged.
