### ISSUE TITLE
Application Settings Fail if Tenant Not Present

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#5419]
Say I want to override some configurations in App Settings (let's user GraphQL as en example). If I use these settings:

```
{
  "OrchardCore": {
    "TenantName": {
      "State": "Placeholder",
      "OrchardCore.Apis.GraphQL": {
        "DefaultNumberOfResults": 1000,
        "MaxNumberOfResults": 10000
      }
    }
  }
}
```

This works out perfect if "TenantName" exists. However, if "TenantName" is not currently a tenant (i.e. if you are setting it up in advance or if you remove a tenant) ALL websites will not function. 

Ideally, Orchard Core would just ignore this section if the "TenantName" does not exist.

**Comment by jtkech** [comment]
Yes, it is intended to preconfigure a tenant so you have to set a valid state as `Uninitialized`, then when you setup the tenant, disable / re-enable it and so on, the current state in `tenants.json` has precedence.

But if the tenant has not been setup or manually removed, the tenant still appears in the tenants index page. Hmm, but maybe better to also have the ability to not display it under the tenants index.

Or maybe not so that we can see under the admin all unititialized tenants that have not been setup but that have preconfigured values, if so here you just have to replace `Placeholder` to `Uninitialized`.

Let me know, it would be easy to fix, already tested it.

Hmm, anyway seems to be good to allow both cases and then prevent the site from failing if the state is not a valid state, i will do a PR.

**Comment by jeffolmstead** [comment]
Fascinating, I only used "Placeholder" as that is what the [documentation showed](https://orchardcore.readthedocs.io/en/dev/docs/reference/core/Configuration/#ishellconfiguration-in-the-orchardcorecmswebcsproj-startup-project) to utilize, I did not realize it was actually tied the tenant state. 

So maybe we can just update the documentation to set it to "Uninitialized" and that will resolve it since it would be overridden by tenants.json. Would it still show up in the tenant list as uninitialized though if the folder doesn't exist / is removed. 

My personal preference is to not be required to provide the "State" in appsettings, I just wanted to put some settings in effect for when the tenant went live. It seems from the documentation it is a requirement to have this though, maybe after your pull request I wouldn't even need to add "State". Thanks for bringing me up to speed and looking into this!

**Comment by jtkech** [comment]
> Would it still show up in the tenant list as uninitialized though if the folder doesn't exist / is removed

Yes

> My personal preference is to not be required to provide the "State" in appsettings

It is required if you want to preconfigure more or less a tenant before it really exists.

E.g you can provide some settings as the prefix, connection string so that there are not requested again on setup, in that case you need to set the state to `Uninitialized`.

Note: E.g the connection string can be provided more globally, but not the prefix that is tenant specific, but it is planed to be able to provide e.g a liquid pattern that we could resolve.

Also used e.g in an mvc app without any admin and by using `.WithTenants()` where you have to provide all required settings and set the state of a given tenant to `Running` to make it running.

> I just wanted to put some settings in effect for when the tenant went live

But yes, if you don't want that these settings are recognized as tenant settings from the beginning, you could just omit the state field.

This would not work for a setting belonging to the form we display when we create a tenant, the setting will be requested and then overridden on saving. Hmm, but if you don't fill any value maybe your configured value will be used on setup coz your tenant has been created before.

Otherwise for any other config values e.g related to a feature, normally your config values will be taken into account when the tenant exists.

So my PR is just to not fail on an invalidate state knowing that if we want to provide preconfigured value for a given tenant we have to specify a valid state for this tenant (as before).
