### ISSUE TITLE
TitlePart driver tries to update editor even if the TitlePartOption is not Editable clearing the DisplayText content

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#5482]
When you set the TitlePartOption to GeneratedDisabled the content item editor displays the disabled TitlePart editor which is fine but when Saving/Publishing the content item the title becomes empty. 

This is because the TitlePartDisplay.UpdateAsync runs the model updater and since the field is disabled it won't be updated so an empty string will be set to ContentItem.DisplayText.

Solution would be to check if the TitlePartOptions is Editable and only then run the model updater.

**Comment by Skrypt** [comment]
No, you should never skip an event as it is called for a reason. Here if you don't call the UpdateAsync event then it would omit indexing the content item in Lucene.

**Comment by barthamark** [comment]
Do you have a suggestion for solving this issue? Maybe changing disabled to readonly? Now it will mess up the DisplayText on save which also not good.

On the other hand, what is the purpose of making a TitlePart driver disabled exactly? User can remove the disabled property from the DOM and update the title anyway so the purpose is not security-related then a readonly could work.
I still think that skipping UpdateAsync if the TitlePartOption is not Editable is a good approach. Since we are in the TitlePartDriver this should worry about the TitlePart editor. The Lucene indexing should worry about indexing the DisplayText not the TitlePart.Title (which is a copy of the DisplayText).

**Comment by deanmarcussen** [comment]
I am confused, because I would anticipate that the `UpdateAsync()` event handler would still generate the title after it has been set empty by the disabled issue.

While it seems a bit odd to be setting the title empty, and regenerating it everytime, but I think that is the point with a generated title, as the fields which are used in generation may have changed, therefore requiring the title to be regenerated.

See the `TitlePartHandler.UpdateAsync()` for where it does this.

But if there is still some reason that it makes sense, to handle the disabled then...

> Solution would be to check if the TitlePartOptions is Editable and only then run the model updater.

This would probably be the solution.

So long as the driver still returns `Edit(model, context);` all the `UpdateAsync()` event handlers will be called, (which will trigger the pattern to generate the title), so as I said I am confused as to exactly what is going wrong

**Comment by barthamark** [comment]
My mistake, sorry. I got confused by the purpose of this option. I thought that it can be used separately from the title generation logic - leave the title generation pattern empty and the tilte can be disabled to only show the title as "read only" and not for editing. The title was emptied out because there was no pattern given. 

So I guess we can close this issue. Thank you @Skrypt and @deanmarcussen .
