### ISSUE TITLE
Rename Tenant: Check existing content item url

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5491]
When we create a tenant with a url prefix, we should check that there is no existing url that already has this permalink an vice-versa, when we create a content item in order to prevent conflicts.

There is also a strange behaviour:
- Create a tenant with the url prefix `blog`.
- Set it up.
- Rename it `blog2` .
=> The url `/blog` will continue to work and any urls like this also: `/blog/azerty` returning the homepage.

**Comment by sebastienros** [comment]
There might be a way to check if a route is defined anywhere in the system.

**Comment by jtkech** [comment]
> There might be a way to check if a route is defined anywhere in the system.

Yes but maybe not necessary, this is just that the tenant prefix takes precedence which makes sense. Then you just have to change the item url or the tenant prefix, but we have to fix the below issue.

Note: Otherwise, each time we save an item, would we need to check that its autoroute path is not in conflict with a tenant prefix?

Here the main issue is that the old prefix (even it is not equal to `blog`) is still working, and if you change it n times, the n previous ones are still reacheable. But that's okay if you stop and restart the application.

**This is because when changing the prefix we don't remove the old one from the running shell table. I will fix it if i have time**.
