### ISSUE TITLE
Shape execution is invalid if executed more than once in a request

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#5516]
What I am trying to do is to generate two content item shapes using `IContentItemDisplayManager` and render it in a service (i.e. not in an MVC view) usiing `IDisplayHelper`. Something similar to this:

```
var shape1 = await displayManager.BuildDisplayAsync(myContent1, null, "Detail");
var htmlContent1 = await _displayHelper.ShapeExecuteAsync(shape1);
var shape2 = await displayManager.BuildDisplayAsync(myContent2, null, "Detail");
var htmlContent2 = await _displayHelper.ShapeExecuteAsync(shape2 );
```

The value of htmlContent1 is correct HTML content of the shape but the value of htmlContent2 will be `Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers.ViewBuffer`.

**Comment by jtkech** [comment]
Hmm, if you are using the theme engine and you are rendering content items you will use twice the current theme layout that will be already processed in the second pass.

But `ViewBuffer` is also an `IHtmlContent`

    IHtmlContentBuilder => IHtmlContentContainer => IHtmlContent

So, I tried the following in the `ItemController`

            var displayHelper = HttpContext.RequestServices.GetRequiredService<IDisplayHelper>();
            var htmlEncoder = HttpContext.RequestServices.GetRequiredService<HtmlEncoder>();

            var shape1 = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, _updateModelAccessor.ModelUpdater, "Detail");

            string contentString1 = null, contentString2 = null;

            using (var sw = new StringWriter())
            {
                var htmlContent1 = await displayHelper.ShapeExecuteAsync(shape1);
                htmlContent1.WriteTo(sw, htmlEncoder);
                contentString1 = sw.ToString();
            }

            var shape2 = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, _updateModelAccessor.ModelUpdater, "Detail");

            using (var sw = new StringWriter())
            {
                var htmlContent2 = await displayHelper.ShapeExecuteAsync(shape2);
                htmlContent2.WriteTo(sw, htmlEncoder);
                contentString2 = sw.ToString();
            }

It works but i needed to use a non null `ModelUpdater` and i needed to do a little fix because, with my curent theme layout, a view was not able to add an element to a layout zone that was already processed.

For this last issue i think it has been introduced by a recent change where we pre-process all layout zones so that any zone can register any resources (e.g HeadScript). Just tried with GraphQL where you can render multiple items in the same scope, same issue. I already have a fix but i will dig into it more in details.

**Comment by jtkech** [comment]
@barthamark 

Beyond the other issue i fixed in another PR, just to say that your `htmlContent1` and `htmlContent2` are both `IHtmlContent` that you can use as in my above example.

So i will close this issue when merging my other PR but feel free to re-open it if you still have an issue.

**Comment by barthamark** [comment]
@jtkech thank you it works perfectly.
