### ISSUE TITLE
Anonymous user can get a content item using the content item ID

### ISSUE THREAD

**Issue by domonkosgabor** [OrchardCMS/OrchardCore#5543]
When you call the api/content/{contentItemId} endpoint using just a browser, Orchard Core will show you the content item with the associated content item ID. That's because in that API we check for the ViewContent permission and an Anonymous user has that permission. I think we should not return the content item for anonymous users.

**Comment by sebastienros** [comment]
You can remove the permission for Anonymous users if you don't want it. That a default set in a recipe, but it can be changed.

**Comment by Piedone** [comment]
If you want content items to be visible on the frontend for the general public then you have to add the ViewContent permission for anonymous users (what most of the websites need). The problem is that this automatically and without the option to turn it off lets anonymous users fetch all the data stored in that content item, basically in the storage format, even if it's never displayed on the frontend, via the API.

So the issue is that if you let certain users see a given content item in the Detail display type then suddenly they also have access to every other data stored in that item. This includes technical properties an end-user should never or not necessarily see (all the metadata including dates, owner), data in a storage format which is not necessarily displayed in the same way to the user, or data which should remain hidden from users (imagine storing audit trail or some editor workflow details, analytics data in the item). You now have to operate under the assumption that if you want certain users to access any piece of a content item then they'll have access to all of it.

**Comment by mawendel** [comment]
I'll just jump in and say, that from a security standpoint it should *never* be the default state to allow access for anonymous users anywhere. 

If what @Piedone says is true and it is somehow now possible to get access to the entire raw json, that is another security and/or privacy risk.

**Comment by carlwoodhouse** [comment]
tend to agree with @Piedone that allowing someone to see something in the frontend / vs retrieve all the data on the api endpoint is not the same thing ..

We get round this in the graphql api by having an additional permission of 'can execute graphql queries' which is not enabled by default for anonymous users. In order to see content there they need that permission *and* the appropriate ViewContent permissions .. I wonder if the same approach could work here.

**Comment by sebastienros** [comment]
Agreed, let's make another permission then.

**Comment by sebastienros** [comment]
And this permission should not be available on the anonymous user by default.

**Comment by sebastienros** [comment]
The permission should be called: 
`GetApiContent`

**Comment by ns8482e** [comment]
IMO user permission are functional and no technical, so defining api permission to user to solve technical problem is not correct way to fix the problem. Api should be protected by shared key.

Api can be called from a console app, background worker or logic apps, that may not have user context
