### ISSUE TITLE
Error when creating custom content type: An item with the same key has already been added. Key: Product'

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#5554]
I am following the documentation on how to create a custom content type via migrations.cs file for a new custom module I am working on. 

According to the documentation [here](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/ContentTypes/#consuming-content-parts-and-fields-from-csharp) I can do the following: 

` _contentDefinitionManager.AlterTypeDefinition("Product", type => type
    .WithPart("Product", part => part
        .WithField("Image", field => field
            .OfType("MediaField")
            .WithDisplayName("Main image"))
        .WithField("Price", field => field
            .OfType("NumericField")
            .WithDisplayName("Price"))
    )
);`

and then in order to  get strongly typed versions of Content Parts and Fields from the above type definitions I can create a class for my new Part as follows: 
```
public class Product : ContentPart
{
    public MediaField Image { get; set; }
    public NumericField Price { get; set; }
}
```

However when the migrations is ran I get the following error thrown in ContentPartFactory.cs: 

> Exception has occurred: CLR/System.ArgumentException
> Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll: 'An item with the same key has already been added. Key: Product'
>    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
>    at OrchardCore.ContentManagement.ContentPartFactory..ctor(IEnumerable`1 contentParts, IOptions`1 contentOptions) in /home/josh/Desktop/LefeWareLearning/LefeWare-Learning-CMS/src/OrchardCore/OrchardCore.ContentManagement/ContentPartFactory.cs:line 38

The same happens if I rename my part to ProductPart. I could of course rename it to ProductDetailsPart and it works. However, the documentation should reflect this if it is not possible to do so.

**Comment by jtkech** [comment]
We can add fields to a part, and to be able to add fields directly to a content type, each content type has a special content part whose name is the same as the content type itself.

So yes, the part that has the same name as the type it belongs already exists, it's a reserved name.

**Comment by JoshLefebvre** [comment]
The documentation does not reflect this fact. It insinuates that this can be done using the following:
```
 _contentDefinitionManager.AlterTypeDefinition("Product", type => type
    .WithPart("Product", part => part
        .WithField("Image", field => field
            .OfType("MediaField")
            .WithDisplayName("Main image"))
        .WithField("Price", field => field
            .OfType("NumericField")
            .WithDisplayName("Price"))
    )
);
```

Looking in Migrations file for Form content item I see the same thing:
```
            // Form
            _contentDefinitionManager.AlterPartDefinition("FormPart", part => part
                .Attachable()
                .WithDescription("Turns your content item into a form."));

            _contentDefinitionManager.AlterTypeDefinition("Form", type => type
                .WithPart("TitlePart")
                .WithPart("FormPart")
                .WithPart("FlowPart")
                .Stereotype("Widget"));
```

With a ContentPart:
```
    public class FormPart : ContentPart
    {
        public string Action { get; set; }
        public string Method { get; set; }
        public string WorkflowTypeId { get; set; }
    }
```

**Comment by jtkech** [comment]
Oups sorry i was wrong, so this is not a reserved name and you have to use it if you want to add fields to the content type, this by code through a migration.

I was not able to use `.WithPart("Product", part => part.WithField()` because here part is a `ContentTypePartDefinitionBuilder` on which `WithField()` doesn't exist, it only exists on a `ContentPartDefinitionBuilder`.

**I tried it on a recent version of the dev branch, so maybe because you have an older version, anyway the doc will have to be updated**.

What i could try and that works (with only one field for testing)

            _contentDefinitionManager.AlterTypeDefinition("Product", type => type
               .WithPart("Product"));

            _contentDefinitionManager.AlterPartDefinition("Product", part => part
               .WithField("Price", field => field
                   .OfType("NumericField")
                   .WithDisplayName("Price")));

![ProductType](https://user-images.githubusercontent.com/8586360/74597375-cf1aa800-505e-11ea-96b5-234f09671907.png)

**Comment by deanmarcussen** [comment]
So I see what is going on here because I may have made the same mistake myself.

The docs are not totally correct, there is a PR here https://github.com/OrchardCMS/OrchardCore/pull/5496 to update them, but the PR also needs a tweak before merging. (I will do this as I have time)

There is a name conflict @JoshLefebvre when you try to name your strongly typed part `"Product"` because that will conflict with the auto created part to hold the `ContentType` fields.

If you want to have some strongly typed fields attached to a `ContentType` you just need to get the naming correct, for both the migration and the name of the `ContentPart`

So I adjust you code a little to this, and I think you will find it works (with your strongly typed part).

```
_contentDefinitionManager.AlterTypeDefinition("Product", type => type
    .WithPart("ProductPart") <= this also must not be named Product ***
);

_contentDefinitionManager.AlterPartDefinition("ProductPart", part => part
    .WithField("Image", field => field
        .OfType("MediaField")
        .WithDisplayName("Main image")
    )
    .WithField("Price", field => field
        .OfType("NumericField")
        .WithDisplayName("Price")
    )
);

public class ProductPart : ContentPart <= this must not be named Product or it conflicts
{
    public MediaField Image { get; set; }
    public NumericField Price { get; set; }
}

```

*** the exception here is you can name it `Product` but you are then attaching fields to a reserved name and in this case you cannot make a strongly typed class to match it.

**Comment by deanmarcussen** [comment]
after merging the fix to the docs I tried this with both a strongly type class called `Product` and `ProductPart`.

both work (the difference being that the `ProductPart` can be attached to multiple content types, and the `Product` is the reserved name for fields only attached to the `Product` content type.

Can you confirm what version of OC you are using @JoshLefebvre ?

There was a recent update to `AddContentPart` that may have resolved the duplicate key error you are having

**Comment by JoshLefebvre** [comment]
Okay yes this is exactly what I figured. I am currently using the latest Master release. I will try merging in this PR myself to the forked version I have and see if it works!

Cheers, thanks for the help and clarification guys!
