### ISSUE TITLE
LINUX   localization？

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#5569]
There is no localization in LINUX by default, changing the language has no effect.
Localization in windows adds the current language list by default
![截图录屏_选择区域_20200217200201](https://user-images.githubusercontent.com/28694676/74653490-36ea0380-51c3-11ea-91f3-ec48cc882aab.jpg)
![截图录屏_选择区域_20200217200300](https://user-images.githubusercontent.com/28694676/74653496-3b162100-51c3-11ea-8da7-6c89d93934e8.jpg)

**Comment by hishamco** [comment]
Thanks for reporting this, but AFAIK the default locale depends on the OS, but I may have a look to this one

**Comment by Skrypt** [comment]
@pgy866 Can you debug and tell me if the OS returns a culture from thé PR.

**Comment by pgy866** [comment]
@skrypt   Deployed in Linux, Recipe "SaaS", after installation, the display language is the system language zh-CN;

However, in the localization settings, there is no "zh-cn" is added as in Windows deployment. In the settings list, delete or re-add zh-cn.

In Linux, because the default "zh-cn" has been applied, it cannot be deleted and selected in the list. Therefore, after changing the language, it cannot be changed back to "zh-cn"。

Sorry, English is very bad. I use Google Machine Translation, I hope you understand。

**Comment by Skrypt** [comment]
Ok, what I need you to do is to debug the source code from that Linux distro directly.
So start from a fresh install by removing everything in the OrchardCore.Cms.Web project /App_Data  folder to trigger a setup of a new tenant.

Start Visual Studio code and put a breakpoint on that line : 

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore/Modules/Services/Clock.cs#L52

Now what I want to know is if there is a TimeZone found from
`var timezone = DateTimeZoneProviders.Tzdb.GetSystemDefault();`

Make me a screenshot of the debugger values so that I can assert that your OS is actually returning you a default culture. Then if there is a returned culture, the issue is that we require to find the corresponding canonical culture to use with Nodatime.

**Comment by pgy866** [comment]
@Skrypt 
I deleted "/ App_Data", now LINUX still doesn't work, and another problem also appears in windows;

Use "" 2020-02-19T01: 24: 35Z "to build the latest source code.

Sorry because of language problems, I posted a few pictures, it should be easier to understand.

<<<操作系统uos 20 Linux 4.19.0-6-amd64 (Debian 8.3.0-6) #1 SMP Uos 4.19.67-7deepin (2020-01-11>>>
![Uploading 1.操作系统uos 20 Linux 4.19.0-6-amd64 (Debian 8.3.0-6) #1 SMP Uos 4.19.67-7deepin (2020-01-11).gif…]()
![2 1 操作系统uos 20 Linux 4 19 0-6-amd64 (Debian 8 3 0-6) #1 SMP Uos 4 19 67-7deepin (2020-01-11)](https://user-images.githubusercontent.com/28694676/74836865-3a17f780-535b-11ea-94e7-d4ca4e85cdd4.gif)
![3 1 操作系统uos 20 Linux 4 19 0-6-amd64 (Debian 8 3 0-6) #1 SMP Uos 4 19 67-7deepin (2020-01-11)](https://user-images.githubusercontent.com/28694676/74836881-40a66f00-535b-11ea-8f68-9bd630ade298.gif)
![4 1 操作系统uos 20 Linux 4 19 0-6-amd64 (Debian 8 3 0-6) #1 SMP Uos 4 19 67-7deepin (2020-01-11)](https://user-images.githubusercontent.com/28694676/74836892-4603b980-535b-11ea-83dd-3fbfde205cdc.gif)

<<<windows_Server_2019_datacenter>>>

**Comment by Skrypt** [comment]
Ok so here first issue is that it doesn't find any culture when doing `Clock.GetSystemTimeZone()`.
Then, for this issue we can't do anything if the OS returns nothing. That's why I wanted you to show me what the debugger shows when you debug it.

**Comment by pgy866** [comment]
<<<windows_Server_2019_datacenter>>>
![1](https://user-images.githubusercontent.com/28694676/74845247-ad286a80-5369-11ea-9431-41c50a454ba2.GIF)

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/74847771-aa455f80-5300-11ea-8448-1b5a3b798d16.png)

Here the value you need to find if it's returning null is CultureInfo.InstalledUICulture.Name from within the Linux OS.

**Comment by Skrypt** [comment]
Now looking at the videos more and the OS is returning you "zh-CN" as the default culture but it's not in the culture list. That's why it sets "zh-CN" as the default culture but doesn't actually add it as a culture in that list of supported culture in the admin UI. The strange part about this is the fact that then it means that your default culture is a culture not listed in your OS cultures. 

And also we can clearly see that "zh-CN" is listed as "zh-Hans-CN".

**Comment by Skrypt** [comment]
Here I took a screenshot from a Ubuntu docker image : 

![image](https://user-images.githubusercontent.com/3228637/74855434-b20c0080-530e-11ea-829b-51fff504c197.png)

The same issue exist. After setup it added the "invariant culture" as the default culture of the website since it did not find any default culture from the OS. After that if we look in that culture list. "zh-CN" is listed as "zh-Hans-CN".

I need to look if we can find something like canonical culture names in .NET Core.

**Comment by Skrypt** [comment]
Here some reading 
https://github.com/dotnet/runtime/issues/28893

**Comment by Skrypt** [comment]
Moved to #5595
