### ISSUE TITLE
Removing a content part does not remove data in subsequent publishes

### ISSUE THREAD

**Issue by aderderian** [OrchardCMS/OrchardCore#5586]
After adding a part like BagPart or WidgetList, add data to those parts, then remove the parts. Even after a publish, this data still is returned in content manager as well as if you re-enable the part.

AliasPart this happens as well. To the point of validation occurring on making sure a duplicate Alias does not exist, it is showing validation errors on alias parts that were removed from other content types. Because the data is still there.

**Comment by deanmarcussen** [comment]
Yes, I can repro.

With the YesSql indexes for alias and autoroute because the content item still has the part data in it's elements dictionary when we call `.Map(contentItem => contentItem.As<AliasPart>() != null` it will still return true for content items that have previously had an alias part attached.

And then continue to index it.

In the case of Autoroute, it will also continue to add to the `AutorouteEntries`

**Comment by mawendel** [comment]
So what it maybe should do, was take all fields from the content manager and then apply actions to any matching that in the content item?

**Comment by sebastienros** [comment]
This could be a setting that would instruct the content manager to remove any data that is not listed in the parts, but that might be risky as someone could add custom field to the json payload, and there is no way to know if that should be removed.

These kind of changes should be done as part of a migration step. Or we could also use a module that would let you write an action to apply on all content items, with Javascript for instance. This could also be triggered by a workflow, to clean data on a schedule.

I would be ok with such a feature.

**Comment by aderderian** [comment]
Also thinking of audit trail in the future, how do we support restoring an item where a content type definition was different and this data was present?

It is strange to me after re-publishing an item after removing Alias part that validation and this data would still be hanging around in subsequent queries. Wouldn't that UPDATE statement occur on the new version of the item so that old data is not persisted and a new item is written?

**Comment by deanmarcussen** [comment]
One other option, specific to `Autoroute` and `Alias` here, could be to check the content definition manager in the index provider, for parts like `Autoroute` and `Alias` which are never welded on, but always defined in the content definition.

Then return `null`, destroying the index record.

This wouldn't clean the document json, but would prevent them showing up in the index tables.

With regard to the migration step suggestion for actual update operations.

This could be a workflow event triggered by the deployment step, allowing workflows to mutate (update and cleanse, or other operations) content items when executing a deployment.

This would be a simple solution to republishing content, i.e. create a plan, export the content, reimport it - it wouldn't quite work right now because content must have changed in order for it to be reimported, but a flag / settings could easily control this.
