### ISSUE TITLE
Better way to adjust UI/UX 

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5610]
The downside of the current theme system is that to change anything will require deployment.  The way around is to include the JS/CSS in a template and include them in every other template.  This is though is cumbersome.

I think we need better ways to make UI style adjustments quicker on production sites.

**Comment by pgy866** [comment]
cool

**Comment by deanmarcussen** [comment]
There are ways to do this, depending on whether you want a more permanent solution, or something temporary to fix a style problem.

The static file provider feature can allow you to keep files in the `App_Data` tenants folder, that can still be served from the site, so that is a place you can keep assets that are not bundled.

The layers module also allows you to push in extra style sheets or scripts, if you have some need to do an adhoc fix.

Question I would ask is if you are wanting a more permanent / different way of bundling styles, or if this is more for the quick fix to website?

**Comment by Skrypt** [comment]
One solution is to bundle your assets locally and serve it through node.js on localhost by using something like Jekyll. On your staging website you create a javascript that will replace in the DOM the url of all your CSS assets when for example you do /?mode=dev and then you can preview the changes without actually publishing them to the staging website. The issue you are facing is that we don't have anything on server side to be able to bundle up those assets. We do it on dev by using a gulpfile but unlike in 01 we never really thought about adding a feature that would allow to modify a scss file on the server and transpile it there. I've never had a requirement for that since I want to avoid having to do so. But in a Saas distribution of OC that would come in quite handy. We could bundle these scss files as part of each themes and make them editable from the admin UI so that it could also be used for modifying the actual transpiled .css files that are used in our themes.

**Comment by dodyg** [comment]
It needs to be something that can be editable online. In many use cases the developers are simply not available after the website is launched.

If you are hosting an OC instance hosting multiple websites, you simply cannot touch the installation often.  

Bundling are optimization techniques but it can also limiting the ability for "web master" to tweaks and adjust their websites online directly on the CMS.

OC allows people to "play" with content directly - but it is really limited in terms of adjusting visual layout.

**Comment by sebastienros** [comment]
We already have an issue to track it, and the solution should be quite simple to implement based on all the things we have already done. Technically it's like the templates module, but the files we edit are served with a custom static file provider. And it caches the file locally like it's done for Azure Media such that subsequent requests don't load from the db.

**Comment by Skrypt** [comment]
We could bundle .map files to make this easier to debug but that would not solve the issue entirely.

**Comment by deanmarcussen** [comment]
Sebastien's solution sounds relatively easy to implement.

I would be reluctant to try and support bundling and minification for sass files, as I've tried a few solutions like the one @Skrypt linked, and run into weird compilation issues.

Does the concept of normal bundling for the sites main assets, with whatever the preferred solution is, gulp, webpack etc. and then this proposed feature sitting on top of this, for css and javascript only, no bundling, just the ability to add and edit normal css, and js files (do the minification externally by whatever means you prefer)

So you end up with a precompiled, baked in, set of theme static files, and the ability to then add additional overrides in different files.

Does this sound like a solution that works @dodyg and others?

**Comment by dodyg** [comment]
>So you end up with a precompiled, baked in, set of theme static files, and the ability to then add additional overrides in different files.

Yes.

**Comment by deanmarcussen** [comment]
Demo'd a possible solution here https://www.youtube.com/watch?v=9eCYnzvIyl0

It didn't seem like the design was wanted for Orchard Core itself, so it will probably remain private at this stage.

If people wanted it, it might be possible to make available at some point as a contrib module

**Comment by Piedone** [comment]
Demo video: https://www.youtube.com/watch?v=g_V7ny3LxY0

**Comment by xperiandri** [comment]
> Something like https://github.com/ligershark/WebOptimizer.sass
> But I'm not sure if I like the idea of using that library yet.

We do use that library for that.
If someone wants to build a module for that, I can provide our source code.
We will also need to pull request and merge some changes to WebOptimizer packages.

**Comment by Piedone** [comment]
There are many approaches available for this now, including admin-edited templates, [GrapesJS](https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.Html/README.md), [Media Theme](https://github.com/Lombiq/Hosting-Media-Theme). Please reopen if this is still applicable.
