### ISSUE TITLE
Ability to localize log messages

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5634]
This is a discussion thread based on https://github.com/OrchardCMS/OrchardCore/pull/5625#issuecomment-590926201 to whether we need to support log messages localizations

**Comment by sebastienros** [comment]
Apparently these are not localized in the aspnetcore repository.

I am waiting for anyone to come with this request, or show other tools that do that.

**Comment by Piedone** [comment]
Probably safe to say by now that this wasn't necessary, due to the lack of feedback. The logs shouldn't really be localized, since we need them to work low-level, in every case. And if any external tool depends on the content of log entries, like for alerts, then they should always be in the same languages (like a log entry shouldn't be different even if it comes from tenants with different languages in a SaaS).
