### ISSUE TITLE
Support for front end workflows

### ISSUE THREAD

**Issue by bdongus** [OrchardCMS/OrchardCore#5661]
Hi.

**Simple example: Vacation approval.**
Employees submitt a form with their vacation request. Superiors can review and approve or deny them. Employees can check their requests.

Would be cool if this can be achieved with orchard core. But I found no information if and how this could be done with orchard core.

**Comment by pgy866** [comment]
oops.....cool.

**Comment by sfmskywalker** [comment]
You can most certainly implement this with Orchard Core using its Forms and Workflows module. The Forms module allows you to create the vacation request form, the Workflows module can then handle form submissions and notify superiors by e.g. email to review the request. It would work similar to a content approval workflow as described [here](http://www.ideliverable.com/blog/orchard-core-workflows-walkthrough-content-approval).

**Comment by bdongus** [comment]
@sfmskywalker Thanks for the link. Excellent example. Can you provide some details on how I can show the requests in the front end? Without duplicating its data in a separate datastore. My real scenario is a bit more complex.

**Comment by sfmskywalker** [comment]
Sure. But it depends on where you will store the form submissions. In Orchard 1, there was a default option to store form submissions, but I'm not sure we have that in Orchard Core. I took a quick look at the Forms module source, but didn't see any indication of having that. Perhaps someone can correct me if I'm wrong. What you could do though, is use the `CreateContent` activity to create a content item of a content type you define, with fields that correspond to the submitted form fields.
Alternatively, you could implement a custom activity that reads the submitted form values from the HTTP request and store it in the data store, which you then query later (see next).

Then to display it on the front-end, you have many options. For example, you could create a controller in a custom module that presents your page. Or probably even better: create a custom content part whose driver loads the submissions from the data store and creates a display shape. This part could then be attached to a content type, which itself could even be a widget so that you can place it anywhere in a flow part for example. A code-free approach for displaying data might be to create a Query object from the admin UI, which results you then display using some a Liquid filter.

So, there are options available out of the box that require no coding, but I think it would be a nice addition to the Forms module to allow one to store form submissions without necessarily having to store them as content items like we have in O1.

**Comment by bdongus** [comment]
Thank you for pointing out some possibilities. Now I have options to play with. Somehow I thought I would store the data "in" the workflow and should query/access it through the workflow.

**Comment by sfmskywalker** [comment]
You're welcome. Actually, that's an interesting thought I hadn't considered. Technically it's possible to store it in the workflow (which happens automatically by the `HttpRequestEvent` activity, which stores the incoming FORM fields in the workflow). You would basically treat the workflow instance as a state machine of the vacation request domain object. 

From the front-end, you would then query all workflow instances of the appropriate workflow type, where each instance represents a vacation request. Perhaps there's even support for that in the Queries module. If not, it's easy to create a custom module that uses the `IWorkflowInstanceStore` to query these yourselves, and then perhaps provide integration with the Query module, or implement a content part to be used for a custom widget type, or expose a GraphQL query / REST endpoint, etc.

One thing that might be a bit awkward to implement is extracting the submitted values from a given workflow instance that you're interested in. A workflow instance has a property called `Properties`, which is a dictionary into which you could have your workflow store the submitted form fields. Then it might be straightforward enough to read these values.

One additional property you might want to add to the workflow is a "State" property that would represent the current state of the state machine (the vacation request). You would update this property as the workflow transitions from "Submitted" to "Approved" or "Denied" for example.
It wouldn't visually look like a real state machine, since Orchard Core Workflows uses the flow chart diagram type, but functionally it will work.

**Comment by bdongus** [comment]
Exactly. Where I am stuck is "the query workflow instances from the front end" part. Found nothing about how to do that. As far as I can see the required controller/actions have the "Admin" attribute and I guess that means: Not accessable from the front end.

**Comment by sfmskywalker** [comment]
Yes. However there are also "Query" & GraphQL endpoints. So if you were able to define a query from the admin that leverages a (custom) query provider, you would be winning. Alternatively, you could implement a GraphQL provider that exposes `WorkflowInstance` as a queryable type. Then your front-end could simply fire off a GraphQL query.

**Comment by bdongus** [comment]
The GraphQL idea sounds very good. Can you point me to a starting point on how to create a GraphQL provider? Did a quick search but found nothing.

**Comment by sfmskywalker** [comment]
Sure. I think the easiest way to understand how to do it is by looking at existing examples: https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Layers/GraphQL

**Comment by bdongus** [comment]
Thanks. Will start experimenting with that.
