### ISSUE TITLE
Feature Request : Resource Types

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5723]
Below the Widgets menu item in the admin menu I would like a menu option called ResourceTypes.
The UI would be similar to Widgets but it would only have textboxes to add text to specific resource types and it would have the Layers UI on the right hand side similar to the widgets page.

**Comment by agriffard** [comment]
I don't get it.
What do you mean by 'resource type'?

**Comment by JoshTango** [comment]
<head>
    ...
    {% resources type: "Meta" %}
    {% resources type: "HeadLink" %}
    {% resources type: "HeadScript" %}
    {% resources type: "Stylesheet" %}
</head>

**Comment by JoshTango** [comment]
#5582

**Comment by JoshTango** [comment]
I'm trying to figure out how you can configure all these things in the Admin UI

**Comment by JoshTango** [comment]
Drupal allows you to do all this through the UI

**Comment by agriffard** [comment]
There are already existing solutions that may be you don't know.
Ex:
- In a Liquid widget, you can use `{% script ... %}` or `{% style ... %}` and the resource will be added in the head.
- You can define a zone in the head, for example called `HeadMeta`, then configure the Zones settings and it will be available in the Widgets. You just need to override the Widget Wrapper alternates so it is not surrounded by some div wih the widget class.

I also made a CustomThemeSettings module with Header and Footer properties that I can inject in my themes.

**Comment by JoshTango** [comment]
When I added a widget it injected a whole bunch of html container code into my head.  Looked weird.

**Comment by agriffard** [comment]
That what I tried to explain, you need to override these templates to prevent them from being wrapped by the default Widget rendering:

Widget:
`{{ Model.Content | shape_render }}`

Widget_Wrapper:
`{{ Model.Content | shape_render }}`

**Comment by agriffard** [comment]
If you add some content from a content type named `RawHtml` that has an HtmlField:

Widget__RawHtml:
`{% assign fields = Model.ContentItem.Content[Model.ContentItem.ContentType] %}
{{ fields.Content.Html | raw }}`

**Comment by JoshTango** [comment]
It just doesn't sound attractive but if that's what I have to do then that's what I have to do.

**Comment by agriffard** [comment]
If we manage to settle on a convention for this specific zone, may be we can find a way to render by default without wrapper.

**Comment by agriffard** [comment]
See also #5698

**Comment by ns8482e** [comment]
You may need to create template to override any HTML that you don’t want. 

Ie Widget-MyContentType.liquid, Content-MyContentType.liquid and MyContentType-Field.liquid

**Comment by JoshTango** [comment]
@ns8482e should not have to override this, the UI to do stuff like this is available in drupal

**Comment by ns8482e** [comment]
> @ns8482e should not have to override this, the UI to do stuff like this is available in drupal

@JoshTango it depends on what solution you choose, if you go with custom content type and you don’t like default rendering then you override the templates to fit your needs.

If you decide to use zone and liquid then it doesn’t require you to override the template. Simply define zone in your layout and use zone block in liquid

**Comment by sebastienros** [comment]
Suggestion:
- We can add in OC a custom Widget type that would accept Liquid code, and would not have any extra HTML, so define a default template for it.
This would be added in any zone, and if the resource tags are used, it will inject it correctly.

As a mitigation for now, you can create a custom content type with a liquid field + alias and a content item of that type. From the layout, resolve this content item (by alias name) and render it. You can then call resource tags.

**Comment by willnationsdev** [comment]
Since it appears to be relevant, I will say that the answer to discussion #8453, specifically jtkech's solution [here](https://github.com/OrchardCMS/OrchardCore/discussions/8453#discussioncomment-322841), and my [final comment with alterations](https://github.com/OrchardCMS/OrchardCore/discussions/8453#discussioncomment-328334) appears to be a possible solution, although I'm not sure if layers can be involved since we didn't use a widget.

1. Implement an IAsyncResultFilter
2. Check for view/page results.
3. GetShapeTable via IShapeTableManager. Check if it has an implementation of a "LayoutOverride" shape (or whatever shape you want it to be). If missing, then do nothing (so that the shape template is optional).
4. Get Layout via ILayoutAccessor. Get the "Content" zone from it.
5. Use an IShapeFactory to create an instance of the "LayoutOverride" shape.
6. Check for the "Content" zone being a `Zone` or `ZoneOnDemand`. Add the built "LayoutOverride" shape to the zone accordingly.

With these steps completed, any child theme can now do...

```cshtml
@* LayoutOverride.cshtml *@
<zone name="HeadMeta">
    SOME CONTENT HERE
</zone>
```

...and the given content will be injected directly into the parent theme's layout "HeadMeta" zone, as if you're directly inheriting from the parent's shape template (though technically it's just a shape appended to the end of the page). This solution could potentially be modified to respect the layer system, though I don't know the details of that yet.

**Comment by Piedone** [comment]
Helpful Extensions has a [Liquid Widget](https://github.com/Lombiq/Helpful-Extensions?tab=readme-ov-file#helpful-widgets) for this, but it's super simple to create too, [see here](https://github.com/Lombiq/Helpful-Extensions/blob/dev/Lombiq.HelpfulExtensions/Extensions/Widgets/Migrations.cs#L40). Anything else to do here?
