### ISSUE TITLE
Partials does not work in Razor Pages

### ISSUE THREAD

**Issue by mawendel** [OrchardCMS/OrchardCore#5787]
I first thought it was simply not possible to model bind ContentItem to partials in Razor Pages. But i soon found out that it is not possible to model bind a partial within Razor Pages at all.

if you put in `@model SomeDTO` in /Pages/Shared/ then the `@Model` is invalid. 
If you put the partial in /Views/Shared/ then it will work.

Only by using `@page` in Razor Pages cshtml files, will `@Model` be accessible. 

I should also say that `@model ContentItem` throws its own error

````
Error:
ArgumentException: Property 'ViewData' is of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]', but this method requires a value of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. (Parameter 'viewContext')```

**Comment by hishamco** [comment]
Every RazorPage require `@page` on the first line, I see that you are complain why the `@Model` is not working on partials

`@model` in partials SHOULD work, please refer to [this](https://github.com/aspnet/Entropy/tree/master/samples/Mvc.RazorPagePartial)

@jtkech is anything prevent to make it works?

**Comment by jtkech** [comment]
It depends on different things e.g the `_ViewImports.cshtml` that are used or not.

E.g if you have a `_ViewImports.cshtml` under the `Pages` folder including

    @inherits OrchardCore.DisplayManagement.RazorPages.Page

And a `_ViewImports.cshtml` under the `Views` folder including

    @inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>

And if it works when the partial is under `/Views/Shared/`, i think that to make it working when under `/Pages/Shared` you just need to specify that the partial is a `RazorPage<TModel>`, otherwise it will inherit from our `RazorPages.Page` by taking into account the `_ViewImports.cshtml` under the parent folder.

So, try to copy paste the `_ViewImports.cshtml` from the `Views` folder to the `Pages/Shared` folder, or if you have others `@page` under this folder, just add the following in your partial

    @inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>

**Comment by mawendel** [comment]
@jtkech Ah that did the trick! I was not aware you could mix in that under the Pages/_ViewImports.cshtml.

I was using the Razor Pages example in the Demo project, but there the partial is loaded from the mvc "/Views/ "(which works).
