### ISSUE TITLE
[Security Issue] Bypass upload malicious file

### ISSUE THREAD

**Issue by thiennv-2147** [OrchardCMS/OrchardCore#5863]
I want to report another bug on OrchardCMS:
User can upload malicious files to server by naming file with *.jpg file. And after file uploaded, he renames file to *.asp, *.html...
Furthermore, By rename file with "../" can raise directory traversal.
In fact, I can not relocate file to out of Media folder so can execute any asp file. But, i can use an html file to trigger XSS or deface website.
Please view my POC: https://vimeo.com/400827701

**Comment by deanmarcussen** [comment]
Thanks for reporting this @thiennv-2147 

Can I ask which version of Orchard Core you used to do this?

I think the issue was resolved in https://github.com/OrchardCMS/OrchardCore/pull/4940 which is after RC1, so requires the latest build from the myget feeds https://www.myget.org/F/orchardcore-preview/api/v3/index.json

**Comment by thiennv-2147** [comment]
I tested on master branch. Now, I tested on dev branch and the issue is fixed.  Thank for your reply!
