### ISSUE TITLE
Feature : Allow registering style block from shapes

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#5897]
The intent is to have something similar to custom scripts feature :

Razor
```
<style>
    .my-class {
        /* some style */
    }
</style>
```

Liquid
```
{% styleblock %}
    .my-class {
        /* some style */
    }
{% endstyleblock %}
```

To do :
- [ ] Allow inline declaration with `StyleTagHelper`
- [ ] Add 'styleblock' Liquid `NamedHelperBlock`
- [ ] Document feature

**Comment by deanmarcussen** [comment]
Yes! We have talked about this but never got to it.

Can you also make sure it will accept a `depends-on` which will allow it to order itself after other styles in the page header, so that it can be used to control precedence?

**Comment by TFleury** [comment]
> Yes! We have talked about this but never got to it.

Nice, let's get it !

> Can you also make sure it will accept a depends-on which will allow it to order itself after other styles in the page header, so that it can be used to control precedence?

Could we just assume those resources are overrides, so they are rendered after regular style resources (`link` tags) ?

**Comment by deanmarcussen** [comment]
> Could we just assume those resources are overrides, so they are rendered after regular style resources (`link` tags) ?

I'm not sure, mostly because the ordering is buried quite deep in the code, you will see when you come to it.

Also there might be a chance of two of them, so they might have to support naming, so that one can (potentially) order itself after the other. 

See what you find, and what works best

**Comment by TFleury** [comment]
I made a first draft, with basicaly the same behavior as `script` tag helper.

However, I agree there is also a need for named custom scripts and styles to have a kind of "require once", with order and dependency constraint.

I will search how it could be achieved.

**Comment by TFleury** [comment]
Hi @deanmarcussen,

I made a second PR for named style and script blocks with dependency constraint.

**Comment by ns8482e** [comment]
@TFleury  @deanmarcussen 

How about creating new `stylesheet` block (for `<style>` tag)  instead of using `style` block (as style is used for `<link>` tag with src) 

Also for inline style creating  new `stylesheet` ' tag helper that support  CSS/  SCSS / LESS?.

Also, some of VS code extension already support syntax highlighting for "stylesheet" block for liquid syntax. https://shopify.dev/tutorials/develop-theme-use-sections

See these extensions that i use -  https://marketplace.visualstudio.com/items?itemName=sissel.shopify-liquid and https://marketplace.visualstudio.com/items?itemName=killalau.vscode-liquid-snippets

**Comment by deanmarcussen** [comment]
@ns8482e I put this comment on the pr but maybe you missed it

@ns8482e Also a good idea, but probably outside the scope of this?

The `<style>` tag is how we use it in razor, but with liquid it becomes the `styleblock`

There could be another `<stylesheet>` tag helper / liquid etc, but it would require a lot more work, in terms of having a sass preprocessor, and making sure it's performant enough.

There's an issue over here #5610 to provide css editable in the admin, which is semi-related, and is ready and waiting for someone to start working on it ;)

I commented there that I have not had much luck with preprocessing sass/less in C#, but it has been sometime since I tried, and part of the problems I had with it where more related to processing js (specifically ES6) with the processors out there.

Also were would the sass variables come from if done inline? or are you just after the sass syntax rather than variable support?

Maybe you have had more success with a C# sass processor?

**Comment by ns8482e** [comment]
> There could be another `<stylesheet>` tag helper / liquid etc, but it would require a lot more work, in terms of having a sass preprocessor, and making sure it's performant enough.

I agree,  @deanmarcussen, IMO,  its better to named it as `stylesheet` liquid tag instead of inventing our own `styleblock` as `stylesheet` is already there in shopify and other liquid implementations and it has extensions and editor support.

**Comment by ns8482e** [comment]
It would be nice to keep exiting StyleTagHelper unchanged and create new StyleSheetTagHelper for inline styles - would allow us to extend it in future for SCSS and LESS

**Comment by ns8482e** [comment]
@TFleury @deanmarcussen Btw, there is also a simpler option available in liquid without having a PR for inline CSS style.
```
{%zone "HeadMeta" %}
<style>
    .my-class {
        /* some style */
    }
</style>
{%endzone%}
```
where "HeadMeta" is a zone in `<head>` tag where you want to have your style to be placed.

**Comment by TFleury** [comment]
> Btw, there is also a simpler option available in liquid without having a PR for inline CSS style.

Yes, it just requires an additional zone/section in the layout.
The idea is to reuse the `{% resources type: "Stylesheet" %}` helper, allow ordering (with `depends-on` attribute) and prevent duplicates.

**Comment by ns8482e** [comment]
@TFleury IMO inline styles are adhoc and can be achievable using plain old html `<style>` You don’t need `dependsOn` for Inline style as those will be always after `{% resources %}`. if someone really need to inject an inline style between two `<link>` created by `resources` then probably its not correct way and needs to have that inline style moved to css file. 

Also with inline styles, duplicates can’t prevented either.

**Comment by TFleury** [comment]
So, I merged the two PRs into one. Everything is possible :
``` liquid
{% styleblock at: "Head" %}
    .my-class {
        /* some style after all link stylesheet resources */
    }
{% endstyleblock %}

{% styleblock name: "Custom" %}
    .my-class {
        /* included only once within link stylesheet resources  */
    }
{% endstyleblock %}

{% styleblock name: "Custom", depend-on="the-theme" %}
    .my-class {
        /* included only once within link stylesheet resources, but after its dependency  */
    }
{% endstyleblock %}
```
Same possibilities with script

I also added some ResourceManagement unit tests.

Ready for reviews.
