### ISSUE TITLE
 IQueryableUserStore

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#5916]
Hi,
when I try to get all users :
var users = _userManager.Users;
I get this error
NotSupportedException: Store does not implement IQueryableUserStore.
get_Users
thank you

**Comment by hishamco** [comment]
Can you use

```csharp
var users = session.Query<User, UserIndex>()
```

**Comment by jtkech** [comment]
Yes our `RoleStore` implements `IQueryableRoleStore<IRole>` but our `UserStore` doesn't implement `IQueryableUserStore<IUser>` that would be something like this.

    public IQueryable<IUser> Users =>
        _session.Query<User>().ListAsync().GetAwaiter().GetResult().AsQueryable();

Maybe we should add this, but anyway, because it is not async, as suggested by @hishamco it is better to use a session query. If you want all users

    var users = await _session.Query<User>().ListAsync();

Or by using the index table if you only want the users that match some conditions

    var users = await _session.Query<User, UserIndex>(u => some predicate).ListAsync();

**Comment by hishamco** [comment]
I will try to implement this to be aligned with `RoleStore`
