### ISSUE TITLE
ShapeTableProvider from feature not recognized

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5921]
When adding an `IShapeTableProvider` as a feature the descriptor is not recognized by the `ShapeTableManager` until the site is hard reset.

I think the static  Shape Descriptor Dictionary already has an entry for the Feature, that the `IShapeTableProvider` is altering, so the new alteration is skipped on rebuild of the shape table.

Clearing the `_shapeDescriptors.Clear()` resolves the issue, but not in a good way.

For repro refer https://github.com/OrchardCMS/OrchardCore/pull/5862

**Comment by jtkech** [comment]
Okay i think i understand

So by using

    [Feature("OrchardCore.Contents.ClickToDeploy")]
    public class ClickToDeployStartup : StartupBase
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddScoped<IShapeTableProvider, ClickToDeployContentShapes>();
        }
    }

You prevent your `IShapeTableProvider` to be registered if the related feature is not enabled

But it doesn't prevent the `ClickToDeployContentShapes` type (a binding strategy) to belong to the main feature, here `OC.Contents`. So when you enable the feature the provider is registered but it is not taken into account because its type is tied to `OC.Contents` which is already an excluded feature.

So you also need to use the feature attribute on your provider class

    [Feature("OrchardCore.Contents.ClickToDeploy")]
    public class ClickToDeployContentShapes : IShapeTableProvider
    {

**Maybe some other places that would need to be updated in the same way.**

---

Hmm, maybe another scenario with the `[RequireFeatures]` attribute that has been created after the shape management. If an enabled feature1 has 2 providers and one that **requires** another feature2 to be registered => same problem when the required feature2 is enabled, the 2nd provider is registered but, because its type is still tied to feature1 that is already excluded, it is not taken into account.

Need to think about it because there are some places in this case e.g

    [RequireFeatures("OrchardCore.Media")]
    public class Startup : StartupBase
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<IShapeTableProvider, MediaShapes>();
        }
    }

**Comment by jtkech** [comment]
I think i will do a PR so that we don't have to update the current code

In place of managing excluded features maybe better to just cache provider type (uniques per feature) to see if they have already been used, i will do a PR so that you will be able to test it #5862

**Comment by deanmarcussen** [comment]
ok thanks @jtkech 

I have just been trying `[Feature("OrchardCore.Contents.ClickToDeploy")]` with no success. But when you have done a pr I will try it there again

**Comment by jtkech** [comment]
@deanmarcussen yes just tried you're right

I think i found why, in `ShapeTemplateBindingStrategy` there is

    // templates are always associated with the namesake feature of module or theme
    var hit = iter;
    foreach (var feature in hit.extensionDescriptor.Features)

So it seems that when discovering template **files** because a template file can't be explicitly tied to a feature, we ties it to all features. I thought we only tie it to the module main feature.

Then i tried the following testin code

    // templates are always associated with the namesake feature of module or theme
    var hit = iter;
    foreach (var feature in (new[] { hit.extensionDescriptor.Features.ElementAt(0) }).ToArray())

Doing this fixed the issue and **i could reduce the `_ShapeDescriptors` entries from 921 to 525**

Need to check that there is no side effects, otherwise @sebastienros will be happy ;)

**Comment by deanmarcussen** [comment]
@jtkech Awesome! Seems we have a good weekend for finding improvements!

I will try and understand your pr later ;)

**Comment by jtkech** [comment]
Thanks, i'll try to finalize it this night
