### ISSUE TITLE
Workflow with Http Request Event as start activity does not check for Single Instance property

### ISSUE THREAD

**Issue by claudesitorus** [OrchardCMS/OrchardCore#5962]
This is about a race condition. I've created a **single instance** workflow that starts with Http Request Event that is followed by these series of tasks:

1.  Retrieve a content item that has a numeric field that serves as a counter (original value is 0)
2.  Store the value of the field into a workflow property
3.  Update the content item with a new count (old value + 1)

then I triggered the workflow by hitting the endpoint with 5 threads running at the same time and checked the content item afterwards. The value in the counter field never reaches 5 (I tried several times, and I reset the value back to 0 every time before testing, the highest value I could get is 2)

It seems that **Invoke** action in **HttpWorkflowController** does not check for single instance property and it means in my case the 5 workflow instances were executed simultaneously.

**Comment by jtkech** [comment]
First with **SingleInstance = false**, all incoming threads will create a WF instance, it is thread safe and that's okay as long as you are not creating / updating the same content item. Otherwise it is not atomic, only on the store side but not for the whole. So here 5 workflow instances will be executed simultaneously and increment the same original value.

With **SingleInstance = true** maybe you were expecting that all demands would be enqueued and then executed one after the other. In fact it just means that a thread doesn't start a new WF instance if one already exists in the database, and then just try to resume it. But with concurrent threads and anyway with no blocking activities, here we can't have a WF instance already stored (only done at the end of the scope) and in a blocking state. So here also the 5 workflow instances will be executed simultaneously.

So in both cases it's quite the same.

So we would need a 3rd option where all demands would be enqueued and executed one after the other, but we don't implement yet such a work queue. And / or we would need to use some locking that would need to be distributed in some environments, but that right now we prefer to not use.

So right now it's the same as when multiple users update concurrently the same item through the admin UI, it is thread safe but not atomic.

We tend to not use locking but rather optimistic concurrency (right now just in some places) where it is not intended to update the same item concurently, and, to preserve the document integrity, where we check (on YesSql side) if the same document is updated concurently.

When saving an item through the YesSql Session there is a `checkConcurrecy` option, if true an exception is thrown if an item is updated concurrently. So maybe an `UpdateContentTask` that would use this option if the document integrity need to be preserved.

**Comment by claudesitorus** [comment]
> So we would need a 3rd option where all demands would be enqueued and executed one after the other, but we don't implement yet such a work queue

This is what I was thinking, because by having a queue, we do not need to handle concurrency issue for content related tasks in the workflow although I also agree with you on the option to preserve document integrity in `UpdateContentTask`. For me this is more about staying true to the description in the Single Instance property that _only one workflow of this type can execute at a time_.

**Comment by jtkech** [comment]
Okay so i opened another issue #5997 to track it, and i'm closing this one

Re-open it if i misunderstood what you mean
