### ISSUE TITLE
Workflow: Content not available when create event is fired

### ISSUE THREAD

**Issue by duncanhoggan** [OrchardCMS/OrchardCore#6008]
I have had a strange problem that straight after a content item is created and the event triggered in a workflow the content item hasn't actually been created and I get the following exception.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=OrchardCore.ContentManagement.Abstractions
  StackTrace:
   at OrchardCore.ContentManagement.ContentItemExtensions.Merge(ContentItem contentItem, Object properties, JsonMergeSettings jsonMergeSettings) in C:\Developement\R&D\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\ContentItemExtensions.cs:line 88

```

Tracking the exception up the stack it seem like the event is fired before the content creation is saved.

https://github.com/OrchardCMS/OrchardCore/blob/cac3c48ebd21ff03ab44414dceecbd3520ecb34d/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L383-L392

The sample workflow is as seen below for reproduction steps.
![image](https://user-images.githubusercontent.com/6050438/79906819-cc4e8180-8418-11ea-8787-24ec392cb960.png)

I'll add the PR and reference shortly. 😎

**Comment by sebastienros** [comment]
It will never be fired before it's saved, because the db commit happens at the end of the request, and the workflow is running inline, before that. But the instance should be available in one the arguments of the task. And doing a sql query using YesSql should still make it availble to queries.

**Comment by duncanhoggan** [comment]
@sebastienros I tested both cases, the previous order throws the exception and after re-ordering its fine.

**Comment by sebastienros** [comment]
What exactly is in the task that triggers the exception ?

**Comment by duncanhoggan** [comment]
As seen in the workflow image.
When the `Content Created` event is fired the content item doesn't exist.
Subsequently any task that that tries to access the Content Item looks like its failing, I'll have a look and see how the workflow accesses the content, but i assume its through the Content Manager.

**Comment by duncanhoggan** [comment]
var contentItemId = await GetContentItemIdAsync(workflowContext);
            var contentItem = await ContentManager.GetAsync(contentItemId, VersionOptions.Latest);

The ContentItem queried in the `ContentManager.GetAsync` returns null as is currently.

Its using the `DefaultContentManager` underneath and looks like the transaction hasn't been committed to the YesSql `_session`

https://github.com/OrchardCMS/OrchardCore/blob/c4189a1030683ecc7ef1ef79e6a5e659d6fad12c/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L106-L109

@sebastienros Do you steps to reproduce the issue?

**Comment by jtkech** [comment]
Okay i think i understand the issue

- First here i think that moving up `_contentManagerSession.Store()` is not needed. The session store would be used if we try to get the published version in `UpdateContentTask`, but we use `GetAsync(contentItemId, VersionOptions.Latest)` and the latest is not session cached.

- So maybe just moving the `_session.Save(contentItem)` but normally it has already been done, and in some places we do it after the handlers because if one handler does a session query, because of the **YesSql auto flush**, the contentItem would not be persisted.

- **But but but this is an handler itself that trigger the `ContentCreatedEvent` and that resumes the WorkFlow**. So yes, here the session save need to be moved up before calling the handlers

      public class ContentsHandler : ContentHandlerBase
      {
        ...
        public override Task CreatedAsync(CreateContentContext context)
        {
          return TriggerWorkflowEventAsync(nameof(ContentCreatedEvent), context.ContentItem);
        }


- But this re-introduces the above issue i described, if an handler does a query, which is the case here, the content item will not be persisted. So it seems that here **we would need to do a session save before and after calling the handlers**.

**Comment by duncanhoggan** [comment]
@jtkech Thanks for looking into it.
I would be happy with your solution to move the session save up, but this would mean to use standard workflow components i would need to implement my own `ContentManager`, where i think everyone would prefer to squash the bug for good or it would become a quirk in the standard interface for all. In the bigger picture does moving the session save have any detrimental effects?

**Comment by jtkech** [comment]
Because i didn't remember all details, sorry i was not totally right

If the session save is only done before an handler that does a query, in fact this is no more a concern precisely **because of the new auto flush that saves the entities**. But there is still a potential issue **if there is a subsequent mutation of the item after the query**, here another session save is needed


    1. item mutation
    2. session save // adds to saved items and allows a next query to see the previous mutation
    3. session save // NO-OP
    4. session query // auto flush => saved items are cleared but entities have been saved
    5. session save // useless as entities have been saved, and if no other mutation afterwards
    6. item mutation
    7. session save // NEEDED to persist the last mutation, if not done in 5. after the query

The issue is if we have 1. and 2. and then 4. and 6. without having 5. or 7., no matter where the steps have been done, in a content manager method or before / after calling it, or in an handler.

We already have this issue when trying to mutate an item after `PublishAsync()` that does a session save before handlers and where we needed to add another explicit session save. In your specific case that's okay beause your activity call `UpdateAsync()` that does another session save.

---

So because of the above, in some content manager methods we have a session save before the handlers and in some other ones after the handlers, **but it doesn't solves the issues globally**.

That's why i suggested another service, `IDocumentStore` in my branch, here could be the existing `ISessionHelper`. In all content manager methods, we would do `_sessionHelper.Save()` as soon as possible **before any handler**, and the service will re-do the saves before committing the session.

Maybe i will open a new issue and / or a PR

A temporary workaround would be, in all content manager methods, to **always call session save** (and session store if there is one) **before the handlers**, and also **always call session save after the handlers**.
