### ISSUE TITLE
Custom Login, Logout, ChangePassword path

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#6019]
Since we have AdminOptions now, can we make Login, Logout and ChangePassword routes customizable also?

I have a site that has its own user portal.  The links are in conflict with the default users login in orchard.  Before endpoint routing, I could just hijack the links by replacing them in configure.  But I couldn't easily do that with endpoint routing. (Upgrading from a very old OrchardCore to latest)

I could do a PR if this is going to be merged.

I plan to just add the 3 paths into AdminOptions.  Please let me know.

I need this asap.  Thanks!

**Comment by hishamco** [comment]
If I'm not wrong ASP.NET Core authentication is already has such options and defaults

**Comment by deanmarcussen** [comment]
I think what you mean @awyl is that it's very hard to override Endpoint Routing routes, as they are now all read only, once they have been mapped?

So you need to be able to reconfigure the `/Login`, /ChangePassword` routes from the `Users` module, as you need them to redirect to another portal / different controller?

If I've got that right, it makes sense to me, too need to be able to configure that.

I would probably do it with it's own options class, rather than `AdminOptions` as your issue seems specific to the `OrchardCore.Users` module

**Comment by awyl** [comment]
@deanmarcussen 

Yes I  am not aware of any way to override Endpoint Routing, unless I hack with reflection.

Yes I need to use `/Login` to our own user portal that we built before migrating to OrchardCore.  And while I am at it, I think it is more flexible if we allow configuration to the other 2 routes, which right now are also hardcoded.

Yes, I am working on it.  And I agree it should be a separate class as UserOptions.  I will send a PR soon today.

**Comment by weirdyang** [comment]
@awyl do you mind providing an example how did you implement your own login?
