### ISSUE TITLE
IDbConnectionaccessor could not be resolved in service class

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#6062]
I followed the document https://docs.orchardcore.net/en/ag-docs/docs/reference/core/Data/ wanting to get IDbConnectionaccessor instance in my service class. But 
```
': Unable to resolve service for type 'OrchardCore.Data.IDbConnectionAccessor' while attempting to activate 'XXXXXXXXX.MyService'.
```
It seems that IDbConnectionAccessor only can be resolved in Controller, is it by design?

**Comment by jtkech** [comment]
It is not restricted to controllers, would need more infos

Where your service is defined and registered and from where it is resolved?

**Is it in a module?**

So that it is done at the tenant level, because `IDbConnectionAccessor` is registered at the tenant level, not at the application level.

In OrchardCore most of the things are executed in a tenant context, a tenant is composed of modules (or themes that are specific modules) and we have at least one `Default` tenant. Then modules services are registered at the tenant level through their module startups. We can define services at the app level and register them at the app level, but by using some of our custom helpers.

**Comment by HengzheLi** [comment]
_Where your service is defined and registered and from where it is resolved?_
* I defined my service in the application startup project and registered it using AddTransient as well as in the Startup class of the startup project. The error is popped up as soon as the application starts.
_Is it in a module?_
* I don't know how to decide if it is in a module. My service is in application startup project. I think it is not a module.

I think the issue is the same as your description. My class may be registered as an application level service. Could you tell where I can find the code that helps to handle things of the application level register.

**Comment by jtkech** [comment]
E.g. from your app startup by using our custom `OrchardCoreBuilder.ConfigureServices` helper

    services.AddOrchardCms()
        .ConfigureServices(tenantServices =>
        {
            tenantServices.AddTransient<IYourService, YourService>();
        });

Then, as i remember you can define a controller at the app level as it will be executed in a tenant context, so then try to inject your service in this controller

**Comment by HengzheLi** [comment]
Thanks. OrchardCoreBuilder.ConfigureServices works.
