### ISSUE TITLE
Integrate orchardcore and nopcommerce.

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#6078]
is it possible to integrate both? 
i not it is possible to use subdomain but I'm looking for a solution to use the same user accounting.
and showing products inside the orchard theme.

any solution?

**Comment by hishamco** [comment]
These are different product, hope @bleroy can update us on Orchard Commerce project

**Comment by ns8482e** [comment]
Maybe you could build a Orchard Core module that access products in NopCommerce via API

**Comment by bleroy** [comment]
Well, we're having this conversation at least in part because I recommended Ahmad he checks out nopCommerce since Orchard Core Commerce is still very far from a usable state. https://github.com/OrchardCMS/OrchardCore.Commerce/issues/61

To answer the specific question of user integration of nopCommerce with Orchard Core, I would expect that at least on the side of Orchard, authentication being largely reliant on oAuth, integration seems possible to an extent.

**Comment by aghili371** [comment]
i think it is possible if we set same the authentication . and then using API to call information.
unfortunately, nopcommerce is really slow.  do you know faster open source e-commerce?

**Comment by dodyg** [comment]
https://github.com/VirtoCommerce

**Comment by Skrypt** [comment]
I believe that NopCommerce changed recently their ORM to address these performance issues related with Entity Framework. VirtoCommerce is not a completely free solution like NopCommerce or OrchardCore.Commerce are.

**Comment by hishamco** [comment]
SimplCommerce is another good solution I contributed in that project long time ago, but again I think OrchardCore.Commerce will be the more suited and more integrated one

**Comment by agriffard** [comment]
Closing. Multiple answers.

**Comment by josiahmaki** [comment]
Did anyone ever find if they could successfully integrate Orchard with NopCommerce? I would like to use Orchard for landing pages and NopCommerce for checkout etc.
