### ISSUE TITLE
Hide title part for form and label type

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6079]
As per below comment by @jwu-au on PR #6053 , 

> Hi @ns8482e , do we want to make below as default for this PR?
> 
> ```
> {
>   "TitlePart": [
>     {
>       // hides title part for form and label type
>       "displayType": "Detail",
>       "contentType": ["Form", "Label"],
>       "place": "-"
>     }
>   ]
> }
> ```

Following options to hide TitlePart, 
Option 1: revert deletion of widget-form.cshtml and widget-label.cshtml 
Option 2: Use placement as above
Option 3: Create "Render Title" in TitlePart setting to hide title on UI,  also a solution for issue #5959 [suggested changes]( https://github.com/OrchardCMS/OrchardCore/compare/dev...surevelox:ns8482e/%236079)

Suggestions? /cc @sebastienros @deanmarcussen @Piedone

**Comment by Piedone** [comment]
I'm fine with 1 or 2, 3 still seems like an overkill.

**Comment by ns8482e** [comment]
> I'm fine with 1 or 2, 3 still seems like an overkill.

@Piedone  1 and 2 works only for compile time, However with option 3 is dynamic and change can be applied at runtime

**Comment by deanmarcussen** [comment]
2 sounds good @ns8482e as the original reason for having 1 was because `contentType` placement hadn't been written yet.

This would make it automatic for forms, which is good, and easier for users.

3 also sounds good, we discussed the issue at length during triage a few weeks ago, and came to the conclusion that we would like the feature to make the `TitlePart` able to be just an editor, easily for users.

@Piedone 3 maybe overkill for your use case, but because there are a bunch of other use cases, it was felt that it helps with making it "easier"

**Comment by ns8482e** [comment]
When I wear developer hat, It seems option 2 is good choice also its original idea. It works well when a developer wants to control the placement of content type that are known at development time and content editor can't override it - that means we can use it for Form and Label.

However, when I wear content-editor hat, IMO option 3 is good. When a content-editor defines/updates content-type using Admin UI e.g. "Container", "Form" he can't use option 1 or option 2. as they are neither in his skills nor in his permissions. Unless orchard core provides new  dynamic placement feature that allows content-editor arranging shapes of a given content type via Admin UI.

TitlePartSetting already  has option to control TitlePart_Edit shape for admin, but, I think by adding option 3, it allows content-editor to control TitlePart Shape for dynamic content types for front end as well.

**Comment by ns8482e** [comment]
@sebastienros @deanmarcussen This needs to be fixed in RC2
