### ISSUE TITLE
Background tasks should optimize database queries

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#6128]
Saw this pattern in PublishLater and probably Indexing too, where a query would be done to check if some work needs to be done. In O1 such pattern could trigger some database locks, and on a multi-tenant system these queries would add up. A better solution is to store the datetime of the next known even in a cache, and only query the database if this time is over. 

It needs to be in a ditributed cache entry. It can also be based on an absolute expiry of a distributed cache item, such that when there is not item in the cache a query needs to be done, and the next entry inserted in the cache as a replacement. If there is no next entry then no cache is provided. The cache entry should also be set on startup (if tasks don't want to check if it has been initialized already). This distributed cache usage might also provide a way to lock a task if multiple nodes are used.

**Comment by jtkech** [comment]
Added on my list, i think we will be able to do all or part of this with the distributed Documents / States done in the distibutedCache branch. They can be Persistent or Volatile but still in sync, and they can be initialized directly from a related database document or by a factory using any related data e.g. an indexed table. And cache options for each Document / States can be configured.

> This distributed cache usage might also provide a way to lock a task if multiple nodes are used.

**Do we need a real distrubuted lock or just a kind of "optimistic" exclusion?**

So maybe **another property on a background task e.g. `IsSingleton`**, meaning it is exclusive accross multiple nodes. This let me think about **Workflow marked as Singleton** where we would need the same kind of lock / exclusion in a distributed environment.

---

Note: If multiple nodes on the same file system ;) maybe the same need for Media Azure caching files and Sitemap caching files, or maybe not if we don't want to support this scenario.

Note: For Lucene indexes files i know this is not the same ;) as soon as an instance has used a writer resource, the related folder is locked by a dedicated `write.lock` file. So, and only if we want to support it, we would need another solution.

**Comment by Piedone** [comment]
I understand the need to execute a background task just once in a multi-node app and yes, absolutely for Publish Later, for indexing I'm not sure, see [this issue](https://github.com/OrchardCMS/OrchardCore/issues/5947#issuecomment-614108844) . The rest not really, what do you mean @sebastienros by "A better solution is to store the datetime of the next known even in a cache, and only query the database if this time is over."? Would this be solved by https://github.com/OrchardCMS/OrchardCore/issues/5755?

**Comment by sebastienros** [comment]
Yes you are right, I just realized that PlublishLater should actually not be based on a background task, but something of a higher level, but we don't have it yet.

**Comment by Piedone** [comment]
So can we rename this to something more like "Distributed locking feature and locking background tasks"?

**Comment by jtkech** [comment]
@Piedone just for infos

I made a distributed lock in #2249 where the default implementation only provide tenant level named locks on the same instance, and with a distributed implementation based on Redis.

But @sebastienros, and i agree with him, prefer to not use, as much as possible, any kind of custom locking system, that's why i talked about "optimistic" exclusions, maybe based on distributed states (implemented in #5249).

He also want to not use, as much as possible, a message bus, so in place of using a distributed signal (implemented in #2247) we would use distributed states (implemented in #5249).

**Comment by Piedone** [comment]
I mean if the app is running only a single node then the lock wouldn't be distributed since the user wouldn't use Redis. But still, such a "singleton" background task would use the same lock service so if the app actually runs on multiple nodes it can be switched over to a distributed implementation. I think we're talking about the same thing.
