### ISSUE TITLE
DateField stores dates differently than DateTimeField

### ISSUE THREAD

**Issue by kadamgreene** [OrchardCMS/OrchardCore#6138]
Background: I'm working on a calendar and I wanted people to be able to select the date range they want on their calendar and the calendar range is date based, but the events are date time based.  And i noticed it wasn't working as expected.

DateTImeField utilizes ILocalClock to convert value inputted into website to Utc to save to DB and back to local on load.  DateField takes the date entered on the website and assumes that that date is Utc (so if I, living in Atlantic Time zone, select May 7, 2020 in a DateField, it stores 2020-05-07T00:00:00Z, rather than 2020-05-07T03:00:00Z as the DateTimeField does when you enter May 7, 2020 at 12AM)

**Comment by sebastienros** [comment]
I believe it's by design. The goal of DateField and TimeField, are to store the values that the user entered, and to not vary with timezones. The DateTimeField is about storing a point in time so this one will vary based on TZ.

Thus don't use ILocalClock or ToLocal on the values from DateField and TimeField.

I think the scenario you described above works fine with that. Or please tell me to read again, or give me another example.

**Comment by ns8482e** [comment]
Date field and Time field is for absolute value. If you need conversion based on timezone and point in time use DateTimeField

**Comment by kadamgreene** [comment]
I am good with your description of the situation, and will close the ticket (I solved the issue internally by taking only the Date and dropping time in my comparisions, which is in line with what you describe).

**Comment by sebastienros** [comment]
The history if this field is that users have request to be able to store a date or a time, the way it was entered, and not vary by Tz. One field that we are missing though is TimeZone, such that one could represent a date, time and a timezone, to render a date/time in the way it was actually entered. For instance for Flight websites.
