### ISSUE TITLE
Versionable is not checked when importing content items

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#6171]
@deanmarcussen 

The `Versionable` option is only checked in `ContentDefinitionManager` [line 190](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L190), when getting a content item with the `IsDraftRequired` option, this to call or not `BuildNewVersionAsync()`.

But the `Versionable` option is not checked when importing content items.

Let me know if you think it's an issue or not, if not you can close it ;)

**Comment by deanmarcussen** [comment]
@jtkech So yes, I think this is by design.

The import uses the two new methods for idempotancy, either
- Creating a new record once (if the versionid does not exist) (and then if the import ran again, it would become an Update)
- Updating the existing version (if the versionid exists) 

So the idea was to keep with the similar behaviour on the import routine as previously, and import versions of content items.

So when importing a version, it would not check or call `BuildNewVersionAsync()` but update / create the existing version or, a new as required.

In this way it maintains some idempotancy - otherwise every import would build a new version, and so on.

Does this make sense?

**Comment by jtkech** [comment]
@deanmarcussen okay i'm fine with it

But here, if not Versionable it would be

> Updating the existing version (if the versionid exists)

Okay, it would be the same

> Creating a new record once (if the versionid does not exist) (and then if the import ran again, it would become an Update)

If not Versionable it would be: Create a new record once but only if there is no existing version, otherwise update the existing one. Then if the import run again, it would become or be still an Update.

**Comment by deanmarcussen** [comment]
> If not Versionable it would be: Create a new record once but only if there is no existing version, otherwise update the existing one. Then if the import run again, it would become or be still an Update.

Yes, so the idea was that it would be like a `Post` here, so not idempotant, but then when run again, would be more like a `Patch`, and the patch would be applied to the existing version id.

Thus to keep the database more in sync, than creating a new version every time an import is run.
So there is a difference in behaviour to what you would experience working through the admin ui, where a new version would be built (if `Versionable`)

So it was also important to do the check to see if the versions have altered (with the json `DeepEquals` ) or a recipe contained existing data, where the user has already created new versions on the server they are importing to, would overwrite the published status of those new versions.

I almost dropped the import of an existing version id feature, but then when I looked at the issues people had raised, I discovered that users where also editing recipe files to alter content (without specifying a new version number), so I decided to keep this feature available, but do the json `DeepEquals` check, so unless the data was different (except for the published / latest values as they would change) there would be no import and subsequent overwrite of newer versions.

**Comment by jtkech** [comment]
@deanmarcussen 

> Yes, so the idea was that it would be like a Post here, so not idempotant

I would said more like a PUT but the resource would be identified by its content item id, not its version id. Then when run again, as checked for other items, no update if this unique version has not changed in the meantime.

**Anyway, as said i'm fine with it and it would add some complexity**, we would need something like this (quickly done so not sure)

    var versionsToUpdate = existingContentItems.Where(c =>
        versionIds.Any(v => String.Equals(v, c.ContentItemVersionId, ...)));

    var notVersionableToUpdate = existingContentItems.Where(c =>
        NotVersionableContentType.Any(v => String.Equals(v, c.ContentType, ...)));

    var versionsThatMaybeEvicted = existingContentItems
        .Except(versionsToUpdate).Except(notVersionableToUpdate);

    ...
    ...

    foreach (var importingItem in batchedContentItems)
    {
        ContentItem originalVersion = null;
        if (!String.IsNullOrEmpty(importingItem.ContentItemVersionId))
        {
            originalVersion = versionsToUpdate.FirstOrDefault(x =>
                String.Equals(x.ContentItemVersionId, importingItem.ContentItemVersionId, ...));

            if (originalVersion == null && !String.IsNullOrEmpty(importingItem.ContentItemId))
            {
                originalVersion = notVersionableToUpdate.FirstOrDefault(x =>
                    String.Equals(x.ContentItemId, importingItem.ContentItemId, ...));
            }
        }

**Comment by jtkech** [comment]
@deanmarcussen any feedback on my last comment?

Sorry to bother you, if don't have any time here a summary

- I talked a little about idempotency where i might be wrong ;) And i quickly did a piece of code to show what i mean with the not versionable option where the original resource is found by its id, not by its version id as it is a single version resource.

- I may be wrong as i didn't try it, but it seems that we can import an item that is neither latest nor published, and then that will be saved in a soft deleted state, is it intended?

**Comment by deanmarcussen** [comment]
> @deanmarcussen any feedback on my last comment?
> 
> Sorry to bother you, if don't have any time here a summary

Sorry @jtkech caught up with other pr's and missed this last comment.

> * I talked a little about idempotency where i might be wrong ;) And i quickly did a piece of code to show what i mean with the not versionable option where the original resource is found by its id, not by its version id as it is a single version resource.
> * I may be wrong as i didn't try it, but it seems that we can import an item that is neither latest nor published, and then that will be saved in a soft deleted state, is it intended?

This was intended, because I saw on the issues people were raising, that they were manually editing recipe files to change things. So I did it because I was doing all the other version options, and this allowed the state to be maintained. And it adds the potential for more of a content sync, at some later point (potentially).
So it was more for completeness, and to make sure, that nothing got skipped.

I'm not sure what the audit trail module will look like, in terms of features / version history, but it seemed to make sense that these would then be included in the version history.

I'm not sure about checking `Versionable`, I will have to think some more.
Part of the problem with building a new version seems to me that the contentitemversionid would change, and then we would potentially run into problems, when re-running the recipe, or trying to keep those version in sync, particularly when people are editing recipes themselves. 

Maybe I am wrong?

I will think some more on it, and try a couple of things tomorrow.

**Comment by jtkech** [comment]
> I'm not sure what the audit trail module will look like, in terms of features / version history, but it seemed to make sense that these would then be included in the version history.

Okay then, i also thought about audit trail, just to be sure that importing such items was intended.

> I'm not sure about checking Versionable, I will have to think some more.
Part of the problem with building a new version seems to me that the contentitemversionid would change, and then we would potentially run into problems, when re-running the recipe, or trying to keep those version in sync, particularly when people are editing recipes themselves.

Anyway i agree that it would be confusing, so i'm okay to say that `Versionable` only change the way that versions are managed through the admin UI, not while importing ;)
