### ISSUE TITLE
change  culture Persian language  not work

### ISSUE THREAD

**Issue by VahidFPA** [OrchardCMS/OrchardCore#6178]
hi
When I change the culture Persian language to default, the display language is English again and does not change

**Comment by hishamco** [comment]
@vahid001 which version you are using, coz I'm sure the `fa-IR` already have translation, I think @aghili371 is already had some experience with Persian language

**Comment by vahid001** [comment]
I use last version,
I have no problem translating the language
My problem is with the default Persian language selection
@hishamco

**Comment by hishamco** [comment]
Could please share the steps to reproduce, coz what I'm expecting is go to cultures, add the `fa-IR` culture, then set it as default culture and save

**Comment by vahid001** [comment]
![001](https://user-images.githubusercontent.com/3223934/81907085-79618780-95dc-11ea-9a8d-3a0d21071a2a.gif)

**default culture language Persian not work**

**Comment by hishamco** [comment]
Let me check and come back to you ...

**Comment by hishamco** [comment]
One more thing could you please the default browser language, seems it's `en-US`, and that's why English win all the time

**Comment by vahid001** [comment]
It shouldn't be like that
The default language should always be predominant over all other languages

**Comment by hishamco** [comment]
You could check how the localization middleware is working behind the scene, there are different `RequstCulltureProvider`s the `AcceptLanguageHeaderRequestCultureProvider` has a precedence over the others, especially if the culture is included in the `SupportedCultures`

**Comment by vahid001** [comment]
I have not get my answer yet. Any further help would be greatly appreciated.

**Comment by sebastienros** [comment]
@vahid001 it's how we think it should be. Default didn't mean "this is the only one you will always see" otherwise just set only persian as they only supported language.

It behaves as a fallback in case no matching language was found between all the requested and supported ones.

What you want is a separate feature that would set which culture to ask for and would have priority over the browser one. It would be a user setting. You might also prefer a different setting that would instead for the admin ui on a specific culture. Both are different features (other than the meaning of default in this screen) that require specific features.
