### ISSUE TITLE
Attach user info to content.

### ISSUE THREAD

**Issue by B-Esmaili** [OrchardCMS/OrchardCore#6204]
Is there any way to attach user info to content type? something like user field.allowing us to attach multiple user to instance of a content item.

**Comment by Piedone** [comment]
To my knowledge, you need to implement this yourself, e.g. from a content part where you store the user's ID and then load it when necessary.

**Comment by B-Esmaili** [comment]
The hard part is implementing a `UserPicker` . i have no idea how to implement that.

**Comment by Piedone** [comment]
I suggest you look around in the `AdminController` class of OrchardCore.Users. You'll see how users are retrieved so you can then do the same in your own content part.

**Comment by deanmarcussen** [comment]
We discussed this at the meeting last week https://www.youtube.com/watch?v=hexujWzGV14
and seemed to think it was something we should implement.

The code to look at for similarities on picker design would be the `ContentPickerField` 

Probably the thing blocking implementing this in Orchard Core at the moment (for me) is the use of a int `DocumentId` property on the `User` object, as this will not carry over between different systems.

Can anyone in the team comment as to why we use the document id for the `User` rather than a `Guid` ?

(semi related https://github.com/OrchardCMS/OrchardCore/issues/5409)

@kevinchalet I wonder if you had any involvement with the original choice there, or opinions on it?

**Comment by B-Esmaili** [comment]
Glad to hear that. frankly i was disappointed about lack of this feature and i think it is something to be implement as builtin feature. actually the need for this feature originated from assigning user info to content items in workflow tasks and i think user specific tasks are lacking in workflow for that matter.

**Comment by jtkech** [comment]
> Can anyone in the team comment as to why we use the document id for the User rather than a Guid ?

@deanmarcussen sorry i don't know why the user id is the doc id so tied the the store. Looks good to have an uid added to the `UserIndex` table and then update the `UserStore` `FindByIdAsync()`

**Comment by Skrypt** [comment]
This issue is getting old. I should probably work on it since I'm concerned by this issue.

**Comment by B-Esmaili** [comment]
RC2 is released but still no milestone specified.Have you done something regarding this?
