### ISSUE TITLE
Display mode for parts and named shapes issue.

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#6206]
After creating display mode for various custom parts (added by this pr  #5329) and then tried to alter alter shapes position in my Content.cshtml using with the new part display mode  : 
```
   @await DisplayAsync(Model.Content.TitlePart)
   @{Model.Content.Remove("TitlePart")};
``` 
This does not work. Instead you have to use the name of the custom display mode eg : 

```
 @await DisplayAsync(Model.Content.Named("TitlePart-TitlePart_Display__MyCustomDisplayMode"))

  @{Model.Content.Remove("TitlePart-TitlePart_Display__MyCustomDisplayMode")};

```
This is a bit cumbersome , having to know the display mode applied to work with the shape.

Would it be possible to preserve the original part name , so you could work with shape part name , regardless of the display mode. ?

So shape.Metadata.Name = "TitlePart" will not change based on the display mode ? 
@deanmarcussen 
Thanks.

**Comment by deanmarcussen** [comment]
Yes, I'm aware of this limitation and it is inconvenient, and it also ties the `DisplayMode` to the `Template`.

Which makes it difficult to change the display mode (which can be set in the UI), without having to have a corresponding change to the template (which maybe written in code)

the `Shape.Metadata.Name` probably couldn't change, because the display modes are tied to shape names, and it would not find it then.

I wonder if it would be possible to have a wildcard (like `TitlePart*`) for matching on when calling `Remove()` ? 

Perhaps @jtkech might have some ideas there too?

@jtkech I have just realised that we never added the template alternates for the `Part.DisplayShapes`, like you did for the Fields (I think they were on different pr's at the time)

**Comment by jtkech** [comment]
> Perhaps @jtkech might have some ideas there too?

Hmm not sure, maybe in the `Named` / `Removed` methods, if there is no part with a given name, check if there is one that starts with this name + the `_Display__` token, assuming that the remaining part is a display mode, or maybe include the display mode to the shape metadata.

> @jtkech I have just realised that we never added the template alternates for the Part.DisplayShapes, like you did for the Fields (I think they were on different pr's at the time)

Oups, would have been better to do it at the same time

**Comment by ns8482e** [comment]
I faced similar situations, Although not related to Display Mode. 

I had a shape object that I wanted to remove from parent zone, But I could not because the `Matadata.Name` was null and `Shape` doesn’t provide Remove by object. So I cast `Items` to `IList`

@jtkech @deanmarcussen so I doubt if `Matadata.Name` really is used in rendering

**Comment by jtkech** [comment]
> @jtkech @deanmarcussen so I doubt if Matadata.Name really is used in rendering

Not sure but I think you're right, hmm as i remember the name is set to the stereotype or the shape type, but for rendering maybe only the shape type is important, need to be tried / checked
