### ISSUE TITLE
Page size at PagerSlim

### ISSUE THREAD

**Issue by PixPunch** [OrchardCMS/OrchardCore#6271]
Hi everyone.
As a web designer I do use TheBlogTheme for one of projects and want to render blog posts as a grid of cards (3 columns x 5 rows) instead of a list.
As I understood from documentation PagerSlim doesn't have an option to change number of items per page (but it used at BlogTheme by default). Is there easy way to modify page size in ".Blog-ListPart.liquid" at TheBlogTheme?

Thank you in advance.

**Comment by deanmarcussen** [comment]
The Blog settings for the `ListPart` have an options for how many items you would like to retrieve.

It is 10 by default, but can be changed to whatever you prefer.

Does this resolve the issue?

**Comment by PixPunch** [comment]
@deanmarcussen, when I saw this setting I had same thoughts about this option :)

But this option changes only number of items in public RSS feed, not the Blog page showing `ListPart` (list of  `BlogPosts`). 

**Example**
At the RSS feed URL it shows the exact number I have set at `ListPart`
_https://localhost:44345/..../Contents/Lists/4xq1x9sw031qa29wm5yhkrp6wm/rss_ 

At the page created based on `ListPart` are shown 10 items.
_https://localhost:44345/blog_ 

**Global setting**
I have found global setting "Page size" at  Admin > Configuration > General > Site (tab) > Page size, but it doesn't affect pager as well on '/blog' page. Anyway pagesize option should content instance specific (not global) in case you have to render different number of items for different content types based on `ListPart`.

**Comment by sebastienros** [comment]
> But this option changes only number of items in public RSS feed, not the Blog page showing

This is a bug then. Should be easy to change if you want to provide a PR.

**Comment by sebastienros** [comment]
I checked the code and tested it, it works as @deanmarcussen suggested. I also found that the Blog edit screen has an RSS page size that you can change, so I think that's where you got confised. The rss page size is changed in the Blog content properties, while the "Blog" type page size is defined in "Content -> Content Definition -> Blog -> List part" settings. So all Blogs will have the same page size. Not sure it's a good thing, we might want to be able to set the pager options for each list instances instead of all the instances of the same type.

But I assume that you only have one Blog, or that it would not be an issue to create a distinct type and have its own settings.

**Comment by PixPunch** [comment]
@sebastienros, you are right I got confused about the setting.
We are really planning from 2 to 5 Blog pages at several sites.
For now common number of items per page is good enough solution.
@deanmarcussen, sorry for the misunderstanding.
Thank you guys for assistance!
