### ISSUE TITLE
Session Object Disposed in IndexProvider

### ISSUE THREAD

**Issue by longchangvn** [OrchardCMS/OrchardCore#6283]
I Tried to query document by `contentManager.GetAsync(ids).Result` inside indexProvider and sometime i got the session disposed issue: **AggregateException: One or more errors occurred. (Cannot access a disposed object. Object name: 'Session'.)**

Any help would be appreciated.
OC version: 1.0.0-rc1-13272

This is the sample code:

`public override void Describe(DescribeContext<ContentItem> context)
        {
            var contentManager = _httpContextAccessor.HttpContext.RequestServices.GetService<IContentManager>();
            context.For<SampleParentChildIndex>()
                .Map(contentItem =>
                {
                    /* some more code here*/
					
                    var part = contentItem.Get<ContentPart>(contentItem.ContentType);

                    if (part == null || part.Content == null || part.Content.Company == null)
                    {
                        return null;
                    }

                    List<string> ids = ((JArray)part.Content.Parent.ContentItemIds).ToObject<List<string>>();
                    var children = (contentManager.GetAsync(ids).Result); //Get Error at this row as session is disposed
                    var child = children.ElementAt(0);
                    var locationId = ((JArray)child.Content.Child.Location.ContentItemIds).ToObject<List<string>>();
                    
                    return new SampleParentChildIndex()
                    {
                        ChildId = child.ContentItemId,
                        ParentId = contentItem.ContentItemId,
						ChildLocationId = locationId
                    };
                });
        }`

**Comment by Piedone** [comment]
I guess the `GetService()` call is rather `GetService<IContentManager>()`, right?

The issue here is that you get the Content Manager instance outside of `Map()`, when `Describe()` runs. Your delegate that you supply to `Map()` is executed at a later stage, and multiple times, in different HTTP requests. Since `IContentManager` shouldn't be shared among requests (it's a dependency that lives as long as the request only) you'll see these exceptions since you try to access a log disposed object from another scope.
