### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by chrisvdb** [OrchardCMS/OrchardCore#6286]
The roadmap ([https://github.com/OrchardCMS/OrchardCore/wiki/Roadmap](https://github.com/OrchardCMS/OrchardCore/wiki/Roadmap)) shows October 2019 for version 1.0, which has obviously not materialized.

We are currently assessing various CMS technologies for customer project, and would like to understand when version 1.0 is expected to be released. We understand from the homepage that "The software is almost ready for final release." and development seems to be (very) active, however a realistic roadmap to 1.0 would help us convince customers about the technology choice.

**Comment by hishamco** [comment]
@agriffard I think we need to update the roadmap and add RC2

**Comment by Piedone** [comment]
While the roadmap is outdated and there is some disagreement in the community on what may be called a 1.0 version but for most purposes, Orchard Core is production-ready already. It's used in production from small websites to more complex websites, and in apps used in health care, community management, fintech.

**Comment by johnsonzhong** [comment]
Since it's production-ready, why not release the final v1.0?  If there any specific reason? You know even it's just a very small difference with the version number, but from the customers' perspective, especially  who don't know much detail on Orchard Core, it means "unstable", "unofficial". As a developer it's very hard to convince the customers to believe it's the good timing to use it in the production environment. 
If the final v1.0 release, then any changes upgrade from it, the story will be different.

**Comment by chrisvdb** [comment]
Exactly, @johnsonzhong. It's hard to convince customers to use software that isn't labeled stable.

(sorry, accidentally closed/reopened the issue)

**Comment by ns8482e** [comment]
@chrisvdb  IMO CMS functionality and Framework is production ready in RC1 and stable

However there are some modules that are not completed  or available compared to Orchard 1. 

I would suggest If you are not concerned about features/modules still under dev, then don’t wait for 1.0 start using it now

**Comment by Skrypt** [comment]
The reason why it's not labelled 1.0 is because it should not be a decision driven by marketing reasons but logical reasons, like the fact that we miss a lot of features in Orchard Core that remains to be done. Also, I believe that we don't want to reproduce the same issue that happened with 1.0. Orchard Core is ready to be used for workshops that wants to use it as a framework if they don't matter running into issues from time to time. So, we're still into the experiencing and fixing issue from feedback stage which is quite important if you want to release a 1.0 version that will be easy to work with compared with how it was with the previous version.

Generally a software should be labelled as stable when the most debilitating bugs have been all fixed which is not the case actually. I could name a few issues that remains to be fixed. And it's taking more time than expected because I believe that we want to do thing properly.

Of course nothing is perfect but at least we should try.

**Comment by Piedone** [comment]
Yeah, we have our differences with Jasmin on whether what can we call 1.0 :) (also see https://github.com/OrchardCMS/OrchardCore/issues/5814). But there are just a couple of 1.0 issues remaining now: https://github.com/OrchardCMS/OrchardCore/milestone/8

**Comment by Skrypt** [comment]
You could be surprised to see how many other issues/pr will emerge from only those. But yeah I'm opiniated, nothing to take personal 😸

**Comment by hishamco** [comment]
FYI the roadmap is updates by Seb https://github.com/OrchardCMS/OrchardCore/wiki/Roadmap
