### ISSUE TITLE
Deleting Content Types that are still in use leaves the system in a error prone state.

### ISSUE THREAD

**Issue by BJury** [OrchardCMS/OrchardCore#6300]
I had a Taxonomy that was used by many pages, where somehow the underlying Term Content Type was deleted in the UI.

The site continues to work, with the taxonomy showing and being used correctly. (Including creating posts where you can select an item from the taxonomy!)

However when trying to edit it to add items the system throws 'Object Not Set' errors.

My guess is the delete button needs to check if a Content Type is still in use before actually deleting the content type. (Or some form of soft delete if its in use?)

**Comment by jagbarcelo** [comment]
I think OC would benefit from having a single view (probably readonly) where a [directed graph](https://en.wikipedia.org/wiki/Directed_graph) shows the interactions among ContentTypes, Parts, and Content items: which ContenType has instances, which does not, which one is used within another one, etc.

That graph would help to avoid deletions that might led to such state and also to better understanding of the overall site organization. There, orphaned ContentTypes (not used at all) could easily be spotted.

It does not need to be something as complex as the Class Diagrams in Visual Studio, but a simpler idea would be a nice-to-have.

Of course (back to the original issue), the real solution would be that OC do the proper checks before deleting anything,

**Comment by Skrypt** [comment]
Content Items are soft delete in OC but not the Content Types. You can create back the Content Type with the same technical name though and it should work back. Look at your content items to know the technical name first and create it back if that fixes your issue.

Or, you can create a new Content Type with a new technical name and migrate your content items with a SQL Query also.

Dependency graph is a good idea, it could lead to tools to migrate data from one content type to an other...

Though this is the kind of issue that happens mostly with Taxonomies because people are often redefining their Taxonomy terms hierarchy. Maybe something to think about but for Taxonomies only first.

**Comment by agriffard** [comment]
Related to #6751
