### ISSUE TITLE
Consider relaxing the OpenID settings validation policy to allow using non-interactive flows without having to register a certificate

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#631]
> Starting with RC1, ASOS now includes a "degraded mode" that allows you to use it without registering a signing key or a signing certificate (ephemeral or not) if you don't opt for JWT access tokens and don't use the implicit or hybrid flows.

> Concretely, using AddEphemeralKey() or AddCertificate() is no longer mandatory if you use non-interactive flows like password or client credentials AND the default access token format.

http://kevinchalet.com/2017/03/14/migrating-to-aspnet-security-openidconnect-server-rc1/

/cc @jersiovic

**Comment by jersiovic** [comment]
That feature would had saved me a lot of work invested on scripts for creating and renew autogenerated certificates. I faced more problems than expected with that due to some inconsistencies of Windows and .net in relation to certificates.
I agree it would be good this configuration is allowed from Orchard.

**Comment by PinpointTownes** [comment]
Now that we support automatic X.509 certificates generation, there's practically no need to implement such a feature. Closing this ticket.
