### ISSUE TITLE
Lucene Index Should Self-Generate Off Definition

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#6327]
In my push to get to a stateless web server, the Lucene Index is my only "problem" left thanks to pull request #5678 resolving the majority of the problems. 

Here is my example. If I have a production site that is being used where Lucene is enabled, and I then deploy updated code to a sandbox (where there is no Lucene index) and swap the sandbox into production, the Lucene Index is gone and has no way to rebuild. I agree that Lucene builds quickly so if it just rebuilt that would be fine... but the code at this point doesn't seem to have ability to rebuild if the actual Lucene folders/files are missing. You have to physically delete the index in the Admin area (which I am guessing deletes it in the database) then build a brand new one. I can't do that every time I push in code so looking for alternatives.

**Options one:** use code like Lombiq put out for Orchard [Orchard Azure Indexing](https://github.com/Lombiq/Orchard-Azure-Indexing) or a third party integration using a library like [AzureDirectory ](https://github.com/azure-contrib/AzureDirectory) but really, I just want them rebuilt since they are small indexes

**Option two:** if the index scheduler (maybe even the IndexingBackgroundTask.cs which calls ProcessContentItemsAsync) would try and build and index that doesn't exist, it would just recreate it on the fly then rebuild it. Does this seem like a feasible / implementable solution? So if a new server (or instance) is spun up and the directory doesn't have the Lucene folders, it would just rebuild it from information in the database? Hopefully I understand this enough that what I am typing makes sense, not an expert on this module at all...

**Comment by jeffolmstead** [comment]
I had a good conversation with @Skrypt regarding this topic and here are the highlights:
1. Tap into LuceneIndexSettingsService (or a similar service which fires on startup) to ensure index folders are at least existent based on lucene.settins.json which is stored in database (otherwise the user cannot rebuild the index in the admin area, it throws an error)
2. Leave the user to rebuild the actual indexes manually or, if they have the Lucene Background Task enabled, it should rebuild them automatically without the performance hit of rebuilding them on server startup (even if they only have one server instance running)

**Comment by Skrypt** [comment]
Preferably I'd see a Workflow task to make the rebuild/reset index/indices configurable with a CRON task timer task.

**Comment by sebastienros** [comment]
>  it would just recreate it on the fly then rebuild it

That's what it's supposed to do, and why we moved the settings in the database, such that if an index is created, all nodes know about it and can build it locally.

**Comment by Skrypt** [comment]
Knowing that for myself rebuilding the all the indexes can take quite some time on my website. I would probably see the automatic rebuild of the indexes as an option only. That's why having it as a workflow for me makes more sense. Also, everytime I republish the website on a new Azure Node I get to rebuild the indexes, so if I want this to be available as soon as it's published by the CI I would tend to look at an option to make the index to be built by the CI.

**Comment by Piedone** [comment]
Did anybody progress on this in the meantime?

I'm looking into making an Azure App Service stateless by storing the Lucene indices off the server. It seems to me that still, the best bet is to use Blob Storage as storage and one of the corresponding Lucene libraries (i.e. [this](https://www.nuget.org/packages/Lucene.Net.Store.Azure/4.8.0-beta007) or [this](https://github.com/azure-contrib/AzureDirectory) or [this](https://www.nuget.org/packages/Lucene.Net.Store.AzureBlob/)). However, I'm not sure if any of them are kept up to date enough to be compatible with the latest Lucene.NET and storage library versions.

Rebuilding the indices after each deployment would work I guess but seems like something where we'd get something that gradually becomes slower.

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/5947#issuecomment-614108844

**Comment by deanmarcussen** [comment]
Agree that the better approach here for true stateless is support for elastic.

The blob storage option that you have talked about a few times @Piedone I have looked at, and think is pretty risky, my experience with similar techniques on Umbraco, was corrupted index, after corrupted index.

Currently we are slot swapping (twice, to get both slots at the same version), and using the LuceneBackgroundWorker to keep the indexes current, and it is sufficent for our needs.

In terms of the actual issue here, triggering a rebuild when the indexes are not present, seems reasonable, and useful to me.

**Comment by Piedone** [comment]
While with O1, we've used AzureDirectory for many years without any issues. So while I agree it's definitely risky, and the problem is not just around storing the index files (but also synchronizing write access, which is its own can of worms), it can actually work pretty well. It would be a nice alternative to using an additional service for indexing (potentially easier to maintain and perhaps cheaper to operate) but at that point, I'd just do it properly and use Elastic. (And there doesn't seem to be too big of a community around storing Lucene indices in Blob Storage, so that's a big minus too.)

**Comment by Skrypt** [comment]
ElasticSearch would be the appropriate thing to do. If you want it to be seemless without requiring to rebuild indexes on every Azure slots or instances. The Lucene module should be keep for simple websites that doesn't require much more than that.

We have the Lucene Queries that are written to "educate" people to learn how to produce ElasticSearch Queries. Here, using ElasticSearch removes the need to produce such Queries on the OC instances. With ElasticSearch, we would just need to call these Queries by name and they would be stored on the ElasticSearch server directly. So, our structure is kind of different in OC for these Lucene Queries.

What we should have is a "Lucene Server" on a separate app that would be able to scale. Something that would replicate how ElasticSearch works. This would require some work which I think would be **considerable**. We need to also consider that Lucene.NET doesn't support everything that Lucene (java) supports as of now. There are also a lot of advantages of using ElasticSearch because of it's already implemented interfaces and documentations.

**Comment by Piedone** [comment]
Yeah, Elastic would offer a lot of advantages. I'd keep queries in the OC app is possible, since otherwise the app is not just using Elastic as an external service but you also have to "deploy" code into it, effectively splitting your app (and thus making development, local testing, and operations more complex). But this is a bit offtopic here.

**Comment by Skrypt** [comment]
Yeah, the issue here is about self generating the indexes when there are none from the index definitions. 😄 
This got removed from my own changes back then because it needed refactoring.
I should take a look at this at least. The other part is about having a Workflow that could be triggered periodically on each instances to rebuild the indexes. So this would be not seamless but at least it would be updated.

**Comment by jtkech** [comment]
We already have a background task to update indexes, here we could also generate them if they don't exist, also rebuild them on demand, e.g. through a shared identifier so that when any instance has done a rebuild, it invalidates the indexes for all other instances, we already used this pattern, and recently we used it for sitemap cached files invalidation.

One "issue" here is when multiple instance share the same file system, but there may be a solution by using different folder names based on process names, and that would need to be cleanup periodically.

It's on my list related to all things to keep nodes in sync, recently we updated things about autoroutes, localized items, sitemap cached files, remaining things around media cached files and lucene indexes.

**Comment by Skrypt** [comment]
Eventually, it will come to require to be scalable too just like ElasticSearch. So maybe worth doing these changes and also consider having the Lucene module as a separate app. Then name it ElasticSearch.NET 😉

**Comment by mickdelaney** [comment]
Is Elasticsearch something that can be implemented soon ? 
We're assessing options for a CMS, we use dotnet & python, and are hosted on AWS using Kubernetes. 
Previously the Lucene index was a problem for us.
We also already leverage elasticsearch, so if that was an option we'd look at Orchard again. 
I'm just trying to understand if using ES is a 'maybe in the future' thing, or yes, its just a small change we could roll out ourselves ?

**Comment by Piedone** [comment]
I'm not aware of anybody working on it at the moment and it's definitely not a small change. It can be implemented via a third-party module though but probably better if the built-in Lucene module is changed to factor out common pieces too.

**Comment by Skrypt** [comment]
It is something that I never got time to start working on. The issue is that if we invest time on fixing Lucene we might end up going all the way back and restart by implementing ElasticSearch because of missing features in Lucene. I'd rather see someone start investing time on ElasticSearch than pushing it too far with Lucene. But that's my opinion. I think @jtkech had it working at some point with "Lucene" but it's a discussion me and him had quite often and I always end up thinking that we push onto Lucene because somehow it is "free" but it's far from ElasticSearch.

Also, if you need this kind of "search tech power", that's because you need to scale your websites and at this point we are talking about websites that generate a massive amount of traffic. Then, we can think about companies that needs Orchard Core as a SaaS service and the efforts to get there should be invested by these people that requires it and then contribute it back to the community.

**Comment by mickdelaney** [comment]
Ok, 

So Lucence is optional ?

At this point I'm assessing whether I can run this on a cluster ? 
If in order to run it on a cluster I need to commit to building an elasticsearch module ? 

Or with Orchard Core at the moment the only way to run it is on a single server ? 

Thanks again for your help.

**Comment by Skrypt** [comment]
Only the search feature of Orchard Core is not scalable as of now.
Everything else works fine. We have distributed cache (Redis) and a lot of Azure modules to handles configs between different instances. The only effort remaining is making either Lucene scalable or start working on an ElasticSearch module.

**Comment by mickdelaney** [comment]
We’re on AWS, what sort of work will I need to take on to make it work there ? 
and is there an interface(s) I can implement to integrate Elasticsearch ? 
Thanks again

**Comment by Piedone** [comment]
Could you continue this under the issue for Elastic, please? https://github.com/OrchardCMS/OrchardCore/issues/4316 This issue is about Lucene.

**Comment by mariojsnunes** [comment]
I am working with Azure App Services.
So the current solution to deploy with a Slot is to have the lucene index folders created on the slot, and activate the Lucene.Worker feature that runs IndexingBackgroundTask every minute?
