### ISSUE TITLE
Error Setup Connection appsettings.json > "OrchardCore"

### ISSUE THREAD

**Issue by devhomecali** [OrchardCMS/OrchardCore#6354]
**Describe the bug**
The following may be an error. Setup does not display connection configuration information in appsettings.json> "OrchardCore"> "OrchardCore_Shells_Database".

**To Reproduce**
1. Download updated source code.
2. Set **OrchardCore.Cms.Web** as your startup project. Configure the connection to the database in the file appsettings.json> "OrchardCore"> "OrchardCore_Shells_Database" [according this information](https://docs.orchardcore.net/en/ag-releasenotes/docs/reference/core/Shells/).
3. Run the aplication.

**Expected behavior**
The CMS configuration page should display the information defined in the appsettings.json file.

**Screenshots**
[Image](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Setup-AppSettingsDatabase.png)

**Comment by sebastienros** [comment]
I don't see the issue with your screenshot. Even if you select a database to store the shell settings, i.e. the list of tenants, each tenant can have its own database, even Sqlite.

However I found a discrepancy in the documentation. You used `_` whereas the documentation uses `.`  for `Orchard.Shell.Database` at https://docs.orchardcore.net/en/ag-releasenotes/docs/reference/core/Shells/#enable-database-shells-configuration. It might be an issue in the documentation. But it's unrelated to the issue your are describing I think.

**Comment by devhomecali** [comment]
@sebastienros I have changed **OrchardCore_Shells_Database** to **OrchardCore.Shells.Database**.

But in the Setup page the **SqLite** database type is preconfigured. **It should be Sql Server** based on the settings in appsettings.json.

[See Screeshot](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Setup-AppSettingsDatabase-2.png).

**Comment by sebastienros** [comment]
I think you didn't understand the first part of my comment.

The settings you have set are not to define what is the default database of the Setup screen.
They are related to some other database settings.

Now let me explain this setting in detail:
Orchard can host multiple tenants. Meaning with one deployment you can host multiple sites, on different urls, with different databases and content and themes. Each site will have its own database configuration. One could use Sqlite, another SQL Server, and so on.
When Orchard starts, it needs to know the list of tenants and the connection string for each of them. This list is stored in a file named `tenants.json` in the App_data folder. Create a site and open this file, you will find the connection string. If you create more tenants you will find even more connection strings.
Now some users don't want to store this list of tenants in a local json file, maybe because they want to use a web farm. Or because of security reasons. At that point they can decide to store the content of this file on Azure Blob Storage, or inside __a SQL Server database__, or anywhere else like Dropbox. 

This is what this specific location that the setting your are talking about is used for. Not the database for the site itself.

**Comment by devhomecali** [comment]
@sebastienros OK. Thanks.
