### ISSUE TITLE
ShellSettings Description and Tenant

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6417]
When the Description property of ShellSettings is changed:
- The Description in the Tenants admin page is not changed.

When the Description property of a tenant is changed from the admin:
- The Description is not changed in tenants.json.
- The Identifier is regenerated in tenants.json.

Also, it could be interesting to be able to use html in this property and to display it with Html.Raw.

**Comment by jtkech** [comment]
`ShellSettings` has 2 inner sources of data (settings and configs), one tied to `tenants.json` that is used for the minimum set of properties required to run a tenant, the other one tied to all the other config sources, e.g. the root `appsettings.json`, the specific one in the tenant folder and so on.

To access the first source of data we provide getter / setter e.g. `shellSettings.RequestUrlPrefix`, for the 2nd source we should use the indexer e.g. `shellSettings["DatabaseProvider"]`.

So we should not use `shellSettings.Description` but `shellSettings["Description"]` as done when rendering the tenant admin page. That's why you didn't see your change when using the setter. And when the Description of a tenant is changed from the admin it is not saved in `tenants.json` but in the `appsettings.json` under the tenant folder.

So it's not correct to have added this property

        public string Description
        {
            get => _settings["Description"];
            set => _settings["Description"] = value;
        }

We need to remove it or, if we want to keep it as a property, replace it by

        public string Description
        {
            get => _configuration["Description"];
            set => _configuration["Description"] = value;
        }

Note: When the Description is changed, to be persited we need to call

    _shellHost.UpdateShellSettingsAsync(shellSettings)

**Comment by agriffard** [comment]
Thank you @jtkech 

Do you know why the Identifier is regenerated everytime?

**Comment by jtkech** [comment]
It will be useful for consistency checking in a distributed env, when we update the shell settings and then reload the shell, we then reload the shell settings to check that we were the last to update them, otherwise we reload the shell and so on.
