### ISSUE TITLE
Script at:"Foot" not working anymore

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#6490]
Scripts no longer rendered in any section.
Doesn't matter if Head or Foot, the scripts are not in the final HTML as defined in the Layout.liquid file.
OC RC2-13535

**Comment by jptissot** [comment]
Do you have the proper package references to the resource management and display management package.

**Comment by Flarescape** [comment]
Hello @jptissot .

You mean on my main web project or my theme?
The thing is, that styles are working just fine, only the scripts are missing since my nuget update.

**Comment by Flarescape** [comment]
Ok I found the issue.
If I use this in my Layout.liquid `{% script name:"bootstrap", at:"Foot", version:"4.4.1" %}` and version 4.4.1 no longer exists in OC than all following liquid script tags are not executed.

**Comment by ns8482e** [comment]
`ResourceManifest.cs`  In `OrchardCore.Resources` defines resources that are used by Admin and orchard core Modules that could change its version with release of OC.

If your module/theme needs different version than OC I would suggest to define your own resource so that OC upgrade doesn’t affect your module/theme

**Comment by Flarescape** [comment]
@ns8482e Thank you, I've now changed my source to a static resource inside my theme. 👍
