### ISSUE TITLE
How to render an image shortcode?

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#6496]
How do you actually use shortcode?

The markdown editor produces something like this `[image]award-prize/2018/best_novel_emerging.png[/image]` but it is not transformed on my page. Is there any filter that needs to be use to process this?

**Comment by dodyg** [comment]
I've read this https://orcharddojo.net/blog/short-codes-new-content-filters-this-week-in-orchard-22-05-2020 but it also doesn't deal with the issue of how to render it. It just magically works.

**Comment by dodyg** [comment]
The shortcode module is enabled

![shortcode](https://user-images.githubusercontent.com/1761249/85512918-b9b01e80-b5fa-11ea-8cc1-cd0f7a63fed9.png)

**Comment by deanmarcussen** [comment]
if you're rendering the markdown directly (rather than through the driver shape) the markdown razor helper will render shortcodes.

The markdownify liquid filter might not (it probably should), but there is also a liquid filter for shortcodes ` | shortcode'

Leaving this open as well, as we need some docs for this

**Comment by dodyg** [comment]
Thanks. I am using liquid template via the CMS Templates section.

**Comment by agriffard** [comment]
You can just suffix your image by `?width=100`
