### ISSUE TITLE
Media Azure inconsistency

### ISSUE THREAD

**Issue by ruisdias** [OrchardCMS/OrchardCore#6594]
Hi,

I discovered a little bug that I would like to report to you guys.

My Type structure is:

Type
{
title
BagPart<Type2>  {
            title,
            BagPart<Type3> {
                      title,
                      image
          }
    }
}

So my Type3 is the one that has a media field and it's an item inside of a bag part in the Type2.
Type2 is an item inside of a bag part in the Type parent.

In this case, every change that I make to the item (Type) it will result in a new id to the items from Type3.

So if I save it as a draft, it will create a new Id for every Type3, so the version which is still published lost its media field because in the blob storage already as new id which is not the one here.

Please note that ContentItemVersionId is always null for Type3, and ContentItemId is almost used as a versionId because it's always generated a new one.

How to reproduce:
- Create an item with a  media file( image, pdf, wtv.);
- Publish it;
- Check-in your blob storage that the file was uploaded with the content item id;
- Change anything in the item;
- Save it as a draft;
- Check-in your blob storage for the folder with the old content item id;

**Comment by deanmarcussen** [comment]
I can repro this @ruisdias 

So when working with local media (not azure) it is resetting the `ContentItemId` on the nested items, and then moving the old media into the new medias folder / name.

(This is using the attached editor, which I presume you are using)

So nothing is getting lost, but some extra images seem to be piling up, from the old `ContentItemId` name.

What is happening with blob storage? Your issue suggests you are losing your media? Which suggests maybe another issue with blob storage and the attached field, which maybe different.

@Skrypt has raised a few issues with blob storage and the attached field also. But I'm still need some clear understanding of what the issue there is and how to repro it.

**Comment by ruisdias** [comment]
Yes, I can lose data, images in this case.

Imagine that I want to do a preview feature, when I save it as draft the image of the published one disappears.

With blob storage, the reset of the id is always renaming the folders that leads to not consistent data.

**Comment by ruisdias** [comment]
And answering to you I'm using the attached edit because I wanted to prevent other possible errors, like cache on my frontend application.

**Comment by deanmarcussen** [comment]
Thanks for the extra info @ruisdias without it I would have thought I fixed the issue.

But actually there are two issues here.
- Content Item Ids not being maintained across nested bags/widgets (easy fix)
- The Attached Media editor has an issue with it's handling of temp files. (hard to fix)

The attached media editor breaks it's images when you start creating a content item and then run the live preview before saving it. The preview calls `UpdateAsync`, which moves the files from a temporary folder, to a specific folder based on the content item id.
Then when you try and save the content item the temp files it is still using as the media path urls no longer exist, because the preview has moved them...

Not sure about the best fix for this one. 
@jtkech I know we've been giving the `Document.Id` a `-1` value, to detect preview, but I can't remember why, and checking that in the media attached driver feels like the wrong thing to do (it also won't work in the case of nested attached fields, as it would have to know about the parents `-1` id)

Neither of us wrote the attached driver @jtkech so just thinking of ideas here.  
It feels like the temp folder concept is causing the problems, more than the preview. 

Need to look, and think a little further, but if you have any ideas?

To repro, 
- create a simple content type with just an attached media editor.
- start creating a content item
- select a media item
- click preview (see the field show up in the preview, with its guids/file hashes
- save the content item
- open for editing
- files are missing

I'll start a draft with the fix for the widget/bag content item ids, and think some more about the other issue

**Comment by jtkech** [comment]
@deanmarcussen 

Yes at least i could repro, but as you said need to look, and think a little further

No problem i will try to help you on this one, but too lazy to start on it this night ;)

**Update**: That said just tried the following in `MediaFieldDisplayDriver` that seems to work

    // If it's an attached media field editor the files are automatically handled by _attachedMediaFieldFileService
    // We also need to check if we are in the Preview mode that uses an unique content item id of -1, this to prevent
    // new uploaded media files from being moved from the temp folder to a folder based on this fake content item id.
    if (field.ContentItem.Id != -1 && String.Equals(context.PartFieldDefinition.Editor(), "Attached", ...))
    {
        try
        {
            await _attachedMediaFieldFileService.HandleFilesOnFieldUpdateAsync(items, field.ContentItem);
        }
        ...

But maybe a little hacky, at least it confirms the source of the issue.

**Comment by deanmarcussen** [comment]
Thanks @jtkech for confirming.

Yes I tried the `-1` as well, and it will work, but not if the attached field is in a bag or a flow, because then it's content item id is == 0, because it will never be saved in the db.

I will look further, but my initial thought is that we should not be doing this file moving in the `DisplayDriver`, but in a `Handler`, on publish. Much like how we would manage autoroute and alias unicity.

But that may introduce other issues (and it may need to be model bound)

I will try something along those lines though and see what would happen.

**Comment by jtkech** [comment]
@deanmarcussen 

Okay cool, didn't have any time to look at it further

Easy to say but we just need to know that we are in a `Preview` mode ;)

**Comment by deanmarcussen** [comment]
@jtkech yes I haven't had any time either.

I remember @sebastienros had an idea when we introduced `-1` to improve it, but I can't remember what it is.

I can check the route dictionary for a `contentItemId` - there will be one if it has been routed, but not in preview mode I suspect.

Handlers will be challenging when I looked, there is it would still need to know if it's in preview.

And it can't be on the published event because the temp directory gets cleared on server restart, so it does need to happen on `Save` as such...

**Comment by jtkech** [comment]
@deanmarcussen 

Still a little hacky but the following also works if the attached field is in a bag

    private readonly bool _isPreview;

    public MediaFieldDisplayDriver(
        IHttpContextAccessor httpContextAccessor,
        AttachedMediaFieldFileService attachedMediaFieldFileService,
        IStringLocalizer<MediaFieldDisplayDriver> localizer,
        ILogger<MediaFieldDisplayDriver> logger)
    {
        _attachedMediaFieldFileService = attachedMediaFieldFileService;
        S = localizer;
        _logger = logger;

        _isPreview = httpContextAccessor.HttpContext.Request.RouteValues["controller"]?.ToString() == "Preview";
    }

        ...

    // If it's an attached media field editor the files are automatically handled by _attachedMediaFieldFileService.
    // We also check if we are in Preview to prevent new uploaded media files from being moved from the temp folder.
    if (!_isPreview && string.Equals(context.PartFieldDefinition.Editor(), "Attached", StringComparison...))
    {

**Comment by deanmarcussen** [comment]
@jtkech will work.

But I am more tempted to put something in the `httpcontext.items` dictionary in the `PreviewController` to say `Preview` is active, and check that, rather than checking route values here.

Possibly because others might implement their own preview controllers, so that way we would have a more defined way to say we are in preview mode - thinking of you @ns8482e and your new preview feature (don't know if it has it's own controller or not, but looks cool)

Agree, maybe it's something that should be in the editor context. I don't know if this issue affects other drivers - can't think of any, as most are handled in the handler

**Comment by ns8482e** [comment]
> thinking of you @ns8482e and your new preview feature (don't know if it has it's own controller or not, but looks cool)

Thanks @deanmarcussen , I am also using ootb preview feature in my device preview module. I like the idea of using `httpcontext.items` How about using `[Preview]` attribute defined on controller/razor page defines it as preview request ? similar to what we do for admin

**Comment by jtkech** [comment]
@ns8482e @deanmarcussen 

Okay let's use `httpContext.Items`, i also like to use `httpContext.Features` often used by aspnetcore, but just saw that if there is a `PreviewPart` and a `PreviewAspect`, the `PreviewController` already uses `HttpContext.Items["PreviewPath"]`.

Note: Just to say that the `ShellScope` also has items and features collections.

**Comment by deanmarcussen** [comment]
Hey, we all agree on something ;)
