### ISSUE TITLE
Autoroute SetHomepage not setting value when homepage changes

### ISSUE THREAD

**Issue by andrew2241** [OrchardCMS/OrchardCore#6653]
I am having an issue where the Autoroute.SetHomepage is always set to false. 

I created a check in my alternate view for a content item that looks at the Autoroute.SetHomepage. When I load my homepage this value is set to false. I went in to the database and noticed that on 6/15/2020 my homepage had the Autoroute.SetHomepage = true. Then I had made some modifications or republished the homepage on 7/8/2020 and the value was set to false. 

Steps I have taken:
- Create new content item and check the Autoroute option to set the homepage. The homepage does change when I visit the root url. The SetHompage value is still false though.
- I went back to original homepage and checked the Set Homepage option to make it the homepage again.  Again, the homepage changes when I visit the root url, but the SetHomepage value is still false.

I am checking this value to populate the canonical url section I created.  I look to see if it is the homepage so that I do not use the Autoroute.Path, I just want the Site.BaseUrl. I put a workaround in for now.  Any advice on this issue would be greatly appreciated.

**Comment by deanmarcussen** [comment]
This is actually by design.

I fixed a bug recently where the property was being allowed to be set true and saved to the database.

The reason for this design is because otherwise this property would be set true for many homepages when you changed the homeroute. Otherwise we would have to look up the existing, set it false, save it as well, then allow the new one to be true.

Not sure what workaround you have used, but what may work for you is to use the `UrlHelper` to generate the routes.

The UrlHelper will return `/` if the page is currently the home page, rather than it's assigned url.

**Comment by andrew2241** [comment]
Thank you Dean.  This helps out a lot.

**Comment by agriffard** [comment]
Can you please tell me what is the reference to the fix you mention @deanmarcussen?

**Comment by deanmarcussen** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/ab3a1e4ec060dd30b0a19736e05f4db30b56151e/src/OrchardCore.Modules/OrchardCore.Autoroute/Handlers/AutoroutePartHandler.cs#L117
