### ISSUE TITLE
Add helper for generic site settings deployment step

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6657]
Small improvement on https://github.com/OrchardCMS/OrchardCore/pull/6570/files: Add a helper/extension method for registering a site settings deployment step (i.e. what you can see in all the `DeploymentStartup`s) in the common configuration (that all registrations under the PR seem to be doing). Would maybe need a type parameter for the settings class, another one for the startup class (to resolve the `IStringLocalizer`) and a factory delegate or something to create the two localized strings.

**Comment by deanmarcussen** [comment]
@Piedone you should come or listen to the meetings where we discuss these things more often ;)

The issue is the the https://github.com/lukaskabrt/PoExtractor will not find these strings if held in an extension method.

The suggestion was to open an issue there, to provide, possibly an attribute which could serve as an identifier, on the startup classes so that the extractor would look at the funcs, i.e `() => S['text'])` in extension methods.

**Comment by hishamco** [comment]
@deanmarcussen if the lack is that PoExtractor not find the localized strings in extensions methods, I can work to support this

**Comment by deanmarcussen** [comment]
@hishamco have a watch of last weeks meeting video for the suggestion and explanation of the issue

**Comment by hishamco** [comment]
I didn't see the last meeting, I'm not sure if it's published on YouTube yet, is the issue explained during the demos?

**Comment by Piedone** [comment]
Ah, thanks Dean!
