### ISSUE TITLE
Routing in a custom module

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6709]
I just extend the current users module to add a new feature, my route in my new module looks like

```csharp
routes.MapAreaControllerRoute(
                name: "XXX",
                areaName: "OrchardCore.Users",
                pattern: _adminOptions.AdminUrlPrefix + "/Users/XYZ",
                defaults: new { controller = typeof(TestController).ControllerName(), action = nameof(TestController.ActionName) }
            );
```

whenever I click the link the address bar shows the correct route but I got 404!! @jtkech any idea?

**Comment by jtkech** [comment]
The area name needs to be the module assembly name where the controller is defined

So you can keep your pattern but try to use your module name for the area

**Comment by hishamco** [comment]
Let me have a try

**Comment by hishamco** [comment]
Same thing ;( my expectation was to find  a named param `namespace` like what we have in the previous version of ASP.NET MVC, without changing the area name

**Comment by jtkech** [comment]
Did you enable your module

Otherwise i will try it as i have time

**Comment by jtkech** [comment]
What is `TestController.ActionName`?

Just tried the following in the `OC.Contents` module, it works

    public class TestController : Controller
    {
        public IActionResult Index() => Content("Hello");
    }

    routes.MapAreaControllerRoute(
        name: "XXX",
        areaName: "OrchardCore.Contents",
        pattern: _adminOptions.AdminUrlPrefix + "/Users/XYZ",
        defaults: new { controller = typeof(TestController).ControllerName(), action = nameof(TestController.Index) }
    );

**Comment by hishamco** [comment]
> Did you enable your module

Of course ;)

`OrchardCore.Contents` as area name is assembly name not namespace, right?

I did exact same thing, let me try one more time ...

**Comment by hishamco** [comment]
Here is the route on action:

https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/impersonation/src/OrchardCoreContrib.Users/Startup.cs#L61-L69

**Comment by jtkech** [comment]
@hishamco 

It's because of your `Manifest.cs`

You always need the `[assembly: Module(` attribute, then if you only have one main feature it's sufficient, if there is no feature attribute a single feature is registered with an `Id` equal to the module id which by default is equal to the module assembly name. But, even if there is only one feature, it's good to also use the `[assembly: Feature(` attribute for this feature, the convention being that the `Id` of the first feature is equal to the module id, in your case `OrchardCoreContrib.Users`.

In fact, for the first feature you can use another `Id` but in this case you will have to decorate some classes as the startup and controllers with `[Feature(AnotherId)]` attributes specifying that these classes are tied to this feature. The advantage of using the module id for the 1st feature is that all non decorated types are automatically tied to this feature.

**Comment by hishamco** [comment]
Seems I follow the email module where there's no `FeatureAttribute`

Thanks a lot

**Comment by hishamco** [comment]
I ended up to user another Id in this case, but I think it would be nice if we have an optional params in `FeatureAttribute` to supply all the classes instead of decorating each one, or add a services that can register this in our behalf

Thanks again
