### ISSUE TITLE
Load a index.html page when open a Blank project

### ISSUE THREAD

**Issue by Nowhk** [OrchardCMS/OrchardCore#6729]
I've setup the CMS orchardcore as Blank, using it to only manage content via API, and the website is rendered using a frontend framework like Vue.js

So, all the front end project is build within wwwroot folder, and is accessible by index.html.

I'd like to recall that page calling www.mydomain.com, instead of www.mydomain.com/index.html

Would be nice to do it directly. Not sure if its achievable right now, can you add this feature?

**Comment by ns8482e** [comment]
You can set Home page  in  MVC / Razor - see following comment by @jtkech in another related issue.

https://github.com/OrchardCMS/OrchardCore/issues/6235#issuecomment-648353184

**Comment by Nowhk** [comment]
@ns8482e hi, thanks for the reply.

Tried this way:

`public void ConfigureServices(IServiceCollection services)
{
	services.AddMvc().AddRazorPagesOptions(options => 
	{
		options.Conventions.AddPageRoute("/", "index.html");
	});

	services.AddOrchardCms();
}`

But I got 500, and nothing load.

**Comment by Nowhk** [comment]
I think I've fixed it. I've simply add `app.UseDefaultFiles();` before `app.UseStaticFiles();` and it find index.html within wwwroot.

Is it correct in your opinion? Thanks

**Comment by ns8482e** [comment]
@Nowhk  Nice!,  

However there is an open issue #6505 with `UseStaticFiles()` - currently it only works with Default tenant.

If you plan to use your vuejs app in multi tenant scenario i.e.  www.mydomain.com/index.html, www.mydomain.com/tenant1/index.html ,  www.mydomain.com/tenant2/index.html then It's suggested that you use `indext.cshtml` instead of static `index.html`
