### ISSUE TITLE
placement via json file only works for Content zone

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#6730]
I'm trying to place shapes in specific zones through the placement.json file, but it only works for the Content zone.

To reproduce follow these steps:

1. Change the Content-Blog.liquid file to this:
```
{% shape_remove_item Model.Content "Blog-Image" %}

{{ Model.Content | shape_render }}
```
2. Add a placement.json file with the following contents
```
{
  "HtmlBodyPart": [
    {
      "displayType": "Detail",
      "place": "Header:5",
      "contentType": [ "Blog" ]
    }
  ]
}
```
3. Start OrchardCore and create a web site with the TheBlogTheme.
Now the HtmlBodyPart is not shown.

4. Change the place in the placement.json file
```
    "place": "Header:5",
```
5. Start the web site
Now the HtmlBodyPart is visible.

**Comment by ns8482e** [comment]
To target Layout zone use prefix it with `/` i.e. `"place": "/Header:5"`

When you define placement as `"place": "Header:5"` you are defining only local zone created within the shape of  your content item. 

For example, if you define `"place": "CustomZone:5"` in placement, It won't be rendered by default. As  the default  OC provided content template is not aware of your `CustomZone` ( default local zone  provided in Contents module are `Header`, `Meta`,  `Content` , `Footer`).  

However you can access your `CustomZone` local zone  in your content template using `Model.CustomZone`


local zone `Header` in `TheBlogTheme` is not rendered because `TheBlogTheme` overrides default content template and only renders `Content`  local zone.

**Comment by ArieGato** [comment]
I knew this from OC1. I couldn't find it in de documentation though, or I missed it somewhere.
