### ISSUE TITLE
MediaField just checking file extensions

### ISSUE THREAD

**Issue by ruisdias** [OrchardCMS/OrchardCore#6767]
Hello,

During some tests, it was discovered that we can upload any type of file if we just change the extension to one which is accepted (defined in the appsettings).
It has been tested with .svg extension files.

In order to solve it, the MIME-type could be checked to see it the upload could be done or no.

I was checking in the source code and I got to this conclusion, please correct me if I'm wrong.

Thanks in advance,

Rui Dias

**Comment by hishamco** [comment]
There's an option to allow specific media extensions @deanmarcussen correct me if I'm wrong

**Comment by ruisdias** [comment]
@hishamco yes, it exists. But my point is that the extensions don't ensure that the file is exactly what the extension says it is. For example, I can send a .exe change it to .svg and the application will accept it.

**Comment by deanmarcussen** [comment]
You are correct @ruisdias 

We check file extensions - that's why it's called `AllowedFileExtensions`, as does the underlying ASP.NET Core `StaticFileMiddleware` when serving the file, so it is based on that.

Many browsers apply the same technique to calculate a mime type, so I'm not sure checking the mime types would achieve anything.

We've already validate that you can't rename a file if it is not in the `AllowedFileExtensions`, so you can't turn a `.svg` into a `.exe` if it is not allowed.

My question would be, how is this causing you an issue?

**Comment by hishamco** [comment]
> For example, I can send a .exe change it to .svg and the application will accept it.

You are right, @deanmarcussen seems the point is if the `.svg` is allowed extension, so any `.exe` file after alter its extension to `.svg` will be accepted

**Comment by sebastienros** [comment]
You can also alter the headers, so checking the mime type is not a solution.
There is no way around this issue. At least, when the file is downloaded, it won't trigger the automatic execution (for exe).
