### ISSUE TITLE
 Confirmation form

### ISSUE THREAD

**Issue by vahid001** [OrchardCMS/OrchardCore#6794]
In Workflow we need the Confirmation form
That we can put different  actions(such as 'Are You delete record ?' or 'Are you confirm action?' ----> actions :'ok','cancel','Yes','Cancel',. . . ) in it and open it in a modal or alert
If possible, consider this as a future work
Thanks a lot

**Comment by sebastienros** [comment]
I don't see how it could drive a Modal window since it would be triggered by a front end action. The only thing that can be done is a redirection to a dedicated page with actions, that can update the workflow. But this could also be done with custom pages and workflow action links (Http request activity).

Feel free to describe the scenario you have in mind though. But to my it looks like you just need to build your own pages, and maybe trigger specific workflows based on specific actions from the user.

**Comment by vahid001** [comment]
@sebastienros 
all right
Thank you
