### ISSUE TITLE
Shortcodes with parameters

### ISSUE THREAD

**Issue by KshitizGIT** [OrchardCMS/OrchardCore#6819]
I need to add a custom class to the image rendered by the ImageShortCode.  I was hoping it could be achieved by this
[image class="image-fluid"] path of image [/image].

But it doesn't work. Can anyone suggest any other approaches ?

**Comment by hishamco** [comment]
AFAIK there's no `class` attribute in the `ImageShortcodeProvider`, @deanmarcussen can we add this while It's common and useful?

**Comment by KshitizGIT** [comment]
It was useful for me, so I have fixed this issue ? Can I send a pull request for this ?

**Comment by deanmarcussen** [comment]
Yes, please send a pr.

If you wanted you could add this feature request as well https://github.com/OrchardCMS/OrchardCore/issues/6745

There was no class attribute added originally because shortcodes are intended to be simple, and not require the content editor to know about html classes, however the `[image]` shortcode is a little bit of an exception as it is also needed to be used by developers to get access to the media library, so I'm ok with adding a class argument
