### ISSUE TITLE
InvalidOperationException: Invalid serial number for shell descriptor ERROR in Orchard Core 

### ISSUE THREAD

**Issue by nasimnk** [OrchardCMS/OrchardCore#6833]
I am using orchard core in .net core 3 and in the start page of setup orchard, when select sql server and click Finish Setup button, this error shown up:

**InvalidOperationException: Invalid serial number for shell descriptor**
OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(int priorSerialNumber, IEnumerable<ShellFeature> enabledFeatures, IEnumerable<ShellParameter> parameters) in ShellDescriptorManager.cs
OrchardCore.Setup.Services.SetupService+<>c__DisplayClass11_1+<<SetupInternalAsync>b__1>d.MoveNext() in SetupService.cs
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
OrchardCore.Setup.Services.SetupService.SetupInternalAsync(SetupContext context) in SetupService.cs
OrchardCore.Setup.Services.SetupService.SetupAsync(SetupContext context) in SetupService.cs
OrchardCore.Setup.Controllers.SetupController.IndexPOST(SetupViewModel model) in SetupController.cs
lambda_method(Closure , object )
Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in ModularTenantRouterMiddleware.cs
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

How can I fix that?

**Comment by hishamco** [comment]
Which version of OC and SQL Server are you using?

**Comment by nasimnk** [comment]
OrchardCore.Application.Cms.Targets  [v: 1.0.0-rc2-13450]
SQL Server 2017

**Comment by deanmarcussen** [comment]
The problem you're experiencing is trying to run setup on a database that has already had setup run against it.

You would need to delete your existing database (or properly clear it's contents) before running setup again.

**Comment by nasimnk** [comment]
Yes I deleted existing database and created it again, the error changed: 
DirectoryNotFoundException: Could not find a part of the path '...........\App_Data\Sites\Default\ContentDefinition.json'.

Did I something wrong?

**Comment by deanmarcussen** [comment]
Just delete the whole `App_Data` folder and your database

**Comment by nasimnk** [comment]
Deleted DB and App_Data folder but the error is still the same.

**Comment by nasimnk** [comment]
I created full directory (....\App_Data\Sites\Default) and it worked!!
Thanks

**Comment by willnationsdev** [comment]
So, I am encountering this same error, but I would like to find a resolution that doesn't involve deleting the entire database / App_Data folder.

We have our Default site, and it works, and we have created some test sites for experimentation (just getting started with OCC). `test` at `/test` got set up with a SQL Server connection and a `test_` database successfully. We then wanted to see if it was possible to not POST the connection string, so we created a `test2` site at `/test2` with `None` for the database. We then directly modified the `App_Data/Sites/test2/appsettings.json` to have the same connection string, table prefix, and sql provider. Run `Reload` button. Run `Setup` button. Get OP's issue. We consider that it might be because of our manual creation, so we try to start over by deleting the `Sites/test` and `Sites/test2` subdirectories, along with deleting each of the `test_` tables in the database. However, strangely enough, even with the sections removed from `tenants.json`, the rows in the GUI still appear. We attempt to set things up only through the GUI this time around, hitting `Edit`, updating the stuff to have the same values as before, `Save`, then `Reload` in tenants page. Then `Setup` in tenants page. Fill in setup info and hit `Finish Setup`. Did this process for the first site and it worked successfully. Did it for the second site and, again, ran into the same issue as OP.

Any clarification on how to get around this without completely deleting everything? I mean, if we really needed to, we could, but we'd like to know if there's a way to add and remove tenants without breaking things.
