### ISSUE TITLE
When you do a release (deploy) the app_data/contentDefinition.json is overwritten every time

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#6855]
Hi folks, 
What would be a good solution for deploying orchardcore cms? My issue is that everytime I create new content definition it gets save on the server (QA) and so when I deploy my local code it overwrites the one on the server (app_data/sites/default/contentdefinition.json) so then all my new content items disappears because I create the definition on the server which is our QA. 

Hope this make sense. I tried the gitignore but it was still overwriting it.

Thanks guys!!

**Comment by deanmarcussen** [comment]
The reason gitignore has not worked for you is because once the file is in git, you need to remove it / stop tracking it, just adding to the .gitignore is not enough.

Personally I always ignore the entire `App_Data` folder, and never deploy anything in it, but that's a matter of opinion.

What I would actually recommend for you is to move the content definition store to the database on your qa server. See this guide for the procedure https://docs.orchardcore.net/en/dev/docs/guides/content-definitions/

**Comment by webmedia1012** [comment]
oh very cool, I'll give it a shot, didn't think I could put in in the DB, that's what I was thinking if there was a way! thank you @deanmarcussen appreciate what you guys do.
