### ISSUE TITLE
Images disappear after resize in Trumbowyg html editor

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#6864]
steps to repo:

1. Create a site with TheBlogTheme
2. Alter the content type definition of Article.
- Set HtmlBody editor to Trumbowyg
- Check 'Insert Media with url'
3. Create new Article
- Set Title
- Add image home-bg.jpg
- Resize image
- publish

Now the image is removed from the html

**Comment by hishamco** [comment]
Please a gif screenshot shows the bug

**Comment by ArieGato** [comment]
![6864_image_resize](https://user-images.githubusercontent.com/1059562/89797145-dbbe1b80-db2a-11ea-9495-7a9a9780179e.gif)

**Comment by ArieGato** [comment]
I have a better capture.

![6864_image_resize_2](https://user-images.githubusercontent.com/1059562/89798680-bfbb7980-db2c-11ea-9bd4-199a0b8e5e25.gif)

**Comment by deanmarcussen** [comment]
I seem to recall you have to turn sanitization off. was that the conclusion we came to on that one @agriffard ?

**Comment by thomasebsmith** [comment]
I'm experiencing the same problem, and turning off sanitization doesn't work for me.

This issue is caused by Trumbowyg replacing `<img>` elements with `<canvas>` elements when images are resized. Trumbowyg changes the canvas back into an image when the editor is no longer focused, but if you don't do that before publishing/previewing, the canvas (which won't be rendered correctly without Trumbowyg) will be saved to the HtmlBodyPart or HtmlField.

One approach to a fix would be to trigger the `tbwblur` event whenever the content is previewed or published. [This causes the image resize canvas to be destroyed and turned back into a regular `<img>` element](https://github.com/Alex-D/Trumbowyg/blob/c4f1bac367d63242776e74e6c8a34e27945b2d3f/plugins/resizimg/trumbowyg.resizimg.js#L293). However, I'm not sure that this approach would be ideal.

**Comment by PiemP** [comment]
I have already made a PR to trubowyg to fix this issue and give some new functions https://github.com/Alex-D/Trumbowyg/pull/1116

**Comment by PiemP** [comment]
about the preview issue in the 2° message I have to check what happen because the the event on the editor seems not fired.
