### ISSUE TITLE
Extending the User with Custom Properties

### ISSUE THREAD

**Issue by mattobox** [OrchardCMS/OrchardCore#6905]
I'm following the example of the User Time Zone source code to create my own custom properties for the User. It appears to be working well except for when I try to edit the User settings within the Admin console. When I do so, it states that it can't find the custom view. In my project, I'm just referencing the Orchard Core framework so I'm not sure where to put the UserCustom.Edit.cshtml view. Obviously the TimeZone view is found here: \OrchardCore.Modules\OrchardCore.Users\Views\UserTimeZone.Edit.cshtml

Is there a way I can inject a view without having to mess with the direct source code?

Thanks in advance.

**Comment by hishamco** [comment]
I think we already discussed this long time ago with user profile in another issue

**Comment by mattobox** [comment]
I searched for quite a while and couldn’t come up with anything. Do you have a reference you could point me to?

**Comment by deanmarcussen** [comment]
The approach I would recommed is to create a module see here -> https://docs.orchardcore.net/en/dev/docs/getting-started/templates/

and use your code in the `Module/Views` folder.

This is necesary because your theme isn't the current theme when running in the admin, the admin theme is, so a view placed in a theme won't be found.

You should also be able to use your host / startup project to place the view, as it will act as a super theme for both the admin, and your current theme, but again I would recommend it is good to take advantage of the modular framework, and make a module. It keeps everything cleaner, and the code becomes more reusable.

**Comment by ArieGato** [comment]
> I think we already discussed this long time ago with user profile in another issue

Is this PR what you are looking for: #3141

**Comment by hishamco** [comment]
Exactly!! thanks for link the PR @ArieGato

**Comment by mattobox** [comment]
Thank you for providing this helpful information. Kudos!
