### ISSUE TITLE
Attached media files are not included in the deployment plan

### ISSUE THREAD

**Issue by lukaskabrt** [OrchardCMS/OrchardCore#6913]
I have a ContentItemType with a Media field with Attached editor type. 

If I try to execute a deployment plan definition with the following steps:
* Media
* ContentItem

I got a ZIP file, that contains files from media library, but none of the attached images. I would expect attached images to be also included. Example: [Import.zip](https://github.com/OrchardCMS/OrchardCore/files/5079550/Import.4.zip)

Version: 1.0.0-rc2-14115

**Comment by deanmarcussen** [comment]
Are you using blob storage, or local storage?

Seems to work ok for me with local storage, but blob storage might be listing the folders differently.

**Comment by lukaskabrt** [comment]
I am using blob storage.

**Comment by deanmarcussen** [comment]
> I am using blob storage.

Ok, I thought it might be blob storage related.

The problem is that blobstorage does not correctly implement the `includeSubDirectories = true` option, it never has.

This is because it's not like a normal file system where you can make one request and list everything, so it would have to make recursive requests for every directory it finds.

The newer api we use may have changed that, but I suspect it hasn't. Will have a look.

Ironically the media step driver does this recursion already itself, but the  recipe step does not, when using `Include All Media`.

So the short term workaround should be to specify the attached fields folder `mediafields`, rather than `Include All Media` when creating the step.

This issue with the `includeSubDirectories = true` affects this step, and the GraphQL media query - it's the only place we use it.

Will have a bit of a think and decide whether recursively fetching directory contents inside the media service itself with repeated blob storage requests is really a good idea or if we can handle it some other way.
