### ISSUE TITLE
Taxonomies Shape type 'ShortcodeModal' not found.

### ISSUE THREAD

**Issue by snovak7** [OrchardCMS/OrchardCore#6925]
After merge #6896 we get this now:

Shape type 'ShortcodeModal' not found.

**Comment by ns8482e** [comment]
I am also getting same error in ` HtmlBodyPart-Wysiwyg.Edit.cshtml` in `dev`

**Comment by deanmarcussen** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/discussions/6908

Please reenable the feature (it has some case sensitivity issues due to the rename)

**Comment by ns8482e** [comment]
@deanmarcussen I have the feature not enabled. It seems either dependency missing in other modules that use the shape.

**Comment by snovak7** [comment]
@deanmarcussen also without the enabled feature.

**Comment by deanmarcussen** [comment]
The feature is required, and correct in the dependencies.

Please reenable it.

It has been partially lost from your installation due to the change of name, which is affecting finding the shape.

It's not an optional feature, but you can blame me for getting the name wrong first time round (`ShortCodes` -> `Shortcodes`)

**Comment by ns8482e** [comment]
@deanmarcussen may be it's `case` issue. However don't understand why the feature was not showing `enabled` in admin when I have `ContentFields` already enabled ?

**Comment by snovak7** [comment]
Enabling features fixes the problem.
