### ISSUE TITLE
Shape type 'Layout' not found

### ISSUE THREAD

**Issue by Iptonius** [OrchardCMS/OrchardCore#7096]
While trying to update to the newest version our back-end started to give the exception that Shape type 'Layout' not found. However we are using the standard admin theme and also the admin panel isn't reachable anymore.

Restoring the previous version also results in the same exception.

Hereby a more detailed stack trace of the exception we are getting and no clue how to solve it.

![image](https://user-images.githubusercontent.com/5961354/93501301-8f2de300-f915-11ea-98d9-58e5749f9fda.png)

**Comment by Skrypt** [comment]
Look at your database and make sure a theme is enabled. Or also make sure if you have a custom theme that it is added to your OrchardCore.Cms.Web project so that it loads it. Seems like an issue where it tries to find your Layout.cshtml or Layout.liquid template and it doesn't find it. Try also looking at your database and find the SiteSettings row in the document table where it sets the current active theme for the frontend website.

**Comment by sebastienros** [comment]
Please provide some repro steps.
