### ISSUE TITLE
Can't enable features whose id ends with a blocked file extension in IIS

### ISSUE THREAD

**Issue by Lawyerson** [OrchardCMS/OrchardCore#7172]
I tried to create a module called "MyCompany.Resources" and found that I can't enable it because IIS blocks any request ending in ".resources" by default. The list of blocked extensions includes a bunch of terms that could conceivably be used in feature ids such as ".master", ".browser", ".sitemap", ".config", ".skin" etc. It's possible to override this behavior in the web.config file but this would have to be done on a per-application basis and carries unwanted security implications.

Is there a way around this or should we just pay attention to our naming?

**Comment by deanmarcussen** [comment]
Funnily enough this is why the `Sitemaps` module is named `Sitemaps` not `Sitemap`.

I decided at the time it was better to just be careful with the naming.

@jtkech may have some thoughts on this

For info JT it's because the Features. Enable/Disable uses the feature name as part of a route parameter.
i.e.
https://localhost:5501/Admin/Features/Enable/OrchardCore.Sitemaps

So I imagine a work around would be for the feature id to be part of the query string (don't think IIS blocks the query string, just the route - could be wrong)
https://localhost:5501/Admin/Features?enable=OrchardCore.Sitemaps

**Comment by Lawyerson** [comment]
Also, my curiosity got the best of me and I tried to disable the OrchardCore.Resources feature. I would be grateful if anyone could tell me how to re-enable this and all dependent features without access to the admin panel. I had hoped that editing their EnableState property directly in the Document table would be enough but that didn't do the trick.

**Comment by jtkech** [comment]
@deanmarcussen @Lawyerson

Yes, nothing to add

> So I imagine a work around would be for the feature id to be part of the query string

Good idea

My suggestion would be to use this pattern `Admin/Features/{id}/Enable` in place of `Admin/Features/Enable/{id}`

**Comment by deanmarcussen** [comment]
> My suggestion would be to use this pattern `Admin/Features/{id}/Enable` in place of `Admin/Features/Enable/{id}`

Yes, that'd be the way to go

**Comment by hishamco** [comment]
I will apply this change ...
