### ISSUE TITLE
Theme dependency documentation

### ISSUE THREAD

**Issue by daerogami** [OrchardCMS/OrchardCore#7239]
I have a theme I have worked on and off with up to beta3. Now coming back to it and updating packages from beta3 to RC2, I am finding a shockingly large number of changes that don't appear to be clearly documented. When trying to follow theme documentation and release notes, I saw no mention that NET Standard was not the supported framework target for themes anymore. Just had to figure that out by the beta3 package updates complaining that my project wasn't netcoreapp3+. So while yes, the message is pointing me in the right direction, I have no way of knowing that the packages I am updating still belong in a theme project and that the API wasn't migrated/refactored to other packages. I made mention in #3799 of a solution that looks like it doesn't apply anymore when compared with the base themes from source.

Even when I mimic as much of the structure of the themes from source, I still get an issue like #3799. So to summarize what I am asking, could an additional section be added to https://docs.orchardcore.net/en/dev/docs/getting-started/theme/ that clearly states the following:

- Minimum framework required for themes using the recommended packages
- Minimum packages that need to be installed from nuget
- Any manual modifications of the project file for a minimum implementation

The ordeal of updating has been frustrating and opaque; a common theme throughout my journey with OrchardCore (mostly on being opaque). That being said, the docs have _vastly_ improved since I started; which I haven't been able to fully appreciate because of this theme dependency blocker.

**Comment by daerogami** [comment]
> Perhaps for v1 the document in theme could be extended with a note what to do when upgrading from beta and rc versions. Using a generated theme module as a reference for example.

This is a fantastic suggestion.

**Comment by Skrypt** [comment]
That's kind of the price to pay when living on the edge with beta software.
Here the thing is that the template themes are using Liquid views so they don't require to use the Razor templates.
When you want to add Razor template support in a custom Theme or Module you want to add this in your .csproj :  

```
<Project Sdk="Microsoft.NET.Sdk.Razor">
```

You will see that most modules are using Razor templates so they use this line in their .csproj.
If you only need to use Liquid templates then it is recommended to use this instead :  

```
<Project Sdk="Microsoft.NET.Sdk">
```

As for the change about .NET Standard. I believe that it has been dropped because of the fact that .NET Standard 2.1 doesn't support .NET Framework 4.8 anymore. That's because we moved to .NET Core 3.x.
These informations can be found on Microsoft website.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard
https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/#:~:text=%20Here%20are%20the%20highlights%3A%20%201%20Span%3CT%3E.,made%20heavy%20use%20of%20dynamic%20features...%20More%20

While we are developping OC it is more likely that we will introduce breaking changes. Though, Orchard Core 1.0 should be using .NET Core 3.1 which is a LTS version if it can ease your mind 😉
