### ISSUE TITLE
User entity should have CreatedDate, ModifiedDate

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#7242]
User entity should have CreatedDate, ModifiedDate.

**Comment by hishamco** [comment]
I think AuditTrail module may be useful for such thing

**Comment by sebastienros** [comment]
Not sure about Modified (would not be sufficient). 

We might want more though like "PasswordChanged", "UsernameChanged" ... Or just let audit trail handles that since you will also have full history, instead of just the last one. Maybe "LastPasswordChanged" might be useful, or "LastLogin", I could see some usage.

Someone will comment on everything that is already available in ASP.NET Identity (which we implement).

**Comment by Piedone** [comment]
Audit Trail now provides all of these.
