### ISSUE TITLE
Add ListContent Permission to each Content Type permission

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#7289]
![image](https://user-images.githubusercontent.com/16968103/96212367-48311d00-0fa9-11eb-8a2e-f86e018b905a.png)

This would allow to decide which Content Type we want to show only owned content or not.
If the ListContent permission is set on the OrchardCore.Contents this would allow it on every Content Type (override the each Content Type permission) just like we do with the other permissions.

**Comment by Skrypt** [comment]
Yes???

**Comment by chinasqzl** [comment]
No problem , controlling the list of different content types.

**Comment by chinasqzl** [comment]
A ContentType : List content item(s) owned by all users
B ContentType : Owned by me
@Skrypt

**Comment by Skrypt** [comment]
@chinasqzl I'm sorry I don't understand what you are trying to make me understand. Write it in mandarin I will use Google translate?

**Comment by Skrypt** [comment]
Let me explain what is : List content item(s) owned by all users.
We added the Permissions.ListContent in the OrchardCore.Contents module. We added this permission because someone could want to allow a user to only see it's "own" content. We have on each content items in the database a column "Owner" which defines who created the content item. Sometimes, you want to only allow users to only see what they created "What they own" as in being the owner of the content item.

This Owner field on the ContentItem is used to verify if a user has authorization on the content item. The Authorization verified could be EditContent, PublishContent ... each permissions that we have in the admin.

Now, if you check the Permission : List Content... it will allow the users assigned to this role to see content items that they did not create. You could either also check the permission "Edit Content from other" to allow editing content items that your users don't own. But we also wanted to let you decide if you want your users to be restricted to see only their own content or not.

**Comment by Skrypt** [comment]
I will check something maybe Dean made me change the description and it is actually the opposite we do. By default we let user see all content?

**Comment by Skrypt** [comment]
No it's fine, by default a user can only see it's own content which seems appropriate.

**Comment by chinasqzl** [comment]
Permissions.ListContent  是让用户看到所有的内容
但我有A内容项，我想让拥有Permissions.ListContent权限的人看到所有用户创建的。
但有B内容项，只可以创建者看到，但现在无法控制。

**Comment by Skrypt** [comment]
Ok so you have one content item "B" that can't be seen by an administrator for example? By default, Administrators should have the ListContent permission assigned. They are supposed to be able to see all Content Items related with "Listable" Content Types.

- [ ] Listable — Determines if an instance of this content type can be listed through the UI.

**Comment by chinasqzl** [comment]
不是，一般角色，此角色，拥有ListContent权限，
A内容，我希望他可见所有内容。
B内容，此角色，只可见自己创建的。

如B内容，不可列出，则自己的也看不到了。

**Comment by Skrypt** [comment]
Ok so repro would be to create 2 new Roles.
Role A = Can see all content
Role B = Can see only it's content

And you say that if Content Type cannot be "Listed" then you cannot see your "Owned" content items of this Content Type.
This is normal. We don't list Content Items that are not "Listable". You simply need to allow Listing the Content Type related to the Content Item.

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/96329099-6287fb00-107c-11eb-8fe7-847294a016d5.png)
![image](https://user-images.githubusercontent.com/16968103/96329140-b2ff5880-107c-11eb-825d-0e5b7e0433a4.png)

**Comment by chinasqzl** [comment]
A内容项，看到所有用户创建的。
B内容项，只显示我创建的。

**Comment by Skrypt** [comment]
Ah I see you mean. When you list specific Content Items of a specific Content Type.
I will try.

**Comment by chinasqzl** [comment]
非常感谢您的耐心。

**Comment by Skrypt** [comment]
No problem. 

I think I understand. What you want is to be able to add the ListContent permission on each Content Type to decide which one you want to display all content or only owned content.

**Comment by Skrypt** [comment]
I like the idea. I'm reopening this issue as a reference.
