### ISSUE TITLE
Admin UI : Flowpart elements permissions not applied

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#7293]
If a user doesn't have the permission to edit a Container, Raw HTML ... he should not be able to in a FlowPart.

/cc @ns8482e

**Comment by ns8482e** [comment]
I guess the permission applicable on creatable ContentItem.  Here for FlowPart creatable parent ContenItem - `Page`.  

Widgets that can be included in FlowPart is controlled by   `ContainedContentTypeDefinitions `

**Comment by deanmarcussen** [comment]
We should evaluate whether permissions would be a helpful thing to apply to contained items.

Normally permission checks are done on the primary content item.

My concern is twofold
- over complicating the flow / bag / taxonomy / menu parts
- having permission checks would make editing / rendering more complicated.

Say for example you remove the edit permission from a Raw HTML for some set of users.
- Create a Page with the Raw HTML as administrator
- Except the restricted users to be able to edit it.
- Presumably it wouldn't then render the Raw HTML Widget in the Edit view
- The Raw HTML Widget would no longer be in the DOM
- It would then be removed on save.

How about describing a use case @Skrypt because this is a pretty complicated thing to implement properly.

**Comment by Skrypt** [comment]
Why do we have the permissions then?

**Comment by ns8482e** [comment]
@Skrypt @deanmarcussen  I believe these permission for widgets are applicable when they added in `Layers` as individual content item. When these widgets are added via `Layers` they are individual content item and not a `Contained` content item within parent like in `FlowPart` in Page.
