### ISSUE TITLE
Why NLog.config is set never to copy to output when it throws not found error? [OrchardCore.Cms.Web.csproj]

### ISSUE THREAD

**Issue by scriptmaster** [OrchardCMS/OrchardCore#7296]
### Error: "NLog.config not found"

Why this change was made?

`src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj`
```
<ItemGroup>
    <Content Update="NLog.config">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

I had to correct it to:
```
<ItemGroup>
    <Content Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

**Comment by jtkech** [comment]
Yes, it has been added through https://github.com/OrchardCMS/OrchardCore/pull/2115/files#diff-41f12f2b3a41962cad49aa00d93355d9e0da28694ab1b174b59c219854dfebed

But it is still outputed on publishing, and it is already there when you run your app just under your app project folder, normally we don't need to output it on building under the bin folder

Maybe you did a `dotnet run` from your `app/bin/{config}/netcoreapp3.1`, if so, you should do it from your app root folder

**Comment by scriptmaster** [comment]
Well, the best practice is to run it from: `bin/{config}/netcoreapp3.1/` for portability.  This is how I have deployed many production dotnet core applications in the past. So you should run do it from that folder. I can send in my PR if you like.

**Comment by jtkech** [comment]
At least not in our case where e.g. in dev mode the content root folder is the app folder, otherwise you will have to also output e.g. the `wwwroot` folder and the `Localization` folder that we need even if it only contains a `.placeholder` file

Then on publishing all is flattened

So i suggest to just remove this `ItemGroup`, just tried it has the same effect, `NLog.config` is outputed
