### ISSUE TITLE
default site culture

### ISSUE THREAD

**Issue by 4m-world** [OrchardCMS/OrchardCore#7338]
I'm working on a web site that supports Arabic and English languages and the clients want the Arabic to be the default culture for the visitors (anonymous not authenticated).

The web site theme depends on culture parameters to setup theme resources i.e. Arabic is an RTL language therefore it loads RTL related assets. 

From the admin setting the default, culture is Arabic however when none authenticated users enter the website it goes to the English version of the web site.

It worth to mention despite that default culture is set "AR" the returned culture information is "EN"

**Comment by Skrypt** [comment]
It's a known issue keep it open.

**Comment by sebastienros** [comment]
Do you know that if the anonymous users have defined their preferred language as English first, then since EN is supported on your site this is what will be used, instead of the "default" culture which is AR on your site?

That's a good default, but that might not be what you want, if you prefer to force the site to return AR then you would need to remove the browser request culture provider (by code).

**Comment by Skrypt** [comment]
The exact name is : AcceptLanguageHeaderRequestCultureProvider
You will want to simply remove this CultureProvider.

https://stackoverflow.com/questions/40569863/disable-default-use-of-accept-language-header-in-asp-net-core
