### ISSUE TITLE
LinkMenuItem text field cannot be saved

### ISSUE THREAD

**Issue by OrchardSkills** [OrchardCMS/OrchardCore#7355]
Added new Text Field "IconClass" to LinkMenuItem but editing the text in field it can not be saved even after publishing the changes.

using Orchard Core Package
<PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc2-14969" />

**Comment by agriffard** [comment]
Tested: It is working with the source code but not with the OC rc2 nuget packages or the latest dev packages.

**Comment by hishamco** [comment]
How it working with the source code but not with the latest dev?!! Which branch you are it's working with, so perhaps a regression bug

**Comment by agriffard** [comment]
Tested with rc2 packages from nuget and dev from cloudsmith.
Can be reproduced on try.orchardproject.net

**Comment by jtkech** [comment]
@agriffard @hishamco I can repro even with the last dev source.

But only when editing an existing link menu item

If i create a new one it works

@OrchardSkills to update an existing one, a workaround is to add a text field on the `LinkMenuItemPart` instead of adding a text field to the `LinkMenuItem` content type, in that case it works

Seems to be is due to how menu item are edited / updated from their parent menu, they are not retrieved as individual items from the store but from their parent that rebuilt them but without taking into account type definition changes.

Okay, just tried a fix that works, i will do a PR tomorrow.

**Comment by OrchardSkills** [comment]
Awesome thanks @jtkech. Looking forward to your pull request.
