### ISSUE TITLE
RSD endpoint returns 'Page not found'

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#737]
If you enable the RemotePublishing feature, this meta is added:
`<link href="http://localhost:2918/xmlrpc/metaweblog/4sycaf2c49s4kxdmm421jda0cs/rsd" rel="EditURI" title="RSD" type="application/rsd&#x2B;xml" />`

but the url returns a 'Page not found'. 

I don't understand why the request doesn't enter in the Rsd method of the RemotePublishingController in Orchard.Lists because in the startup.cs, there is this map routing instruction:
```
routes.MapAreaRoute(
                name: "RSD",
                areaName: "Orchard.Lists",
                template: "xmlrpc/metaweblog/{contentItemId}/rsd",
                defaults: new { controller = "RemotePublishing", action = "Rsd" }
            );
```

**Comment by sebastienros** [comment]
This controller is assigned to the Orchard.RemotePublishing feature, which is defined by another module.
This is not wrong (new feature in OC) but might have been broken at some point when we played with ShellFeatureApplicationPart.

This controller should be registered if the Orchard.RemotePublishing is enabled.

/cc @jtkech

**Comment by jtkech** [comment]
Here my findings.

- So, without `[Feature("Orchard.RemotePublishing")]` it works, otherwise it doesn't work.

- In `ModularApplicationModelProvider.OnProvidersExecuted()` there is this line.

      var controllerType = controller.ControllerType.AsType();
      var blueprint = _provider.GetFeatureForDependency(controllerType);
      if (blueprint != null)
      {
        controller.RouteValues.Add("area", blueprint.Extension.Id);

    Here i can see that the area we add for `RemotePublishingController` is `Orchard.XmlRpc`. This is not `Orchard.Lists`, this is the id of the extension to which the feature belongs.

- I tried to use this area name when we define the route, but it doesn't work.

- But, just for testing, if in the above code i use this.

        var id = controllerType.GetTypeInfo().Assembly.GetName().Name;
        controller.RouteValues.Add("area", id);

    Then it works.

So, it seems that for a controller type, the area need to be related to the module in which it is defined. In O1, i couldn't find a module which defines a controller type with a feature attribute, this for a feature which doesn't belong to this module. Ok for other types, but not for controller types.

**Comment by jtkech** [comment]
So, i could get it working just by doing the 2 following changes.

- By using `areaName: "Orchard.XmlRpc"` for the map routing in `Orchard.Lists` startup.

- But also by using `area = "Orchard.XmlRpc"` to register the link in `ListPart.RemotePublishing.cshtml`.

Best

**Comment by sebastienros** [comment]
For now that will do. This is a new feature with some very advanced scenario, I am ok with it.
Thanks @jtkech.
