### ISSUE TITLE
Display Driver now depends on the handler

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7377]
Relating to pr https://github.com/OrchardCMS/OrchardCore/pull/6195

comment from @sebastienros 
> Can it be an issue that the Display Driver now depends on the handler?

The comment is correct, the `Validating` code added to the `ContentItemDisplayManager` should be moved to the `ContentItemDisplayCoordinator` as it currently creates an unwanted dependency between the display manager and drivers.

/cc @MichaelPetrinolis

**Comment by sebastienros** [comment]
@MichaelPetrinolis it's less risky to keep the duplicated code as before. They might trick you into thinking this should be the same reused Validate method, but they are not. Some components might be able to use the same logic, but it's not true for everything, so trying to reuse it by design is wrong IMO.

**Comment by MichaelPetrinolis** [comment]
@sebastienros I see your point. Do you prefer bringing the validation code as it was before, duplicate, or introduce an extension method and call it explicitly from Handler and Driver (for alias and autoroute)?

**Comment by MichaelPetrinolis** [comment]
@sebastienros @deanmarcussen I made some changes in the PR trying to have a common validation logic in one place for AliasPart and AutoroutePart. Pls tell me if you prefer to leave the code as it was before.
