### ISSUE TITLE
Should Search be a separate feature?

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#7501]
When I enable Lucene it unexpectedly assumes I am planning to offer search functionality on the website, which may never be the case. It registers a "/search" route, adds some search specific admin menu options, and displays the following message when I navigate to the "/search" route:

"Search is not configured."

In O1 the **Search** and **Admin Content Search** features are separate from Lucene, because Lucene queries can be used without offering search.

And, if you do offer search functionality on the website but later wish to disable it (even temporarily), it doesn't appear that you can unless you disable Lucene, which may still be used to run queries that have nothing to do with search.

**Comment by jptissot** [comment]
I agree. Let's make it a separate feature.

**Comment by jagbarcelo** [comment]
The route should also be configurable so that multilanguage sites could customise it. Instead of a fixed `/search` page, maybe (depending on the configurations of each site) it would rather make sense to have `/en/search`, `/fr/chercher` and `/es/buscar`

**Comment by Skrypt** [comment]
I agree on the proposition. I believe the search form was added even before we added the culture options on the Lucene indexes. I suggest we create an entire module for Lucene so that it can be extended easily by anyone using abstractions.

**Comment by scleaver** [comment]
Most sites I have worked on the site-wide search box is within the header and the results are on a specific page (clients have varying preferences for URL but really it doesn't matter). 

Occasionally, a specific content type like news or blog will also have it's own content type specific search where it's important that the results are presented within the same page layout as the news or blog section itself... I know all this can be achieved with customisation via shapes etc but is this relatively easy with the current configuration? Should these types of senarios be taken into consideration with the proposed changes above?

**Comment by Skrypt** [comment]
I think we are defining a different Search scope here. The current search form is a simple global search form to use with a single indexed column in Lucene. Of course, this is a simple example and it is way too simple for most common use cases. I think, we should be able to disable it because this is a feature that should be designed differently, maybe in the form of a Lucene Search form builder, I think we can elaborate a lot of other ideas around this. In the end, the search feature is based around it's Queries (Lucene or not). I think, for now, since it's not a priority we should either show more examples/documentations on how to design a custom search and allow to disable the current search feature.

I for myself built something custom around Lucene Queries for my website and I can't really share it but eventually, if I get time I'll work on something more orchardy.

**Comment by Piedone** [comment]
As of 1.5, we have a separate Search and Indexing module, as well as modules for the Lucene and Elasticsearch implementation.
