### ISSUE TITLE
"{{something}} are not working" is replaced to "{something} are not working"

### ISSUE THREAD

**Issue by arunendapally** [OrchardCMS/OrchardCore#7520]
I have an issue when calling the below method, "{{" are getting replaced with "{" when I passed parameters
count = 2
singular = "{{something}} is not working"
plural = "{{something}} are not working"
localizer.Plural((int)count, this._message, this._pluralMessage).Value << this returns "{something} are not working" but i am expecting "{{something}} are not working" as I have a regex match and replace in place, I need "{{" and "}}"

https://github.com/OrchardCMS/OrchardCore/blob/84ac3aabbe48bef6bbc942be4e458b2c2a53cb0e/src/OrchardCore/OrchardCore.Localization.Abstractions/Extensions/StringLocalizerExtensions.cs#L19

**Comment by netwavebe** [comment]
It does a string.Format() to be able to write `localizer.Plural(count, "ball", "{0} balls", count)` here:

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Localization.Core/PortableObject/PortableObjectStringLocalizer.cs#L61

Your passing in double braces, used to prevent unwanting formatting so `String.Format("public {0} {1} {{ get; private set; }}"` becomes `public Int32 MyProperty { get; private set; }`

So what you see is by design I'm afraid.

**Comment by sebastienros** [comment]
You might need 4 braces to escape the two of them. But we need to investigate if this should be taken as a bug or by design. Maybe filing an issue in aspnet too, I'll follow up.

**Comment by netwavebe** [comment]
@sebastienros https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting?redirectedfrom=MSDN#escaping-braces

**Comment by sebastienros** [comment]
I just verified and you need to use 4 braces to render 2.
