### ISSUE TITLE
Is placement possible in the User editor?

### ISSUE THREAD

**Issue by craftyweb** [OrchardCMS/OrchardCore#7526]
Hi,

I made a CustomerModel to attach to the User entity. I was wondering if it is possible to place the editor of this model in separated tabs like you can do with fields and parts in placement.

Now it’s just showing below the default fields of the User.

![AC3F8EB6-1514-4415-AB6C-B6EED8FEC52D](https://user-images.githubusercontent.com/61787638/98290439-f7aa4f80-1fa9-11eb-94c8-6da33e7708b0.jpeg)

Thanks!

**Comment by deanmarcussen** [comment]
I don't see why not. Have you tried it?

**Comment by craftyweb** [comment]
> I don't see why not. Have you tried it?

@deanmarcussen 
Yes I've tried it by placing the name of the shape defined in the driver:

Customer_Edit

And place this in placement.json like 

"Customer_Edit": [
    {
      "place": "#Customer:0"
    }
  ]

I think there is something wrong with the way I want it to place in placement.json so I was wondering if you guys could help me with the right solution (if it is possible).

**Comment by deanmarcussen** [comment]
For placement to work there you need a `Match`. Just specifying `place` is not enough.

But we don't have any differentiators by default on `User` shapes, or anything to `Match` on.

Plus, I was working on something yesterday, and realised tabs don't quite work with users, because they don't have a `ContentItemId`

However, this pr fixes that https://github.com/OrchardCMS/OrchardCore/pull/7556
and if you look at the `CustomUserSettingsDisplayDriver` you'll see how I've specified the tab via the `Location` property.

```
 .Location($"Content:10#{contentTypeDefinition.DisplayName}")`
```

So when that is merged, tabs will work, and I would suggest using `.Location` as you have written a driver.

**Comment by craftyweb** [comment]
@deanmarcussen Thanks! this works very well. Closing this now.
