### ISSUE TITLE
Block search indexing with 'noindex'

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#7529]
I've just titled this issue the same as [this ](https://support.google.com/webmasters/answer/93710?hl=en) Google's page.

Some pages in our site (and I suppose any other site too) should be prevented from being included in search engine indexes.
For instance, the [thank-you page](https://docs.orchardcore.net/en/dev/docs/reference/modules/Forms/#adding-a-thank-you-page) after the form submission (in OrchardCore documentation) should:
 
- [ ] Not be Included in the **sitemap.xml** file nor be indexed at all by any search engine, and
- [ ] It shouldn't even be allowed to be directly navigated to in order to acurately calculate the right figures for hits/events/conversions etc.

In order to exclude these pages from the sitemap file, I suppose we could create them based on a new NoIndexPage content type and generate the sitemap just excluding it. For this particular content type we could also create a template mimicking the original site template, and just include `<meta name="robots" content="noindex">` in the header tag.

Has someone done this before? Can anyone think about how doing it in any other way (easier)?

And what about the second point? Can those pages be made unaccessible unless they are called with a particular referrer header or in any other way?

**Comment by deanmarcussen** [comment]
You pretty much have all the options covered

You could also exclude those pages with a `robots.txt` - I tend to work with that rather than having a `meta` tag, but equally I have a robots meta tag field, so it can be done either way - it's just a field, and the field template has a meta tag helper. i.e. `<meta asp-name="robots"` etc

My preference is to exclude them from the sitemap in the first place.
Which you can do, either by 
- having a different content type, 
- adding the `SitemapPart` and setting to exclude
- a content handler, which overrides the aspect (that I added / refactored last week for your other issue) excludes it

See this issue https://github.com/OrchardCMS/OrchardCore/issues/3848 for the question of routing to pages that shouldn't be routable.

**Comment by jagbarcelo** [comment]
Just a warning about excluding those pages via robots.txt (picked from Google's article cited above):
![image](https://user-images.githubusercontent.com/6704109/98365447-bca02e80-2032-11eb-814e-065553450b39.png)

Thanks for your comments. I'll have a look at that issue about non-routable pages.

**Comment by sebastienros** [comment]
Since the setting is already there in the part, I assume this issue can be closed.
