### ISSUE TITLE
ContentItems not being indexed - problem with ShellScope.AddDeferredTask?

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#7557]
Here's my scenario

1. Early on in my recipe I enable OrchardCore.Lucene and OrchardCore.Indexing in a "feature" step
2. Then my recipe configures LuceneSettings
3. Then in my recipe I have a "lucene-index" step to configure my index
4. At the last point in my recipe, I have a separate "feature" step to enable my own modules

I did this because my own modules will create content items in their migrations, and by doing things in this order I was ensuring that Lucene was fully configured first so that my content items would get indexed.

This was working before, but at some point recently, it seems like my content items stopped being indexed when I run the recipe from scratch. I'm not entirely sure what is going on, but I did some investigation and this is what I found so far:

`IndexingTaskManager.CreateTaskAsync` _is_ being called for my content items, and new `IndexingTask`s are being put into the queue. The first time in, `ShellScope.AddDeferredTask` is called, passing in a lambda that calls `IndexingTask.FlushAsync`. However, my breakpoint in `IndexingTask.FlushAsync` is never hit. Sure enough, when I look at the IndexingTask table in the DB, the records that were in the queue aren't there. It appears as though they are never being flushed.

I had been running 1.0.0-rc2-14774. I updated to 1.0.0-rc2-15409 to see if that would resolve the problem, but it did not.

**Comment by jtkech** [comment]
@rjpowers10 

> I did this because my own modules will create content items in their **migrations**

Yes, there are some related issues in the sense that there are all using custom **migrations** recipes e.g. #7449, #7558. For some good reasons (e.g. database issues), normally when executing a recipe, each recipe step is executed in its own scope, which is not the case of a **migration** recipe. Originaly, migrations and then migrations recipes were intended to only update the type definition table, but yes it is useful to automatically do other things when enableing a feature.

So i understand your issue, migrations steps are executed when a tenant is activated but not in their own scope, there are all executed in a lighter scope that does not execute deferred tasks, that's why your items are not indexed. And yes, for other good reasons, lucene indexing is now done in deferred tasks, and as said in your case there are not executed.

So, i will work on a more global solution related to the scopes of migraion recipes.

**Comment by rjpowers10** [comment]
@jtkech What you're saying is consistent with what I'm seeing. If I create a content item within a normal recipe (not a migration) then it gets indexed as I expect. It's only the content items created in a migration recipe that have the issue.

Thanks for looking into this. It's not critical for us because we can just force the item to be indexed by publishing it again.

**Comment by jtkech** [comment]
@rjpowers10 

Okay, i think i know how to fix it, i will do a PR tomorrow
