### ISSUE TITLE
Media should have server-side pagination

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#7559]
Related to #5001
When entering a folder, all files or sub-folders are requested and then paginated on the client-side.

Maybe this is the norm in CMSs, but it will lead to issues like the one referenced. I haven't tested, but I guess it would crash when there are many files as well.

@deanmarcussen you mentioned it is possible to add pagination to media and blob storage, can you share that research? (https://github.com/OrchardCMS/OrchardCore/issues/5001#issuecomment-569034752)
(I couldn't find a direct way via the FileSystem apis - maybe could be done by applying a prefix and using a searchPattern?)

Another issue is if we rename a media file or folder, the paths are not updated.

I understand (as mentioned here https://github.com/OrchardCMS/OrchardCore/issues/3404#issuecomment-477741293) the current solution avoids extra queries to the database, as we have the direct filepaths.

But what if we store a FilePath AND a MediaId?
The media Id would refer to a Media Content Type or somthing of sorts.
The filepath would be duplicated in the mediapicker and the "media content type".

This would:
- Keep media access fast, since we still have the media path, no extra DB query is needed
- Allow scalable pagination - as we would query the "media content type"
- Allow extra media metadata - by extending the "media content type"
- Allow renaming files without breaking - by keeping the media references and updating the filepaths

I'd like to hear your thoughts as I'm about to implement something related to the media in my project, and this could change my approach.

**Comment by sebastienros** [comment]
The files are already paginated on the server IFAIR. @matiasmolleja can you confirm?

**Comment by mariojsnunes** [comment]
> The files are already paginated on the server IFAIR. @matiasmolleja can you confirm?

I don't think so, as seen here:
https://github.com/OrchardCMS/OrchardCore/blob/8a2fa21102f62e478680daacf504d0e6ac7e0929/src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs#L105

**Comment by deanmarcussen** [comment]
Regarding #5001 

- never repro'd 
- 5000 folders of one root folder is something I would suggest should be split into more sub folders.

Before looking at it in detail I'd prefer to see a repro, i.e. rather than thinking there might be an issue, if you want to get a zip file of folder/file arrangements to prove it is a problem, that would be helpful.

**Comment by deanmarcussen** [comment]
`GetDirectoryContentAsync` btw takes a parameter if you want to get subfolders.

we don't use it here in the admin controller.

**Comment by mariojsnunes** [comment]
So I've run the following experiment:
- Clean install with the Blog Recipe on my localmachine
- Duplicate the images a bunch of times on the media folder (~6k images)
GetMediaItems request took 600ms
content-length: 2019079

- Duplicate the images again (~12k images)
GetMediaItems request took 1200ms
content-length: 4177567

On the browser devtools, you can see the request payload on the network tab:
![image](https://user-images.githubusercontent.com/8073622/99090737-e45d3c80-25c6-11eb-8254-8d0e1015eab7.png)
The pagination is then handled by the Vue component and there are no extra requests.

It did not crash. But as you can see, it won't scale.

I understand the workaround is to not store all images on the same folder, but would be nice if this was handled by orchard in some way.
For example, on a SaaS product, if there are 20k users in one tenant, and each of them have a profile image, A simple "profile-photos" wouldn't be enough, would need to implement custom logic to create sub-folders for each X users.
I also know that this would only happen while browsing the specific folder, and that might be rare, but I'm afraid of the worst case scenario.

Anyway, there should at least be a documented recommendation about dealing with this.

Thoughts?

**Comment by deanmarcussen** [comment]
No crash ? Great 👍 

> I understand the workaround is to not store all images on the same folder, but would be nice if this was handled by orchard in some way.

So same workaround you have to do in windows explorer to stop it crashing when you put too many files in one folder? 

The difficulty with pagination is there are many underlying operating system limitations.

I don't know how you'd handle it with a file system, or if it is even possible.

Now blob storage is a different scenario again, because it's not file system based.

We get an `IAsyncEnumerable` back, which potentially we could page, but then we're getting into implementation specific details, and it would force other implementations, like the file system implementation, to fake support it.

But because we're not getting a result from a file system, all we're talking about (potential issue wise) is the size of the http payload returned.

Currently we page the `IAsyncEnumerable` into an `IEnumerable`, so we could consider changing that implementation detail, but not sure there is much advantage, because an asp.net core controller will still turn the `IAsyncEnumerable` into a list of results, because streaming an `IAsyncEnumerable` result isn't supported.

A gprc implementation might be interesting... 

Personally I make use of both the Media Library and Azure Storage Explorer, and I think that's a reasonable thing for users to do when handling large quantities of files.

> For example, on a SaaS product, if there are 20k users in one tenant, and each of them has a profile image, A simple "profile-photos" folder wouldn't be enough, would need to implement custom logic to create sub-folders for each X users.

The attached media field might be more useful for you here? 
As you'll get that fake directory structure oob

**Note** I'm not trying to block you working on this if you feel strongly about it @mariojsnunes I'm just aware of some limitations, and I'm not yet convinced it's a problem to be solved.

**Comment by mariojsnunes** [comment]
Thanks for this, yeah, I also use Azure Storage.
I realise now with Azure Storage it won't affect the site performance as it doesn't read the filesystem, and there are separate blob containers for each tenant.
Now I think this is less of a problem than I thought originally. Being aware of the limitations should just be enough.

Another problem I found is that when renaming/moving media, the media pickers using that image are not updated.
I'll open another issue for this.

Should i close this one?

**Comment by deanmarcussen** [comment]
A useful discussion, glad we have come to a conclusion.

> because an asp.net core controller will still turn the IAsyncEnumerable into a list of results, because streaming an IAsyncEnumerable result isn't supported.

> A gprc implementation might be interesting... and fun to do!

Let's keep it open. I think the outcome is that it's worth changing the interfaces to support `IAsyncEnumerable`, now that at least one implementation has support for it.

Not so much for the possibility of a GPRC implementation, but it could be better in terms of threading.

And easier to do now, than later.
