### ISSUE TITLE
Creating a ContentType with migration doesn't apply all properties

### ISSUE THREAD

**Issue by juchom** [OrchardCMS/OrchardCore#7569]
I created a simple ContentType from the admin menu called Customer, I added a TextField and a MediaField.

The type is defined like this.

```
public Task<int> UpdateFrom3Async()
{
    _contentDefinitionManager.AlterTypeDefinition("Customer", type => type
        .DisplayedAs("Customer")
        .Creatable()
        .Listable()
        .Draftable()
        .Versionable()
        .Securable()
        .WithSettings(new FullTextAspectSettings
        {
            IncludeBodyAspect = false,
            IncludeDisplayText = false,
        })
        .WithPart("Customer", part => part
            .WithPosition("0")
        )
    );

    _contentDefinitionManager.AlterPartDefinition("Customer", part => part
        .WithField("Name", field => field
                .OfType("TextField")
                .WithDisplayName("Name")
                .WithPosition("0")
            )
        .WithField("Logo", field => field
                .OfType("MediaField")
                .WithDisplayName("Logo")
                .WithPosition("1")
        )
    );

    return Task.FromResult(4);
}
```

An incremental migration works fine, but starting from scratch, the type is created but this part of the code is ignored, leaving this options unchecked:

```
        .Creatable()
        .Listable()
        .Draftable()
        .Versionable()
        .Securable()
```

**Comment by jtkech** [comment]
Can you show us your `Create() / CreateAsync()` method and other `UpdateFromXAsync()`, from scratch normally this is the create method that does all you need and then return 4 to skip other migration steps

**Comment by juchom** [comment]
I made a repo here with all the files: https://github.com/juchom/OCRepro/

The issue is only happening in this particular case, if I change the company name used for namespaces it works well...

**Comment by jtkech** [comment]
Usually, in `CreateAsync()` we do all what is needed and return in your case 4 to skip all others migration steps.

> if I change the company name used for namespaces it works well

Yes, in the Document table there is a data migration record with the migrations types, including their namespaces, and their versions, see below, so yes, changing the namespace will triger again the migration from the beginning

    {"DataMigrationClass":"OrchardCore.Markdown.Migrations","Version":4},

> but starting from scratch

What do you mean here? I thought about a fresh setup, but in your case its like your type definition and the migration record already exist, and including a version for your migration, preventing a step, that you may have updated, to run.

Note: With the blog recipe, the content definitions are by default in a file under the tenant folder, this because in the blog recipe we enable the `FileContentDefinition` feature, otherwise it would be in the database.

**Comment by juchom** [comment]
Actually if you clone the repo and hit F5, do the setup process, are you able to create a Customer content?

**Comment by jtkech** [comment]
Didn't try it yet, i will do it this night and will let you know ;)

**Comment by juchom** [comment]
Ok thanks a lot, this is very nice

**Comment by jtkech** [comment]
@juchom

Okay just tried it, just needed to add a missing dependency, **then it was working**.

**Your module manifest needs a dependency on `OrchardCore.ContentTypes` so that the right features odering is computed**, even if you enable it through your main setup recipe, it's important e.g. for the order of services registrations (but not only, e.g. also for shape precedences), e.g. if a module A depends on a module B, module B registers its services (through its startup) before module A. **And the execution order of migrations also depends on features ordering**.

Also, when enabling module A, module B is automatically enabled as it is a dependency, so no need to also specify module B in the recipe, but may be better to keep it for clarity. Then wen disabling module A, module B is not disabled because it doesn't depend on module A. But if you disable module B, module A is automatically disabled as it is a dependent.

In your main recipe you don't need the following in your feature section, **as they are always active features**

        "Application.Default",
        "LinoaWebsite.Backend", // <= the main app

Maybe you don't need `IsAlwaysEnabled` in your module manifest, here this option is not the same, it prevents a feature (a module may have multiple features or only a main one) from being disabled through the admin, but this feature still need to be 1rst enabled by a recipe or through the admin.

**Comment by juchom** [comment]
Thanks a lot @jtkech !

I understand a bit more how the startup process work (even if I will have to read your comment again to be very clear).
