### ISSUE TITLE
How to handle the owner id with recipemigrations

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7603]
Pulled over from the discussion here https://github.com/OrchardCMS/OrchardCore/discussions/7575#discussioncomment-127219

There's a couple of scenarios we may need to take into account with the `UserId` / `Owner`

During a setup recipe, the `AdminUserId` is available as a js property.

However people are also trying to use `RecipeMigrator` to setup content this is fine, but it potentially leaves the content without an owner.

In this case there is no context object provided, so the  `"Owner": "[js: parameters('AdminUserId')]"` is not available.

Also migrations are run during site startup so there is no `HttpContext` from which to get the current user.

However we do have the `ISite.SuperUser` property available, which could be used to pass to the context, always providing at least an `[js: parameters('AdminUserId')]` which would make sense for content being imported during a migration.

The other scenario is with deployment plans, and how the owner id an be maintained when deploying through sites.

This does also open up a conversation about migrating users between sites - which maybe better covered when I get that secrets/encryption module finished off.

**Comment by Skrypt** [comment]
Question is also if we should have a "system" user account for migrating things like Workflows which can also end up most of the time not having any "Owner" assigned to. Globally, a content item should never end up having a "null" Owner else it becomes an orphan and it's more complex to reassign those to a specific Owner from UI afterward. Of course there will always be exceptions so we do not enforce the database Owner to never be null but at least we could assign them a special user account so that we can evaluate permissions on them.

**Comment by sebastienros** [comment]
We need to use SuperUser  in this case

**Comment by agriffard** [comment]
I'd like to remind a feature that would be really useful:
Allow to declare parameters from a the setup (like ARM templates) and use them in the recipe.

See also #3966 to use the culture and #495 for a Setup Wizard.

**Comment by deanmarcussen** [comment]
@jtkech might have to reach out for some ideas on this.

It is trivial to retrieve the SuperUser in the `IRecipeMigrator` but it is more complicated to do so during a setup process, as it is the values for the Site set until after the recipes have run.

Ideally this information would be useful to provide to the `IRecipeMigrator` during both setup and normal ongoing migrations, as from users reports, they are using data migrations to create content items, which will then run during setup.

I had thought it might be possible to use the `ShellScope.Items` for this, and set a value in the setup service, that could later be caught in the `IRecipeMigrator`.

But there are so many scopes created during recipes, and `AutomaticDataMigrations` run on their own scope during activation that I haven't quite been able to get it wired up.

I wondered if it was possible to go up the current scope to find an items dictionary of the parent/parent, but not really sure that's a great idea, or even possible.

Do you have any thoughts?

**Comment by jtkech** [comment]
> @jtkech might have to reach out for some ideas on this.

Yes, we have shell scope items / features but can't be accessed by a child from its parent, but here the parent of all these scopes is the current request scope, so here we could use some request items / features.

Yes, the recipe migrator passes an empty object to the recipe executor, maybe we would need to pass an object to the recipe migrator, or it could build this object itself and then pass it to the recipe executor.

With the last option, we could use a request feature to hold the setup context, so that the migrator could retrieve it during a setup, if it doesn't exist it could use the current site settings (that is a cached document) to build this object.

**Comment by deanmarcussen** [comment]
> we could use a request feature to hold the setup context

ok, so what you mean is `httpcontext` is the same across these? even during shell activation, i.e. modular tenant events?

I will try, I didn't, I was just trying to see if I could get it working with the shell scope items.

**Comment by jtkech** [comment]
Yes,the httpContext should be the same, but try it as i'm never sure at 100% ;)

Note: We make its RequestServices tenant aware but all other properties are not affected

It's an async local value so potentially a property set by a child scope may not be seen by its parent, but as i remember it's not a deep copy on write so the referenced Items collection and then the Features (also based on Items) are the same, unless maybe if a child scope set the Items to reference another collection (not just add / remove items on the curent one).
