### ISSUE TITLE
Upgrading from Orchard V. 1.9.2 to Orchard Core

### ISSUE THREAD

**Issue by mahyarmot** [OrchardCMS/OrchardCore#7656]
Hi, we do have a running website on Orchard v. 1.9.2 and we are not trying to consider if we can upgrade it or not. According to the project docs, roadmaps and issues, I couldn't find responses to my questions below:

1- Is it possible to upgrade the site to the latest Core version?
2- Will Orchard CMS continue and other new versions be released?

Thanks

**Comment by Flarescape** [comment]
For question 1:
No! There is no simple way to upgrade a O1 to a OC website.
It's because the modules wouldn't work anymore simply because of .NET Core and a completely different architecture of OC Modules itself.
Further the complete DB changed and the Layout Editor is no longer existing in the way O1 has it.

For question 2:
I don't know the exact developement plans for O1 but i guess that there is still a big community around it to support it in the future.
There are already much newer versions than 1.9.2, so maybe it would be better to upgrade to this versions instead if it's not possible for you to create the homepage from scratch again with OC.

**Comment by mahyarmot** [comment]
Many thanks, @Flarescape. Marked as Closed.
