### ISSUE TITLE
does not implement interface member 'IOpenIddictApplicationManager.CreateAsync(OpenIddictApplicationDescriptor, CancellationToken)'

### ISSUE THREAD

**Issue by SharadKamate** [OrchardCMS/OrchardCore#7751]
This same issue we are facing for multiple interfaces.

**Comment by deanmarcussen** [comment]
You will need to upgrade your build SDK to .Net 5.

We are still build an ASP.NET Core 3 runtime, but due to a bug in the v3 SDK the build SDK had to be bumped to 5.

Depending on whether you are using dotnet build or Visual Studio 2019, you will either need to just update the SDK to 5, or update Visual Studio to the latest.
