### ISSUE TITLE
Localization do not get copied if using net5.0

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7783]
I switched our solution to net5.0 and the Orchard's tranlations files are no longer being copied on build. I traced the code and think this might be related to this line: 

https://github.com/OrchardCMS/OrchardCore/blob/569e256b1aeb86c3321c5233562cea19ee94be9c/src%2FOrchardCore%2FOrchardCore.Application.Cms.Core.Targets%2FOrchardCore.Application.Cms.Core.Targets.csproj#L10

Which still targets netcoreapp3.1 but our app targets net5.0

Is there any way to fix this ?

**Comment by jtkech** [comment]
@hishamco @jptissot 

Okay i think i know why and how to fix it, i will do this week end ;)

**Comment by jtkech** [comment]
@jptissot 

So i created and packed a little project `OrchardCore.Test.Targets` targeting `netcoreapp3.1` and using the same kind of `PackagePath` pointing to simple `.props` and `.targets` files, just to show a message to check if there are executed

    <ItemGroup>
      <None Include="OrchardCore.Test.Targets.props" Pack="true">
        <PackagePath>build\$(TargetFramework)\OrchardCore.Test.Targets.props</PackagePath>
      </None>
      <None Include="OrchardCore.Test.Targets.targets" Pack="true">
        <PackagePath>build\$(TargetFramework)\OrchardCore.Test.Targets.targets</PackagePath>
      </None>
    </ItemGroup>

In our `OC.Cms.Web` i referenced this testing package and on building i can see that the testing script is executed

Then, in `OC.Cms.Web` i tried `<TargetFramework>net5.0`, the testing script is still executed

Then i tried a multi targeting `<TargetFrameworks>$(AspNetCoreTargetFramework);net5.0`, notice that i used TargetFrameworks with a `s`. The script is still executed, here it is executed twice but that's okay for translations as we `SkipUnchangedFiles`, otherwise we would need to use a `buildMultiTargeting` folder in the package so that it is executed once for all TFMs. Not sure that for now we want to support `buildMultiTargeting` for `OC.Application.Cms.Core.Targets`.

That said, as i have tried it works, so i would need more info on what you are doing, are you using `TargetFramework` or `TargetFrameworks` and where?

**Comment by jptissot** [comment]
@jtkech Thank you for looking into it. Repository is [here](https://github.com/StatCan/StatCan.OrchardCore) if you want to try it. It was not installing the localization files on build for me.

**Comment by jtkech** [comment]
@jptissot it works if you reference translation packages, e.g. the `OC.Translations.All` one ;)

    <ItemGroup>
      <PackageReference Include="OrchardCore.Translations.All" Version="1.0.0-rc2-108003" />
    </ItemGroup>

It is referenced by `OC.Application.Cms.Targets` but not by `OC.Application.Cms.Core.Targets`, so you have to reference it yourself, in you main application, it also works if referenced transitively through a sub project / package, the translation packages enlist their po files on building through their msbuild props file that is under a `buildTransitive` folder.

**Comment by jptissot** [comment]
Makes sense. I thought the translations were included in all targets. I will add this package
