### ISSUE TITLE
Add GitHub action to deploy OrchardCore to Azure App Service

### ISSUE THREAD

**Issue by aaronamm** [OrchardCMS/OrchardCore#7819]
Hello everyone

I think it would be nice if we can add GitHub action to deploy OrchardCore to Azure App Service automatically or add a document/guide of how to deploy the website with GitHub action.

This is starting from the issue that I open (https://github.com/OrchardCMS/OrchardCore/issues/7778).
I want to add Yarn Workspace to the project and want to to make sure it work if we deploy to App Service.

FYI, workspaces does not work with Kudu deployment because of file permission.
If you are interested in GitHub action, I have a PoC build script that work with Yarn Workspaces and ASP.NET Core MVC .NET.
https://raw.githubusercontent.com/codesanook/CoreMvcAppService/develop/.github/workflows/github-actions-app-service.yml

Please let me know the proper way to handle this `add build script to the repository` or `create a document`.
I am happy to create a PR for this.

Thanks.

**Comment by deanmarcussen** [comment]
This actually sounds like something that might suit a blog post best.

The focus could be on deploying Orchard Core through NuGet packages.

We are actively encouraging users to develop and deploy with the NuGet packages, rather than the source code directly.

The issues with adding a build script, or docs about it is that we are then supporting github actions, and being opinionated about what people should use and how they should use it. 

Many users, use Azure DevOps for example, rather than github actions, so then we would have to have one for DevOps as well, and then we become involved in answering issues about how to use github actions, or devops, when what we want to focus on is how to use Orchard Core.

**Comment by aaronamm** [comment]
@deanmarcussen Agree, but how about support add yarn workspaces.
This is because I want to add this to my personal Orchard project and want to contribute it back to the community.

**Comment by aaronamm** [comment]
FYI, I found this is interesting blog post that mention as below but I am not sure it is right.
`
from what was seen at Microsoft Build, many of the new features are going to GitHub Actions CICD — and not Azure DevOps.
`
From https://www.cbtnuggets.com/blog/certifications/microsoft/github-actions-vs-azure-devops-a-guide-to-microsofts-new-ci-cd-platform

**Comment by aaronamm** [comment]
@deanmarcussen Could you please give me more details about automated deploy to Azure App Service by Nuget package?
It can be sudo build steps or useful documents/articles.  I can help contribute on this.

FYI, here is PoC ( not include Yarn build yet)  for Azure Devops Pipelines by code. https://github.com/codesanook/CoreMvcAppService/blob/develop/azure-pipelines-app-service.yml

**Comment by aaronamm** [comment]
@deanmarcussen  I haven't noticed, we already have some GitHub actions work flows.
Here there are:
https://github.com/OrchardCMS/OrchardCore/tree/dev/.github/workflows

**Comment by deanmarcussen** [comment]
Yes @aaronamm we are using github actions.

Our github solution is quite different from a nuget version of Orchard Core, so has many different needs.

- We build nugets out, and docker containers, and a lot of things, that you are unlikely to need on an Orchard Core NuGet project.
- We also need to include all out build assets in the solution, so that contributors can use the solution, rather than building on a ci server. This is one of the reasons the gulp pipeline is made the way it is, and doesn't worry about yarn.
- It's also why the code we have in the solution may not always be relevant to working with a NuGet version.
- So we suggest guides, rather than code in the repository, with the idea to keep the code in the repository relevant to the repository, if that makes sense.

To answer your previous question, here are some common things that people struggle with setting up a CI pipeline for a NuGet Orchard Core.

The CI pipeline
- Including the preview package feed for cloudsmith in the CI pipeline
- after building using the Deploy as Zip feature to release, rather than Web Deploy

Afterwards
- managing data transfer with import/export after setting up the site
- managing app_secrets configuration

If you're doing a guide / blog post, I would suggest keeping it focused on one topic at a time :)

I think @OrchardSkills has done a number of videos related to this topic

**Comment by aaronamm** [comment]
@deanmarcussen Thank you so much for the answer in details.
It is very useful.

**Comment by Piedone** [comment]
Nothing else to do here.
