### ISSUE TITLE
Bug: Exporting a Deployment Plan that includes the Admin settings step produces wrong json

### ISSUE THREAD

**Issue by serverside-is** [OrchardCMS/OrchardCore#7852]
![image](https://user-images.githubusercontent.com/3681658/101177599-e81d3580-363f-11eb-9d1e-9a2b70fd9efc.png)

Adding the `Admin Settings` step and the `Deployment Plans`  to a `Deployment Plan`  (as in the above picture), and downloading the json file, produces something like this:

```
[...]
          "Steps": [
            {
              "Type": "SiteSettingsPropertyDeploymentStep`1",
              "Step": {
                "Id": "6582efaa9f7e4246a4722320fa19ee2c",
                "Name": "AdminSettings_SiteSettingsPropertyDeploymentStep"
              }
            },
[...]
```
When we import this package, we get:

```
InvalidOperationException: No changes have been made. The following types of deployment plans cannot be added: SiteSettingsPropertyDeploymentStep`1. Please ensure that the related features are enabled to add these types of deployment plans.
OrchardCore.Deployment.Recipes.DeploymentPlansRecipeStep.ExecuteAsync(RecipeExecutionContext context) in DeploymentPlansRecipeStep.cs, line 74
```
This seems to work just fine:

```
[...]
          "Steps": [
            {
              "Type": "AdminSettings_SiteSettingsPropertyDeploymentStep",
              "Step": {
                "Id": "6582efaa9f7e4246a4722320fa19ee2c",
                "Name": "AdminSettings_SiteSettingsPropertyDeploymentStep"
              }
            },
[...]
```

To produce the second result, I did this modification to DeploymentPlanDeploymentSource.cs (OrchardCore.Deployment module):

```
-- Type = step.GetType().Name,
++ Type = (step.GetType().GenericTypeArguments.Count() == 0)?step.GetType().Name:step.Name,
```

Although this is working for me, I'm not creating a PR because I'm not sure if this has other implications.

**Comment by deanmarcussen** [comment]
Yes, your code will probably work, but later implications...

What the `Source needs to do is a similar action to the `RecipeStep` 
https://github.com/OrchardCMS/OrchardCore/blob/dedf32dbb60573f1cf48addc0a94f126f42f3010/src/OrchardCore.Modules/OrchardCore.Deployment/Recipes/DeploymentPlansRecipeStep.cs#L53

where it will need to find the factory that matches the `Name` and asks the factory for it's type.

This happened because we introduced a generic type, and the `Source` was using a shortcut. But the factory is responsible for returning the type, so if it matches against that, then no more problems in the future.
