### ISSUE TITLE
Security issue: Managing Users permission

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#7915]
When defining role for user that can manage users (add/edit) it allows also to delete users with administrator role, or to change role of administrator user, even though managing roles / assign roles is not allowed.

1.0.0-rc2-15584

**Comment by hishamco** [comment]
This is already done by @Skrypt since month or two ago in the dev branch

**Comment by MikeKry** [comment]
@hishamco If it is in dev branch, then it should work on my version, I have updated nuggets yesterday.

**Comment by jtkech** [comment]
On nuget this is the master branch

The dev branch is on the cloudsmith feed

**Comment by deanmarcussen** [comment]
This wasn't fixed by @Skrypt recently. @Skrypt fixed another issue.

I opened an issue around this https://github.com/OrchardCMS/OrchardCore/issues/7619

The assign roles permission is currently unused / unchecked so rather useless right now.

The idea being that we need to 
- use the permission
- probably move it to the users module, rather than roles
- update the user role editing view to come from another driver, which can check those permissions

**Comment by hishamco** [comment]
> @hishamco If it is in dev branch, then it should work on my version, I have updated nuggets yesterday. (but it does not work)

Nope, please refer to @jtkech comment

@deanmarcussen I will have a look to the issues that you refer to

Thanks

**Comment by MikeKry** [comment]
@jtkech 

I am using nuget feed from cloudsmith :)

**Comment by jtkech** [comment]
Ah okay, sorry i thought you were using nuget from nuget ;)

**Comment by hishamco** [comment]
Sorry seems we thought you are using a NuGet feed ;)

I will have a look to the refered issue

**Comment by sebastienros** [comment]
Custom permissions (dynamic) to add/remove a specific role, implied by "Manage Roles". Only check for Manage Roles, and granted if the specific one is one of the allowed permissions.
