### ISSUE TITLE
Use InMemory Provider for Development

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#792]
After this commit https://github.com/sebastienros/yessql/commit/a4f0531f6630fb95b60b4a75707adeae5dc3b2cd Orchard can use `UseInMemory` database provider for demo / testing purpose, so i'm thinking about:

1. Use `UseInMemory` as default data provider in `Development` environment
2. Use `UseInMemory` is a good option for testing, so if there are tests that interact with disk, we can use InMemory database provider instead

/cc @sebastienros

**Comment by sebastienros** [comment]
I tried and it didn't work. Because during Setup we recreate the container as new features are added and lose the data. There might be a solution that involves taking snapshots and storing on the filesystem when the container is disposed, and reload everything in memory when the app is started.

Then for testing, why not if it can improve performance. Development, I am not sure that losing all data after each restart is any better. The performance with Sqlite on disk is already pretty good, even more when you actually compare to the time it takes to just compile the razor views, or precompile them.

Feel to try it if you think you are onto something though.

**Comment by hishamco** [comment]
> There might be a solution that involves taking snapshots and storing on the filesystem when the container is disposed, and reload everything in memory when the app is started.

This is a good solution

> Development, I am not sure that losing all data after each restart is any better

IMHO It's acceptable because the important things during development is test the product even with temporary data

Let me try and I will come back to you on this ..

**Comment by sebastienros** [comment]
Just a piece of advice: This won't be possible without doing some weird/hacky changes in both YesSql and Orchard. 
For instance you will need to detect when the Store is disposed, before it's actually disposed. You will also need to know when or not to look for the file. And have a very custom connectionstring that is both memory and file based. It will be to convince me to accept these changes just to enable this scenario.

**Comment by hishamco** [comment]
FYI I found there's a backup APIs in SQLite that has ability to copy db file to memory, memory to file, this is of course will simplify the scenario that you suggested before

**Comment by sebastienros** [comment]
I knew about this API and this is why I suggested it, it won't prevent all the issues I mentioned.

**Comment by hishamco** [comment]
Is this mean there's no plan to implement such provider?

**Comment by sebastienros** [comment]
Correct, can't work in Orchard for the reasons I explained. And not a huge loss either.
