### ISSUE TITLE
NRE When Displaying Content Items That Have Null Content Type Definition

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#7963]
Similar to Issue #1794.

If one creates a new tenant using _TheBlogTheme_ and subsequently delete the `RawHtml` Content Type, one will receive a null reference exception both on the frontend and in the backend when [ContentDisplayManager](https://github.com/OrchardCMS/OrchardCore/blob/b5fa5f6e73526e58050482b7ccdea0c640232409/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplayManager.cs#L63) interrogates a null content type definition when it attempts to display instances of `RawHtml` that were not deleted before deleting the content type.

```csharp
var contentTypeDefinition = _contentDefinitionManager.GetTypeDefinition(contentItem.ContentType); // This will be null

var stereotype = contentTypeDefinition.GetSettings<ContentTypeSettings>().Stereotype; // NRE
```

I suspect this exception will occur more often when experimenting than in actual production, but in general, **it's assumed that when displaying a content item that the content type definition will not be null**, which can make the frontend and backend fairly unusable when it is null. One can't actually fix the problem that I know of other than to realize by some luck that a content type definition has been deleted and add it back so one can then go back and delete the offending content items.

I'm wondering if there is a more graceful solution that can handle this case, such that one can be better notified of the problem, possibly avoid it, and easily fix the issue without making the frontend and backend unusable.

I was thinking one could be warned about deleting a content type definition that has content items in play, and perhaps rather than generating a NRE, one could get some type of overridable shape in its place that would be more descriptive of the problem and allow one to deal with it more gracefully. In the case of the `RawHtml` widget, it would be nice to be able to still view widgets in the design admin menu and see a shape where `RawHtml` would normally be that notifies one of the problem and still gives me the option to delete it if I wish. [Note: And possibly when an Audit Trail Module is in production, give me the option of re-creating the deleted definition.]

I've only run into the problem a few times while experimenting, but it's enough to get one thinking it could be handled much more gracefully.

**Comment by Skrypt** [comment]
I think this is an issue that everyone has faced before. This is related with migration of data when someone changes it's ContentDefinition. I personally use SQL scripts to migrate data manually when I have structural changes in my ContentDefinitions because in the end it is what it is. Adding a warning could prevent this to happen but in the end if the structural changes are required then you have no other choices than to create a data migration.

What needs to be done is an external tool to provide renaming technical names of fields/parts and to be able to migrate it's actual data. Also a tool to be able to remove any fields/part data that is an orphan on a content item. This could be easily done with a module I think. Should this be part of the Admin UI, maybe, it needs some more thinking and conceptualization.

**Comment by deanmarcussen** [comment]
related https://github.com/OrchardCMS/OrchardCore/issues/1014

**Comment by davidhayden** [comment]
Thanks @deanmarcussen. I added a comment to #1014 that addresses a couple things I mentioned here that weren't mentioned in the earlier issue.

This issue can be closed from my viewpoint unless there is value to having it remain open.
