### ISSUE TITLE
IsEnabled flag for User is not respected when authenticating via third party identity providers

### ISSUE THREAD

**Issue by aderderian** [OrchardCMS/OrchardCore#7999]
I am not clear if the local account property of IsEnabled should be respected or not when authenticating via a third party provider. Since there is an account linkage I believe it should be and so we ca use this flag for pending accounts to be processed via workflows, etc.

Secondarily, my workaround is to check this in a custom AuthorizationHandler in my Razor Pages and then redirect a use to a 403 page. We should also potentially store the IsEnabled flag as a claim so this property does not need to be retrieved every request from the UserManager (db call). This would then allow users to access it easily in pages for custom views and actions.

**Comment by hishamco** [comment]
Hi @aderderian the property should respect other AUTH providers too

Could please submit a PR for it

**Comment by deanmarcussen** [comment]
To clarify the `IsEnabled` flag is not correctly checked when using an external provider to login.

This bug we need to fix - I have confirmed it's not in the code base to perform the check there.

The behaviour for `IsEnabled` is to prevent a Login, not allow a Login, and prevent access to resources. 

It was more intended to allow users to have their accounts disabled, but still remain on the system for historic purposes.

A `Pending Account` feature would have to be something different. 

I personally think that's more of a moving the user into a `Pending` role, with no access, than a User Flag property.

This is also why it can't go in the Claim, because the User shouldn't be able to login at all if their account is not enabled.

**Comment by aderderian** [comment]
I agree with your assessment of the situation @deanmarcussen. I am not familiar with the Auth section of the code, so not sure if you can do this PR? I won't be able to get to it.
