### ISSUE TITLE
IOrchardHelper throw null error with a simple query

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#8013]
A very simple Razor page, the IOrchardHelper thrown null error with a simple query.

I took it from here and move the logic to the .cs file: https://docs.orchardcore.net/en/dev/docs/reference/modules/Queries/#razor-helpers

![image](https://user-images.githubusercontent.com/16193516/102280358-ea776d80-3f24-11eb-9b38-7c1938d8724d.png)

**Comment by hishamco** [comment]
AFAIK `IOrchardHelper` is intend to be accessed from within the views

**Comment by orchardc** [comment]
Got it thanks!

**Comment by jtkech** [comment]
@orchardc @hishamco 

Yes we can inject `IOrchardHelper` in a razor page or through its `PageModel`

With our custom `Razor.RazorPage` (razor view) and `RazorPages.Page` (razor page), we can also use the `Orchard` property to get an helper derived from `IOrchardHelper` and used it directly in the view / page.

    await Orchard.ContentQueryAsync(...)

To use the `Orchard` property you need in your `_ViewImports` respectively

    @inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel> // <= For a razor view
    @inherits OrchardCore.DisplayManagement.RazorPages.Page // <= For a razor page

Just tried the following in a page defined from the application (that can behaves as a module so executed in a tenant context / container)

    @page
    @model IndexModel
    @using Microsoft.AspNetCore.Mvc.RazorPages
    @using OrchardCore
    @using OrchardCore.ContentManagement

    @functions
    {
        public class IndexModel : PageModel
        {
            private readonly IOrchardHelper _helper;

            public IndexModel(IOrchardHelper helper)
            {
                _helper = helper;
            }

            public IEnumerable<ContentItem> Result { get; set; }

            public async void OnGet()
            {
                Result = await _helper.ContentQueryAsync("RecentBlogPosts");
            }
        }
    }

    // This one works even if the page doesn't inherit from our custom one
    Test1: @Model.Result.Count()

    // This one works if the page inherits from our custom one (in the view imports)
    Test2: @((await Orchard.ContentQueryAsync("RecentBlogPosts")).Count())

Maybe the issue is that you defined the page from the app and also did some routing at the app level that bypasses the OrchardCore routing, and then the page is not executed in a tenant context / container where the helper is not registered.

**Comment by hishamco** [comment]
Thanks @jtkech I knew that it requires few imports but I thought that the intend to use it in the views only
