### ISSUE TITLE
Sitemap cache handling improvments

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8087]
@jtkech think there's a regression from the distributed pr where the sitemap caches are not being cleared when content items are updated / added, so it's serving stale comment.

I see that you're generating a new id, which I assume is for the document to refresh.

But the local cache itself is no longer cleared.

https://github.com/OrchardCMS/OrchardCore/pull/5249/files#r546233524

I haven't dug further into it.

But I guess we will need to clear the cache locally, and when the id / document is regenerated clear it on the others as well?

**Edited**

Aha! I have missed what you did with `Identifiers`

So the cache is no longer cleared, the identifier is used to resolve whether it is a valid sitemap.

But this will mean the cache is not used if the server is restarted, as it is only collecting identifiers during running operations?

There might just be some changes to be done in the interfaces, to drop some no longer used.

I have to go but there might be a better way we can store the file based on the identifier, and retrieve it that way.

**Comment by jtkech** [comment]
@deanmarcussen 

> So the cache is no longer cleared, the identifier is used to resolve whether it is a valid sitemap.

Yes, and in a distributed env the same happens in a given instance A even the identifier was updated by an instance B.

> But this will mean the cache is not used if the server is restarted, as it is only collecting identifiers during running operations?

Yes, for now is it a problem?

> There might just be some changes to be done in the interfaces, to drop some no longer used.
I have to go but there might be a better way we can store the file based on the identifier, and retrieve it that way.

Yes, as we discussed and planned to do step by step for remaining things that need to be distributed aware. I worked on WF atomicity, next step maybe atomic / exclusive background tasks, maybe a good candidate to clean cached files.

Seems like it's time to think about it

**Comment by deanmarcussen** [comment]
@jtkech I've renamed it to improvements. As not a regression, and we can work through some improvements.

> But this will mean the cache is not used if the server is restarted, as it is only collecting identifiers during running operations?

> Yes, for now is it a problem?

It is not a major problem. 
But Azure WebApps tend to restart for Azure Reasons (they move them around a lot sometimes, so they restart).\
So the improvement would be to handle restarts as well.

As you say we could also look at cleaning with a background task.

I suspect these are different to media. For media we have the possibilities of 10000s files, with no database id/record attached. Whereas with this we have a document.Identifier - the one you are changing.

So we could easily store the cached file, against that identifier name, and background task to clean them when not in database? For ideas.

**Comment by jtkech** [comment]
@deanmarcussen 

> But Azure WebApps tend to restart for Azure Reasons (they move them around a lot sometimes, so they restart).
So the improvement would be to handle restarts as well.

No problem, it was a choice at some point for simplicity, hmm another scenario where final built data are not persisted in the database and where we need a kind of history, hmm here we can't use an index provider as it is related to a single document, so maybe a time based solution

E.g. a date time of the last update that we could compare to the date time of the file. Hmm but time based solution may not be the best, e.g. when updating from different servers with some clocks shifts, but here maybe not so important.

> So we could easily store the cached file

Do you mean that there are not so many files and not so big, so that we could store files contents in the database?

If so maybe good to also use these contents to not have to build a given one if there is not a cached file yet.

Anyway, we would still need a solution to keep the files in sync, e.g. with a time based solution as said above, unless we could always serve these contents from the database, but i assume it's important for perf to cache them in local files, right?

I will focus on it soon
