### ISSUE TITLE
[Orchard.Resources] Depending on a script resource without a version causes an exception

### ISSUE THREAD

**Issue by timmahon** [OrchardCMS/OrchardCore#814]
**Summary**:
If you have a script resource (A) that depends on another script resource (B) where resource B does not have a version set, this causes an exception when the page is rendered.

**Steps to Reproduce**:
In a view use the following markup

`<script asp-name="jquery-ui" at="Foot"></script>`
`<script asp-src ="/Orchard.Demo/Scripts/test.js" at="Foot" depends-on="jquery-ui"></script>`

_Current jquery-ui does not have it's version set in Orchard.Resources._

**Expected Results**:
All scripts are rendered in the correct order.

**Actual Results**:
The markup causes a NullReferenceException when the page is rendered.

![capture](https://user-images.githubusercontent.com/15673531/27041794-e8d003b0-4f8c-11e7-8649-d7409d6b0c55.PNG)

**Comment by agriffard** [comment]
I made a few tests and it seems it cannot be reproduced anymore. 

It must have been fixed since the issue has been raised.

BTW, in the screenshot of the error, you can see it occurs on `<resources type="HeadScript" />` so the `jquery-ui` script declared `at="Foot"` couldn't be the one that caused the error.
