### ISSUE TITLE
Documentation: Add inner recipe feature documentation

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#8166]
Today while browsing OrchardCore code base I discovered inner recipes feature that is not documented at this moment. Would be nice to explain what `ExecutionId` is responsible for.

**Comment by willnationsdev** [comment]
+1 for the need to document how this feature works. Currently trying to identify what the proper format of the step is since what I thought would work didn't.

Although, I will say that, based on the error message that is displayed if it can't find a valid execution ID, it would appear that it is supposed to be the name of the extension/module/theme library, e.g. `MyOrganization.MyProject.MyLibrary` or what-have-you.

**Comment by willnationsdev** [comment]
Figured out the correct format. This ran successfully for me:

Original Recipe Header in `\Recipes` subfolder of module `MyOrg.OrchardCore.MyLib`:

```js
{
  "name": "MyRecipeName",
  "displayName": "My Recipe Name",
  "description": "Defines certain content types.",
  // ...
}
```

Recipe Step:

```js
}, // <-- preceding step
{
  "name": "Recipes",
  "Values": [
    {
      "ExecutionId": "MyOrg.OrchardCore.MyLib",
      "Name": "MyRecipeName"
    }
  ]
},
{ // <-- next step
```

The name of the actual recipe file doesn't appear to matter as it does for the IRecipeMigrator. You just have to give the name that it defines within the file since all of the files are harvested by the `IRecipeHarvester` instances.

**Comment by Piedone** [comment]
This is now documented: https://docs.orchardcore.net/en/latest/reference/modules/Recipes/#recipes-step
