### ISSUE TITLE
Document that all shells can use a single connection string

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#8387]
Original request below. Dean let me know this is actually possible so I'm now documenting it.

### Is your feature request related to a problem? Please describe.
In a multi-tenant app you have to configure the connection string and DatabaseProvider one by one. This suggestion is about being able to use a single, centrally managed connection string instead so you can easily have all your tenants in a single database.

### Describe the solution you'd like
The Database Shells Configuration Provider allows you to store shell settings in the DB. For this a connection string needs to be configured. We could optionally use the same connection string and DatabaseProvider for all tenants too.

### Describe alternatives you've considered
I guess it's possible to set tenants' connection data when or after creating them too from custom code, so the same logic can also be implemented from a module.

**Comment by deanmarcussen** [comment]
I think this is already possible.

The configuration to use would be
```
"OrchardCore" : {
  "ConnectionString": "blah"
}
```
instead of 
```
"OrchardCore" : {
  "Default" : {
      "ConnectionString": "blah"
  }
}
```

I believe someone made changes recently so that if has been set like that, it is no longer visible in the tenant ui to view, so protecting it.

**Comment by Piedone** [comment]
Ah fantastic, I didn't see this being possible with RC2. Indeed, the below works for example:

```json
{
  "OrchardCore": {
    "ConnectionString": "Server=.;Database=MyDB;Integrated Security=True;",
    "DatabaseProvider": "SqlConnection",
    "TablePrefix": "Default",
    "OrchardCore_Shells_Database": {
      "DatabaseProvider": "SqlConnection",
      "TablePrefix": "Shells",
      "ConnectionString": "Server=.;Database=MyDB;Integrated Security=True;",
      "MigrateFromFiles": true
    }
  }
}
```

I haven't found this explained like this in the docs. If it's indeed missing, where do you think it's most fitting? [Configuration](https://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/) and [Shells Configuration Providers](https://docs.orchardcore.net/en/dev/docs/reference/core/Shells/#database-shells-configuration-provider) seem both suitable. I'd add it.

**Comment by deanmarcussen** [comment]
Great. 

If the docs need more examples I would go for Configuration.

It's a configuration thing / feature.

ShellsConfiguration feature wouldn't support that, or is really a totally different configuration. Because it's a host feature (not even a module), it only gets `IConfiguration` not `IShellConfiguration`, so there's nothing that is really related.
We decided when doing ShellsConfiguration to keep it totally seperate, as by choice you might want to segregate out your host information to a host database.

Equally it's a pretty common request, so a guide, with examples, might be just as good. Configuration docs are pretty dense already.

**Comment by Piedone** [comment]
Thanks, opened a PR.

**Comment by jtkech** [comment]
Yes, we use all the default stack of aspnetcore config sources, and in the same order, the last one having an higher precedence, and for our `IShellConfiguration` we add at the end our custom config sources, ordered by specificity.

We only let the env variables config source at the end, so that it still have the higher precedence.

Yes, a provider with an higher precedence can override a config, but only if it provides a value.

So e.g. you can define a global config for all tenants, and you are still able to define specific values for some of them.
