### ISSUE TITLE
missing keep-alive message response when using AzureSignalR in Orchard Module 

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#8409]
### Describe the bug
When using **AzureSignalR** service inside **Orchard Module** (ocmodulemvc) I'm not receiving response for ping requests (keep-alive request `{"type":6}`).
Everything seems to be fine with local SignalR.

With simple **MVC Web app** (without Orchard) I'm getting response for every ping request.

That's why I decided to create issue here instead of SignalR repo.

I've prepared repro repo available here [https://github.com/lampersky/OrchardModuleWithAzureSignalRServiceSDK](https://github.com/lampersky/OrchardModuleWithAzureSignalRServiceSDK)
[Repro.zip](https://github.com/OrchardCMS/OrchardCore/files/5859103/Repro.zip)
![image](https://user-images.githubusercontent.com/6403130/105557882-91fa7380-5d0d-11eb-8d02-4635ca76f6d8.png)

```
OC version: 1.0.0-rc2-15791
SignalR version: 1.7.0
Target framework: netcoreapp3.1
```

### To Reproduce
1. Use attached repro repo,
2. Edit **Startup.cs** in **Repro.TestModule** and in **SimpleMvc.Web** by providing connection string to your AzureSignalR instance,
`.AddAzureSignalR("Endpoint=https://your-endpoint.signalr.net;AccessKey={your-access-key};Version=1.0;");`
3. Run web app,
4. Open Network tab in dev tools in your browser, check if you are getting response for ping request.

### Expected behavior
Response from server for ~every ping request.

### Screenshots
ocmvc + ocmodulemvc with AzureSignalR:
![AzureSignalR](https://user-images.githubusercontent.com/6403130/105557963-c706c600-5d0d-11eb-9a4f-5c583a38d790.png)
![AzureSignalRConsole](https://user-images.githubusercontent.com/6403130/105557970-ca01b680-5d0d-11eb-9211-6664cf139ea1.png)

ocmvc + ocmodulemvc with local SignalR:
![localSignalR](https://user-images.githubusercontent.com/6403130/105557976-cf5f0100-5d0d-11eb-8d6a-c8963eebd536.png)
![localSignalRConsole](https://user-images.githubusercontent.com/6403130/105558034-f61d3780-5d0d-11eb-8c96-878891bd6abb.png)

simple mvc with AzureSignalR:
![SimpleMvc](https://user-images.githubusercontent.com/6403130/105558023-f0bfed00-5d0d-11eb-96fc-2d08b9bb9cf6.png)

### Connected issue
https://github.com/Azure/azure-signalr/issues/1193

**Comment by jtkech** [comment]
@lampersky 

> @jtkech any known workaround when somebody really needs to register long running IHostedService at tenant level?

Yes, an `IHostedService` can only be registered at the host level ;)

I thought about supporting `ITenantHostedService` but we didn't do it because we already have `IBackgroundTask` triggered by an hosted service, but yes the granularity is one minute, this to not consume too much processor time by default, hmm maybe a good candidate to be a configurable option.

For now you would need to register your own hosted service at the app level, it would be a light bg service without bg task schedulers, settings and so on, that would just use the shell host to retrieve the running tenants, and then create a shell scope on them periodically to be able to call a kind of `IFastBackgroundTask`, easy to say ;)

**Comment by lampersky** [comment]
@jtkech I'm closing this issue.

I've tried few options:
1) I've implemented **IFastBackgroundService** but this is only partial solution, because it still requires changing **AzureSignalR** implementation a bit, which is not good to me because I don't want to maintain own **AzureSignalR** version,
2) I've started manually HeartBeat service at tenant level and changed my module as always on, but this was only for testing purpose (just to make sure this is the case), it does the trick, but running it manually is not the right use of **IHostedService**
```
var heartBeat = serviceProvider
    .GetServices<IHostedService>()
    .Where(x => typeof(BackgroundService).IsAssignableFrom(x.GetType()))
    .Where(x => x.ToString() == "Microsoft.Azure.SignalR.HeartBeat")
    .FirstOrDefault();

if (heartBeat != null)
{
    var stop = new CancellationTokenSource();
    Task.Run(() => heartBeat.StartAsync(stop.Token));
}
```
3) I've moved all **AzureSignalR** related things from tenant level to host level, which is not perfect (module was preferred), but I can live with that.

So, just to summarize, for further readers, for now you won't be able to use any library which is using IHostedService (BackgroundService) at tenant level.

**Comment by stoyandimov** [comment]
> I thought about supporting `ITenantHostedService` but we didn't do it because we already have `IBackgroundTask` triggered by an hosted service, but yes the granularity is one minute, this to not consume too much processor time by default, hmm maybe a good candidate to be a configurable option.

@jtkech, I'm running a Minimal API targeting `OrchardCore.Application.Mvc.Targets` and modules targeting `OrchardCore.Module.Targets`. I have a background task registered in a module's Startup that never gets triggered. Do I need to do something to get background tasks to run in a minimal API (with modules)?

```
[BackgroundTask(Schedule = "*/1 * * * * *", Description = "My Background Task")]
public class MyBackgroundTask : IBackgroundTask
...
```

**Comment by jtkech** [comment]
@stoyandimov 

If you don't use `.AddOrchardCms()` but `AddOrchardCore()`, you need to call `AddBackgroundService()` explicitly at the application level.

    builder.Services
        .AddOrchardCore()
        .AddBackgroundService()
        .AddMvc();

**Comment by stoyandimov** [comment]
Thank you that worked for me.
I ran against a different issue but will mentioned it here since other OC devs might endup here:

Due to [this issue with ASP.NET Core minimal APIs](https://github.com/dotnet/aspnetcore/issues/39037) the hosted services and therefore background tasks won't start before the first request hits the application. The workaround is to always send a request after the process starts.

**Comment by ericrrichards** [comment]
I realize I am necromancing, but this seems to be the only thread anywhere about using Azure SignalR with OrchardCore.

I've been trying to use use Azure SignalR in a multi-tenanted Orchard application for a while now, and it mostly works, but there are some issues I'm running into.

Like @lampersky, I haven't been able to get websocket connections to work reliably, because that heartbeat response would never run if I used .AddAzureSignalR() from a module.  So I'd end up with the clients trying to send a heartbeat, then the server would never send one back to them, and so they would think that the connection had timed out and go into reconnection mode.  I had been forcing my JS clients to use long-polling, and that seems to work, but is obviously less desirable than using web sockets.

Today I saw the post here about trying to manually start the HeartBeat IHostedService, and I had a thought that is probably all kinds of wrong.  Let's say I wrap starting and stopping that HeartBeat service in a ModularTenantEvents class.  My SignalR module is registering this, so when a tenant gets spun up, it fires and kicks off this HeartBeat service.  When the tenant is destroyed, it will stop the service.

Nothing is obviously breaking here, and I've now got client websocket connections receiving keep-alive heartbeats so they don't timeout.

This seems like Not The Way To Do Things, but how bad is it really?

```csharp
public class AzureSignalRModularEvents : ModularTenantEvents {
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<AzureSignalRModularEvents> _logger;
    private readonly ShellSettings _shellSettings;
    private string TenantName => _shellSettings.Name;

    public AzureSignalRModularEvents(IServiceProvider serviceProvider, ILogger<AzureSignalRModularEvents> logger, ShellSettings shellSettings) {
        _serviceProvider = serviceProvider;
        _logger = logger;
        _shellSettings = shellSettings;
    }

    public override Task ActivatingAsync() {
        var heartBeat = _serviceProvider
            .GetServices<IHostedService>()
            .Where(x => x is BackgroundService)
            .FirstOrDefault(x => x.ToString() == "Microsoft.Azure.SignalR.HeartBeat");

        if (heartBeat != null) {
            var stop = new CancellationTokenSource();

            _logger.LogInformation("Tenant {TenantName}: Starting hackjob to keep Azure SignalR HeartBeat alive", TenantName);
            Task.Run(() => heartBeat.StartAsync(stop.Token));
        }

        return Task.CompletedTask;
    }

    public override Task TerminatingAsync() {
        var heartBeat = _serviceProvider
            .GetServices<IHostedService>()
            .Where(x => x is BackgroundService)
            .FirstOrDefault(x => x.ToString() == "Microsoft.Azure.SignalR.HeartBeat");

        if (heartBeat != null) {
            var stop = new CancellationTokenSource();

            _logger.LogInformation("Tenant {TenantName}: Stopping hackjob to keep Azure SignalR HeartBeat alive", TenantName);
            Task.Run(() => heartBeat.StopAsync(stop.Token));
        }

        return Task.CompletedTask;
    }
}
```

Possibly relatedly, I've also run into an issue with Azure SignalR and OrchardCore tenant reloads.
The situation is like this:
- If I use regular SignalR, my clients can connect without issues pretty much all the time.  Reloading a tenant doesn't cause any issues.
- If I use Azure SignalR, my clients start out being able to connect fine.  However, as soon as I do something that initiates a tenant shell being released or reloaded (save settings, install features, reload from the Tenants screen), then I start getting transient errors trying to connect to SignalR.

There isn't anything obvious that I can see here - it looks like for some reason SignalR is holding on to a DI IServiceProvider that has gotten disposed.  And this isn't a consistent error; refreshing the page or putting in continuous reconnect logic on the JS client will eventually get connected successfully.  And once the client is successfully connected, there are no issues.  But it is basically a coin flip whether I get connected, or I get this error and it fails out.

Anybody seen this or have any ideas about how to fix it?
```
17:11:18|test4639_1|0HN00RH7ENG3B:0000000D|Microsoft.AspNetCore.SignalR.HubConnectionHandler|ERROR|Error when dispatching 'OnConnectedAsync' on hub.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateScope()
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(IServiceScopeFactory serviceScopeFactory)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```
