### ISSUE TITLE
Every modules can set a table name prefix (Collection)

### ISSUE THREAD

**Issue by chdq0306** [OrchardCMS/OrchardCore#8422]
Every modules can set a "colection",like this
![image](https://user-images.githubusercontent.com/4231580/105658363-4a3c3d80-5f01-11eb-8701-42f8f127f268.png)

**Comment by deanmarcussen** [comment]
Yes, it would be good to have an implementionat / or support for YesSql.Collections.

Maybe one way to handle it (and the transition, because we need to think of existing sites), is to register an `IOptions` class, which can provide `Collection` names.

It could be empty by default, i.e. no collection, and when a collection is registered use the collection name, for the module / feature.

The only dificulty is they would have to be configured before the site is setup (or manually rename the tables)

**Comment by chdq0306** [comment]
How to use the Tokens?Where set? And other modules ？

**Comment by chdq0306** [comment]
I have got it by myself with yessql collection;
OrchardCore is not only a cms or little saas ,but a powered saas now!

**Comment by chdq0306** [comment]
已经解决了，谢谢大家，学到了很多东西。虽然不是完全按照OpenID Tokens的例子搞的，但是也学习了。
