### ISSUE TITLE
Add check to confirm OpenId has Read access to signing certificate

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#847]
Follow-up from #827

It seems worth adding a check in the OpenId module that the process can access the cert when updating the settings through the UI. And/or improve the log output.

**Comment by Jetski5822** [comment]
@PinpointTownes Got time to take a look? (See you doing commits ;))

**Comment by Piedone** [comment]
@kevinchalet could you please comment on whether this is still applicable?

**Comment by kevinchalet** [comment]
@Piedone you can't know for sure whether a certificate will "work" until you really do the crypto operation you need (e.g signing a token, which requires the private key) and AFAIK, we haven't implemented any "test routine" that would perform a test crypto operation to eagerly detect invalid certificates (or inaccessible private keys).

That said, I don't think we should spend time on that since we're planning on removing this feature once the secrets module lands :smiley:

**Comment by Piedone** [comment]
Good point, and thank you. Closing it, then, in favor of https://github.com/OrchardCMS/OrchardCore/pull/7891.
