### ISSUE TITLE
Fields placement don't use the order defined in the Content type when rendered on front

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#852]
Add two fields in a Content type definition.

Drag and drop the field added in second before the first one created.

In the editor, this order will be used but when you display it, it keeps the order of creation.

**Comment by agriffard** [comment]
If there is no placement specified in the theme, the fields placement should by default respect the order set in the Content definition.

**Comment by agriffard** [comment]
Do we need a dedicated admin page like in O1 to specify the placement of the editors for fields and parts together?

If we need inspiration, Craft CMS seems to have a nice placement editor in which you can create tabs.

**Comment by paynecrl97** [comment]
This is also true of Content Parts, but I'm not sure if this is by design (if so, then it's a bit confusing IMO):

Currently, the placement is determined like so:

1. If there's a matching placement.info record, then use that
1. If not, use a location set in the driver suitable for the current display type, eg: `Shape("MyShape").Location("Detail", "Content:5");`
1. Fall back to a default placement if none of these options are available

Adding in logic to check the order of the parts in the type definition introduces a few problems:

- Parts will almost always have an order/position (the only exception I can think of is content type definitions not created/edited with the UI). This means that drivers that explicitly set the position will almost always have this value overridden.
- What zone do we put these ordered parts in to? What if a driver does something like `Shape("MyShape").Location("Detail", "Header:5");`?

I created this proof of concept to show how ordering parts on the front end could work: https://github.com/OrchardCMS/OrchardCore/compare/issue/852/field_position?expand=1 (notice the hard-coded zone name). I think this should be easily adaptable for fields too.

**Comment by sebastienros** [comment]
After some discussions, we agreed that the order defined in the Content Type definition is just for the editor, by design. We could have some hint on the page to warn about this behavior.
