### ISSUE TITLE
IServiceProvider disposed issue when use Task to run a background job

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#8522]
I run a background job using a Task in every 10 seconds. The task which will retrieve the site settings from ISiteService. But every time I call GetSiteSettings of ISiteService, it throws below exception.
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at OrchardCore.Settings.Services.SiteService.get_DocumentManager()
   at OrchardCore.Settings.Services.SiteService.GetSiteSettingsAsync()
```
The IServiceProvider already inject to the class before the job running. And ISiteService can be resovled from IServiceProvider with succeed. So I can't figure out why the exception thrown and saying that the IServiceProvider was disposed.
Below is the issue code:
```
using (var scope = serviceProvider.CreateScope())
            {
                var siteService = scope.ServiceProvider.GetService<ISiteService>();
                var siteSettings = await siteService.GetSiteSettingsAsync(); //Exception is thrown from here
                .......
            }
```

**Comment by jtkech** [comment]
@HengzheLi 

Because we support multi tenants (multi sites) and modularity, for many reasons we need custom tenant / shell containers and custom service scopes, and we provide API to get and use them.

Because you can first resolve `ISiteService` with the injected service provider, i assume your class is resolved and used under a shell / tenant context, and is a **singleton**, more precisely a **tenant singleton** (e.g. if registered through a module startup), this to be able to start (and then to stop under some conditions) a periodic job.

That said, here at least you need to get and use what we call a shell scope, this by injecting and using `IShellHost` that is an app level singleton, and `ShellSettings` that is a tenant singleton.

                var shellScope = await _shellHost.GetScopeAsync(_shellSettings);

                await shellScope.UsingAsync(async scope =>
                {
                    var siteService = scope.ServiceProvider.GetService<ISiteService>();
                    var siteSettings = await siteService.GetSiteSettingsAsync();
                    .......
               });

But take care, a shell container may be released, e.g. if we enable / disable a module / feature, if we save some site settings, so you may have to stop your periodic job when your service is being disposed, i would need more infos on your code.

Note: `ISiteService` is a tenant singleton, so you could inject it directly, but `GetSiteSettingsAsync` still need to be called in a tenant / shell scope, so better to resolve it lazily as you did.

**Comment by HengzheLi** [comment]
I did use the Task in a tenant singleton class. And for the below comment

> But take care, a shell container may be released, e.g. if we enable / disable a module / feature, if we save some site settings, so you may have to stop your periodic job when your service is being disposed, i would need more infos on your code.

My understand is that if I don't enable/disable a module/feature or save some site settings, my tenant singleton class won't never be disposed. And my periodic job will keep going for ever. Am I correct?

How about a CustomeSetting, will it cause a tenant singleton be disposed if it is updated and saved?

**Comment by jtkech** [comment]
@HengzheLi 

E.g. when first composing a given tenant / shell, we create a temporary container to resolve modules startups, that is then disposed, using the shell host ensures that you get a scope under a non disposed tenant / shell container.

How do you start your jobs? Through the ctor of your tenant singleton? If so, how do you resolve / activate it?

You may want to derive your class from `ModularTenantEvents`, register it as an `IModularTenantEvents`, and then override e.g. the `ActivatedAsync` and `TerminatingAsync` event handlers, there are some examples in the source code.

**Comment by HengzheLi** [comment]
My derive class from ModularTenantEvents is the place where I start my periodic job. The job is started in ctor of the class and seems it runs well for the last two days.
