### ISSUE TITLE
SQLite Error5: Database locked 

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8551]
When I launched multiple exports from local OC to another server, I ran into an database locked error. 1st import is all content export (~1700 items), second export is just taxonomy content item. Seems they ran at same time and it caused this issue

![image](https://user-images.githubusercontent.com/52829889/107326531-dcb91100-6aab-11eb-9b70-7240ce696bb3.png)

Anyway, it seems that it unlocks itself after some while (probably after import is finished) but until then I can't access CMS.

**Comment by jtkech** [comment]
Yes, because they trigger separate `_httpClient.PostAsync` they may run concurrently.

Each one in a different scope, but sqlite don't support concurrent writes.

**Comment by MikeKry** [comment]
@jtkech 

Ok, I understand that, but shouldn't it allow parallel reads ? I am not aware that accessing CMS would write something in DB, so it would fail on read. But if its not possible, then we can close the issue. 

I am just curious about few things: 
a) what happens when multiple users save content item at same time? Is there some queue to handle multiple requests?
b) same as a, but with imports => can I run multiple imports, or should I enforce user to run only one at a time? 
c) might not be related, but.. what if this lock or some other error happens during email sending, is it stored somehow and sent when possible, or it is just lost?

**Comment by jtkech** [comment]
@MikeKry 

> Ok, I understand that, but shouldn't it allow parallel reads ?

Yes, it is allowed but not during a write, at least in the mode we are using sqlite

> what happens when multiple users save content item at same time? Is there some queue to handle multiple requests?

Yes somewhere as we are using database transactions, but if there are too many updates, there may be a victim.

For info, at another level, on yesSql side, there is an optional concurrency checking to ensure that we write the same document version that we updated, this to preserve data integrity but not to manage a queue, if there is a version mismatch there is an exception, but for now we are not using this option on all documents, e.g. not for content items.

> same as a, but with imports => can I run multiple imports, or should I enforce user to run only one at a time?

Anyway not recommanded, and particularly with sqlite.

> might not be related, but.. what if this lock or some other error happens during email sending, is it stored somehow and sent when possible, or it is just lost?

It may depend in which context it is sent, through a background task it is done in an isolated shell scope, so it will be sent even there is an error (non fatal error) in another scope. Through a worflow, if it is triggered by a timer event, this is the same, but when the WF is executed in the same scope throwing a db lock exception, it depends, if the excetion is thrown at the end of the scope e.g. when committing the session, the mail is sent before, but if before sending the mail there is a db query that fails on a db lock, yes the mail would not be sent.

For info, i have some pending PRs about atomicity for background tasks, workflows, database migrations when activating a tenant, but not yet on imports / recipes, and so on, so that e.g. we could start multiples imports that would be executed atomically, so one after each other as they were "enqueued".

**Comment by MikeKry** [comment]
@jtkech 

Thank you, that explains a lot of problems I have encountered. I guess that best solution for me is to use different DB for now.

> For info, i have some pending PRs about atomicity for background tasks, workflows, database migrations when activating a tenant, but not yet on imports / recipes, and so on, so that e.g. we could start multiples imports that would be executed atomically, so one after each other as they were "enqueued".

That sounds cool :) But I guess it won't be anytime soon, right? Sounds kind of complicated, but it would be fine, as I have ran into this exception multiple times. I can imagine there could be just some queue on OC side (or yessql) in case of sqlite, that would send write requests one at a time, when db unlocks.
