### ISSUE TITLE
Tenant section in appsettings.json 

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8558]
Create a tenant section in the appsetting.json file.
OrchardCore--->Tenants---> list of tenants.

Declare the word DEFAULT as a reserved word for tenants as well?

**Comment by Piedone** [comment]
Can you provide examples of how you'd use this feature? I don't really understand what you're requesting.

BTW tenant-level configuration and a lot more is available, see: https://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/

**Comment by Skrypt** [comment]
This is getting redundant in different issues now.

**Comment by JoshTango** [comment]
They are 2 separate issues.
This issue is simply saying tenants should be in their own section called Tenants in the appsettings.json file rather than having on the tenants on the same level as OrchardCore.

**Comment by Skrypt** [comment]
But you are talking about almost the same topics in 3 different issues there.
I don't mind, but the issue is spreading here.

Please provide an example of a configuration that would be more appropriate.
A JSON representation of that configuration with some comments.

Here after, we will debate why the configurations are made like they are, if changing them would add any plus value to the OC or else. I think this part has been made in OC by @jtkech and I personally think it works perfectly fine right now.

**Comment by JoshTango** [comment]
I will re articulate this all in a new issue.
