### ISSUE TITLE
Archiving unused Tenants

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8626]
If a tenant has not be used or accessed for X number of days then the tenant would be archived by compressing it and storing it in cheaper blob storage.

Since you have delete tenant working and you are working on tenant backup you should have all the building blocks you need to make this happen.

I suppose X number of days would be both configurable on the tenant level and globally for all tenants.

**Comment by Piedone** [comment]
Due to on-demand shell starts, an inactive tenant is not using any CPU or memory. Its storage does still use space, but if you store Media in Azure Blobs, then that wouldn't change. So, only the DB tables remain.

This looks like a very niche requirement. You can implement a clean-up job from the Default tenant, and now that tenant deletion is available, delete inactive tenants periodically. You can e.g. save the last activity time to their `ShellSettings` from a middleware.

Does this meet your use case or do you still think something needs to be built into OC?
