### ISSUE TITLE
Recipe Migrations introduce unexpected logical dependencies

### ISSUE THREAD

**Issue by flew2bits** [OrchardCMS/OrchardCore#8747]
### Describe the bug
The `RecipeMigrator` makes calls to modules that provide implementations of `IRecipeEnvironmentProvider` (currently implemented in `OrchardCore.Users`, `OrchardCore.Settings`, and `OrchardCore.Recipes`). In the situation described below, updates were made to `OrchardCore.Users` that have to occur prior to any recipes that are run, otherwise a SQL error occurs:

```IRecipeEnvironmentProvider thrown from OrchardCore.Users.Services.RecipeEnvironmentSuperUserProvider by SqliteException Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: UserIndex_a1.UserId'.```

This means that any module that uses the `RecipeMigrator` should logically define a dependency on any module that implements an `IRecipeEnvironmentProvider`. However, this puts the onus on the developer to know all of those modules, which could change at any time. Also, the module that was failing to update was `OrchardCore.Menu` in the step `UpdateFrom2Async`; the recipe doesn't make any use of the AdminUserId provided by the `OrchardCore.Users` module, so this is not an actual dependency.

**NB**: Since the `OrchardCore.Users` migrations don't update successfully (the transaction is rolled back), this causes other problems in the site, such as the inability to edit users.

### To Reproduce
1. Create a new docker container using orchardproject/orchardcore-cms-linux:latest
2. Setup the site in the web browser
3. Stop the container and update it to orchardproject/orchardcore-cms-linux:dev
4. Start the container and visit the site
5. Check the logs for the SQL error

### Expected behavior
The migrations should complete successfully

### Possible remedy
The `DataMigrationManager` could check modules to see if they provide an implementation of `IRecipeEnvironmentProvider` and execute these migrations before others. These migrations should be run in the reverse order of the `IRecipeEnvironmentProvider`'s `Order` property.

**Comment by flew2bits** [comment]
### Temporary work-around
In my situation, the work-around to this was to start the site, and then disable and re-enable the `OrchardCore.Menus` feature. This allowed the `OrchardCore.Users` migrations to complete.

**Comment by deanmarcussen** [comment]
I would suggest the best thing to do here is `try catch` the `RecipeEnvironmentSuperUserProvider` 

I wouldn't want to rearrange the module dependencies / ordering for this.

The `RecipeEnvironmentSuperUserProvider` is not going to be useful to provide the `UserId` when upgrading from RC2 because the `UserId` did not exist!

Ultimately all we really need in terms of an upgrade from RC2, is that no exceptions are thrown, so migrations are able to complete successfully.

Equally we're (OC) internally using the `UserId` in recipes (I think, dashboard widgets might be an exception to this). The feature was added more for consumers of Orchard Core, to allow creating of content items, from with recipes.

**Comment by flew2bits** [comment]
Okay; that's easy enough to fix. I'll get a PR ready shortly.

**Comment by flew2bits** [comment]
Submitted PR #8748
