### ISSUE TITLE
Solution build is failing

### ISSUE THREAD

**Issue by dafergu2** [OrchardCMS/OrchardCore#8789]
### Describe the bug

Running `dotnet build` in the root directory of the repository results in:

`/Users/df/development/dafergu2/src/Templates/OrchardCore.ProjectTemplates/OrchardCore.ProjectTemplates.csproj(96,5): error MSB4044: The "ReplaceFileText" task was not given a value for the required parameter "ReplacementText".

### To Reproduce
1. Clone the repo
2. Execute `dotnet build` in the root of the repo with both net5.0 and netcoreapp3.1 sdk's installed

### Expected behavior
Build is successful

**Comment by dafergu2** [comment]
This is due to the change in https://github.com/OrchardCMS/OrchardCore/pull/8717 that builds the project templates for each TFM.

As part of the multi-target build, the project file is process with an empty `$(TargetFramework)`.  This causes the following to fail:

https://github.com/OrchardCMS/OrchardCore/blob/60bad85a0a4ba8699595f98b56e98b8e371a0eb2/src/Templates/OrchardCore.ProjectTemplates/OrchardCore.ProjectTemplates.csproj#L96

When the multi-target PR was merged, the direction for the templates from @sebastienros was to simply build them for the net5.0 TFM.  If we want to build for all TFMs, we will need to change how the templates are rewritten in the `TransformTemplateConfigs` target.  I looked at doing this briefly and the approach I was taking (prefixing the temp file output folder path with a TFM folder) ran into a couple of flaws so I backed off and went with simply specifying that the template library was only built for net5.0.  When the template is used, you can still specify the resulting project to target netcoreapp3.1 however.  The line linked above is simply setting the default.

**Comment by jtkech** [comment]
> This is due to the change in #8717 that builds the project templates for each TFM.

In fact, before when defining a TFM in a given project, and also TFMs (as it was defined in the global props file), through the dotnet cli, a dotnet build (without specifying --framework xxx) was building only one TFM, but through Visual Studio it was building both. So now we define only a TFM or a TFMs but not both so that it behaves the same.

Then, we first defined a singular TFM for web app, project templates and all was okay, but through our CI integration we do a dotnet build at the solution level, that now, because of the above, builds both TFMs, so because the Tests project references the web app, and so on, i made these projects multi targetable.

But at this point te ProjectTemplates was still defining a single TFM ;)

Then, because there are known isuues on building concurrently multi targetable projects concurrently when a multi TFMs project references a multi TFMs app that may then been built concurrently, we separated in 2 steps the dotnet build command for each TFM, that's why finally we made also the ProjectTemplates multi targetable.

Sorry for the long story ;)

So yes, at the root level i could repro the issue with dotnet build, but that's okay with e.g. dotnet build --framework net5.0. Hmm, we separated the dotnet build in 2 steps, but at some point it was working with only one dotnet build, i will check it more in depth for the ProjectTemplates, thanks for the feedback

What we could do is to modify the CI to not build all projects for both TFMs and then re-use only a single TFM (but not also TFMs) for the web apps, and also the ProjectTemplates

**Comment by jtkech** [comment]
@dafergu2 

After a deeper look at the ProjecTemplates, you're right makes no sense to build it for both TFMs as anyway it doesn't pack a lib folder with multiple TFMs, and when building each TFM (that may happen concurrently) it mutates the content of some .json files, and the last wins, currently netcoreapp3.1. I would also prefer to only use one TFM for the web apps

This is what we were doing at some point, but as said we separated the dotnet build at the solution level in 2 builds for each TFM, this because of some race conditions, e.g. when building the cms app concurrently with the tests project that references the cms app, the cms app is built concurently and then may output some files concurretly in the same output folder.

But there is no obvious way to update the CI to re-use `dotnet build` without specifying --framework, but still in separate steps, e.g. one for all the projects under the src folder, one for all the projects under the tests folder. Hmm, and no luck here, the `OC.Benchmarks` project references the tests project that references the web app.

**This because dotnet build doesn't accept anymore globbing patterns to find project files, so you need to be in the same folder as a project file or a solution file.**

So for now, i think i will just update the `ProjectTemplates` project to only copy / mutate the json files for our defined default framework, so that the default TFM when using our templates will be again net5.0 ;)
