### ISSUE TITLE
Regression from Dashboard Widgets

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8838]
### To Reproduce

Go the edit the Blog, a `ListPart`

The `DetailAdmin` display location added for Dashboard Widgets causes both the `TitlePart` and `HtmlBodyPart` to be rendered in the `Content` zone.

### Expected behavior

I didn't follow completely the choice to use `DetailAdmin` for the dashboard widgets.

Feels like it conflicts with existing `DetailAdmin` views (of which there is only really the `ListPart`)

Easy to fix the `TitlePart` by giving it a `DetailAdmin` view and removing the existing rendering from the `Content.DetailAdmin` shape.

Less easy to fix the `HtmlBodyPart` showing as well. Without resorting to a different display type.

Which would probably be my preference. `DisplayAdmin` for the `ListPart` as it **was** the only one making use of it.

The point is when using the `ListPart` with more parts on it's parents, the list display gets ridiculous, where it shouldn't be showing these extra details, just the list of items that are contained in it (unless user specifically put them there with placement).

`DisplayAdmin` makes sense to me, as the controller it's viewed through is actually called `Display`

### Screenshots

<img width="1126" alt="Screenshot 2021-03-12 at 10 49 20" src="https://user-images.githubusercontent.com/13782679/110932807-df658b00-8323-11eb-80d0-f4388c7fffdd.png">

**Comment by hishamco** [comment]
I just notice the same bug, hope it could be fixed soon

**Comment by sebastienros** [comment]
> @sebastienros will want to do it differently :)

You bet! I am glad you realized your PR would be controversial, like it was bothering you somehow but couldn't find a better way without going deeper in the reflection ;)

I don't buy the argument of Display controller -> `DisplayAdmin` ... or we would change the front-end display type to `Display` instead of `Details`.
But that's not the issue here. You are creating a new display type such that no other part can be rendered than the ones that you want to be in this screen. And because you decided that `ListPart` was fine, we got only `ListPart` ... let's call this display type `ListPartAdmin` ;) Why wouldn't `TitlePart` be by default on a `DetailAdmin` page? Or a body part? Quite opinionated.
What if someone wants to display something else in the admin, that doesn't have a ListPart? It will show empty.

How do we handle that in OC usually? Placement or custom templates. The only dynamic solution being placement in this case. 
_Ideally_ we would configure the Blog to hide its `Title` and `HtmlBodyPart` from the `DetailAdmin` display type.

I thought we could share the `DetailAdmin` with the dashboard too, so we don't create too many display types that we have to provide defaults in each display driver. Maybe we need one for the dashboard widgets (Dashboard?). But I don't think this removes the issue of how we decide what is on `DetailAdmin`.

We can already handle the placement for Blog with the recipe or theme. That would be the best solution for now IMO. But only for Blog. What about other types?
A nice solution, if we don't want to use @TFleury 's new admin placement feature, would be to provide checkboxes with common display types, maybe in the current list of Parts/Fields from the Content Type Definitions screen, and there we could check/uncheck where this part should be hidden (displaying is harder to manage, because placement, and also what's the default values if nothing is set?). This would be a custom placement info provider. And we could also use it as part of the Blog recipe to actually hide Title and HtmlBodyPart from appearing there. Some global settings would let us provide which display types we want to show in the list (DetailAdmin, SummaryAdmin). Probably would be for admin placement only. Could also contain just "string" placement rules ("-", "/Header", ...) but it would be close to the placement.json editor. We definitely need some better UI there.

So for now I would just provide a placement file with the Blog recipe to hide the parts from this view. And I want to repeat that if we decide to add a new display type for dashboard, the issue remains, though might be postponed.

**Comment by sebastienros** [comment]
We can chat if you prefer, to find a solution.
