### ISSUE TITLE
Provide database connection string examples

### ISSUE THREAD

**Issue by snovak7** [OrchardCMS/OrchardCore#885]
invalid keyword: data source ArgumentException

Sadly copying from "Example" connection string and changing settings doesn't work since it reports error.

Replacing with something like (from Npgsql website) works:
Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase

**Comment by sebastienros** [comment]
Ah, the example connection string must be for SQL Server ...

**Comment by agriffard** [comment]
Do we enhance the setup to provide an example of connection string by database type?

**Comment by agentgates** [comment]
snovak7,

I know it's been a while and you might have already solved it but just for the record, please find the correct PostgreSQL connection string on the bottom of this comment.

agriffard,

That would be very useful. In case you'd implement that I have compiled a list for you with some basic connection string examples (in ascending order) and links to more advanced options, so that you don't have to look them up:

MySQL/MariaDB https://www.connectionstrings.com/mysql/
`Server=MyServer;Database=MyDatabase;Uid=MyLogin;Pwd=MyPassword;`

PostgreSQL https://www.connectionstrings.com/postgresql/
`Server=MyServer;Port=5432;Database=MyDatabase;User Id=MyLogin;Password=MyPassword;`

SQLite https://www.connectionstrings.com/sqlite/
`Data Source=c:\MyDatabase.db;Version=3;`

SQL Server https://www.connectionstrings.com/sql-server/
`Host=MyServer;Database=MyDatabase;Username=MyLogin;Password=MyPassword`

**Comment by hishamco** [comment]
@sebastienros what's prevent us from extract the connection string example from the PO resource and control it via JavaScript based on the database type

**Comment by sebastienros** [comment]
Nothing to do with PO files, just a hint on each textbox that sets the connection string.

**Comment by hishamco** [comment]
> Nothing to do with PO files

Don't forget that the current connection string look like this
```html
<span class="text-muted form-text small">@T["The connection string to your database instance. e.g., Data Source=<em>localhost</em>;Initial Catalog=<em>Orchard</em>;User Id=<em>userid</em>;Password=<em>password</em>"]</span>
```
which is the thing I dislike, we can strip the actual connection String and localize the remaining text
```html
<span class="text-muted form-text small">@T["The connection string to your database instance. e.g. "] Data Source=<em>localhost</em>;Initial Catalog=<em>Orchard</em>;User Id=<em>userid</em>;Password=<em>password</em></span>
```
