### ISSUE TITLE
Cannot edit / view SuperUser

### ISSUE THREAD

**Issue by kdubious** [OrchardCMS/OrchardCore#8870]
There is no UI to edit which account is the Super User account.
There is no UI to indicate which account is the Super User account.

**Comment by hishamco** [comment]
The `SuperUser` is the first user created in the system, I think we did some restriction to avoid disable it or delete it too

**Comment by Skrypt** [comment]
Hmm, that's worth keeping it open. Nothing allows to filter users to find the super user account. 

Should we be able to filter users to find the _Super User_ account?
Should we make the edit user form display a notification that we are currently editing the _Super User_ account?

**Comment by kdubious** [comment]
I would think:

1. identify which user is Super User in User List
2. identify which user is Super User in User Edit
3. remove role assignment UI in User Edit for Super User
4. provide UI to select a different user as Super User

**Comment by hishamco** [comment]
1 & 2 could be done by make the username bold or much better use an icon as indicator

3 Agree, if the super user is there

4. This could be done by impersonation whiched demoed by @agriffard, for more details checkout [OCC](https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules)

**Comment by Skrypt** [comment]
We allow only one Super User per tenant as of now. So, you would need to be logged in as a Super User to create an other one. So, basically, editing the current Super User account should be giving the same result if we agree that we should always have only one Super User account per tenant.

**Comment by kdubious** [comment]
A dropdown somewhere that allows you to pick the "only" Super User, which is only visible to the Current Super User

**Comment by Skrypt** [comment]
But, why? Can't you just change the Super User "username" or "email" to reflect what would be used on this other user account which you want it to get it assigned to? Here, if we allow to move the Super User account from one UserId to an other then it makes thing more complicated "security wise".

**Comment by kdubious** [comment]
So if I want to make you the Super User, and me just an admin...
1. Create another user account with my second email address
2. Edit the current Super User account to your name + email (but now all the history of my content authorship moves to you)
3. Sign in as my other email address, and change that account back to the email I really want to use

versus
1. Create your account.
2. Select you as the site Super User

**Comment by Skrypt** [comment]
So, yeah, here is an other issue. That Super User account will have create content items and migrating them to a different user account might take a lot of time depending on how much data this involves.

Have you seen for example how Github handles changing your UserName? Does it migrate all your Commits and PR's and comments and tagging like @skrypt in a issue comment? This is mainly why I don't really like migrating a user accounts. I did it with ContentHandlers and removed them because doing this is non neglectable performance wise. If moving a Super User account from one account to the other takes 10 minutes then it's not a solution.

**Comment by Skrypt** [comment]
Let's wait and see other contributors opinion on this. I think ultimately what you/we need is a module to migrate content items from one user account to the other which a module could subscribe on if it requires to parse some of it's content.

**Comment by kdubious** [comment]
"That Super User account will have assigned content items and migrating them to a different user account might take a lot of time depending on how much data this involves."
I think Migrating content is a separate process from assigning a different user as Super User. Typically Super User is a "role" / "claim" assigned to a user. I'd rather not rename users. (but just my opinion)

**Comment by Skrypt** [comment]
Super User is not a role in OC.

**Comment by kdubious** [comment]
@Skrypt I understand that it is not managed formally by a role, but I think the typical user things of "Super User" as a set of permissions assigned to one (or more) users, rather than an account whose email should be changed to match the person acting in that role.

**Comment by Skrypt** [comment]
Yeah, I see your point, I don't want to say you're wrong. Because then I would assume that what we did is perfect which is probably not in some case. I keep this issue opened.

Should we have more than one SuperUser account in OC?
Should we be able to change the SuperUser account to a different UserId?

Lots of questions here which I think needs some reflection 😉

**Comment by kdubious** [comment]
@Skrypt Also, I'm not trying to be pushy to "do it my way," just tossing out opinions / experience as someone with "fresh eyes" looking at the system.

> Should we have more than one SuperUser account in OC?

I say not necessarily, but it might be nice to have. (Prevents someone from getting locked out when they lose access to an email address)

>Should we be able to change the SuperUser account to a different UserId?

For this I think yes.

>Should we be able to migrate content from one user account to another?

For this I think's it's related, but a separate topic.

**Comment by deanmarcussen** [comment]
A lot depends on what you see the super user as.

for us it is and will always be admin - by convention internally. An account which none of us use, but the password for which is available for dr scenarios.

@Skrypt is right, it’s not a role. It’s a magic permission handler which succeeds everything. Another reason we never use it, because testing permissions is difficult when everything succeeds.

(I have had to remove the handler on one site, as us administrators aren’t allowed to see some secure content)

The value itself is an id stored on site settings, ie ISite.

I don’t see any reason we can’t have some ui for it somewhere, but we would need a permission to secure changing it, which you would probably only want to grant to the super user, but I’m not so sure about ui to indicate who is the super user. Just sounds like an invitation to try and hack that particular account ;)

personally if I wanted to change it (haven’t had the need yet) I’d just edit the db.

so really all I am doing here is an explanation of what the magic super user is.

and then asking why you need to be able to change it, and which user you think should have rights to be able to reassign it?

**Comment by kdubious** [comment]
@deanmarcussen makes sense.
Then perhaps one of the 2 simplest approaches is best:
1. A dropdown to select this user, editable ONLY by the current Super User
2. Do nothing

**Comment by sebastienros** [comment]
Closing in favor of https://github.com/OrchardCMS/OrchardCore/issues/8903
For now please update the database directly, or use a migration.
