### ISSUE TITLE
Support multiple translation providers

### ISSUE THREAD

**Issue by doticca** [OrchardCMS/OrchardCore#8939]
Localization manager should be able to handle multiple instances of ITranslationProvider. This way we can create more methods for storing translations.

**Comment by hishamco** [comment]
@doticca could you please tell us the current issue that you are trying to solve? what is the current limitation?

**Comment by doticca** [comment]
> @doticca could you please tell us the current issue that you are trying to solve? what is the current limitation?

In our project we have a module under construction that provides the ability to administrators to create translations at the DB level (per culture) without the need to save/load them from a PO.
These translation are served through a singleton that implements ITranslationProvider.
I have already used a version of the LocalizationManager for our needs using service.Replace and it merges the new translations at the end of the dictionary.

**Comment by hishamco** [comment]
You can create a custom localization provider that read your localization resources from within the database without touching PO related types

You just need to register your `DatabaseStringLocalizerFactory` & `DatabaseStringLocalizer` in the same way the `PoStringLocalizer` did, still I don't see any need to support multiple translation providers, unless you need to provide different translations from different providers like your custom module

Let me think if there's impact of this, because one thing I'm thinking about is the provider priority, which will win first. Assume I have a resource `Title` that's available in both providers, from where the resource value should come from? If you say the first one, perhaps the intend the value should come from the second provider

@sebastienros your thought

/cc  @Skrypt @jptissot

**Comment by doticca** [comment]
Yes I would like to keep the .po translations as the default ones, but at the same time provide the end user with the functionality to replace them with his own.

**Comment by Skrypt** [comment]
We have a PR that needs work that will introduce Data Localization that will come from the DB. Maybe this is not needed like @hishamco is mentioning.

Related with : https://github.com/OrchardCMS/OrchardCore/pull/8098
