### ISSUE TITLE
The initial site creator (site administrator) cannot add a new role to himself.

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#8977]
### Describe the bug
In the recent month release, the initial site creator (site administrator) cannot add a new role to himself.

### To Reproduce
1. Go to '/admin'  panel
2. Click on 'Security/Users'
3. Select the user who's the creator of this site (Site Adminstrator user), then click Edit 
4. Add extra roles in addition to Administrator, click Save.

### Expected behavior
The extra roles should be set for Site Adminstrator user; but it doesn't.

**Comment by Skrypt** [comment]
Not necessary as this user is currently the "super user" so it has all the roles implicitly without having them explicitly.

**Comment by deanmarcussen** [comment]
This was done to prevent a user removing themselves from all roles, and then being unable to access the site.

`// The current user cannot alter their own roles. This prevents them removing access to the site for themselves.`

You need to login as a different administrator to change the roles for the current administrator.

The problem was users complained they could remove themselves from the administrator role (when they were not site owner, and then when it saved (because it logs them out on save, and relogs them in, they no longer had access to the admin / users list to add themselves back in again)

The ui doesn't reflect that in any way, so it is not obvious.

Need to have a little thing about what is best for the ui here.

I lean towards disabling the removal of any existing roles on the current user, but allowing addition of roles (if they have permission to assign them)

Really the problem is we have tried to prevent users doing silly things, which then makes it more dificult for users to do things they want to.

**Comment by Skrypt** [comment]
You are probably right but if we remove the super user to use Owner permission like we talked last time then we will need to rethink these things. So the issue here is not relevant if we refactor things.

**Comment by Piedone** [comment]
This isn't the case anymore, you can add roles to your own account as the initial admin user.

**Comment by mvarblow** [comment]
> // The current user cannot alter their own roles. This prevents them removing access to the site for themselves.

@Piedone, are you sure this is fixed? I'm still seeing this behavior. It's not just for the initial admin. It's actually for any user who tries to edit their own roles. The problem is likely here in the UserRoleDisplayDriver:

```
    public override async Task<IDisplayResult> UpdateAsync(User user, UpdateEditorContext context)
    {
        // The current user cannot alter their own roles. This prevents them removing access to the site for themselves.
        if (_httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier) == user.UserId
            && !await _authorizationService.AuthorizeAsync(_httpContextAccessor.HttpContext.User, StandardPermissions.SiteOwner))
        {
            return null;
        }

``` 

And the behavior is strange. It looks like it made the change. No error. But also, no change was made.

**Comment by mvarblow** [comment]
Oh, I take that back. It's for any admin who is a site owner. But still, is this a check that we want? If so, we should at least add a notification that your role changes were not saved?

**Comment by mvarblow** [comment]
Oh, and another reason to consider just removing that "silently return" code block at the top of UpdateAsync -- it already has a check later on to ensure that there is always at least one administrator account:

                    // Make sure we always have at least one enabled administrator account.
                    if (enabledUsersOfAdminRole.Count == 1 && user.UserId == enabledUsersOfAdminRole.First().UserId)
                    {
                        await _notifier.WarningAsync(H[$"Cannot remove {OrchardCoreConstants.Roles.Administrator} role from the only enabled administrator."]);

                        continue;
                    }

This code below really feels like a bug, perhaps left over accidentally when the code above was added?

        // The current user cannot alter their own roles. This prevents them removing access to the site for themselves.
        if (_httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier) == user.UserId
            && !await _authorizationService.AuthorizeAsync(_httpContextAccessor.HttpContext.User, StandardPermissions.SiteOwner))
        {
            return null;
        }

**Comment by Piedone** [comment]
Yes, the issue, as described originally, is fixed:

https://github.com/user-attachments/assets/269e8549-31a5-4e4f-969c-cb0b46e2d44d

What you're talking about is something different: if I understand correctly, you don't agree that only users with roles possessing the Site Owner permission should be able to change their own roles. Please open a new issue for this, with the details and rationale you elaborated above.

**Comment by mvarblow** [comment]
Yes, I don't understand why we would fix it for a site owner but leave it broken for other admins. I've created a new issue.
