### ISSUE TITLE
Setup Password Validation

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrchardCMS/OrchardCore#898]
Entering a password without a special character (i.e. non-matching criteria) does not provide any user feedback. The 'strength' indicator? is Amber - but apart from this, nothing is presented to the user to indicate the reason that no action is performed when clicking on 'Finish Setup'.

**Comment by sebastienros** [comment]
Hover the password and there should be a tooltip appearing with the restrictions. If it's not already the case we should display them right after the inputs.

**Comment by GadgetGeekUK** [comment]
It would be good to have them displayed after the inputs. If you type and tab between fields you don't have any indicator that something has gone wrong.

**Comment by Hazzamanic** [comment]
Do we really need these arbitrary password rules for setting up a tenant? I know some archaic business practices demand convoluted password rules and they should be free to cripple their registration system with them, but the default tenant creation doesn't need that

**Comment by sebastienros** [comment]
@Hazzamanic it was discussed during a meeting, and there are two reasons:
- Users will ultimately set admin/admin otherwise, and never change it. Not our responsibility but will prevent PR issues when sites get hacked because of this, like Orchard doesn't impose strong passwords ...
- The Indentity library will impose a default set of rules when the user object is created. So we either remove any constraint or display these and enforce these rules when creating any user, even on setup.

**Comment by Hazzamanic** [comment]
Fair enough, thanks for the explanation.

**Comment by agriffard** [comment]
Here is a blog post that explains how you can configure these options : http://www.ideliverable.com/blog/how-to-change-the-password-requirements-for-orchard-core-sites
