### ISSUE TITLE
Ordering of list items in Admin when managing content items

### ISSUE THREAD

**Issue by jameshollyhomes** [OrchardCMS/OrchardCore#9018]
### Describe the bug

In build rc2-15500 you had the ability to reorder list items within a content item.  the cross arrows appeared and you were able to move items up and down.

I am not sure what build this happened in but if i get rc2-16037 the cross arrows for reorder no longer exist.

### To Reproduce

1. Create a Basic Orchard App in VS targeting OrchardCore.Application.Cms.Targets rc2-15500
2. Create a Blog site from the blog recipe
3. Go to the admin, Content Types and Edit the Blog content type
4. Edit the List Part and Enable Ordering
5. Add one more blog post
6. You will see the cross arrows for reordering
7. Change the Target of  OrchardCore.Application.Cms.Targets to rc2-16037
8. You no longer see the cross arrows

### Expected behavior
To see the cross arrows and be able to reorder

**Comment by jameshollyhomes** [comment]
Further investigations reveal it was working in rc2-15948 but was broken in rc2-15949.

**Comment by Skrypt** [comment]
19 days ago which resumes it to these commits.
![image](https://user-images.githubusercontent.com/3228637/113183922-9a49c000-9222-11eb-807e-b1ace51d8c63.png)

**Comment by Skrypt** [comment]
Ok the issue is related with the Fluid 2.0 PR. https://github.com/OrchardCMS/OrchardCore/commit/1f581a14a1f37d0105d93331a83d87e3c4bc310a

**Comment by jtkech** [comment]
And it is a ZOD ;)

Meaning nohing has been added

First i thought about another issue i fixed recently about the messages zone that was rendering only one message, because when 1rst adding a shape to a ZOD it create a new real zone, so before adding other shapes in a loop we first need to retrieve the newly created zone, which can be done easily as it returned by the `.AddAsync()` method.

But looking at the code and trying it, just saw that we just need in a razor file to replace an old `.Add()` by a `.AddAsync()`

I will do a PR soon

Need to see if there are other places with the same problem, if so not so many i think

Just saw another place, will fix it soon

**Comment by Skrypt** [comment]
ZOD is a vilain 😄 

![image](https://user-images.githubusercontent.com/3228637/113201631-b99f1800-9237-11eb-9713-09753d913caa.png)

**Comment by jtkech** [comment]
Yes, but here it is not because of it ;)

Just need to replace some remaining `Add()` to `AddAsync()` in some razor views
