### ISSUE TITLE
Exceptions when using foreign language taxonomy as tags

### ISSUE THREAD

**Issue by MehranDHN** [OrchardCMS/OrchardCore#9025]
### Describe the bug
It seems there is a restriction when using taxonomy tags where the user is not allowed to use Unicode foreign language text.
Suppose I want to tag some content with (**متون کهن**) and use that to categorize my content.
As you can see in the screenshot using them in both Category and Tags raises an exception in View/Preview.

### Screenshots
![image](https://user-images.githubusercontent.com/9722881/113139401-4cda4c80-923c-11eb-95d2-c4a9a2c04f93.png)

![image](https://user-images.githubusercontent.com/9722881/113139845-df7aeb80-923c-11eb-8792-8b6af6a35d15.png)

**Comment by jtkech** [comment]
Yes we already had this issue since a recent aspnetcore patch that may affect any hosted app of any OrchardCore version

We did a fix recently but only for the last dev branch available from the Cloudsmith package feed

Regarding the line 101 of `ViewBufferTextWriterContent` in the trace, it seems that this is not the last dev but an older dev version or the master branch available from the Nuget package feed.

**Comment by Piedone** [comment]
This seems to be fixed, then. Please reopen if you still encounter it.
