### ISSUE TITLE
Show technical name of a Content Type

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#9035]
### Is your feature request related to a problem? Please describe.
We often rename the Display Name of a Content Type and make a mistake afterward on it's technical name.
It is not displayed on the Content Type edit form anywhere else than looking at it's element created in the Parts section to reorder it's fields.

### Describe the solution you'd like
I think we should display the Display Name in the Parts list to be consistent instead of the technical name if possible. We should also display the technical name somewhere in the hint of the Display Name input.

/cc @agriffard

**Comment by KshitizGIT** [comment]
Hi @Skrypt ,
I made some changes to the code to make the output look like this. Instead of adding hint for the Technical Name, I added is as a readonly field, to make it consistent with the edit page of Content Part.
![contentpart](https://user-images.githubusercontent.com/8330582/118374060-d1f5a700-b5d9-11eb-9693-3260452b711d.PNG)

If this is what you suggested, I can send in the PR..
