### ISSUE TITLE
Razor dynamic compilation should be off in Production

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#9045]
A memory dumps shows that it's still on.
It should be on only if in Development. (independent from debug/release)

**Comment by sebastienros** [comment]
@jtkech one for you. Assigned to 1.0 as it's using memory for nothing otherwise.

**Comment by jtkech** [comment]
@sebastienros 

Normally this is already the case

Are you sure that the `ASPNETCORE_ENVIRONMENT` env var was not set to `Development`?

I will check it

**Comment by sebastienros** [comment]
```
2021-04-02 16:48:22.0066|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://localhost:5000
2021-04-02 16:48:22.0066|INFO|Microsoft.Hosting.Lifetime|Now listening on: https://localhost:5001
2021-04-02 16:48:22.0066|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2021-04-02 16:48:22.0066|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2021-04-02 16:48:22.0066|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\temp\code\orchard_a\orchardcore\src\OrchardCore.Cms.Web
```

**Comment by jtkech** [comment]
Okay, i'm checking it

**Comment by jtkech** [comment]
Yes, now i remember a little and i already thought about the fact

That currently before registering the related services we only check that the `refs` folder exists

But if in Production, normally no runtime complation happens for module embedded views, unless you have some app level views and the option to output the `refs` folder.

And because at some point we wanted to still allow app level views to be runtime compiled, even if in production but still depending on the app level project properties

But this was when the runtime compilation was the default, which is no more the case

So i will do a PR to also check `IsDevelopment`

**But can you show me what in the memory dumps shows that it's still on.**

Maybe some changes in net5.0 that now trigger some runtime compilation stuff.

**Comment by jtkech** [comment]
Yes, before `PreserveCompilationReferences` was set to true by default which is no more the case

So we added in the web app project file (so that people don't have to think about it)

    <PreserveCompilationReferences>true</PreserveCompilationReferences>

So for now to prevent any razor compile stuff, we can control this by using

    <PreserveCompilationReferences>false</PreserveCompilationReferences>


but yes, because of the new default behavior, better to also check `IsDevelopement` for the related service registrations
