### ISSUE TITLE
ImageSharp memory usage

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#9060]
https://github.com/SixLabors/ImageSharp/discussions/1590

@deanmarcussen @jtkech Are we using a single ISW configuration instance, in which case the same pools are shared across tenants?

**Comment by deanmarcussen** [comment]
I would say we have not designed it that way.

But I would need to look because I have a feeling this is, under the hood, a static configuration of IS itself, rather than ISW

**Comment by jtkech** [comment]
What i can see is that we use

            options.Configuration = Configuration.Default;

And there is this
https://github.com/SixLabors/ImageSharp/blob/bb727699686cba9cf55b67c5b114bb45311e6f3f/src/ImageSharp/Configuration.cs#L24-L30

        /// <summary>
        /// A lazily initialized configuration default instance.
        /// </summary>
        private static readonly Lazy<Configuration> Lazy = new Lazy<Configuration>(CreateDefaultInstance);

And this
https://github.com/SixLabors/ImageSharp/blob/bb727699686cba9cf55b67c5b114bb45311e6f3f/src/ImageSharp/Configuration.cs#L54-L57

        /// <summary>
        /// Gets the default <see cref="Configuration"/> instance.
        /// </summary>
        public static Configuration Default { get; } = Lazy.Value;

**Comment by deanmarcussen** [comment]
Related https://github.com/OrchardCMS/OrchardCore/issues/7826 but the op never replied to any questions so :(

Looks like maybe we should introduce a background task to regularly clear the pools

**Comment by mariojsnunes** [comment]
I'm finding an issue pointing to a memory leak.

These tests were done on a P1V3 Azure Linux App Service which I think is x64.
My Orchard is setup with Azure Media on a Blob Storage private container.

![image](https://user-images.githubusercontent.com/8073622/116271694-20045100-a778-11eb-9a32-a668f4acedfb.png)
On **(1)** and **(2)** I did around ~800 image requests which caused steep increases of memory.

The absolute value of memory increase was **~1GB** while the sum of image sizes is around **~380MB**.

On **(2)**  you can see where I retried the 800 requests after cleaning up browser cache, the memory increased again and hit 97% and went down after (in my experience, it never records hitting 100% because the app restarts) 
Although this is strange because site didn't notice it becoming unavailable, if it fully restarted I think the memory would go down even further. Maybe it has a different behavior because of Linux or .net core or both.

I'll be reading up on the source code next, update if I can find anything suspicious.

**Comment by mariojsnunes** [comment]
Okay I did some more testing...
The image requests I'm experimenting have this querystring:
?ranchor=center&rmode=pad&width=180&height=180

![image](https://user-images.githubusercontent.com/8073622/116293860-336ee680-a78f-11eb-97db-d5376a97a44e.png)
1. 800 image requests - memory increase.
2. 800 image requests again - memory increased and then decreased without app service restart.
3. a few more 800 image requests, no memory increase (cached?)
4. Purge cache
5. Image requests - memory increase
6. Image requests - App service ran out of memory and actually restarted this time (was unavailable for 2min and memory went down to 15%)
7. Image requests - memory did not increase! (cached?)
8. Purge cache again and Image requests - memory increase, then decreases automatically
9. A few more image requests, no memory change

I think it's very likely there is an issue when caching the images (maybe these streams are not being correctly deallocated?) https://github.com/OrchardCMS/OrchardCore/blob/1ec2e9898ff37e49d4224732c8a3e0acb5ed2fa6/src/OrchardCore.Modules/OrchardCore.Media/Services/MediaFileStoreResolverMiddleware.cs#L90-L93

But what's so strange is that even after the first request, it increases the memory again like it's caching a second time... and other times there is no memory increase.
And another time as seen on 8. it reduced the memory automatically...

Are there any other tests you want me to run?

**Comment by deanmarcussen** [comment]
Probably the thing to establish here is whether there is an issue with the blob storage cache, or ImageSharp.Web

When you say 
> Purge cache

I am guessing you mean you purged the blob storage cache?
Doing this essentially changes all the file dates (as they are the date the blob cache image was written), so causes ImageSharp.Web to see them as new images, which causes resizing of these new images.
So by purging the blob cache you would be in effect purging two caches, or at least forcing a resize.

To establish if we need to look at the issue in the blob cache, really the test would be to see what happens without it, i.e. not using blob storage, but using the default file system storage. 

I don't know if you are able to test that, but it would at least help point in a direction.

Side Note: Normally with ImageSharp we see `OutOfMemory` exceptions (azure windows, not linux containers), and failed requests, when trying to process too many images at once, rather than what you are describing of actually bringing down the server. It might be useful to see what your logs are reporting.

**Comment by mariojsnunes** [comment]
By purge cache I mean cleaning the ms-cache tenant folder (which lives on the App Service FileSystem), by clicking here:
![image](https://user-images.githubusercontent.com/8073622/116410996-31f3fb80-a82d-11eb-96b3-1aa43f26f059.png)

This is the only exception I see during the testing periods:
SixLabors.ImageSharp.UnknownImageFormatException
Don't think it's related...

I'll update after doing a few more tests.

**Comment by deanmarcussen** [comment]
Other suggestion is to do a test without resizing the image, ie no query string

that would help isolate whether it is related to resizing or the cache middleware

**Comment by mariojsnunes** [comment]
Yeah, so still with the same setup as before, but without resizing, I see no memory changes, even after multiple purges and retries.
Still need to test the resizing without blob storage.
But it's looking like an ImageSharp resizing memory leak.

**Comment by sebastienros** [comment]
We opened an issue with the size of the buffer pool that IS is using. Might be related. Not a "leak", but maybe trying to allocate some buffer under load while no more memory is available.

Or maybe the pool can't share the buffer and there is no locking mechanism, so all the thread try to get a buffer. If you were querying the same url, some code from Dean should have prevented it. Now in the other case, there might be an issue, that a site could be taken down. We might need to add a semaphore to prevent too many images from being resized concurrently.

**Comment by deanmarcussen** [comment]
Tracked down inside ImageSharp. Fix will not be long
