### ISSUE TITLE
Search Broken?

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#9150]
I upgraded one of my Orchard Core websites to a recent development release a couple of days ago and search stopped working. In particular it looks like the templates for `Search-Form.liquid` and `Search-Results.liquid` are no longer being rendered, but I haven't had time to investigate it deeply. I also noticed that I am getting errors in the backend when I attempt to add or edit a Lucene Index, but I'm not worried about that at the moment.

Interestingly enough, when I run OrchardCore.CMS.Web (.NET5) from the source code using The Blog Theme and navigate to ~/search, it displays nothing (although I can add and edit indexes). I believe this used to display the search form and search results. I verified the search index and permissions are properly configured, but the route just doesn't display the search form or search results.

Reproduce

I start with no App_Data folder.

1. Navigate to src/OrchardCore.Cms.Web
2. `dotnet run -f net5.0`
3. Setup using The Blog Theme and Sqlite
4. Navigate browser to "search" and see nothing is displayed

I don't see anything in the documentation that says search is any different. Am I missing something simple?

Thanks!

**Comment by Skrypt** [comment]
I'd say something is wrong starting from this step :  
https://docs.orchardcore.net/en/dev/docs/guides/implement-fulltext-search/#third-step-configure-search-settings

You either don't have any index field associated to the Search form or no index at all.
Also, you need to have at least added some FullText settings on a content type if your settings are set to Content.ContentItem.FullText field.

**Comment by davidhayden** [comment]
The Blog Theme Recipe sets all that up, but as mentioned, I verified everything was setup correctly.

I don't think it's a configuration issue.

**Comment by agriffard** [comment]
After creating a tenant and configuring the indexing on blogpost, rebuilding and debugging it, I can see that the model returns a Result with items but I confirm that the SearchForm and SearchResults are not rendered. (calling url `/search?Terms=man`)

Even if I add `{{ Model.Terms }} ` in TheBlogTheme\Views\Shared\Search.liquid, nothing appears.

if I add `{{ Model | json }}`, it returns:
`{"Terms":"man","SearchForm":{"Terms":"man","Metadata":{"Type":"Search__Form","DisplayType":null,"Position":null,"Tab":null,"Card":null,"Column":null,"PlacementSource":null,"Prefix":null,"Name":null,"Differentiator":null,"Wrappers":[],"Alternates":[],"IsCached":false,"ChildContent":null},"Position":null,"Id":null,"TagName":null,"Classes":[],"Attributes":{},"Properties":{},"Items":[]},"SearchResults":{"ContentItems":[{"ContentItemId":"411j7vxa410pf7z65hfrw51xdd","ContentItemVersionId":"4gwqn8xb4dvtj75j0dx5v1mn46","ContentType":"BlogPost","DisplayText":"Man must explore, and this is exploration at its greatest","Latest":true,"Published":true,"ModifiedUtc":"2021-04-12T20:50:11.9623995Z","PublishedUtc":"2021-04-12T20:50:11.973173Z","CreatedUtc":"2021-04-12T20:50:11.9623608Z","Owner":"483nv4za1m3mw2h1wjc7e7hm42","Author":"admin","TitlePart":{"Title":"Man must explore, and this is exploration at its greatest"},"ContainedPart":{"ListContentItemId":"4gtznwgzer3zm6z6w0v0h4v5xm","Order":0},"MarkdownBodyPart":{"Markdown":"Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.\n\nScience cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.\n\nWhat was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.\n\nA Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.\n\nFor those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us."},"AutoroutePart":{"Path":"blog/post-1"},"BlogPost":{"Subtitle":{"Text":"Problems look mighty small from 150 miles up"},"Image":{"Paths":["post-bg.jpg"],"MediaTexts":[""],"Anchors":[{"X":0.5,"Y":0.5}]},"Tags":{"TermContentItemIds":["4zhfm33wj7c7ez3vdw5k9w7bdq","4qtdmhf2xqgkgw97tww58z86w3","4q8sfpa9sfsjd780ryeyntjjwj"],"TaxonomyContentItemId":"43dep92f238j9wm8np3rtbzhwh","TagNames":["Earth","Exploration","Space"]},"Category":{"TermContentItemIds":["43x4cvtswq1c7vv965sep9bvcm"],"TaxonomyContentItemId":"48rer99gx458nr3gzn924y2cwn"}}}],"Metadata":{"Type":"Search__Results","DisplayType":null,"Position":null,"Tab":null,"Card":null,"Column":null,"PlacementSource":null,"Prefix":null,"Name":null,"Differentiator":null,"Wrappers":[],"Alternates":[],"IsCached":false,"ChildContent":null},"Position":null,"Id":null,"TagName":null,"Classes":[],"Attributes":{},"Properties":{},"Items":[]},"Pager":[],"ContentItems":null}`

**Comment by jtkech** [comment]
Fixed on my side ;)

Yes, this is because now we don't register the access strategy of each model type automatically on the fly.

So we need to register them explicitly and the search view models are missing

Will do a PR soon

**Comment by agriffard** [comment]
If `Model.SearchResults` has no results, it is not rendered at all so it does not render the `There are no such results.` in Search-Results.liquid. Ex: when the search form is empty.

**Comment by Skrypt** [comment]
Probably null handling has changed.

**Comment by jtkech** [comment]
@agriffard 

Just tried it works as expected when you input at least one term that is not found, you get `There are no such results`.

When you don't input any term, this is in the controller that we only return the form shape, not the result one.

            if (string.IsNullOrWhiteSpace(viewModel.Terms))
            {
                return View(new SearchIndexViewModel
                {
                    SearchForm = new SearchFormViewModel("Search__Form") { },
                });
            }

Maybe the logic is wrong but if you don't input anything it would mean that you search nothing

At least it works as before, so the search is no more broken

Maybe a separate issue requesting to display that there is no result when you search nothing.

**Comment by Skrypt** [comment]
Form validation simply yep
