### ISSUE TITLE
Non draftable items should display the unpublish button

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9162]
The unpublish button is visible and can be used for types that are not draftable. This button should be hidden.

**Comment by Skrypt** [comment]
I think it is fine. When you unpublish a Content Item that is not versionable it will unpublish the current Content Item without creating a new version of this Content Item. So, if you unpublish it, it's fine, else you would require to delete these content items to unpublish them from the website. Here unpublishing a content item doesn't create a new version of the Content Item unless I'm wrong. So, where is the issue? Can you explain your use case and why unpublishing a non-draftable Content Item might become an issue?

**Comment by jptissot** [comment]
It's not an issue but I just assumed that an non draftable item should not have a button to make it a draft. Even if we know there are other ways to do this (scripting, workflows) that would not be enforced. I just found it counter intuitive.

**Comment by Skrypt** [comment]
So, if unpublishing a Content Item that is non-draftable makes a new ContentItemVersionId I agree, else it's not an issue.

**Comment by jtkech** [comment]
As i remember the version records of a non draftable items are managed internally in the same way as others

The main difference is that when editing a non draftable there is no button to save it as a draft, only a publish button, so even if they are managed internally in the same way, e.g. when you edit it we create a new temporary draft version that is then published when we click on publish, the result is that normally **you only have one active version that is published**.

So because you can't save a non draftable item as a draft, makes sense that you can't create a draft active version by unpublishing the currently published active version

**Comment by Skrypt** [comment]
What if I want to still be able to unpublish a content item then? Should we have another Content Item state in that case? Something like published = 0, latest = 1. Then the item would be marked as a "draft" but it's just the same content item but marked as unpublished ...

**Comment by jtkech** [comment]
> What if I want to still be able to unpublish a content item then?

Yes i agree, you would have to delete it ;)

Hmm finally, non draftable is just that we don't suggest a save as draft button while editing, but still allowing to unpublish an active published version that you are able to re-edit and then re-publish

So i would let it as it is

**Comment by Piedone** [comment]
Let's go with JT's opinion.
