### ISSUE TITLE
Roadmap up to date?

### ISSUE THREAD

**Issue by thierholzer** [OrchardCMS/OrchardCore#919]
Is this still on schedule for Sept 2017? Just curious. Thanks!

**Comment by sebastienros** [comment]
I am currently looking for bugs for beta. Testing, demoing, ... so that the obvious issues are found before releasing it. Others are finalizing some PRs, like dotnet core 2.0, liquid templates, user management and bootstrap beta. They are all currently being reviewed. I am confident we are shipping something before September.

**Comment by pgy866** [comment]
Expect Orchard2 very much! Is an exciting thing

**Comment by pgy866** [comment]
Is it on time? Before September? Countdown Remaining 8 days Very much looking forward to

**Comment by 0liver** [comment]
@pgy866 September has 30 days, so there are really 38 days left to be on schedule.

On a side note: I don't think putting pressure on people is the best thing to do when they are trying to get their work done ;-)

**Comment by pgy866** [comment]
very sorry! Just expect the waiting time one day just like January! I have no ill intentions! Very looking forward to the new orchard2, I am a user! Not a developer! But I'm not programming! Ok! We still quietly look forward to the perfect orchard2 release it! I believe! It is wonderful!

**Comment by sebastienros** [comment]
Count down is on, 7 days to go ...

**Comment by Jetski5822** [comment]
Should we all have a get together on Skype before we release.... issues, etc?

**Comment by sebastienros** [comment]
@Jetski5822 yes, and you don't need to comment on github for that ;)

**Comment by Jetski5822** [comment]
Do what I want :)

**Comment by pgy866** [comment]
This is a very exciting! Thank you! To all orchard 2 developers! You are so hard! Thank you! You are the best!

**Comment by six006** [comment]
2017.9.1

**Comment by pgy866** [comment]
Very exciting moments,Whether it will come today？？2017.09.01

**Comment by sebastienros** [comment]
Status update then.
I have merged all the branches that could make it for beta and were necessary. Everything works as expected.

Here is a todo list in order to ship
- Rename packages to OrchardCore and remove usage of Microsoft.*
- Change version to 1.0.0-beta1-xxxx
- Rename Github repository to OrchardCore (instead of Orchard2)
- Update CREDITS of open source technologies we are using
- Use all our dependent packages on Nuget.org

Not much coding, just making it look nice.

Then we'll probably do some little more testing and release some blog posts and announcements.

**Comment by pgy866** [comment]
First of all very grateful,
Careful reply,
Want to wait is beautiful!
Can be measured as soon as possible,
Can be better found BUG,
Very much looking forward to that moment.。。。。。。
Specific release time can not be determined too many factors,
I will pay attention to you

**Comment by pgy866** [comment]
Somewhat sad, roadmap RC version is still far away
