### ISSUE TITLE
FluidTagHelper reuse of buffers

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#9209]
This code seems to use the same `ViewBufferTextWriterContent` twice which would throw an exception.

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/Tags/FluidTagHelper.cs#L89-L97

Either the code is wrong, or the buffer should me materialized first. Ideally we should understand how the TagHelper is working hre and add a comment.

**Comment by jtkech** [comment]
Okay maybe just a mistake or a good reason i don't remember ;)

 i will check it

**Comment by jtkech** [comment]
So i checked that the `WriteTo()` of our `ViewBufferTextWriterContent` was not called twice, i could repro (but only by using breaking points) the `Has already been rendered` issue, the same i fixed in our `DynamicCacheShapeDisplayEvents` for shapes where we now set the shape child content with an `HtmlString` if already processed for caching.

Looking again at the mvc source code, it seems that this is when we call `ProcessAsync` on a given tagHelper that it calls `GetChildContentAsync()` that calls our delegate, and then this is this tag helper that updates (or not) the `TagHelperOutput.Content`, as our script tag helper does

So i removed line 96 and 108

    tagHelperOutput.Content.AppendHtml(content)
    ...
    tagHelperOutput.WriteTo(writer, (HtmlEncoder)encoder);

And kept line 93 and 106

    outputAttributes, (_, e) => Task.FromResult(new DefaultTagHelperContent().AppendHtml(content))

    await tagHelper.ProcessAsync(tagHelperContext, tagHelperOutput);

**Seems to work as before, i will do a PR**

Also saw that we now have

    o.LiquidViewParserConfiguration.Add(parser => parser.RegisterParserBlock("scriptblock", ...));
    o.LiquidViewParserConfiguration.Add(parser => parser.RegisterParserBlock("styleblock", ...));

But still have

    RegisterParserBlock("scriptblock", ..., (list, ...) => FluidTagHelper.WriteToAsync("scriptblock", ...));
    RegisterParserBlock("styleblock", ..., (list, ...) => FluidTagHelper.WriteToAsync("styleblock", ...));

I will remove the last registrations in the same PR
