### ISSUE TITLE
Pressing Enter on recipe combo box item resets focus

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#9289]
### Describe the bug
When you move the focus from site name to recipe combo box and press `Arrow Down` the recipe list pops up. But when you commit your choice via `Enter` focus resets to the first item on the page.

### To Reproduce
1. Open Setup
2. Press `Tab` to move to recipes combobox
3. Press `Arrow Down`
4. Choose any item and press `Enter`

### Expected behavior
Focus stays on the combo box

**Comment by agriffard** [comment]
@sebastienros To answer your question about the Bootstrap dropdown and the ability to go the next element by pressing `Tab` once you selected a recipe (without pressing Enter): It does not seem possible because the `Tab ` button allows to navigate between the options inside the dropdown menu when displayed.
