### ISSUE TITLE
SetHomepage option doesn't update flag

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#9292]
I wanted to use content menu items and discovered that if I pick the page wich is set as homepage, the link is not "/" but the actual generated link from the title field.
So I thought, I'll add a check inside the template myself and therefore change the link, if the SetHomepage flag is true.
The problem is, that this flag is never true, even if the page IS the homepage, the link "/" is working and it is checked in the admin.

Example:
![image](https://user-images.githubusercontent.com/1375119/116241366-20dfb780-a765-11eb-9499-7d24c1f0caaf.png)
![image](https://user-images.githubusercontent.com/1375119/116241432-2b9a4c80-a765-11eb-9750-d9139844480c.png)

So two problems:
1.) Flag is not updated
2.) Content menu item is using the wrong link when the homepage is selected

Problem 2 is maybe resolved by fixing problem 1.

OC Version: RC2-16145

**Comment by deanmarcussen** [comment]
The flag is not a maintained value.

You need to check the site settings for the home route value

(the problem would be that if the value was maintained then when the home route changed two content items would have the flag set)

That being said, I couldn't repro problem 2, that the wrong link is used when an item is the home page.

**Comment by Flarescape** [comment]
Ah, is see, that makes sense!
Thanks for the quick clarification!

I'll compare my content menu item template with one of the predefined themes, even if I've copied it from there some time ago.

**Comment by Skrypt** [comment]
One thing though that we should have done since a while is allowing to change the values of the home route from the admin UI. Probably something in the General Site Settings that could be used to change the current values.

**Comment by Flarescape** [comment]
Ok I've checked it and I'm using the exact same views as the ones in the agency theme for content menu items.
Maybe it's just on my side, but display_url outputs the generated URL, even if it's the homepage.
So it's not `/`, it's `/xyz`, if the title is XYZ.

@Skrypt In this specific case, it wouldn't help that much, but in general it's a great idea and should be an easy one to implement.
Maybe just a "Home Route" autoroute/url field in the General Site Settings, as you have said, would do it.

**Comment by pierslawson** [comment]
I stumbled across this issue with a site based on the Agency Theme as well. For me it manifested itself with the SEO tags being genertaed using the full URL rather than the home page URL as mention in this discussion:

https://github.com/OrchardCMS/OrchardCore/discussions/11901

Would love to know how to get the right URL out!

**Comment by dsghi** [comment]
> One thing though that we should have done since a while is allowing to change the values of the home route from the admin UI. Probably something in the General Site Settings that could be used to change the current values.

This would be a very nice feature; somehow, we deleted the homepage content item, and ticking the 'set as homepage' option on a new item isn't working, and we're stuck without a homepage. We used the nuclear option to restore from a backup without an easy way to change the setting. @Skrypt I realize this is a very old issue; what are the odds a UI setting will find its way in somewhere?

**Comment by Flarescape** [comment]
Also the issue still exists in OC1.6. so that you have two URLs for the Homepage.
This is especially a problem with the Sitemap Module, because the Homepage gets two entries as separate pages and is therefore counted as duplicate content by Google.
Also the original URL of the site always shows up as redirected to the "/" Homepage-URL in various SEO Tools, which negatively impacts the rating of the site.

**Comment by Skrypt** [comment]
Yes, this issue has been left here because in 01 we had a feature "Alias" that was used to set these manually. But I believe that in OC we have a site setting for the HomePage and it can be replaced by an MVC route manually in the DB. This is not optimal at all, I agree. We would need a PR from someone that has time to work on it. Up for grab guys. 😄

**Comment by jtkech** [comment]
Just tried the `HomeRoute` feature, I could made any item of any type the `homepage` (if the autoroute part settings allow it), about generated url it works if the right mvc helpers are used, so that not only our custom `AutorouteValuesAddressScheme` but also `HomeRouteValuesAddressScheme` are used.

For example if you have a menu where you still uses a `Link Menu Item` (which is recommended for perf) where the url is specified manually, it "doesn't work", but if you use a `Content Menu Item` it works.

If the `homepage` is lost, you can set any other item to be the `new homepage` (if the autoroute part settings allow it). So for now on my side all is working as expected.

Yes, the `homepage` has 2 working urls but just tried a sitemap related to 3 `Article` content items: About, A1 and A2. If I make A1 the homepage, the sitemap still includes `/about` and `/a2`, then `/` not `/a1`.

**Comment by hishamco** [comment]
Is that mean we should close the PR :)
