### ISSUE TITLE
Content fields on named parts are not indexed in SQL

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#9444]
### Describe the bug

Content field values are not indexed if those are attached to a content part used as a named part on a content item. Fields attached directly to the content type, however, are indexed as expected.

### To Reproduce

Prerequisites: Make sure SQL field indexing feature is enabled.

1. Go to Admin UI > Content > Content Parts
2. Create a Content Part and edit it
    - Set Reusable to true
    - Add some field (e.g., a TextField)
    - Save
3. Go to Admin UI > Content > Content Types
4. Create a Content Type and edit it
    - Add a named part using the content part you've created previously.
    - Add a content field to the content type directly for observing proper indexing for this field
    - Save
5. Create a content item using the type you've previously created
    - Set the two field values you've attached: the one from the named part and the other one attached directly to the type
    - Save
6. Open SSMS / DB Browser for SQLite depending on the database type.
    - Open the related index table (e.g., TextFieldIndex)

### Actual result
Observe the field value on the named part is not indexed, however, the one attached to the type directly is properly indexed.

### Expected behavior
The field attached to the named part should be indexed. The ContentPart value should be the name of the named part.

**Comment by Skrypt** [comment]
Probably in the same spirit of the existing module but as a feature of that module. Indexing these records fills up the database quick. It's always better to have custom indexing providers per content type / content part so that it can be fine tuned. Not against the idea, I think it would be a good addition. This and other suggestions that has been made over time for this module. We should probably tag the issues about this module and regroup the ideas.
