### ISSUE TITLE
Content Items created inside BagPart are not listable.

### ISSUE THREAD

**Issue by KshitizGIT** [OrchardCMS/OrchardCore#9471]
I created a content type called "Skill" that is  Creatable and Listable. Then I created another ContentType called "Person" in which I added a BagPart. In the BagPart, I added Skill as a allow content item..

Now, I create a "Person" content item and add some "Skill" content item from the "Person". These "Skill" content items are not listed via the "List" button of Content Type.

**Comment by deanmarcussen** [comment]
Items contained in a bag part are considered `Contained` items, and as a result are not listed in the UI.

The UI only lists parent items which can, in this case, contain other items.

If you want / require listable items, rather than items which are bagged into a primary content item, you may prefer the `ListPart`

**Comment by KshitizGIT** [comment]
Thanks, that makes sense. Thus closing the bug.
