### ISSUE TITLE
SQL Queries : support JSON functions

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#9480]
I'm pretty sure we could implent this as a common method for every DB as they all support it and they are quite similar.

/cc @lampersky

**Comment by lampersky** [comment]
If you are using db like **SQL Server**, **MySQL >= 8** or **Oracle** then you could use JSON functions right away.
The problem is with [postgreSQL](https://www.postgresql.org/docs/9.5/functions-json.html), where the syntax is a bit odd and differs from other db engines.

This feature request is more about extending **YesSql** by adding some additional **TemplateFunction**s, because from **OC** point of view everything is ready to support them (**SQLParser** and **SQLDialect**).

Here is an example (SQL Sever):
![image](https://user-images.githubusercontent.com/6403130/118766901-574cb600-b87d-11eb-91a0-f485c0e96655.png)

**Comment by lampersky** [comment]
@Skrypt I've added support for those functions:
- JSON_VALUE,
- JSON_MODIFY.

I've tested them with:
- PostgreSQL 13.2,
- MySQL 8.0.23,
- SQL Server 12.0.2000.8 and SQL Server 15.0.4102.2,
- SQLite 3.33.0.

It would be good to add support for **ISJSON** too, but to be honest I'm not sure how to add **postgreSQL** equivalent without custom **plpgsql** function :-P

https://github.com/sebastienros/yessql/pull/392

**Comment by Skrypt** [comment]
All good. Thank you, will review it.

**Comment by RockNHawk** [comment]
A related issue: Auto transform Query Expression to SQL JSON Query with Document table https://github.com/OrchardCMS/OrchardCore/issues/6096

**Comment by jersiovic** [comment]
Entity framework now also supports sth like that https://twitter.com/ajcvickers/status/1580250088622153728?t=lL4E29lLpzMIEwimuwKd5A&s=19

It would be interesing yessql also support sth like this through Dapper, it will ease things when we want to optimice bulk changes in entities skiping to load data from db to make massive changes.

**Comment by Piedone** [comment]
So, this needs to be implemented in YesSql by https://github.com/sebastienros/yessql/pull/392. Otherwise, you can use the functions with MySql and SQL Server already.
