### ISSUE TITLE
Database is locked when call HTTP request via workflow and do DB operations.

### ISSUE THREAD

**Issue by MohitNaroliya** [OrchardCMS/OrchardCore#9560]
### Describe the bug
Database is locked when we call HTTP request Task via workflow with same solution API request. 
![image](https://user-images.githubusercontent.com/26460323/119803322-f9634280-befc-11eb-8bd0-f004abf5fb05.png)
![image](https://user-images.githubusercontent.com/26460323/119804101-ab027380-befd-11eb-83a2-e304c6804a98.png)

### To Reproduce
1. Create a content type and workflow..
2. Add content type update event in workflow and call HTTP request with same solution API. ![image](https://user-images.githubusercontent.com/26460323/119806653-07669280-bf00-11eb-92bf-1adfd4842d59.png)
4. Update content type item and see the console you will get database is locked error.

**Comment by jtkech** [comment]
Which version of OC and which database?

E.g. Sqlite doesn't support parallel writes, one process will have to wait for another one, that's okay if there are not waiting for each other for another "logical" reason, the first that begin the write will complete and then the other one is unlocked.

Does your Request activity triggers a database write? Hmm, maybe it is the same even if only one process do a write, the second may still have to wait even if it only do a read.

So here the problem seems to be that the Request activity belonging to a process A triggers a process B that will wait for the process A that did the update to complete and then commit its transaction, but because the Request activity is waiting for a response from process B, there is a dead lock because of this logical dependency introduced by the workflow.


That's why we have a feature that adds (if enabled) a CommitTransaction activity that you could use before the Request activity, but should be used with care, in place of using an Update event, you should use a Published and / or DraftSaved event, because with these 2 last events we know that all validations was already executed, so if one fails it ensures that the session is canceled before the commit activity.

**Comment by MohitNaroliya** [comment]
> Which version of OC and which database?
> 
> E.g. Sqlite doesn't support parallel writes, one process will have to wait for another one, that's okay if there are not waiting for each other for another "logical" reason, the first that begin the write will complete and then the other one is unlocked.
> 
> Does your Request activity triggers a database write? Hmm, maybe it is the same even if only one process do a write, the second may still have to wait even if it only do a read.
> 
> So here the problem seems to be that the Request activity belonging to a process A triggers a process B that will wait for the process A that did the update to complete and then commit its transaction, but because the Request activity is waiting for a response from process B, there is a dead lock because of this logical dependency introduced by the workflow.
> 
> That's why we have a feature that adds (if enabled) a CommitTransaction activity that you could use before the Request activity, but should be used with care, in place of using an Update event, you should use a Published and / or DraftSaved event, because with these 2 last events we know that all validations was already executed, so if one fails it ensures that the session is canceled before the commit activity.

**Comment by MohitNaroliya** [comment]
OC version - 1.0.0-rc2-16189
Database - SQLite.. 

Yes I tried to fix with CommitTransaction activity but getting same issue every time. 
Tried to CommitTransaction activity before calling HTTPS request and also after Request done but on both case getting same issue.

**Comment by jtkech** [comment]
Okay, i will try it this night but with the last dev (16256), and will let you know

**Comment by jtkech** [comment]
@MohitNaroliya 

Okay, just tried and i could repro

But then, adding the CommitTransaction activity, just before the Request activity, did the trick ;)

**Comment by MohitNaroliya** [comment]
@jtkech

Could you please provide an example which you tried?

**Comment by jtkech** [comment]
@MohitNaroliya 

From memory i used an updated event (Article type) and a request activity that was just doing a GET of the home page.

And then to fix the observed dead lock, i added a commit activity just before the request activity.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
