### ISSUE TITLE
Claims Argument Null Exception When Migrating Site

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#9641]
Attempting to migrate a website from RC2-15222 and received the attached error after upgrading to the latest source code in the Dev branch. Occurs when I "successfully" log in as an administrator. For completeness, also experienced another issue on the frontend as well (#9640). No place to go from here with both frontend and backend out of commission. Changed the framework to .NET5 as well if that matters.

Curious if this is expected. Nothing fancy about the user. Just a plain 'ol administrator account.

![claims-error](https://user-images.githubusercontent.com/96801/121252117-a632ad80-c875-11eb-9a95-a29dc97eeaa7.png)

**Comment by deanmarcussen** [comment]
@davidhayden this and your other issue look like a migration error.

See here for notes I wrote about upgrades
https://github.com/OrchardCMS/OrchardCore/issues/7206#issuecomment-796536006

Probably you need to check your log files, as another migration may have failed previously causing both the users and layers/ rules to fail during migration.

**Comment by deanmarcussen** [comment]
> 'OrchardCore.Users'. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table UserIndex has no column named IsLockoutEnabled'.

Yes, looks like an issue with that migration. I'll check it tomorrow if noone else gets there first.

Short term solution would be to back down the nuget packages by a week I imagine?

**Comment by deanmarcussen** [comment]
@jtkech I haven't had time to pr it, but will run what I think we need to do past you, in case you have a better idea.

Migration 7 is failing now, where it updates the User, because there are now new properties added in Migration 10, and of course the index provider being activated during MIgration 7 is expecting them.

I don't think we can rearrange the migration order, in a way that will be succesful for all of the various versions that may use it.

So I am think of moving guts of migration 7, i.e. the query and saves, into a deferred task, so it isn't run until all other migration steps have completed.

It's not ideal, so hoping for a better idea...

**Comment by jtkech** [comment]
@deanmarcussen

Looks like the same kind of issue we had with contents creation in a migration recipe and that we fixed by using a deferred task in the content step, here it's not about contents but users, not creation but updating, but same issue related to missing migration steps before doing some operations.

Yes, here step 7 would need to be still run last, maybe we could mark a step (or a set of steps) to be run last (if not yet done), but this is what a deferred task will do in its own scope, even more if needed we could think about a deferred task that uses a deferred task, so that we could define steps that run last and others that run very last, and so on.

So yes, here i think that using a deferred task, and still triggered by step 7, is the right thing to do.
