### ISSUE TITLE
Double click on publish button creates two published versions

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#9709]
Double click on publish button results in multiple published versions.

![db](https://user-images.githubusercontent.com/6403130/122376860-d27cb700-cf64-11eb-9cbd-af30e08665c9.png)

![result](https://user-images.githubusercontent.com/6403130/122376880-d6a8d480-cf64-11eb-9c00-fc8562cb3df8.png)

Other than that, sometimes I can find two records with same **ContentItemVersionId** in ContentItemIndex table.

![image](https://user-images.githubusercontent.com/6403130/122381583-60f33780-cf69-11eb-91f0-0b69f7d2d2db.png)

**Comment by lampersky** [comment]
First part of my issue seems to be similar to https://github.com/OrchardCMS/OrchardCore/issues/8900.

Duplicated **ContentItemVersionId** looks like something new.

**Comment by sebastienros** [comment]
Might need to add a Checkconcurrency option when saving the content items. And fix the issue that is mentioned, to prevent double clicks.

**Comment by jptissot** [comment]
Should this also be fixed on yessql side?

**Comment by deanmarcussen** [comment]
No the concurrency check option is already available in YesSql, it is just unused in Orchard Core for content items.

So needs enabling and testing (you can see how Users and OpenId use it)

**Comment by Skrypt** [comment]
I tried last night adding _session.save(contentItem, checkConcurrency = true) in the DefaultContentManager and it did nothing. Need to see how we do this with Users.

**Comment by deanmarcussen** [comment]
Because we are actually saving different documents (because different content item versions), for the most part it will do nothing.

But the issue listed above was related to the same version id being saved twice into the db, which means it comes from concurrent requests, editing drafts, so is likely a concurrency hit, on the same document, so would likely trigger the concurrency exception.

Where a draft is actually the same document record in the db.

If that makes sense?

**Comment by Skrypt** [comment]
See https://github.com/OrchardCMS/OrchardCore/pull/9725 that I just added and review if that makes sense. I did not commit this last night because after trying doing a double click the CheckConcurrency did not stop it to get created. Also, tried to modify the same content item concurrently in 2 different browsers and I never got a duplicate content item version id because we generate a new UUID everytime we create a draft so it is unlikely that we will get a duplicate ContentItemVersionId from 2 differents users trying to modify the same content item. The last save will win.
