### ISSUE TITLE
Add ability to provide title for images

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#9710]
### Is your feature request related to a problem? Please describe.
Image UI in admin panel does not allow to set image title

### Describe the solution you'd like
Popup opened from an image in admin panel has 2 fields: alt and title

1.0.0-rc-16300

**Comment by sebastienros** [comment]
Media Fields have an alt text already. The Assets page can't have one since it's just a file system wrapper. There is no metadata associated to the files. The recommended solution when you need to associate custom metadata to these files is to create a custom ContentItem with a media field and other fields like taxonomies, text fields, ... ( a Media content type?). Then reference these content items from other types instead of the asset directly.

**Comment by xperiandri** [comment]
So why can't we add one more field along with alt?

**Comment by sebastienros** [comment]
@xperiandri are you asking why as "custome fields" or as "predefined fields like alt text" ?

**Comment by xperiandri** [comment]
Predefined field

**Comment by sebastienros** [comment]
We only thought that "alt" was necessary for image tags. What does the title do? Is it just to be able to list image fields?
A mitigation could be to separate two values in the tag input and split it at rendering.

How would you justify media fields need a title and nothing else?
An existing extensibility is to use a custom "editor" that would expose more data stored with the field.

**Comment by sebastienros** [comment]
You can also create a custom part with a media field and other extra fields (like title) and reuse this part.

**Comment by xperiandri** [comment]
We thought the same until we got the requirements from SEO engineer. He asked to provide ability to set alt and title

**Comment by xperiandri** [comment]
Can we just modify the default editor?

**Comment by sebastienros** [comment]
You can change the default editor, you will still need to create a driver that handles the new input in the view.

**Comment by xperiandri** [comment]
Can we submit a PR with this change?

**Comment by deanmarcussen** [comment]
When we designed the extra text field for the MediaField we said, let's only put a single string array here, because there are many atttributes people may wish to use it for, and we cannot support them all.

If we add a title, people will then want a media profile property, or a width property, or...

The design and suggestion was, you can either use it simply as a string, or if you want extra attributes, choice your own seperator style (eg comma seperated, or I know of someone using json, because they want many things)

OR 

if you want a stronger editor experience the pattern is to use fields (predefined lists etc) with a content type and contain these inside a named BagPart.

Example: Currently for the last site, I need alt-text, caption, attribution, and date of photo. So there's no way I can put all these on a field, with a great editor experience. It's too much for a field, so as above, BagPart, and type.

So I don't think an extra field is a good idea.

What we could potentially consider is an attribute editor i.e named attributes, (but I think it is too much for the field, and better suited to type composition)
