### ISSUE TITLE
Add ability to switch language within admin panel

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#9720]
### Is your feature request related to a problem? Please describe.
Unless you have a language switcher on website pages you cannot switch a language in the admin panel

### Describe the solution you'd like
A dropdown button in admin panel header to switch languages

**Comment by jptissot** [comment]
@agriffard maybe we could render the ContentCulturePicker in the admin and add an Admin option to show / hide it.

**Comment by hishamco** [comment]
@jptissot what if the Content localization module is disabled, If I'm nor wrong this is should rely on localization not content localization

**Comment by sebastienros** [comment]
I agree it doesn't relate on content localization.

It's confusing though because we already display the admin using the aspnet culture selectors, and the admin reflect that already.
So here you'd suggest to add a picker that would override this setting and store it as a cookie. It should then display all the available cultures like in the Setup screen (not the content localization ones). And when no cookie is found it could show the current one by default (from the browser or querystring, via the aspnet culture selectors).

**Comment by sebastienros** [comment]
The cookie name should be different from the front-end.

**Comment by hishamco** [comment]
I will handle this, but this should go into `1.0.x` I think we already have an excellent and robust localization features and some need to be merge

I can put my hands on this if nothing else important

**Comment by hishamco** [comment]
@sebastienros I succussfully did a simplistic prototype for this one that I might share later, my question is why we need to list all the cultures in the selector instead of the supported one? The scenario in the setup screen is totally different because we didn't configure the supported cultures yet. That's why I think list the supported culture is the right option here

**Comment by sebastienros** [comment]
@hishamco makes sense
