### ISSUE TITLE
DistributedShellHostedService parallel tenant creation issue

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#9772]
We ran into an issue while using the DistributedShellHostedService when while testing multiple tenant creation on multiple servers which leads to server instances being out of sync.  

I think the problem is related to the line below as it doesn't take into account that server 2 may write out a shellCreatedId to Redis right before server 1 writes out its own.  When server 1 retrieves the value it will see its own value and not the one from server 2 so it won't know to actually reload the setting names.

```
DistributedShellHostedService.ExecuteAsync()
..
  // Check if at least one tenant has been created.
  if (shellCreatedId != null && _shellCreatedId != shellCreatedId)
..
```

**Comment by jtkech** [comment]
@ShaneCourtrille Thanks for the feedback

I would need more info on your envs / configs.

- E.g. you need that tenant specific settings / config sources use a shared storage, as the azure blob or a shared database, by configuring and using `AddAzureShellsConfiguration()` or `AddDatabaseShellsConfiguration()` in the main startup.

    https://docs.orchardcore.net/en/dev/docs/reference/core/Shells/index.html

- You also need that the `Default` tenant is already setup and (because of the above) that each server is aware of it, otherwise you would also need to use the `AutoSetup` feature configured for a distributed env.

    https://docs.orchardcore.net/en/dev/docs/reference/modules/AutoSetup/index.html

**Comment by jtkech** [comment]
@ShaneCourtrille 

That said maybe there is an issue in our logic.

> server 2 may write out a shellCreatedId to Redis right before server 1 writes out its own.

Yes but notice that at this point server 1 doesn't cache it in its `_shellCreatedId`.

> When server 1 retrieves the value it will see its own value and not the one from server 2.

Yes but normally because it is not yet cached it is not yet equal to the current `_shellCreatedId`, so it will reload the settings names that normally also include the one that has been created first by server 2. Note: Notice the local semaphore used for the atomicity of the local operations.

In fact, when a new `shellCreatedId` identifier is written, we do the same even if it is done by the local server, we don't cache it immediately, only when it is read from the main loop, this to take into account the new tenants. One rule being to capture an identifier before doing operations, so that if something happens in the meantime, we will see it by reading the next time a new identifier.

So it would mean that when reading a new identifier the related tenant would not be seen, but when a given server writes a new `shellCreatedId` to Redis, normally the related tenant settings have already been persisted. This assuming that the current tenant specific settings / config sources use a shared storage (e.g. blob or database).

So here the logic and how it is intended to work, but maybe there is still an issue, waiting for your feedback.

**Comment by ShaneCourtrille** [comment]
@jtkech We took another look at the code and realized the same thing.  I did some more investigation and found that we weren't using the AddAzureShellsConfiguration() or AddDatabaseShellsConfiguration() so we're retesting with that in place.  I'll close this issue once we've verified things work properly.  

Thanks!

**Comment by ShaneCourtrille** [comment]
Closed as we ended up going a different direction.  Thanks for the tenants description change as it makes more sense now
