### ISSUE TITLE
Theadmin.js cause drop-down menu needs to be clicked twice

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#9881]
All drop-down menus need to be clicked twice to display.
Block the request of theadmin.js in devtools can solve this.

### Screenshots
![image](https://user-images.githubusercontent.com/14150259/125071378-c57a6000-e0eb-11eb-9a4f-04842eb37d3b.png)
![image](https://user-images.githubusercontent.com/14150259/125071425-d5923f80-e0eb-11eb-9b51-4835db3c07aa.png)

**Comment by Skrypt** [comment]
I does that on very specific pages in the admin. Not all of them.

**Comment by EternityTeam** [comment]
So this is the expected effect. Using bootstrap select in my custom page is also affected. How can I avoid this feature?

**Comment by hishamco** [comment]
@Skrypt why it need to be clicked twice?

**Comment by Skrypt** [comment]
I don't know yet. Maybe some recent PR merge that does this. I removed the form double-click code I added recently to see if it was not that and it's not.

**Comment by jtkech** [comment]
Yes I confirm, just tried with the last dev with the dropdowns of the content items page

Oops maybe too late to fix it before the 1.0 release ;)

After a search on Google, it seems that most of the time this is because bootstrap.js is loaded twice.

In the dev tools I saw TheAdmin.js script which embeds bootstrap.js

    "inputs": [
      "node_modules/popper.js/dist/umd/popper.js",
      "node_modules/bootstrap/dist/js/bootstrap.js",
      "Assets/js/*.js"
    ],
    "output": "wwwroot/js/TheAdmin.js"

But I also saw before the bootstrap script explicitly as a dependency of bootstrap-select that we also use

            manifest
                .DefineScript("bootstrap-select")
                .SetDependencies("jQuery", "bootstrap:4.6.0")

But not sure, not yet tried
