### ISSUE TITLE
Content Item Version History view from admin

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#9884]
Hello @deanmarcussen 
Will the content item version history view from the admin be available soon on the dev branch ?
I saw you giving a glimpse of it in the audit trail demo.
I'd really like to use it instead of the full blown audit trail for viewing content item history.
Thanks
Yiannis

**Comment by hyzx86** [comment]
If you have problems with rendering older versions of shapes, it is recommended to use JSON previews, preferably with version comparison support

**Comment by deanmarcussen** [comment]
Hi @giannik the branch is here https://github.com/OrchardCMS/OrchardCore/tree/deanmarcussen/audittrail-historyview

Yes, I think we will want it, what I'd quite like it to be able to do is integrate with audit trail (when it is enabled)

Audit trail tracks the events that occur, at the time they occur, where the content item version table, has a little more limited view , because it is sometimes (when editing drafts, or publishing etc) only changes the modified time.

Quite busy at the moment, so super happy if you want to take the branch over and make it work :)

**Comment by Piedone** [comment]
What's really the feature request here, can you elaborate?
