### ISSUE TITLE
Layout files trouble

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#993]
I have a theme and module in a same project (has module.txt and theme.txt).  

I have a `Views/Layout.cshtml ` for content items.

Then I have some controller actions.  Some use the layout, some don't and some needs another layout.  So the troubles are as below:

* In a controller view file, e.g., if I assigned it to the same layout like
`Layout = "../Layout.cshtml"`
I needed to use relative path (see following bullet), I got:
`InvalidOperationException: RenderBody has not been called for the page`

* I could not `Layout = "~/Views/Layout.cshtml"`, `~` didn't get expanded.
`InvalidOperationException: The layout view '~/Views/Layout.cshtml' could not be located`

* Then I copied Views/Layout.cshtml to Views/Shared/Layout.cshtml.  
Reference by Layout = "Layout".  I still got except same as first bullet.
`InvalidOperationException: RenderBody has not been called for the page`

* Then I changed `RenderBodyAsync` to `RenderBody`, then it worked.

* Then I went back to `Layout = "../Layout.cshtml"` and removed all `RenderSectionAsync` and changed `RenderBodyAsync` to `RenderBody`.  It worked too.

So there are two issues here.  `~` not expanded and `RenderBodyAsync` was not working in custom controller layout view.  I am not sure whether it is MVC or Orchard, or I missed something...

Thanks!

Edit:
Include a sample project that demonstrate the issues: [RenderBodyA.zip](https://github.com/OrchardCMS/OrchardCore/files/1297868/RenderBodyA.zip)
u: admin p: Qwert123$

1) http://localhost:2918/RenderBodyAsync --> Exception RenderBody has not been called
2) http://localhost:2918/RenderBody --> works fine.
3) http://localhost:2918/Tilda --> Exception The layout view '~/Views/Layout.cshtml' could not be located

**Comment by sebastienros** [comment]
You can't have a theme and a module in the same project. We never even imagined how we could support that.

**Comment by sebastienros** [comment]
You issue might not be related to it though.

**Comment by awyl** [comment]
I am just lazy, so I tried, but it works so far.  I will split them when I have to.

**Comment by jtkech** [comment]
Normally, you just need a theme in which you can add other features that you can enable / disable as in any other module. But interesting.

We would need to have the exact distribution of your views, so here just some infos.

- When a theme is enabled and selected, a module controller view is first searched in `Theme/Views/Module/Controller/View.cshtml`. Then in `Module/Views/Controller/View.cshtml`.

- Anyway, we have a filter to not use a theme aware view location for the selected theme itself. So if your module is also the selected theme, then i think it only search in `ModuleTheme/Views/Controller/`.

- Normally, we don't have to do anything to get the layout, see in our `ThemeViewStart.cs` where we do

      Layout = "~/Views/Shared/_Layout" + RazorViewEngine.ViewExtension;

- Then the above trigger the execution of the following (see in our `ThemeLayout.cs`)

      var body = RenderLayoutBody();
      this.ThemeLayout.Content.Add(body);
      Write(await DisplayAsync(ThemeLayout));

- `RenderBodyAsync()` and `RenderSectionAsync()` are defined in our custom `RazorPage` (see in RazorPage.cs) so to use it you need to have a `_ViewImports` which includes `@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>`. Or put the directive in the view.

**Comment by awyl** [comment]
@jtkech Thanks for your reply.  I already have the _ViewImports setup correctly as earlier by the help of Sebastien.

I have edited the first post to include a sample project to demonstrate the problem.

**Comment by jtkech** [comment]
- When overriding the layout, eg:

      Layout = "../Layout.cshtml";

- I think you are not executing our custom precompiled view in `ThemeLayout.cs` which do:

            var body = RenderLayoutBody();
            this.ThemeLayout.Content.Add(body);
            Write(await DisplayAsync(ThemeLayout));

- And see in our `RazorPage.cs` what do `RenderLayoutBody()`:

            var result = base.RenderBody();
            return result;

- So, you need to call `RenderBody()` yourself in your custom layout, this before trying to display any partial view. Otherwise razor will fail.

- Note: `RenderBodyAsync()` displays a partial view by doing `DisplayAsync(ThemeLayout.Content)`, see in our `RazorPage.cs`. So, it fails if `RenderBody()` has not be called before. And this is not what you want to render when you don't want to use the theme layout.

**Comment by awyl** [comment]
Hmm... so I want a custom layout nested in the theme layout, and the custom layout will be used by the a controller action like in the sample project.

How do I call these RenderBody() on the theme layout, so that I don't have to duplicate the theme layout and change that call?

**Comment by jtkech** [comment]
1. If you want to use the layout of the selected theme just do nothing.

2. If you just want to display the controller view without layout, try to do.

        @{ 
              Layout = null;
        }

3. If you want to use another layout, specify another path or a partial name (without extension) then it will search in the controller folder then in the shared folder. For the path, as i remember `../` works but `~/` doesn't. Then, in this layout you need to call `RenderBody()` to render the content of your controller view. Here, because we don't use the regular theme layout pattern, you can't call `RenderBodyAsync()`.

For 1. if you want your theme be the selected one, you not only need to enable it but also select it through the admin UI as the current theme. Not sure that now we can enable a theme which is not already enabled by the setup recipe. I remember it was not the case at some point, and i didn't try it again.

**Comment by awyl** [comment]
Thanks.  But that's not what I am trying to achieve.  I wanted to have a nested layout.  Something like,
`controller view -> controller layout -> theme layout`

**Comment by awyl** [comment]
Any idea why the stylesheets defined in ControllerLayout is not showing?

like e.g.,
```
<link rel="stylesheet" type="text/css" asp-append-version="true"
      asp-src="/styles/footer.min.css" />
```

**Comment by jtkech** [comment]
- First, your style file need to be under `YourModule/Contents/Styles/...` folder.

- Then, to get it working from a partial view you need to have `<resources type="Stylesheet" />` as in `Layout.cshtml` of our `TheTheme` theme.

- So, you need it in the `head` section of the `Layout.cshtml` of the selected theme.

- For other infos take a look to [this video](https://channel9.msdn.com/Shows/Code-Conversations/Sebastien-Ros-on-ASPNET-Core-MVC-Resource-Management?ocid=player)

**Comment by awyl** [comment]
Thanks.  I have watched it sometimes ago.

The resources tags are already in Layout.cshtml.  My content items works perfectly.
```
@{
    var body = RenderLayoutBody();
    this.ThemeLayout.Content.Add(body);
    this.ThemeLayout.Content.Metadata.Wrappers.Add("ControllerLayout");
    Write(await DisplayAsync(ThemeLayout));
}
```
I followed your suggestion above.  It works, the contents shows.  However in `ControllerLayout` the `link` tags are missing.  `Script` tags `at="Foot"` are fine though.

**Comment by jtkech** [comment]
Oh, in place of using a `<link>` tag here you need to use a `<style asp-src=...>` tag.

This to trigger the `StyleTagHelper` defined in `OrchardCore.ResourceManagement.TagHelpers`.

**Comment by awyl** [comment]
Mmm... same, still doesn't work after I change to `<style>`.

I then tried to move around the `<resources>`.  I found that if I move them after `@await RenderBodyAsync`.   `<style>` appear.

Is it a bug?

**Comment by jtkech** [comment]
- Just tried, you're right, it doesn't work in the wrapper.

- And `<style>` in the controller view works.

- With the debugger i can see that the style taghelper is executed too late with `RenderBodyAsync()`.

- When i will have time, i will try to find way to overcome this.

**Comment by jtkech** [comment]
So, indeed in `ThemeLayout.cshtml` one solution would be to call `DisplayAsync` on a `ControllerLayout` shape just to register `style` tags before `RenderLayoutBody`.

Indeed, if we first display the `ControllerLayout` shape for nothing (without items) but just to register `style` tags before `RenderLayoutBody`, then it works.

    @{
        await DisplayAsync(New.ControllerLayout());
        var body = RenderLayoutBody();
        this.ThemeLayout.Content.Add(body);
        this.ThemeLayout.Content.Metadata.Wrappers.Add("ControllerLayout");
        Write(await DisplayAsync(ThemeLayout));
    }

But this is not good because e.g a `script` tag would be registered twice.

So, what i suggest is to have a `ControllerLayout.cshtml` for your custom nested layout but without any resource tags. And also have a `ControllerResources.cshtml` where you put your additional resources as.

    <style asp-src="foo.css"></style>

Then, in `ThemeLayout.cshtml`.

    @{
        await DisplayAsync(New.ControllerResources());
        var body = RenderLayoutBody();
        this.ThemeLayout.Content.Add(body);
        this.ThemeLayout.Content.Metadata.Wrappers.Add("ControllerLayout");
        Write(await DisplayAsync(ThemeLayout));
    }

**Comment by ns8482e** [comment]
> * Just tried, you're right, it doesn't work in the wrapper.

As Layout is rendered before any Zones defined in layout, styles defined on wrappers of zones will not register to ResourceManager

related #3947
