### ISSUE TITLE
Enabling/Disabling features perf investigation

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#998]
Enabling and disabling a feature used to take something like 100ms from the features page. Today I noticed it would take multiple seconds. This is a huge regression that should be looked into.

**Comment by Jetski5822** [comment]
I've noticed the same locally

**Comment by sebastienros** [comment]
@jtkech could it be file system access since we are looking in many more places than before for views? 

Maybe we should try to just comment out some of this stuff to narrow it down.

**Comment by jtkech** [comment]
Ok, i will try it by disabling some of them step by step

**Comment by jtkech** [comment]
- So, on my side it takes about 2s to enable / disable `O.Demo`.

- 1st test, i removed `AddModularRazorPages()` => idem.

- 2nd test, i also removed `ModuleProjectRazorFileProvider` => idem.

- 3rd test, i also removed `ModuleProjectLiquidFileProvider` => idem.

**Comment by sebastienros** [comment]
Good ;) this is not it then

A scientific approach would be to use a profiler.

**Comment by sebastienros** [comment]
I suspect the same thing will also impact setup times.

**Comment by jtkech** [comment]
And when a tenant is restarted.

I don't remember well but maybe i have an idea. 

- When i first go and directly to the features page it's quite the same even more.

- So it's like that before a given view was compiled once even if we restart a tenant, but not now

- So, i'm thinking about our old shared compiler cache accross tenant.

- Now we have a `SharedViewCompilerProvider` that shares precompiled views but just saw that it doesn't share the `RazorViewCompiler`. Normal because this one embeds e.g a razor fileprovider which is a tenant service and which may differ between 2 tenants according to the razor options we use.

- But it also embeds a `IMemoryCache`. So, we have one `RazorViewCompiler` per tenant and with its own `MemoryCache`. So, we only share precompiled views accross tenants. It seems that we don't share accross tenants compiled views which are compiled at runtime.

I will try just for testing to use only one `RazorViewCompiler` even if it looks bad regarding services scopes.

**Comment by sebastienros** [comment]
Probably, we need to fix this.

**Comment by jtkech** [comment]
So, by using the same `RazorViewCompiler` it takes 300ms to enable/disable `O.Demo`.

**Comment by jtkech** [comment]
One problem i see is that the composite razor file provider embeds some of our file providers which are tenant services. So maybe we would need to move them at the app level. And also the razor file provider itself, i don't know.

At least we see where is the issue, need to think about this ...

**Comment by sebastienros** [comment]
I can remember there was a notion of ICompilerCache before, it's gone?

**Comment by jtkech** [comment]
Yes with 2.0, now it is embedded in the razor compiler

**Comment by jtkech** [comment]
I think we need to create a razor compiler at the app level (makes sense) and with the related services it uses

**Comment by sebastienros** [comment]
not sure it makes sense, can't we just assign compiled type with our own cache like it's done for precompiled views? ... skype
