### ISSUE TITLE
CMS take too much memory

### ISSUE THREAD

**Issue by hoanghai1212** [OrchardCMS/OrchardCore#9998]
### Describe the bug
I published release version of CMS and deploy to my EC2, every still okay but today when I checking my EC2 status, I see Orchard take too much memory as an web application. (over 700mb).

### Screenshots
![image](https://user-images.githubusercontent.com/57449818/127457375-decffd7a-26cc-4b86-94e4-c4fb7ed346df.png)

This is normal or something not going right ?

**Comment by deanmarcussen** [comment]
Is it possible you are using the app in `Development` mode?

Please check your deployed `ASPNETCORE_ENVIRONMENT` variable.

Also please provide the version of Orchard Core you are using

**Comment by hoanghai1212** [comment]
> Please check your deployed `ASPNETCORE_ENVIRONMENT` variable.
>> I don't found an variable with that name in my publish folder. 
> Also please provide the version of Orchard Core you are using
>> I use latest version 1.0.0

**Comment by deanmarcussen** [comment]
> Is it possible you are using the app in `Development` mode?
> 
> Please check your deployed `ASPNETCORE_ENVIRONMENT` variable.

Try logging the `ASPNETCORE_ENVIRONMENT` in a Layout view or something. It is pretty common for people to use the `Development` environment variable and run into issues like this. Try setting it specifically to `Production`

**Comment by hoanghai1212** [comment]
> Production

Okay I'll try this

**Comment by Skrypt** [comment]
Should be normally around 300 mb from fresh install of a single tenant.

**Comment by sebastienros** [comment]
It also depends on the amount of memory your server has. If the total is 1GB there could be a problem. If it's 16GB it's might actually be normal, the GC not freeing the memory because it doesn't have to.

**Comment by hoanghai1212** [comment]
I redeploy latest version and it take around 300Mb like Skrypt mention before, today I check it again it take 450Mb, maybe it's take more memory by the time. 
My server only have 2gb of RAM. I use ec2 ubuntu 20.04 by the way

**Comment by FinnurHrafn** [comment]
I am running the Docker Hub Linux v1.0.0/Latest image on Azure App Service which returns normally less than 300 MB of memory:
![image](https://user-images.githubusercontent.com/12381011/127935934-44ba1759-38c8-4ccc-8c40-82f31455aabf.png)

**Comment by FinnurHrafn** [comment]
Docker Desktop on my local machine reports 700-800 MB so I am not sure what gives:
![image](https://user-images.githubusercontent.com/12381011/127936090-1879faf4-d958-48d2-85cb-c7b56ce8f897.png)

**Comment by hoanghai1212** [comment]
after few day it's take more memory again.
![image](https://user-images.githubusercontent.com/57449818/128164406-1d3c20c1-5112-4dd3-9bc7-193aa63858ba.png)

**Comment by Skrypt** [comment]
Like Sebastien said, the memory is probably not disposed by the garbage collector because it doesn't need to. Over time, some operations on the website could cause the memory usage to go up. The question is : does it make your Docker container unusable or not? If you limit your container to 2 gb it can use it all if it requires to. If it starts to slow down because it seems to require more than the limit then it's because the website does something that requires it. What you should try to know then is : what makes the memory usage goes up and also "when".

**Comment by hoanghai1212** [comment]
For now I'm not using Docker to run my Orchard anymore I just run it directly in my ec2 as an system service. It not slowing down my website although it take a lot of memory. Everything still ok for now but I'm not sure in the future so my solution is setting a crontab job to restart my Orchard service every day.

**Comment by Skrypt** [comment]
I'm using an Azure App and it sits at around 700 mb. Never had an issue and never needed to reboot the website periodically. Maybe, that's just how much memory it reserves for OC to run. I'd feel concerned if it was making the application crash because the memory would grow and require to use disk swapping to run. But, else, it just takes more ram because it can ...

**Comment by Piedone** [comment]
Since then, we've fixed multiple memory leaks and optimized memory usage a lot. Please open a new issue with specifics if the problem persists.

**Comment by sebastienros** [comment]
There is a new GC mode in .NET 8.0 that should be tested, by setting this ENV: `DOTNET_GCDynamicAdaptationMode=1`

This should improve the overall memory usage while not impacting the perf visibly.

**Comment by Piedone** [comment]
Interesting, thanks for the tip, we'll try this!
